[package]
name = "destack_napi"
description = "N-API bindings for Destack"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
readme = "README.md"
repository = "https://github.com/destack-sh/destack"
homepage = "https://github.com/destack-sh/destack"
documentation = "https://docs.rs/destack_napi"
keywords = ["destack", "napi", "node", "bindings"]
categories = ["api-bindings", "development-tools"]

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
doctest = false

[dependencies]
destack_bridge_language.workspace = true
destack_compiler.workspace = true
destack_linter.workspace = true
destack_query.workspace = true
destack_repository.workspace = true
destack_session.workspace = true
destack_source.workspace = true
napi = { version = "3", features = ["napi8"] }
napi-derive = "3"

[lints]
workspace = true

[package.metadata.napi]
name = "destack-language-napi"
features = ["napi8"]
