[package]
name = "dyst_json_fuzz"
description = "Dyst JSON Fuzz"
edition = "2024"
authors = ["Symbol Industries"]
license = "proprietary"
rust-version = "1.88.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
dyst_json = { path = ".." }

arbitrary = { version = "1.4.2", features = ["derive"] }
libfuzzer-sys = "0.4.10"

[[bin]]
name = "dyst_json_fuzz"
path = "fuzz_targets/json.rs"
test = false
doc = false
