[package]
name = "tspp_lsp"
description = "TS++ Language Server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "tspp_lsp"
path = "src/main.rs"

[dependencies]
# language
tspp_artifact = { workspace = true }
tspp_compiler = { workspace = true, features = ["native"] }
tspp_core = { workspace = true }
tspp_dir = { workspace = true }
tspp_fir = { workspace = true }
tspp_formatter = { workspace = true }
tspp_query = { workspace = true }
tspp_session = { workspace = true, features = ["native"] }
tspp_repository = { workspace = true }
tspp_lsp_server = { workspace = true }
tspp_lsp_types = { workspace = true }
tspp_parser = { workspace = true }
tspp_source = { workspace = true }
tspp_serde = { workspace = true }
tspp_workspace = { workspace = true }

# general
base64 = { workspace = true }
libc = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = [
	"macros",
	"rt-multi-thread",
	"io-std",
	"sync",
	"time",
] }

[dev-dependencies]
futures = { workspace = true }
tower = { workspace = true }
