[package]
name = "destack_lsp"
description = "Destack Language Server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
test = ["dep:futures", "dep:tower"]

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "destack_lsp"
path = "src/main.rs"

[dependencies]
# language
destack_artifact = { workspace = true }
destack_compiler = { workspace = true }
destack_core = { workspace = true }
destack_dir = { workspace = true }
destack_fir = { workspace = true }
destack_formatter = { workspace = true }
destack_query = { workspace = true }
destack_session = { workspace = true }
destack_workspace = { workspace = true }
destack_lsp_server = { workspace = true }
destack_lsp_types = { workspace = true }
destack_parser = { workspace = true }
destack_source = { workspace = true }
destack_service = { workspace = true }

# general
dashmap = { workspace = true }
libc = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = [
	"macros",
	"rt-multi-thread",
	"io-std",
	"sync",
	"time",
] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
futures = { workspace = true, default-features = false, features = ["std", "async-await"], optional = true }
tower = { workspace = true, default-features = false, features = ["util"], optional = true }

[dev-dependencies]
futures = { workspace = true, default-features = false, features = ["std", "async-await"] }
tower = { workspace = true, default-features = false, features = ["util"] }
