[package]
name = "destack_rust"
description = "Destack Rust Extension"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"
doctest = false

[dependencies]
dyst_ast = { workspace = true }
dyst_fir = { workspace = true }
dyst_session = { workspace = true }
dyst_source = { workspace = true }
dyst_prelude = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
