[package]
name = "dyst_javascript_ast"
description = "Dyst JavaScript AST"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"
doctest = false

[dependencies]
dyst_source = { workspace = true }

destack_unicode = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
