[workspace]
# fuzzer is in its own workspace

[package]
name = "destack_time_fuzz"
description = "Destack Time Fuzz"
edition = "2024"
authors = ["Symbol Industries"]
license = "proprietary"
rust-version = "1.88.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
destack_time = { path = ".." }

arbitrary = { version = "1.4.2", features = ["derive"] }
libfuzzer-sys = "0.4.10"

[[bin]]
name = "destack_time_fuzz"
path = "fuzz_targets/time.rs"
test = false
doc = false

[[bin]]
name = "destack_date_fuzz"
path = "fuzz_targets/date.rs"
test = false
doc = false

[[bin]]
name = "destack_datetime_fuzz"
path = "fuzz_targets/datetime.rs"
test = false
doc = false

[[bin]]
name = "destack_duration_fuzz"
path = "fuzz_targets/duration.rs"
test = false
doc = false

[[bin]]
name = "destack_timestamp_fuzz"
path = "fuzz_targets/timestamp.rs"
test = false
doc = false
