[package]
name = "destack_service"
description = "Destack Service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_compiler = { path = "../compiler", default-features = false }
destack_query = { workspace = true }
destack_resolver = { workspace = true }
destack_source = { workspace = true }
destack_workspace = { path = "../workspace", default-features = false }

# general
dashmap = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[features]
default = ["full"]
parallel = ["destack_compiler/parallel"]
native-codegen = ["destack_compiler/native-codegen"]
deadlock-detection = ["destack_compiler/deadlock-detection"]
lint = ["destack_compiler/lint"]
optimize = ["destack_compiler/optimize"]
builtin-full = ["destack_compiler/builtin-full", "destack_workspace/builtin-full"]
builtin-core = [
    "destack_compiler/builtin-core",
    "destack_workspace/builtin-core",
]
full = [
    "parallel",
    "native-codegen",
    "deadlock-detection",
    "lint",
    "optimize",
    "builtin-full",
]
core = ["builtin-core"]

[lints]
workspace = true
