[package]
name = "destack_python"
description = "Python bindings support crate for Destack"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
readme = "../README.md"
repository = "https://github.com/destack-sh/destack"
homepage = "https://github.com/destack-sh/destack"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
doctest = false

[dependencies]
destack.workspace = true
destack_bridge_language.workspace = true
pyo3 = { workspace = true, features = ["extension-module"] }

[lints]
workspace = true
