[package]
name = "destack_macros"
description = "Destack Macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]

[dev-dependencies]
quickcheck = "1"
quickcheck_macros = "1"

[lints]
workspace = true
