/* generated by scripts/generate.mjs, do not edit */

import type * as Napi from "@destack/language-napi";

/** Immutable source revision. */
export type Revision = Napi.Revision;

/** One source file in an explicit source snapshot. */
export type SourceFile = Napi.SourceFile;

/** Source truth used to open a live session. */
export type SourceSnapshot = Napi.SourceSnapshot;

/** Source text range in byte offsets. */
export type TextRange = Napi.TextRange;

/** Source text replacement. */
export type TextEdit = Napi.TextEdit;

/** One source edit accepted by a session update. */
export type SourceEdit = Napi.SourceEdit;

/** Source update applied through one live session. */
export type SourceUpdate = Napi.SourceUpdate;

/** File update projected from a source update. */
export type FileUpdate = Napi.FileUpdate;

/** Source update result. */
export type SourceUpdateResult = Napi.SourceUpdateResult;
