[package]
name = "destack_linter"
description = "Destack Linter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
destack_artifact = { workspace = true }
destack_ast = { workspace = true }
destack_core = { workspace = true }
destack_dir = { workspace = true }
destack_linter_macros = { workspace = true }
destack_mir = { workspace = true }
destack_parser = { workspace = true }
destack_source = { workspace = true }
destack_workspace = { path = "../workspace", default-features = false }

# general
aho-corasick = { workspace = true }
indexmap = { workspace = true }
parking_lot = { workspace = true }
regex = { workspace = true }
regex-syntax = { workspace = true }
toml = { workspace = true }
url = { workspace = true }

[dev-dependencies]
clap = { workspace = true }
destack_compiler = { workspace = true }
destack_fir = { workspace = true }
destack_formatter = { workspace = true }
destack_session = { workspace = true }

[lints]
workspace = true
