[package]
name = "tspp_linter"
description = "TS++ Linter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
tspp_artifact = { workspace = true }
tspp_artifact_macros = { workspace = true }
tspp_core = { workspace = true }
tspp_dir = { workspace = true }
tspp_mir = { workspace = true }
tspp_source = { workspace = true }
tspp_unicode = { workspace = true }
tspp_repository = { path = "../repository", default-features = false }

[dev-dependencies]
# language
tspp_session = { workspace = true, features = ["native"] }

# general
futures = { workspace = true, features = ["executor"] }

[lints]
workspace = true
