[package]
name = "destack_linter"
description = "Destack Linter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
destack_ast = { workspace = true }
destack_base = { workspace = true }
destack_dir = { workspace = true }
destack_linter_macros = { workspace = true }
destack_mir = { workspace = true }
destack_parser = { workspace = true }
destack_source = { workspace = true }
destack_workspace = { workspace = true }

# general
indexmap = { workspace = true }
parking_lot = { workspace = true }
regex = { workspace = true }
regex-syntax = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
destack_compiler = { workspace = true }
destack_fir = { workspace = true }
destack_formatter = { workspace = true }

[lints]
workspace = true
