/* eslint-disable */
// @generated by protobuf-ts 2.11.0
// @generated from protobuf file "destack-proto/universe.proto" (package "symbol.destack", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Universe } from "./universe";
import type { ResolveSpacesResponse } from "./universe";
import type { ResolveSpacesRequest } from "./universe";
import type { LogoutUserResponse } from "./universe";
import type { LogoutUserRequest } from "./universe";
import type { LoginUserResponse } from "./universe";
import type { LoginUserRequest } from "./universe";
import type { ChangeUserPasswordResponse } from "./universe";
import type { ChangeUserPasswordRequest } from "./universe";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SignupUserResponse } from "./universe";
import type { SignupUserRequest } from "./universe";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service symbol.destack.Universe
 */
export interface IUniverseClient {
    /**
     * Create User.
     *
     * @generated from protobuf rpc: SignupUser
     */
    signupUser(input: SignupUserRequest, options?: RpcOptions): UnaryCall<SignupUserRequest, SignupUserResponse>;
    /**
     * Change User.password.
     *
     * @generated from protobuf rpc: ChangeUserPassword
     */
    changeUserPassword(input: ChangeUserPasswordRequest, options?: RpcOptions): UnaryCall<ChangeUserPasswordRequest, ChangeUserPasswordResponse>;
    /**
     * Login User with a new or existing Client.
     *
     * @generated from protobuf rpc: LoginUser
     */
    loginUser(input: LoginUserRequest, options?: RpcOptions): UnaryCall<LoginUserRequest, LoginUserResponse>;
    /**
     * Logout User with the current or other owned Clients.
     *
     * @generated from protobuf rpc: LogoutUser
     */
    logoutUser(input: LogoutUserRequest, options?: RpcOptions): UnaryCall<LogoutUserRequest, LogoutUserResponse>;
    /**
     * Gets Space space information.
     *
     * @generated from protobuf rpc: ResolveSpaces
     */
    resolveSpaces(input: ResolveSpacesRequest, options?: RpcOptions): UnaryCall<ResolveSpacesRequest, ResolveSpacesResponse>;
}
/**
 * @generated from protobuf service symbol.destack.Universe
 */
export class UniverseClient implements IUniverseClient, ServiceInfo {
    typeName = Universe.typeName;
    methods = Universe.methods;
    options = Universe.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Create User.
     *
     * @generated from protobuf rpc: SignupUser
     */
    signupUser(input: SignupUserRequest, options?: RpcOptions): UnaryCall<SignupUserRequest, SignupUserResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignupUserRequest, SignupUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Change User.password.
     *
     * @generated from protobuf rpc: ChangeUserPassword
     */
    changeUserPassword(input: ChangeUserPasswordRequest, options?: RpcOptions): UnaryCall<ChangeUserPasswordRequest, ChangeUserPasswordResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChangeUserPasswordRequest, ChangeUserPasswordResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Login User with a new or existing Client.
     *
     * @generated from protobuf rpc: LoginUser
     */
    loginUser(input: LoginUserRequest, options?: RpcOptions): UnaryCall<LoginUserRequest, LoginUserResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginUserRequest, LoginUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Logout User with the current or other owned Clients.
     *
     * @generated from protobuf rpc: LogoutUser
     */
    logoutUser(input: LogoutUserRequest, options?: RpcOptions): UnaryCall<LogoutUserRequest, LogoutUserResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutUserRequest, LogoutUserResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Gets Space space information.
     *
     * @generated from protobuf rpc: ResolveSpaces
     */
    resolveSpaces(input: ResolveSpacesRequest, options?: RpcOptions): UnaryCall<ResolveSpacesRequest, ResolveSpacesResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ResolveSpacesRequest, ResolveSpacesResponse>("unary", this._transport, method, opt, input);
    }
}
