// generated by generate-bindings: do not edit

#include "../types.h"
#include "../jni.h"
#include "../loader.h"
#include "callbacks.generated.h"
#include "runtime.generated.h"

#include <deque>
#include <string>
#include <vector>

namespace {

/// Convert one host status code into one runtime status.
RuntimeStatus runtime_status_from_code(uint32_t code) {
    RuntimeStatus status = {
        .code = code,
        .error_id = 0,
    };

    return status;
}

}

/// Forward the `adapter_list` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_adapter_list_for_session(
    uint64_t session_handle,
    AndroidHostBluetoothAdapterDescriptorHeaderSlice adapters,
    uint32_t *adapter_count_written,
    NativeU8Slice string_bytes,
    uint32_t *string_bytes_written
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_adapter_list(env, session_handle, adapters, adapter_count_written, string_bytes, string_bytes_written);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `scan_open` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_scan_open_for_session(
    uint64_t session_handle,
    NativeStringRef adapter_id,
    AndroidHostBluetoothScanFilterHeader filter,
    uint32_t filter_flags,
    NativeU8Slice filter_bytes,
    uint64_t *session_id
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_scan_open(env, session_handle, adapter_id, filter, filter_flags, filter_bytes, session_id);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `scan_close` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_scan_close_for_session(
    uint64_t session_handle,
    uint64_t session_id
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_scan_close(env, session_handle, session_id);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `scan_read` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_scan_read_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    uint64_t timeout_ns,
    AndroidHostBluetoothDeviceDescriptorHeaderSlice devices,
    uint32_t *device_count_written,
    NativeU8Slice string_bytes,
    uint32_t *string_bytes_written
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_scan_read(env, session_handle, session_id, timeout_ns, devices, device_count_written, string_bytes, string_bytes_written);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `scan_try_read` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_scan_try_read_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    AndroidHostBluetoothDeviceDescriptorHeaderSlice devices,
    uint32_t *device_count_written,
    NativeU8Slice string_bytes,
    uint32_t *string_bytes_written
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_scan_try_read(env, session_handle, session_id, devices, device_count_written, string_bytes, string_bytes_written);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `scan_read_event` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_scan_read_event_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    uint64_t timeout_ns,
    AndroidHostBluetoothScanEventHeader *event,
    NativeU8Slice string_bytes,
    uint32_t *string_bytes_written
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_scan_read_event(env, session_handle, session_id, timeout_ns, event, string_bytes, string_bytes_written);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `scan_try_read_event` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_scan_try_read_event_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    AndroidHostBluetoothScanEventHeader *event,
    NativeU8Slice string_bytes,
    uint32_t *string_bytes_written
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_scan_try_read_event(env, session_handle, session_id, event, string_bytes, string_bytes_written);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `open` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_open_for_session(
    uint64_t session_handle,
    NativeStringRef adapter_id,
    NativeStringRef device_id,
    uint64_t *session_id,
    AndroidHostBluetoothDeviceDescriptorHeader *descriptor,
    NativeU8Slice string_bytes,
    uint32_t *string_bytes_written
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_open(env, session_handle, adapter_id, device_id, session_id, descriptor, string_bytes, string_bytes_written);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `close` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_close_for_session(
    uint64_t session_handle,
    uint64_t session_id
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_close(env, session_handle, session_id);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `pair` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_pair_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    uint64_t timeout_ns
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_pair(env, session_handle, session_id, timeout_ns);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `unpair` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_unpair_for_session(
    uint64_t session_handle,
    NativeStringRef adapter_id,
    NativeStringRef device_id
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_unpair(env, session_handle, adapter_id, device_id);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `read_rssi` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_read_rssi_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    uint64_t timeout_ns,
    int16_t *rssi_dbm
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_read_rssi(env, session_handle, session_id, timeout_ns, rssi_dbm);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `session_read_event` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_session_read_event_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    uint64_t timeout_ns,
    AndroidHostBluetoothSessionEventHeader *event
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_session_read_event(env, session_handle, session_id, timeout_ns, event);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `session_try_read_event` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_session_try_read_event_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    AndroidHostBluetoothSessionEventHeader *event
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_session_try_read_event(env, session_handle, session_id, event);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_service_list` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_service_list_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    AndroidHostBluetoothGattServiceHeaderSlice services,
    uint32_t *service_count_written,
    NativeU8Slice string_bytes,
    uint32_t *string_bytes_written
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_service_list(env, session_handle, session_id, services, service_count_written, string_bytes, string_bytes_written);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_characteristic_list` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_characteristic_list_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    NativeStringRef service_id,
    AndroidHostBluetoothGattCharacteristicHeaderSlice characteristics,
    uint32_t *characteristic_count_written,
    NativeU8Slice string_bytes,
    uint32_t *string_bytes_written
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_characteristic_list(env, session_handle, session_id, service_id, characteristics, characteristic_count_written, string_bytes, string_bytes_written);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_descriptor_list` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_descriptor_list_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    NativeStringRef characteristic_id,
    AndroidHostBluetoothGattDescriptorHeaderSlice descriptors,
    uint32_t *descriptor_count_written,
    NativeU8Slice string_bytes,
    uint32_t *string_bytes_written
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_descriptor_list(env, session_handle, session_id, characteristic_id, descriptors, descriptor_count_written, string_bytes, string_bytes_written);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_mtu` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_mtu_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    uint16_t *mtu
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_mtu(env, session_handle, session_id, mtu);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_read` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_read_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    NativeStringRef characteristic_id,
    uint64_t timeout_ns,
    NativeU8Slice bytes,
    uint32_t *bytes_written
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_read(env, session_handle, session_id, characteristic_id, timeout_ns, bytes, bytes_written);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_read_descriptor` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_read_descriptor_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    NativeStringRef descriptor_id,
    uint64_t timeout_ns,
    NativeU8Slice bytes,
    uint32_t *bytes_written
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_read_descriptor(env, session_handle, session_id, descriptor_id, timeout_ns, bytes, bytes_written);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_write` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_write_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    NativeStringRef characteristic_id,
    uint32_t mode,
    NativeU8Slice value,
    uint64_t timeout_ns
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_write(env, session_handle, session_id, characteristic_id, mode, value, timeout_ns);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_write_descriptor` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_write_descriptor_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    NativeStringRef descriptor_id,
    NativeU8Slice value,
    uint64_t timeout_ns
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_write_descriptor(env, session_handle, session_id, descriptor_id, value, timeout_ns);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_subscribe` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_subscribe_for_session(
    uint64_t session_handle,
    uint64_t session_id,
    NativeStringRef characteristic_id,
    uint64_t *subscription_id
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_subscribe(env, session_handle, session_id, characteristic_id, subscription_id);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_unsubscribe` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_unsubscribe_for_session(
    uint64_t session_handle,
    uint64_t subscription_id
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_unsubscribe(env, session_handle, subscription_id);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_read_event` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_read_event_for_session(
    uint64_t session_handle,
    uint64_t subscription_id,
    uint64_t timeout_ns,
    NativeU8Slice *event,
    uint64_t *timestamp_ns
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_read_event(env, session_handle, subscription_id, timeout_ns, event, timestamp_ns);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Forward the `gatt_try_read_event` bluetooth request through one attached bridge session.
uint32_t call_bluetooth_gatt_try_read_event_for_session(
    uint64_t session_handle,
    uint64_t subscription_id,
    NativeU8Slice *event,
    uint64_t *timestamp_ns
) {
    JNIEnv *env = nullptr;
    bool did_attach_thread = false;

    if (!resolve_jni_env(&env, &did_attach_thread)) {
        return HOST_STATUS_FAILED;
    }

    uint32_t status = call_bluetooth_gatt_try_read_event(env, session_handle, subscription_id, event, timestamp_ns);

    detach_jni_thread(did_attach_thread);

    return status;
}

/// Build one Android host bluetooth callback bundle.
AndroidHostBluetoothCallbacks make_bluetooth_callbacks() {
    return AndroidHostBluetoothCallbacks {
        .adapter_list = call_bluetooth_adapter_list_for_session,
        .scan_open = call_bluetooth_scan_open_for_session,
        .scan_close = call_bluetooth_scan_close_for_session,
        .scan_read = call_bluetooth_scan_read_for_session,
        .scan_try_read = call_bluetooth_scan_try_read_for_session,
        .scan_read_event = call_bluetooth_scan_read_event_for_session,
        .scan_try_read_event = call_bluetooth_scan_try_read_event_for_session,
        .open = call_bluetooth_open_for_session,
        .close = call_bluetooth_close_for_session,
        .pair = call_bluetooth_pair_for_session,
        .unpair = call_bluetooth_unpair_for_session,
        .read_rssi = call_bluetooth_read_rssi_for_session,
        .session_read_event = call_bluetooth_session_read_event_for_session,
        .session_try_read_event = call_bluetooth_session_try_read_event_for_session,
        .gatt_service_list = call_bluetooth_gatt_service_list_for_session,
        .gatt_characteristic_list = call_bluetooth_gatt_characteristic_list_for_session,
        .gatt_descriptor_list = call_bluetooth_gatt_descriptor_list_for_session,
        .gatt_mtu = call_bluetooth_gatt_mtu_for_session,
        .gatt_read = call_bluetooth_gatt_read_for_session,
        .gatt_read_descriptor = call_bluetooth_gatt_read_descriptor_for_session,
        .gatt_write = call_bluetooth_gatt_write_for_session,
        .gatt_write_descriptor = call_bluetooth_gatt_write_descriptor_for_session,
        .gatt_subscribe = call_bluetooth_gatt_subscribe_for_session,
        .gatt_unsubscribe = call_bluetooth_gatt_unsubscribe_for_session,
        .gatt_read_event = call_bluetooth_gatt_read_event_for_session,
        .gatt_try_read_event = call_bluetooth_gatt_try_read_event_for_session,
    };
}
