id = "destack"
name = "Destack"
description = "Destack language and toolchain support."
version = "2026.9.0"
schema_version = 1
authors = ["Florian Cäsar <florian@symbol.industries>"]
repository = "https://github.com/destack-sh/destack"
languages = ["languages/ds", "languages/dsm", "languages/dsa"]

[[capabilities]]
kind = "process:exec"
command = "*"
args = ["--version"]

[[capabilities]]
kind = "download_file"
host = "github.com"
path = ["destack-sh", "destack", "releases", "download", "**"]

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.destack-lsp]
name = "Destack Language Server"
languages = ["Destack"]
language_ids = { Destack = "destack" }

[grammars.destack]
repository = "https://github.com/destack-sh/destack"
rev = "f3e06dd1a7c7cec3f098ae4f9abbcfbf712b6109"
path = "language/grammar/destack/destack"

[grammars.mir]
repository = "https://github.com/destack-sh/destack"
rev = "f3e06dd1a7c7cec3f098ae4f9abbcfbf712b6109"
path = "language/grammar/mir"

[grammars.destack_bytecode]
repository = "https://github.com/destack-sh/destack"
rev = "f3e06dd1a7c7cec3f098ae4f9abbcfbf712b6109"
path = "language/grammar/bytecode"
