id = "tspp"
name = "TS++"
description = "TS++ language and toolchain support."
version = "2026.9.0"
schema_version = 1
authors = ["Florian Cäsar <florian@symbol.industries>"]
repository = "https://github.com/destack-sh/destack"
languages = ["languages/tspp", "languages/tsppm", "languages/tsppa"]

[[capabilities]]
kind = "process:exec"
command = "*"
args = ["--version"]

[[capabilities]]
kind = "download_file"
host = "github.com"
path = ["destack-sh", "tspp", "releases", "download", "**"]

[lib]
kind = "Rust"
version = "0.7.0"

[language_servers.tspp-lsp]
name = "TS++ Language Server"
languages = ["TS++"]
language_ids = { "TS++" = "tspp" }

[grammars.destack]
repository = "https://github.com/destack-sh/destack"
rev = "f3e06dd1a7c7cec3f098ae4f9abbcfbf712b6109"
path = "language/grammar/destack/destack"

[grammars.mir]
repository = "https://github.com/destack-sh/destack"
rev = "f3e06dd1a7c7cec3f098ae4f9abbcfbf712b6109"
path = "language/grammar/mir"

[grammars.destack_bytecode]
repository = "https://github.com/destack-sh/destack"
rev = "f3e06dd1a7c7cec3f098ae4f9abbcfbf712b6109"
path = "language/grammar/bytecode"
