[package]
name = "destack_extension_lsp"
description = "Destack Extension Language Server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"

[[bin]]
name = "destack_extension_lsp"
path = "rust/main.rs"

[dependencies]
dyst_language_ast = { workspace = true }
dyst_language_diagnostic = { workspace = true }
dyst_language_token = { workspace = true }
dyst_language_session = { workspace = true }
dyst_language_source = { workspace = true }
destack_library_file = { workspace = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = [
	"macros",
	"rt-multi-thread",
	"io-std",
	"sync",
] }
tower-lsp-server = "0.22.1"
libc = "0.2.175"
