[package]
name = "destack_cli"
description = "Destack CLI"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
default-run = "destack"

[features]
default = ["dev"]
dev = ["destack_language_cli/dev"]
schema = ["schemars", "destack_language_cli/schema"]

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "destack"
path = "src/bin/destack.rs"

[[bin]]
name = "ds"
path = "src/bin/ds.rs"

[[bin]]
name = "dsc"
path = "src/bin/dsc.rs"

[[bin]]
name = "generate-cli-schema"
path = "src/bin/generate-cli-schema.rs"
required-features = ["schema"]

[dependencies]
# language
destack_language_cli = { workspace = true }

# general
schemars = { workspace = true, optional = true }
serde_json = { workspace = true }

[lints]
workspace = true
