[package]
name = "destack_cli"
description = "Destack CLI"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
default-run = "destack"

[features]
default = ["dev"]
dev = ["tiktoken-rs"]
schema = ["schemars", "destack_daemon/schema"]

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "destack"
path = "src/main.rs"

[[bin]]
name = "ds"
path = "src/bin/ds.rs"

[[bin]]
name = "dsc"
path = "src/bin/dsc.rs"

[[bin]]
name = "dsx"
path = "src/bin/dsx.rs"

[[bin]]
name = "generate-cli-schema"
path = "src/bin/generate-cli-schema.rs"
required-features = ["schema"]

[dependencies]
# language
destack_artifact = { workspace = true }
destack_codegen_js = { workspace = true }
destack_compiler = { workspace = true }
destack_dir = { workspace = true }
destack_engine = { workspace = true }
destack_fir = { workspace = true }
destack_formatter = { workspace = true }
destack_json = { workspace = true }
destack_linter = { workspace = true }
destack_mir = { workspace = true }
destack_parser = { workspace = true }
destack_query = { workspace = true }
destack_workspace = { workspace = true }
destack_runtime = { workspace = true }
destack_session = { workspace = true }
destack_source = { workspace = true }
destack_vm = { workspace = true }

# platform
destack_daemon = { workspace = true }
destack_lsp = { workspace = true }
destack_service = { workspace = true }

# general
clap = { workspace = true, features = ["derive"] }
clap_complete = { workspace = true }
console = { workspace = true }
indicatif = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
schemars = { workspace = true, optional = true }

# dev-only
tiktoken-rs = { workspace = true, optional = true }

[dev-dependencies]

[lints]
workspace = true
