set shell := ["bash", "-cu"]
set windows-shell := ["C:/Program Files/Git/bin/bash.exe", "-cu"]
set dotenv-load := true
set dotenv-filename := "../../.env.local"

_default:
    @just --list --unsorted

# init
init +deployment:
    deno run -A src/main.ts init {{deployment}}

# check
check:
    deno fmt --check src/main.ts src/command src/deployment src/credential
    deno check src/main.ts
    deno run -A src/main.ts check

# format
format:
    deno fmt src/main.ts src/command src/deployment src/credential
    deno run -A src/main.ts format

# diff
diff +deployment:
    deno run -A src/main.ts diff {{deployment}}

# deploy
deploy +deployment:
    deno run -A src/main.ts deploy {{deployment}}
