// generated by generate-bindings: do not edit

#include "../types.h"
#include "../jni.h"
#include "../registry.h"
#include "callbacks.generated.h"

#include <deque>
#include <string>
#include <vector>

namespace {

jclass bridge_class = nullptr;
jmethodID deviceList_method = nullptr;
jmethodID deviceOpen_method = nullptr;
jmethodID deviceClose_method = nullptr;
jmethodID streamConfigList_method = nullptr;
jmethodID streamCapabilityList_method = nullptr;
jmethodID streamOpen_method = nullptr;
jmethodID streamClose_method = nullptr;
jmethodID streamStart_method = nullptr;
jmethodID streamStop_method = nullptr;
jmethodID streamRead_method = nullptr;
jmethodID streamTryRead_method = nullptr;
jmethodID streamTakePhoto_method = nullptr;
jmethodID streamConfig_method = nullptr;
jmethodID streamRecordingCapabilities_method = nullptr;
jmethodID streamStartRecording_method = nullptr;
jmethodID streamPauseRecording_method = nullptr;
jmethodID streamResumeRecording_method = nullptr;
jmethodID streamStopRecording_method = nullptr;
jmethodID streamGetU64_method = nullptr;
jmethodID streamSetU64_method = nullptr;
jmethodID streamGetU32_method = nullptr;
jmethodID streamSetU32_method = nullptr;
jmethodID streamGetF64_method = nullptr;
jmethodID streamSetF64_method = nullptr;
jmethodID streamGetRangeF64_method = nullptr;
jmethodID streamGetRangeU64_method = nullptr;
jmethodID streamGetRangeU32_method = nullptr;

/// Build one JNI string borrowed from one native string reference.
jstring java_string_or_null(JNIEnv *env, NativeStringRef value) {
    if (value.data == nullptr) {
        return nullptr;
    }

    return new_java_string(env, value);
}

jobject box_int(JNIEnv *env, jint value) {
    jclass value_class = env->FindClass("java/lang/Integer");
    if (value_class == nullptr) {
        return nullptr;
    }

    jmethodID constructor = env->GetMethodID(value_class, "<init>", "(I)V");
    if (constructor == nullptr) {
        env->DeleteLocalRef(value_class);
        return nullptr;
    }

    jobject value_object = env->NewObject(value_class, constructor, value);
    env->DeleteLocalRef(value_class);
    return value_object;
}

jobject box_long(JNIEnv *env, jlong value) {
    jclass value_class = env->FindClass("java/lang/Long");
    if (value_class == nullptr) {
        return nullptr;
    }

    jmethodID constructor = env->GetMethodID(value_class, "<init>", "(J)V");
    if (constructor == nullptr) {
        env->DeleteLocalRef(value_class);
        return nullptr;
    }

    jobject value_object = env->NewObject(value_class, constructor, value);
    env->DeleteLocalRef(value_class);
    return value_object;
}

jobject box_boolean(JNIEnv *env, jboolean value) {
    jclass value_class = env->FindClass("java/lang/Boolean");
    if (value_class == nullptr) {
        return nullptr;
    }

    jmethodID constructor = env->GetMethodID(value_class, "<init>", "(Z)V");
    if (constructor == nullptr) {
        env->DeleteLocalRef(value_class);
        return nullptr;
    }

    jobject value_object = env->NewObject(value_class, constructor, value);
    env->DeleteLocalRef(value_class);
    return value_object;
}

jobject box_double(JNIEnv *env, jdouble value) {
    jclass value_class = env->FindClass("java/lang/Double");
    if (value_class == nullptr) {
        return nullptr;
    }

    jmethodID constructor = env->GetMethodID(value_class, "<init>", "(D)V");
    if (constructor == nullptr) {
        env->DeleteLocalRef(value_class);
        return nullptr;
    }

    jobject value_object = env->NewObject(value_class, constructor, value);
    env->DeleteLocalRef(value_class);
    return value_object;
}

jmethodID resolve_constructor(JNIEnv *env, jclass value_class, const char *signature) {
    return env->GetMethodID(value_class, "<init>", signature);
}

thread_local std::deque<std::string> result_string_storage;
thread_local std::deque<std::vector<uint8_t>> result_u8_storage;

void clear_result_decode_storage() {
    result_string_storage.clear();
    result_u8_storage.clear();
}

jint call_list_size(JNIEnv *env, jobject value);
jobject call_list_get(JNIEnv *env, jobject value, jint index);

jint call_int_getter(JNIEnv *env, jobject value, const char *name);

jintArray encode_u8_slice(JNIEnv *env, NativeU8Slice values) {
    jintArray array = env->NewIntArray(static_cast<jsize>(values.len));
    if (array == nullptr) {
        return nullptr;
    }

    std::vector<jint> buffer(static_cast<size_t>(values.len));
    for (uint32_t index = 0; index < values.len; index += 1) {
        buffer[static_cast<size_t>(index)] = static_cast<jint>(values.data[index]);
    }

    env->SetIntArrayRegion(array, 0, static_cast<jsize>(values.len), buffer.data());
    return array;
}

NativeU8Slice decode_u8_list(JNIEnv *env, jobject list) {
    if (list == nullptr) {
        return NativeU8Slice {
            .data = nullptr,
            .len = 0,
        };
    }

    jint size = call_list_size(env, list);
    result_u8_storage.emplace_back();
    auto &storage = result_u8_storage.back();
    storage.reserve(static_cast<size_t>(size));

    for (jint index = 0; index < size; index += 1) {
        jobject value = call_list_get(env, list, index);
        jint resolved = call_int_getter(env, value, "intValue");
        storage.push_back(static_cast<uint8_t>(resolved));
        env->DeleteLocalRef(value);
    }

    return NativeU8Slice {
        .data = storage.data(),
        .len = static_cast<uint32_t>(storage.size()),
    };
}

jobject encode_AndroidHostCameraDeviceDescriptorHeader(JNIEnv *env, AndroidHostCameraDeviceDescriptorHeader value);
jobject encode_AndroidHostCameraStreamConfigHeader(JNIEnv *env, AndroidHostCameraStreamConfigHeader value);
jobject encode_AndroidHostCameraStreamCapabilityHeader(JNIEnv *env, AndroidHostCameraStreamCapabilityHeader value);
jobjectArray encode_AndroidHostCameraDeviceDescriptorHeaderSlice(JNIEnv *env, AndroidHostCameraDeviceDescriptorHeaderSlice value);
jobjectArray encode_AndroidHostCameraStreamConfigHeaderSlice(JNIEnv *env, AndroidHostCameraStreamConfigHeaderSlice value);
jobjectArray encode_AndroidHostCameraStreamCapabilityHeaderSlice(JNIEnv *env, AndroidHostCameraStreamCapabilityHeaderSlice value);

jobject encode_AndroidHostCameraDeviceDescriptorHeader(JNIEnv *env, AndroidHostCameraDeviceDescriptorHeader value) {
    jclass value_class = env->FindClass("dev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraDeviceDescriptorHeader");
    if (value_class == nullptr) {
        return nullptr;
    }

    jmethodID constructor = resolve_constructor(env, value_class, "(IIIIIIIIII)V");
    if (constructor == nullptr) {
        env->DeleteLocalRef(value_class);
        return nullptr;
    }


    jobject result = env->NewObject(
        value_class,
        constructorstatic_cast<jint>(value.id_offset)static_cast<jint>(value.id_len)static_cast<jint>(value.group_id_offset)static_cast<jint>(value.group_id_len)static_cast<jint>(value.name_offset)static_cast<jint>(value.name_len)static_cast<jint>(value.manufacturer_offset)static_cast<jint>(value.manufacturer_len)static_cast<jint>(value.facing_mode)static_cast<jint>(value.depth_capable)
    );

    env->DeleteLocalRef(value_class);

    return result;
}

jobject encode_AndroidHostCameraStreamConfigHeader(JNIEnv *env, AndroidHostCameraStreamConfigHeader value) {
    jclass value_class = env->FindClass("dev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraStreamConfigHeader");
    if (value_class == nullptr) {
        return nullptr;
    }

    jmethodID constructor = resolve_constructor(env, value_class, "(IIIIII)V");
    if (constructor == nullptr) {
        env->DeleteLocalRef(value_class);
        return nullptr;
    }


    jobject result = env->NewObject(
        value_class,
        constructorstatic_cast<jint>(value.width)static_cast<jint>(value.height)static_cast<jint>(value.frame_rate_milli_hz)static_cast<jint>(value.pixel_format)static_cast<jint>(value.pixel_format_family)static_cast<jint>(value.is_compressed)
    );

    env->DeleteLocalRef(value_class);

    return result;
}

jobject encode_AndroidHostCameraStreamCapabilityHeader(JNIEnv *env, AndroidHostCameraStreamCapabilityHeader value) {
    jclass value_class = env->FindClass("dev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraStreamCapabilityHeader");
    if (value_class == nullptr) {
        return nullptr;
    }

    jmethodID constructor = resolve_constructor(env, value_class, "(Ldev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraStreamConfigHeader;IIIIIIIII)V");
    if (constructor == nullptr) {
        env->DeleteLocalRef(value_class);
        return nullptr;
    }

    jobject config_value = encode_AndroidHostCameraStreamConfigHeader(env, value.config);

    jobject result = env->NewObject(
        value_class,
        constructorconfig_valuestatic_cast<jint>(value.minimum_frame_rate_milli_hz)static_cast<jint>(value.maximum_frame_rate_milli_hz)static_cast<jint>(value.color_space_flags)static_cast<jint>(value.dynamic_range_flags)static_cast<jint>(value.exposure_mode_flags)static_cast<jint>(value.white_balance_mode_flags)static_cast<jint>(value.focus_mode_flags)static_cast<jint>(value.stabilization_mode_flags)static_cast<jint>(value.torch_mode_flags)
    );

    if (config_value != nullptr) { env->DeleteLocalRef(config_value); }
    env->DeleteLocalRef(value_class);

    return result;
}

jobjectArray encode_AndroidHostCameraDeviceDescriptorHeaderSlice(JNIEnv *env, AndroidHostCameraDeviceDescriptorHeaderSlice value) {
    jclass element_class = env->FindClass("dev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraDeviceDescriptorHeader");
    if (element_class == nullptr) {
        return nullptr;
    }

    jobjectArray array = env->NewObjectArray(static_cast<jsize>(value.len), element_class, nullptr);
    env->DeleteLocalRef(element_class);
    if (array == nullptr) {
        return nullptr;
    }

    for (uint32_t index = 0; index < value.len; index += 1) {
        jobject element = encode_AndroidHostCameraDeviceDescriptorHeader(env, value.data[index]);
        if (element == nullptr) {
            env->DeleteLocalRef(array);
            return nullptr;
        }

        env->SetObjectArrayElement(array, static_cast<jsize>(index), element);
        env->DeleteLocalRef(element);
    }

    return array;
}

jobjectArray encode_AndroidHostCameraStreamConfigHeaderSlice(JNIEnv *env, AndroidHostCameraStreamConfigHeaderSlice value) {
    jclass element_class = env->FindClass("dev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraStreamConfigHeader");
    if (element_class == nullptr) {
        return nullptr;
    }

    jobjectArray array = env->NewObjectArray(static_cast<jsize>(value.len), element_class, nullptr);
    env->DeleteLocalRef(element_class);
    if (array == nullptr) {
        return nullptr;
    }

    for (uint32_t index = 0; index < value.len; index += 1) {
        jobject element = encode_AndroidHostCameraStreamConfigHeader(env, value.data[index]);
        if (element == nullptr) {
            env->DeleteLocalRef(array);
            return nullptr;
        }

        env->SetObjectArrayElement(array, static_cast<jsize>(index), element);
        env->DeleteLocalRef(element);
    }

    return array;
}

jobjectArray encode_AndroidHostCameraStreamCapabilityHeaderSlice(JNIEnv *env, AndroidHostCameraStreamCapabilityHeaderSlice value) {
    jclass element_class = env->FindClass("dev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraStreamCapabilityHeader");
    if (element_class == nullptr) {
        return nullptr;
    }

    jobjectArray array = env->NewObjectArray(static_cast<jsize>(value.len), element_class, nullptr);
    env->DeleteLocalRef(element_class);
    if (array == nullptr) {
        return nullptr;
    }

    for (uint32_t index = 0; index < value.len; index += 1) {
        jobject element = encode_AndroidHostCameraStreamCapabilityHeader(env, value.data[index]);
        if (element == nullptr) {
            env->DeleteLocalRef(array);
            return nullptr;
        }

        env->SetObjectArrayElement(array, static_cast<jsize>(index), element);
        env->DeleteLocalRef(element);
    }

    return array;
}


AndroidHostCameraFrameHeader decode_AndroidHostCameraFrameHeader(JNIEnv *env, jobject value, std::deque<std::string> *string_storage);
AndroidHostCameraStreamConfigHeader decode_AndroidHostCameraStreamConfigHeader(JNIEnv *env, jobject value, std::deque<std::string> *string_storage);
AndroidHostCameraRecordingCapabilitiesHeader decode_AndroidHostCameraRecordingCapabilitiesHeader(JNIEnv *env, jobject value, std::deque<std::string> *string_storage);

jmethodID resolve_instance_method(
    JNIEnv *env,
    jobject value,
    const char *name,
    const char *signature
) {
    jclass value_class = env->GetObjectClass(value);
    if (value_class == nullptr) {
        return nullptr;
    }

    jmethodID method = env->GetMethodID(value_class, name, signature);
    env->DeleteLocalRef(value_class);

    return method;
}

jobject call_object_getter(
    JNIEnv *env,
    jobject value,
    const char *name,
    const char *signature
) {
    jmethodID method = resolve_instance_method(env, value, name, signature);
    if (method == nullptr) {
        return nullptr;
    }

    return env->CallObjectMethod(value, method);
}

jint call_int_getter(JNIEnv *env, jobject value, const char *name) {
    jmethodID method = resolve_instance_method(env, value, name, "()I");
    return method == nullptr ? 0 : env->CallIntMethod(value, method);
}

jlong call_long_getter(JNIEnv *env, jobject value, const char *name) {
    jmethodID method = resolve_instance_method(env, value, name, "()J");
    return method == nullptr ? 0 : env->CallLongMethod(value, method);
}

jdouble call_double_getter(JNIEnv *env, jobject value, const char *name) {
    jmethodID method = resolve_instance_method(env, value, name, "()D");
    return method == nullptr ? 0.0 : env->CallDoubleMethod(value, method);
}

jboolean call_boolean_getter(JNIEnv *env, jobject value, const char *name) {
    jmethodID method = resolve_instance_method(env, value, name, "()Z");
    return method == nullptr ? JNI_FALSE : env->CallBooleanMethod(value, method);
}

uint64_t decode_boxed_u64(JNIEnv *env, jobject value) {
    jmethodID method = resolve_instance_method(env, value, "longValue", "()J");
    return method == nullptr ? 0 : static_cast<uint64_t>(env->CallLongMethod(value, method));
}

jint call_list_size(JNIEnv *env, jobject value) {
    jmethodID method = resolve_instance_method(env, value, "size", "()I");
    return method == nullptr ? 0 : env->CallIntMethod(value, method);
}

jobject call_list_get(JNIEnv *env, jobject value, jint index) {
    jmethodID method = resolve_instance_method(env, value, "get", "(I)Ljava/lang/Object;");
    return method == nullptr ? nullptr : env->CallObjectMethod(value, method, index);
}

AndroidHostCameraFrameHeader decode_AndroidHostCameraFrameHeader(JNIEnv *env, jobject value, std::deque<std::string> *string_storage) {
    AndroidHostCameraFrameHeader decoded = {};

    decoded.timestamp_ns = static_cast<uint64_t>(call_long_getter(env, value, "getTimestampNs"));

    decoded.sequence = static_cast<uint64_t>(call_long_getter(env, value, "getSequence"));

    decoded.width = static_cast<uint32_t>(call_int_getter(env, value, "getWidth"));

    decoded.height = static_cast<uint32_t>(call_int_getter(env, value, "getHeight"));

    decoded.pixel_format = static_cast<uint32_t>(call_int_getter(env, value, "getPixelFormat"));

    decoded.pixel_format_family = static_cast<uint32_t>(call_int_getter(env, value, "getPixelFormatFamily"));

    decoded.is_compressed = static_cast<uint32_t>(call_int_getter(env, value, "getIsCompressed"));

    decoded.color_space = static_cast<uint32_t>(call_int_getter(env, value, "getColorSpace"));

    decoded.plane_count = static_cast<uint32_t>(call_int_getter(env, value, "getPlaneCount"));

    decoded.bytes_len = static_cast<uint32_t>(call_int_getter(env, value, "getBytesLen"));


    return decoded;
}

AndroidHostCameraStreamConfigHeader decode_AndroidHostCameraStreamConfigHeader(JNIEnv *env, jobject value, std::deque<std::string> *string_storage) {
    AndroidHostCameraStreamConfigHeader decoded = {};

    decoded.width = static_cast<uint32_t>(call_int_getter(env, value, "getWidth"));

    decoded.height = static_cast<uint32_t>(call_int_getter(env, value, "getHeight"));

    decoded.frame_rate_milli_hz = static_cast<uint32_t>(call_int_getter(env, value, "getFrameRateMilliHz"));

    decoded.pixel_format = static_cast<uint32_t>(call_int_getter(env, value, "getPixelFormat"));

    decoded.pixel_format_family = static_cast<uint32_t>(call_int_getter(env, value, "getPixelFormatFamily"));

    decoded.is_compressed = static_cast<uint32_t>(call_int_getter(env, value, "getIsCompressed"));


    return decoded;
}

AndroidHostCameraRecordingCapabilitiesHeader decode_AndroidHostCameraRecordingCapabilitiesHeader(JNIEnv *env, jobject value, std::deque<std::string> *string_storage) {
    AndroidHostCameraRecordingCapabilitiesHeader decoded = {};

    decoded.container_flags = static_cast<uint32_t>(call_int_getter(env, value, "getContainerFlags"));

    decoded.video_codec_flags = static_cast<uint32_t>(call_int_getter(env, value, "getVideoCodecFlags"));

    decoded.audio_supported = static_cast<uint32_t>(call_int_getter(env, value, "getAudioSupported"));

    decoded.audio_codec_flags = static_cast<uint32_t>(call_int_getter(env, value, "getAudioCodecFlags"));

    decoded.pause_supported = static_cast<uint32_t>(call_int_getter(env, value, "getPauseSupported"));

    jobject maximum_video_bit_rate_value = call_object_getter(env, value, "getMaximumVideoBitRate", "()Ljava/lang/Long;");
    decoded.maximum_video_bit_rate = ([&]() -> OptionalU64 { if (maximum_video_bit_rate_value == nullptr) { return { .has_value = false, .value = {} }; } return { .has_value = true, .value = decode_boxed_u64(env, maximum_video_bit_rate_value) }; })();
    if (maximum_video_bit_rate_value != nullptr) { env->DeleteLocalRef(maximum_video_bit_rate_value); }

    jobject maximum_audio_bit_rate_value = call_object_getter(env, value, "getMaximumAudioBitRate", "()Ljava/lang/Long;");
    decoded.maximum_audio_bit_rate = ([&]() -> OptionalU64 { if (maximum_audio_bit_rate_value == nullptr) { return { .has_value = false, .value = {} }; } return { .has_value = true, .value = decode_boxed_u64(env, maximum_audio_bit_rate_value) }; })();
    if (maximum_audio_bit_rate_value != nullptr) { env->DeleteLocalRef(maximum_audio_bit_rate_value); }


    return decoded;
}


/// Resolve the camera bridge methods from one runtime bridge instance.
bool resolve_bridge_methods(JNIEnv *env, jobject bridge) {
    if (bridge_class == nullptr) {
        jclass local_class = env->GetObjectClass(bridge);
        if (local_class == nullptr) {
            return false;
        }

        bridge_class = reinterpret_cast<jclass>(env->NewGlobalRef(local_class));
        env->DeleteLocalRef(local_class);
        if (bridge_class == nullptr) {
            return false;
        }
    }

    if (deviceList_method == nullptr) {
        deviceList_method = env->GetMethodID(
            bridge_class,
            "cameraDeviceList",
            "([Ldev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraDeviceDescriptorHeader;[I)Ldev/destack/runtime/android/bridge/RuntimeHostCameraDeviceListResponse;"
        );
    }

    if (deviceOpen_method == nullptr) {
        deviceOpen_method = env->GetMethodID(
            bridge_class,
            "cameraDeviceOpen",
            "(Ljava/lang/String;)Ldev/destack/runtime/android/bridge/RuntimeHostCameraDeviceOpenResponse;"
        );
    }

    if (deviceClose_method == nullptr) {
        deviceClose_method = env->GetMethodID(
            bridge_class,
            "cameraDeviceClose",
            "(J)I"
        );
    }

    if (streamConfigList_method == nullptr) {
        streamConfigList_method = env->GetMethodID(
            bridge_class,
            "cameraStreamConfigList",
            "(J[Ldev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraStreamConfigHeader;)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamConfigListResponse;"
        );
    }

    if (streamCapabilityList_method == nullptr) {
        streamCapabilityList_method = env->GetMethodID(
            bridge_class,
            "cameraStreamCapabilityList",
            "(J[Ldev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraStreamCapabilityHeader;)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamCapabilityListResponse;"
        );
    }

    if (streamOpen_method == nullptr) {
        streamOpen_method = env->GetMethodID(
            bridge_class,
            "cameraStreamOpen",
            "(JIIIIII)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamOpenResponse;"
        );
    }

    if (streamClose_method == nullptr) {
        streamClose_method = env->GetMethodID(
            bridge_class,
            "cameraStreamClose",
            "(J)I"
        );
    }

    if (streamStart_method == nullptr) {
        streamStart_method = env->GetMethodID(
            bridge_class,
            "cameraStreamStart",
            "(J)I"
        );
    }

    if (streamStop_method == nullptr) {
        streamStop_method = env->GetMethodID(
            bridge_class,
            "cameraStreamStop",
            "(J)I"
        );
    }

    if (streamRead_method == nullptr) {
        streamRead_method = env->GetMethodID(
            bridge_class,
            "cameraStreamRead",
            "(JJ[I)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamReadResponse;"
        );
    }

    if (streamTryRead_method == nullptr) {
        streamTryRead_method = env->GetMethodID(
            bridge_class,
            "cameraStreamTryRead",
            "(J[I)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamTryReadResponse;"
        );
    }

    if (streamTakePhoto_method == nullptr) {
        streamTakePhoto_method = env->GetMethodID(
            bridge_class,
            "cameraStreamTakePhoto",
            "(JJ[I)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamTakePhotoResponse;"
        );
    }

    if (streamConfig_method == nullptr) {
        streamConfig_method = env->GetMethodID(
            bridge_class,
            "cameraStreamConfig",
            "(J)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamConfigResponse;"
        );
    }

    if (streamRecordingCapabilities_method == nullptr) {
        streamRecordingCapabilities_method = env->GetMethodID(
            bridge_class,
            "cameraStreamRecordingCapabilities",
            "(J)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamRecordingCapabilitiesResponse;"
        );
    }

    if (streamStartRecording_method == nullptr) {
        streamStartRecording_method = env->GetMethodID(
            bridge_class,
            "cameraStreamStartRecording",
            "(JIILjava/lang/Integer;ILjava/lang/Long;Ljava/lang/Long;Ljava/lang/Integer;Ljava/lang/Long;Ljava/lang/Long;Ljava/lang/String;)I"
        );
    }

    if (streamPauseRecording_method == nullptr) {
        streamPauseRecording_method = env->GetMethodID(
            bridge_class,
            "cameraStreamPauseRecording",
            "(J)I"
        );
    }

    if (streamResumeRecording_method == nullptr) {
        streamResumeRecording_method = env->GetMethodID(
            bridge_class,
            "cameraStreamResumeRecording",
            "(J)I"
        );
    }

    if (streamStopRecording_method == nullptr) {
        streamStopRecording_method = env->GetMethodID(
            bridge_class,
            "cameraStreamStopRecording",
            "(JJ)I"
        );
    }

    if (streamGetU64_method == nullptr) {
        streamGetU64_method = env->GetMethodID(
            bridge_class,
            "cameraStreamGetU64",
            "(JI)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamGetU64Response;"
        );
    }

    if (streamSetU64_method == nullptr) {
        streamSetU64_method = env->GetMethodID(
            bridge_class,
            "cameraStreamSetU64",
            "(JIJ)I"
        );
    }

    if (streamGetU32_method == nullptr) {
        streamGetU32_method = env->GetMethodID(
            bridge_class,
            "cameraStreamGetU32",
            "(JI)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamGetU32Response;"
        );
    }

    if (streamSetU32_method == nullptr) {
        streamSetU32_method = env->GetMethodID(
            bridge_class,
            "cameraStreamSetU32",
            "(JII)I"
        );
    }

    if (streamGetF64_method == nullptr) {
        streamGetF64_method = env->GetMethodID(
            bridge_class,
            "cameraStreamGetF64",
            "(JI)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamGetF64Response;"
        );
    }

    if (streamSetF64_method == nullptr) {
        streamSetF64_method = env->GetMethodID(
            bridge_class,
            "cameraStreamSetF64",
            "(JID)I"
        );
    }

    if (streamGetRangeF64_method == nullptr) {
        streamGetRangeF64_method = env->GetMethodID(
            bridge_class,
            "cameraStreamGetRangeF64",
            "(JI)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamGetRangeF64Response;"
        );
    }

    if (streamGetRangeU64_method == nullptr) {
        streamGetRangeU64_method = env->GetMethodID(
            bridge_class,
            "cameraStreamGetRangeU64",
            "(JI)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamGetRangeU64Response;"
        );
    }

    if (streamGetRangeU32_method == nullptr) {
        streamGetRangeU32_method = env->GetMethodID(
            bridge_class,
            "cameraStreamGetRangeU32",
            "(JI)Ldev/destack/runtime/android/bridge/RuntimeHostCameraStreamGetRangeU32Response;"
        );
    }

    return
        deviceList_method != nullptr &&
        deviceOpen_method != nullptr &&
        deviceClose_method != nullptr &&
        streamConfigList_method != nullptr &&
        streamCapabilityList_method != nullptr &&
        streamOpen_method != nullptr &&
        streamClose_method != nullptr &&
        streamStart_method != nullptr &&
        streamStop_method != nullptr &&
        streamRead_method != nullptr &&
        streamTryRead_method != nullptr &&
        streamTakePhoto_method != nullptr &&
        streamConfig_method != nullptr &&
        streamRecordingCapabilities_method != nullptr &&
        streamStartRecording_method != nullptr &&
        streamPauseRecording_method != nullptr &&
        streamResumeRecording_method != nullptr &&
        streamStopRecording_method != nullptr &&
        streamGetU64_method != nullptr &&
        streamSetU64_method != nullptr &&
        streamGetU32_method != nullptr &&
        streamSetU32_method != nullptr &&
        streamGetF64_method != nullptr &&
        streamSetF64_method != nullptr &&
        streamGetRangeF64_method != nullptr &&
        streamGetRangeU64_method != nullptr &&
        streamGetRangeU32_method != nullptr;
}

}

bool resolve_camera_methods(JNIEnv *env, jobject bridge) {
    return resolve_bridge_methods(env, bridge);
}

/// Call the camera-device-list entrypoint on one registered bridge.
uint32_t call_camera_device_list(
    JNIEnv *env,
    uint64_t session_handle,
    AndroidHostCameraDeviceDescriptorHeaderSlice devices,
    uint32_t *device_count_written,
    NativeU8Slice string_bytes,
    uint32_t *string_bytes_written
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }

    jobjectArray devices_value = encode_AndroidHostCameraDeviceDescriptorHeaderSlice(env, devices);
    if (devices_value == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }
    jintArray string_bytes_value = encode_u8_slice(env, string_bytes);
    if (string_bytes_value == nullptr) {
        if (devices_value != nullptr) { env->DeleteLocalRef(devices_value); }
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jobject response_object = env->CallObjectMethod(
        bridge,
        deviceList_method,
        devices_value,
        string_bytes_value
    );
    if (response_object == nullptr) {
        if (devices_value != nullptr) { env->DeleteLocalRef(devices_value); }
        if (string_bytes_value != nullptr) { env->DeleteLocalRef(string_bytes_value); }
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        *device_count_written = static_cast<uint32_t>(call_int_getter(env, response_object, "getDeviceCountWritten"));
        *string_bytes_written = static_cast<uint32_t>(call_int_getter(env, response_object, "getStringBytesWritten"));
    }
    if (devices_value != nullptr) { env->DeleteLocalRef(devices_value); }
    if (string_bytes_value != nullptr) { env->DeleteLocalRef(string_bytes_value); }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-device-open entrypoint on one registered bridge.
uint32_t call_camera_device_open(
    JNIEnv *env,
    uint64_t session_handle,
    NativeStringRef id,
    uint64_t *session_id
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }

    jstring id_value = java_string_or_null(env, id);

    jobject response_object = env->CallObjectMethod(
        bridge,
        deviceOpen_method,
        id_value
    );
    if (response_object == nullptr) {
        if (id_value != nullptr) { env->DeleteLocalRef(id_value); }
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        *session_id = static_cast<uint64_t>(call_long_getter(env, response_object, "getSessionId"));
    }
    if (id_value != nullptr) { env->DeleteLocalRef(id_value); }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-device-close entrypoint on one registered bridge.
uint32_t call_camera_device_close(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t session_id
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jint status = env->CallIntMethod(
        bridge,
        deviceClose_method,
        static_cast<jlong>(session_id)
    );
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-config-list entrypoint on one registered bridge.
uint32_t call_camera_stream_config_list(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t session_id,
    AndroidHostCameraStreamConfigHeaderSlice configs,
    uint32_t *config_count_written
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }

    jobjectArray configs_value = encode_AndroidHostCameraStreamConfigHeaderSlice(env, configs);
    if (configs_value == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jobject response_object = env->CallObjectMethod(
        bridge,
        streamConfigList_method,
        static_cast<jlong>(session_id),
        configs_value
    );
    if (response_object == nullptr) {
        if (configs_value != nullptr) { env->DeleteLocalRef(configs_value); }
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        *config_count_written = static_cast<uint32_t>(call_int_getter(env, response_object, "getConfigCountWritten"));
    }
    if (configs_value != nullptr) { env->DeleteLocalRef(configs_value); }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-capability-list entrypoint on one registered bridge.
uint32_t call_camera_stream_capability_list(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t session_id,
    AndroidHostCameraStreamCapabilityHeaderSlice capabilities,
    uint32_t *capability_count_written
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }

    jobjectArray capabilities_value = encode_AndroidHostCameraStreamCapabilityHeaderSlice(env, capabilities);
    if (capabilities_value == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jobject response_object = env->CallObjectMethod(
        bridge,
        streamCapabilityList_method,
        static_cast<jlong>(session_id),
        capabilities_value
    );
    if (response_object == nullptr) {
        if (capabilities_value != nullptr) { env->DeleteLocalRef(capabilities_value); }
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        *capability_count_written = static_cast<uint32_t>(call_int_getter(env, response_object, "getCapabilityCountWritten"));
    }
    if (capabilities_value != nullptr) { env->DeleteLocalRef(capabilities_value); }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-open entrypoint on one registered bridge.
uint32_t call_camera_stream_open(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t session_id,
    AndroidHostCameraStreamConfigHeader config,
    uint64_t *stream_id
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jobject response_object = env->CallObjectMethod(
        bridge,
        streamOpen_method,
        static_cast<jlong>(session_id),
        static_cast<jint>(config.width),
        static_cast<jint>(config.height),
        static_cast<jint>(config.frame_rate_milli_hz),
        static_cast<jint>(config.pixel_format),
        static_cast<jint>(config.pixel_format_family),
        static_cast<jint>(config.is_compressed)
    );
    if (response_object == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        *stream_id = static_cast<uint64_t>(call_long_getter(env, response_object, "getStreamId"));
    }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-close entrypoint on one registered bridge.
uint32_t call_camera_stream_close(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jint status = env->CallIntMethod(
        bridge,
        streamClose_method,
        static_cast<jlong>(stream_id)
    );
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-start entrypoint on one registered bridge.
uint32_t call_camera_stream_start(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jint status = env->CallIntMethod(
        bridge,
        streamStart_method,
        static_cast<jlong>(stream_id)
    );
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-stop entrypoint on one registered bridge.
uint32_t call_camera_stream_stop(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jint status = env->CallIntMethod(
        bridge,
        streamStop_method,
        static_cast<jlong>(stream_id)
    );
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-read entrypoint on one registered bridge.
uint32_t call_camera_stream_read(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint64_t timeout_ns,
    AndroidHostCameraFrameHeader *header,
    NativeU8Slice bytes,
    uint32_t *bytes_written
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }

    jintArray bytes_value = encode_u8_slice(env, bytes);
    if (bytes_value == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jobject response_object = env->CallObjectMethod(
        bridge,
        streamRead_method,
        static_cast<jlong>(stream_id),
        static_cast<jlong>(timeout_ns),
        bytes_value
    );
    if (response_object == nullptr) {
        if (bytes_value != nullptr) { env->DeleteLocalRef(bytes_value); }
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    clear_result_decode_storage();
    std::deque<std::string> *string_storage = &result_string_storage;

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        jobject header_value = call_object_getter(env, response_object, "getHeader", "()Ldev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraFrameHeader;");
        if (header_value == nullptr) {
            status = HOST_STATUS_FAILED;
        } else {
            *header = decode_AndroidHostCameraFrameHeader(env, header_value, string_storage);
            env->DeleteLocalRef(header_value);
        }
        *bytes_written = static_cast<uint32_t>(call_int_getter(env, response_object, "getBytesWritten"));
    }
    if (bytes_value != nullptr) { env->DeleteLocalRef(bytes_value); }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-try-read entrypoint on one registered bridge.
uint32_t call_camera_stream_try_read(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    AndroidHostCameraFrameHeader *header,
    NativeU8Slice bytes,
    uint32_t *bytes_written
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }

    jintArray bytes_value = encode_u8_slice(env, bytes);
    if (bytes_value == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jobject response_object = env->CallObjectMethod(
        bridge,
        streamTryRead_method,
        static_cast<jlong>(stream_id),
        bytes_value
    );
    if (response_object == nullptr) {
        if (bytes_value != nullptr) { env->DeleteLocalRef(bytes_value); }
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    clear_result_decode_storage();
    std::deque<std::string> *string_storage = &result_string_storage;

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        jobject header_value = call_object_getter(env, response_object, "getHeader", "()Ldev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraFrameHeader;");
        if (header_value == nullptr) {
            status = HOST_STATUS_FAILED;
        } else {
            *header = decode_AndroidHostCameraFrameHeader(env, header_value, string_storage);
            env->DeleteLocalRef(header_value);
        }
        *bytes_written = static_cast<uint32_t>(call_int_getter(env, response_object, "getBytesWritten"));
    }
    if (bytes_value != nullptr) { env->DeleteLocalRef(bytes_value); }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-take-photo entrypoint on one registered bridge.
uint32_t call_camera_stream_take_photo(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint64_t timeout_ns,
    AndroidHostCameraFrameHeader *header,
    NativeU8Slice bytes,
    uint32_t *bytes_written
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }

    jintArray bytes_value = encode_u8_slice(env, bytes);
    if (bytes_value == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jobject response_object = env->CallObjectMethod(
        bridge,
        streamTakePhoto_method,
        static_cast<jlong>(stream_id),
        static_cast<jlong>(timeout_ns),
        bytes_value
    );
    if (response_object == nullptr) {
        if (bytes_value != nullptr) { env->DeleteLocalRef(bytes_value); }
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    clear_result_decode_storage();
    std::deque<std::string> *string_storage = &result_string_storage;

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        jobject header_value = call_object_getter(env, response_object, "getHeader", "()Ldev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraFrameHeader;");
        if (header_value == nullptr) {
            status = HOST_STATUS_FAILED;
        } else {
            *header = decode_AndroidHostCameraFrameHeader(env, header_value, string_storage);
            env->DeleteLocalRef(header_value);
        }
        *bytes_written = static_cast<uint32_t>(call_int_getter(env, response_object, "getBytesWritten"));
    }
    if (bytes_value != nullptr) { env->DeleteLocalRef(bytes_value); }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-config entrypoint on one registered bridge.
uint32_t call_camera_stream_config(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    AndroidHostCameraStreamConfigHeader *config
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jobject response_object = env->CallObjectMethod(
        bridge,
        streamConfig_method,
        static_cast<jlong>(stream_id)
    );
    if (response_object == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    clear_result_decode_storage();
    std::deque<std::string> *string_storage = &result_string_storage;

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        jobject config_value = call_object_getter(env, response_object, "getConfig", "()Ldev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraStreamConfigHeader;");
        if (config_value == nullptr) {
            status = HOST_STATUS_FAILED;
        } else {
            *config = decode_AndroidHostCameraStreamConfigHeader(env, config_value, string_storage);
            env->DeleteLocalRef(config_value);
        }
    }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-recording-capabilities entrypoint on one registered bridge.
uint32_t call_camera_stream_recording_capabilities(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    AndroidHostCameraRecordingCapabilitiesHeader *capabilities
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jobject response_object = env->CallObjectMethod(
        bridge,
        streamRecordingCapabilities_method,
        static_cast<jlong>(stream_id)
    );
    if (response_object == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    clear_result_decode_storage();
    std::deque<std::string> *string_storage = &result_string_storage;

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        jobject capabilities_value = call_object_getter(env, response_object, "getCapabilities", "()Ldev/destack/runtime/android/module/camera/RuntimeAndroidHostCameraRecordingCapabilitiesHeader;");
        if (capabilities_value == nullptr) {
            status = HOST_STATUS_FAILED;
        } else {
            *capabilities = decode_AndroidHostCameraRecordingCapabilitiesHeader(env, capabilities_value, string_storage);
            env->DeleteLocalRef(capabilities_value);
        }
    }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-start-recording entrypoint on one registered bridge.
uint32_t call_camera_stream_start_recording(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    AndroidHostCameraRecordingOptionsHeader options,
    NativeStringRef output_path
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }

    jobject audio_enabled_value = options.audio_enabled.has_value ? box_int(env, static_cast<jint>(options.audio_enabled.value)) : nullptr;
    jobject video_bit_rate_value = options.video_bit_rate.has_value ? box_long(env, static_cast<jlong>(options.video_bit_rate.value)) : nullptr;
    jobject audio_bit_rate_value = options.audio_bit_rate.has_value ? box_long(env, static_cast<jlong>(options.audio_bit_rate.value)) : nullptr;
    jobject key_frame_interval_frames_value = options.key_frame_interval_frames.has_value ? box_int(env, static_cast<jint>(options.key_frame_interval_frames.value)) : nullptr;
    jobject maximum_duration_ns_value = options.maximum_duration_ns.has_value ? box_long(env, static_cast<jlong>(options.maximum_duration_ns.value)) : nullptr;
    jobject maximum_bytes_value = options.maximum_bytes.has_value ? box_long(env, static_cast<jlong>(options.maximum_bytes.value)) : nullptr;
    jstring output_path_value = java_string_or_null(env, output_path);

    jint status = env->CallIntMethod(
        bridge,
        streamStartRecording_method,
        static_cast<jlong>(stream_id),
        static_cast<jint>(options.container),
        static_cast<jint>(options.video_codec),
        audio_enabled_value,
        static_cast<jint>(options.audio_codec),
        video_bit_rate_value,
        audio_bit_rate_value,
        key_frame_interval_frames_value,
        maximum_duration_ns_value,
        maximum_bytes_value,
        output_path_value
    );
    if (audio_enabled_value != nullptr) { env->DeleteLocalRef(audio_enabled_value); }
    if (video_bit_rate_value != nullptr) { env->DeleteLocalRef(video_bit_rate_value); }
    if (audio_bit_rate_value != nullptr) { env->DeleteLocalRef(audio_bit_rate_value); }
    if (key_frame_interval_frames_value != nullptr) { env->DeleteLocalRef(key_frame_interval_frames_value); }
    if (maximum_duration_ns_value != nullptr) { env->DeleteLocalRef(maximum_duration_ns_value); }
    if (maximum_bytes_value != nullptr) { env->DeleteLocalRef(maximum_bytes_value); }
    if (output_path_value != nullptr) { env->DeleteLocalRef(output_path_value); }
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-pause-recording entrypoint on one registered bridge.
uint32_t call_camera_stream_pause_recording(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jint status = env->CallIntMethod(
        bridge,
        streamPauseRecording_method,
        static_cast<jlong>(stream_id)
    );
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-resume-recording entrypoint on one registered bridge.
uint32_t call_camera_stream_resume_recording(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jint status = env->CallIntMethod(
        bridge,
        streamResumeRecording_method,
        static_cast<jlong>(stream_id)
    );
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-stop-recording entrypoint on one registered bridge.
uint32_t call_camera_stream_stop_recording(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint64_t timeout_ns
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jint status = env->CallIntMethod(
        bridge,
        streamStopRecording_method,
        static_cast<jlong>(stream_id),
        static_cast<jlong>(timeout_ns)
    );
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-get-u64 entrypoint on one registered bridge.
uint32_t call_camera_stream_get_u64(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint32_t selector,
    uint64_t *value
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jobject response_object = env->CallObjectMethod(
        bridge,
        streamGetU64_method,
        static_cast<jlong>(stream_id),
        static_cast<jint>(selector)
    );
    if (response_object == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        *value = static_cast<uint64_t>(call_long_getter(env, response_object, "getValue"));
    }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-set-u64 entrypoint on one registered bridge.
uint32_t call_camera_stream_set_u64(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint32_t selector,
    uint64_t value
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jint status = env->CallIntMethod(
        bridge,
        streamSetU64_method,
        static_cast<jlong>(stream_id),
        static_cast<jint>(selector),
        static_cast<jlong>(value)
    );
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-get-u32 entrypoint on one registered bridge.
uint32_t call_camera_stream_get_u32(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint32_t selector,
    uint32_t *value
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jobject response_object = env->CallObjectMethod(
        bridge,
        streamGetU32_method,
        static_cast<jlong>(stream_id),
        static_cast<jint>(selector)
    );
    if (response_object == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        *value = static_cast<uint32_t>(call_int_getter(env, response_object, "getValue"));
    }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-set-u32 entrypoint on one registered bridge.
uint32_t call_camera_stream_set_u32(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint32_t selector,
    uint32_t value
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jint status = env->CallIntMethod(
        bridge,
        streamSetU32_method,
        static_cast<jlong>(stream_id),
        static_cast<jint>(selector),
        static_cast<jint>(value)
    );
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-get-f64 entrypoint on one registered bridge.
uint32_t call_camera_stream_get_f64(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint32_t selector,
    double *value
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jobject response_object = env->CallObjectMethod(
        bridge,
        streamGetF64_method,
        static_cast<jlong>(stream_id),
        static_cast<jint>(selector)
    );
    if (response_object == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        *value = static_cast<double>(call_double_getter(env, response_object, "getValue"));
    }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-set-f64 entrypoint on one registered bridge.
uint32_t call_camera_stream_set_f64(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint32_t selector,
    double value
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jint status = env->CallIntMethod(
        bridge,
        streamSetF64_method,
        static_cast<jlong>(stream_id),
        static_cast<jint>(selector),
        static_cast<jdouble>(value)
    );
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-get-range-f64 entrypoint on one registered bridge.
uint32_t call_camera_stream_get_range_f64(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint32_t selector,
    double *minimum,
    double *maximum,
    double *step
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jobject response_object = env->CallObjectMethod(
        bridge,
        streamGetRangeF64_method,
        static_cast<jlong>(stream_id),
        static_cast<jint>(selector)
    );
    if (response_object == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        *minimum = static_cast<double>(call_double_getter(env, response_object, "getMinimum"));
        *maximum = static_cast<double>(call_double_getter(env, response_object, "getMaximum"));
        *step = static_cast<double>(call_double_getter(env, response_object, "getStep"));
    }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-get-range-u64 entrypoint on one registered bridge.
uint32_t call_camera_stream_get_range_u64(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint32_t selector,
    uint64_t *minimum,
    uint64_t *maximum,
    uint64_t *step
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jobject response_object = env->CallObjectMethod(
        bridge,
        streamGetRangeU64_method,
        static_cast<jlong>(stream_id),
        static_cast<jint>(selector)
    );
    if (response_object == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        *minimum = static_cast<uint64_t>(call_long_getter(env, response_object, "getMinimum"));
        *maximum = static_cast<uint64_t>(call_long_getter(env, response_object, "getMaximum"));
        *step = static_cast<uint64_t>(call_long_getter(env, response_object, "getStep"));
    }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}

/// Call the camera-stream-get-range-u32 entrypoint on one registered bridge.
uint32_t call_camera_stream_get_range_u32(
    JNIEnv *env,
    uint64_t session_handle,
    uint64_t stream_id,
    uint32_t selector,
    uint32_t *minimum,
    uint32_t *maximum,
    uint32_t *step
) {
    jobject bridge = resolve_bridge(env, session_handle);
    if (bridge == nullptr) {
        return HOST_STATUS_NOT_FOUND;
    }


    jobject response_object = env->CallObjectMethod(
        bridge,
        streamGetRangeU32_method,
        static_cast<jlong>(stream_id),
        static_cast<jint>(selector)
    );
    if (response_object == nullptr) {
        if (env->ExceptionCheck()) {
            env->ExceptionClear();
        }
        env->DeleteLocalRef(bridge);
        return HOST_STATUS_FAILED;
    }

    jint status = call_int_getter(env, response_object, "getStatus");
    if (status == HOST_STATUS_OK) {
        *minimum = static_cast<uint32_t>(call_int_getter(env, response_object, "getMinimum"));
        *maximum = static_cast<uint32_t>(call_int_getter(env, response_object, "getMaximum"));
        *step = static_cast<uint32_t>(call_int_getter(env, response_object, "getStep"));
    }
    env->DeleteLocalRef(response_object);
    env->DeleteLocalRef(bridge);

    if (env->ExceptionCheck()) {
        env->ExceptionClear();
        return HOST_STATUS_FAILED;
    }

    return static_cast<uint32_t>(status);
}
