name = "TS++ Bytecode Assembly"
grammar = "destack_bytecode"
path_suffixes = ["tsppa"]
line_comments = ["// "]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = true, newline = false },
]
word_characters = ["."]
tab_size = 4
