[package]
name = "destack_std_cli"
description = "Destack Standard Library CLI"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
default-run = "destack_std_cli"

[lib]
path = "rust/lib.rs"

[[bin]]
name = "destack_std_cli"
path = "rust/main.rs"

[dependencies]
destack_std_lsp = { workspace = true }
destack_std_tokei = { workspace = true }
destack_lang_lex = { workspace = true }
destack_lang_parse = { workspace = true }

tokio = { version = "1.47.1" }

[dev-dependencies]

[lints]
workspace = true
