repos:
  # Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.284
    hooks:
      - id: ruff
        name: ruff (py)
        exclude: ^bench/migrations
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: black (py)
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (py)
  - repo: local
    hooks: # (on all files)
      - id: pyright
        name: pyright (py)
        entry: pyright
        language: system
        always_run: true
        types: [ python ]

  # JS/TS
  - repo: local
    hooks:
      - id: bun-check
        name: bun-check (ts)
        entry: bun
        args: [ run, --cwd, bench-web, check ]
        language: system
        verbose: true
        always_run: true
        types: [ javascript, jsx, ts, tsx, vue ]

  # General
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
  - repo: https://github.com/flotothemoon/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: check-no-nocheckin
        types_or: [ javascript, jsx, ts, tsx, vue, python, bash ]
