repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        name: flake8 (py)
        args: ["--max-line-length=100", "--select=C,E,F,W,B,B950", "--extend-ignore=E203,E501,W503"]
        exclude: ^backend/notebooks/|^backend/alembic
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: black (py)
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (py)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        name: mypy (py)
        args: [--strict-optional, --ignore-missing-imports, --follow-imports=skip, --config-file=pyproject.toml]
        # TODO @Cleanup: specify additional_dependencies rather than using language: system
        #  I couldn't figure out how to make mypy ignore missing imports (despite above args),
        #  so for now just run it in the system environment. This will probably fail in CI.
        language: system
  #        additional_dependencies:
  #          - "mypy==0.942"
  #           should match relevant stubs in requirements-dev.in
  #          - "djangorestframework-stubs==1.5.0"
  #          - "django-stubs==1.10.1"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.13.0
    hooks:
      - id: eslint
        name: eslint (js)
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        types_or: [javascript, jsx, ts, tsx, vue]
        additional_dependencies:
          - eslint@8.5.0
          - eslint-plugin-cypress@2.12.1
          - eslint-plugin-vue@8.2.0
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        name: prettier (js)
        types_or: [javascript, jsx, ts, tsx, vue]
        additional_dependencies:
          - prettier@2.6.2
          - prettier-plugin-tailwindcss@0.1.8
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
  - repo: https://github.com/flotothemoon/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: check-no-nocheckin
        types_or: [javascript, jsx, ts, tsx, vue, python, bash]
