repos:
  # Python
  - repo: local
    hooks:
      # lint
      - id: ruff
        name: ruff check (py)
        entry: ruff 
        language: python
        language_version: python3.13
        additional_dependencies:
          - ruff==0.11.12
        exclude: ^bench/(migrations|proto)
        types: [ python ]
        args: [ check, --fix ]
      # format
      - id: ruff-format
        name: ruff format (py)
        entry: ruff
        language: python
        language_version: python3.13
        additional_dependencies:
          - ruff==0.11.12
        types: [ python ]
        args: [ format ]

  # General
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v1.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
  - repo: https://github.com/flotothemoon/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: check-no-nocheckin
        types_or: [ javascript, jsx, ts, tsx, vue, python, bash, rust ]
