[workspace]
resolver = "2"
members = [
	# language
	"language/ast",
	"language/container",
	"language/compiler",
	"language/concurrency",
	"language/diagnostic",
	"language/dir",
	"language/dvm",
	"language/fir",
	"language/formatter",
	"language/js",
	"language/jsc",
	"language/jsm",
	"language/mir",
	"language/parser",
	"language/module",
	"language/prelude",
	"language/source",
	"language/string",
	"language/test",
	"language/tree",
	# platform
	"platform/file",
	"platform/terminal",
	"platform/test",
	"platform/json",
	"platform/order",
	"platform/time",
	"platform/unicode",
	"platform/uuid",
	# extension
	"extension/cli",
	"extension/lsp",
	"extension/tokei",
	"extension/vscode",
	"extension/zed",
]

[workspace.package]
version = "2025.11.5-0"
edition = "2024"
authors = ["Symbol Industries"]
license = "proprietary"
rust-version = "1.88.0"

[workspace.dependencies]
# language
dyst_ast = { path = "language/ast" }
dyst_compiler = { path = "language/compiler" }
dyst_concurrency = { path = "language/concurrency" }
dyst_container = { path = "language/container" }
dyst_diagnostic = { path = "language/diagnostic" }
dyst_dir = { path = "language/dir" }
dyst_dvm = { path = "language/dvm" }
dyst_fir = { path = "language/fir" }
dyst_formatter = { path = "language/formatter" }
dyst_js = { path = "language/js" }
dyst_jsc = { path = "language/jsc" }
dyst_jsm = { path = "language/jsm" }
dyst_memory = { path = "language/memory" }
dyst_mir = { path = "language/mir" }
dyst_parser = { path = "language/parser" }
dyst_module = { path = "language/module" }
dyst_prelude = { path = "language/prelude" }
dyst_session = { path = "language/session" }
dyst_source = { path = "language/source" }
dyst_string = { path = "language/string" }
dyst_test = { path = "language/test" }
dyst_tree = { path = "language/tree" }
# platform
destack_file = { path = "platform/file" }
destack_json = { path = "platform/json" }
destack_order = { path = "platform/order" }
destack_terminal = { path = "platform/terminal" }
destack_test = { path = "platform/test" }
destack_time = { path = "platform/time" }
destack_unicode = { path = "platform/unicode" }
destack_uuid = { path = "platform/uuid" }
# extension
destack_cli = { path = "extension/cli" }
destack_javascript = { path = "extension/javascript" }
destack_lsp = { path = "extension/lsp" }
destack_python = { path = "extension/python" }
destack_rust = { path = "extension/rust" }
destack_tokei = { path = "extension/tokei" }
destack_vscode = { path = "extension/vscode" }
destack_web = { path = "extension/web" }
destack_zed = { path = "extension/zed" }

# build dependencies
wasm-bindgen = "0.2.100"

# dev dependencies
arbitrary = { version = "1.4.2", features = ["derive"] }
libfuzzer-sys = "0.4.10"
pretty_assertions = "1.4.1"
quickcheck = "1.0.3"
quickcheck_macros = "1.1.0"
static_assertions = "1.1.0"
wasm-bindgen-test = "0.3.50"
criterion = { version = "0.5", features = ["html_reports"] }
pprof = { version = "0.15", features = ["flamegraph", "criterion"] }

[workspace.lints.rust]
missing_debug_implementations = "warn"
rust_2018_idioms = "warn"
unreachable_pub = "warn"
ambiguous_glob_reexports = { level = "forbid", priority = 1 }

[workspace.lints.clippy]
perf = "warn"
uninlined_format_args = "warn"
expect_used = { level = "allow", priority = 1 }
manual_range_contains = { level = "allow", priority = 1 }
module_inception = { level = "allow", priority = 1 }

[workspace.lints.rustdoc]
broken_intra_doc_links = "warn"

[profile.dev]
opt-level = 0
debug = "full"
debug-assertions = true
overflow-checks = true
incremental = true
split-debuginfo = "unpacked"
panic = "abort"

[profile.bench]
opt-level = 3
codegen-units = 1
lto = "thin"
debug-assertions = false
overflow-checks = false
split-debuginfo = "unpacked"
strip = "none"
debug = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = "thin"
debug-assertions = false
overflow-checks = false
strip = "symbols"
debug = false
panic = "abort"
