[workspace]
resolver = "2"
members = [
	"destack-rs/destack",
	"destack-rs/destack_cli",
	"destack-rs/destack_cli_macros",
	"destack-rs/destack_codegen",
	"destack-rs/destack_json",
	"destack-rs/destack_json/fuzz",
	"destack-rs/destack_lexer",
	"destack-rs/destack_lexer/fuzz",
	"destack-rs/destack_order",
	"destack-rs/destack_test",
	"destack-rs/destack_time",
	"destack-rs/destack_time/fuzz",
	"destack-rs/destack_unicode",
	"destack-rs/destack_uuid",
	"destack-rs/destack_uuid/fuzz",
]

[workspace.package]
version = "2025.8.19-3"
edition = "2024"
authors = ["Symbol Industries"]
license = "proprietary"
rust-version = "1.88.0"

[workspace.dependencies]
destack = { path = "destack-rs/destack" }
destack_cli = { path = "destack-rs/destack_cli" }
destack_cli_macros = { path = "destack-rs/destack_cli_macros" }
destack_codegen = { path = "destack-rs/destack_codegen" }
destack_json = { path = "destack-rs/destack_json" }
destack_lexer = { path = "destack-rs/destack_lexer" }
destack_macros = { path = "destack-rs/destack_macros" }
destack_order = { path = "destack-rs/destack_order" }
destack_time = { path = "destack-rs/destack_time" }
destack_unicode = { path = "destack-rs/destack_unicode" }
destack_uuid = { path = "destack-rs/destack_uuid" }

# dependencies
tokio = "1.47.1"

# build dependencies
wasm-bindgen = "0.2.100"

# dev dependencies
arbitrary = { version = "1.4.2", features = ["derive"] }
libfuzzer-sys = "0.4.10"
pretty_assertions = "1.4.1"
quickcheck = "1.0.3"
quickcheck_macros = "1.1.0"
static_assertions = "1.1.0"
wasm-bindgen-test = "0.3.50"
criterion = { version = "0.5", features = ["html_reports"] }

[workspace.lints.rust]
missing_debug_implementations = "warn"
rust_2018_idioms = "warn"
unreachable_pub = "warn"
ambiguous_glob_reexports = { level = "forbid", priority = 1 }

[workspace.lints.clippy]
perf = "warn"
uninlined_format_args = "warn"
expect_used = "warn"
manual_range_contains = { level = "allow", priority = 1 }
module_inception = { level = "allow", priority = 1 }

[workspace.lints.rustdoc]
broken_intra_doc_links = "warn"

[profile.dev]
opt-level = 1
debug = 2
debug-assertions = true
overflow-checks = true
incremental = true

[profile.bench]
lto = "fat"
opt-level = 3
codegen-units = 1
debug-assertions = false
overflow-checks = false
strip = "none"
debug = false

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
debug-assertions = false
overflow-checks = false
strip = "symbols"
debug = false
panic = "abort"
