[workspace]
resolver = "2"
members = [
	"destack-rs/destack",
	"destack-rs/destack_order",
	"destack-rs/destack_time",
	"destack-rs/destack_json",
	"destack-rs/destack_uuid",
	"destack-rs/destack_system",
	"destack-rs/destack_test",
]

[workspace.package]
version = "2025.8.18-0"
edition = "2024"
authors = ["Symbol Industries"]
license = "proprietary"
rust-version = "1.88.0"

[workspace.dependencies]
destack = { path = "destack-rs/destack" }
destack_macros = { path = "destack-rs/destack_macros" }
destack_order = { path = "destack-rs/destack_order" }
destack_json = { path = "destack-rs/destack_json" }
destack_time = { path = "destack-rs/destack_time" }
destack_uuid = { path = "destack-rs/destack_uuid" }
destack_system = { path = "destack-rs/destack_system" }

# dependencies
tokio = "1.47.1"

# build dependencies
wasm-bindgen = "0.2.100"

# dev dependencies
arbitrary = { version = "1.4.2", features = ["derive"] }
libfuzzer-sys = "0.4.10"
pretty_assertions = "1.4.1"
quickcheck = "1.0.3"
quickcheck_macros = "1.1.0"
static_assertions = "1.1.0"
wasm-bindgen-test = "0.3.50"

[workspace.lints.rust]
missing_debug_implementations = "warn"
rust_2018_idioms = "warn"
unreachable_pub = "warn"
ambiguous_glob_reexports = { level = "forbid", priority = 1 }

[workspace.lints.clippy]
perf = "warn"
uninlined_format_args = "warn"
expect_used = "warn"
manual_range_contains = { level = "allow", priority = 1 }
module_inception = { level = "allow", priority = 1 }

[workspace.lints.rustdoc]
broken_intra_doc_links = "warn"

[profile.dev]
opt-level = 1
debug = 2
debug-assertions = true
overflow-checks = true
incremental = true

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
debug-assertions = false
overflow-checks = false
strip = "none"
debug = false

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug-assertions = false
overflow-checks = false
strip = "symbols"
debug = false
panic = "abort"
