[mypy]
plugins = mypy_django_plugin.main
follow_imports = silent

[mypy.plugins.django-stubs]
django_settings_module = "bench.settings"

[mypy-uvicorn.*]
ignore_missing_imports = True

[mypy-gunicorn.*]
ignore_missing_imports = True