[project]
name = "destack"
version = "2025.07.26.0"
description = "Destack Python"
authors = [{ name = "Symbol Industries", email = "hello@symbol.industries" }]

[tool.uv]
workspace = { members = [
	"destack-py",
	"destack-py-system",
	"destack-py-runtime",
	"destack-py-web",
] }

[tool.ruff]
line-length = 100

[tool.ruff.lint]
preview = true
select = [
	# pycodestyle
	"E",
	# Pyflakes
	"F",
	# pyupgrade
	"UP",
	# refurb
	"FURB",
	# flake8-bugbear
	"B",
	# flake8-simplify
	"SIM",
	# flake8-comprehensions
	"C4",
	# flake8-async
	"ASYNC",
	# flake8-datetimez,
	"DTZ",
	# flake8-pytest-style
	"PT",
	# flake8-print
	"T20",
	# isort
	"I",
	# pep8-naming
	"N",
	# ruff
	"RUF",
]
ignore = [
	# line too long
	"E501",
	# getattr/setattr with constant 
	"B009",
	"B010",
	# multiple asserts in one line
	"PT018",
	# exception too broad
	"PT011",
	# pytest.raises should contain a single statement
	"PT012",
	# single if instead of nested ifs
	"SIM102",
	# non lowercase variable in function
	"N806",
]

[tool.ruff.lint.isort]
known-first-party = ["destack-py", "destack", "desys", "derun", "deweb"]

[tool.pyright]
include = ["destack-py/destack", "destack-py-system/desys"]
ignore = ["^destack-py/venv*"]
venv = "destack-py/venv"
extraPaths = ["destack-py", "destack-py-system"]
strictDictionaryInference = true
strictListInference = true
strictTupleInference = true
strictSetInference = true
reportPrivateUsage = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportUnknownParameterType = false
reportMissingParameterType = false
reportMissingTypeArgument = false
reportUnknownLambdaType = false
reportUnusedVariable = false
reportUnusedFunction = false
reportUnusedImport = false
reportMissingTypeStubs = false
reportUnnecessaryIsInstance = false
reportUnnecessaryContains = false
reportUnnecessaryComparison = false
reportUnnecessaryCast = false
reportConstantRedefinition = false

[tool.pytest_env]
ENVIRONMENT = "test"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_test_loop_scope = "session"
python_files = "test/**/*.py test/*.py"
python_classes = "!TestProfile"
pythonpath = ["destack-py", "destack-py-system"]
log_cli = true
addopts = [
	'-rP',
	"-vv",
	"--import-mode=importlib",
	"--color=yes",
	'--strict-markers',
]
markers = []
filterwarnings = ["ignore::DeprecationWarning", "ignore::UserWarning"]
