"""Can only be resolved by user with organization write permission"""
directive @canWriteOrganization(atRoot: Boolean! = true) on FIELD_DEFINITION

"""Can only be resolved by user with project view permission"""
directive @canViewProject(atRoot: Boolean! = true) on FIELD_DEFINITION

"""Can only be resolved by user with project write permission"""
directive @canWriteProject(atRoot: Boolean! = true) on FIELD_DEFINITION

"""Can only be resolved by user with user write permission"""
directive @canWriteUser(atRoot: Boolean! = true) on FIELD_DEFINITION

type AccessToken implements Node {
  id: GlobalID!
  token: String
  name: String
  tokenKey: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  expiresAt: DateTime
  revokedAt: DateTime
  status: AccessTokenStatus!
  scopes: [AccessTokenScope!]!
  owner: UserOrganization!
}

"""A connection to a list of items."""
type AccessTokenConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [AccessTokenEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

input AccessTokenCreateInput {
  ownerId: GlobalID!
  scopes: [AccessTokenScope!]!
  expiresAt: DateTime = null
  name: String = null
}

type AccessTokenCreatePayload {
  accessToken: AccessToken!
  token: String!
}

union AccessTokenCreatePayloadOperationInfo = AccessTokenCreatePayload | OperationInfo

"""An edge in a connection."""
type AccessTokenEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: AccessToken!
}

union AccessTokenOperationInfo = AccessToken | OperationInfo

enum AccessTokenScope {
  RUN
}

enum AccessTokenStatus {
  ACTIVE
  EXPIRED
  REVOKED
}

input BuildInput {
  projectVersionId: GlobalID!
  buildableId: GlobalID = null
}

type BuildState {
  projectVersionId: GlobalID!
  success: Boolean!
}

union BuildStateOperationInfo = BuildState | OperationInfo

input CommitInput {
  projectVersionId: GlobalID!
  name: String!
  tag: String = null
  description: String = null
}

type CommitPayload {
  project: Project!
  committedVersion: ProjectVersion!
  newWorkingVersion: ProjectVersion!
}

union CommitPayloadOperationInfo = CommitPayload | OperationInfo

type DatasetRecord implements Node {
  id: GlobalID!
  createdAt: DateTime!
  updatedAt: DateTime!
  orderKey: String!
  data: JSON!
}

"""A connection to a list of items."""
type DatasetRecordConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [DatasetRecordEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type DatasetRecordEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: DatasetRecord!
}

"""Date with time (isoformat)"""
scalar DateTime

input DeployInput {
  id: GlobalID!
  status: DeploymentStatus!
}

type Deployment implements Node {
  id: GlobalID!
  owner: OrganizationUser!
  project: Project!
  projectVersion: ProjectVersion!
  createdAt: DateTime!
  updatedAt: DateTime!
  status: DeploymentStatus!
  type: DeploymentType!
  deployAllStatements: Boolean!
  deployedStatements: [Statement!]!
}

input DeploymentAddStatementInput {
  id: GlobalID!
  statementId: ID!
}

"""A connection to a list of items."""
type DeploymentConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [DeploymentEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type DeploymentEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: Deployment!
}

input DeploymentFilter {
  isOwned: Boolean = null
}

union DeploymentOperationInfo = Deployment | OperationInfo

input DeploymentRemoveStatementInput {
  id: GlobalID!
  statementId: ID!
}

input DeploymentSetDeployAllStatementsInput {
  id: GlobalID!
  deployAllStatements: Boolean!
}

enum DeploymentStatus {
  INACTIVE
  SLEEPING
  ACTIVE
  ARCHIVED
  DESTROYED
}

enum DeploymentType {
  ADHOC
  MANUAL
}

enum ErrorType {
  INTERNAL
  UNKNOWN_TOKEN
  MISSING_TOKEN
  UNEXPECTED_TOKEN_TYPE
  UNEXPECTED_TOKEN_VALUE
  UNEXPECTED_INDENT
  EXPECTED_BLANK
  MISSING_EXTRA
  UNEXPECTED_EXTRA
  INVALID_TOKEN_VALUE
  INVALID_STATEMENT
  UNKNOWN_IMPORT_SOURCE
  MISSING_REFERENCE
  UNDEFINED_LOCAL_REFERENCE
  UNDEFINED_EXTERNAL_REFERENCE
  EXTERNAL_LOOKUP_FAILED
  REFERENCE_TYPE_MISMATCH
  AMBIGUOUS_DEFINITION
  AMBIGUOUS_REQUIREMENT
  UNEXPECTED_PARENT
  EXPECTED_PARENT
  EXPECTED_PROPER_CHILDREN
  UNEXPECTED_CHILDREN
  EXPECTED_PARAMETERS
  UNEXPECTED_PARAMETERS
  EXPECTED_ARGUMENTS
  UNEXPECTED_STATEMENT
  BUILD_MISSING_MODEL
  BUILD_MISSING_TASK
  CIRCULAR_ANCESTRY
}

type Execution implements Node {
  id: GlobalID!
  createdAt: DateTime!
  updatedAt: DateTime!

  """Time of transition to RUNNING status."""
  startedAt: DateTime

  """Time of transition to a terminal status."""
  terminatedAt: DateTime
  durationMillis: Float
  status: ExecutionStatus!
  inputs: JSON
  outputs: JSON
  error: JSON
  root: Execution
  parent: Execution
  descendants: [Execution!]!
  build: Statement
  task: Statement
  code: Statement
  model: Statement
}

"""A connection to a list of items."""
type ExecutionConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [ExecutionEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type ExecutionEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: Execution!
}

enum ExecutionStatus {
  Created
  Scheduled
  Queued
  Running
  Aborting
  Aborted
  Failed
  Completed
}

type File implements Node {
  id: GlobalID!
  projectVersion: ProjectVersion!
  revision: Int!
  name: String!
  path: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  deletedAt: DateTime
  directory: Boolean!
  generated: Boolean!
  parent: File
  files: [File!]!
  statements(filters: StatementFilter): [Statement!]!
}

"""A connection to a list of items."""
type FileConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [FileEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

input FileCreateInput {
  id: GlobalID = null
  projectVersionId: GlobalID!
  name: String!
  path: String!
  parentId: GlobalID = null
  directory: Boolean! = false
}

"""An edge in a connection."""
type FileEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: File!
}

input FileFilter {
  isVisible: Boolean = true
}

input FileMoveInput {
  id: GlobalID!
  parentId: GlobalID = null
  path: String!
}

union FileOperationInfo = File | OperationInfo

input FileRenameInput {
  id: GlobalID!
  name: String!
  path: String!
}

"""
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
"""
scalar GlobalID @specifiedBy(url: "https://relay.dev/graphql/objectidentification.htm")

type InterpError {
  type: ErrorType!
  message: String!
  symbol: InterpSymbol
}

type InterpFile {
  id: GlobalID!
  module: InterpModule!
  path: String!
  symbols: [InterpSymbol!]!
}

type InterpJob {
  id: GlobalID!
  type: JobType!
  status: JobStatus!
  startedAt: DateTime
  terminatedAt: DateTime
  symbol: InterpSymbol
}

type InterpModule {
  id: GlobalID!
  name: String!
  files: [InterpFile!]!
}

"""
Proxy type to SimpleType to avoid overwriting source SimpleType references
(no extra fields yet but needed since (SimpleType, id) global id would be the same
 for the simple types output by the runtime and by the source types put in).
"""
type InterpSimpleType implements Node & SimpleType {
  id: GlobalID!
  name: String
  orderKey: String!
  tag: TypeTag!
  isOutput: Boolean!
  isArray: Boolean!
  isNullable: Boolean!
  description: String
  value: JSON
  reference: Statement
  statement: NodeType!
  createdAt: DateTime!
  updatedAt: DateTime!
}

type InterpSymbol implements SimplyTyped {
  rootTypeTag: TypeTag
  typeNodes: [InterpSimpleType!]
  id: GlobalID!
  file: InterpFile!
  orderKey: String!
  parentId: GlobalID
  name: String
  type: StatementType!
  generated: Boolean!
  modifier: StatementModifier
  symbolType: SymbolType
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON @specifiedBy(url: "http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf")

enum JobStatus {
  QUEUED
  RUNNING
  COMPLETED
  FAILED
}

enum JobType {
  INTERP
  BUILD
  GENERATE
  EVALUATE
}

type ModuleRuntime {
  updatedAt: DateTime!
  module: InterpModule!
  jobs: [InterpJob!]!
  dependencies: [InterpModule!]!
  errors: [InterpError!]!
  staleSymbols: [InterpSymbol!]!
}

type Mutation {
  completeSignup(input: UserCompleteSignupInput!): UserOperationInfo!
  logout: OperationInfo
  createAccessToken(input: AccessTokenCreateInput!): AccessTokenCreatePayloadOperationInfo!
  revokeAccessToken(id: GlobalID!): AccessTokenOperationInfo!
  createProject(input: ProjectCreateInput!): ProjectOperationInfo!
  updateProjectVisibility(input: ProjectUpdateVisibilityInput!): ProjectOperationInfo!
  updateProjectName(input: ProjectUpdateNameInput!): ProjectOperationInfo!
  updateProjectVersion(input: UpdateProjectVersion!): ProjectVersionOperationInfo!
  commit(input: CommitInput!): CommitPayloadOperationInfo!
  restore(input: RestoreInput!): CommitPayloadOperationInfo!
  createStatement(input: StatementCreateInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  morphStatement(input: StatementMorphInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  softDeleteStatement(input: StatementSoftDeleteInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  restoreStatement(input: StatementRestoreInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  updateStatementModifier(input: StatementSetModifierInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  updateStatementReference(input: StatementSetReferenceInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  commentStatement(input: StatementCommentedInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  moveStatement(input: StatementMoveInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  renameStatement(input: StatementRenameInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  updateStatementText(input: StatementUpdateCodeInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  updateStatementDescription(input: StatementUpdateDescriptionInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  updateStatementCode(input: StatementUpdateCodeInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  updateStatementLanguage(input: StatementUpdateLanguageInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  createStatementRecord(input: RecordCreateInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  updateStatementRecord(input: RecordUpdateInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  moveStatementRecord(input: RecordMoveInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  deleteStatementRecord(input: RecordDeleteInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  createStatementTypeNode(input: TypeNodeCreateInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  updateStatementTypeNode(input: TypeNodeUpdateInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  moveStatementTypeNode(input: TypeNodeMoveInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  deleteStatementTypeNode(input: TypeNodeDeleteInput!): StatementOperationInfo! @canWriteProject(atRoot: true)
  createFile(input: FileCreateInput!): FileOperationInfo! @canWriteProject(atRoot: true)
  softDeleteFile(input: NodeInput!): FileOperationInfo! @canWriteProject(atRoot: true)
  restoreFile(input: NodeInput!): FileOperationInfo! @canWriteProject(atRoot: true)
  moveFile(input: FileMoveInput!): FileOperationInfo! @canWriteProject(atRoot: true)
  renameFile(input: FileRenameInput!): FileOperationInfo! @canWriteProject(atRoot: true)
  setDeployAllStatements(input: DeploymentSetDeployAllStatementsInput!): DeploymentOperationInfo! @canWriteProject(atRoot: true)
  addDeployedStatement(input: DeploymentAddStatementInput!): DeploymentOperationInfo! @canWriteProject(atRoot: true)
  removeDeployedStatement(input: DeploymentRemoveStatementInput!): DeploymentOperationInfo! @canWriteProject(atRoot: true)
  updateDeployment(input: DeployInput!): DeploymentOperationInfo! @canWriteProject(atRoot: true)
  build(input: BuildInput!): BuildStateOperationInfo!
  run(input: RunInput!): RunStateOperationInfo!
}

"""An object with a Globally Unique ID"""
interface Node {
  """The Globally Unique ID of this object"""
  id: GlobalID!
}

"""Input of an object that implements the `Node` interface."""
input NodeInput {
  id: GlobalID!
}

"""Generic type for objects that implements the `Node` interface."""
type NodeType implements Node {
  id: GlobalID!
}

"""Multiple messages returned by an operation."""
type OperationInfo {
  """List of messages returned by the operation."""
  messages: [OperationMessage!]!
}

"""An error that happened while executing an operation."""
type OperationMessage {
  """The kind of this message."""
  kind: OperationMessageKind!

  """The error message."""
  message: String!

  """
  The field that caused the error, or `null` if it isn't associated with any particular field.
  """
  field: String
}

"""The kind of the returned message."""
enum OperationMessageKind {
  INFO
  WARNING
  ERROR
  PERMISSION
  VALIDATION
}

type Organization implements Node & Owner {
  id: GlobalID!
  slug: String!
  name: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  projects(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): ProjectConnection! @canViewProject(atRoot: false)
  accessTokens(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): AccessTokenConnection! @canWriteOrganization(atRoot: false)
  members(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): UserConnection!
}

"""A connection to a list of items."""
type OrganizationConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [OrganizationEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type OrganizationEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: Organization!
}

union OrganizationUser = Organization | User

interface Owner {
  id: GlobalID!
  slug: String!
  name: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  projects: ProjectConnection!
  accessTokens: AccessTokenConnection!
}

"""Information to aid in pagination."""
type PageInfo {
  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: String

  """When paginating forwards, the cursor to continue."""
  endCursor: String
}

type Project implements Node {
  id: GlobalID!
  name: String!
  slug: String!
  type: ProjectType!
  visibility: ProjectVisibility!
  path: String!
  owner: UserOrganization!
  createdAt: DateTime!
  updatedAt: DateTime!
  head: ProjectVersion!
  versions(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
    filters: ProjectVersionFilter
  ): ProjectVersionConnection!
  deployments(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
    filters: DeploymentFilter
  ): DeploymentConnection!
  canWrite: Boolean!
}

"""A connection to a list of items."""
type ProjectConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [ProjectEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

input ProjectCreateInput {
  ownerId: GlobalID!
  name: String!
  slug: String!
  visibility: ProjectVisibility!
  type: ProjectType! = EXECUTABLE
}

"""An edge in a connection."""
type ProjectEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: Project!
}

union ProjectOperationInfo = Project | OperationInfo

enum ProjectType {
  EXECUTABLE
  LIBRARY
}

input ProjectUpdateNameInput {
  id: GlobalID!
  name: String!
}

input ProjectUpdateVisibilityInput {
  id: GlobalID!
  visibility: ProjectVisibility!
}

type ProjectVersion implements Node {
  id: GlobalID!
  project: Project!
  name: String
  tag: String
  description: String
  parents: [ProjectVersion!]!
  children: [ProjectVersion!]!
  createdAt: DateTime!
  committed: Boolean!
  committedAt: DateTime
  dependencies: [ProjectVersion!]!
  files(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
    filters: FileFilter
  ): FileConnection!
  deployments(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
    filters: DeploymentFilter
  ): DeploymentConnection!
  parentsRefs: [RefMapping!]!
}

"""A connection to a list of items."""
type ProjectVersionConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [ProjectVersionEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type ProjectVersionEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: ProjectVersion!
}

input ProjectVersionFilter {
  fromId: GlobalID!
  toId: GlobalID!
}

union ProjectVersionOperationInfo = ProjectVersion | OperationInfo

enum ProjectVisibility {
  PUBLIC
  SOURCE_PRIVATE
  PRIVATE
}

type Query {
  executions(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
    projectVersionId: GlobalID = null
    buildId: GlobalID = null
    taskId: GlobalID = null
    codeId: GlobalID = null
    rootId: GlobalID = null
    rootIdNull: Boolean! = false
  ): ExecutionConnection! @canViewProject(atRoot: true)
  systemInfo: SystemInfo!
  me: User
  user(
    """The ID of the object."""
    id: GlobalID!
  ): User
  organization(
    """The ID of the object."""
    id: GlobalID!
  ): Organization
  ownerBySlug(slug: String!): UserOrganization
  project(
    """The ID of the object."""
    id: GlobalID!
  ): Project @canViewProject(atRoot: true)
  projectBySlug(owner: String!, project: String!): Project @canViewProject(atRoot: true)
  projectVersion(
    """The ID of the object."""
    id: GlobalID!
  ): ProjectVersion @canViewProject(atRoot: true)
  projectVersionBySlug(owner: String!, project: String!, tag: String!): ProjectVersion @canViewProject(atRoot: true)
  file(
    """The ID of the object."""
    id: GlobalID!
  ): File @canViewProject(atRoot: true)
}

input RecordCreateInput {
  id: GlobalID!
  statementId: GlobalID!
  data: JSON!
  orderKey: String!
}

input RecordDeleteInput {
  id: GlobalID!
  statementId: GlobalID!
}

input RecordMoveInput {
  id: GlobalID!
  statementId: GlobalID!
  orderKey: String!
}

input RecordUpdateInput {
  id: GlobalID!
  statementId: GlobalID!
  data: JSON!
}

type RefMapping {
  source: GlobalID!
  target: GlobalID!
}

input RestoreInput {
  projectVersionId: GlobalID!
}

input RunInput {
  projectVersionId: GlobalID!
  runnableId: GlobalID = null
  buildId: GlobalID = null
  arguments: JSON!
}

type RunState {
  projectVersionId: GlobalID!
  runnableId: GlobalID
  buildId: GlobalID
  output: JSON
  success: Boolean!
}

union RunStateOperationInfo = RunState | OperationInfo

interface SimpleType {
  id: GlobalID!
  name: String
  orderKey: String!
  tag: TypeTag!
  isOutput: Boolean!
  isArray: Boolean!
  isNullable: Boolean!
  description: String
  value: JSON
  reference: Statement
}

type SimpleTypeNode implements Node & SimpleType {
  id: GlobalID!
  name: String
  orderKey: String!
  tag: TypeTag!
  isOutput: Boolean!
  isArray: Boolean!
  isNullable: Boolean!
  description: String
  value: JSON
  reference: Statement
  statement: NodeType!
  createdAt: DateTime!
  updatedAt: DateTime!
}

"""Anything typed using SimpleType nodes."""
interface SimplyTyped {
  rootTypeTag: TypeTag
  typeNodes: [SimpleType!]
}

type Statement implements Node & SimplyTyped {
  id: GlobalID!
  rootTypeTag: TypeTag
  typeNodes: [SimpleTypeNode!]!
  projectVersion: ProjectVersion!
  file: File!
  revision: Int!
  type: StatementType!
  modifier: StatementModifier
  name: String
  createdAt: DateTime!
  updatedAt: DateTime!
  deletedAt: DateTime
  commented: Boolean!
  generated: Boolean!
  parent: Statement
  children: [Statement!]!
  descendants: [Statement!]!
  orderKey: String!
  reference: Statement
  referencedBy(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): StatementConnection!
  symbolType: SymbolType
  lang: String
  code: String
  description: String
  referenceProjectVersion: ProjectVersion
  value: JSON
  records(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): DatasetRecordConnection!
}

input StatementCommentedInput {
  id: GlobalID!
  commented: Boolean!
}

"""A connection to a list of items."""
type StatementConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [StatementEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""Creates a blank statement"""
input StatementCreateInput {
  id: GlobalID = null
  fileId: GlobalID!
  orderKey: String!
  parentId: GlobalID = null
}

"""An edge in a connection."""
type StatementEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: Statement!
}

input StatementFilter {
  isVisible: Boolean = true
}

"""A modifier to a Bench statement."""
enum StatementModifier {
  VAR
  WITH
  INCLUDE
  LIKE
  UNLIKE
  CHECK
  MAGIC
}

input StatementMorphInput {
  id: GlobalID!
  type: StatementType!
  symbolType: SymbolType = null
  name: String = null
  rootTypeTag: TypeTag = null
  typeNodes: [TypeNodeCreateInput!] = null
  lang: String = null
}

input StatementMoveInput {
  id: GlobalID!
  fileId: GlobalID!
  parentId: GlobalID = null
  orderKey: String = null
}

union StatementOperationInfo = Statement | OperationInfo

input StatementRenameInput {
  id: GlobalID!
  name: String
}

input StatementRestoreInput {
  id: GlobalID!
}

input StatementSetModifierInput {
  id: GlobalID!
  modifier: StatementModifier
}

input StatementSetReferenceInput {
  id: GlobalID!
  referenceId: GlobalID = null
}

input StatementSoftDeleteInput {
  id: GlobalID!
}

"""The type of Bench statement."""
enum StatementType {
  IMPORT
  DEFINITION
  REFERENCE
  REDEFINITION
  COMMENT
  BLANK
}

input StatementUpdateCodeInput {
  id: GlobalID!
  code: String = null
}

input StatementUpdateDescriptionInput {
  id: GlobalID!
  description: String!
}

input StatementUpdateLanguageInput {
  id: GlobalID!
  language: String!
}

type Subscription {
  moduleRuntimeChanged(projectVersionId: GlobalID!): ModuleRuntime!
  moduleExecutionChanged(projectVersionId: GlobalID!, buildId: GlobalID = null, taskId: GlobalID = null, codeId: GlobalID = null, rootId: GlobalID = null, rootIdNull: Boolean! = false): Execution!
}

"""The type of symbol content."""
enum SymbolType {
  TYPE
  CAPABILITY
  TASK
  EXPECTATION
  CODE
  MODEL
  DATA
  VALUE
  REQUIREMENT
  BUILD
  RUNCONFIG
}

type SystemInfo {
  version: String!
  gitCommit: String!
}

type Type {
  description: String
  btl: String!
}

"""Upsert a statement type node data"""
input TypeNodeCreateInput {
  id: GlobalID!
  orderKey: String!
  statementId: GlobalID!
  name: String = null
  tag: TypeTag!
  description: String = null
  isOutput: Boolean! = false
  isNullable: Boolean! = false
  isArray: Boolean! = false
  value: JSON = null
  referenceId: GlobalID = null
}

input TypeNodeDeleteInput {
  id: GlobalID!
  statementId: GlobalID!
}

input TypeNodeMoveInput {
  id: GlobalID!
  statementId: GlobalID!
  orderKey: String!
}

input TypeNodeUpdateInput {
  id: GlobalID!
  name: String = null
  tag: TypeTag!
  description: String = null
  isOutput: Boolean! = false
  isNullable: Boolean! = false
  isArray: Boolean! = false
  value: JSON = null
  referenceId: GlobalID = null
}

"""The type of type node."""
enum TypeTag {
  STRING
  NUMBER
  BOOLEAN
  EMBEDDING
  IMAGE
  VIDEO
  AUDIO
  ARRAY
  TUPLE
  MAP
  STRUCT
  FUNCTION
  UNION
  INTERSECTION
  ENUM
  LITERAL
  NULL
  ANY
  TYPE_REFERENCE
}

input UpdateProjectVersion {
  id: GlobalID!
  name: String!
  tag: String = null
  description: String = null
}

type User implements Node & Owner {
  id: GlobalID!
  slug: String!
  name: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  projects(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): ProjectConnection! @canViewProject(atRoot: false)
  accessTokens(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): AccessTokenConnection! @canWriteUser(atRoot: false)

  """Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."""
  username: String!
  email: String!
  completedSignup: Boolean!
  bot: Boolean!
  organizations(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): OrganizationConnection!
}

input UserCompleteSignupInput {
  id: GlobalID!
  username: String!
  fullName: String!
}

"""A connection to a list of items."""
type UserConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [UserEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type UserEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: User!
}

union UserOperationInfo = User | OperationInfo

union UserOrganization = User | Organization