input AddCompilationInput {
  taskSymbolId: GlobalID!
  name: String!
  backends: [String!]!
}

type AddCompilationPayload {
  compilation: Compilation!
}

type Code implements SymbolContent & Node {
  id: GlobalID!
  definition: Statement!
  builtinId: String
  code: String
  length: Int!
}

input CodeUpdateContentCode {
  statementId: GlobalID!
  builtinId: String = null
  code: String = null
}

input CommitInput {
  projectVersionId: GlobalID!
  name: String!
  description: String = null
}

type CommitPayload {
  project: Project!
  committedVersion: ProjectVersion!
  newWorkingVersion: ProjectVersion!
}

type Compilation implements Node {
  id: GlobalID!
  mappings: [SourceMapping!]!
}

input CompileInput {
  compilationId: GlobalID!
}

type CompilePayload {
  compilation: Compilation!
}

union CreateFilePayload = File | OperationInfo

type Dataset implements SymbolContent & Node {
  id: GlobalID!
  definition: Statement!
  length: Int!
  records: [DatasetRecord!]!
}

type DatasetRecord implements Node {
  id: GlobalID!
  index: Int!
  data: JSON!
}

"""Date with time (isoformat)"""
scalar DateTime

type Execution implements Node {
  id: GlobalID!
  createdAt: DateTime!
  updatedAt: DateTime!

  """Time of transition to RUNNING status."""
  startedAt: DateTime

  """Time of transition to a terminal status."""
  terminatedAt: DateTime
  durationMillis: Float
  status: String!
  inputs: JSON
  outputs: JSON
  error: JSON
  parent: Execution
  children: [Execution!]!
  code: Code!
  model: Model
}

type Expectation implements SymbolContent & Node {
  id: GlobalID!
  definition: Statement!
  description: String!
}

input ExpectationUpdateContentDescription {
  statementId: GlobalID!
  description: String!
}

type File implements Node {
  id: GlobalID!
  projectVersion: ProjectVersion!
  type: FileType!
  name: String!
  path: String!
  pathWithoutExtension: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  deletedAt: DateTime
  parent: File
  files: [File!]!
  statements(filters: StatementFilter): [Statement!]!
}

input FileCreateInput {
  projectVersion: NodeInput!
  type: FileType
  name: String!
  parent: NodeInput
}

input FileFilter {
  isVisible: Boolean = true
}

input FileRenameInput {
  id: GlobalID!
  name: String
}

input FileRestoreInput {
  id: GlobalID!
}

input FileSoftDeleteInput {
  id: GlobalID!
}

"""The type of file determines what it is intended to contain."""
enum FileType {
  DIRECTORY
  INSTRUCT
  PROJECT
}

"""
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
"""
scalar GlobalID @specifiedBy(url: "https://relay.dev/graphql/objectidentification.htm")

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON @specifiedBy(url: "http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf")

type Model implements SymbolContent & Node {
  id: GlobalID!
  definition: Statement!
  baseline(pk: ID): Model
  provider: String!
}

type MorphStatementPayload {
  statement: Statement!
}

type Mutation {
  renameStatement(input: StatementRenameInput!): RenameStatementPayload!
  setModifierStatement(input: StatementSetModifierInput!): SetModifierStatementPayload!
  createStatement(input: StatementCreateInput!): StatementCreatePayload!
  setReferenceStatement(input: StatementSetReferenceInput!): StatementSetReferencePayload!
  morphStatement(input: StatementMorphInput!): MorphStatementPayload!
  commentStatement(input: StatementCommentedInput!): StatementCommentedPayload!
  moveStatement(input: StatementMoveInput!): StatementMovePayload!
  softDeleteStatement(input: StatementSoftDeleteInput!): StatementSoftDeletePayload!
  restoreStatement(input: StatementRestoreInput!): StatementRestorePayload!
  createFile(input: FileCreateInput!): CreateFilePayload!
  renameFile(input: FileRenameInput!): RenameFilePayload!
  softDeleteFile(input: FileSoftDeleteInput!): File!
  restoreFile(input: FileRestoreInput!): File!
  updateTaskContent(input: TaskUpdateContentDescription!): Statement!
  updateExpectationContent(input: ExpectationUpdateContentDescription!): Statement!
  updateCodeContent(input: CodeUpdateContentCode!): Statement!
  run(input: RunCodeInput!): RunCodePayload!
  addCompilationTarget(input: AddCompilationInput!): AddCompilationPayload!
  compile(input: CompileInput!): CompilePayload!
  commit(input: CommitInput!): CommitPayload!
}

"""An object with a Globally Unique ID"""
interface Node {
  """The Globally Unique ID of this object"""
  id: GlobalID!
}

"""Input of an object that implements the `Node` interface."""
input NodeInput {
  id: GlobalID!
}

"""Multiple messages returned by an operation."""
type OperationInfo {
  """List of messages returned by the operation."""
  messages: [OperationMessage!]!
}

"""An error that happened while executing an operation."""
type OperationMessage {
  """The kind of this message."""
  kind: OperationMessageKind!

  """The error message."""
  message: String!

  """
  The field that caused the error, or `null` if it isn't associated with any particular field.
  """
  field: String
}

"""The kind of the returned message."""
enum OperationMessageKind {
  INFO
  WARNING
  ERROR
  PERMISSION
  VALIDATION
}

type Organization implements Node {
  id: GlobalID!
  name: String!
  slug: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  projects: [Project!]!
  members: [User!]!
}

"""Information to aid in pagination."""
type PageInfo {
  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: String

  """When paginating forwards, the cursor to continue."""
  endCursor: String
}

type Project implements Node {
  id: GlobalID!
  name: String!
  slug: String!
  path: String!
  organization: Organization!
  createdAt: DateTime!
  updatedAt: DateTime!
  head: ProjectVersion!
  versions(filters: ProjectVersionFilter): [ProjectVersion!]!
}

"""A connection to a list of items."""
type ProjectConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [ProjectEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type ProjectEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: Project!
}

type ProjectVersion implements Node {
  id: GlobalID!
  project: Project!
  name: String
  description: String
  parents: [ProjectVersion!]!
  children: [ProjectVersion!]!
  createdAt: DateTime!
  committed: Boolean!
  committedAt: DateTime
  dependencies: [ProjectVersion!]!
  mainProgram: Statement
  files(filters: FileFilter): [File!]!
  statements(filters: StatementFilter): [Statement!]!
  compilations: [Compilation!]!
  parentsRefs: [RefMapping!]!
}

input ProjectVersionFilter {
  afterId: GlobalID!
}

type Query {
  user(
    """The ID of the object."""
    id: GlobalID!
  ): User
  users(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): UserConnection!
  organization(
    """The ID of the object."""
    id: GlobalID!
  ): Organization
  organizationBySlug(organization: String!): Organization
  project(
    """The ID of the object."""
    id: GlobalID!
  ): Project
  projectBySlug(organization: String!, project: String!): Project
  projects(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): ProjectConnection!
  projectVersion(
    """The ID of the object."""
    id: GlobalID!
  ): ProjectVersion
  file(
    """The ID of the object."""
    id: GlobalID!
  ): File
  statement(
    """The ID of the object."""
    id: GlobalID!
  ): Statement
}

type RefMapping {
  source: GlobalID!
  target: GlobalID!
}

union RenameFilePayload = File | OperationInfo

union RenameStatementPayload = Statement | OperationInfo

type Requirement implements Node {
  id: GlobalID!
  projectVersion: ProjectVersion!
}

input RunCodeInput {
  codeId: GlobalID!
  arguments: [RunCodeValueArgumentInput!]!
}

type RunCodeOutput {
  name: String!
  value: String!
}

type RunCodePayload {
  code: Code!
  execution: Execution!
  outputs: [RunCodeOutput!]
}

input RunCodeValueArgumentInput {
  name: String!
  value: String!
}

type Schema implements SymbolContent & Node {
  id: GlobalID!
  definition: Statement!
  description: String!
  element: SchemaElement!
}

type SchemaElement {
  name: String
  type: ValueType!
  required: Boolean!
  schemaId: String
  elements: [SchemaElement!]
}

union SetModifierStatementPayload = Statement | OperationInfo

type SourceMapping implements Node {
  id: GlobalID!
  source: Statement!
  sourcePath: JSON!
  sourceRevision: Int!
  target: Statement!
  targetPath: JSON!
  targetRevision: Int!
}

type Statement implements Node {
  id: GlobalID!
  projectVersion: ProjectVersion!
  file: File!
  type: StatementType!
  modifier: StatementModifier
  name: String
  createdAt: DateTime!
  updatedAt: DateTime!
  deletedAt: DateTime
  commented: Boolean!
  compiled: Boolean!
  parent: Statement
  children: [Statement!]!
  descendants: [Statement!]!
  index: Int
  symbolType: SymbolType
  text: String

  """Traverses references to get the source definition."""
  sourceDefinition(pk: ID): Statement
  reference: Statement
  referencedBy: [Statement!]!
  content(pk: ID): SymbolContent
  compilation: Compilation
  requirement: Requirement
}

input StatementCommentedInput {
  id: GlobalID!
  commented: Boolean!
}

type StatementCommentedPayload {
  statement: Statement!
}

input StatementCreateInput {
  fileId: GlobalID!
  type: StatementType!
  name: String = null
  parentId: GlobalID = null
  index: Int = null
}

type StatementCreatePayload {
  statement: Statement!
}

input StatementFilter {
  isVisible: Boolean = true
  type: StatementType = null
  id: GlobalID
}

"""A modifier to a Bench statement."""
enum StatementModifier {
  WITH
  LIKE
  UNLIKE
  VERIFY
}

input StatementMorphInput {
  statementId: GlobalID!
  type: StatementType!
  symbolType: SymbolType = null
}

input StatementMoveInput {
  id: GlobalID!
  fileId: GlobalID!
  parentId: GlobalID = null
  index: Int = null
}

type StatementMovePayload {
  statement: Statement!
  oldFile: File!
  newFile: File!
}

input StatementRenameInput {
  id: GlobalID!
  name: String
}

input StatementRestoreInput {
  id: GlobalID!
}

type StatementRestorePayload {
  statement: Statement!
}

input StatementSetModifierInput {
  id: GlobalID!
  modifier: StatementModifier
}

input StatementSetReferenceInput {
  statementId: GlobalID!
  referenceId: GlobalID = null
}

type StatementSetReferencePayload {
  statement: Statement!
}

input StatementSoftDeleteInput {
  id: GlobalID!
}

type StatementSoftDeletePayload {
  statement: Statement!
}

"""The type of Bench statement."""
enum StatementType {
  IMPORT
  DEFINITION
  REFERENCE
  REDEFINITION
  REQUIREMENT
  COMPILATION
  RUNCONFIG
  COMMENT
  BLANK
}

interface SymbolContent implements Node {
  id: GlobalID!
}

"""The type of symbol content."""
enum SymbolType {
  SCHEMA
  TASK
  EXPECTATION
  CODE
  MODEL
  DATASET
  VALUE
}

type Task implements SymbolContent & Node {
  id: GlobalID!
  definition: Statement!
  description: String!
  compilations: [Compilation!]!
}

input TaskUpdateContentDescription {
  statementId: GlobalID!
  description: String!
}

type User implements Node {
  id: GlobalID!

  """Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."""
  username: String!
  firstName: String!
  lastName: String!
  email: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  organizations: [Organization!]!
}

"""A connection to a list of items."""
type UserConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [UserEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type UserEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: User!
}

type Value implements SymbolContent & Node {
  id: GlobalID!
  value: JSON
}

"""An enumeration."""
enum ValueType {
  STRING
  NUMBER
  BOOLEAN
  SCHEMA
  OBJECT
  ARRAY
  NULL
}