type Dataset implements Node {
  id: GlobalID!
  name: String!
  createdAt: DateTime!
  schema: JSON
  length: Int!
  records: [DjangoModelType!]
}

"""Date with time (isoformat)"""
scalar DateTime

type DjangoModelType {
  pk: ID!
}

"""
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
"""
scalar GlobalID @specifiedBy(url: "https://relay.dev/graphql/objectidentification.htm")

type Instruction implements Node {
  id: GlobalID!
  name: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  parent: Instruction
  children: [Instruction!]!
  builtinId: String
  code: String
  scope: String!
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
"""
scalar JSON @specifiedBy(url: "http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf")

type Model implements Node {
  id: GlobalID!
  name: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  baseline: Model
  provider: String!
}

type Mutation {
  compileTask(taskId: UUID!): Void
  runProgram(projectId: UUID!): Void
}

"""An object with a Globally Unique ID"""
interface Node {
  """The Globally Unique ID of this object"""
  id: GlobalID!
}

type Organization implements Node {
  id: GlobalID!
  name: String!
  slug: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  projects: [Project!]!
  members: [User!]!
}

"""A connection to a list of items."""
type OrganizationConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [OrganizationEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type OrganizationEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: Organization!
}

"""Information to aid in pagination."""
type PageInfo {
  """When paginating forwards, are there more items?"""
  hasNextPage: Boolean!

  """When paginating backwards, are there more items?"""
  hasPreviousPage: Boolean!

  """When paginating backwards, the cursor to continue."""
  startCursor: String

  """When paginating forwards, the cursor to continue."""
  endCursor: String
}

type Project implements Node {
  id: GlobalID!
  name: String!
  slug: String!
  organization: Organization!
  createdAt: DateTime!
  updatedAt: DateTime!
  head: ProjectVersion!
  versions: [ProjectVersion!]!
}

"""A connection to a list of items."""
type ProjectConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [ProjectEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type ProjectEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: Project!
}

type ProjectFile implements Node {
  id: GlobalID!
  projectVersion: ProjectVersion!
  type: String!
  name: String!
  task: Task!
  instruction: Instruction!
  model: Model!
  dataset: Dataset!
  nameDotType: String!
}

type ProjectVersion implements Node {
  id: GlobalID!
  project: Project!
  name: String
  description: String
  parents: [ProjectVersion!]!
  createdAt: DateTime!
  committedAt: DateTime
  program: Task
  files: [ProjectFile!]!
}

type Query {
  user(
    """The ID of the object."""
    id: GlobalID!
  ): User
  users(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): UserConnection!
  project(
    """The ID of the object."""
    id: GlobalID!
  ): Project
  projectBySlug(organization: String!, project: String!): Project
  projects(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): ProjectConnection!
  projectVersion(
    """The ID of the object."""
    id: GlobalID!
  ): ProjectVersion
  organization(
    """The ID of the object."""
    id: GlobalID!
  ): Organization
  organizationBySlug(organization: String!): Organization
  organizations(
    """Returns the items in the list that come before the specified cursor."""
    before: String = null

    """Returns the items in the list that come after the specified cursor."""
    after: String = null

    """Returns the first n items from the list."""
    first: Int = null

    """Returns the items in the list that come after the specified cursor."""
    last: Int = null
  ): OrganizationConnection!
}

type Task implements Node {
  id: GlobalID!
  name: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  parent: Task
  children: [Task!]!
  schema: JSON!
  templateImplementation: Instruction
}

scalar UUID

type User implements Node {
  id: GlobalID!

  """Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."""
  username: String!
  firstName: String!
  lastName: String!
  email: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  organizations: [Organization!]!
}

"""A connection to a list of items."""
type UserConnection {
  """Pagination data for this connection"""
  pageInfo: PageInfo!

  """Contains the nodes in this connection"""
  edges: [UserEdge!]!

  """Total quantity of existing nodes"""
  totalCount: Int
}

"""An edge in a connection."""
type UserEdge {
  """A cursor for use in pagination"""
  cursor: String!

  """The item at the end of the edge"""
  node: User!
}

"""Represents NULL values"""
scalar Void