[package]
name = "destack_engine"
description = "Destack execution contract"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
destack_core = { workspace = true }
destack_heap = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
