[package]
name = "tspp_pattern"
description = "TS++ source patterns"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
tspp_artifact = { workspace = true }
tspp_artifact_macros = { workspace = true }
tspp_core = { workspace = true }
tspp_dir = { workspace = true }
tspp_parser = { workspace = true }
tspp_source = { workspace = true }

[dev-dependencies]
# language
tspp_formatter = { workspace = true }
tspp_repository = { workspace = true }
tspp_session = { workspace = true, features = ["native"] }

# general
futures = { workspace = true, features = ["executor"] }

[lints]
workspace = true
