[package]
name = "destack_language_libgen_rust"
description = "Destack Rust Library Code Generator"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"

[dependencies]
destack_language_lexer = { workspace = true }
destack_language_parser = { workspace = true }
destack_language_prelude = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }

[lints]
workspace = true
