# generated bridge target, do not edit

from .edit import (
    FilePatch,
    Patch,
    PatchSet,
    decode_file_patch,
    decode_patch,
    decode_patch_set,
    encode_file_patch,
    encode_patch,
    encode_patch_set,
)
from .text import (
    TextChange,
    TextPosition,
    TextRange,
    decode_text_change,
    decode_text_position,
    decode_text_range,
    encode_text_change,
    encode_text_position,
    encode_text_range,
)
from .update import (
    ByteRange,
    Edit,
    EditEditText,
    EditMove,
    EditRemove,
    EditSetBytes,
    EditSetText,
    TextPatch,
    decode_byte_range,
    decode_edit,
    decode_text_patch,
    encode_byte_range,
    encode_edit,
    encode_text_patch,
)

__all__ = [
    "PatchSet",
    "encode_patch_set",
    "decode_patch_set",
    "FilePatch",
    "encode_file_patch",
    "decode_file_patch",
    "Patch",
    "encode_patch",
    "decode_patch",
    "TextChange",
    "encode_text_change",
    "decode_text_change",
    "TextRange",
    "encode_text_range",
    "decode_text_range",
    "TextPosition",
    "encode_text_position",
    "decode_text_position",
    "Edit",
    "encode_edit",
    "decode_edit",
    "EditSetText",
    "EditEditText",
    "EditSetBytes",
    "EditRemove",
    "EditMove",
    "TextPatch",
    "encode_text_patch",
    "decode_text_patch",
    "ByteRange",
    "encode_byte_range",
    "decode_byte_range",
]
