set shell := ["bash", "-cu"]
set windows-shell := ["C:/Program Files/Git/bin/bash.exe", "-cu"]
set dotenv-load := true
set dotenv-filename := "../../.env.local"

_default:
    @just --list --unsorted

# init
init +deployment:
    bun run src/main.ts init {{deployment}}

# check
check:
    bun run destack-check format-check src/main.ts src/command src/deployment src/credential
    bun run tsc --project tsconfig.json
    bun run src/main.ts check

# format
format:
    bun run destack-check format src/main.ts src/command src/deployment src/credential
    bun run src/main.ts format

# diff
diff +deployment:
    bun run src/main.ts diff {{deployment}}

# deploy
deploy +deployment:
    bun run src/main.ts deploy {{deployment}}
