[package]
name = "tspp_artifact"
description = "TS++ Artifact"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[features]
schema = ["schemars"]

[dependencies]
# language
tspp_core = { workspace = true }
tspp_dir = { workspace = true }
tspp_js = { workspace = true }
tspp_mir = { workspace = true }
tspp_program = { workspace = true }
tspp_serde = { workspace = true }
tspp_source = { workspace = true }

# general
blake3 = { workspace = true }
crc32fast = { workspace = true }
dashmap = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
rustc-hash = { workspace = true }
siphasher = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true, features = ["preserve_order"] }
schemars = { workspace = true, optional = true }

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
fs2 = { workspace = true }

[lints]
workspace = true
