//! destack.core.builtin.universe@2025.08.15.1

#![destack::generated(destack.core.builtin.universe, file)]

use crate::{
    EnumType, HandleType, ModuleType, NodeType, ObjectKind, ObjectStability, StructType, TraitType,
    UniverseCategory, UniverseDomain,
};

#[destack::generated(ObjectKind, Debug, block)]
impl std::fmt::Debug for ObjectKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ObjectKind::Module => write!(f, "MODULE"),
            ObjectKind::Node => write!(f, "NODE"),
            ObjectKind::Struct => write!(f, "STRUCT"),
            ObjectKind::Handle => write!(f, "HANDLE"),
        }
    }
}

#[destack::generated(ModuleType, Debug, block)]
impl std::fmt::Debug for ModuleType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ModuleType::Root => write!(f, "ROOT"),
            ModuleType::Domain => write!(f, "DOMAIN"),
            ModuleType::Category => write!(f, "CATEGORY"),
            ModuleType::Object => write!(f, "OBJECT"),
        }
    }
}

#[destack::generated(EnumType, Debug, block)]
impl std::fmt::Debug for EnumType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EnumType::ObjectKind => write!(f, "OBJECT_KIND"),
            EnumType::ModuleType => write!(f, "MODULE_TYPE"),
            EnumType::EnumType => write!(f, "ENUM_TYPE"),
            EnumType::NodeType => write!(f, "NODE_TYPE"),
            EnumType::StructType => write!(f, "STRUCT_TYPE"),
            EnumType::TraitType => write!(f, "TRAIT_TYPE"),
            EnumType::HandleType => write!(f, "HANDLE_TYPE"),
            EnumType::ObjectStability => write!(f, "OBJECT_STABILITY"),
            EnumType::UniverseDomain => write!(f, "UNIVERSE_DOMAIN"),
            EnumType::UniverseCategory => write!(f, "UNIVERSE_CATEGORY"),
            EnumType::Materialization => write!(f, "MATERIALIZATION"),
            EnumType::ProcessFlag => write!(f, "PROCESS_FLAG"),
            EnumType::ExtensionFlag => write!(f, "EXTENSION_FLAG"),
            EnumType::RuntimePlatform => write!(f, "RUNTIME_PLATFORM"),
            EnumType::RuntimeLanguage => write!(f, "RUNTIME_LANGUAGE"),
            EnumType::RuntimeType => write!(f, "RUNTIME_TYPE"),
            EnumType::EventStatus => write!(f, "EVENT_STATUS"),
            EnumType::StringCasing => write!(f, "STRING_CASING"),
            EnumType::PrimitiveType => write!(f, "PRIMITIVE_TYPE"),
            EnumType::TypeCardinality => write!(f, "TYPE_CARDINALITY"),
            EnumType::ScalarType => write!(f, "SCALAR_TYPE"),
            EnumType::ValueFactory => write!(f, "VALUE_FACTORY"),
            EnumType::PropertyZone => write!(f, "PROPERTY_ZONE"),
            EnumType::ReferenceType => write!(f, "REFERENCE_TYPE"),
            EnumType::TextSpanType => write!(f, "TEXT_SPAN_TYPE"),
            EnumType::TextStyleFlag => write!(f, "TEXT_STYLE_FLAG"),
            EnumType::IconType => write!(f, "ICON_TYPE"),
            EnumType::ChangeType => write!(f, "CHANGE_TYPE"),
            EnumType::EditOperationType => write!(f, "EDIT_OPERATION_TYPE"),
            EnumType::ConditionalType => write!(f, "CONDITIONAL_TYPE"),
            EnumType::AggregationType => write!(f, "AGGREGATION_TYPE"),
            EnumType::SortMode => write!(f, "SORT_MODE"),
            EnumType::SortType => write!(f, "SORT_TYPE"),
            EnumType::JoinType => write!(f, "JOIN_TYPE"),
            EnumType::ExpressionType => write!(f, "EXPRESSION_TYPE"),
            EnumType::QueryType => write!(f, "QUERY_TYPE"),
            EnumType::Encoding => write!(f, "ENCODING"),
            EnumType::EncoderFlag => write!(f, "ENCODER_FLAG"),
            EnumType::EncoderStability => write!(f, "ENCODER_STABILITY"),
            EnumType::ClientType => write!(f, "CLIENT_TYPE"),
            EnumType::BranchType => write!(f, "BRANCH_TYPE"),
            EnumType::SnapshotType => write!(f, "SNAPSHOT_TYPE"),
            EnumType::SnapshotStatus => write!(f, "SNAPSHOT_STATUS"),
            EnumType::FolderType => write!(f, "FOLDER_TYPE"),
            EnumType::IndexType => write!(f, "INDEX_TYPE"),
            EnumType::ConstraintType => write!(f, "CONSTRAINT_TYPE"),
            EnumType::MigrationType => write!(f, "MIGRATION_TYPE"),
            EnumType::RunStatus => write!(f, "RUN_STATUS"),
            EnumType::FunctionOperator => write!(f, "FUNCTION_OPERATOR"),
            EnumType::MethodType => write!(f, "METHOD_TYPE"),
            EnumType::ActionType => write!(f, "ACTION_TYPE"),
            EnumType::TriggerType => write!(f, "TRIGGER_TYPE"),
            EnumType::TimerType => write!(f, "TIMER_TYPE"),
            EnumType::DayOfWeek => write!(f, "DAY_OF_WEEK"),
            EnumType::Month => write!(f, "MONTH"),
            EnumType::ScheduleFrequency => write!(f, "SCHEDULE_FREQUENCY"),
            EnumType::LogLevel => write!(f, "LOG_LEVEL"),
            EnumType::RoleType => write!(f, "ROLE_TYPE"),
            EnumType::SanctionType => write!(f, "SANCTION_TYPE"),
            EnumType::EntitlementType => write!(f, "ENTITLEMENT_TYPE"),
            EnumType::NotificationStatus => write!(f, "NOTIFICATION_STATUS"),
            EnumType::RigidMotionMode => write!(f, "RIGID_MOTION_MODE"),
            EnumType::JointFlag => write!(f, "JOINT_FLAG"),
            EnumType::MouseButton => write!(f, "MOUSE_BUTTON"),
            EnumType::TransitionType => write!(f, "TRANSITION_TYPE"),
            EnumType::SpringType => write!(f, "SPRING_TYPE"),
            EnumType::EffectType => write!(f, "EFFECT_TYPE"),
            EnumType::RepeatType => write!(f, "REPEAT_TYPE"),
            EnumType::Easing => write!(f, "EASING"),
            EnumType::TextSplitType => write!(f, "TEXT_SPLIT_TYPE"),
            EnumType::OffscreenBehavior => write!(f, "OFFSCREEN_BEHAVIOR"),
            EnumType::ColorType => write!(f, "COLOR_TYPE"),
            EnumType::ColorShade => write!(f, "COLOR_SHADE"),
            EnumType::ColorHue => write!(f, "COLOR_HUE"),
            EnumType::ColorIntent => write!(f, "COLOR_INTENT"),
            EnumType::FillType => write!(f, "FILL_TYPE"),
            EnumType::FillPosition => write!(f, "FILL_POSITION"),
            EnumType::FillSize => write!(f, "FILL_SIZE"),
            EnumType::FontType => write!(f, "FONT_TYPE"),
            EnumType::FontWeight => write!(f, "FONT_WEIGHT"),
            EnumType::FontSize => write!(f, "FONT_SIZE"),
            EnumType::TextAlign => write!(f, "TEXT_ALIGN"),
            EnumType::TextDecoration => write!(f, "TEXT_DECORATION"),
            EnumType::TextTransform => write!(f, "TEXT_TRANSFORM"),
            EnumType::BorderType => write!(f, "BORDER_TYPE"),
            EnumType::ShadowType => write!(f, "SHADOW_TYPE"),
            EnumType::ShadowPosition => write!(f, "SHADOW_POSITION"),
            EnumType::GradientType => write!(f, "GRADIENT_TYPE"),
            EnumType::StrokeType => write!(f, "STROKE_TYPE"),
            EnumType::LengthType => write!(f, "LENGTH_TYPE"),
            EnumType::Layout => write!(f, "LAYOUT"),
            EnumType::Distribute => write!(f, "DISTRIBUTE"),
            EnumType::Align => write!(f, "ALIGN"),
            EnumType::Direction => write!(f, "DIRECTION"),
            EnumType::Overflow => write!(f, "OVERFLOW"),
            EnumType::Anchor => write!(f, "ANCHOR"),
            EnumType::Region => write!(f, "REGION"),
            EnumType::RegionArea => write!(f, "REGION_AREA"),
            EnumType::RegionContinent => write!(f, "REGION_CONTINENT"),
            EnumType::MachineType => write!(f, "MACHINE_TYPE"),
        }
    }
}

#[destack::generated(NodeType, Debug, block)]
impl std::fmt::Debug for NodeType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            NodeType::Node => write!(f, "NODE"),
            NodeType::Entity => write!(f, "ENTITY"),
            NodeType::Event => write!(f, "EVENT"),
            NodeType::ChangeEvent => write!(f, "CHANGE_EVENT"),
            NodeType::Universe => write!(f, "UNIVERSE"),
            NodeType::User => write!(f, "USER"),
            NodeType::Client => write!(f, "CLIENT"),
            NodeType::Organization => write!(f, "ORGANIZATION"),
            NodeType::Team => write!(f, "TEAM"),
            NodeType::Space => write!(f, "SPACE"),
            NodeType::Branch => write!(f, "BRANCH"),
            NodeType::Snapshot => write!(f, "SNAPSHOT"),
            NodeType::Folder => write!(f, "FOLDER"),
            NodeType::CustomEventDefinition => write!(f, "CUSTOM_EVENT_DEFINITION"),
            NodeType::CustomStructDefinition => write!(f, "CUSTOM_STRUCT_DEFINITION"),
            NodeType::CustomErrorDefinition => write!(f, "CUSTOM_ERROR_DEFINITION"),
            NodeType::CustomMessageDefinition => write!(f, "CUSTOM_MESSAGE_DEFINITION"),
            NodeType::CustomEnumDefinition => write!(f, "CUSTOM_ENUM_DEFINITION"),
            NodeType::CustomPropertyDefinition => write!(f, "CUSTOM_PROPERTY_DEFINITION"),
            NodeType::CustomOptionDefinition => write!(f, "CUSTOM_OPTION_DEFINITION"),
            NodeType::Tag => write!(f, "TAG"),
            NodeType::Index => write!(f, "INDEX"),
            NodeType::Constraint => write!(f, "CONSTRAINT"),
            NodeType::Migration => write!(f, "MIGRATION"),
            NodeType::MigrationOperation => write!(f, "MIGRATION_OPERATION"),
            NodeType::File => write!(f, "FILE"),
            NodeType::Environment => write!(f, "ENVIRONMENT"),
            NodeType::Script => write!(f, "SCRIPT"),
            NodeType::CustomEvent => write!(f, "CUSTOM_EVENT"),
            NodeType::Function => write!(f, "FUNCTION"),
            NodeType::Method => write!(f, "METHOD"),
            NodeType::Action => write!(f, "ACTION"),
            NodeType::Trigger => write!(f, "TRIGGER"),
            NodeType::TriggerEvent => write!(f, "TRIGGER_EVENT"),
            NodeType::Timer => write!(f, "TIMER"),
            NodeType::TimerEvent => write!(f, "TIMER_EVENT"),
            NodeType::TimerStartedEvent => write!(f, "TIMER_STARTED_EVENT"),
            NodeType::TimerPausedEvent => write!(f, "TIMER_PAUSED_EVENT"),
            NodeType::TimerResumedEvent => write!(f, "TIMER_RESUMED_EVENT"),
            NodeType::TimerCompletedEvent => write!(f, "TIMER_COMPLETED_EVENT"),
            NodeType::TimerCancelledEvent => write!(f, "TIMER_CANCELLED_EVENT"),
            NodeType::Run => write!(f, "RUN"),
            NodeType::RunEvent => write!(f, "RUN_EVENT"),
            NodeType::RunStartedEvent => write!(f, "RUN_STARTED_EVENT"),
            NodeType::RunPauseRequestedEvent => write!(f, "RUN_PAUSE_REQUESTED_EVENT"),
            NodeType::RunPausedEvent => write!(f, "RUN_PAUSED_EVENT"),
            NodeType::RunResumeRequestedEvent => write!(f, "RUN_RESUME_REQUESTED_EVENT"),
            NodeType::RunResumedEvent => write!(f, "RUN_RESUMED_EVENT"),
            NodeType::RunStopRequestedEvent => write!(f, "RUN_STOP_REQUESTED_EVENT"),
            NodeType::RunFailedEvent => write!(f, "RUN_FAILED_EVENT"),
            NodeType::RunCompletedEvent => write!(f, "RUN_COMPLETED_EVENT"),
            NodeType::SpanEvent => write!(f, "SPAN_EVENT"),
            NodeType::LogEvent => write!(f, "LOG_EVENT"),
            NodeType::Permission => write!(f, "PERMISSION"),
            NodeType::Membership => write!(f, "MEMBERSHIP"),
            NodeType::MembershipEvent => write!(f, "MEMBERSHIP_EVENT"),
            NodeType::MembershipJoinedEvent => write!(f, "MEMBERSHIP_JOINED_EVENT"),
            NodeType::MembershipLeftEvent => write!(f, "MEMBERSHIP_LEFT_EVENT"),
            NodeType::Invite => write!(f, "INVITE"),
            NodeType::InviteEvent => write!(f, "INVITE_EVENT"),
            NodeType::InviteSentEvent => write!(f, "INVITE_SENT_EVENT"),
            NodeType::InviteRescindedEvent => write!(f, "INVITE_RESCINDED_EVENT"),
            NodeType::InviteAcceptedEvent => write!(f, "INVITE_ACCEPTED_EVENT"),
            NodeType::InviteRejectedEvent => write!(f, "INVITE_REJECTED_EVENT"),
            NodeType::Role => write!(f, "ROLE"),
            NodeType::RoleEvent => write!(f, "ROLE_EVENT"),
            NodeType::RoleAssignedEvent => write!(f, "ROLE_ASSIGNED_EVENT"),
            NodeType::RoleUnassignedEvent => write!(f, "ROLE_UNASSIGNED_EVENT"),
            NodeType::Sanction => write!(f, "SANCTION"),
            NodeType::SanctionEvent => write!(f, "SANCTION_EVENT"),
            NodeType::SanctionRequestedEvent => write!(f, "SANCTION_REQUESTED_EVENT"),
            NodeType::SanctionGrantedEvent => write!(f, "SANCTION_GRANTED_EVENT"),
            NodeType::SanctionRevokedEvent => write!(f, "SANCTION_REVOKED_EVENT"),
            NodeType::SanctionExpiredEvent => write!(f, "SANCTION_EXPIRED_EVENT"),
            NodeType::Entitlement => write!(f, "ENTITLEMENT"),
            NodeType::EntitlementEvent => write!(f, "ENTITLEMENT_EVENT"),
            NodeType::EntitlementRequestedEvent => write!(f, "ENTITLEMENT_REQUESTED_EVENT"),
            NodeType::EntitlementGrantedEvent => write!(f, "ENTITLEMENT_GRANTED_EVENT"),
            NodeType::EntitlementRevokedEvent => write!(f, "ENTITLEMENT_REVOKED_EVENT"),
            NodeType::EntitlementExpiredEvent => write!(f, "ENTITLEMENT_EXPIRED_EVENT"),
            NodeType::Star => write!(f, "STAR"),
            NodeType::StarEvent => write!(f, "STAR_EVENT"),
            NodeType::StarAddedEvent => write!(f, "STAR_ADDED_EVENT"),
            NodeType::StarRemovedEvent => write!(f, "STAR_REMOVED_EVENT"),
            NodeType::Reaction => write!(f, "REACTION"),
            NodeType::ReactionEvent => write!(f, "REACTION_EVENT"),
            NodeType::ReactionAddedEvent => write!(f, "REACTION_ADDED_EVENT"),
            NodeType::ReactionRemovedEvent => write!(f, "REACTION_REMOVED_EVENT"),
            NodeType::Follow => write!(f, "FOLLOW"),
            NodeType::FollowEvent => write!(f, "FOLLOW_EVENT"),
            NodeType::FollowAddedEvent => write!(f, "FOLLOW_ADDED_EVENT"),
            NodeType::FollowRemovedEvent => write!(f, "FOLLOW_REMOVED_EVENT"),
            NodeType::Notification => write!(f, "NOTIFICATION"),
            NodeType::NotificationEvent => write!(f, "NOTIFICATION_EVENT"),
            NodeType::NotificationSentEvent => write!(f, "NOTIFICATION_SENT_EVENT"),
            NodeType::NotificationRescindedEvent => write!(f, "NOTIFICATION_RESCINDED_EVENT"),
            NodeType::NotificationReadEvent => write!(f, "NOTIFICATION_READ_EVENT"),
            NodeType::NotificationDismissedEvent => write!(f, "NOTIFICATION_DISMISSED_EVENT"),
            NodeType::NotificationExpiredEvent => write!(f, "NOTIFICATION_EXPIRED_EVENT"),
            NodeType::Entity2D => write!(f, "ENTITY2D"),
            NodeType::Shape2D => write!(f, "SHAPE2D"),
            NodeType::PointShape2D => write!(f, "POINT_SHAPE2D"),
            NodeType::CircleShape2D => write!(f, "CIRCLE_SHAPE2D"),
            NodeType::CapsuleShape2D => write!(f, "CAPSULE_SHAPE2D"),
            NodeType::RectangleShape2D => write!(f, "RECTANGLE_SHAPE2D"),
            NodeType::SegmentShape2D => write!(f, "SEGMENT_SHAPE2D"),
            NodeType::PathShape2D => write!(f, "PATH_SHAPE2D"),
            NodeType::EllipseShape2D => write!(f, "ELLIPSE_SHAPE2D"),
            NodeType::HalfspaceShape2D => write!(f, "HALFSPACE_SHAPE2D"),
            NodeType::ConvexShape2D => write!(f, "CONVEX_SHAPE2D"),
            NodeType::MeshShape2D => write!(f, "MESH_SHAPE2D"),
            NodeType::Entity3D => write!(f, "ENTITY3D"),
            NodeType::Shape3D => write!(f, "SHAPE3D"),
            NodeType::PointShape3D => write!(f, "POINT_SHAPE3D"),
            NodeType::SphereShape3D => write!(f, "SPHERE_SHAPE3D"),
            NodeType::CapsuleShape3D => write!(f, "CAPSULE_SHAPE3D"),
            NodeType::BoxShape3D => write!(f, "BOX_SHAPE3D"),
            NodeType::SegmentShape3D => write!(f, "SEGMENT_SHAPE3D"),
            NodeType::PolylineShape3D => write!(f, "POLYLINE_SHAPE3D"),
            NodeType::EllipsoidShape3D => write!(f, "ELLIPSOID_SHAPE3D"),
            NodeType::CylinderShape3D => write!(f, "CYLINDER_SHAPE3D"),
            NodeType::ConeShape3D => write!(f, "CONE_SHAPE3D"),
            NodeType::PlaneShape3D => write!(f, "PLANE_SHAPE3D"),
            NodeType::ConvexShape3D => write!(f, "CONVEX_SHAPE3D"),
            NodeType::MeshShape3D => write!(f, "MESH_SHAPE3D"),
            NodeType::Body2D => write!(f, "BODY2D"),
            NodeType::BodyEvent => write!(f, "BODY_EVENT"),
            NodeType::BodySleepEvent => write!(f, "BODY_SLEEP_EVENT"),
            NodeType::BodyWakeEvent => write!(f, "BODY_WAKE_EVENT"),
            NodeType::RigidBody2D => write!(f, "RIGID_BODY2D"),
            NodeType::SoftBody2D => write!(f, "SOFT_BODY2D"),
            NodeType::Joint2D => write!(f, "JOINT2D"),
            NodeType::JointEvent => write!(f, "JOINT_EVENT"),
            NodeType::JointBreakEvent => write!(f, "JOINT_BREAK_EVENT"),
            NodeType::HingeJoint2D => write!(f, "HINGE_JOINT2D"),
            NodeType::PrismaticJoint2D => write!(f, "PRISMATIC_JOINT2D"),
            NodeType::FixedJoint2D => write!(f, "FIXED_JOINT2D"),
            NodeType::RopeJoint2D => write!(f, "ROPE_JOINT2D"),
            NodeType::WheelJoint2D => write!(f, "WHEEL_JOINT2D"),
            NodeType::Body3D => write!(f, "BODY3D"),
            NodeType::RigidBody3D => write!(f, "RIGID_BODY3D"),
            NodeType::SoftBody3D => write!(f, "SOFT_BODY3D"),
            NodeType::Joint3D => write!(f, "JOINT3D"),
            NodeType::HingeJoint3D => write!(f, "HINGE_JOINT3D"),
            NodeType::PrismaticJoint3D => write!(f, "PRISMATIC_JOINT3D"),
            NodeType::FixedJoint3D => write!(f, "FIXED_JOINT3D"),
            NodeType::RopeJoint3D => write!(f, "ROPE_JOINT3D"),
            NodeType::WheelJoint3D => write!(f, "WHEEL_JOINT3D"),
            NodeType::SphericalJoint3D => write!(f, "SPHERICAL_JOINT3D"),
            NodeType::Collider2D => write!(f, "COLLIDER2D"),
            NodeType::ColliderEvent => write!(f, "COLLIDER_EVENT"),
            NodeType::ColliderContactEvent => write!(f, "COLLIDER_CONTACT_EVENT"),
            NodeType::Collider3D => write!(f, "COLLIDER3D"),
            NodeType::InputEvent => write!(f, "INPUT_EVENT"),
            NodeType::Pointer2D => write!(f, "POINTER2D"),
            NodeType::PointerEvent => write!(f, "POINTER_EVENT"),
            NodeType::PointerDownEvent => write!(f, "POINTER_DOWN_EVENT"),
            NodeType::PointerUpEvent => write!(f, "POINTER_UP_EVENT"),
            NodeType::PointerMoveEvent => write!(f, "POINTER_MOVE_EVENT"),
            NodeType::PointerEnterEvent => write!(f, "POINTER_ENTER_EVENT"),
            NodeType::PointerOverEvent => write!(f, "POINTER_OVER_EVENT"),
            NodeType::PointerLeaveEvent => write!(f, "POINTER_LEAVE_EVENT"),
            NodeType::PointerLongPressEvent => write!(f, "POINTER_LONG_PRESS_EVENT"),
            NodeType::Mouse2D => write!(f, "MOUSE2D"),
            NodeType::MouseEvent => write!(f, "MOUSE_EVENT"),
            NodeType::ClickEvent => write!(f, "CLICK_EVENT"),
            NodeType::SingleClickEvent => write!(f, "SINGLE_CLICK_EVENT"),
            NodeType::DoubleClickEvent => write!(f, "DOUBLE_CLICK_EVENT"),
            NodeType::TripleClickEvent => write!(f, "TRIPLE_CLICK_EVENT"),
            NodeType::WheelEvent => write!(f, "WHEEL_EVENT"),
            NodeType::KeyEvent => write!(f, "KEY_EVENT"),
            NodeType::KeyDownEvent => write!(f, "KEY_DOWN_EVENT"),
            NodeType::KeyUpEvent => write!(f, "KEY_UP_EVENT"),
            NodeType::KeyPressEvent => write!(f, "KEY_PRESS_EVENT"),
            NodeType::DragEvent => write!(f, "DRAG_EVENT"),
            NodeType::DragStartEvent => write!(f, "DRAG_START_EVENT"),
            NodeType::DragEndEvent => write!(f, "DRAG_END_EVENT"),
            NodeType::DragOverEvent => write!(f, "DRAG_OVER_EVENT"),
            NodeType::DragEnterEvent => write!(f, "DRAG_ENTER_EVENT"),
            NodeType::DragLeaveEvent => write!(f, "DRAG_LEAVE_EVENT"),
            NodeType::DropEvent => write!(f, "DROP_EVENT"),
            NodeType::ClipboardEvent => write!(f, "CLIPBOARD_EVENT"),
            NodeType::CopyEvent => write!(f, "COPY_EVENT"),
            NodeType::CutEvent => write!(f, "CUT_EVENT"),
            NodeType::PasteEvent => write!(f, "PASTE_EVENT"),
            NodeType::FocusEvent => write!(f, "FOCUS_EVENT"),
            NodeType::FocusInEvent => write!(f, "FOCUS_IN_EVENT"),
            NodeType::FocusOutEvent => write!(f, "FOCUS_OUT_EVENT"),
            NodeType::Audio => write!(f, "AUDIO"),
            NodeType::Image => write!(f, "IMAGE"),
            NodeType::Video => write!(f, "VIDEO"),
            NodeType::Model => write!(f, "MODEL"),
            NodeType::TransitionTemplate => write!(f, "TRANSITION_TEMPLATE"),
            NodeType::EffectTemplate => write!(f, "EFFECT_TEMPLATE"),
            NodeType::Theme => write!(f, "THEME"),
            NodeType::Palette => write!(f, "PALETTE"),
            NodeType::Style => write!(f, "STYLE"),
            NodeType::ColorStyle => write!(f, "COLOR_STYLE"),
            NodeType::FillStyle => write!(f, "FILL_STYLE"),
            NodeType::FontStyle => write!(f, "FONT_STYLE"),
            NodeType::BorderStyle => write!(f, "BORDER_STYLE"),
            NodeType::ShadowStyle => write!(f, "SHADOW_STYLE"),
            NodeType::GradientStyle => write!(f, "GRADIENT_STYLE"),
            NodeType::StrokeStyle => write!(f, "STROKE_STYLE"),
            NodeType::Document => write!(f, "DOCUMENT"),
            NodeType::Stage => write!(f, "STAGE"),
            NodeType::Scene => write!(f, "SCENE"),
            NodeType::SceneEvent => write!(f, "SCENE_EVENT"),
            NodeType::Layer => write!(f, "LAYER"),
            NodeType::View2D => write!(f, "VIEW2D"),
            NodeType::LayoutView2D => write!(f, "LAYOUT_VIEW2D"),
            NodeType::FrameView2D => write!(f, "FRAME_VIEW2D"),
            NodeType::LabelView2D => write!(f, "LABEL_VIEW2D"),
            NodeType::SplitView2D => write!(f, "SPLIT_VIEW2D"),
            NodeType::ContentView2D => write!(f, "CONTENT_VIEW2D"),
            NodeType::TextView2D => write!(f, "TEXT_VIEW2D"),
            NodeType::InputView2D => write!(f, "INPUT_VIEW2D"),
            NodeType::NumberInputView2D => write!(f, "NUMBER_INPUT_VIEW2D"),
            NodeType::SliderInputView2D => write!(f, "SLIDER_INPUT_VIEW2D"),
            NodeType::Machine => write!(f, "MACHINE"),
            NodeType::Metric => write!(f, "METRIC"),
            NodeType::MeasurementEvent => write!(f, "MEASUREMENT_EVENT"),
            NodeType::GaugeMetric => write!(f, "GAUGE_METRIC"),
            NodeType::GaugeMeasurementEvent => write!(f, "GAUGE_MEASUREMENT_EVENT"),
            NodeType::CounterMetric => write!(f, "COUNTER_METRIC"),
            NodeType::CounterMeasurementEvent => write!(f, "COUNTER_MEASUREMENT_EVENT"),
            NodeType::HistogramMetric => write!(f, "HISTOGRAM_METRIC"),
            NodeType::HistogramMeasurementEvent => write!(f, "HISTOGRAM_MEASUREMENT_EVENT"),
            NodeType::Locale => write!(f, "LOCALE"),
        }
    }
}

#[destack::generated(StructType, Debug, block)]
impl std::fmt::Debug for StructType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            StructType::Struct => write!(f, "STRUCT"),
            StructType::Error => write!(f, "ERROR"),
            StructType::Message => write!(f, "MESSAGE"),
            StructType::Definition => write!(f, "DEFINITION"),
            StructType::SchemaDefinition => write!(f, "SCHEMA_DEFINITION"),
            StructType::ModuleDefinition => write!(f, "MODULE_DEFINITION"),
            StructType::ObjectDefinition => write!(f, "OBJECT_DEFINITION"),
            StructType::NodeDefinition => write!(f, "NODE_DEFINITION"),
            StructType::StructDefinition => write!(f, "STRUCT_DEFINITION"),
            StructType::HandleDefinition => write!(f, "HANDLE_DEFINITION"),
            StructType::EnumDefinition => write!(f, "ENUM_DEFINITION"),
            StructType::PropertyDefinition => write!(f, "PROPERTY_DEFINITION"),
            StructType::ConstantDefinition => write!(f, "CONSTANT_DEFINITION"),
            StructType::OptionDefinition => write!(f, "OPTION_DEFINITION"),
            StructType::Type => write!(f, "TYPE"),
            StructType::NumberConstraint => write!(f, "NUMBER_CONSTRAINT"),
            StructType::StringConstraint => write!(f, "STRING_CONSTRAINT"),
            StructType::CollectionConstraint => write!(f, "COLLECTION_CONSTRAINT"),
            StructType::Value => write!(f, "VALUE"),
            StructType::NamedValue => write!(f, "NAMED_VALUE"),
            StructType::Expression => write!(f, "EXPRESSION"),
            StructType::Join => write!(f, "JOIN"),
            StructType::Aggregation => write!(f, "AGGREGATION"),
            StructType::Condition => write!(f, "CONDITION"),
            StructType::Sort => write!(f, "SORT"),
            StructType::Select => write!(f, "SELECT"),
            StructType::Query => write!(f, "QUERY"),
            StructType::NodeIdentityReference => write!(f, "NODE_IDENTITY_REFERENCE"),
            StructType::NodeSpatialReference => write!(f, "NODE_SPATIAL_REFERENCE"),
            StructType::NodeTemporalReference => write!(f, "NODE_TEMPORAL_REFERENCE"),
            StructType::ObjectDefinitionReference => write!(f, "OBJECT_DEFINITION_REFERENCE"),
            StructType::PropertyReference => write!(f, "PROPERTY_REFERENCE"),
            StructType::Text => write!(f, "TEXT"),
            StructType::TextSpan => write!(f, "TEXT_SPAN"),
            StructType::Icon => write!(f, "ICON"),
            StructType::EditOperation => write!(f, "EDIT_OPERATION"),
            StructType::UniverseSignupRequest => write!(f, "UNIVERSE_SIGNUP_REQUEST"),
            StructType::UniverseSignupResponse => write!(f, "UNIVERSE_SIGNUP_RESPONSE"),
            StructType::UniverseSpawnRequest => write!(f, "UNIVERSE_SPAWN_REQUEST"),
            StructType::UniverseSpawnResponse => write!(f, "UNIVERSE_SPAWN_RESPONSE"),
            StructType::CustomStruct => write!(f, "CUSTOM_STRUCT"),
            StructType::CustomError => write!(f, "CUSTOM_ERROR"),
            StructType::CustomMessage => write!(f, "CUSTOM_MESSAGE"),
            StructType::TagDefinition => write!(f, "TAG_DEFINITION"),
            StructType::IndexDefinition => write!(f, "INDEX_DEFINITION"),
            StructType::ConstraintDefinition => write!(f, "CONSTRAINT_DEFINITION"),
            StructType::MigrationDefinition => write!(f, "MIGRATION_DEFINITION"),
            StructType::MigrationOperationDefinition => write!(f, "MIGRATION_OPERATION_DEFINITION"),
            StructType::Schedule => write!(f, "SCHEDULE"),
            StructType::FunctionDefinition => write!(f, "FUNCTION_DEFINITION"),
            StructType::MethodDefinition => write!(f, "METHOD_DEFINITION"),
            StructType::ActionDefinition => write!(f, "ACTION_DEFINITION"),
            StructType::PermissionDefinition => write!(f, "PERMISSION_DEFINITION"),
            StructType::Vector2 => write!(f, "VECTOR2"),
            StructType::Vector2I => write!(f, "VECTOR2I"),
            StructType::Vector3 => write!(f, "VECTOR3"),
            StructType::Vector3I => write!(f, "VECTOR3I"),
            StructType::Vector4 => write!(f, "VECTOR4"),
            StructType::Vector4I => write!(f, "VECTOR4I"),
            StructType::Quaternion => write!(f, "QUATERNION"),
            StructType::Mesh2 => write!(f, "MESH2"),
            StructType::Mesh3 => write!(f, "MESH3"),
            StructType::Form2D => write!(f, "FORM2D"),
            StructType::Point2D => write!(f, "POINT2D"),
            StructType::Circle2D => write!(f, "CIRCLE2D"),
            StructType::Capsule2D => write!(f, "CAPSULE2D"),
            StructType::Rectangle2D => write!(f, "RECTANGLE2D"),
            StructType::Segment2D => write!(f, "SEGMENT2D"),
            StructType::Path2D => write!(f, "PATH2D"),
            StructType::Ellipse2D => write!(f, "ELLIPSE2D"),
            StructType::Halfspace2D => write!(f, "HALFSPACE2D"),
            StructType::Form3D => write!(f, "FORM3D"),
            StructType::Point3D => write!(f, "POINT3D"),
            StructType::Sphere3D => write!(f, "SPHERE3D"),
            StructType::Capsule3D => write!(f, "CAPSULE3D"),
            StructType::Box3D => write!(f, "BOX3D"),
            StructType::Segment3D => write!(f, "SEGMENT3D"),
            StructType::Polyline3D => write!(f, "POLYLINE3D"),
            StructType::Ellipsoid3D => write!(f, "ELLIPSOID3D"),
            StructType::Cylinder3D => write!(f, "CYLINDER3D"),
            StructType::Cone3D => write!(f, "CONE3D"),
            StructType::Plane3D => write!(f, "PLANE3D"),
            StructType::JointSpring => write!(f, "JOINT_SPRING"),
            StructType::JointScalarLimit => write!(f, "JOINT_SCALAR_LIMIT"),
            StructType::JointConeLimit => write!(f, "JOINT_CONE_LIMIT"),
            StructType::JointTwistLimit => write!(f, "JOINT_TWIST_LIMIT"),
            StructType::JointBreakLimit => write!(f, "JOINT_BREAK_LIMIT"),
            StructType::JointMotor => write!(f, "JOINT_MOTOR"),
            StructType::JointFrame2D => write!(f, "JOINT_FRAME2D"),
            StructType::JointFrame3D => write!(f, "JOINT_FRAME3D"),
            StructType::Transition => write!(f, "TRANSITION"),
            StructType::Effect => write!(f, "EFFECT"),
            StructType::Color => write!(f, "COLOR"),
            StructType::Fill => write!(f, "FILL"),
            StructType::Font => write!(f, "FONT"),
            StructType::Border => write!(f, "BORDER"),
            StructType::Shadow => write!(f, "SHADOW"),
            StructType::Gradient => write!(f, "GRADIENT"),
            StructType::GradientStop => write!(f, "GRADIENT_STOP"),
            StructType::Stroke => write!(f, "STROKE"),
            StructType::StrokeCap => write!(f, "STROKE_CAP"),
            StructType::StrokePath => write!(f, "STROKE_PATH"),
            StructType::StrokePoint => write!(f, "STROKE_POINT"),
            StructType::Length => write!(f, "LENGTH"),
            StructType::Offset2 => write!(f, "OFFSET2"),
            StructType::Grid2 => write!(f, "GRID2"),
            StructType::GridSpan2 => write!(f, "GRID_SPAN2"),
            StructType::Inset2 => write!(f, "INSET2"),
            StructType::Corner2 => write!(f, "CORNER2"),
            StructType::Axis2 => write!(f, "AXIS2"),
            StructType::Axis3 => write!(f, "AXIS3"),
        }
    }
}

#[destack::generated(TraitType, Debug, block)]
impl std::fmt::Debug for TraitType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TraitType::Ordered => write!(f, "ORDERED"),
            TraitType::Resource => write!(f, "RESOURCE"),
            TraitType::Variant => write!(f, "VARIANT"),
            TraitType::Template => write!(f, "TEMPLATE"),
            TraitType::Runnable => write!(f, "RUNNABLE"),
            TraitType::Ownable => write!(f, "OWNABLE"),
            TraitType::Owned => write!(f, "OWNED"),
            TraitType::Joinable => write!(f, "JOINABLE"),
            TraitType::Actor => write!(f, "ACTOR"),
            TraitType::Starable => write!(f, "STARABLE"),
            TraitType::Reactable => write!(f, "REACTABLE"),
            TraitType::Followable => write!(f, "FOLLOWABLE"),
            TraitType::Interactive => write!(f, "INTERACTIVE"),
            TraitType::Draggable => write!(f, "DRAGGABLE"),
            TraitType::Selectable => write!(f, "SELECTABLE"),
        }
    }
}

#[destack::generated(HandleType, Debug, block)]
impl std::fmt::Debug for HandleType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            HandleType::Handle => write!(f, "HANDLE"),
            HandleType::Graph => write!(f, "GRAPH"),
            HandleType::Session => write!(f, "SESSION"),
            HandleType::Context => write!(f, "CONTEXT"),
            HandleType::Logger => write!(f, "LOGGER"),
            HandleType::Tracer => write!(f, "TRACER"),
        }
    }
}

#[destack::generated(ObjectStability, Debug, block)]
impl std::fmt::Debug for ObjectStability {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ObjectStability::Dynamic => write!(f, "DYNAMIC"),
            ObjectStability::Static => write!(f, "STATIC"),
        }
    }
}

#[destack::generated(UniverseDomain, Debug, block)]
impl std::fmt::Debug for UniverseDomain {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            UniverseDomain::Core => write!(f, "CORE"),
            UniverseDomain::Basics => write!(f, "BASICS"),
            UniverseDomain::Simulation => write!(f, "SIMULATION"),
            UniverseDomain::Imagination => write!(f, "IMAGINATION"),
            UniverseDomain::Presentation => write!(f, "PRESENTATION"),
            UniverseDomain::Production => write!(f, "PRODUCTION"),
            UniverseDomain::Distribution => write!(f, "DISTRIBUTION"),
        }
    }
}

#[destack::generated(UniverseCategory, Debug, block)]
impl std::fmt::Debug for UniverseCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            UniverseCategory::Builtin => write!(f, "BUILTIN"),
            UniverseCategory::Definition => write!(f, "DEFINITION"),
            UniverseCategory::Common => write!(f, "COMMON"),
            UniverseCategory::Encoding => write!(f, "ENCODING"),
            UniverseCategory::Persistence => write!(f, "PERSISTENCE"),
            UniverseCategory::Generation => write!(f, "GENERATION"),
            UniverseCategory::Local => write!(f, "LOCAL"),
            UniverseCategory::Universe => write!(f, "UNIVERSE"),
            UniverseCategory::Space => write!(f, "SPACE"),
            UniverseCategory::Entity => write!(f, "ENTITY"),
            UniverseCategory::Script => write!(f, "SCRIPT"),
            UniverseCategory::Intelligence => write!(f, "INTELLIGENCE"),
            UniverseCategory::Access => write!(f, "ACCESS"),
            UniverseCategory::Quality => write!(f, "QUALITY"),
            UniverseCategory::Social => write!(f, "SOCIAL"),
            UniverseCategory::Finance => write!(f, "FINANCE"),
            UniverseCategory::Studio => write!(f, "STUDIO"),
            UniverseCategory::Geometry => write!(f, "GEOMETRY"),
            UniverseCategory::Geography => write!(f, "GEOGRAPHY"),
            UniverseCategory::Physics => write!(f, "PHYSICS"),
            UniverseCategory::Perception => write!(f, "PERCEPTION"),
            UniverseCategory::Audio => write!(f, "AUDIO"),
            UniverseCategory::Image => write!(f, "IMAGE"),
            UniverseCategory::Video => write!(f, "VIDEO"),
            UniverseCategory::Model => write!(f, "MODEL"),
            UniverseCategory::Paint => write!(f, "PAINT"),
            UniverseCategory::Animation => write!(f, "ANIMATION"),
            UniverseCategory::Style => write!(f, "STYLE"),
            UniverseCategory::Document => write!(f, "DOCUMENT"),
            UniverseCategory::Scene => write!(f, "SCENE"),
            UniverseCategory::View => write!(f, "VIEW"),
            UniverseCategory::Rendering => write!(f, "RENDERING"),
            UniverseCategory::Camera => write!(f, "CAMERA"),
            UniverseCategory::Shaders => write!(f, "SHADERS"),
            UniverseCategory::Material => write!(f, "MATERIAL"),
            UniverseCategory::Lighting => write!(f, "LIGHTING"),
            UniverseCategory::Cloud => write!(f, "CLOUD"),
            UniverseCategory::Observability => write!(f, "OBSERVABILITY"),
            UniverseCategory::Experience => write!(f, "EXPERIENCE"),
            UniverseCategory::Localization => write!(f, "LOCALIZATION"),
            UniverseCategory::Legal => write!(f, "LEGAL"),
            UniverseCategory::Commerce => write!(f, "COMMERCE"),
        }
    }
}
