import { expect, test } from "bun:test";

import {
  artifact,
  core,
  decodeValue,
  dir,
  encodeValue,
  repository,
  source,
} from "../dist/index.js";

test("serde roundtrips content through binary and JSON codecs", () => {
  const value = source.Content.binary(new Uint8Array([1, 2, 3]));

  // roundtrip through the binary codec generated from the reflected model
  const bytes = encodeValue((writer) => source.Content.encode(writer, value));
  const decoded = decodeValue(bytes, (reader) => source.Content.decode(reader));

  // roundtrip through the JSON codec generated from the same model
  const json = source.Content.toJson(value);
  const parsed = source.Content.fromJson(json);

  expect(decoded.kind).toBe("binary");
  expect(Array.from(decoded.content)).toEqual([1, 2, 3]);
  expect(Array.from(parsed.content)).toEqual([1, 2, 3]);
});

test("serde roundtrips artifact keys through binary and JSON codecs", () => {
  const packageId = 1n;
  const module = {
    packageId,
    moduleKey: 2n,
  };
  const profile = 3n;
  const target = {
    packageId,
    targetKey: 4n,
  };
  const key = artifact.ArtifactKey.mirLowered(module, profile, target);

  // preserve a nested cross-crate artifact key through binary serde
  const bytes = encodeValue((writer) => artifact.ArtifactKey.encode(writer, key));
  const decoded = decodeValue(bytes, (reader) => artifact.ArtifactKey.decode(reader));

  // preserve the same nested value through JSON serde
  const json = artifact.ArtifactKey.toJson(key);
  const parsed = artifact.ArtifactKey.fromJson(json);

  expect(decoded).toEqual(key);
  expect(parsed).toEqual(key);
});

test("serde roundtrips fixed revisions through binary and JSON codecs", () => {
  const value = {
    value: new Uint8Array(32).fill(9),
  };

  // fixed-size byte identities should remain byte identities
  const bytes = encodeValue((writer) => repository.Revision.encode(writer, value));
  const decoded = decodeValue(bytes, (reader) => repository.Revision.decode(reader));

  // JSON keeps the same value using the generated byte representation
  const json = repository.Revision.toJson(value);
  const parsed = repository.Revision.fromJson(json);

  expect(Array.from(decoded.value)).toEqual(Array.from(value.value));
  expect(Array.from(parsed.value)).toEqual(Array.from(value.value));
});

test("serde resolves generated IR strings through a string pool", () => {
  const data = {
    strings: [
      [11n, "std"],
      [22n, "math"],
      [33n, "add"],
    ],
  };
  const path = {
    segments: [11n, 22n, 33n],
  };

  // resolve raw generated StringId values through the public pool helper
  const strings = core.StringPool.fromData(data);

  expect(dir.Path.lastSegment(path)).toBe(33n);
  expect(strings.get(22n)).toBe("math");
  expect(strings.values(path.segments)).toEqual(["std", "math", "add"]);
  expect(strings.join(path.segments, ".")).toBe("std.math.add");
  expect(strings.intern("add")).toBe(33n);
});
