// generated by generate-bindings: do not edit

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unreachable_pub)]

use crate::diagnostic::{RuntimeError, RuntimeResult};
use crate::platform::abi::{BindingAbi, NativeAbi, VmAbi};
use crate::platform::{
    PlatformError as AbiPlatformError, VmAggregateCodec, VmArray, VmSlice, VmValueCodec,
    error as platform_error,
};
use destack_vm as vm;
use serde::{Deserialize, Serialize};

/// ABI enum for PlatformErrorCode.
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlatformErrorCode {
    /// InvalidArgument.
    InvalidArgument = 1000,
    /// InvalidArgumentType.
    InvalidArgumentType = 1001,
    /// InvalidArgumentValue.
    InvalidArgumentValue = 1002,
    /// NullPointer.
    NullPointer = 1100,
    /// NotSupported.
    NotSupported = 1200,
    /// Io.
    Io = 2000,
    /// IoReadFailed.
    IoReadFailed = 2100,
    /// IoWriteFailed.
    IoWriteFailed = 2101,
    /// IoNotFound.
    IoNotFound = 2102,
    /// IoPermissionDenied.
    IoPermissionDenied = 2103,
    /// IoAlreadyExists.
    IoAlreadyExists = 2104,
    /// IoNotDirectory.
    IoNotDirectory = 2105,
    /// IoIsDirectory.
    IoIsDirectory = 2106,
    /// IoNotEmpty.
    IoNotEmpty = 2107,
    /// IoReadOnly.
    IoReadOnly = 2108,
    /// IoNameTooLong.
    IoNameTooLong = 2109,
    /// IoFileTooLarge.
    IoFileTooLarge = 2110,
    /// IoTooManyOpenFiles.
    IoTooManyOpenFiles = 2111,
    /// IoFileTableOverflow.
    IoFileTableOverflow = 2112,
    /// IoInvalidData.
    IoInvalidData = 2113,
    /// IoCrossDevice.
    IoCrossDevice = 2114,
    /// IoBrokenPipe.
    IoBrokenPipe = 2115,
    /// IoTimedOut.
    IoTimedOut = 2116,
    /// IoInterrupted.
    IoInterrupted = 2117,
    /// IoBusy.
    IoBusy = 2118,
    /// IoWouldBlock.
    IoWouldBlock = 2119,
    /// Net.
    Net = 3000,
    /// NetConnectionRefused.
    NetConnectionRefused = 3100,
    /// NetTimedOut.
    NetTimedOut = 3101,
    /// NetConnectionReset.
    NetConnectionReset = 3102,
    /// NetAddressInUse.
    NetAddressInUse = 3103,
    /// NetAddressNotAvailable.
    NetAddressNotAvailable = 3104,
    /// NetNetworkUnreachable.
    NetNetworkUnreachable = 3105,
    /// NetHostUnreachable.
    NetHostUnreachable = 3106,
    /// NetConnectionAborted.
    NetConnectionAborted = 3107,
    /// NetBrokenPipe.
    NetBrokenPipe = 3108,
    /// NetDnsFailed.
    NetDnsFailed = 3109,
    /// NetNotConnected.
    NetNotConnected = 3110,
    /// NetAlreadyConnected.
    NetAlreadyConnected = 3111,
    /// NetMessageTooLarge.
    NetMessageTooLarge = 3112,
    /// NetNotSocket.
    NetNotSocket = 3113,
    /// NetProtocolError.
    NetProtocolError = 3114,
    /// NetInProgress.
    NetInProgress = 3115,
    /// NetShutdown.
    NetShutdown = 3116,
    /// NetUnsupportedFamily.
    NetUnsupportedFamily = 3117,
    /// NetUnsupportedProtocol.
    NetUnsupportedProtocol = 3118,
    /// NetNoBufferSpace.
    NetNoBufferSpace = 3119,
    /// Process.
    Process = 4000,
    /// ProcessSpawnFailed.
    ProcessSpawnFailed = 4100,
    /// ProcessNotFound.
    ProcessNotFound = 4101,
    /// ProcessPermissionDenied.
    ProcessPermissionDenied = 4102,
    /// ProcessExecFailed.
    ProcessExecFailed = 4103,
    /// ProcessWaitFailed.
    ProcessWaitFailed = 4104,
    /// ProcessSignaled.
    ProcessSignaled = 4105,
    /// ProcessTimedOut.
    ProcessTimedOut = 4106,
    /// Random.
    Random = 5000,
    /// RandomUnavailable.
    RandomUnavailable = 5100,
    /// Time.
    Time = 6000,
    /// TimeUnavailable.
    TimeUnavailable = 6100,
    /// Ipc.
    Ipc = 7000,
    /// IpcMessageTooLarge.
    IpcMessageTooLarge = 7100,
    /// IpcTimedOut.
    IpcTimedOut = 7101,
    /// IpcClosed.
    IpcClosed = 7102,
    /// IpcWouldBlock.
    IpcWouldBlock = 7103,
    /// IpcAlreadyExists.
    IpcAlreadyExists = 7104,
    /// Security.
    Security = 7200,
    /// SecurityDenied.
    SecurityDenied = 7210,
    /// SecurityViolation.
    SecurityViolation = 7211,
    /// Thread.
    Thread = 7300,
    /// ThreadSpawnFailed.
    ThreadSpawnFailed = 7310,
    /// ThreadJoinFailed.
    ThreadJoinFailed = 7311,
    /// ThreadDeadlock.
    ThreadDeadlock = 7312,
    /// Ffi.
    Ffi = 7400,
    /// FfiLibraryLoadFailed.
    FfiLibraryLoadFailed = 7410,
    /// FfiSymbolNotFound.
    FfiSymbolNotFound = 7411,
    /// FfiCallFailed.
    FfiCallFailed = 7412,
    /// Device.
    Device = 7500,
    /// DeviceUnavailable.
    DeviceUnavailable = 7510,
    /// Display.
    Display = 7600,
    /// DisplayUnavailable.
    DisplayUnavailable = 7610,
    /// Audio.
    Audio = 7700,
    /// AudioUnavailable.
    AudioUnavailable = 7710,
    /// Gpu.
    Gpu = 7800,
    /// GpuUnavailable.
    GpuUnavailable = 7810,
    /// GpuOutOfMemory.
    GpuOutOfMemory = 7811,
    /// GpuDeviceLost.
    GpuDeviceLost = 7812,
    /// Resource.
    Resource = 7900,
    /// ResourceNotFound.
    ResourceNotFound = 7910,
    /// ResourceClosed.
    ResourceClosed = 7911,
    /// ResourceBusy.
    ResourceBusy = 7912,
    /// ResourceTypeMismatch.
    ResourceTypeMismatch = 7913,
    /// IoDriver.
    IoDriver = 8000,
    /// IoSubmissionFailed.
    IoSubmissionFailed = 8010,
    /// IoCompletionFailed.
    IoCompletionFailed = 8011,
    /// IoCancelled.
    IoCancelled = 8012,
    /// Generic.
    Generic = 9000,
}

impl VmValueCodec for PlatformErrorCode {
    fn decode(value: vm::Value) -> RuntimeResult<Self> {
        let raw = <u16 as VmValueCodec>::decode(value)?;
        let decoded = match raw {
            1000u16 => Self::InvalidArgument,
            1001u16 => Self::InvalidArgumentType,
            1002u16 => Self::InvalidArgumentValue,
            1100u16 => Self::NullPointer,
            1200u16 => Self::NotSupported,
            2000u16 => Self::Io,
            2100u16 => Self::IoReadFailed,
            2101u16 => Self::IoWriteFailed,
            2102u16 => Self::IoNotFound,
            2103u16 => Self::IoPermissionDenied,
            2104u16 => Self::IoAlreadyExists,
            2105u16 => Self::IoNotDirectory,
            2106u16 => Self::IoIsDirectory,
            2107u16 => Self::IoNotEmpty,
            2108u16 => Self::IoReadOnly,
            2109u16 => Self::IoNameTooLong,
            2110u16 => Self::IoFileTooLarge,
            2111u16 => Self::IoTooManyOpenFiles,
            2112u16 => Self::IoFileTableOverflow,
            2113u16 => Self::IoInvalidData,
            2114u16 => Self::IoCrossDevice,
            2115u16 => Self::IoBrokenPipe,
            2116u16 => Self::IoTimedOut,
            2117u16 => Self::IoInterrupted,
            2118u16 => Self::IoBusy,
            2119u16 => Self::IoWouldBlock,
            3000u16 => Self::Net,
            3100u16 => Self::NetConnectionRefused,
            3101u16 => Self::NetTimedOut,
            3102u16 => Self::NetConnectionReset,
            3103u16 => Self::NetAddressInUse,
            3104u16 => Self::NetAddressNotAvailable,
            3105u16 => Self::NetNetworkUnreachable,
            3106u16 => Self::NetHostUnreachable,
            3107u16 => Self::NetConnectionAborted,
            3108u16 => Self::NetBrokenPipe,
            3109u16 => Self::NetDnsFailed,
            3110u16 => Self::NetNotConnected,
            3111u16 => Self::NetAlreadyConnected,
            3112u16 => Self::NetMessageTooLarge,
            3113u16 => Self::NetNotSocket,
            3114u16 => Self::NetProtocolError,
            3115u16 => Self::NetInProgress,
            3116u16 => Self::NetShutdown,
            3117u16 => Self::NetUnsupportedFamily,
            3118u16 => Self::NetUnsupportedProtocol,
            3119u16 => Self::NetNoBufferSpace,
            4000u16 => Self::Process,
            4100u16 => Self::ProcessSpawnFailed,
            4101u16 => Self::ProcessNotFound,
            4102u16 => Self::ProcessPermissionDenied,
            4103u16 => Self::ProcessExecFailed,
            4104u16 => Self::ProcessWaitFailed,
            4105u16 => Self::ProcessSignaled,
            4106u16 => Self::ProcessTimedOut,
            5000u16 => Self::Random,
            5100u16 => Self::RandomUnavailable,
            6000u16 => Self::Time,
            6100u16 => Self::TimeUnavailable,
            7000u16 => Self::Ipc,
            7100u16 => Self::IpcMessageTooLarge,
            7101u16 => Self::IpcTimedOut,
            7102u16 => Self::IpcClosed,
            7103u16 => Self::IpcWouldBlock,
            7104u16 => Self::IpcAlreadyExists,
            7200u16 => Self::Security,
            7210u16 => Self::SecurityDenied,
            7211u16 => Self::SecurityViolation,
            7300u16 => Self::Thread,
            7310u16 => Self::ThreadSpawnFailed,
            7311u16 => Self::ThreadJoinFailed,
            7312u16 => Self::ThreadDeadlock,
            7400u16 => Self::Ffi,
            7410u16 => Self::FfiLibraryLoadFailed,
            7411u16 => Self::FfiSymbolNotFound,
            7412u16 => Self::FfiCallFailed,
            7500u16 => Self::Device,
            7510u16 => Self::DeviceUnavailable,
            7600u16 => Self::Display,
            7610u16 => Self::DisplayUnavailable,
            7700u16 => Self::Audio,
            7710u16 => Self::AudioUnavailable,
            7800u16 => Self::Gpu,
            7810u16 => Self::GpuUnavailable,
            7811u16 => Self::GpuOutOfMemory,
            7812u16 => Self::GpuDeviceLost,
            7900u16 => Self::Resource,
            7910u16 => Self::ResourceNotFound,
            7911u16 => Self::ResourceClosed,
            7912u16 => Self::ResourceBusy,
            7913u16 => Self::ResourceTypeMismatch,
            8000u16 => Self::IoDriver,
            8010u16 => Self::IoSubmissionFailed,
            8011u16 => Self::IoCompletionFailed,
            8012u16 => Self::IoCancelled,
            9000u16 => Self::Generic,
            _ => {
                return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(
                    "value",
                    "unknown PlatformErrorCode value",
                ))
                .boxed());
            }
        };
        Ok(decoded)
    }

    fn encode(self) -> vm::Value {
        <u16 as VmValueCodec>::encode(self as u16)
    }
}

/// ABI enum for PlatformErrorContextKind.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlatformErrorContextKind {
    /// Generic.
    Generic = 1,
    /// Io.
    Io = 2,
    /// Net.
    Net = 3,
    /// Process.
    Process = 4,
    /// Timer.
    Timer = 5,
    /// Resource.
    Resource = 6,
    /// Security.
    Security = 7,
    /// Ffi.
    Ffi = 8,
    /// Thread.
    Thread = 9,
    /// Ipc.
    Ipc = 10,
    /// Device.
    Device = 11,
    /// Display.
    Display = 12,
    /// Audio.
    Audio = 13,
    /// Gpu.
    Gpu = 14,
    /// IoDriver.
    IoDriver = 15,
}

impl VmValueCodec for PlatformErrorContextKind {
    fn decode(value: vm::Value) -> RuntimeResult<Self> {
        let raw = <u8 as VmValueCodec>::decode(value)?;
        let decoded = match raw {
            1u8 => Self::Generic,
            2u8 => Self::Io,
            3u8 => Self::Net,
            4u8 => Self::Process,
            5u8 => Self::Timer,
            6u8 => Self::Resource,
            7u8 => Self::Security,
            8u8 => Self::Ffi,
            9u8 => Self::Thread,
            10u8 => Self::Ipc,
            11u8 => Self::Device,
            12u8 => Self::Display,
            13u8 => Self::Audio,
            14u8 => Self::Gpu,
            15u8 => Self::IoDriver,
            _ => {
                return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(
                    "value",
                    "unknown PlatformErrorContextKind value",
                ))
                .boxed());
            }
        };
        Ok(decoded)
    }

    fn encode(self) -> vm::Value {
        <u8 as VmValueCodec>::encode(self as u8)
    }
}

/// ABI enum for PlatformPathEncoding.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlatformPathEncoding {
    /// Bytes.
    Bytes = 1,
    /// Utf16.
    Utf16 = 2,
}

impl VmValueCodec for PlatformPathEncoding {
    fn decode(value: vm::Value) -> RuntimeResult<Self> {
        let raw = <u8 as VmValueCodec>::decode(value)?;
        let decoded = match raw {
            1u8 => Self::Bytes,
            2u8 => Self::Utf16,
            _ => {
                return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(
                    "value",
                    "unknown PlatformPathEncoding value",
                ))
                .boxed());
            }
        };
        Ok(decoded)
    }

    fn encode(self) -> vm::Value {
        <u8 as VmValueCodec>::encode(self as u8)
    }
}

/// ABI enum for PlatformSystemSourceKind.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PlatformSystemSourceKind {
    /// Errno.
    Errno = 1,
    /// Winsock.
    Winsock = 2,
    /// HResult.
    HResult = 3,
    /// Eai.
    Eai = 4,
    /// Signal.
    Signal = 5,
    /// Other.
    Other = 255,
}

impl VmValueCodec for PlatformSystemSourceKind {
    fn decode(value: vm::Value) -> RuntimeResult<Self> {
        let raw = <u8 as VmValueCodec>::decode(value)?;
        let decoded = match raw {
            1u8 => Self::Errno,
            2u8 => Self::Winsock,
            3u8 => Self::HResult,
            4u8 => Self::Eai,
            5u8 => Self::Signal,
            255u8 => Self::Other,
            _ => {
                return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(
                    "value",
                    "unknown PlatformSystemSourceKind value",
                ))
                .boxed());
            }
        };
        Ok(decoded)
    }

    fn encode(self) -> vm::Value {
        <u8 as VmValueCodec>::encode(self as u8)
    }
}

/// ABI struct for PlatformError.
#[repr(C)]
pub struct PlatformErrorAbi<A: BindingAbi> {
    /// The code field.
    pub code: PlatformErrorCode,
    /// The op field.
    pub op: A::String,
    /// The source field.
    pub source: platform_error::PlatformSystemSourceAbi<A>,
    /// The context field.
    pub context: platform_error::PlatformErrorContextAbi<A>,
    /// The message field.
    pub message: A::String,
}

pub type PlatformError = PlatformErrorAbi<NativeAbi>;
pub type PlatformErrorVm = PlatformErrorAbi<VmAbi>;

impl<A: BindingAbi> std::fmt::Debug for PlatformErrorAbi<A> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("PlatformErrorAbi")
            .finish_non_exhaustive()
    }
}

impl Copy for PlatformErrorAbi<NativeAbi> {}
impl Clone for PlatformErrorAbi<NativeAbi> {
    fn clone(&self) -> Self {
        *self
    }
}
impl Copy for PlatformErrorAbi<VmAbi> {}
impl Clone for PlatformErrorAbi<VmAbi> {
    fn clone(&self) -> Self {
        *self
    }
}

impl VmAggregateCodec for PlatformErrorAbi<VmAbi> {
    fn decode_with_context(
        context: &vm::ExternalCallContext<'_>,
        value: vm::Value,
    ) -> RuntimeResult<Self> {
        if value.tag() != vm::ValueTag::Aggregate {
            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_type(
                "value",
                "PlatformError",
            ))
            .boxed());
        }
        let slots = context
            .aggregate_slots(value)
            .map_err(|error| RuntimeError::from(error).boxed())?;
        if slots.len() != 5 {
            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(
                "value",
                "expected 5 fields",
            ))
            .boxed());
        }
        let field_code =
            <PlatformErrorCode as VmAggregateCodec>::decode_with_context(context, slots[0])?;
        let field_op =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[1])?;
        let field_source =
            <PlatformSystemSourceVm as VmAggregateCodec>::decode_with_context(context, slots[2])?;
        let field_context =
            <PlatformErrorContextVm as VmAggregateCodec>::decode_with_context(context, slots[3])?;
        let field_message =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[4])?;
        Ok(Self {
            code: field_code,
            op: field_op,
            source: field_source,
            context: field_context,
            message: field_message,
        })
    }

    fn encode_with_context(
        self,
        context: &mut vm::ExternalCallContext<'_>,
    ) -> RuntimeResult<vm::Value> {
        let slots = vec![
            <PlatformErrorCode as VmAggregateCodec>::encode_with_context(self.code, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.op, context)?,
            <PlatformSystemSourceVm as VmAggregateCodec>::encode_with_context(
                self.source,
                context,
            )?,
            <PlatformErrorContextVm as VmAggregateCodec>::encode_with_context(
                self.context,
                context,
            )?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.message, context)?,
        ];
        Ok(context.allocate_aggregate(slots))
    }
}

/// ABI struct for PlatformErrorContext.
#[repr(C)]
pub struct PlatformErrorContextAbi<A: BindingAbi> {
    /// The kind field.
    pub kind: PlatformErrorContextKind,
    /// The syscall field.
    pub syscall: A::String,
    /// The path field.
    pub path: platform_error::PlatformPathPayloadAbi<A>,
    /// The dest field.
    pub dest: platform_error::PlatformPathPayloadAbi<A>,
    /// The path_text field.
    pub path_text: A::String,
    /// The dest_text field.
    pub dest_text: A::String,
    /// The fd field.
    pub fd: i32,
    /// The address field.
    pub address: A::String,
    /// The port field.
    pub port: u16,
    /// The hostname field.
    pub hostname: A::String,
    /// The pid field.
    pub pid: u64,
    /// The signal field.
    pub signal: A::String,
    /// The exit_code field.
    pub exit_code: i32,
    /// The timer_id field.
    pub timer_id: u64,
    /// The deadline_ns field.
    pub deadline_ns: u64,
    /// The resource_id field.
    pub resource_id: u64,
    /// The resource_kind field.
    pub resource_kind: A::String,
    /// The capability field.
    pub capability: A::String,
    /// The policy field.
    pub policy: A::String,
    /// The library field.
    pub library: A::String,
    /// The symbol field.
    pub symbol: A::String,
    /// The thread_id field.
    pub thread_id: u64,
    /// The argument field.
    pub argument: A::String,
    /// The pointer field.
    pub pointer: A::String,
    /// The feature field.
    pub feature: A::String,
}

pub type PlatformErrorContext = PlatformErrorContextAbi<NativeAbi>;
pub type PlatformErrorContextVm = PlatformErrorContextAbi<VmAbi>;

impl<A: BindingAbi> std::fmt::Debug for PlatformErrorContextAbi<A> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("PlatformErrorContextAbi")
            .finish_non_exhaustive()
    }
}

impl Copy for PlatformErrorContextAbi<NativeAbi> {}
impl Clone for PlatformErrorContextAbi<NativeAbi> {
    fn clone(&self) -> Self {
        *self
    }
}
impl Copy for PlatformErrorContextAbi<VmAbi> {}
impl Clone for PlatformErrorContextAbi<VmAbi> {
    fn clone(&self) -> Self {
        *self
    }
}

impl VmAggregateCodec for PlatformErrorContextAbi<VmAbi> {
    fn decode_with_context(
        context: &vm::ExternalCallContext<'_>,
        value: vm::Value,
    ) -> RuntimeResult<Self> {
        if value.tag() != vm::ValueTag::Aggregate {
            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_type(
                "value",
                "PlatformErrorContext",
            ))
            .boxed());
        }
        let slots = context
            .aggregate_slots(value)
            .map_err(|error| RuntimeError::from(error).boxed())?;
        if slots.len() != 25 {
            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(
                "value",
                "expected 25 fields",
            ))
            .boxed());
        }
        let field_kind =
            <PlatformErrorContextKind as VmAggregateCodec>::decode_with_context(context, slots[0])?;
        let field_syscall =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[1])?;
        let field_path =
            <PlatformPathPayloadVm as VmAggregateCodec>::decode_with_context(context, slots[2])?;
        let field_dest =
            <PlatformPathPayloadVm as VmAggregateCodec>::decode_with_context(context, slots[3])?;
        let field_path_text =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[4])?;
        let field_dest_text =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[5])?;
        let field_fd = <i32 as VmAggregateCodec>::decode_with_context(context, slots[6])?;
        let field_address =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[7])?;
        let field_port = <u16 as VmAggregateCodec>::decode_with_context(context, slots[8])?;
        let field_hostname =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[9])?;
        let field_pid = <u64 as VmAggregateCodec>::decode_with_context(context, slots[10])?;
        let field_signal =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[11])?;
        let field_exit_code = <i32 as VmAggregateCodec>::decode_with_context(context, slots[12])?;
        let field_timer_id = <u64 as VmAggregateCodec>::decode_with_context(context, slots[13])?;
        let field_deadline_ns = <u64 as VmAggregateCodec>::decode_with_context(context, slots[14])?;
        let field_resource_id = <u64 as VmAggregateCodec>::decode_with_context(context, slots[15])?;
        let field_resource_kind =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[16])?;
        let field_capability =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[17])?;
        let field_policy =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[18])?;
        let field_library =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[19])?;
        let field_symbol =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[20])?;
        let field_thread_id = <u64 as VmAggregateCodec>::decode_with_context(context, slots[21])?;
        let field_argument =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[22])?;
        let field_pointer =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[23])?;
        let field_feature =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[24])?;
        Ok(Self {
            kind: field_kind,
            syscall: field_syscall,
            path: field_path,
            dest: field_dest,
            path_text: field_path_text,
            dest_text: field_dest_text,
            fd: field_fd,
            address: field_address,
            port: field_port,
            hostname: field_hostname,
            pid: field_pid,
            signal: field_signal,
            exit_code: field_exit_code,
            timer_id: field_timer_id,
            deadline_ns: field_deadline_ns,
            resource_id: field_resource_id,
            resource_kind: field_resource_kind,
            capability: field_capability,
            policy: field_policy,
            library: field_library,
            symbol: field_symbol,
            thread_id: field_thread_id,
            argument: field_argument,
            pointer: field_pointer,
            feature: field_feature,
        })
    }

    fn encode_with_context(
        self,
        context: &mut vm::ExternalCallContext<'_>,
    ) -> RuntimeResult<vm::Value> {
        let slots = vec![
            <PlatformErrorContextKind as VmAggregateCodec>::encode_with_context(
                self.kind, context,
            )?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.syscall, context)?,
            <PlatformPathPayloadVm as VmAggregateCodec>::encode_with_context(self.path, context)?,
            <PlatformPathPayloadVm as VmAggregateCodec>::encode_with_context(self.dest, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.path_text, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.dest_text, context)?,
            <i32 as VmAggregateCodec>::encode_with_context(self.fd, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.address, context)?,
            <u16 as VmAggregateCodec>::encode_with_context(self.port, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.hostname, context)?,
            <u64 as VmAggregateCodec>::encode_with_context(self.pid, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.signal, context)?,
            <i32 as VmAggregateCodec>::encode_with_context(self.exit_code, context)?,
            <u64 as VmAggregateCodec>::encode_with_context(self.timer_id, context)?,
            <u64 as VmAggregateCodec>::encode_with_context(self.deadline_ns, context)?,
            <u64 as VmAggregateCodec>::encode_with_context(self.resource_id, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(
                self.resource_kind,
                context,
            )?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.capability, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.policy, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.library, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.symbol, context)?,
            <u64 as VmAggregateCodec>::encode_with_context(self.thread_id, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.argument, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.pointer, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.feature, context)?,
        ];
        Ok(context.allocate_aggregate(slots))
    }
}

/// ABI struct for PlatformPathPayload.
#[repr(C)]
pub struct PlatformPathPayloadAbi<A: BindingAbi> {
    /// The encoding field.
    pub encoding: PlatformPathEncoding,
    /// The data field.
    pub data: A::Array<u8>,
}

pub type PlatformPathPayload = PlatformPathPayloadAbi<NativeAbi>;
pub type PlatformPathPayloadVm = PlatformPathPayloadAbi<VmAbi>;

impl<A: BindingAbi> std::fmt::Debug for PlatformPathPayloadAbi<A> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("PlatformPathPayloadAbi")
            .finish_non_exhaustive()
    }
}

impl Copy for PlatformPathPayloadAbi<NativeAbi> {}
impl Clone for PlatformPathPayloadAbi<NativeAbi> {
    fn clone(&self) -> Self {
        *self
    }
}
impl Copy for PlatformPathPayloadAbi<VmAbi> {}
impl Clone for PlatformPathPayloadAbi<VmAbi> {
    fn clone(&self) -> Self {
        *self
    }
}

impl VmAggregateCodec for PlatformPathPayloadAbi<VmAbi> {
    fn decode_with_context(
        context: &vm::ExternalCallContext<'_>,
        value: vm::Value,
    ) -> RuntimeResult<Self> {
        if value.tag() != vm::ValueTag::Aggregate {
            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_type(
                "value",
                "PlatformPathPayload",
            ))
            .boxed());
        }
        let slots = context
            .aggregate_slots(value)
            .map_err(|error| RuntimeError::from(error).boxed())?;
        if slots.len() != 2 {
            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(
                "value",
                "expected 2 fields",
            ))
            .boxed());
        }
        let field_encoding =
            <PlatformPathEncoding as VmAggregateCodec>::decode_with_context(context, slots[0])?;
        let field_data = <VmArray<u8> as VmAggregateCodec>::decode_with_context(context, slots[1])?;
        Ok(Self {
            encoding: field_encoding,
            data: field_data,
        })
    }

    fn encode_with_context(
        self,
        context: &mut vm::ExternalCallContext<'_>,
    ) -> RuntimeResult<vm::Value> {
        let slots = vec![
            <PlatformPathEncoding as VmAggregateCodec>::encode_with_context(
                self.encoding,
                context,
            )?,
            <VmArray<u8> as VmAggregateCodec>::encode_with_context(self.data, context)?,
        ];
        Ok(context.allocate_aggregate(slots))
    }
}

/// ABI struct for PlatformSystemSource.
#[repr(C)]
pub struct PlatformSystemSourceAbi<A: BindingAbi> {
    /// The kind field.
    pub kind: PlatformSystemSourceKind,
    /// The value field.
    pub value: i32,
    /// The name field.
    pub name: A::String,
}

pub type PlatformSystemSource = PlatformSystemSourceAbi<NativeAbi>;
pub type PlatformSystemSourceVm = PlatformSystemSourceAbi<VmAbi>;

impl<A: BindingAbi> std::fmt::Debug for PlatformSystemSourceAbi<A> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("PlatformSystemSourceAbi")
            .finish_non_exhaustive()
    }
}

impl Copy for PlatformSystemSourceAbi<NativeAbi> {}
impl Clone for PlatformSystemSourceAbi<NativeAbi> {
    fn clone(&self) -> Self {
        *self
    }
}
impl Copy for PlatformSystemSourceAbi<VmAbi> {}
impl Clone for PlatformSystemSourceAbi<VmAbi> {
    fn clone(&self) -> Self {
        *self
    }
}

impl VmAggregateCodec for PlatformSystemSourceAbi<VmAbi> {
    fn decode_with_context(
        context: &vm::ExternalCallContext<'_>,
        value: vm::Value,
    ) -> RuntimeResult<Self> {
        if value.tag() != vm::ValueTag::Aggregate {
            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_type(
                "value",
                "PlatformSystemSource",
            ))
            .boxed());
        }
        let slots = context
            .aggregate_slots(value)
            .map_err(|error| RuntimeError::from(error).boxed())?;
        if slots.len() != 3 {
            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(
                "value",
                "expected 3 fields",
            ))
            .boxed());
        }
        let field_kind =
            <PlatformSystemSourceKind as VmAggregateCodec>::decode_with_context(context, slots[0])?;
        let field_value = <i32 as VmAggregateCodec>::decode_with_context(context, slots[1])?;
        let field_name =
            <vm::StringHandle as VmAggregateCodec>::decode_with_context(context, slots[2])?;
        Ok(Self {
            kind: field_kind,
            value: field_value,
            name: field_name,
        })
    }

    fn encode_with_context(
        self,
        context: &mut vm::ExternalCallContext<'_>,
    ) -> RuntimeResult<vm::Value> {
        let slots = vec![
            <PlatformSystemSourceKind as VmAggregateCodec>::encode_with_context(
                self.kind, context,
            )?,
            <i32 as VmAggregateCodec>::encode_with_context(self.value, context)?,
            <vm::StringHandle as VmAggregateCodec>::encode_with_context(self.name, context)?,
        ];
        Ok(context.allocate_aggregate(slots))
    }
}

/// Replay struct for PlatformError.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlatformErrorReplayRecord {
    /// The code field.
    pub code: PlatformErrorCode,
    /// The op field.
    pub op: String,
    /// The source field.
    pub source: PlatformSystemSourceReplayRecord,
    /// The context field.
    pub context: PlatformErrorContextReplayRecord,
    /// The message field.
    pub message: String,
}

/// Replay struct for PlatformErrorContext.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlatformErrorContextReplayRecord {
    /// The kind field.
    pub kind: PlatformErrorContextKind,
    /// The syscall field.
    pub syscall: String,
    /// The path field.
    pub path: PlatformPathPayloadReplayRecord,
    /// The dest field.
    pub dest: PlatformPathPayloadReplayRecord,
    /// The path_text field.
    pub path_text: String,
    /// The dest_text field.
    pub dest_text: String,
    /// The fd field.
    pub fd: i32,
    /// The address field.
    pub address: String,
    /// The port field.
    pub port: u16,
    /// The hostname field.
    pub hostname: String,
    /// The pid field.
    pub pid: u64,
    /// The signal field.
    pub signal: String,
    /// The exit_code field.
    pub exit_code: i32,
    /// The timer_id field.
    pub timer_id: u64,
    /// The deadline_ns field.
    pub deadline_ns: u64,
    /// The resource_id field.
    pub resource_id: u64,
    /// The resource_kind field.
    pub resource_kind: String,
    /// The capability field.
    pub capability: String,
    /// The policy field.
    pub policy: String,
    /// The library field.
    pub library: String,
    /// The symbol field.
    pub symbol: String,
    /// The thread_id field.
    pub thread_id: u64,
    /// The argument field.
    pub argument: String,
    /// The pointer field.
    pub pointer: String,
    /// The feature field.
    pub feature: String,
}

/// Replay struct for PlatformPathPayload.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlatformPathPayloadReplayRecord {
    /// The encoding field.
    pub encoding: PlatformPathEncoding,
    /// The data field.
    pub data: Vec<u8>,
}

/// Replay struct for PlatformSystemSource.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlatformSystemSourceReplayRecord {
    /// The kind field.
    pub kind: PlatformSystemSourceKind,
    /// The value field.
    pub value: i32,
    /// The name field.
    pub name: String,
}
