/* generated by destack_client_generate, do not edit */

export {
    Code,
} from "../../../_generated/program/vm/code/code.js";
export {
    FunctionTable,
} from "../../../_generated/program/vm/code/function.js";
export {
    ResumeTable,
} from "../../../_generated/program/vm/code/state.js";
export {
    SideRecordTable,
    SideTable,
} from "../../../_generated/program/vm/code/table.js";
