// generated by generate-bindings: do not edit

#ifndef DESTACK_RUNTIME_ANDROID_BRIDGE_BACKGROUND_METHODS_H
#define DESTACK_RUNTIME_ANDROID_BRIDGE_BACKGROUND_METHODS_H

#include "../types.h"

/// Resolve the background bridge methods from one runtime bridge instance.
bool resolve_background_methods(JNIEnv *env, jobject bridge);
/// Call the background-status entrypoint on one registered bridge.
uint32_t call_background_status(
    JNIEnv *env,
    uint64_t session_handle,
    HostBackgroundStatusResponse *response
);

/// Call the background-list entrypoint on one registered bridge.
uint32_t call_background_list(
    JNIEnv *env,
    uint64_t session_handle,
    HostBackgroundListResponse *response
);

/// Call the background-register-task entrypoint on one registered bridge.
uint32_t call_background_register_task(
    JNIEnv *env,
    uint64_t session_handle,
    HostBackgroundTaskOptions request
);

/// Call the background-unregister entrypoint on one registered bridge.
uint32_t call_background_unregister(
    JNIEnv *env,
    uint64_t session_handle,
    HostBackgroundUnregisterRequest request
);

/// Call the background-trigger-test entrypoint on one registered bridge.
uint32_t call_background_trigger_test(
    JNIEnv *env,
    uint64_t session_handle,
    HostBackgroundTriggerTestRequest request,
    HostBackgroundTriggerTestResponse *response
);

/// Call the background-complete entrypoint on one registered bridge.
uint32_t call_background_complete(
    JNIEnv *env,
    uint64_t session_handle,
    HostBackgroundCompleteRequest request
);

#endif
