[package]
name = "tspp_daemon"
description = "Destack Daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
tspp_artifact = { workspace = true }
tspp_core = { workspace = true }
tspp_program = { workspace = true }
tspp_repository = { workspace = true }
tspp_rpc = { workspace = true }
tspp_runtime = { workspace = true }
tspp_serde = { workspace = true }
tspp_session = { workspace = true }
tspp_source = { workspace = true }
tspp_vm = { workspace = true }
tspp_workspace = { workspace = true }

# general
base64 = { workspace = true }
crossbeam-channel = { workspace = true }
fs2 = { workspace = true }
futures = { workspace = true }
getrandom = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[lints]
workspace = true
