[package]
name = "destack_daemon"
description = "Destack Daemon"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_query = { workspace = true }
destack_repository = { workspace = true }
destack_session = { workspace = true, features = ["native"] }
destack_workspace = { workspace = true }
destack_source = { workspace = true }

# general
parking_lot = { workspace = true }

[dev-dependencies]
# language
destack_artifact = { workspace = true }

[lints]
workspace = true
