[build-system]
requires = ["uv_build>=0.7.13,<0.8.0"]
build-backend = "uv_build"

[project]
name = "destack-py"
version = "2025.06.16.0"
description = "Destack Python SDK"
authors = [{ name = "Symbol Industries", email = "hello@symbol.industries" }]
requires-python = ">=3.10"

[tool.uv_build.targets.wheel]
packages = ["destack"]