[project]
name = "destack-py"
version = "2025.08.20.1"
description = "Destack Python library"
authors = [{ name = "Symbol Industries", email = "hello@symbol.industries" }]
requires-python = ">=3.13"

[build-system]
requires = ["uv_build>=0.7.13,<0.8.0"]
build-backend = "uv_build"

[tool.pytest_env]
ENVIRONMENT = "test"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_test_loop_scope = "session"
python_files = "test/**/*.py test/*.py"
python_classes = "!TestProfile"
pythonpath = ["."]
log_cli = true
addopts = [
	'-rP',
	"-vv",
	"--import-mode=importlib",
	"--color=yes",
	'--strict-markers',
]
markers = []
filterwarnings = ["ignore::DeprecationWarning", "ignore::UserWarning"]
