[package]
name = "destack_vm"
description = "Destack VM - MIR machine and JIT execution engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[features]
default = []

[dependencies]
# language
destack_core = { workspace = true }
destack_engine = { workspace = true }
destack_heap = { workspace = true }
destack_memory = { workspace = true }
destack_mir = { workspace = true }
destack_source = { workspace = true }

# util
postcard = { workspace = true }
serde = { workspace = true, features = ["rc"] }
smallvec = { workspace = true }

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
criterion = { workspace = true }
pprof = { workspace = true }

[[bench]]
name = "dispatch"
path = "benches/dispatch/bench.rs"
harness = false

[lints]
workspace = true
