[package]
name = "destack_vm"
description = "Destack VM - MIR interpreter and JIT execution engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[features]
default = []
stats = []
perf-counters = ["dep:perf-event"]

[dependencies]
# language
destack_base = { workspace = true }
destack_mir = { workspace = true }
destack_source = { workspace = true }
destack_vm_abi = { workspace = true }

# util
smallvec = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
perf-event = { version = "0.4.8", optional = true }

[dev-dependencies]
clap = { version = "4.5", features = ["derive"] }
criterion = { workspace = true }
destack_test_mirbench = { workspace = true, features = ["cli", "stats"] }
pprof = { workspace = true }

[[bench]]
name = "vm_execute"
harness = false

[lints]
workspace = true
