[package]
name = "tspp_vm"
description = "TS++ bytecode virtual machine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[features]
default = []

[dependencies]
# language
tspp_bytecode = { workspace = true }
tspp_heap = { workspace = true }
tspp_memory = { workspace = true }
tspp_mir = { workspace = true }
tspp_program = { workspace = true }
tspp_serde = { workspace = true }

# util
serde = { workspace = true, features = ["rc"] }

[dev-dependencies]
# language
tspp_core = { workspace = true }
tspp_source = { workspace = true }

# util
criterion = { workspace = true }

[[bench]]
name = "execute"
path = "benches/execute/bench.rs"
harness = false

[lints]
workspace = true
