config:
  aws:region: "eu-central-1"
  bench:BETTERSTACK_SECRET:
    secure: AAABAMcwUhrDe9/PMrDDQk9hpHE5QnHFfGG4gdUBTjnOTB+eIKH0syhoPvnBh0In4KlQ2yF4Syc=
  bench:BROWSERLESS_API_KEY:
    secure: AAABAPHDsqwb8sZZZnuupmI/xgSabdHyQzTMB3d1gOaGfQpEwrvbGxphr/BXvsmWzmoPATG+Ue5l23GzAOOjUiu8lHU=
  bench:DEEPGRAM_API_KEY:
    secure: AAABANzJubkeeMQeUHaAfddP51ITzPDJwV7biQd8kOCo5C0Tjrsg/sM0+DRH8vnKP7s0ELnCKeKfBerciIGPttSctp8EbcAA
  bench:HUGGINGFACE_API_KEY:
    secure: AAABAKTXjre+JCbEbrlXhvLNlple7oCuGCYikUvQW7F+rsC2qv3A1f7jWKYv0vCDYRnV0pzBBr7DW17n2VyO0SZjZqft
  bench:LOOPS_API_KEY:
    secure: AAABALugbjvj+BJBfVwXcSB2vq9oCmiWncVZ5V6k1xNKaIkCCLIJa/+VmPsidbPSTLYJpnROIzaSD6MGabTWDA==
  bench:LOOPS_USER_TRANSACTIONAL_ID: cloo304uv01ebjq0olzfb0dfu
  bench:OPENAI_API_KEY:
    secure: AAABAPNZUmkJnMERio8jl0beB7jZJktjMP7yxPSKZNNDygwnkIS2hcc1h/oXFZK/oHgduMzD0Hs8HBkkIgo9DUzqtJOUONv/qb0rXhw8Bxk22Vo=
  bench:SENTRY_DSN:
    secure: AAABAPr2x2HnBVeoBCFpS2AkZa0HJWnfRHlhML3Reyo8uFnxClxpMNm+fN7xPPUE5o6zFGUgvlErBK/uWPQmjDkwO9tg0tufG56kQa7LFGrFzgp4aTzBHDjCGd6/Xqk9w1rdavoRLltEwYIOdLGeAb6siuqplZPsq+Chuw==
  bench:apiAllowedHosts: "*"
  bench:apiAllowedOrigins: https://api.bench.is,https://bench.is
  bench:awsRegion: eu-central-1
  bench:betterstackValuesPath: .betterstack.prod.yaml
  bench:desiredClusterSize: "3"
  bench:eksNodeInstanceType: t3.medium
  bench:env: prod
  bench:ghcrToken:
    secure: AAABAEEyRBP91rRUbjQJZ/l3IjF6qVVIPMXxk8yMov7HkCt5ziuHbjqnoFF4OY8HpI9aG6TXmG+bu5NjKViUoeIko4oFM98d5wIWezpMpDGKf8vDZiwBRcl9PeV4RMgvbRD5PQ1Qpok=
  bench:globalDbPassword:
    secure: AAABAPAK6vinbym9SIGWu6dSO53w7Xk4SnlxxaH7ESjTr8Av9i0vjzk3YzdexRa3epM+hivMoYR0++6IwhM6KnVrCWO/9clEROm1ejQXlz3wTx1DHOk5psxWZ5Wj+Us=
  bench:globalPgCryptoKey:
    secure: AAABAKGMJv773Z9IbH1YDlUy+58OxlhKb1h6md0TJDbCE60De9uu5TNH5Hf9mgxR6nQ5j78Wima/Fb4pcKR/DaGKs7llKS8stem/
  bench:maxClusterSize: "4"
  bench:minClusterSize: "2"
  bench:sharedOsPassword:
    secure: AAABANnU/ujGstYwg+Tcyfyug64gPvG32UxB2LufnN5bulDtOL63kwWQ5Uwz16Wagq5AJWJJ7YPBfrTyHfdHJh9UCZIZHEHh7rlhyM8r7T18jQ==
  bench:userDbPassword:
    secure: AAABAAMpH4OXy1Mtxv3pwraWcU4SszDrNSimjs2q0HIPSH+FnJ8TUJSfVlyMiXYKH6pnjNeMZLbd8CGmW2GSxO+RvppjRUA+PqHMCHJbQ/9+CkWQaq5shP+EJvaKIFYb
  bench:version: "current"
  bench:vpcNetworkCidr: 10.0.0.0/16
  bench:webappUrl: https://bench.is
  pulumi:template: kubernetes-aws-typescript
