config:
  Bench:apiAllowedHosts: "*"
  Bench:dbPassword:
    secure: AAABAHNMg0BRcTWRgoeTiH5W+ydM7jkjxqbgEgPjA3+mFYzaVEA7FMD3YCTD9TqkO7B24rypa3jTTWtnnabxegRsyYMIznF5EiAprlKyVmCcEUOK2KLmekCUWu8QI6w=
  Bench:desiredClusterSize: "2"
  Bench:eksNodeInstanceType: t3.medium
  Bench:env: prod
  Bench:ghcrToken:
    secure: AAABAEEyRBP91rRUbjQJZ/l3IjF6qVVIPMXxk8yMov7HkCt5ziuHbjqnoFF4OY8HpI9aG6TXmG+bu5NjKViUoeIko4oFM98d5wIWezpMpDGKf8vDZiwBRcl9PeV4RMgvbRD5PQ1Qpok=
  Bench:maxClusterSize: "3"
  Bench:minClusterSize: "2"
  Bench:vpcNetworkCidr: 10.0.0.0/16
  Bench:version: "current"
  aws:region: "eu-central-1"
  pulumi:template: kubernetes-aws-typescript
