# generated bridge target, do not edit

from __future__ import annotations

from ..._generated.source.diagnostic.collector import (
    DiagnosticCollection,
    decode_diagnostic_collection,
    encode_diagnostic_collection,
    from_json_diagnostic_collection,
    to_json_diagnostic_collection,
)
from ..._generated.source.diagnostic.diagnostic import (
    Diagnostic,
    decode_diagnostic,
    encode_diagnostic,
    from_json_diagnostic,
    to_json_diagnostic,
)
from ..._generated.source.diagnostic.label import (
    DiagnosticHelp,
    DiagnosticLabel,
    DiagnosticNote,
    decode_diagnostic_help,
    decode_diagnostic_label,
    decode_diagnostic_note,
    encode_diagnostic_help,
    encode_diagnostic_label,
    encode_diagnostic_note,
    from_json_diagnostic_help,
    from_json_diagnostic_label,
    from_json_diagnostic_note,
    to_json_diagnostic_help,
    to_json_diagnostic_label,
    to_json_diagnostic_note,
)
from ..._generated.source.diagnostic.severity import (
    DiagnosticSeverity,
    DiagnosticTag,
    decode_diagnostic_severity,
    decode_diagnostic_tag,
    encode_diagnostic_severity,
    encode_diagnostic_tag,
    from_json_diagnostic_severity,
    from_json_diagnostic_tag,
    to_json_diagnostic_severity,
    to_json_diagnostic_tag,
)
from ..._generated.source.diagnostic.suggestion import (
    Applicability,
    DiagnosticSuggestion,
    decode_applicability,
    decode_diagnostic_suggestion,
    encode_applicability,
    encode_diagnostic_suggestion,
    from_json_applicability,
    from_json_diagnostic_suggestion,
    to_json_applicability,
    to_json_diagnostic_suggestion,
)

__all__ = [
    "DiagnosticCollection",
    "encode_diagnostic_collection",
    "decode_diagnostic_collection",
    "to_json_diagnostic_collection",
    "from_json_diagnostic_collection",
    "Diagnostic",
    "encode_diagnostic",
    "decode_diagnostic",
    "to_json_diagnostic",
    "from_json_diagnostic",
    "DiagnosticLabel",
    "encode_diagnostic_label",
    "decode_diagnostic_label",
    "to_json_diagnostic_label",
    "from_json_diagnostic_label",
    "DiagnosticNote",
    "encode_diagnostic_note",
    "decode_diagnostic_note",
    "to_json_diagnostic_note",
    "from_json_diagnostic_note",
    "DiagnosticHelp",
    "encode_diagnostic_help",
    "decode_diagnostic_help",
    "to_json_diagnostic_help",
    "from_json_diagnostic_help",
    "DiagnosticSeverity",
    "encode_diagnostic_severity",
    "decode_diagnostic_severity",
    "to_json_diagnostic_severity",
    "from_json_diagnostic_severity",
    "DiagnosticTag",
    "encode_diagnostic_tag",
    "decode_diagnostic_tag",
    "to_json_diagnostic_tag",
    "from_json_diagnostic_tag",
    "Applicability",
    "encode_applicability",
    "decode_applicability",
    "to_json_applicability",
    "from_json_applicability",
    "DiagnosticSuggestion",
    "encode_diagnostic_suggestion",
    "decode_diagnostic_suggestion",
    "to_json_diagnostic_suggestion",
    "from_json_diagnostic_suggestion",
]
