[package]
name = "destack_machine"
description = "Destack Machine - MIR interpreter and JIT execution engine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_mir = { workspace = true }
destack_source = { workspace = true }


[dev-dependencies]

[lints]
workspace = true
