[package]
name = "dyst_js"
description = "Dyst JavaScript"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"
doctest = false

[dependencies]
dyst_container = { workspace = true }
dyst_memory = { workspace = true }
dyst_session = { workspace = true }
dyst_source = { workspace = true }
dyst_string = { workspace = true }
dyst_tree = { workspace = true }

destack_unicode = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
