[package]
name = "dyst_formatter"
description = "Dyst Formatter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"
doctest = false

[dependencies]
dyst_ast = { workspace = true }
dyst_container = { workspace = true }
dyst_diagnostic = { workspace = true }
dyst_fir = { workspace = true }
dyst_parser = { workspace = true }
dyst_session = { workspace = true }
dyst_source = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
