[package]
name = "destack_formatter"
description = "Destack Formatter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[features]
default = []
timings = []

[dependencies]
# language
destack_artifact = { workspace = true }
destack_core = { workspace = true }
destack_css = { workspace = true }
destack_dir = { workspace = true }
destack_fir = { workspace = true }
destack_html = { workspace = true }
destack_parser = { workspace = true }
destack_source = { workspace = true }
destack_workspace = { path = "../workspace", default-features = false }

# general
markdown = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
clap = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
