# ruff: noqa
from typing import Union

from .common_grpc import *
from .common_pb2 import *
from .health_grpc import *
from .health_pb2 import *
from .lang_grpc import *
from .lang_pb2 import *
from .runtime_grpc import *
from .runtime_pb2 import *
from .system_grpc import *
from .system_pb2 import *

AnyNodeData = Union[
    BenchData,
    UserData,
    OrganizationData,
    HandleData,
    ClientData,
    ServerData,
    StoreData,
    MachineData,
    DriveData,
    MembershipData,
    InviteData,
    BranchData,
    PackageData,
    DependencyData,
    SpaceData,
    BlockData,
    TriggerData,
    FieldData,
    QueryData,
    ViewData,
    StepData,
    PipeData,
    BadgeData,
    FileData,
    SecretData,
    MessageData,
    RecordData,
    NotificationData,
    SessionData,
    RunData,
    SignalData,
    LogData,
    SkipData,
]
AnyStructData = Union[
    SessionContextData,
    EditContextData,
    EditData,
    ChangeData,
    ChangeVignetteData,
    GraphScopeData,
    ClientOriginData,
    NodeReferenceData,
    PropertyReferenceData,
    PathData,
    PathTokenData,
    PolicyData,
    PolicyRuleData,
    SubjectData,
    AccessZoneData,
    AccessMatrixData,
    AccessData,
    TextData,
    TextLineData,
    TextSpanData,
    TypeInfoData,
    TypeConstraintData,
    ScheduleData,
    FileReferenceData,
    IconData,
    SecretReferenceData,
    FileInfoData,
    TriggerInfoData,
    ExpressionData,
    AggregationData,
    SelectionData,
    QueryInfoData,
    ReadOptionsData,
    ValueData,
    ComputedValueData,
    CodeData,
    CodeLineData,
    PortKeyData,
    PortData,
    RunErrorData,
    RunOptionsData,
    RunAttemptData,
    RunTraceData,
    RunFrameData,
    RunSpanData,
    RunEventData,
    BreakpointData,
    LogInfoData,
    ColorData,
    FontData,
    BoxData,
    OffsetData,
    TransformData,
    Vector2Data,
    Vector3Data,
    Vector4Data,
    LineData,
    StartViewStateData,
    FeedViewStateData,
    UserWizardViewStateData,
    TreeViewStateData,
]
