[package]
name = "cranelift-assembler-x64"
description = "A Cranelift-specific x64 assembler"
version = "0.131.1"
license = "Apache-2.0 WITH LLVM-exception"
edition = "2024"
rust-version = "1.92.0"

[dependencies]
arbitrary = { workspace = true, features = ["derive"], optional = true }
capstone = { workspace = true, optional = true }

[dev-dependencies]
arbitrary = { workspace = true, features = ["derive"] }
arbtest = { workspace = true }
capstone = { workspace = true }

[build-dependencies]
cranelift-assembler-x64-meta = { path = "meta", version = "0.131.1" }


[features]
fuzz = ['dep:arbitrary', 'dep:capstone']
