[package]
name = "dyst_parser"
description = "Dyst Parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
dyst_ast = { workspace = true }
dyst_source = { workspace = true }
dyst_unicode = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
pprof = { workspace = true }
criterion = { workspace = true }

[lints]
workspace = true
