[package]
name = "destack_parser"
description = "Destack Parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_ast = { workspace = true }
destack_core = { workspace = true }
destack_source = { workspace = true }
destack_unicode = { workspace = true }

# general
memchr = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
pprof = { workspace = true }
rayon = { workspace = true }
num_cpus = { workspace = true }

[[bench]]
name = "destack_parse"
harness = false

[[bench]]
name = "destack_lex"
harness = false

[lints]
workspace = true
