[package]
name = "tspp_parser"
description = "TS++ Parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
tspp_dir = { workspace = true }
tspp_core = { workspace = true }
tspp_source = { workspace = true }
tspp_unicode = { workspace = true }

# general
memchr = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
num_cpus = { workspace = true }
pprof = { workspace = true }
rayon = { workspace = true }

[[bench]]
name = "tspp_parse"
harness = false

[[bench]]
name = "tspp_lex"
harness = false

[lints]
workspace = true
