set shell := ["bash", "-cu"]
set windows-shell := ["C:/Program Files/Git/bin/bash.exe", "-cu"]

_default:
    @just --list --unsorted

# typecheck
typecheck:
    bun run typecheck

# lint
lint:
    bun run destack-check check src README.md

# test
test:
    bun run test

# check formatting
format-check:
    bun run destack-check format-check src package.json destack.json

# typecheck, lint and check formatting
check: typecheck lint format-check

# format
format *args:
    bun run destack-check format {{args}} src package.json destack.json
