[package]
name = "tspp_lsp_types"
description = "LSP types for the TS++ language server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[features]
default = ["proposed"]
proposed = []

[dependencies]
bitflags = { workspace = true }
fluent-uri = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_repr = { workspace = true }

[lints]
workspace = true
