[package]
name = "destack_fuzz-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
destack = { path = "../../destack" }
destack_time = { path = "../../destack_time" }
destack_order = { path = "../../destack_order" }
destack_uuid = { path = "../../destack_uuid" }
destack_json = { path = "../../destack_json" }

arbitrary = { workspace = true }
libfuzzer-sys = { workspace = true }

[[bin]]
name = "destack_time_time"
path = "fuzz_targets/destack_time/time.rs"
test = false
doc = false

[[bin]]
name = "destack_time_date"
path = "fuzz_targets/destack_time/date.rs"
test = false
doc = false

[[bin]]
name = "destack_time_datetime"
path = "fuzz_targets/destack_time/datetime.rs"
test = false
doc = false

[[bin]]
name = "destack_time_duration"
path = "fuzz_targets/destack_time/duration.rs"
test = false
doc = false

[[bin]]
name = "destack_time_timestamp"
path = "fuzz_targets/destack_time/timestamp.rs"
test = false
doc = false

[[bin]]
name = "destack_uuid_uuid"
path = "fuzz_targets/destack_uuid/uuid.rs"
test = false
doc = false

[[bin]]
name = "destack_json_json"
path = "fuzz_targets/destack_json/json.rs"
test = false
doc = false

[profile.release]
panic = "abort"
