[package]
name = "destack"
description = "Destack Rust library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "destack"
path = "src/main.rs"

[dependencies]
destack_fractional = { workspace = true }
bytes = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
smallvec = { workspace = true }
sysinfo = { workspace = true }
uuid = { workspace = true }
wasm-bindgen = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
pretty_assertions = { workspace = true }
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
static_assertions = { workspace = true }
wasm-bindgen-test = { workspace = true }

[lints]
workspace = true

