[package]
name = "destack"
description = "Destack Rust library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "destack"
path = "src/main.rs"

[dependencies]
destack_fractional = { workspace = true }
destack_time = { workspace = true }
destack_uuid = { workspace = true }
destack_json = { workspace = true }

bytes = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
static_assertions = { workspace = true }

[lints]
workspace = true
