[package]
name = "destack_lsp"
description = "Destack Language Server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"

[[bin]]
name = "destack_lsp"
path = "rust/main.rs"

[dependencies]
dyst_ast = { workspace = true }
dyst_diagnostic = { workspace = true }
dyst_dir = { workspace = true }
dyst_fir = { workspace = true }
dyst_module = { workspace = true }
dyst_parser = { workspace = true }
dyst_session = { workspace = true }
dyst_source = { workspace = true }

destack_file = { workspace = true }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = [
	"macros",
	"rt-multi-thread",
	"io-std",
	"sync",
] }
tower-lsp-server = "0.22.1"
libc = "0.2.175"
