[package]
name = "destack_bridge_generate"
description = "Destack bridge binding generator"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "destack-bridge-generate"
path = "src/main.rs"

[dependencies]
# destack
destack_artifact.workspace = true
destack_dir.workspace = true
destack_mir.workspace = true
destack_program.workspace = true
destack_query.workspace = true
destack_repository.workspace = true
destack_serde.workspace = true
destack_source.workspace = true
destack_workspace.workspace = true

# general
anyhow.workspace = true

[lints]
workspace = true
