[package]
name = "destack_fuzz"
description = "Destack fuzzer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "destack_fuzz"
path = "src/main.rs"

[dependencies]
destack = { workspace = true }
destack_json = { workspace = true }
destack_order = { workspace = true }
destack_system = { workspace = true }
destack_time = { workspace = true }
destack_uuid = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
pretty_assertions = { workspace = true }
static_assertions = { workspace = true }
libfuzzer-sys = { workspace = true }

[lints]
workspace = true
