[package]
name = "dyst_dir"
description = "Dyst Data IR"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
dyst_ast = { workspace = true }
dyst_fir = { workspace = true }
dyst_source = { workspace = true }
dyst_unicode = { workspace = true }

parking_lot = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
