[package]
name = "tspp_dir"
description = "TS++ Data IR"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
tspp_core = { workspace = true }
tspp_dir_macros = { workspace = true }
tspp_fir = { workspace = true }
tspp_serde = { workspace = true }
tspp_source = { workspace = true }
tspp_unicode = { workspace = true }

# general
dashmap = { workspace = true }
elsa = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
parking_lot = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
siphasher = { workspace = true }
serde_json = { workspace = true }
smallvec = { workspace = true, features = ["serde"] }

[lints]
workspace = true
