[package]
name = "dyst_dir"
description = "Dyst Data IR"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"
doctest = false

[dependencies]
dyst_ast = { workspace = true }
dyst_container = { workspace = true }
dyst_diagnostic = { workspace = true }
dyst_fir = { workspace = true }
dyst_module = { workspace = true }
dyst_session = { workspace = true }
dyst_source = { workspace = true }
dyst_tree = { workspace = true }

destack_unicode = { workspace = true }
destack_file = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
