/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, jsonField, jsonInteger, jsonObject } from "../../../../protocol/serde.js";
import type { SizeClassTable } from "../../allocator/class.js";
import type { GcOptions } from "../../core/gc.js";
import { decodeSizeClassTable, encodeSizeClassTable, fromJsonSizeClassTable, toJsonSizeClassTable } from "../../allocator/class.js";
import { decodeGcOptions, encodeGcOptions, fromJsonGcOptions, toJsonGcOptions } from "../../core/gc.js";

/** The configuration for one shared heap instance. */
export type SharedHeapOptions = {
    /** The collector configuration. */
    readonly gc: GcOptions;
    /** The configured small-block class table. */
    readonly sizeClasses: SizeClassTable;
    /** The byte size for shared heap small-block spans. */
    readonly heapSmallSizeBytes: number;
    /** The virtual byte capacity for shared heap storage. */
    readonly addressSpaceSizeBytes: number;
    /** The byte size for allocator pages. */
    readonly pageSizeBytes: number;
    /** The byte size for one physical allocator chunk. */
    readonly allocatorChunkSizeBytes: number;
    /** The required alignment for configured small-block classes. */
    readonly smallAllocationAlignmentBytes: number;
};

export const SharedHeapOptions = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: SharedHeapOptions): void {
        encodeSharedHeapOptions(writer, value);
    },

    /** Decode one SharedHeapOptions. */
    decode(reader: BinaryReader): SharedHeapOptions {
        return decodeSharedHeapOptions(reader);
    },

    /** Return this value as JSON. */
    toJson(value: SharedHeapOptions): Json {
        return toJsonSharedHeapOptions(value);
    },

    /** Return one SharedHeapOptions from one JSON value. */
    fromJson(value: Json): SharedHeapOptions {
        return fromJsonSharedHeapOptions(value);
    },
};

/** Encode one SharedHeapOptions. */
export function encodeSharedHeapOptions(writer: BinaryWriter, value: SharedHeapOptions): void {
    encodeGcOptions(writer, value.gc);
    encodeSizeClassTable(writer, value.sizeClasses);
    writer.writeUnsigned(value.heapSmallSizeBytes);
    writer.writeUnsigned(value.addressSpaceSizeBytes);
    writer.writeUnsigned(value.pageSizeBytes);
    writer.writeUnsigned(value.allocatorChunkSizeBytes);
    writer.writeUnsigned(value.smallAllocationAlignmentBytes);
}

/** Decode one SharedHeapOptions. */
export function decodeSharedHeapOptions(reader: BinaryReader): SharedHeapOptions {
    const gc = decodeGcOptions(reader);
    const sizeClasses = decodeSizeClassTable(reader);
    const heapSmallSizeBytes = reader.readNumber();
    const addressSpaceSizeBytes = reader.readNumber();
    const pageSizeBytes = reader.readNumber();
    const allocatorChunkSizeBytes = reader.readNumber();
    const smallAllocationAlignmentBytes = reader.readNumber();

    return {
        gc,
        sizeClasses,
        heapSmallSizeBytes,
        addressSpaceSizeBytes,
        pageSizeBytes,
        allocatorChunkSizeBytes,
        smallAllocationAlignmentBytes,
    };
}

/** Return one JSON value for one SharedHeapOptions. */
export function toJsonSharedHeapOptions(value: SharedHeapOptions): Json {
    return {
        gc: toJsonGcOptions(value.gc),
        sizeClasses: toJsonSizeClassTable(value.sizeClasses),
        heapSmallSizeBytes: value.heapSmallSizeBytes,
        addressSpaceSizeBytes: value.addressSpaceSizeBytes,
        pageSizeBytes: value.pageSizeBytes,
        allocatorChunkSizeBytes: value.allocatorChunkSizeBytes,
        smallAllocationAlignmentBytes: value.smallAllocationAlignmentBytes,
    };
}

/** Return one SharedHeapOptions from one JSON value. */
export function fromJsonSharedHeapOptions(value: Json): SharedHeapOptions {
    const object = jsonObject(value);

    return {
        gc: fromJsonGcOptions(jsonField(object, "gc")),
        sizeClasses: fromJsonSizeClassTable(jsonField(object, "sizeClasses")),
        heapSmallSizeBytes: jsonInteger(jsonField(object, "heapSmallSizeBytes")),
        addressSpaceSizeBytes: jsonInteger(jsonField(object, "addressSpaceSizeBytes")),
        pageSizeBytes: jsonInteger(jsonField(object, "pageSizeBytes")),
        allocatorChunkSizeBytes: jsonInteger(jsonField(object, "allocatorChunkSizeBytes")),
        smallAllocationAlignmentBytes: jsonInteger(jsonField(object, "smallAllocationAlignmentBytes")),
    };
}
