[package]
name = "destack_cli_macros"
description = "Destack CLI Macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
destack = { workspace = true }
destack_codegen = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
