# Generated by Django 4.0.4 on 2022-08-01 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bench", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flownode",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
