# Generated by Django 4.1.3 on 2022-11-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bench", "0002_alter_dataset_schema"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="instructionargument",
            name="bench_instruction_argument_bound_free_ck",
        ),
        migrations.AddConstraint(
            model_name="instructionargument",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("instruction_bound__isnull", True),
                    ("instruction_free__isnull", True),
                    _connector="XOR",
                ),
                name="bench_instruction_argument_bound_free_ck",
            ),
        ),
    ]
