# Generated by Django 4.2.1 on 2023-06-01 13:26

from django.db import migrations, models
import django_choices_field.fields


class PlaceholderEnum(models.TextChoices):
    value = "0" * 32


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0002_remove_execution_build_remove_execution_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="tenancy",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("COMMUNITY", "Community"), ("DEDICATED", "Dedicated")],
                choices_enum=PlaceholderEnum,
                default="COMMUNITY",
                max_length=9,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="execution",
            name="tracing_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="execution",
            name="trigger_type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("rest", "Api"), ("ui", "Ui")],
                choices_enum=PlaceholderEnum,
                max_length=4,
            ),
        ),
    ]
