# Generated by Django 4.1.3 on 2022-11-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bench", "0003_remove_instruction_bench_instruction_code_id_xor_code_ck_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructionargument",
            name="type",
            field=models.CharField(
                choices=[
                    ("dataset", "Dataset"),
                    ("model", "Model"),
                    ("instruction", "Instruction"),
                    ("json", "Json"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="instructionparameter",
            name="type",
            field=models.CharField(
                choices=[
                    ("dataset", "Dataset"),
                    ("model", "Model"),
                    ("instruction", "Instruction"),
                    ("json", "Json"),
                ],
                max_length=64,
            ),
        ),
    ]
