# Generated by Django 4.1.5 on 2023-02-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bench", "0003_ownerslug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="completed_signup",
            field=models.BooleanField(default=False),
        ),
    ]
