# Generated by Django 4.2.1 on 2023-06-06 16:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0010_issue_file_issue_scope_alter_resolvedfield_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="field",
            name="value",
        ),
        migrations.AlterField(
            model_name="resolvedfield",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
