# Generated by Django 4.2.1 on 2023-07-02 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0018_remove_statement_modifier_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statement",
            name="commented",
        ),
    ]
