# Generated by Django 4.2.1 on 2023-07-11 15:35

import bench.utils.uuidt
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0026_remove_user_completed_signup_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Run",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=bench.utils.uuidt.UUIDT,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Scheduled", "Scheduled"),
                            ("Queued", "Queued"),
                            ("Running", "Running"),
                            ("Aborting", "Aborting"),
                            ("Aborted", "Aborted"),
                            ("Failed", "Failed"),
                            ("Completed", "Completed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                ("inputs", models.JSONField(blank=True, null=True)),
                ("outputs", models.JSONField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("cached_generated_at", models.DateTimeField(blank=True, null=True)),
                ("cached_duration", models.FloatField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="bench.run",
                    ),
                ),
                (
                    "project_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bench.projectversion"
                    ),
                ),
                (
                    "root",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descendants",
                        to="bench.run",
                    ),
                ),
                (
                    "runnable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bench.statement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=bench.utils.uuidt.UUIDT,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tracing_level", models.IntegerField(default=0)),
                (
                    "trigger_type",
                    models.CharField(choices=[("rest", "API"), ("ui", "UI")], max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "access_token",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bench.accesstoken",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bench.project"
                    ),
                ),
                (
                    "project_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bench.projectversion"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated_signup", "Initiated Signup"),
                    ("waitlisted", "Waitlisted"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("deactivated", "Deactivated"),
                ],
                max_length=32,
            ),
        ),
        migrations.DeleteModel(
            name="Execution",
        ),
        migrations.AddField(
            model_name="session",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bench.worker",
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="runs", to="bench.session"
            ),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["started_at"], name="run_started_at_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["updated_at"], name="run_updated_at_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["runnable_id"], name="run_runnable_id_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(
                fields=["runnable_id", "project_version_id"], name="run_runnable_id_scoped_idx"
            ),
        ),
    ]
