# Generated by Django 4.2.1 on 2023-07-21 09:01

import bench.language.tag
import bench.language.type
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0030_remove_run_cached_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="runnable_type",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bench.worker",
            ),
        ),
        migrations.AlterField(
            model_name="field",
            name="key",
            field=models.CharField(default=bench.language.type.new_field_key, max_length=48),
        ),
        migrations.AlterField(
            model_name="tagging",
            name="key",
            field=models.CharField(default=bench.language.tag.new_tag_key, max_length=48),
        ),
    ]
