# Generated by Django 4.1.5 on 2023-03-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0033_evaluationresult_buildcandidate"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildcandidate",
            name="order_key",
            field=models.CharField(default="a1", max_length=64),
            preserve_default=False,
        ),
    ]
