# Generated by Django 4.1.5 on 2023-03-31 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bench", "0045_remove_execution_model_inference_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="xblock",
            options={"ordering": ["order_key"]},
        ),
        migrations.AddField(
            model_name="buildcandidate",
            name="instruct_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="bench.statement",
            ),
        ),
    ]
