# Generated by Django 4.1.5 on 2023-04-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bench", "0055_remove_statement_on_job_symbol_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statement",
            name="value",
        ),
    ]
