# Generated by Django 4.1.5 on 2023-04-20 07:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0056_remove_statement_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildcandidate",
            name="build",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="build_candidates",
                to="bench.statement",
            ),
        ),
        migrations.AlterField(
            model_name="buildcandidate",
            name="file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="bench.file",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationresult",
            name="record",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluation_results",
                to="bench.datasetrecord",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationresult",
            name="statement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluation_results",
                to="bench.statement",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationresult",
            name="type_node",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluation_results",
                to="bench.simpletypenode",
            ),
        ),
        migrations.CreateModel(
            name="EvaluationPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "generated_dataset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="bench.statement",
                    ),
                ),
                (
                    "statement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_plan",
                        to="bench.statement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvaluateSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("weights", models.JSONField()),
                ("reactive", models.BooleanField()),
                (
                    "statement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluate_settings",
                        to="bench.statement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuildSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reactive", models.BooleanField(default=False)),
                (
                    "statement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_settings",
                        to="bench.statement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
