# Generated by Django 4.2.3 on 2023-11-04 09:59

from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0068_project_base_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="search_password",
            field=pgcrypto.fields.TextPGPSymmetricKeyField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="storage_password",
            field=pgcrypto.fields.TextPGPSymmetricKeyField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="statement",
            name="type",
            field=models.CharField(
                choices=[
                    ("tag", "TAG"),
                    ("text", "TEXT"),
                    ("blank", "BLANK"),
                    ("class", "CLASS"),
                    ("choice", "CHOICE"),
                    ("task", "TASK"),
                    ("code", "CODE"),
                    ("flow", "FLOW"),
                    ("model", "MODEL"),
                    ("variable", "VARIABLE"),
                    ("database", "DATABASE"),
                    ("reference", "REFERENCE"),
                    ("group", "GROUP"),
                ],
                max_length=32,
            ),
        ),
    ]
