# Generated by Django 4.2.1 on 2023-05-15 08:06
import enum

from django.db import migrations, models


class TypeFlag(enum.IntFlag):
    Null = 2**0
    IsOutput = 2**0
    IsArray = 2**1
    IsNullable = 2**2
    IsUnionWith = 2**3


def set_type_flags(apps, schema_editor):
    SimpleTypeNode = apps.get_model("bench", "SimpleTypeNode")

    for simple_type_node in SimpleTypeNode.objects.all():
        flags = 0
        if simple_type_node.is_array:
            flags |= TypeFlag.IsArray
        if simple_type_node.is_nullable:
            flags |= TypeFlag.IsNullable
        if simple_type_node.is_output:
            flags |= TypeFlag.IsOutput
        simple_type_node.flags = flags
        simple_type_node.save()


def revert_type_flags(apps, schema_editor):
    SimpleTypeNode = apps.get_model("bench", "SimpleTypeNode")

    for simple_type_node in SimpleTypeNode.objects.all():
        flags = simple_type_node.flags
        simple_type_node.is_array = bool(flags & TypeFlag.IsArray)
        simple_type_node.is_nullable = bool(flags & TypeFlag.IsNullable)
        simple_type_node.is_output = bool(flags & TypeFlag.IsOutput)
        simple_type_node.save()


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0071_buildsettings_weights"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpletypenode",
            name="flags",
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(set_type_flags, revert_type_flags),
        migrations.RemoveField(
            model_name="simpletypenode",
            name="is_array",
        ),
        migrations.RemoveField(
            model_name="simpletypenode",
            name="is_nullable",
        ),
        migrations.RemoveField(
            model_name="simpletypenode",
            name="is_output",
        ),
    ]
