# Generated by Django 4.2.1 on 2023-05-17 15:46

import bench.language.type
from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields
import pgcrypto.fields
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0073_statement_root_type_flags"),
    ]

    operations = [
        migrations.AddField(
            model_name="simpletypenode",
            name="hint",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("string", "String"),
                    ("number", "Number"),
                    ("boolean", "Boolean"),
                    ("embedding", "Embedding"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("file", "File"),
                    ("struct", "Struct"),
                    ("json", "Json"),
                    ("function", "Function"),
                    ("union", "Union"),
                    ("enum", "Enum"),
                    ("literal", "Literal"),
                    ("null", "Null"),
                    ("any", "Any"),
                    ("ref", "Type Reference"),
                ],
                choices_enum=bench.language.type.TypeTag,
                max_length=9,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sha512", models.CharField(max_length=128)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("value", pgcrypto.fields.TextPGPPublicKeyField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="bench.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
