# Generated by Django 4.2.3 on 2023-12-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0079_remove_run_run_statement_id_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statement",
            name="reference_ck",
        ),
        migrations.AlterField(
            model_name="statement",
            name="type",
            field=models.CharField(
                choices=[
                    ("tag", "TAG"),
                    ("text", "TEXT"),
                    ("blank", "BLANK"),
                    ("class", "CLASS"),
                    ("choice", "CHOICE"),
                    ("task", "TASK"),
                    ("code", "CODE"),
                    ("flow", "FLOW"),
                    ("model", "MODEL"),
                    ("variable", "VARIABLE"),
                    ("database", "DATABASE"),
                    ("view", "VIEW"),
                    ("group", "GROUP"),
                ],
                max_length=32,
            ),
        ),
    ]
