# Generated by Django 4.2.3 on 2024-01-04 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bench", "0097_rename_ownerslug_handle_remove_workerset_bench_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="benchmembership",
            name="bench",
        ),
        migrations.RemoveField(
            model_name="benchmembership",
            name="user",
        ),
        migrations.RemoveField(
            model_name="organizationinvite",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="organizationinvite",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="organizationinvite",
            name="user",
        ),
        migrations.RemoveField(
            model_name="organizationmembership",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="organizationmembership",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="bench",
            options={
                "base_manager_name": "objects",
                "default_related_name": "benches",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="handle",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
        migrations.DeleteModel(
            name="BenchMembership",
        ),
        migrations.DeleteModel(
            name="OrganizationInvite",
        ),
        migrations.DeleteModel(
            name="OrganizationMembership",
        ),
        migrations.DeleteModel(
            name="BenchInvite",
        ),
    ]
