/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, jsonInteger } from "../../protocol/serde.js";

/** Durable 32-bit runtime type id inside one program. */
export type TypeId = number;

export const TypeId = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: TypeId): void {
        encodeTypeId(writer, value);
    },

    /** Decode one TypeId. */
    decode(reader: BinaryReader): TypeId {
        return decodeTypeId(reader);
    },

    /** Return this value as JSON. */
    toJson(value: TypeId): Json {
        return toJsonTypeId(value);
    },

    /** Return one TypeId from one JSON value. */
    fromJson(value: Json): TypeId {
        return fromJsonTypeId(value);
    },
};

/** Encode one TypeId. */
export function encodeTypeId(writer: BinaryWriter, value: TypeId): void {
    writer.writeUnsigned(value);
}

/** Decode one TypeId. */
export function decodeTypeId(reader: BinaryReader): TypeId {
    return reader.readNumber();
}

/** Return one JSON value for one TypeId. */
export function toJsonTypeId(value: TypeId): Json {
    return value;
}

/** Return one TypeId from one JSON value. */
export function fromJsonTypeId(value: Json): TypeId {
    return jsonInteger(value);
}
