// generated by generate-bindings: do not edit

use super::types::HostPermissionRequest;
use crate::host::apple::abi::binding::invoke_ios_binding_callback;

/// The host callback for `request`.
pub(crate) type IosHostPermissionRequestCallback =
    unsafe extern "C" fn(session_handle: u64, request: HostPermissionRequest) -> u32;

/// The host callback for `open_settings`.
pub(crate) type IosHostPermissionOpenSettingsCallback =
    unsafe extern "C" fn(session_handle: u64) -> u32;

/// Callback table for iOS host permission request interop.
#[derive(Clone, Copy, Debug, Default)]
#[repr(C)]
pub(crate) struct IosHostPermissionCallbacks {
    /// The callback for `request`.
    pub request: Option<IosHostPermissionRequestCallback>,
    /// The callback for `open_settings`.
    pub open_settings: Option<IosHostPermissionOpenSettingsCallback>,
}

/// Resolve and invoke one iOS host permission callback.
pub(super) fn call_ios_permission_callback<T: Copy>(
    session_handle: u64,
    resolve: impl FnOnce(&IosHostPermissionCallbacks) -> Option<T>,
    invoke: impl FnOnce(T) -> u32,
) -> u32 {
    invoke_ios_binding_callback(
        session_handle,
        |bindings| resolve(&bindings.permission),
        invoke,
    )
}
