FROM python:3.13-slim

LABEL org.opencontainers.image.source=https://github.com/symbolx/bench
LABEL org.opencontainers.image.description="Bench"

#
# OS
#

# install libs
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzbar-dev \
    postgresql-client \
    ffmpeg \
    gcc \
    gfortran \
    g++ \
    pkg-config \
    cmake \
    libopenblas-dev \
    liblapack-dev \
    libxml2-dev \
    libxslt-dev \
    git \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# create bench-runtime user
RUN useradd -ms /bin/bash bench-runtime \
    && echo "bench-runtime ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# uv
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && mv /root/.local/bin/uv /usr/local/bin/ && rm /uv-installer.sh
ENV PATH="/usr/local/bin:$PATH"

ENV PYTHONUNBUFFERED=1

# install requirements
COPY bench/requirements/runtime.txt /home/bench-runtime/requirements.txt
WORKDIR /home/bench-runtime
RUN uv pip install --system --no-cache -r requirements.txt

# copy relevant files
COPY --chown=bench-runtime:bench-runtime bench/ /home/bench-runtime/bench/
# prune unnecessary files
RUN rm -rf /home/bench-runtime/bench/system /home/bench-runtime/bench/test
RUN find /home/bench-runtime/bench/ -type f -name 'test_*.py' -delete

COPY --chown=bench-runtime:bench-runtime bench.py /home/bench-runtime/
COPY --chown=bench-runtime:bench-runtime pyproject.toml /home/bench-runtime/
COPY --chown=bench-runtime:bench-runtime version /home/bench-runtime/

# startup script
RUN cat <<'EOF' > /start.sh
#!/bin/sh
su bench-runtime -s /bin/bash -m -c "python3 /home/bench-runtime/bench.py serve runtime 0.0.0.0 5432"
EOF
RUN chmod +x /start.sh

ARG GIT_COMMIT
ARG VERSION
ENV GIT_COMMIT=$GIT_COMMIT
ENV VERSION=$VERSION

EXPOSE 5432
EXPOSE 80

CMD ["/start.sh"] 