# define the common base image
FROM python:3.13-slim AS bench-base

LABEL org.opencontainers.image.source=https://github.com/symbolx/bench
LABEL org.opencontainers.image.description="Bench"

# install libs
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzbar-dev \
    postgresql-client \
    ffmpeg \
    gcc \
    gfortran \
    g++ \
    pkg-config \
    cmake \
    libopenblas-dev \
    liblapack-dev \
    libxml2-dev \
    libxslt-dev \
    git \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# uv
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && rm /uv-installer.sh
ENV PATH="/root/.local/bin/:$PATH"

ENV PYTHONUNBUFFERED=1

# --- System (Supervisor/Host) ---
FROM bench-base AS bench-system

COPY bench/requirements/system.txt requirements.txt
RUN uv pip install --system --no-cache -r requirements.txt

# copy relevant files
COPY bench/ bench/
COPY bench.py .
COPY pyproject.toml .
COPY version .
# prune unnecessary files
RUN rm -rf bench/test
# prune tests
RUN find bench/ -type f -name 'test_*.py' -delete

ARG GIT_COMMIT
ARG VERSION
ENV GIT_COMMIT=$GIT_COMMIT
ENV VERSION=$VERSION

EXPOSE 5432
EXPOSE 80

# --- Runtime ---
FROM bench-base AS bench-runtime

COPY bench/requirements/runtime.txt requirements.txt
RUN uv pip install --system --no-cache -r requirements.txt

# copy relevant files
COPY bench/ bench/ 
# prune unnecessary files
RUN rm -rf bench/system bench/test bench/builtin
# prune tests
RUN find bench/ -type f -name 'test_*.py' -delete

COPY bench.py .
COPY pyproject.toml .
COPY version .

ARG GIT_COMMIT
ARG VERSION
ENV GIT_COMMIT=$GIT_COMMIT
ENV VERSION=$VERSION

EXPOSE 5432
EXPOSE 80