FROM python:3.13-slim

LABEL org.opencontainers.image.source=https://github.com/symbolx/bench
LABEL org.opencontainers.image.description="Bench"

#
# OS
#

# install libs
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzbar-dev \
    postgresql-client \
    ffmpeg \
    gcc \
    gfortran \
    g++ \
    pkg-config \
    cmake \
    libopenblas-dev \
    liblapack-dev \
    libxml2-dev \
    libxslt-dev \
    git \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# create bench-system user
RUN useradd -ms /bin/bash bench-system \
    && echo "bench-system ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# uv
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && mv /root/.local/bin/uv /usr/local/bin/ && rm /uv-installer.sh
ENV PATH="/usr/local/bin:$PATH"

ENV PYTHONUNBUFFERED=1

# install requirements
COPY bench/requirements/system.txt /home/bench-system/requirements.txt
WORKDIR /home/bench-system
RUN uv pip install --system --no-cache -r requirements.txt

# copy relevant files
COPY --chown=bench-system:bench-system bench/ /home/bench-system/bench/
COPY --chown=bench-system:bench-system bench.py /home/bench-system/
COPY --chown=bench-system:bench-system pyproject.toml /home/bench-system/
COPY --chown=bench-system:bench-system version /home/bench-system/
# prune unnecessary files
RUN rm -rf /home/bench-system/bench/test
# prune tests
RUN find /home/bench-system/bench/ -type f -name 'test_*.py' -delete

# startup script
RUN cat <<'EOF' > /start.sh
#!/bin/sh
su bench-system -s /bin/bash -m -c "python3 /home/bench-system/bench.py serve supervisor 0.0.0.0 5432"
EOF
RUN chmod +x /start.sh

ARG GIT_COMMIT
ARG VERSION
ENV GIT_COMMIT=$GIT_COMMIT
ENV VERSION=$VERSION

EXPOSE 5432
EXPOSE 80

CMD ["/start.sh"] 