# define the common base image
FROM python:3.13-slim AS bench-base

LABEL org.opencontainers.image.source=https://github.com/symbolx/bench
LABEL org.opencontainers.image.description="Bench"

RUN apt-get update
# install postgresql-libs
RUN apt-get install -y libpq-dev libzbar-dev postgresql-client
# install ML libs
RUN apt-get install -y ffmpeg
# install GCC and Fortran
RUN apt-get install -y gcc gfortran
RUN apt-get install -y pkg-config cmake libopenblas-dev liblapack-dev
# install git
RUN apt-get install -y git
# install curl
RUN apt-get install -y curl
# install uv 
ADD --chmod=755 https://astral.sh/uv/install.sh /install.sh
RUN /install.sh && rm /install.sh

ENV PYTHONUNBUFFERED=1

# --- System (Supervisor/Host) ---
FROM bench-base AS bench-system

COPY bench/requirements/system.txt requirements.txt
RUN /root/.cargo/bin/uv pip install --system --no-cache -r requirements.txt

# copy relevant files
COPY bench/ bench/
COPY bench.py .
COPY pyproject.toml .
COPY version .
# prune unnecessary files
RUN rm -rf bench/test
# prune tests
RUN find bench/ -type f -name 'test_*.py' -delete

ARG GIT_COMMIT
ARG VERSION
ENV GIT_COMMIT=$GIT_COMMIT
ENV VERSION=$VERSION

EXPOSE 5432
EXPOSE 80

# --- Runtime ---
FROM bench-base AS bench-runtime

# install pandoc
RUN apt-get install -y pandoc

COPY bench/requirements/runtime.txt requirements.txt
RUN /root/.cargo/bin/uv pip install --system --no-cache -r requirements.txt

# copy relevant files
COPY bench/ bench/ 
# prune unnecessary files
RUN rm -rf bench/system bench/test
# prune tests
RUN find bench/ -type f -name 'test_*.py' -delete

COPY bench.py .
COPY pyproject.toml .
COPY version .

ARG GIT_COMMIT
ARG VERSION
ENV GIT_COMMIT $GIT_COMMIT
ENV VERSION $VERSION

EXPOSE 5432
EXPOSE 80