syntax = "proto3";

package symbol.destack;

import "google/protobuf/struct.proto";
import "destack-proto/common.proto";
import "destack-proto/language.proto";

message ScopeProto {
  string space_id = 1;
}

message QueryRequest {
  ScopeProto scope = 1;
  // The Query to execute.
  QueryProto query = 2;
}
message QueryResponse {
  // The result of the Query.
  QueryResultProto result = 1;
}

message CommitRequest {
  ScopeProto scope = 1;
  repeated SomeEventProto events = 3;
}
message CommitResponse {
  uint64 epoch = 3;
  repeated SomeEventProto events = 4;
}

message SubscribeRequest {
  QueryProto query = 1;
}
message SubscribeResponse {
  // The result of the Query.
  QueryUpdateProto update = 1;
}

message UploadFilesRequest { 
  ScopeProto scope = 1;
  repeated FileProto files = 2;
}

message UploadFilesResponse {
  message UploadHandle {
    FileProto file = 1;
    string post_url = 2;
    google.protobuf.Struct fields = 3;
    string get_url = 4;
  }
  repeated UploadHandle handles = 1; // handles for each valid file upload
}

message DownloadFilesRequest {
  ScopeProto scope = 1;
  repeated NodeReferenceProto files = 2;
}

message DownloadFilesResponse {
  message DownloadHandle {
    FileProto file = 1;
    string get_url = 2;
  }
  repeated DownloadHandle handles = 1; // handles for each valid file download
}

// A Host provides the operating system of a Space.
service Space {
  option (kind) = PUBLIC; // :ServiceKind
  
  // NOTE :Architecture: maybe separate methods for non-Entity commits? (Event/Analytic/... upserts?)
  // Query the Space.
  rpc Query(QueryRequest) returns (QueryResponse);
  // Commit Changes to the Space.
  rpc Commit(CommitRequest) returns (CommitResponse);
  // Subscribe to updates from the Space.
  rpc Subscribe(SubscribeRequest) returns (stream SubscribeResponse);

  // 'Upload' some files (get URLs to upload them to).
  rpc UploadFiles(UploadFilesRequest) returns (UploadFilesResponse);
  // 'Download' some files (get URLs to download them from).
  rpc DownloadFiles(DownloadFilesRequest) returns (DownloadFilesResponse);
}
