syntax = "proto3";

package symbol.destack;

import "google/protobuf/struct.proto";
import "destack-proto/common.proto";
import "destack-proto/language.proto";

message ScopeProto {
  string space_id = 1;
}

message QueryRequest {
  ScopeProto scope = 1;
  // The Query to execute.
  QueryProto query = 2;
}
message QueryResponse {
  // The result of the Query.
  QueryResultProto result = 1;
}

message AppendRequest {
  ScopeProto scope = 1;
  repeated SomeEventProto events = 3;
}
message AppendResponse {
  uint64 epoch = 3;
  repeated SomeEventProto events = 4;
}

message SubscribeRequest {
  QueryProto query = 1;
}
message SubscribeResponse {
  // The result of the Query.
  QueryUpdateProto update = 1;
}

// A Host provides the operating system of a Space.
service Space {
  option (kind) = PUBLIC; // :ServiceKind
  
  // NOTE :Architecture: maybe separate methods for non-Entity commits? (Event/Analytic/... upserts?)
  // Query the Space.
  rpc Query(QueryRequest) returns (QueryResponse);
  // Commit Events to the Space.
  rpc Append(AppendRequest) returns (AppendResponse);
  // Subscribe to updates from the Space.
  rpc Subscribe(SubscribeRequest) returns (stream SubscribeResponse);
}
