syntax = "proto3";

package symbol.destack;

import "destack-proto/common.proto";
import "destack-proto/language.proto";

message SignupUserRequest {
  string slug = 2;
  optional string name = 3;
  string email = 4 [(sensitive) = true];
  string password = 5 [(sensitive) = true];
  RegionProto region = 6;
  ClientProto client = 9;
}
message SignupUserResponse {
  UserProto user = 1;
  ClientProto client = 2;
  SpaceProto space = 3;
  string access_token = 4 [(sensitive) = true];
}

message ChangeUserPasswordRequest {
  string old_password = 1 [(sensitive) = true];
  string new_password = 2 [(sensitive) = true];
}
message ChangeUserPasswordResponse {
  UserProto user = 1;
  ClientProto client = 2;
  uint64 epoch = 3;
}

message LoginUserRequest {
  oneof user {
    string id = 1;
    string slug = 2;
    string email = 3 [(sensitive) = true];
  }
  string password = 4 [(sensitive) = true];
  ClientProto client = 5;
}
message LoginUserResponse {
  UserProto user = 1;
  ClientProto client = 2;
  string access_token = 3 [(sensitive) = true];
}

message LogoutUserRequest {
  // If specified, log out only the specified clients (instead of the current client).
  repeated NodeReferenceProto clients = 1;
  // If specified, log out all clients (incl. current).
  optional bool logout_all = 2;
}
message LogoutUserResponse {
}

message CreateOrganizationRequest {
  OrganizationProto organization = 1;
}
message CreateOrganizationResponse {
  OrganizationProto organization = 1;
  uint64 epoch = 2;
}

message ResolveSpacesRequest {
  message SpaceKey {
    oneof space {
      string id = 1;
      string slug = 2;
    }
  }
  repeated SpaceKey spaces = 1;
}
message ResolveSpacesResponse {
  message SpaceInfo {
    string domain = 1;
    int32 grpc_port = 2;
    int32 grpc_web_port = 3;
    bool ssl = 4;
    NodeReferenceProto space = 5;
  }
  repeated SpaceInfo spaces = 1;
}

service Universe {
  option (kind) = PUBLIC; // :ServiceKind

  // Create User.
  rpc SignupUser(SignupUserRequest) returns (SignupUserResponse);
  // Change User.password.
  rpc ChangeUserPassword(ChangeUserPasswordRequest) returns (ChangeUserPasswordResponse);
  // Login User with a new or existing Client.
  rpc LoginUser(LoginUserRequest) returns (LoginUserResponse);
  // Logout User with the current or other owned Clients.
  rpc LogoutUser(LogoutUserRequest) returns (LogoutUserResponse);

  // Gets Space space information.
  rpc ResolveSpaces(ResolveSpacesRequest) returns (ResolveSpacesResponse);
}
