[package]
name = "destack_parser"
description = "Destack AST parsing"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"

[dependencies]
destack = { path = "../destack" }
destack_unicode = { path = "../destack_unicode" }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "lexer"
harness = false

[lints]
workspace = true
