[package]
name = "destack_system"
description = "Destack Rust system library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "destack-system"
path = "src/main.rs"

[dependencies]
destack = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
itoa = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]