[package]
name = "destack_system"
description = "Destack Rust system library"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "destack-system"
path = "src/main.rs"

[dependencies]
destack = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
smallvec = { workspace = true }
regex = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = "0.7.9"

[dev-dependencies]
pretty_assertions = { workspace = true }
quickcheck = { workspace = true }
thiserror = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
wasm-bindgen-test = { workspace = true }