[package]
name = "cranelift-srcgen"
version = "0.131.1"
authors = ["The Wasmtime Project Developers"]
description = "Helper functions for generating Rust and ISLE files"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2024"
rust-version = "1.92.0"


[dependencies]
