[package]
name = "destack_lang_lex"
description = "Destack Language Lexer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"

[dependencies]
destack_std_unicode = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "lex"
harness = false

[lints]
workspace = true
