[package]
name = "wasmtime-math"
version = "0.127.0"
description = "Low-level math routines (vendored from Wasmtime)"
documentation = "https://docs.rs/wasmtime-math"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
edition = "2021"


[package.metadata.docs.rs]
all-features = true

[features]
std = []

[dependencies]
libm = { workspace = true }
