import structlog
from asgiref.sync import async_to_sync
from django.core.management.base import BaseCommand
from django.db import transaction

from bench import models
from bench.language.const import NodeType
from bench.language.module import NODE_CLASS_BY_NODE_TYPE
from bench.models import Bench
from bench.sql.engine import (
    create_local_pg_database,
    delete_local_pg_database,
    map_bench_node_to_pg_table,
    update_pg_schema,
)
from bench.utils.utils import format_python

logger = structlog.get_logger(__name__)


async def update_pg_schema_from_db(module: models.Module) -> None:
    from bench.runtime.utils import interp_module

    logger.info("pg.update_mappings", module=repr(module))
    module, bench = await interp_module(module.id)
    await update_pg_schema(bench.pg_name, module)


class Command(BaseCommand):
    help = "Manage user PG databases."

    def add_arguments(self, parser):
        parser.add_argument("action", type=str)
        # optional arguments
        parser.add_argument("slug", type=str, nargs="?")

    def get_bench(self, slug: str) -> Bench:
        owner, bench_name = slug.split("/")
        bench = Bench.objects.get_by_slug(owner, bench_name)
        for attr in ("user", "organization", "head", "pg_username", "pg_password"):
            getattr(bench, attr)
        return bench

    @transaction.atomic
    def handle(self, action: str, slug: str | None, *args, **options):
        if slug == "all":
            benches = (
                models.Bench.objects.select_related("user", "organization", "head")
                .defer(None)
                .all()
            )
        elif slug:
            benches = [self.get_bench(slug)]
        else:
            benches = []

        if action == "bench_schema":
            chunks: list[str] = [
                # standardized generated notice
                "# This file was automatically generated by Bench. Do not edit.",
                "from bench.sql.core import Table, Column, ColumnType, Constraint, ConstraintType, Index, IndexType",
            ]
            for node_t in NodeType:
                node_cls = NODE_CLASS_BY_NODE_TYPE[node_t]
                if not node_cls.__is_stored__ or node_cls.__is_local__:
                    continue
                table = map_bench_node_to_pg_table(node_cls)
                const_name = f"{node_cls.metatype.name}_TABLE"
                table_def = f"{const_name} = {table.source_repr()}"
                chunks.append(table_def)
            source = "\n\n".join(chunks)
            source = format_python(source)
            print(source)
        elif action == "local_create":
            for bench in benches:
                async_to_sync(create_local_pg_database)(bench, upsert=True)
        elif action == "local_schema_apply":
            for bench in benches:
                module = bench.head
                module.parent_bench = bench  # 'preloaded' bench
                module.parent_bench.owner  # noqa why do we need to load this again?
                async_to_sync(update_pg_schema_from_db)(module)
        elif action == "local_delete":
            for bench in benches:
                async_to_sync(delete_local_pg_database)(bench)
        else:
            raise ValueError("Unknown action")
