from bench.utils.utils import IS_DEBUG, get_from_env

KUBERNETES_KUBECONFIG_PATH = get_from_env("KUBERNETES_KUBECONFIG_PATH", optional=True)
KUBERNETES_KUBECONFIG_CTX = get_from_env("KUBERNETES_KUBECONFIG_CTX", optional=True)
KUBERNETES_SERVER_IMAGE = get_from_env("KUBERNETES_SERVER_IMAGE", optional=True)
KUBERNETES_SERVER_NAMESPACE = get_from_env("KUBERNETES_SERVER_NAMESPACE", default="default")
KUBERNETES_SERVER_ENV_VARS_STR = get_from_env("KUBERNETES_SERVER_ENV_VARS", optional=True)
KUBERNETES_SERVER_IMAGE_PULL_SECRET_NAME = get_from_env(
    "KUBERNETES_SERVER_IMAGE_PULL_SECRET_NAME", optional=True
)
KUBERNETES_ENABLED = get_from_env("KUBERNETES_ENABLED", default=not IS_DEBUG, type_cast=bool)
