# ruff: noqa

from typing import TYPE_CHECKING, Union

VERSION = "2025.06.16.0"

# import from all generated files
from .health_pb2 import *
from .common_pb2 import *
from .common_grpc import *
from .language_grpc import *
from .destack_grpc import *
from .space_grpc import *
from .health_grpc import *
from .language_pb2 import *
from .destack_pb2 import *
from .space_pb2 import *
from .google.type.date_pb2 import *
from .google.type.timeofday_pb2 import *
from .google.type.datetime_pb2 import *

# extra utility types
AnyNodeData = Union[
    CustomEntityDefinitionData,
    CustomEntityData,
    CustomEnumDefinitionData,
    EditEventData,
    CustomEventDefinitionData,
    CustomEventData,
    FieldData,
    GaugeMetricData,
    GaugeMeasurementData,
    CounterMetricData,
    CounterMeasurementData,
    HistogramMetricData,
    HistogramMeasurementData,
    OptionData,
    SnapshotData,
    BranchData,
    CustomStructDefinitionData,
    EntitlementEventData,
    EntitlementData,
    InviteEventData,
    InviteData,
    MembershipEventData,
    MembershipData,
    PermissionData,
    RoleEventData,
    RoleData,
    SanctionEventData,
    SanctionData,
    CustomViewDefinitionData,
    CustomViewData,
    FrameViewData,
    LabelViewData,
    SplitViewData,
    TextViewData,
    NumberInputViewData,
    SliderInputViewData,
    WizardViewData,
    ThreadViewData,
    AnnotationShapeData,
    ArrowShapeData,
    CanvasData,
    LineShapeData,
    PlaneShapeData,
    FileData,
    LinkData,
    EnvironmentData,
    FolderData,
    TagData,
    TaggingData,
    DatabaseData,
    MachineData,
    ActionData,
    EventCursorData,
    ScreenCursorData,
    ThreadCursorData,
    RouteData,
    ScriptData,
    ServiceData,
    TimerEventData,
    TimerData,
    TriggerEventData,
    TriggerData,
    InterruptionData,
    LogData,
    RunEventData,
    RunData,
    SpanData,
    LayerData,
    SceneEventData,
    SceneData,
    VariantData,
    WindowData,
    FollowData,
    MessageData,
    NotificationEventData,
    NotificationData,
    ReactionData,
    StarData,
    ThreadData,
    AgentData,
    ClientData,
    FriendshipData,
    FriendshipInviteEventData,
    FriendshipInviteData,
    HandleData,
    OrganizationData,
    SpaceData,
    TeamData,
    UserData,
    ColorStyleData,
    BorderStyleData,
    TransitionStyleData,
    EffectStyleData,
    GradientStyleData,
    FillStyleData,
    FontStyleData,
    PaletteData,
    ShadowStyleData,
    ThemeData,
]
AnyStructData = Union[
    ScopeData,
    RelationReferenceData,
    AttributeReferenceData,
    PropertyReferenceData,
    NodeReferenceData,
    EditData,
    ChangeData,
    ChangeResultData,
    ErrorData,
    StringConstraintData,
    NumberConstraintData,
    CollectionConstraintData,
    NodeConstraintData,
    TypeData,
    ValueData,
    FunctionData,
    ConditionData,
    AggregationData,
    ExpressionData,
    SortData,
    SelectData,
    JoinData,
    QueryData,
    HistogramData,
    QueryResultData,
    QueryResultGroupData,
    QueryUpdateData,
    SelectionData,
    IconData,
    PropertyDefinitionData,
    TraitDefinitionData,
    NodeDefinitionData,
    StructDefinitionData,
    EnumDefinitionData,
    EnumOptionDefinitionData,
    PermissionDefinitionData,
    TextSpanData,
    TextLineData,
    TextData,
    LengthData,
    PositionData,
    DimensionData,
    InsetsData,
    CornersData,
    Axis2Data,
    Axis3Data,
    Vector2Data,
    Vector3Data,
    Vector4Data,
    Vector2iData,
    Vector3iData,
    Vector4iData,
    GridData,
    GridSpanData,
    DatabaseInfoData,
    GalaxyInfoData,
    ScheduleData,
    OriginData,
    ColorData,
    BorderData,
    TransitionData,
    EffectData,
    GradientStopData,
    GradientData,
    FillData,
    FontData,
    ShadowData,
]
AnyObjectData = AnyNodeData | AnyStructData
