# ruff: noqa

from typing import TYPE_CHECKING, Union

VERSION = "2025.06.10.0"

# import from all generated files
from .runtime_pb2 import *
from .health_pb2 import *
from .common_pb2 import *
from .common_grpc import *
from .language_grpc import *
from .runtime_grpc import *
from .supervisor_grpc import *
from .host_grpc import *
from .health_grpc import *
from .language_pb2 import *
from .supervisor_pb2 import *
from .host_pb2 import *
from .google.type.date_pb2 import *
from .google.type.timeofday_pb2 import *
from .google.type.datetime_pb2 import *

# extra utility types
AnyNodeData = Union[
    CustomEntityDefinitionData,
    CustomEntityData,
    EditEventData,
    ChangeEventData,
    QueryEventData,
    CustomEventDefinitionData,
    CustomEventData,
    FieldData,
    GaugeMetricData,
    GaugeMeasurementData,
    CounterMetricData,
    CounterMeasurementData,
    HistogramMetricData,
    HistogramMeasurementData,
    SchemaData,
    FileData,
    LinkData,
    FolderData,
    FolderMembershipData,
    FolderInviteData,
    DatabaseData,
    MachineData,
    ActionData,
    ScreenCursorData,
    QueryCursorData,
    ScriptData,
    ServiceData,
    TimerData,
    TriggerData,
    InterruptionData,
    LogData,
    RunData,
    SpanData,
    RouteData,
    SceneData,
    WindowData,
    MessageData,
    NotificationData,
    ReactionData,
    StarData,
    ThreadData,
    ClientData,
    FriendshipData,
    FriendshipInviteData,
    HandleData,
    OrganizationData,
    OrganizationInviteData,
    OrganizationMembershipData,
    SpaceData,
    SpaceInviteData,
    SpaceMembershipData,
    UserData,
    ColorStyleData,
    BorderStyleData,
    TransitionStyleData,
    EffectStyleData,
    GradientStyleData,
    FillStyleData,
    FontStyleData,
    ShadowStyleData,
    ThemeData,
    CustomViewDefinitionData,
    CustomViewData,
    FrameViewData,
    LabelViewData,
    SplitViewData,
    TextViewData,
    NumberInputViewData,
    SliderInputViewData,
    WizardViewData,
    ThreadViewData,
]
AnyStructData = Union[
    ScopeData,
    RelationReferenceData,
    AttributeReferenceData,
    PropertyReferenceData,
    NodeReferenceData,
    EditData,
    ChangeData,
    ChangeResultData,
    ErrorData,
    StringConstraintData,
    NumberConstraintData,
    CollectionConstraintData,
    NodeConstraintData,
    TypeData,
    ValueData,
    FunctionData,
    ConditionData,
    AggregationData,
    ExpressionData,
    SortData,
    SelectData,
    JoinData,
    QueryData,
    HistogramData,
    QueryResultData,
    QueryResultGroupData,
    QueryUpdateData,
    SelectionData,
    IconData,
    PropertyInfoData,
    TraitInfoData,
    NodeInfoData,
    StructInfoData,
    EnumInfoData,
    EnumOptionInfoData,
    TextSpanData,
    TextLineData,
    TextData,
    VariableData,
    CellInfoData,
    DatabaseInfoData,
    ScheduleData,
    OriginData,
    ColorData,
    LengthData,
    PositionData,
    DimensionData,
    InsetsData,
    CornersData,
    Axis2Data,
    Axis3Data,
    Vector2Data,
    Vector3Data,
    Vector4Data,
    Vector2IData,
    Vector3IData,
    Vector4IData,
    GridData,
    GridSpanData,
    BorderData,
    TransitionData,
    EffectData,
    GradientStopData,
    GradientData,
    FillData,
    FontData,
    ShadowData,
]
AnyObjectData = AnyNodeData | AnyStructData
