/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, jsonInteger } from "../../../protocol/serde.js";

/** One native code alignment in bytes. */
export type Alignment = number;

export const Alignment = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: Alignment): void {
        encodeAlignment(writer, value);
    },

    /** Decode one Alignment. */
    decode(reader: BinaryReader): Alignment {
        return decodeAlignment(reader);
    },

    /** Return this value as JSON. */
    toJson(value: Alignment): Json {
        return toJsonAlignment(value);
    },

    /** Return one Alignment from one JSON value. */
    fromJson(value: Json): Alignment {
        return fromJsonAlignment(value);
    },
};

/** Encode one Alignment. */
export function encodeAlignment(writer: BinaryWriter, value: Alignment): void {
    writer.writeUnsigned(value);
}

/** Decode one Alignment. */
export function decodeAlignment(reader: BinaryReader): Alignment {
    return reader.readNumber();
}

/** Return one JSON value for one Alignment. */
export function toJsonAlignment(value: Alignment): Json {
    return value;
}

/** Return one Alignment from one JSON value. */
export function fromJsonAlignment(value: Json): Alignment {
    return jsonInteger(value);
}
