/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, jsonField, jsonObject } from "../../../../protocol/serde.js";
import type { ClockOptions } from "./clock.js";
import type { ExecutionMode } from "./execution.js";
import type { ReplayPayloadMode } from "./execution.js";
import type { RandomOptions } from "./random.js";
import { decodeClockOptions, encodeClockOptions, fromJsonClockOptions, toJsonClockOptions } from "./clock.js";
import { decodeExecutionMode, encodeExecutionMode, fromJsonExecutionMode, toJsonExecutionMode } from "./execution.js";
import { decodeReplayPayloadMode, encodeReplayPayloadMode, fromJsonReplayPayloadMode, toJsonReplayPayloadMode } from "./execution.js";
import { decodeRandomOptions, encodeRandomOptions, fromJsonRandomOptions, toJsonRandomOptions } from "./random.js";

/** World configuration. */
export type WorldOptions = {
    /** Execution mode for scheduling and effect handling. */
    readonly mode: ExecutionMode;
    /** World clock seed configuration. */
    readonly clock: ClockOptions;
    /** World randomness source configuration. */
    readonly random: RandomOptions;
    /** Recorded binding call payload selection. */
    readonly replayPayload: ReplayPayloadMode;
};

export const WorldOptions = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: WorldOptions): void {
        encodeWorldOptions(writer, value);
    },

    /** Decode one WorldOptions. */
    decode(reader: BinaryReader): WorldOptions {
        return decodeWorldOptions(reader);
    },

    /** Return this value as JSON. */
    toJson(value: WorldOptions): Json {
        return toJsonWorldOptions(value);
    },

    /** Return one WorldOptions from one JSON value. */
    fromJson(value: Json): WorldOptions {
        return fromJsonWorldOptions(value);
    },
};

/** Encode one WorldOptions. */
export function encodeWorldOptions(writer: BinaryWriter, value: WorldOptions): void {
    encodeExecutionMode(writer, value.mode);
    encodeClockOptions(writer, value.clock);
    encodeRandomOptions(writer, value.random);
    encodeReplayPayloadMode(writer, value.replayPayload);
}

/** Decode one WorldOptions. */
export function decodeWorldOptions(reader: BinaryReader): WorldOptions {
    const mode = decodeExecutionMode(reader);
    const clock = decodeClockOptions(reader);
    const random = decodeRandomOptions(reader);
    const replayPayload = decodeReplayPayloadMode(reader);

    return {
        mode,
        clock,
        random,
        replayPayload,
    };
}

/** Return one JSON value for one WorldOptions. */
export function toJsonWorldOptions(value: WorldOptions): Json {
    return {
        mode: toJsonExecutionMode(value.mode),
        clock: toJsonClockOptions(value.clock),
        random: toJsonRandomOptions(value.random),
        replayPayload: toJsonReplayPayloadMode(value.replayPayload),
    };
}

/** Return one WorldOptions from one JSON value. */
export function fromJsonWorldOptions(value: Json): WorldOptions {
    const object = jsonObject(value);

    return {
        mode: fromJsonExecutionMode(jsonField(object, "mode")),
        clock: fromJsonClockOptions(jsonField(object, "clock")),
        random: fromJsonRandomOptions(jsonField(object, "random")),
        replayPayload: fromJsonReplayPayloadMode(jsonField(object, "replayPayload")),
    };
}
