[package]
name = "destack_uuid-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
destack_uuid = { path = ".." }
arbitrary = { workspace = true }
libfuzzer-sys = { workspace = true }

[[bin]]
name = "destack_uuid_uuid"
path = "fuzz_targets/uuid.rs"
test = false
doc = false

[profile.release]
panic = "abort"


