[package]
name = "dyst_resolver"
description = "Dyst Resolver"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
dyst_ast = { workspace = true }
dyst_dir = { workspace = true }
dyst_source = { workspace = true }
dyst_parser = { workspace = true }
dyst_unicode = { workspace = true }

cfg-if = { workspace = true }
rustix = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
serde = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
papaya = { workspace = true }
url = { workspace = true }

# nocheckin: vendor/remove resolver dependencies
thiserror = "2.0.17"
rustc-hash = "2.1.1"

[dev-dependencies]
vfs = "0.12.2"

[lints]
workspace = true
