[package]
name = "destack_resolver"
description = "Destack Resolver"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_ast = { workspace = true }
destack_dir = { workspace = true }
destack_parser = { workspace = true }
destack_source = { workspace = true }
destack_unicode = { workspace = true }
destack_workspace = { workspace = true }

# general
cfg-if = { workspace = true }
crossbeam-deque = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
papaya = { workspace = true }
rustc-hash = { workspace = true }
rustix = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
fancy-regex = "0.16.2"

[lints]
workspace = true
