// generated by generate-bindings: do not edit

#![allow(dead_code)]
#![allow(unreachable_pub)]

use crate::diagnostic::RuntimeResult;
use crate::platform::VmValueCodec;
use crate::platform::abi::{BindingAbi, NativeAbi, VmAbi};
use destack_vm as vm;
use serde::{Deserialize, Serialize};

/// ABI newtype for RandomStream.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct RandomStream(
    /// Inner value.
    pub u64,
);

pub type RandomStreamVm = RandomStream;

impl VmValueCodec for RandomStream {
    fn decode(value: vm::Value) -> RuntimeResult<Self> {
        Ok(Self(<u64 as VmValueCodec>::decode(value)?))
    }

    fn encode(self) -> vm::Value {
        <u64 as VmValueCodec>::encode(self.0)
    }
}

/// ABI enum for RandomStreamDomain.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum RandomStreamDomain {
    /// Process.
    Process = 1,
    /// Task.
    Task = 2,
}

impl VmValueCodec for RandomStreamDomain {
    fn decode(value: vm::Value) -> RuntimeResult<Self> {
        let raw = <u8 as VmValueCodec>::decode(value)?;
        Ok(unsafe { std::mem::transmute::<u8, RandomStreamDomain>(raw) })
    }

    fn encode(self) -> vm::Value {
        <u8 as VmValueCodec>::encode(self as u8)
    }
}

/// ABI enum for SecureRandomSource.
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SecureRandomSource {
    /// Kernel.
    Kernel = 1,
    /// SystemCryptoProvider.
    SystemCryptoProvider = 2,
    /// Hardware.
    Hardware = 3,
    /// Virtualized.
    Virtualized = 4,
    /// Unknown.
    Unknown = 5,
}

impl VmValueCodec for SecureRandomSource {
    fn decode(value: vm::Value) -> RuntimeResult<Self> {
        let raw = <u8 as VmValueCodec>::decode(value)?;
        Ok(unsafe { std::mem::transmute::<u8, SecureRandomSource>(raw) })
    }

    fn encode(self) -> vm::Value {
        <u8 as VmValueCodec>::encode(self as u8)
    }
}

/// ABI struct for RandomStreamState.
#[repr(C)]
pub struct RandomStreamStateAbi<A: BindingAbi> {
    /// The version field.
    pub version: u32,
    /// The bytes field.
    pub bytes: A::Array<u8>,
}

pub type RandomStreamState = RandomStreamStateAbi<NativeAbi>;
pub type RandomStreamStateVm = RandomStreamStateAbi<VmAbi>;

impl<A: BindingAbi> std::fmt::Debug for RandomStreamStateAbi<A> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("RandomStreamStateAbi")
            .finish_non_exhaustive()
    }
}

impl Copy for RandomStreamStateAbi<NativeAbi> {}
impl Clone for RandomStreamStateAbi<NativeAbi> {
    fn clone(&self) -> Self {
        *self
    }
}
impl Copy for RandomStreamStateAbi<VmAbi> {}
impl Clone for RandomStreamStateAbi<VmAbi> {
    fn clone(&self) -> Self {
        *self
    }
}

/// ABI struct for SecureRandomInfo.
#[repr(C)]
pub struct SecureRandomInfoAbi<A: BindingAbi> {
    /// The source field.
    pub source: SecureRandomSource,
    /// The backend_name field.
    pub backend_name: A::String,
    /// The may_block field.
    pub may_block: bool,
    /// The is_cryptographic field.
    pub is_cryptographic: bool,
    /// The is_seeded field.
    pub is_seeded: bool,
    /// The is_fips_approved field.
    pub is_fips_approved: bool,
    /// The entropy_bits_per_byte field.
    pub entropy_bits_per_byte: f64,
}

pub type SecureRandomInfo = SecureRandomInfoAbi<NativeAbi>;
pub type SecureRandomInfoVm = SecureRandomInfoAbi<VmAbi>;

impl<A: BindingAbi> std::fmt::Debug for SecureRandomInfoAbi<A> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("SecureRandomInfoAbi")
            .finish_non_exhaustive()
    }
}

impl Copy for SecureRandomInfoAbi<NativeAbi> {}
impl Clone for SecureRandomInfoAbi<NativeAbi> {
    fn clone(&self) -> Self {
        *self
    }
}
impl Copy for SecureRandomInfoAbi<VmAbi> {}
impl Clone for SecureRandomInfoAbi<VmAbi> {
    fn clone(&self) -> Self {
        *self
    }
}

/// Replay struct for RandomStreamState.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RandomStreamStateReplay {
    /// The version field.
    pub version: u32,
    /// The bytes field.
    pub bytes: Vec<u8>,
}

/// Replay struct for SecureRandomInfo.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SecureRandomInfoReplay {
    /// The source field.
    pub source: SecureRandomSource,
    /// The backend_name field.
    pub backend_name: String,
    /// The may_block field.
    pub may_block: bool,
    /// The is_cryptographic field.
    pub is_cryptographic: bool,
    /// The is_seeded field.
    pub is_seeded: bool,
    /// The is_fips_approved field.
    pub is_fips_approved: bool,
    /// The entropy_bits_per_byte field.
    pub entropy_bits_per_byte: f64,
}
