[workspace]
# fuzzer is in its own workspace

[package]
name = "tspp_formatter_fuzz"
description = "TS++ Formatter Fuzzing"
edition = "2024"
authors = ["Symbol Industries"]
license = "proprietary"
rust-version = "1.88.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
tspp_formatter = { path = ".." }
tspp_source = { path = "../../source" }
tspp_repository = { path = "../../repository" }

libfuzzer-sys = "0.4.10"

[[bin]]
name = "formatter"
path = "fuzz_targets/formatter.rs"
test = false
doc = false
bench = false
