[workspace]
# fuzzer is in its own workspace

[package]
name = "destack_formatter_fuzz"
description = "Destack Formatter Fuzzing"
edition = "2024"
authors = ["Symbol Industries"]
license = "proprietary"
rust-version = "1.88.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
destack_dir = { path = "../../dir" }
destack_fir = { path = "../../fir" }
destack_formatter = { path = ".." }
destack_parser = { path = "../../parser" }
destack_source = { path = "../../source" }

arbitrary = { version = "1.4.2", features = ["derive"] }
libfuzzer-sys = "0.4.10"

[[bin]]
name = "formatter"
path = "fuzz_targets/formatter.rs"
test = false
doc = false
bench = false
