/* eslint-disable */
import { groupByList } from '@/utils/functools';
// @generated by protobuf-ts 2.11.0
// @generated from protobuf file "destack-proto/common.proto" (package "symbol.destack", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ClientTypeProto } from "./language";
/**
 * Core metadata for all RPC requests.
 * This is passed as specially encoded headers with robust dicts,
 * but it's nice to have a common definition.
 * NOTE: keep :RpcMetadataEncoding references in sync with RpcMetadata
 * NOTE :Monitoring: add request id to RPC metadata?
 *
 * @generated from protobuf message symbol.destack.RpcMetadata
 */
export interface RpcMetadata {
    /**
     * Client
     *
     * @generated from protobuf field: optional symbol.destack.ClientTypeProto client_type = 2
     */
    clientType?: ClientTypeProto;
    /**
     * @generated from protobuf field: optional string client_id = 3
     */
    clientId?: string;
    /**
     * @generated from protobuf field: optional string client_nonce = 4
     */
    clientNonce?: string;
    /**
     * @generated from protobuf field: optional string client_access_token = 5
     */
    clientAccessToken?: string;
}
/**
 * @generated from protobuf enum symbol.destack.ServiceKind
 */
export enum ServiceKind {
    /**
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: INTERNAL = 1;
     */
    INTERNAL = 1,
    /**
     * @generated from protobuf enum value: PUBLIC = 2;
     */
    PUBLIC = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class RpcMetadata$Type extends MessageType<RpcMetadata> {
    constructor() {
        super("symbol.destack.RpcMetadata", [
            { no: 2, name: "client_type", kind: "enum", opt: true, T: () => ["symbol.destack.ClientTypeProto", ClientTypeProto] },
            { no: 3, name: "client_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "client_nonce", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "client_access_token", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RpcMetadata>): RpcMetadata {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RpcMetadata>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RpcMetadata): RpcMetadata {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional symbol.destack.ClientTypeProto client_type */ 2:
                    message.clientType = reader.int32();
                    break;
                case /* optional string client_id */ 3:
                    message.clientId = reader.string();
                    break;
                case /* optional string client_nonce */ 4:
                    message.clientNonce = reader.string();
                    break;
                case /* optional string client_access_token */ 5:
                    message.clientAccessToken = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RpcMetadata, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional symbol.destack.ClientTypeProto client_type = 2; */
        if (message.clientType !== undefined)
            writer.tag(2, WireType.Varint).int32(message.clientType);
        /* optional string client_id = 3; */
        if (message.clientId !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.clientId);
        /* optional string client_nonce = 4; */
        if (message.clientNonce !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.clientNonce);
        /* optional string client_access_token = 5; */
        if (message.clientAccessToken !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.clientAccessToken);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message symbol.destack.RpcMetadata
 */
export const RpcMetadata = new RpcMetadata$Type();
