[package]
name = "destack_test"
description = "Destack Test"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "update_conformance_catalog"
path = "src/conformance/bin/update_catalog.rs"

[[bin]]
name = "print_conformance_translation_diffs"
path = "src/conformance/bin/translation_diff.rs"

[[bin]]
name = "refresh_conformance_translation_metadata"
path = "src/conformance/bin/refresh_translation_metadata.rs"

[[bin]]
name = "update_conformance_schema"
path = "src/conformance/bin/update_schema.rs"

[[test]]
name = "formatter"
path = "src/formatter/main.rs"
harness = false

[[test]]
name = "conformance-formatter"
path = "src/conformance/formatter/main.rs"
harness = false

[[test]]
name = "specification"
path = "src/specification/main.rs"
harness = false

[[test]]
name = "query"
path = "src/query/main.rs"
harness = false

[[test]]
name = "conformance-ecma"
path = "src/conformance/bin/ecma.rs"
harness = false

[[test]]
name = "stress"
path = "src/stress/main.rs"
harness = false

[dependencies]
# language
destack_artifact = { workspace = true }
destack_codegen_js = { workspace = true }
destack_codegen_lib = { workspace = true }
destack_compiler = { workspace = true }
destack_core = { workspace = true }
destack_dir = { workspace = true }
destack_fir = { workspace = true }
destack_formatter = { workspace = true }
destack_heap = { workspace = true }
destack_linter = { workspace = true }
destack_mir = { workspace = true }
destack_parser = { workspace = true }
destack_query = { workspace = true }
destack_repository = { workspace = true }
destack_runtime = { workspace = true }
destack_session = { workspace = true }
destack_source = { workspace = true }
destack_vm = { workspace = true }

# general
clap = { workspace = true, features = ["derive"] }
pulldown-cmark = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
schemars = { workspace = true }
indexmap = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "time"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
