[package]
name = "destack_test"
description = "Destack Test"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
destack_codegen_lib = { workspace = true }
destack_compiler = { workspace = true }
destack_dir = { workspace = true }
destack_machine = { workspace = true }
destack_mir = { workspace = true }
destack_runtime = { workspace = true }
destack_source = { workspace = true }
destack_workspace = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
