[package]
name = "destack_test"
description = "Destack Test"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[[test]]
name = "smoke"
path = "src/smoke/main.rs"
harness = false

[[test]]
name = "codegen"
path = "src/codegen/main.rs"
harness = false

[[test]]
name = "formatter"
path = "src/formatter/main.rs"
harness = false

[[test]]
name = "mdtest"
path = "src/mdtest/main.rs"
harness = false

[[test]]
name = "conformance"
path = "src/conformance/main.rs"
harness = false

[[test]]
name = "ecosystem"
path = "src/ecosystem/main.rs"
harness = false

[dependencies]
# language
destack_ast = { workspace = true }
destack_codegen_js = { workspace = true }
destack_codegen_lib = { workspace = true }
destack_compiler = { workspace = true }
destack_dir = { workspace = true }
destack_fir = { workspace = true }
destack_formatter = { workspace = true }
destack_machine = { workspace = true }
destack_mir = { workspace = true }
destack_parser = { workspace = true }
destack_runtime = { workspace = true }
destack_source = { workspace = true }
destack_workspace = { workspace = true }

# general
clap = { version = "4.5", features = ["derive"] }
pulldown-cmark = "0.12"
rayon = "1.10"
serde = { version = "1", features = ["derive"] }
toml = "0.8"

[dev-dependencies]

[lints]
workspace = true
