from uuid import UUID

import pytest

from bench.language import NodeReference
from bench.language.const import EnumType, NodeType, PrimitiveType, StructType
from bench.language.field import TypeInfo, TypeKind, decode_type_identity, encode_type_identity
from bench.language.node import get_tk_from_ptr_maybe

# the targets were generated by manually running and verifying encode_type_identity
TEST_TYPE_IDENTITIES: tuple[tuple[TypeInfo, str], ...] = (
    (TypeInfo(kind=TypeKind.PRIMITIVE, primitive_type=PrimitiveType.DATETIME), "pe"),
    (TypeInfo(kind=TypeKind.NODE, bench_type=NodeType.USER, is_list=True), "NdD"),
    (TypeInfo(kind=TypeKind.STRUCT, bench_type=StructType.TEXT), "sIS"),
    (TypeInfo(kind=TypeKind.ENUM, bench_type=EnumType.OBJECT_TYPE, is_secret=True), "!eUf"),
    (
        TypeInfo(
            kind=TypeKind.BASED_NODE,
            bench_type=NodeType.FIELD,
            base_type_ptr=NodeReference(
                type=NodeType.BLOCK, ck=UUID("12345678-ffff-0000-0000-000000000000")
            ),
            is_secret=True,
            is_list=True,
        ),
        "!BEjRWeP//AAA=g",
    ),
    (
        TypeInfo(
            kind=TypeKind.OBJECT,
            base_type_ptr=NodeReference(
                type=NodeType.BLOCK, ck=UUID("12345678-ffff-0000-0000-000000000000")
            ),
        ),
        "oEjRWeP//AAA=",
    ),
)


@pytest.mark.parametrize("target", TEST_TYPE_IDENTITIES)
def test_roundtrip_type_identity(target: tuple[TypeInfo, str]):
    type_info, target_key = target
    identity_key = encode_type_identity(type_info)
    assert identity_key and identity_key == target_key
    decoded = decode_type_identity(identity_key)
    assert decoded.primitive_type == type_info.primitive_type
    assert decoded.bench_type == type_info.bench_type
    assert get_tk_from_ptr_maybe(decoded.base_type_ptr) == get_tk_from_ptr_maybe(
        type_info.base_type_ptr
    )
    assert decoded.is_list == type_info.is_list
    assert decoded.is_secret == type_info.is_secret
