pub mod bench;
pub mod build;
pub mod check;
pub mod clean;
pub mod completions;
pub mod config;
pub mod doc;
pub mod doctor;
pub mod explain;
pub mod fmt;
pub mod info;
pub mod init;
pub mod lint;
pub mod lsp;
pub mod run;
pub mod targets;
pub mod task;
pub mod test;
pub mod version;

pub use bench::BenchArgs;
pub use build::BuildArgs;
pub use check::CheckArgs;
pub use clean::CleanArgs;
pub use completions::CompletionsArgs;
pub use config::ConfigArgs;
pub use doc::DocArgs;
pub use doctor::DoctorArgs;
pub use explain::ExplainArgs;
pub use fmt::FmtArgs;
pub use info::InfoArgs;
pub use init::InitArgs;
pub use lint::LintArgs;
pub use lsp::LspArgs;
pub use run::RunArgs;
pub use targets::TargetsArgs;
pub use task::TaskArgs;
pub use test::TestArgs;
pub use version::VersionArgs;

#[cfg(feature = "dev")]
pub mod dev;
#[cfg(feature = "dev")]
pub use dev::DevCommand;
