// generated by generate-bindings: do not edit

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unreachable_pub)]

use crate::platform::{resource, resource as platform_resource, tty as platform_tty};
use serde::{Deserialize, Serialize};

/// ABI struct for PtyPair.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct PtyPair {
    /// The controller field.
    pub controller: resource::PtyHandle,
    /// The worker field.
    pub worker: resource::TtyHandle,
}

pub type PtyPairVm = PtyPair;

/// ABI struct for TtyMode.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct TtyMode {
    /// The input_flags field.
    pub input_flags: u64,
    /// The output_flags field.
    pub output_flags: u64,
    /// The control_flags field.
    pub control_flags: u64,
    /// The local_flags field.
    pub local_flags: u64,
}

pub type TtyModeVm = TtyMode;

/// ABI struct for TtySize.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct TtySize {
    /// The rows field.
    pub rows: u32,
    /// The columns field.
    pub columns: u32,
    /// The x_pixels field.
    pub x_pixels: u32,
    /// The y_pixels field.
    pub y_pixels: u32,
}

pub type TtySizeVm = TtySize;
