[package]
name = "tspp_source"
description = "TS++ Span"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[features]
default = []
schema = ["schemars"]

[dependencies]
# language
tspp_core = { workspace = true }
tspp_serde = { workspace = true }
tspp_unicode = { workspace = true }

# general
cfg-if = { workspace = true }
dashmap = { workspace = true }
indexmap = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
schemars = { workspace = true, optional = true }
simdutf8 = { workspace = true }
smallvec = { workspace = true }
rustc-hash = { workspace = true }

[dev-dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
crossbeam-channel = { workspace = true }
notify = { workspace = true }
rustix = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }

[lints]
workspace = true
