[package]
name = "dyst_source"
description = "Dyst Span"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]

parking_lot = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
