[package]
name = "destack_source"
description = "Destack Span"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_core = { workspace = true }

# general
cfg-if = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
indexmap = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }
simdutf8 = { workspace = true }
smallvec = { workspace = true }
rustc-hash = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
notify = { workspace = true }
rustix = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }

[lints]
workspace = true
