[package]
name = "tspp_mir"
description = "TS++ Machine IR"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
tspp_core = { workspace = true }
tspp_fir = { workspace = true }
tspp_serde = { workspace = true }
tspp_source = { workspace = true }
tspp_unicode = { workspace = true }

# general
indexmap = { workspace = true, features = ["serde"] }
parking_lot = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
smallvec = { workspace = true, features = ["serde"] }

[dev-dependencies]

[lints]
workspace = true
