[package]
name = "destack_mir"
description = "Destack Machine IR"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_core = { workspace = true }
destack_fir = { workspace = true }
destack_source = { workspace = true }
destack_unicode = { workspace = true }

# general
indexmap = { workspace = true }
serde = { workspace = true, features = ["derive"] }
smallvec = { workspace = true, features = ["serde"] }

[dev-dependencies]

[lints]
workspace = true
