[package]
name = "destack_cli"
description = "Destack CLI"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
default-run = "destack_cli"

[lib]
path = "rust/lib.rs"

[[bin]]
name = "destack_cli"
path = "rust/main.rs"

[dependencies]
dyst_ast = { workspace = true }
dyst_compiler = { workspace = true }
dyst_dir = { workspace = true }
dyst_fir = { workspace = true }
dyst_formatter = { workspace = true }
dyst_javascript_ast = { workspace = true }
dyst_javascript_transpiler = { workspace = true }
dyst_javascript_machine = { workspace = true, optional = true }
dyst_parser = { workspace = true }
dyst_source = { workspace = true }

destack_file = { workspace = true }
destack_terminal = { workspace = true }

tokio = { version = "1.47.1" }

[dev-dependencies]

[lints]
workspace = true
