[package]
name = "destack_bridge_core"
description = "Shared core for Destack bridge clients"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
readme = "README.md"
repository = "https://github.com/destack-sh/destack"
homepage = "https://github.com/destack-sh/destack"

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
destack_compiler.workspace = true
destack_linter.workspace = true
destack_query.workspace = true
destack_session.workspace = true
destack_source.workspace = true
destack_workspace.workspace = true

[lints]
workspace = true
