/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, SerdeError, jsonString } from "../../../protocol/serde.js";

/** Binary arithmetic/logic operator. */
export type BinaryOperator = "add" | "subtract" | "multiply" | "signedDivide" | "unsignedDivide" | "signedRemainder" | "unsignedRemainder" | "floatAdd" | "floatSubtract" | "floatMultiply" | "floatDivide" | "and" | "or" | "xor" | "shiftLeft" | "arithmeticShiftRight" | "logicalShiftRight" | "equal" | "notEqual" | "signedLessThan" | "signedLessEqual" | "signedGreaterThan" | "signedGreaterEqual" | "unsignedLessThan" | "unsignedLessEqual" | "unsignedGreaterThan" | "unsignedGreaterEqual" | "floatEqual" | "floatNotEqual" | "floatLessThan" | "floatLessEqual" | "floatGreaterThan" | "floatGreaterEqual";

export const BinaryOperator = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: BinaryOperator): void {
        encodeBinaryOperator(writer, value);
    },

    /** Decode one BinaryOperator. */
    decode(reader: BinaryReader): BinaryOperator {
        return decodeBinaryOperator(reader);
    },

    /** Return this value as JSON. */
    toJson(value: BinaryOperator): Json {
        return toJsonBinaryOperator(value);
    },

    /** Return one BinaryOperator from one JSON value. */
    fromJson(value: Json): BinaryOperator {
        return fromJsonBinaryOperator(value);
    },
};

/** Encode one BinaryOperator. */
export function encodeBinaryOperator(writer: BinaryWriter, value: BinaryOperator): void {
    switch (value) {
        case "add":
            writer.writeUnsigned(0);
            return;
        case "subtract":
            writer.writeUnsigned(1);
            return;
        case "multiply":
            writer.writeUnsigned(2);
            return;
        case "signedDivide":
            writer.writeUnsigned(3);
            return;
        case "unsignedDivide":
            writer.writeUnsigned(4);
            return;
        case "signedRemainder":
            writer.writeUnsigned(5);
            return;
        case "unsignedRemainder":
            writer.writeUnsigned(6);
            return;
        case "floatAdd":
            writer.writeUnsigned(7);
            return;
        case "floatSubtract":
            writer.writeUnsigned(8);
            return;
        case "floatMultiply":
            writer.writeUnsigned(9);
            return;
        case "floatDivide":
            writer.writeUnsigned(10);
            return;
        case "and":
            writer.writeUnsigned(11);
            return;
        case "or":
            writer.writeUnsigned(12);
            return;
        case "xor":
            writer.writeUnsigned(13);
            return;
        case "shiftLeft":
            writer.writeUnsigned(14);
            return;
        case "arithmeticShiftRight":
            writer.writeUnsigned(15);
            return;
        case "logicalShiftRight":
            writer.writeUnsigned(16);
            return;
        case "equal":
            writer.writeUnsigned(17);
            return;
        case "notEqual":
            writer.writeUnsigned(18);
            return;
        case "signedLessThan":
            writer.writeUnsigned(19);
            return;
        case "signedLessEqual":
            writer.writeUnsigned(20);
            return;
        case "signedGreaterThan":
            writer.writeUnsigned(21);
            return;
        case "signedGreaterEqual":
            writer.writeUnsigned(22);
            return;
        case "unsignedLessThan":
            writer.writeUnsigned(23);
            return;
        case "unsignedLessEqual":
            writer.writeUnsigned(24);
            return;
        case "unsignedGreaterThan":
            writer.writeUnsigned(25);
            return;
        case "unsignedGreaterEqual":
            writer.writeUnsigned(26);
            return;
        case "floatEqual":
            writer.writeUnsigned(27);
            return;
        case "floatNotEqual":
            writer.writeUnsigned(28);
            return;
        case "floatLessThan":
            writer.writeUnsigned(29);
            return;
        case "floatLessEqual":
            writer.writeUnsigned(30);
            return;
        case "floatGreaterThan":
            writer.writeUnsigned(31);
            return;
        case "floatGreaterEqual":
            writer.writeUnsigned(32);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one BinaryOperator. */
export function decodeBinaryOperator(reader: BinaryReader): BinaryOperator {
    const variant = reader.readNumber();

    switch (variant) {
        case 0:
            return "add";
        case 1:
            return "subtract";
        case 2:
            return "multiply";
        case 3:
            return "signedDivide";
        case 4:
            return "unsignedDivide";
        case 5:
            return "signedRemainder";
        case 6:
            return "unsignedRemainder";
        case 7:
            return "floatAdd";
        case 8:
            return "floatSubtract";
        case 9:
            return "floatMultiply";
        case 10:
            return "floatDivide";
        case 11:
            return "and";
        case 12:
            return "or";
        case 13:
            return "xor";
        case 14:
            return "shiftLeft";
        case 15:
            return "arithmeticShiftRight";
        case 16:
            return "logicalShiftRight";
        case 17:
            return "equal";
        case 18:
            return "notEqual";
        case 19:
            return "signedLessThan";
        case 20:
            return "signedLessEqual";
        case 21:
            return "signedGreaterThan";
        case 22:
            return "signedGreaterEqual";
        case 23:
            return "unsignedLessThan";
        case 24:
            return "unsignedLessEqual";
        case 25:
            return "unsignedGreaterThan";
        case 26:
            return "unsignedGreaterEqual";
        case 27:
            return "floatEqual";
        case 28:
            return "floatNotEqual";
        case 29:
            return "floatLessThan";
        case 30:
            return "floatLessEqual";
        case 31:
            return "floatGreaterThan";
        case 32:
            return "floatGreaterEqual";
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one BinaryOperator. */
export function toJsonBinaryOperator(value: BinaryOperator): Json {
    return value;
}

/** Return one BinaryOperator from one JSON value. */
export function fromJsonBinaryOperator(value: Json): BinaryOperator {
    const variant = jsonString(value);

    switch (variant) {
        case "add":
            return "add";
        case "subtract":
            return "subtract";
        case "multiply":
            return "multiply";
        case "signedDivide":
            return "signedDivide";
        case "unsignedDivide":
            return "unsignedDivide";
        case "signedRemainder":
            return "signedRemainder";
        case "unsignedRemainder":
            return "unsignedRemainder";
        case "floatAdd":
            return "floatAdd";
        case "floatSubtract":
            return "floatSubtract";
        case "floatMultiply":
            return "floatMultiply";
        case "floatDivide":
            return "floatDivide";
        case "and":
            return "and";
        case "or":
            return "or";
        case "xor":
            return "xor";
        case "shiftLeft":
            return "shiftLeft";
        case "arithmeticShiftRight":
            return "arithmeticShiftRight";
        case "logicalShiftRight":
            return "logicalShiftRight";
        case "equal":
            return "equal";
        case "notEqual":
            return "notEqual";
        case "signedLessThan":
            return "signedLessThan";
        case "signedLessEqual":
            return "signedLessEqual";
        case "signedGreaterThan":
            return "signedGreaterThan";
        case "signedGreaterEqual":
            return "signedGreaterEqual";
        case "unsignedLessThan":
            return "unsignedLessThan";
        case "unsignedLessEqual":
            return "unsignedLessEqual";
        case "unsignedGreaterThan":
            return "unsignedGreaterThan";
        case "unsignedGreaterEqual":
            return "unsignedGreaterEqual";
        case "floatEqual":
            return "floatEqual";
        case "floatNotEqual":
            return "floatNotEqual";
        case "floatLessThan":
            return "floatLessThan";
        case "floatLessEqual":
            return "floatLessEqual";
        case "floatGreaterThan":
            return "floatGreaterThan";
        case "floatGreaterEqual":
            return "floatGreaterEqual";
    }

    throw new SerdeError(`unknown enum variant: ${variant}`);
}

/** Unary operator. */
export type UnaryOperator = "negate" | "floatNegate" | "not";

export const UnaryOperator = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: UnaryOperator): void {
        encodeUnaryOperator(writer, value);
    },

    /** Decode one UnaryOperator. */
    decode(reader: BinaryReader): UnaryOperator {
        return decodeUnaryOperator(reader);
    },

    /** Return this value as JSON. */
    toJson(value: UnaryOperator): Json {
        return toJsonUnaryOperator(value);
    },

    /** Return one UnaryOperator from one JSON value. */
    fromJson(value: Json): UnaryOperator {
        return fromJsonUnaryOperator(value);
    },
};

/** Encode one UnaryOperator. */
export function encodeUnaryOperator(writer: BinaryWriter, value: UnaryOperator): void {
    switch (value) {
        case "negate":
            writer.writeUnsigned(0);
            return;
        case "floatNegate":
            writer.writeUnsigned(1);
            return;
        case "not":
            writer.writeUnsigned(2);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one UnaryOperator. */
export function decodeUnaryOperator(reader: BinaryReader): UnaryOperator {
    const variant = reader.readNumber();

    switch (variant) {
        case 0:
            return "negate";
        case 1:
            return "floatNegate";
        case 2:
            return "not";
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one UnaryOperator. */
export function toJsonUnaryOperator(value: UnaryOperator): Json {
    return value;
}

/** Return one UnaryOperator from one JSON value. */
export function fromJsonUnaryOperator(value: Json): UnaryOperator {
    const variant = jsonString(value);

    switch (variant) {
        case "negate":
            return "negate";
        case "floatNegate":
            return "floatNegate";
        case "not":
            return "not";
    }

    throw new SerdeError(`unknown enum variant: ${variant}`);
}
