FROM python:3.13-slim

LABEL org.opencontainers.image.source=https://github.com/symbolx/destack
LABEL org.opencontainers.image.description="Destack"

#
# OS
#

# install libs
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzbar-dev \
    postgresql-client \
    ffmpeg \
    gcc \
    gfortran \
    g++ \
    pkg-config \
    cmake \
    libopenblas-dev \
    liblapack-dev \
    libxml2-dev \
    libxslt-dev \
    git \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# create destack-runtime user
RUN useradd -ms /bin/bash destack-runtime \
    && echo "destack-runtime ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# uv
ADD https://astral.sh/uv/install.sh /uv-installer.sh
RUN sh /uv-installer.sh && mv /root/.local/bin/uv /usr/local/bin/ && rm /uv-installer.sh
ENV PATH="/usr/local/bin:$PATH"

ENV PYTHONUNBUFFERED=1

# install requirements
COPY destack/requirements/runtime.txt /home/destack-runtime/requirements.txt
WORKDIR /home/destack-runtime
RUN uv pip install --system --no-cache -r requirements.txt

# copy relevant files
COPY --chown=destack-runtime:destack-runtime destack/ /home/destack-runtime/destack/
# prune unnecessary files
RUN rm -rf /home/destack-runtime/destack/system /home/destack-runtime/destack/test
RUN find /home/destack-runtime/destack/ -type f -name 'test_*.py' -delete

COPY --chown=destack-runtime:destack-runtime destack.py /home/destack-runtime/
COPY --chown=destack-runtime:destack-runtime pyproject.toml /home/destack-runtime/
COPY --chown=destack-runtime:destack-runtime version /home/destack-runtime/

# startup script
RUN cat <<'EOF' > /start.sh
#!/bin/sh
su destack-runtime -s /bin/bash -m -c "python3 /home/destack-runtime/destack.py serve runtime 0.0.0.0 5432"
EOF
RUN chmod +x /start.sh

ARG GIT_COMMIT
ARG VERSION
ENV GIT_COMMIT=$GIT_COMMIT
ENV VERSION=$VERSION

EXPOSE 5432
EXPOSE 80

CMD ["/start.sh"] 