/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, jsonField, jsonObject, jsonString } from "../../../protocol/serde.js";

/** Request to read one workspace root revision. */
export type ReadRevisionRequest = {
    /** Root path to read. */
    readonly root: string;
};

export const ReadRevisionRequest = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: ReadRevisionRequest): void {
        encodeReadRevisionRequest(writer, value);
    },

    /** Decode one ReadRevisionRequest. */
    decode(reader: BinaryReader): ReadRevisionRequest {
        return decodeReadRevisionRequest(reader);
    },

    /** Return this value as JSON. */
    toJson(value: ReadRevisionRequest): Json {
        return toJsonReadRevisionRequest(value);
    },

    /** Return one ReadRevisionRequest from one JSON value. */
    fromJson(value: Json): ReadRevisionRequest {
        return fromJsonReadRevisionRequest(value);
    },
};

/** Encode one ReadRevisionRequest. */
export function encodeReadRevisionRequest(writer: BinaryWriter, value: ReadRevisionRequest): void {
    writer.writeString(value.root);
}

/** Decode one ReadRevisionRequest. */
export function decodeReadRevisionRequest(reader: BinaryReader): ReadRevisionRequest {
    const root = reader.readString();

    return {
        root,
    };
}

/** Return one JSON value for one ReadRevisionRequest. */
export function toJsonReadRevisionRequest(value: ReadRevisionRequest): Json {
    return {
        root: value.root,
    };
}

/** Return one ReadRevisionRequest from one JSON value. */
export function fromJsonReadRevisionRequest(value: Json): ReadRevisionRequest {
    const object = jsonObject(value);

    return {
        root: jsonString(jsonField(object, "root")),
    };
}

/** Request to reload one workspace root from its host. */
export type ReloadRequest = {
    /** Root path to reload. */
    readonly root: string;
};

export const ReloadRequest = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: ReloadRequest): void {
        encodeReloadRequest(writer, value);
    },

    /** Decode one ReloadRequest. */
    decode(reader: BinaryReader): ReloadRequest {
        return decodeReloadRequest(reader);
    },

    /** Return this value as JSON. */
    toJson(value: ReloadRequest): Json {
        return toJsonReloadRequest(value);
    },

    /** Return one ReloadRequest from one JSON value. */
    fromJson(value: Json): ReloadRequest {
        return fromJsonReloadRequest(value);
    },
};

/** Encode one ReloadRequest. */
export function encodeReloadRequest(writer: BinaryWriter, value: ReloadRequest): void {
    writer.writeString(value.root);
}

/** Decode one ReloadRequest. */
export function decodeReloadRequest(reader: BinaryReader): ReloadRequest {
    const root = reader.readString();

    return {
        root,
    };
}

/** Return one JSON value for one ReloadRequest. */
export function toJsonReloadRequest(value: ReloadRequest): Json {
    return {
        root: value.root,
    };
}

/** Return one ReloadRequest from one JSON value. */
export function fromJsonReloadRequest(value: Json): ReloadRequest {
    const object = jsonObject(value);

    return {
        root: jsonString(jsonField(object, "root")),
    };
}
