[package]
name = "tspp_runtime"
description = "TS++ Runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[features]
default = ["replay", "audio-backends-default"]
replay = []
audio-backends-default = [
    "audio-wasapi",
    "audio-asio",
    "audio-coreaudio",
    "audio-alsa",
    "audio-pipewire",
    "audio-pulseaudio",
    "audio-jack",
]
audio-wasapi = []
audio-asio = []
audio-coreaudio = []
audio-alsa = []
# linux backends
audio-pipewire = []
audio-pulseaudio = []
audio-jack = []

[dependencies]
# language
tspp_artifact = { workspace = true }
tspp_core = { workspace = true }
tspp_heap = { workspace = true }
tspp_memory = { workspace = true }
tspp_signal = { workspace = true }
tspp_mir = { workspace = true }
tspp_native = { workspace = true }
tspp_program = { workspace = true }
tspp_repository = { workspace = true }
tspp_rpc = { workspace = true }
tspp_serde = { workspace = true }
tspp_source = { workspace = true }
tspp_vm = { workspace = true }

libc = { workspace = true }
parking_lot = { workspace = true }
psm = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }
rustc-hash = { workspace = true }

windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Security_Cryptography",
    "Win32_Networking_WinSock",
    "Win32_System_Performance",
    "Win32_System_Threading",
    "Win32_System_SystemInformation",
    "Win32_System_Time",
] }

[target.'cfg(target_os = "linux")'.dependencies]
io-uring = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
tspp_compiler = { workspace = true, features = ["native"] }

[[bench]]
name = "footprint"
path = "benches/footprint/bench.rs"
harness = false

[lints]
workspace = true
