[package]
name = "destack_signal"
description = "Destack Signal"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[lints]
workspace = true
