[workspace]
# fuzzer is in its own workspace

[package]
name = "destack_parser_fuzz"
description = "Destack Parser Fuzzing"
edition = "2024"
authors = ["Symbol Industries"]
license = "proprietary"
rust-version = "1.88.0"

[package.metadata]
cargo-fuzz = true

[dependencies]
destack_core = { path = "../../core" }
destack_parser = { path = ".." }
destack_source = { path = "../../source" }
destack_test = { path = "../../test" }

arbitrary = { version = "1.4.2", features = ["derive"] }
libfuzzer-sys = "0.4.10"

[[bin]]
name = "lexer"
path = "fuzz_targets/lexer.rs"
test = false
doc = false
bench = false

[[bin]]
name = "parser"
path = "fuzz_targets/parser.rs"
test = false
doc = false
bench = false
