/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, SerdeError, jsonArray, jsonBool, jsonField, jsonObject, jsonOptional, jsonString } from "../../../protocol/serde.js";
import type { Asynchrony } from "./node.js";
import type { LocalNodeId } from "./node.js";
import { decodeAsynchrony, encodeAsynchrony, fromJsonAsynchrony, toJsonAsynchrony } from "./node.js";
import { decodeLocalNodeId, encodeLocalNodeId, fromJsonLocalNodeId, toJsonLocalNodeId } from "./node.js";

/** The signature of a function. */
export type FunctionSignature = {
    /** The asynchrony of the function. */
    readonly asynchrony: Asynchrony;
    /** The role of the function. */
    readonly role?: FunctionRole;
    /** The form of the function. */
    readonly form: FunctionForm;
    /** The generic parameters of the function. */
    readonly genericParameters: ReadonlyArray<LocalNodeId>;
    /** The optional `this` parameter of the function. */
    readonly thisParameter?: LocalNodeId;
    /** The runtime parameters of the function. */
    readonly parameters: ReadonlyArray<LocalNodeId>;
    /** The return type of the function. */
    readonly returnType?: LocalNodeId;
    /** Whether the function is abstract. */
    readonly isAbstract: boolean;
    /** Whether the function is an override. */
    readonly isOverride: boolean;
    /** Whether the function is a generator. */
    readonly isGenerator: boolean;
};

export const FunctionSignature = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: FunctionSignature): void {
        encodeFunctionSignature(writer, value);
    },

    /** Decode one FunctionSignature. */
    decode(reader: BinaryReader): FunctionSignature {
        return decodeFunctionSignature(reader);
    },

    /** Return this value as JSON. */
    toJson(value: FunctionSignature): Json {
        return toJsonFunctionSignature(value);
    },

    /** Return one FunctionSignature from one JSON value. */
    fromJson(value: Json): FunctionSignature {
        return fromJsonFunctionSignature(value);
    },
};

/** Encode one FunctionSignature. */
export function encodeFunctionSignature(writer: BinaryWriter, value: FunctionSignature): void {
    encodeAsynchrony(writer, value.asynchrony);
    writer.writeOption(value.role, (value1) => {
        encodeFunctionRole(writer, value1);
    });
    encodeFunctionForm(writer, value.form);
    writer.writeUnsigned(value.genericParameters.length);
    for (const item3 of value.genericParameters) {
        encodeLocalNodeId(writer, item3);
    }
    writer.writeOption(value.thisParameter, (value4) => {
        encodeLocalNodeId(writer, value4);
    });
    writer.writeUnsigned(value.parameters.length);
    for (const item5 of value.parameters) {
        encodeLocalNodeId(writer, item5);
    }
    writer.writeOption(value.returnType, (value6) => {
        encodeLocalNodeId(writer, value6);
    });
    writer.writeBool(value.isAbstract);
    writer.writeBool(value.isOverride);
    writer.writeBool(value.isGenerator);
}

/** Decode one FunctionSignature. */
export function decodeFunctionSignature(reader: BinaryReader): FunctionSignature {
    const asynchrony = decodeAsynchrony(reader);
    const role = reader.readOption(() => decodeFunctionRole(reader));
    const form = decodeFunctionForm(reader);
    const genericParameters = (() => { const length3 = reader.readNumber(); const items3: Array<LocalNodeId> = []; for (let index = 0; index < length3; index += 1) { items3.push(decodeLocalNodeId(reader)); } return items3; })();
    const thisParameter = reader.readOption(() => decodeLocalNodeId(reader));
    const parameters = (() => { const length5 = reader.readNumber(); const items5: Array<LocalNodeId> = []; for (let index = 0; index < length5; index += 1) { items5.push(decodeLocalNodeId(reader)); } return items5; })();
    const returnType = reader.readOption(() => decodeLocalNodeId(reader));
    const isAbstract = reader.readBool();
    const isOverride = reader.readBool();
    const isGenerator = reader.readBool();

    return {
        asynchrony,
        ...(role === undefined ? {} : { role }),
        form,
        genericParameters,
        ...(thisParameter === undefined ? {} : { thisParameter }),
        parameters,
        ...(returnType === undefined ? {} : { returnType }),
        isAbstract,
        isOverride,
        isGenerator,
    };
}

/** Return one JSON value for one FunctionSignature. */
export function toJsonFunctionSignature(value: FunctionSignature): Json {
    return {
        asynchrony: toJsonAsynchrony(value.asynchrony),
        ...(value.role === undefined ? {} : { role: toJsonFunctionRole(value.role) }),
        form: toJsonFunctionForm(value.form),
        genericParameters: value.genericParameters.map((item0) => toJsonLocalNodeId(item0)),
        ...(value.thisParameter === undefined ? {} : { thisParameter: toJsonLocalNodeId(value.thisParameter) }),
        parameters: value.parameters.map((item0) => toJsonLocalNodeId(item0)),
        ...(value.returnType === undefined ? {} : { returnType: toJsonLocalNodeId(value.returnType) }),
        isAbstract: value.isAbstract,
        isOverride: value.isOverride,
        isGenerator: value.isGenerator,
    };
}

/** Return one FunctionSignature from one JSON value. */
export function fromJsonFunctionSignature(value: Json): FunctionSignature {
    const object = jsonObject(value);

    return {
        asynchrony: fromJsonAsynchrony(jsonField(object, "asynchrony")),
        role: jsonOptional(object, "role", (value) => fromJsonFunctionRole(value)),
        form: fromJsonFunctionForm(jsonField(object, "form")),
        genericParameters: jsonArray(jsonField(object, "genericParameters")).map((item0) => fromJsonLocalNodeId(item0)),
        thisParameter: jsonOptional(object, "thisParameter", (value) => fromJsonLocalNodeId(value)),
        parameters: jsonArray(jsonField(object, "parameters")).map((item0) => fromJsonLocalNodeId(item0)),
        returnType: jsonOptional(object, "returnType", (value) => fromJsonLocalNodeId(value)),
        isAbstract: jsonBool(jsonField(object, "isAbstract")),
        isOverride: jsonBool(jsonField(object, "isOverride")),
        isGenerator: jsonBool(jsonField(object, "isGenerator")),
    };
}

/** The role of a function. */
export type FunctionRole = "getter" | "setter" | "constructor";

export const FunctionRole = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: FunctionRole): void {
        encodeFunctionRole(writer, value);
    },

    /** Decode one FunctionRole. */
    decode(reader: BinaryReader): FunctionRole {
        return decodeFunctionRole(reader);
    },

    /** Return this value as JSON. */
    toJson(value: FunctionRole): Json {
        return toJsonFunctionRole(value);
    },

    /** Return one FunctionRole from one JSON value. */
    fromJson(value: Json): FunctionRole {
        return fromJsonFunctionRole(value);
    },
};

/** Encode one FunctionRole. */
export function encodeFunctionRole(writer: BinaryWriter, value: FunctionRole): void {
    switch (value) {
        case "getter":
            writer.writeUnsigned(0);
            return;
        case "setter":
            writer.writeUnsigned(1);
            return;
        case "constructor":
            writer.writeUnsigned(2);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one FunctionRole. */
export function decodeFunctionRole(reader: BinaryReader): FunctionRole {
    const variant = reader.readNumber();

    switch (variant) {
        case 0:
            return "getter";
        case 1:
            return "setter";
        case 2:
            return "constructor";
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one FunctionRole. */
export function toJsonFunctionRole(value: FunctionRole): Json {
    return value;
}

/** Return one FunctionRole from one JSON value. */
export function fromJsonFunctionRole(value: Json): FunctionRole {
    const variant = jsonString(value);

    switch (variant) {
        case "getter":
            return "getter";
        case "setter":
            return "setter";
        case "constructor":
            return "constructor";
    }

    throw new SerdeError(`unknown enum variant: ${variant}`);
}

/** The style of a function. */
export type FunctionForm = "function" | "lambda";

export const FunctionForm = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: FunctionForm): void {
        encodeFunctionForm(writer, value);
    },

    /** Decode one FunctionForm. */
    decode(reader: BinaryReader): FunctionForm {
        return decodeFunctionForm(reader);
    },

    /** Return this value as JSON. */
    toJson(value: FunctionForm): Json {
        return toJsonFunctionForm(value);
    },

    /** Return one FunctionForm from one JSON value. */
    fromJson(value: Json): FunctionForm {
        return fromJsonFunctionForm(value);
    },
};

/** Encode one FunctionForm. */
export function encodeFunctionForm(writer: BinaryWriter, value: FunctionForm): void {
    switch (value) {
        case "function":
            writer.writeUnsigned(0);
            return;
        case "lambda":
            writer.writeUnsigned(1);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one FunctionForm. */
export function decodeFunctionForm(reader: BinaryReader): FunctionForm {
    const variant = reader.readNumber();

    switch (variant) {
        case 0:
            return "function";
        case 1:
            return "lambda";
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one FunctionForm. */
export function toJsonFunctionForm(value: FunctionForm): Json {
    return value;
}

/** Return one FunctionForm from one JSON value. */
export function fromJsonFunctionForm(value: Json): FunctionForm {
    const variant = jsonString(value);

    switch (variant) {
        case "function":
            return "function";
        case "lambda":
            return "lambda";
    }

    throw new SerdeError(`unknown enum variant: ${variant}`);
}
