syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

enum AggregationOp {
  AGGREGATION_OP_UNSPECIFIED = 0;
  AGGREGATION_OP_COUNT = 1;
  AGGREGATION_OP_SUM = 2;
  AGGREGATION_OP_AVERAGE = 3;
  AGGREGATION_OP_MIN = 4;
  AGGREGATION_OP_MAX = 5;
  AGGREGATION_OP_MEDIAN = 6;
  AGGREGATION_OP_HISTOGRAM = 7;
}

enum BenchType {
  BENCH_TYPE_UNSPECIFIED = 0;
  BENCH_TYPE_MODULE = 1;
  BENCH_TYPE_FILE = 2;
  BENCH_TYPE_STATEMENT = 3;
  BENCH_TYPE_TRIGGER = 4;
  BENCH_TYPE_TAGGING = 5;
  BENCH_TYPE_FIELD = 6;
  BENCH_TYPE_RECORD = 7;
  BENCH_TYPE_VIEW = 8;
  BENCH_TYPE_ISSUE = 9;
  BENCH_TYPE_RESOLVED_FIELD = 10;
  BENCH_TYPE_BLOB = 11;
  BENCH_TYPE_SECRET = 12;
  BENCH_TYPE_SESSION = 13;
  BENCH_TYPE_RUN = 14;
  BENCH_TYPE_EXPRESSION = 101;
  BENCH_TYPE_RUN_CODE_FRAME = 102;
  BENCH_TYPE_RUN_ERROR = 103;
  BENCH_TYPE_LOG_ENTRY = 104;
  BENCH_TYPE_WORKER_SET = 105;
  BENCH_TYPE_ENVIRONMENT = 106;
}

enum BlobStatus {
  BLOB_STATUS_UNSPECIFIED = 0;
  BLOB_STATUS_PREPARED = 1;
  BLOB_STATUS_UPLOADING = 2;
  BLOB_STATUS_AVAILABLE = 3;
}

enum ConditionalOp {
  CONDITIONAL_OP_UNSPECIFIED = 0;
  CONDITIONAL_OP_TRUE = 1;
  CONDITIONAL_OP_FALSE = 2;
  CONDITIONAL_OP_NOT = 3;
  CONDITIONAL_OP_AND = 4;
  CONDITIONAL_OP_OR = 5;
  CONDITIONAL_OP_EQUALS = 6;
  CONDITIONAL_OP_NOT_EQUALS = 7;
  CONDITIONAL_OP_GREATER_THAN = 8;
  CONDITIONAL_OP_GREATER_THAN_OR_EQUALS = 9;
  CONDITIONAL_OP_LESS_THAN = 10;
  CONDITIONAL_OP_LESS_THAN_OR_EQUALS = 11;
  CONDITIONAL_OP_MATCHES = 12;
  CONDITIONAL_OP_STARTS_WITH = 13;
  CONDITIONAL_OP_CONTAINS = 14;
  CONDITIONAL_OP_NOT_CONTAINS = 15;
  CONDITIONAL_OP_IN = 16;
  CONDITIONAL_OP_NOT_IN = 17;
  CONDITIONAL_OP_EXISTS = 18;
  CONDITIONAL_OP_NOT_EXISTS = 19;
  CONDITIONAL_OP_NEAR = 20;
}

enum ExpressionKind {
  EXPRESSION_KIND_UNSPECIFIED = 0;
  EXPRESSION_KIND_CONDITIONAL = 1;
  EXPRESSION_KIND_SORT = 2;
  EXPRESSION_KIND_AGGREGATION = 3;
}

enum ExpressionOp {
  option allow_alias = true;
  EXPRESSION_OP_UNSPECIFIED = 0;
  EXPRESSION_OP_TRUE = 1;
  EXPRESSION_OP_FALSE = 2;
  EXPRESSION_OP_NOT = 3;
  EXPRESSION_OP_AND = 4;
  EXPRESSION_OP_OR = 5;
  EXPRESSION_OP_EQUALS = 6;
  EXPRESSION_OP_NOT_EQUALS = 7;
  EXPRESSION_OP_GREATER_THAN = 8;
  EXPRESSION_OP_GREATER_THAN_OR_EQUALS = 9;
  EXPRESSION_OP_LESS_THAN = 10;
  EXPRESSION_OP_LESS_THAN_OR_EQUALS = 11;
  EXPRESSION_OP_MATCHES = 12;
  EXPRESSION_OP_STARTS_WITH = 13;
  EXPRESSION_OP_CONTAINS = 14;
  EXPRESSION_OP_NOT_CONTAINS = 15;
  EXPRESSION_OP_IN = 16;
  EXPRESSION_OP_NOT_IN = 17;
  EXPRESSION_OP_EXISTS = 18;
  EXPRESSION_OP_NOT_EXISTS = 19;
  EXPRESSION_OP_NEAR = 20;
  EXPRESSION_OP_COUNT = 1;
  EXPRESSION_OP_SUM = 2;
  EXPRESSION_OP_AVERAGE = 3;
  EXPRESSION_OP_MIN = 4;
  EXPRESSION_OP_MAX = 5;
  EXPRESSION_OP_MEDIAN = 6;
  EXPRESSION_OP_HISTOGRAM = 7;
  EXPRESSION_OP_ASCENDING = 1;
  EXPRESSION_OP_DESCENDING = 2;
}

enum IdentifierType {
  IDENTIFIER_TYPE_UNSPECIFIED = 0;
  IDENTIFIER_TYPE_METHOD = 1;
  IDENTIFIER_TYPE_TYPE = 2;
  IDENTIFIER_TYPE_CONSTANT = 3;
  IDENTIFIER_TYPE_PATH = 4;
  IDENTIFIER_TYPE_VARIABLE = 5;
  IDENTIFIER_TYPE_FIELD = 6;
}

enum IssueKind {
  ISSUE_KIND_UNSPECIFIED = 0;
  ISSUE_KIND_ERROR = 1;
  ISSUE_KIND_WARNING = 2;
  ISSUE_KIND_NOTICE = 3;
}

enum IssueType {
  ISSUE_TYPE_UNSPECIFIED = 0;
  ISSUE_TYPE_INTERNAL = 1;
  ISSUE_TYPE_UNKNOWN_IMPORT_SOURCE = 2;
  ISSUE_TYPE_MISSING_REFERENCE = 3;
  ISSUE_TYPE_CIRCULAR_ANCESTRY = 4;
  ISSUE_TYPE_CIRCULAR_UNION = 5;
  ISSUE_TYPE_MISMATCHED_UNION = 6;
  ISSUE_TYPE_INVALID_DATA = 7;
  ISSUE_TYPE_AMBIGUOUS_DEFINITION = 8;
  ISSUE_TYPE_CODE_NOT_EXPORTABLE = 9;
  ISSUE_TYPE_CODE_NOT_CACHEABLE = 10;
  ISSUE_TYPE_CODE_REFERENCE_NOT_EXPORTED = 11;
  ISSUE_TYPE_TASK_MISSING_IO = 12;
  ISSUE_TYPE_TASK_IS_STATIC = 13;
}

enum NodeTrackingLevel {
  NODE_TRACKING_LEVEL_NONE = 0;
  NODE_TRACKING_LEVEL_ANONYMOUS = 1;
  NODE_TRACKING_LEVEL_FULL = 2;
}

enum NodeType {
  NODE_TYPE_UNSPECIFIED = 0;
  NODE_TYPE_MODULE = 1;
  NODE_TYPE_FILE = 2;
  NODE_TYPE_STATEMENT = 3;
  NODE_TYPE_TRIGGER = 4;
  NODE_TYPE_TAGGING = 5;
  NODE_TYPE_FIELD = 6;
  NODE_TYPE_RECORD = 7;
  NODE_TYPE_VIEW = 8;
  NODE_TYPE_ISSUE = 9;
  NODE_TYPE_RESOLVED_FIELD = 10;
  NODE_TYPE_BLOB = 11;
  NODE_TYPE_SECRET = 12;
  NODE_TYPE_SESSION = 13;
  NODE_TYPE_RUN = 14;
}

enum ProjectRegion {
  PROJECT_REGION_UNSPECIFIED = 0;
  PROJECT_REGION_US_WEST = 1;
  PROJECT_REGION_EU_CENTRAL = 2;
}

enum ProtoStrEnum {
  PROTO_STR_ENUM_UNSPECIFIED = 0;
}

enum QueryEngine {
  QUERY_ENGINE_UNSPECIFIED = 0;
  QUERY_ENGINE_LOCAL = 1;
  QUERY_ENGINE_RUNTIME = 2;
  QUERY_ENGINE_OPENSEARCH = 3;
  QUERY_ENGINE_POSTGRES = 4;
}

enum RunErrorKind {
  RUN_ERROR_KIND_UNSPECIFIED = 0;
  RUN_ERROR_KIND_Internal = 1;
  RUN_ERROR_KIND_Parse = 2;
  RUN_ERROR_KIND_Validation = 3;
  RUN_ERROR_KIND_Runtime = 4;
  RUN_ERROR_KIND_Untrusted = 5;
}

enum RunStatus {
  RUN_STATUS_UNSPECIFIED = 0;
  RUN_STATUS_SCHEDULED = 1;
  RUN_STATUS_QUEUED = 2;
  RUN_STATUS_RUNNING = 3;
  RUN_STATUS_SUSPENDED = 4;
  RUN_STATUS_ABORTING = 5;
  RUN_STATUS_CANCELLED = 6;
  RUN_STATUS_ABORTED = 7;
  RUN_STATUS_FAILED = 8;
  RUN_STATUS_COMPLETED = 9;
}

enum ScheduleType {
  SCHEDULE_TYPE_UNSPECIFIED = 0;
  SCHEDULE_TYPE_INTERVAL = 1;
  SCHEDULE_TYPE_CRON = 2;
}

enum SessionAccessLevel {
  option allow_alias = true;
  SESSION_ACCESS_LEVEL_Zero = 0;
  SESSION_ACCESS_LEVEL_Read = 1;
  SESSION_ACCESS_LEVEL_Create = 2;
  SESSION_ACCESS_LEVEL_Update = 3;
  SESSION_ACCESS_LEVEL_Delete = 4;
  SESSION_ACCESS_LEVEL_Full = 4;
}

enum SessionStatus {
  SESSION_STATUS_UNSPECIFIED = 0;
  SESSION_STATUS_ACTIVE = 1;
  SESSION_STATUS_SUSPENDED = 2;
  SESSION_STATUS_TERMINATED = 3;
}

enum SortMode {
  SORT_MODE_UNSPECIFIED = 0;
  SORT_MODE_MAX = 1;
  SORT_MODE_MIN = 2;
  SORT_MODE_AVERAGE = 3;
  SORT_MODE_SUM = 4;
  SORT_MODE_MEDIAN = 5;
}

enum SortOp {
  SORT_OP_UNSPECIFIED = 0;
  SORT_OP_ASCENDING = 1;
  SORT_OP_DESCENDING = 2;
}

enum StatementType {
  STATEMENT_TYPE_UNSPECIFIED = 0;
  STATEMENT_TYPE_TAG = 1;
  STATEMENT_TYPE_TEXT = 2;
  STATEMENT_TYPE_BLANK = 3;
  STATEMENT_TYPE_CLASS = 4;
  STATEMENT_TYPE_CHOICE = 5;
  STATEMENT_TYPE_TASK = 6;
  STATEMENT_TYPE_CODE = 7;
  STATEMENT_TYPE_FLOW = 8;
  STATEMENT_TYPE_MODEL = 9;
  STATEMENT_TYPE_VARIABLE = 10;
  STATEMENT_TYPE_DATABASE = 11;
  STATEMENT_TYPE_VIEW = 12;
  STATEMENT_TYPE_GROUP = 13;
}

enum StructType {
  STRUCT_TYPE_UNSPECIFIED = 0;
  STRUCT_TYPE_EXPRESSION = 101;
  STRUCT_TYPE_RUN_CODE_FRAME = 102;
  STRUCT_TYPE_RUN_ERROR = 103;
  STRUCT_TYPE_LOG_ENTRY = 104;
  STRUCT_TYPE_WORKER_SET = 105;
  STRUCT_TYPE_ENVIRONMENT = 106;
}

enum TextHeadingLevel {
  TEXT_HEADING_LEVEL_UNSPECIFIED = 0;
  TEXT_HEADING_LEVEL_H1 = 1;
  TEXT_HEADING_LEVEL_H2 = 2;
  TEXT_HEADING_LEVEL_H3 = 3;
}

enum TriggerType {
  TRIGGER_TYPE_UNSPECIFIED = 0;
  TRIGGER_TYPE_INVOKE = 1;
  TRIGGER_TYPE_TIME = 2;
  TRIGGER_TYPE_RUN = 3;
  TRIGGER_TYPE_EDIT = 4;
  TRIGGER_TYPE_MESSAGE = 5;
  TRIGGER_TYPE_USER = 6;
  TRIGGER_TYPE_API = 7;
}

enum TypeFlag {
  TYPE_FLAG_ZERO = 0;
  TYPE_FLAG_IS_OUTPUT = 1;
  TYPE_FLAG_IS_ARRAY = 2;
  TYPE_FLAG_IS_OPTIONAL = 4;
  TYPE_FLAG_IS_UNION_WITH = 8;
  TYPE_FLAG_IS_SECRET = 16;
  TYPE_FLAG_IS_STORE_ONLY = 32;
  TYPE_FLAG_IS_ARRAYABLE = 64;
  TYPE_FLAG_IS_META = 128;
  TYPE_FLAG_IS_CONFIG = 256;
  TYPE_FLAG_IS_HIDDEN = 512;
}

enum TypeHint {
  TYPE_HINT_UNSPECIFIED = 0;
  TYPE_HINT_NAME = 1;
  TYPE_HINT_UUID = 2;
  TYPE_HINT_DATE = 3;
  TYPE_HINT_DATETIME = 4;
  TYPE_HINT_TIME = 5;
  TYPE_HINT_DURATION = 6;
  TYPE_HINT_EMAIL = 7;
  TYPE_HINT_URL = 8;
  TYPE_HINT_MARKDOWN = 9;
  TYPE_HINT_RICH_TEXT = 10;
  TYPE_HINT_HTML = 11;
  TYPE_HINT_CODE = 12;
  TYPE_HINT_KEY = 13;
  TYPE_HINT_INTEGER = 14;
  TYPE_HINT_FLOAT = 15;
  TYPE_HINT_SLIDER = 16;
  TYPE_HINT_PHONE = 17;
  TYPE_HINT_RATING = 18;
  TYPE_HINT_TOGGLE = 19;
  TYPE_HINT_CHECKBOX = 20;
  TYPE_HINT_THUMBS = 21;
  TYPE_HINT_EMBEDDING = 22;
  TYPE_HINT_IMAGE = 23;
  TYPE_HINT_VIDEO = 24;
  TYPE_HINT_AUDIO = 25;
  TYPE_HINT_FILE = 26;
  TYPE_HINT_STATEMENT = 27;
  TYPE_HINT_RECORD = 28;
  TYPE_HINT_FIELD = 29;
  TYPE_HINT_RUN = 30;
  TYPE_HINT_SECRET = 31;
  TYPE_HINT_BLOB = 32;
}

enum TypeStorageFormat {
  TYPE_STORAGE_FORMAT_UNSPECIFIED = 0;
  TYPE_STORAGE_FORMAT_STRING = 1;
  TYPE_STORAGE_FORMAT_DOUBLE = 2;
  TYPE_STORAGE_FORMAT_LONG = 3;
  TYPE_STORAGE_FORMAT_VECTOR = 4;
  TYPE_STORAGE_FORMAT_BINARY = 5;
  TYPE_STORAGE_FORMAT_BOOLEAN = 6;
  TYPE_STORAGE_FORMAT_DATE = 7;
  TYPE_STORAGE_FORMAT_KEYWORD = 8;
  TYPE_STORAGE_FORMAT_OBJECT = 9;
  TYPE_STORAGE_FORMAT_RELATION = 10;
}

enum TypeTag {
  TYPE_TAG_UNSPECIFIED = 0;
  TYPE_TAG_STRING = 1;
  TYPE_TAG_NUMBER = 2;
  TYPE_TAG_BOOLEAN = 3;
  TYPE_TAG_VECTOR = 4;
  TYPE_TAG_BLOB = 5;
  TYPE_TAG_STRUCT = 6;
  TYPE_TAG_JSON = 7;
  TYPE_TAG_FUNCTION = 8;
  TYPE_TAG_ENUM = 9;
  TYPE_TAG_LITERAL = 10;
  TYPE_TAG_TYPE_REFERENCE = 11;
  TYPE_TAG_NODE = 12;
  TYPE_TAG_ANY = 13;
}

enum WorkerProfile {
  WORKER_PROFILE_UNSPECIFIED = 0;
  WORKER_PROFILE_TINY = 1;
  WORKER_PROFILE_SMALL = 2;
  WORKER_PROFILE_MEDIUM = 3;
  WORKER_PROFILE_LARGE = 4;
  WORKER_PROFILE_XLARGE_CPU = 5;
  WORKER_PROFILE_XLARGE_MEM = 6;
}

enum WorkerSetStatus {
  WORKER_SET_STATUS_UNSPECIFIED = 0;
  WORKER_SET_STATUS_SLEEPING = 1;
  WORKER_SET_STATUS_PENDING = 2;
  WORKER_SET_STATUS_UPDATING = 3;
  WORKER_SET_STATUS_HEALTHY = 4;
  WORKER_SET_STATUS_UNHEALTHY = 5;
  WORKER_SET_STATUS_UNAVAILABLE = 6;
  WORKER_SET_STATUS_UNKNOWN = 7;
}

message EnvironmentData {
  BenchType metatype = 1;
  string language = 20;
  string version = 21;
  string platform = 22;
  google.protobuf.Struct packages = 23;
}

message ExpressionData {
  BenchType metatype = 1;
  ExpressionOp op = 21;
  string field_ck = 22;
  string field_key = 23;
  repeated ExpressionData clauses = 24;
  google.protobuf.Struct value = 25;
  string mode = 26;
}

message LogEntryData {
  BenchType metatype = 1;
  string id = 2;
  string project_id = 20;
  string module_ck = 21;
  google.protobuf.Timestamp created_at = 22;
  string stream = 23;
  string session_ck = 24;
  string level = 25;
  string logger = 26;
  string statement_ck = 27;
  string run_ck = 28;
  string message = 29;
  google.protobuf.Struct value = 30;
}

message RunCodeFrameData {
  BenchType metatype = 1;
  string filename = 20;
  int64 lineno = 21;
  string name = 22;
  google.protobuf.Struct locals = 23;
  string line = 24;
}

message RunErrorData {
  BenchType metatype = 1;
  RunErrorKind kind = 20;
  string type = 21;
  string message = 22;
  string statement_ck = 23;
  repeated RunCodeFrameData traceback = 24;
}

message WorkerSetData {
  BenchType metatype = 1;
  string id = 2;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  string project_id = 20;
  ProjectRegion region = 21;
  WorkerProfile profile = 22;
  bool sleeping = 23;
  WorkerSetStatus status = 24;
  int64 desired_replicas = 25;
  int64 target_replicas = 26;
  int64 available_replicas = 27;
  int64 ready_replicas = 28;
  google.protobuf.Timestamp last_active_at = 29;
}

message BlobData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  string sha512 = 20;
  int64 content_length = 21;
  string content_type = 22;
  string name = 23;
  BlobStatus status = 24;
}

message FieldData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  string name = 21;
  string order_key = 22;
  string text = 23;
  TypeTag tag = 24;
  string key = 25;
  google.protobuf.Struct value = 26;
  string hint = 27;
  int64 flags = 28;
  string reference_ck = 29;
}

message FileData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  string name = 20;
}

message IssueData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  IssueType type = 20;
  IssueKind kind = 21;
  string message = 22;
  string subject_ck = 23;
  string path = 24;
  repeated string properties = 25;
}

message ModuleData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  string name = 20;
  bool committed = 21;
  string project_id = 22;
  string os_name = 23;
  string pg_name = 24;
}

message BaseNodeData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
}

message RecordData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  google.protobuf.Struct value = 20;
}

message ResolvedFieldData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  string field_ck = 20;
  string name = 21;
  string order_key = 22;
  string text = 23;
  TypeTag tag = 24;
  string key = 25;
  google.protobuf.Struct value = 26;
  string hint = 27;
  int64 flags = 28;
  string reference_ck = 29;
}

message RunData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  string session_id = 20;
  string root_id = 21;
  string project_id = 22;
  string worker_node_id = 23;
  string worker_process_id = 24;
  string statement_ck = 25;
  string statement_path = 26;
  google.protobuf.Timestamp scheduled_at = 27;
  google.protobuf.Timestamp started_at = 28;
  google.protobuf.Timestamp terminated_at = 29;
  string trigger_type = 30;
  string trigger_id = 31;
  int64 access_level = 32;
  RunStatus status = 33;
  google.protobuf.Struct inputs = 34;
  google.protobuf.Struct outputs = 35;
  google.protobuf.Struct error = 36;
  google.protobuf.Struct value = 37;
}

message SecretData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  string sha512 = 20;
}

message SessionData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  int64 access_level = 20;
  string project_id = 21;
  string worker_node_id = 22;
  string worker_process_id = 23;
  TriggerType trigger_type = 24;
  string trigger_id = 25;
  google.protobuf.Timestamp opened_at = 26;
  google.protobuf.Timestamp closed_at = 27;
  int64 inference_timeout = 28;
  int64 inference_retries = 29;
}

message StatementData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  StatementType type = 20;
  string name = 22;
  string order_key = 23;
  string reference_ck = 24;
  int64 heading_level = 25;
  string text = 26;
  string key = 27;
  string code = 28;
  google.protobuf.Struct value = 29;
  bool versioned = 30;
  string external_name = 31;
}

message TaggingData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  string key = 20;
  google.protobuf.Struct value = 21;
  string reference_ck = 22;
}

message TriggerData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  TriggerType type = 20;
  bool active = 21;
  string schedule_type = 22;
  string timezone = 23;
  int64 interval = 24;
  string cron = 25;
}

message ViewData {
  BenchType metatype = 1;
  string id = 2;
  string ck = 3;
  string parent_id = 4;
  google.protobuf.Timestamp created_at = 10;
  google.protobuf.Timestamp updated_at = 11;
  google.protobuf.Timestamp deleted_at = 12;
  google.protobuf.Timestamp last_edited_at = 13;
  google.protobuf.Timestamp last_changed_at = 14;
  int64 revision = 15;
  string name = 20;
  ExpressionData query = 22;
  repeated ExpressionData sort = 23;
}

message SomeNodeData {
  oneof node {
    ModuleData module = 1;
    FileData file = 2;
    StatementData statement = 3;
    TriggerData trigger = 4;
    TaggingData tagging = 5;
    FieldData field = 6;
    RecordData record = 7;
    ViewData view = 8;
    IssueData issue = 9;
    ResolvedFieldData resolved_field = 10;
    BlobData blob = 11;
    SecretData secret = 12;
    SessionData session = 13;
    RunData run = 14;
  };
}

message SomeStructData {
  oneof struct {
    ExpressionData expression = 1;
    RunCodeFrameData run_code_frame = 2;
    RunErrorData run_error = 3;
    LogEntryData log_entry = 4;
    WorkerSetData worker_set = 5;
    EnvironmentData environment = 6;
  };
}

message ModuleTreeData {
  ModuleData module = 1;
  repeated SomeNodeData nodes = 2;
}

