syntax = "proto3";

package symbolx.bench;

import "bench/proto/lang.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

enum ClientKind {
  CLIENT_KIND_UNSPECIFIED = 0;
  CLIENT_KIND_USER = 1;
  CLIENT_KIND_WORKER = 2;
}

message ClientOrigin {
  ClientKind kind = 1;
  string id = 2;
  string nonce = 3;
}

// Core metadata for all RPC requests.
// (This is passed as specially encoded headers, but it's nice to have a common definition.)
message RpcMetadata {
  // Client origin
  optional ClientKind client_kind = 1;
  optional string client_id = 2;
  optional string client_nonce = 3;
  optional string client_token = 4;

  // Scope
  optional string bench_id = 5;
  optional string package_id = 6;

  // Badge
  optional string badge_id = 7;
  optional string badge_link_token = 8;
  optional string badge_link_password = 9;
  optional string badge_key_value = 10;
}


// Edit describes an edit to a node in a Bench.
// (Manually defined here since Node properties inside structs aren't supported.)
message EditData {
  EditType type = 1;
  NodeType node_type = 2;
  SomeNodeData node = 3;
  repeated sint32 properties = 4;
  ClientOrigin origin = 5;
}
