syntax = "proto3";

package symbolx.bench;

import "bench/proto/lang.proto";
import "google/protobuf/descriptor.proto";

enum ServiceKind {
  UNSPECIFIED = 0;
  INTERNAL = 1;
  PUBLIC = 2;
}

extend google.protobuf.ServiceOptions {
  ServiceKind kind = 50000;
}

extend google.protobuf.FieldOptions {
  // Field should never be printed in logs.
  optional bool sensitive = 50000;
}

message ClientOrigin {
  ClientType type = 2;
  string id = 3;
  string nonce = 4;
}

// Core metadata for all RPC requests.
// This is passed as specially encoded headers with robust dicts,
// but it's nice to have a common definition.
// NOTE: update :RpcMetadataEncoding when changing RpcMetadata
message RpcMetadata {
  // Client
  optional string client_id = 2;
  optional string client_nonce = 3;
  optional string client_access_token = 4;

  // Badges
  message BadgeInfo {
    optional string id = 2;
    optional string key = 3;
    optional string password = 4;
  }
  repeated BadgeInfo badges = 5;
}

// Scope for an operation in the Bench graph.
message GraphScope {
  optional string bench_id = 1;
  optional string package_id = 3;
  optional string transaction_id = 4;
}

// Edit describes an edit to a Node.
// NOTE: obviously, we can only trust edits originating from the system
message EditData {
  string id = 2;
  EditType type = 30;
  optional ClientOrigin origin = 31;
  GraphScope scope = 32;
  NodeType node_type = 33;
  SomeNodeData node = 35;
  repeated uint32 properties = 36;

  optional NodeReferenceData subject = 40;
  optional uint64 seen_epoch = 41;
  // System-accepted revision for the edit.
  optional int64 revision = 42;
  // System-accepted epoch for the edit.
  optional int64 epoch = 43;
}

// Transaction of edits to a Node.
message TransactionData {
  string id = 2;
  ClientOrigin origin = 30;
  repeated EditData edits = 31;
}