syntax = "proto3";

import "bench/proto/bench.proto";
import "google/protobuf/empty.proto";

enum ClientType {
  WEB = 0;
  WORKER = 1;
}

message ClientOrigin {
  ClientType client_type = 1;
  string client_id = 2;
  string nonce = 3;
}

enum ServiceType {
  SERVICE_TYPE_UNSPECIFIED = 0;
  SERVICE_TYPE_RUNTIME_SUPERVISOR = 1;
  SERVICE_TYPE_RUNTIME_HOST = 2;
  SERVICE_TYPE_WORKER_NODE = 3;
}

//
// Runtime supervisor
//

message DidCreateProjectRequest {
  string project_id = 2;
}

service RuntimeSupervisor {// global (not yet sharded)
  rpc DidCreateProject(DidCreateProjectRequest) returns (google.protobuf.Empty);

  // worker management
  //  rpc WorkersChanged(WorkersChangedRequest) returns (stream WorkersChangedResponse);
  //  rpc ConfigureWorkerSet(ConfigureWorkerSetRequest) returns (ConfigureWorkerSetResponse);
  //  rpc WakeWorkerSet(WakeWorkerSetRequest) returns (WakeWorkerSetResponse);
  //  rpc RestartWorkerSet(RestartWorkerSetRequest) returns (RestartWorkerSetResponse);
  //  rpc GetEnvironment(GetEnvironmentRequest) returns (GetEnvironmentResponse);
  //  rpc PingWorkerSet(PingWorkerSetRequest) returns (PingWorkerSetResponse);
}

//
// Runtime host
//

message ReadModuleRequest {}

message ReadModuleResponse {
  ModuleTreeData module = 1;
}


service RuntimeHost {// scoped to project_id/module_id
  // subscriptions
  //  rpc ProjectChanged(ProjectChangedRequest) returns (stream ProjectChangedResponse);
  //  rpc ModuleChanged(ModuleChangedRequest) returns (stream ModuleChangedResponse);
  //  rpc RunsChanged(RunsChangedRequest) returns (stream RunsChangedResponse);
  //  rpc LogsChanged(LogsChangedRequest) returns (stream LogsChangedResponse);

  // read/write module
  rpc ReadModule(ReadModuleRequest) returns (ReadModuleResponse);
  //  rpc CommitEdits(CommitEditsRequest) returns (CommitEditsResponse);
  //  rpc PasteNodes(PasteNodesRequest) returns (PasteNodesResponse);
  //  rpc SnapshotModule(SnapshotModuleRequest) returns (SnapshotModuleResponse);
  //  rpc SearchRecords(SearchRecordsRequest) returns (SearchRecordsResponse);
  //  rpc DownloadBlob(DownloadBlobRequest) returns (DownloadBlobResponse);
  //  rpc UploadBlob(UploadBlobRequest) returns (UploadBlobResponse);
  //  rpc MarkUploadedBlob(MarkUploadedBlobRequest) returns (MarkUploadedBlobResponse);
  //  rpc RevealSecret(RevealSecretRequest) returns (RevealSecretResponse);
  //  rpc RunProxyInference(RunProxyInferenceRequest) returns (RunProxyInferenceResponse);
  //  rpc RunProxyStatement(RunProxyStatementRequest) returns (RunProxyStatementResponse);

  // runs
  //  rpc StartRun(StartRunRequest) returns (StartRunResponse);
  //  rpc KillRun(KillRunRequest) returns (KillRunResponse);
  //  rpc PullWorkerRuns(PullWorkerRunsRequest) returns (PullWorkerRunsResponse);
}

//
// Worker node
//

service WorkerNode {// scoped to project_id/worker_set_id
  //  rpc RestartWorker(RestartWorkerRequest) returns (RestartWorkerResponse);
  //  rpc StartRun(StartRunRequest) returns (StartRunResponse);
  //  rpc KillRun(KillRunRequest) returns (KillRunResponse);
}

