// generated by generate-bindings: do not edit

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(unreachable_pub)]
#![allow(clippy::bind_instead_of_map)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::len_zero)]

use crate::diagnostic::{RuntimeError, RuntimeResult};
use crate::platform::abi::{NativeSlice, NativeStringRef, NativeStringSlice};
use crate::platform::{
    NativeAbiCodec, NativeArray, PlatformError as AbiPlatformError, VmAbiCodec, VmAggregateCodec,
    VmArray, VmCollectionElement, VmSlice, VmValueCodec, memory as platform_memory,
};
use crate::runtime::BindingCallContext;
use destack_vm as vm;
use serde::{Deserialize, Serialize};

/// ABI newtype for MemoryProtection.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MemoryProtection(
    /// Inner value.
    pub u32,
);

pub type MemoryProtectionVm = MemoryProtection;

impl VmValueCodec for MemoryProtection {
    fn decode(value: vm::Word) -> RuntimeResult<Self> {
        Ok(Self(<u32 as VmValueCodec>::decode(value)?))
    }

    fn encode(self) -> vm::Word {
        <u32 as VmValueCodec>::encode(self.0)
    }
}

impl VmCollectionElement for MemoryProtection {}

/// Value type for MemoryProtection.
pub type MemoryProtectionValue = MemoryProtection;

impl NativeAbiCodec for MemoryProtection {
    type Value = MemoryProtectionValue;

    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(_binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {
        value
    }
}

impl VmAbiCodec for MemoryProtection {
    type Value = MemoryProtectionValue;

    fn into_value(
        self,
        _context: &vm::ExternalReadContext<'_, '_>,
    ) -> RuntimeResult<<Self as VmAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(
        _context: &mut vm::ExternalWriteContext<'_, '_>,
        value: <Self as VmAbiCodec>::Value,
    ) -> RuntimeResult<Self> {
        Ok(value)
    }
}

/// ABI newtype for MemoryRemapFlags.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MemoryRemapFlags(
    /// Inner value.
    pub u32,
);

pub type MemoryRemapFlagsVm = MemoryRemapFlags;

impl VmValueCodec for MemoryRemapFlags {
    fn decode(value: vm::Word) -> RuntimeResult<Self> {
        Ok(Self(<u32 as VmValueCodec>::decode(value)?))
    }

    fn encode(self) -> vm::Word {
        <u32 as VmValueCodec>::encode(self.0)
    }
}

impl VmCollectionElement for MemoryRemapFlags {}

/// Value type for MemoryRemapFlags.
pub type MemoryRemapFlagsValue = MemoryRemapFlags;

impl NativeAbiCodec for MemoryRemapFlags {
    type Value = MemoryRemapFlagsValue;

    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(_binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {
        value
    }
}

impl VmAbiCodec for MemoryRemapFlags {
    type Value = MemoryRemapFlagsValue;

    fn into_value(
        self,
        _context: &vm::ExternalReadContext<'_, '_>,
    ) -> RuntimeResult<<Self as VmAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(
        _context: &mut vm::ExternalWriteContext<'_, '_>,
        value: <Self as VmAbiCodec>::Value,
    ) -> RuntimeResult<Self> {
        Ok(value)
    }
}

/// ABI newtype for MemoryReserveFlags.
#[repr(transparent)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct MemoryReserveFlags(
    /// Inner value.
    pub u32,
);

pub type MemoryReserveFlagsVm = MemoryReserveFlags;

impl VmValueCodec for MemoryReserveFlags {
    fn decode(value: vm::Word) -> RuntimeResult<Self> {
        Ok(Self(<u32 as VmValueCodec>::decode(value)?))
    }

    fn encode(self) -> vm::Word {
        <u32 as VmValueCodec>::encode(self.0)
    }
}

impl VmCollectionElement for MemoryReserveFlags {}

/// Value type for MemoryReserveFlags.
pub type MemoryReserveFlagsValue = MemoryReserveFlags;

impl NativeAbiCodec for MemoryReserveFlags {
    type Value = MemoryReserveFlagsValue;

    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(_binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {
        value
    }
}

impl VmAbiCodec for MemoryReserveFlags {
    type Value = MemoryReserveFlagsValue;

    fn into_value(
        self,
        _context: &vm::ExternalReadContext<'_, '_>,
    ) -> RuntimeResult<<Self as VmAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(
        _context: &mut vm::ExternalWriteContext<'_, '_>,
        value: <Self as VmAbiCodec>::Value,
    ) -> RuntimeResult<Self> {
        Ok(value)
    }
}

/// ABI enum for MemoryAdvice.
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MemoryAdvice {
    /// Normal.
    Normal = 0,
    /// Sequential.
    Sequential = 1,
    /// Random.
    Random = 2,
    /// WillNeed.
    WillNeed = 3,
    /// DontNeed.
    DontNeed = 4,
}

impl VmValueCodec for MemoryAdvice {
    fn decode(value: vm::Word) -> RuntimeResult<Self> {
        let raw = <i32 as VmValueCodec>::decode(value)?;
        let decoded = match raw {
            0i32 => Self::Normal,
            1i32 => Self::Sequential,
            2i32 => Self::Random,
            3i32 => Self::WillNeed,
            4i32 => Self::DontNeed,
            _ => {
                return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(
                    "value",
                    "unknown MemoryAdvice value",
                ))
                .boxed());
            }
        };
        Ok(decoded)
    }

    fn encode(self) -> vm::Word {
        <i32 as VmValueCodec>::encode(self as i32)
    }
}

impl VmCollectionElement for MemoryAdvice {}

/// Value type for MemoryAdvice.
pub type MemoryAdviceValue = MemoryAdvice;

impl NativeAbiCodec for MemoryAdvice {
    type Value = MemoryAdviceValue;

    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(_binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {
        value
    }
}

impl VmAbiCodec for MemoryAdvice {
    type Value = MemoryAdviceValue;

    fn into_value(
        self,
        _context: &vm::ExternalReadContext<'_, '_>,
    ) -> RuntimeResult<<Self as VmAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(
        _context: &mut vm::ExternalWriteContext<'_, '_>,
        value: <Self as VmAbiCodec>::Value,
    ) -> RuntimeResult<Self> {
        Ok(value)
    }
}

/// ABI struct for MemoryRange.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct MemoryRange {
    /// Base address of the mapped range.
    pub address: u64,
    /// Length of the mapped range in bytes.
    pub length: u64,
}

pub type MemoryRangeVm = MemoryRange;

impl VmAggregateCodec for MemoryRange {
    fn decode_with_context(
        context: &vm::ExternalReadContext<'_, '_>,
        value: vm::Word,
    ) -> RuntimeResult<Self> {
        let value_ref = context
            .value_ref(value, "memory::MemoryRange")
            .map_err(|error| RuntimeError::from(error).boxed())?;
        <Self as VmAggregateCodec>::decode_value_ref_with_context(context, &value_ref)
    }

    fn decode_value_ref_with_context(
        context: &vm::ExternalReadContext<'_, '_>,
        value_ref: &vm::VmValueRef<'_, '_>,
    ) -> RuntimeResult<Self> {
        let field_count = value_ref.field_count();
        if field_count != 2 {
            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(
                "value",
                "expected 2 fields",
            ))
            .boxed());
        }
        let field_address =
            <u64 as VmAggregateCodec>::decode_field_with_context(context, value_ref, 0)?;
        let field_length =
            <u64 as VmAggregateCodec>::decode_field_with_context(context, value_ref, 1)?;
        Ok(Self {
            address: field_address,
            length: field_length,
        })
    }

    fn encode_with_context(
        self,
        context: &mut vm::ExternalWriteContext<'_, '_>,
    ) -> RuntimeResult<vm::Word> {
        let mut value_builder = context
            .begin_named_aggregate_builder("memory::MemoryRange")
            .map_err(Box::<RuntimeError>::from)?;
        let field_value = <u64 as VmAggregateCodec>::encode_with_context(self.address, context)?;
        value_builder
            .write_field(0, field_value)
            .map_err(Box::<RuntimeError>::from)?;
        let field_value = <u64 as VmAggregateCodec>::encode_with_context(self.length, context)?;
        value_builder
            .write_field(1, field_value)
            .map_err(Box::<RuntimeError>::from)?;
        value_builder.finish().map_err(Box::<RuntimeError>::from)
    }
}

/// Value type for MemoryRange.
pub type MemoryRangeValue = MemoryRange;

impl NativeAbiCodec for MemoryRange {
    type Value = MemoryRangeValue;

    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(_binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {
        value
    }
}

impl VmAbiCodec for MemoryRange {
    type Value = MemoryRangeValue;

    fn into_value(
        self,
        _context: &vm::ExternalReadContext<'_, '_>,
    ) -> RuntimeResult<<Self as VmAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(
        _context: &mut vm::ExternalWriteContext<'_, '_>,
        value: <Self as VmAbiCodec>::Value,
    ) -> RuntimeResult<Self> {
        Ok(value)
    }
}

impl VmCollectionElement for MemoryRange {}

/// ABI struct for ProtectedMemoryRange.
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct ProtectedMemoryRange {
    /// Base address of the mapped range.
    pub address: u64,
    /// Length of the mapped range in bytes.
    pub length: u64,
}

pub type ProtectedMemoryRangeVm = ProtectedMemoryRange;

impl VmAggregateCodec for ProtectedMemoryRange {
    fn decode_with_context(
        context: &vm::ExternalReadContext<'_, '_>,
        value: vm::Word,
    ) -> RuntimeResult<Self> {
        let value_ref = context
            .value_ref(value, "memory::ProtectedMemoryRange")
            .map_err(|error| RuntimeError::from(error).boxed())?;
        <Self as VmAggregateCodec>::decode_value_ref_with_context(context, &value_ref)
    }

    fn decode_value_ref_with_context(
        context: &vm::ExternalReadContext<'_, '_>,
        value_ref: &vm::VmValueRef<'_, '_>,
    ) -> RuntimeResult<Self> {
        let field_count = value_ref.field_count();
        if field_count != 2 {
            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(
                "value",
                "expected 2 fields",
            ))
            .boxed());
        }
        let field_address =
            <u64 as VmAggregateCodec>::decode_field_with_context(context, value_ref, 0)?;
        let field_length =
            <u64 as VmAggregateCodec>::decode_field_with_context(context, value_ref, 1)?;
        Ok(Self {
            address: field_address,
            length: field_length,
        })
    }

    fn encode_with_context(
        self,
        context: &mut vm::ExternalWriteContext<'_, '_>,
    ) -> RuntimeResult<vm::Word> {
        let mut value_builder = context
            .begin_named_aggregate_builder("memory::ProtectedMemoryRange")
            .map_err(Box::<RuntimeError>::from)?;
        let field_value = <u64 as VmAggregateCodec>::encode_with_context(self.address, context)?;
        value_builder
            .write_field(0, field_value)
            .map_err(Box::<RuntimeError>::from)?;
        let field_value = <u64 as VmAggregateCodec>::encode_with_context(self.length, context)?;
        value_builder
            .write_field(1, field_value)
            .map_err(Box::<RuntimeError>::from)?;
        value_builder.finish().map_err(Box::<RuntimeError>::from)
    }
}

/// Value type for ProtectedMemoryRange.
pub type ProtectedMemoryRangeValue = ProtectedMemoryRange;

impl NativeAbiCodec for ProtectedMemoryRange {
    type Value = ProtectedMemoryRangeValue;

    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(_binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {
        value
    }
}

impl VmAbiCodec for ProtectedMemoryRange {
    type Value = ProtectedMemoryRangeValue;

    fn into_value(
        self,
        _context: &vm::ExternalReadContext<'_, '_>,
    ) -> RuntimeResult<<Self as VmAbiCodec>::Value> {
        Ok(self)
    }

    fn from_value(
        _context: &mut vm::ExternalWriteContext<'_, '_>,
        value: <Self as VmAbiCodec>::Value,
    ) -> RuntimeResult<Self> {
        Ok(value)
    }
}

impl VmCollectionElement for ProtectedMemoryRange {}

/// Allow instruction fetch from mapped pages.
pub const MEMORY_PROTECTION_EXECUTE: MemoryProtection = MemoryProtection(4u32);

/// No protection bits.
pub const MEMORY_PROTECTION_NONE: MemoryProtection = MemoryProtection(0u32);

/// Allow reads from mapped pages.
pub const MEMORY_PROTECTION_READ: MemoryProtection = MemoryProtection(1u32);

/// Allow writes to mapped pages.
pub const MEMORY_PROTECTION_WRITE: MemoryProtection = MemoryProtection(2u32);

/// Allow remap operation to move mapping base address.
pub const MEMORY_REMAP_MAY_MOVE: MemoryRemapFlags = MemoryRemapFlags(1u32);

/// No remap flags.
pub const MEMORY_REMAP_NONE: MemoryRemapFlags = MemoryRemapFlags(0u32);

/// Request large-page backing for allocation-time mappings where supported.
pub const MEMORY_RESERVE_LARGE_PAGES: MemoryReserveFlags = MemoryReserveFlags(2u32);

/// No reserve flags.
pub const MEMORY_RESERVE_NONE: MemoryReserveFlags = MemoryReserveFlags(0u32);

/// Reserve address space without guaranteed swap reservation where supported.
pub const MEMORY_RESERVE_NO_RESERVE: MemoryReserveFlags = MemoryReserveFlags(4u32);

/// Prefer high virtual addresses where supported.
pub const MEMORY_RESERVE_TOP_DOWN: MemoryReserveFlags = MemoryReserveFlags(1u32);

/// Register VM aggregate schemas for memory.
pub(crate) fn register_memory_vm_aggregate_types(isolate: &mut vm::Isolate) -> vm::Result<()> {
    isolate.register_named_aggregate_type("memory::MemoryRange", 2)?;
    isolate.register_named_aggregate_type("memory::ProtectedMemoryRange", 2)?;

    Ok(())
}
