// generated by generate-bindings: do not edit

use crate::diagnostic::{RuntimeError, RuntimeResult};
use crate::platform::bindings::{
    BindingBlocking, BindingDescriptor, BindingRegistry, BindingReplayKind, BindingScope,
    NativeBinding, NativeBindingSet, ReplayPolicy, native_call,
};
use crate::platform::memory::{
    MemoryRange, MemoryRangeVm, ProtectedMemoryRange, ProtectedMemoryRangeVm,
};
use crate::platform::{PlatformError, RuntimeStatus};
#[cfg(feature = "replay")]
use crate::vm_binding_set;
use destack_vm as vm;
use destack_vm::Isolate;

use crate::binding;
use crate::runtime::{RuntimeCallContext, with_runtime_call_context};

use serde::{Deserialize, Serialize};

use crate::platform::memory::{native as platform_native, vm as platform_vm};

/// Read a positional argument value.
fn arg_value(
    args: &[vm::Value],
    index: usize,
    name: &'static str,
    expected: &'static str,
) -> RuntimeResult<vm::Value> {
    let value = args.get(index).copied().ok_or_else(|| {
        RuntimeError::from(PlatformError::invalid_argument_type(name, expected)).boxed()
    })?;

    Ok(value)
}

/// Decode a boolean argument.
#[allow(dead_code)]
fn decode_bool(
    value: vm::Value,
    name: &'static str,
    expected: &'static str,
) -> RuntimeResult<bool> {
    value.as_bool().ok_or_else(|| {
        RuntimeError::from(PlatformError::invalid_argument_type(name, expected)).boxed()
    })
}

/// Decode an unsigned integer argument with an explicit width.
fn decode_uint(
    value: vm::Value,
    name: &'static str,
    expected: &'static str,
    bits: u8,
) -> RuntimeResult<u64> {
    let (raw, width) = value.as_uint_with_width().ok_or_else(|| {
        RuntimeError::from(PlatformError::invalid_argument_type(name, expected)).boxed()
    })?;
    if width != bits {
        return Err(
            RuntimeError::from(PlatformError::invalid_argument_type(name, expected)).boxed(),
        );
    }

    Ok(raw)
}

/// Decode a u32 argument.
fn decode_uint32(
    value: vm::Value,
    name: &'static str,
    expected: &'static str,
) -> RuntimeResult<u32> {
    Ok(decode_uint(value, name, expected, 32)? as u32)
}

/// Decode a u64 argument.
fn decode_uint64(
    value: vm::Value,
    name: &'static str,
    expected: &'static str,
) -> RuntimeResult<u64> {
    decode_uint(value, name, expected, 64)
}

/// Decode arguments for destack.memory.advise.advise.
#[inline]
fn decode_destack_memory_advise_advise_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64, u32)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    let advice_value = arg_value(args, 2, "advice", "uint32")?;
    let advice = decode_uint32(advice_value, "advice", "uint32")?;
    Ok((address, length, advice))
}

/// Encode the result for destack.memory.advise.advise.
#[inline]
fn encode_destack_memory_advise_advise_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.advise.discard.
#[inline]
fn decode_destack_memory_advise_discard_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    Ok((address, length))
}

/// Encode the result for destack.memory.advise.discard.
#[inline]
fn encode_destack_memory_advise_discard_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.advise.hugePage.
#[inline]
fn decode_destack_memory_advise_huge_page_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64, bool)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    let enabled_value = arg_value(args, 2, "enabled", "boolean")?;
    let enabled = decode_bool(enabled_value, "enabled", "boolean")?;
    Ok((address, length, enabled))
}

/// Encode the result for destack.memory.advise.hugePage.
#[inline]
fn encode_destack_memory_advise_huge_page_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.lock.lock.
#[inline]
fn decode_destack_memory_lock_lock_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    Ok((address, length))
}

/// Encode the result for destack.memory.lock.lock.
#[inline]
fn encode_destack_memory_lock_lock_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.lock.unlock.
#[inline]
fn decode_destack_memory_lock_unlock_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    Ok((address, length))
}

/// Encode the result for destack.memory.lock.unlock.
#[inline]
fn encode_destack_memory_lock_unlock_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.map.commit.
#[inline]
fn decode_destack_memory_map_commit_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64, u32)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    let flags_value = arg_value(args, 2, "flags", "uint32")?;
    let flags = decode_uint32(flags_value, "flags", "uint32")?;
    Ok((address, length, flags))
}

/// Encode the result for destack.memory.map.commit.
#[inline]
fn encode_destack_memory_map_commit_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.map.decommit.
#[inline]
fn decode_destack_memory_map_decommit_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    Ok((address, length))
}

/// Encode the result for destack.memory.map.decommit.
#[inline]
fn encode_destack_memory_map_decommit_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.map.numaBind.
#[inline]
fn decode_destack_memory_map_numa_bind_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64, u32, u64)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    let policy_value = arg_value(args, 2, "policy", "uint32")?;
    let policy = decode_uint32(policy_value, "policy", "uint32")?;
    let nodemask_value = arg_value(args, 3, "nodemask", "uint64")?;
    let nodemask = decode_uint64(nodemask_value, "nodemask", "uint64")?;
    Ok((address, length, policy, nodemask))
}

/// Encode the result for destack.memory.map.numaBind.
#[inline]
fn encode_destack_memory_map_numa_bind_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.map.release.
#[inline]
fn decode_destack_memory_map_release_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    Ok((address, length))
}

/// Encode the result for destack.memory.map.release.
#[inline]
fn encode_destack_memory_map_release_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.map.reserve.
#[inline]
fn decode_destack_memory_map_reserve_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u32)> {
    // ignore unused context
    let _ = context;

    let length_value = arg_value(args, 0, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    let flags_value = arg_value(args, 1, "flags", "uint32")?;
    let flags = decode_uint32(flags_value, "flags", "uint32")?;
    Ok((length, flags))
}

/// Encode the result for destack.memory.map.reserve.
#[inline]
fn encode_destack_memory_map_reserve_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<MemoryRangeVm>,
) -> RuntimeResult<vm::Value> {
    result.map(|value| {
        let field_0 = vm::Value::uint(value.address, 64);
        let field_1 = vm::Value::uint(value.length, 64);
        context.allocate_aggregate(vec![field_0, field_1])
    })
}

/// Decode arguments for destack.memory.protect.execute.
#[inline]
fn decode_destack_memory_protect_execute_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64, bool)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    let enabled_value = arg_value(args, 2, "enabled", "boolean")?;
    let enabled = decode_bool(enabled_value, "enabled", "boolean")?;
    Ok((address, length, enabled))
}

/// Encode the result for destack.memory.protect.execute.
#[inline]
fn encode_destack_memory_protect_execute_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.protect.flushInstructionCache.
#[inline]
fn decode_destack_memory_protect_flush_instruction_cache_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    Ok((address, length))
}

/// Encode the result for destack.memory.protect.flushInstructionCache.
#[inline]
fn encode_destack_memory_protect_flush_instruction_cache_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.protect.protect.
#[inline]
fn decode_destack_memory_protect_protect_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64, u32)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let length_value = arg_value(args, 1, "length", "uint64")?;
    let length = decode_uint64(length_value, "length", "uint64")?;
    let protection_value = arg_value(args, 2, "protection", "uint32")?;
    let protection = decode_uint32(protection_value, "protection", "uint32")?;
    Ok((address, length, protection))
}

/// Encode the result for destack.memory.protect.protect.
#[inline]
fn encode_destack_memory_protect_protect_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Decode arguments for destack.memory.protect.remap.
#[inline]
fn decode_destack_memory_protect_remap_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(u64, u64, u64, u32)> {
    // ignore unused context
    let _ = context;

    let address_value = arg_value(args, 0, "address", "uint64")?;
    let address = decode_uint64(address_value, "address", "uint64")?;
    let oldlength_value = arg_value(args, 1, "oldlength", "uint64")?;
    let oldlength = decode_uint64(oldlength_value, "oldlength", "uint64")?;
    let newlength_value = arg_value(args, 2, "newlength", "uint64")?;
    let newlength = decode_uint64(newlength_value, "newlength", "uint64")?;
    let flags_value = arg_value(args, 3, "flags", "uint32")?;
    let flags = decode_uint32(flags_value, "flags", "uint32")?;
    Ok((address, oldlength, newlength, flags))
}

/// Encode the result for destack.memory.protect.remap.
#[inline]
fn encode_destack_memory_protect_remap_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<ProtectedMemoryRangeVm>,
) -> RuntimeResult<vm::Value> {
    result.map(|value| {
        let field_0 = vm::Value::uint(value.address, 64);
        let field_1 = vm::Value::uint(value.length, 64);
        context.allocate_aggregate(vec![field_0, field_1])
    })
}

/// Decode arguments for destack.memory.protect.setWriteXorExecute.
#[inline]
fn decode_destack_memory_protect_set_write_xor_execute_args(
    context: &mut vm::RuntimeContext<'_>,
    args: &[vm::Value],
) -> RuntimeResult<(bool,)> {
    // ignore unused context
    let _ = context;

    let enabled_value = arg_value(args, 0, "enabled", "boolean")?;
    let enabled = decode_bool(enabled_value, "enabled", "boolean")?;
    Ok((enabled,))
}

/// Encode the result for destack.memory.protect.setWriteXorExecute.
#[inline]
fn encode_destack_memory_protect_set_write_xor_execute_result(
    context: &mut vm::RuntimeContext<'_>,
    result: RuntimeResult<()>,
) -> RuntimeResult<vm::Value> {
    // ignore unused context
    let _ = context;

    result.map(|_| vm::Value::VOID)
}

/// Replay payload for destack.memory.advise.advise.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryAdviseAdviseReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.advise.discard.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryAdviseDiscardReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.advise.hugePage.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryAdviseHugePageReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.lock.lock.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryLockLockReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.lock.unlock.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryLockUnlockReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.map.commit.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryMapCommitReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.map.decommit.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryMapDecommitReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.map.numaBind.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryMapNumaBindReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.map.release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryMapReleaseReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.map.reserve.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryMapReserveReplay {
    /// Replay result payload.
    pub result: Result<MemoryRange, PlatformError>,
}

/// Replay payload for destack.memory.protect.execute.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryProtectExecuteReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.protect.flushInstructionCache.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryProtectFlushInstructionCacheReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.protect.protect.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryProtectProtectReplay {
    /// Replay result payload.
    pub result: Result<(), PlatformError>,
}

/// Replay payload for destack.memory.protect.remap.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
struct MemoryProtectRemapReplay {
    /// Replay result payload.
    pub result: Result<ProtectedMemoryRange, PlatformError>,
}

/// Binding descriptor for destack.memory.advise.advise.
pub const MEMORY_ADVISE_ADVISE: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.advise.advise",
        "export function advise(address: uint64, length: uint64, advice: uint32): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.advise"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.advise.discard.
pub const MEMORY_ADVISE_DISCARD: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.advise.discard",
        "export function discard(address: uint64, length: uint64): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.advise"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.advise.hugePage.
pub const MEMORY_ADVISE_HUGE_PAGE: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.advise.hugePage",
        "export function hugePage(address: uint64, length: uint64, enabled: boolean): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.hugePage"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.lock.lock.
pub const MEMORY_LOCK_LOCK: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.lock.lock",
        "export function lock(address: uint64, length: uint64): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.lock"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.lock.unlock.
pub const MEMORY_LOCK_UNLOCK: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.lock.unlock",
        "export function unlock(address: uint64, length: uint64): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.lock"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.map.commit.
pub const MEMORY_MAP_COMMIT: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.map.commit",
        "export function commit(address: uint64, length: uint64, flags: uint32): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.map"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.map.decommit.
pub const MEMORY_MAP_DECOMMIT: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.map.decommit",
        "export function decommit(address: uint64, length: uint64): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.map"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.map.numaBind.
pub const MEMORY_MAP_NUMA_BIND: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.map.numaBind",
        "export function numaBind(address: uint64, length: uint64, policy: uint32, nodeMask: uint64): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.numa"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.map.release.
pub const MEMORY_MAP_RELEASE: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.map.release",
        "export function release(address: uint64, length: uint64): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.map"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.map.reserve.
pub const MEMORY_MAP_RESERVE: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.map.reserve",
        "export function reserve(length: uint64, flags: uint32): Result<MemoryRange, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.map"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.protect.execute.
pub const MEMORY_PROTECT_EXECUTE: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.protect.execute",
        "export function protectExecute(address: uint64, length: uint64, enabled: boolean): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.execute"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.protect.flushInstructionCache.
pub const MEMORY_PROTECT_FLUSH_INSTRUCTION_CACHE: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.protect.flushInstructionCache",
        "export function flushInstructionCache(address: uint64, length: uint64): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.execute"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.protect.protect.
pub const MEMORY_PROTECT_PROTECT: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.protect.protect",
        "export function protect(address: uint64, length: uint64, protection: uint32): Result<void, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.protect"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.protect.remap.
pub const MEMORY_PROTECT_REMAP: BindingDescriptor =
    BindingDescriptor::external_with_requires_and_behavior(
        "destack.memory.protect.remap",
        "export function remap(address: uint64, oldLength: uint64, newLength: uint64, flags: uint32): Result<ProtectedMemoryRange, PlatformError>",
        ReplayPolicy::Recordable,
        BindingReplayKind::Regular,
        &["memory.protect"],
        BindingScope::Os,
        BindingBlocking::Sometimes,
    );

/// Binding descriptor for destack.memory.protect.setWriteXorExecute.
pub const MEMORY_PROTECT_SET_WRITE_XOR_EXECUTE: BindingDescriptor =
    BindingDescriptor::deterministic_with_requires_and_behavior(
        "destack.memory.protect.setWriteXorExecute",
        "export function setWriteXorExecute(enabled: boolean): Result<void, PlatformError>",
        &["memory.execute"],
        BindingScope::Runtime,
        BindingBlocking::Never,
    );

/// Binding descriptors for memory.
pub const BINDINGS: &[BindingDescriptor] = &[
    MEMORY_ADVISE_ADVISE,
    MEMORY_ADVISE_DISCARD,
    MEMORY_ADVISE_HUGE_PAGE,
    MEMORY_LOCK_LOCK,
    MEMORY_LOCK_UNLOCK,
    MEMORY_MAP_COMMIT,
    MEMORY_MAP_DECOMMIT,
    MEMORY_MAP_NUMA_BIND,
    MEMORY_MAP_RELEASE,
    MEMORY_MAP_RESERVE,
    MEMORY_PROTECT_EXECUTE,
    MEMORY_PROTECT_FLUSH_INSTRUCTION_CACHE,
    MEMORY_PROTECT_PROTECT,
    MEMORY_PROTECT_REMAP,
    MEMORY_PROTECT_SET_WRITE_XOR_EXECUTE,
];

/// Native binding set for memory.
pub const MEMORY_NATIVE_BINDINGS: NativeBindingSet = NativeBindingSet {
    name: "memory",
    bindings: &[
        NativeBinding::new(
            MEMORY_ADVISE_ADVISE,
            "destack.memory.advise.advise",
            destack_memory_advise_advise as *const (),
        ),
        NativeBinding::new(
            MEMORY_ADVISE_DISCARD,
            "destack.memory.advise.discard",
            destack_memory_advise_discard as *const (),
        ),
        NativeBinding::new(
            MEMORY_ADVISE_HUGE_PAGE,
            "destack.memory.advise.hugePage",
            destack_memory_advise_huge_page as *const (),
        ),
        NativeBinding::new(
            MEMORY_LOCK_LOCK,
            "destack.memory.lock.lock",
            destack_memory_lock_lock as *const (),
        ),
        NativeBinding::new(
            MEMORY_LOCK_UNLOCK,
            "destack.memory.lock.unlock",
            destack_memory_lock_unlock as *const (),
        ),
        NativeBinding::new(
            MEMORY_MAP_COMMIT,
            "destack.memory.map.commit",
            destack_memory_map_commit as *const (),
        ),
        NativeBinding::new(
            MEMORY_MAP_DECOMMIT,
            "destack.memory.map.decommit",
            destack_memory_map_decommit as *const (),
        ),
        NativeBinding::new(
            MEMORY_MAP_NUMA_BIND,
            "destack.memory.map.numaBind",
            destack_memory_map_numa_bind as *const (),
        ),
        NativeBinding::new(
            MEMORY_MAP_RELEASE,
            "destack.memory.map.release",
            destack_memory_map_release as *const (),
        ),
        NativeBinding::new(
            MEMORY_MAP_RESERVE,
            "destack.memory.map.reserve",
            destack_memory_map_reserve as *const (),
        ),
        NativeBinding::new(
            MEMORY_PROTECT_EXECUTE,
            "destack.memory.protect.execute",
            destack_memory_protect_execute as *const (),
        ),
        NativeBinding::new(
            MEMORY_PROTECT_FLUSH_INSTRUCTION_CACHE,
            "destack.memory.protect.flushInstructionCache",
            destack_memory_protect_flush_instruction_cache as *const (),
        ),
        NativeBinding::new(
            MEMORY_PROTECT_PROTECT,
            "destack.memory.protect.protect",
            destack_memory_protect_protect as *const (),
        ),
        NativeBinding::new(
            MEMORY_PROTECT_REMAP,
            "destack.memory.protect.remap",
            destack_memory_protect_remap as *const (),
        ),
        NativeBinding::new(
            MEMORY_PROTECT_SET_WRITE_XOR_EXECUTE,
            "destack.memory.protect.setWriteXorExecute",
            destack_memory_protect_set_write_xor_execute as *const (),
        ),
    ],
};

/// Native replay implementations for memory bindings.
#[inline]
fn destack_memory_advise_advise_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
    advice: u32,
) -> RuntimeResult<()> {
    let _ = (&address, &length, &advice);

    context.replay().run_binding(
        MEMORY_ADVISE_ADVISE,
        || unsafe { platform_native::destack_memory_advise(context, address, length, advice) },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryAdviseAdviseReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryAdviseAdviseReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_advise_discard_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
) -> RuntimeResult<()> {
    let _ = (&address, &length);

    context.replay().run_binding(
        MEMORY_ADVISE_DISCARD,
        || unsafe { platform_native::destack_memory_discard(context, address, length) },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryAdviseDiscardReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryAdviseDiscardReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_advise_huge_page_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
    enabled: bool,
) -> RuntimeResult<()> {
    let _ = (&address, &length, &enabled);

    context.replay().run_binding(
        MEMORY_ADVISE_HUGE_PAGE,
        || unsafe { platform_native::destack_memory_huge_page(context, address, length, enabled) },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryAdviseHugePageReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryAdviseHugePageReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_lock_lock_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
) -> RuntimeResult<()> {
    let _ = (&address, &length);

    context.replay().run_binding(
        MEMORY_LOCK_LOCK,
        || unsafe { platform_native::destack_memory_lock(context, address, length) },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryLockLockReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryLockLockReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_lock_unlock_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
) -> RuntimeResult<()> {
    let _ = (&address, &length);

    context.replay().run_binding(
        MEMORY_LOCK_UNLOCK,
        || unsafe { platform_native::destack_memory_unlock(context, address, length) },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryLockUnlockReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryLockUnlockReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_map_commit_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
    flags: u32,
) -> RuntimeResult<()> {
    let _ = (&address, &length, &flags);

    context.replay().run_binding(
        MEMORY_MAP_COMMIT,
        || unsafe { platform_native::destack_memory_commit(context, address, length, flags) },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryMapCommitReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryMapCommitReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_map_decommit_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
) -> RuntimeResult<()> {
    let _ = (&address, &length);

    context.replay().run_binding(
        MEMORY_MAP_DECOMMIT,
        || unsafe { platform_native::destack_memory_decommit(context, address, length) },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryMapDecommitReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryMapDecommitReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_map_numa_bind_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
    policy: u32,
    nodemask: u64,
) -> RuntimeResult<()> {
    let _ = (&address, &length, &policy, &nodemask);

    context.replay().run_binding(
        MEMORY_MAP_NUMA_BIND,
        || unsafe {
            platform_native::destack_memory_numa_bind(context, address, length, policy, nodemask)
        },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryMapNumaBindReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryMapNumaBindReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_map_release_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
) -> RuntimeResult<()> {
    let _ = (&address, &length);

    context.replay().run_binding(
        MEMORY_MAP_RELEASE,
        || unsafe { platform_native::destack_memory_release(context, address, length) },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryMapReleaseReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryMapReleaseReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_map_reserve_replay(
    context: &RuntimeCallContext,
    out: *mut MemoryRange,
    length: u64,
    flags: u32,
) -> RuntimeResult<()> {
    let _ = (&length, &flags);

    context.replay().run_binding(
        MEMORY_MAP_RESERVE,
        || unsafe { platform_native::destack_memory_reserve(context, out, length, flags) },
        |result| {
            if let Ok(()) = result {
                let result_value = unsafe {
                    if out.is_null() {
                        return Err(RuntimeError::from(PlatformError::null_pointer("out")).boxed());
                    }
                    *out
                };
                let result_replay_address = result_value.address;
                let result_replay_length = result_value.length;
                let result_replay = MemoryRange {
                    address: result_replay_address,
                    length: result_replay_length,
                };
                let payload = MemoryMapReserveReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryMapReserveReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(value) => {
                    let value_native_address = value.address;
                    let value_native_length = value.length;
                    let value_native = MemoryRange {
                        address: value_native_address,
                        length: value_native_length,
                    };
                    unsafe {
                        std::ptr::write(out, value_native);
                    }
                    Ok(())
                }
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_protect_execute_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
    enabled: bool,
) -> RuntimeResult<()> {
    let _ = (&address, &length, &enabled);

    context.replay().run_binding(
        MEMORY_PROTECT_EXECUTE,
        || unsafe {
            platform_native::destack_memory_protect_execute(context, address, length, enabled)
        },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryProtectExecuteReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryProtectExecuteReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_protect_flush_instruction_cache_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
) -> RuntimeResult<()> {
    let _ = (&address, &length);

    context.replay().run_binding(
        MEMORY_PROTECT_FLUSH_INSTRUCTION_CACHE,
        || unsafe {
            platform_native::destack_memory_flush_instruction_cache(context, address, length)
        },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryProtectFlushInstructionCacheReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryProtectFlushInstructionCacheReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_protect_protect_replay(
    context: &RuntimeCallContext,
    address: u64,
    length: u64,
    protection: u32,
) -> RuntimeResult<()> {
    let _ = (&address, &length, &protection);

    context.replay().run_binding(
        MEMORY_PROTECT_PROTECT,
        || unsafe { platform_native::destack_memory_protect(context, address, length, protection) },
        |result| {
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryProtectProtectReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryProtectProtectReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

#[inline]
fn destack_memory_protect_remap_replay(
    context: &RuntimeCallContext,
    out: *mut ProtectedMemoryRange,
    address: u64,
    oldlength: u64,
    newlength: u64,
    flags: u32,
) -> RuntimeResult<()> {
    let _ = (&address, &oldlength, &newlength, &flags);

    context.replay().run_binding(
        MEMORY_PROTECT_REMAP,
        || unsafe {
            platform_native::destack_memory_remap(
                context, out, address, oldlength, newlength, flags,
            )
        },
        |result| {
            if let Ok(()) = result {
                let result_value = unsafe {
                    if out.is_null() {
                        return Err(RuntimeError::from(PlatformError::null_pointer("out")).boxed());
                    }
                    *out
                };
                let result_replay_address = result_value.address;
                let result_replay_length = result_value.length;
                let result_replay = ProtectedMemoryRange {
                    address: result_replay_address,
                    length: result_replay_length,
                };
                let payload = MemoryProtectRemapReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryProtectRemapReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |payload| {
            // replay result
            match payload.result {
                Ok(value) => {
                    let value_native_address = value.address;
                    let value_native_length = value.length;
                    let value_native = ProtectedMemoryRange {
                        address: value_native_address,
                        length: value_native_length,
                    };
                    unsafe {
                        std::ptr::write(out, value_native);
                    }
                    Ok(())
                }
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    )
}

/// Native export wrappers for memory bindings.
#[unsafe(export_name = "destack.memory.advise.advise")]
pub unsafe extern "C" fn destack_memory_advise_advise(
    address: u64,
    length: u64,
    advice: u32,
) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_ADVISE_ADVISE)?;
        let _ = (&address, &length, &advice);

        destack_memory_advise_advise_replay(context, address, length, advice)
    })
}

#[unsafe(export_name = "destack.memory.advise.discard")]
pub unsafe extern "C" fn destack_memory_advise_discard(address: u64, length: u64) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_ADVISE_DISCARD)?;
        let _ = (&address, &length);

        destack_memory_advise_discard_replay(context, address, length)
    })
}

#[unsafe(export_name = "destack.memory.advise.hugePage")]
pub unsafe extern "C" fn destack_memory_advise_huge_page(
    address: u64,
    length: u64,
    enabled: bool,
) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_ADVISE_HUGE_PAGE)?;
        let _ = (&address, &length, &enabled);

        destack_memory_advise_huge_page_replay(context, address, length, enabled)
    })
}

#[unsafe(export_name = "destack.memory.lock.lock")]
pub unsafe extern "C" fn destack_memory_lock_lock(address: u64, length: u64) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_LOCK_LOCK)?;
        let _ = (&address, &length);

        destack_memory_lock_lock_replay(context, address, length)
    })
}

#[unsafe(export_name = "destack.memory.lock.unlock")]
pub unsafe extern "C" fn destack_memory_lock_unlock(address: u64, length: u64) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_LOCK_UNLOCK)?;
        let _ = (&address, &length);

        destack_memory_lock_unlock_replay(context, address, length)
    })
}

#[unsafe(export_name = "destack.memory.map.commit")]
pub unsafe extern "C" fn destack_memory_map_commit(
    address: u64,
    length: u64,
    flags: u32,
) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_MAP_COMMIT)?;
        let _ = (&address, &length, &flags);

        destack_memory_map_commit_replay(context, address, length, flags)
    })
}

#[unsafe(export_name = "destack.memory.map.decommit")]
pub unsafe extern "C" fn destack_memory_map_decommit(address: u64, length: u64) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_MAP_DECOMMIT)?;
        let _ = (&address, &length);

        destack_memory_map_decommit_replay(context, address, length)
    })
}

#[unsafe(export_name = "destack.memory.map.numaBind")]
pub unsafe extern "C" fn destack_memory_map_numa_bind(
    address: u64,
    length: u64,
    policy: u32,
    nodemask: u64,
) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_MAP_NUMA_BIND)?;
        let _ = (&address, &length, &policy, &nodemask);

        destack_memory_map_numa_bind_replay(context, address, length, policy, nodemask)
    })
}

#[unsafe(export_name = "destack.memory.map.release")]
pub unsafe extern "C" fn destack_memory_map_release(address: u64, length: u64) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_MAP_RELEASE)?;
        let _ = (&address, &length);

        destack_memory_map_release_replay(context, address, length)
    })
}

#[unsafe(export_name = "destack.memory.map.reserve")]
pub unsafe extern "C" fn destack_memory_map_reserve(
    out: *mut MemoryRange,
    length: u64,
    flags: u32,
) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_MAP_RESERVE)?;
        if out.is_null() {
            return Err(RuntimeError::from(PlatformError::null_pointer("out")).boxed());
        }
        let _ = (&out, &length, &flags);

        destack_memory_map_reserve_replay(context, out, length, flags)
    })
}

#[unsafe(export_name = "destack.memory.protect.execute")]
pub unsafe extern "C" fn destack_memory_protect_execute(
    address: u64,
    length: u64,
    enabled: bool,
) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_PROTECT_EXECUTE)?;
        let _ = (&address, &length, &enabled);

        destack_memory_protect_execute_replay(context, address, length, enabled)
    })
}

#[unsafe(export_name = "destack.memory.protect.flushInstructionCache")]
pub unsafe extern "C" fn destack_memory_protect_flush_instruction_cache(
    address: u64,
    length: u64,
) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_PROTECT_FLUSH_INSTRUCTION_CACHE)?;
        let _ = (&address, &length);

        destack_memory_protect_flush_instruction_cache_replay(context, address, length)
    })
}

#[unsafe(export_name = "destack.memory.protect.protect")]
pub unsafe extern "C" fn destack_memory_protect_protect(
    address: u64,
    length: u64,
    protection: u32,
) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_PROTECT_PROTECT)?;
        let _ = (&address, &length, &protection);

        destack_memory_protect_protect_replay(context, address, length, protection)
    })
}

#[unsafe(export_name = "destack.memory.protect.remap")]
pub unsafe extern "C" fn destack_memory_protect_remap(
    out: *mut ProtectedMemoryRange,
    address: u64,
    oldlength: u64,
    newlength: u64,
    flags: u32,
) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_PROTECT_REMAP)?;
        if out.is_null() {
            return Err(RuntimeError::from(PlatformError::null_pointer("out")).boxed());
        }
        let _ = (&out, &address, &oldlength, &newlength, &flags);

        destack_memory_protect_remap_replay(context, out, address, oldlength, newlength, flags)
    })
}

#[unsafe(export_name = "destack.memory.protect.setWriteXorExecute")]
pub unsafe extern "C" fn destack_memory_protect_set_write_xor_execute(
    enabled: bool,
) -> RuntimeStatus {
    native_call(|context| {
        context.check_policy(MEMORY_PROTECT_SET_WRITE_XOR_EXECUTE)?;
        let _ = &enabled;

        unsafe { platform_native::destack_memory_set_write_xor_execute(context, enabled) }
    })
}

/// VM replay implementations for memory bindings.
#[inline]
fn destack_memory_advise_advise_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
    advice: u32,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_ADVISE_ADVISE,
        context,
        |context| platform_vm::destack_memory_advise(runtime, context, address, length, advice),
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryAdviseAdviseReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryAdviseAdviseReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_advise_advise_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_advise_discard_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_ADVISE_DISCARD,
        context,
        |context| platform_vm::destack_memory_discard(runtime, context, address, length),
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryAdviseDiscardReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryAdviseDiscardReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_advise_discard_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_advise_huge_page_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
    enabled: bool,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_ADVISE_HUGE_PAGE,
        context,
        |context| platform_vm::destack_memory_huge_page(runtime, context, address, length, enabled),
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryAdviseHugePageReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryAdviseHugePageReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_advise_huge_page_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_lock_lock_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_LOCK_LOCK,
        context,
        |context| platform_vm::destack_memory_lock(runtime, context, address, length),
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryLockLockReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryLockLockReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_lock_lock_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_lock_unlock_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_LOCK_UNLOCK,
        context,
        |context| platform_vm::destack_memory_unlock(runtime, context, address, length),
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryLockUnlockReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryLockUnlockReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_lock_unlock_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_map_commit_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
    flags: u32,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_MAP_COMMIT,
        context,
        |context| platform_vm::destack_memory_commit(runtime, context, address, length, flags),
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryMapCommitReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryMapCommitReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_map_commit_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_map_decommit_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_MAP_DECOMMIT,
        context,
        |context| platform_vm::destack_memory_decommit(runtime, context, address, length),
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryMapDecommitReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryMapDecommitReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_map_decommit_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_map_numa_bind_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
    policy: u32,
    nodemask: u64,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_MAP_NUMA_BIND,
        context,
        |context| {
            platform_vm::destack_memory_numa_bind(
                runtime, context, address, length, policy, nodemask,
            )
        },
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryMapNumaBindReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryMapNumaBindReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_map_numa_bind_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_map_release_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_MAP_RELEASE,
        context,
        |context| platform_vm::destack_memory_release(runtime, context, address, length),
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryMapReleaseReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryMapReleaseReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_map_release_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_map_reserve_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    length: u64,
    flags: u32,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_MAP_RESERVE,
        context,
        |context| platform_vm::destack_memory_reserve(runtime, context, length, flags),
        |context, result| {
            let _ = &context;
            if let Ok(value) = result {
                let result_value = *value;
                let result_replay_address = result_value.address;
                let result_replay_length = result_value.length;
                let result_replay = MemoryRange {
                    address: result_replay_address,
                    length: result_replay_length,
                };
                let payload = MemoryMapReserveReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryMapReserveReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(value) => {
                    let vm_result_address = value.address;
                    let vm_result_length = value.length;
                    let vm_result = MemoryRangeVm {
                        address: vm_result_address,
                        length: vm_result_length,
                    };
                    Ok(vm_result)
                }
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_map_reserve_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_protect_execute_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
    enabled: bool,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_PROTECT_EXECUTE,
        context,
        |context| {
            platform_vm::destack_memory_protect_execute(runtime, context, address, length, enabled)
        },
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryProtectExecuteReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryProtectExecuteReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_protect_execute_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_protect_flush_instruction_cache_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_PROTECT_FLUSH_INSTRUCTION_CACHE,
        context,
        |context| {
            platform_vm::destack_memory_flush_instruction_cache(runtime, context, address, length)
        },
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryProtectFlushInstructionCacheReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryProtectFlushInstructionCacheReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_protect_flush_instruction_cache_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_protect_protect_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    length: u64,
    protection: u32,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_PROTECT_PROTECT,
        context,
        |context| {
            platform_vm::destack_memory_protect(runtime, context, address, length, protection)
        },
        |context, result| {
            let _ = &context;
            if let Ok(()) = result {
                let result_replay = ();
                let payload = MemoryProtectProtectReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryProtectProtectReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(()) => Ok(()),
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_protect_protect_result(context, result)?;
    Ok(result)
}

#[inline]
fn destack_memory_protect_remap_vm_replay(
    runtime: &RuntimeCallContext,
    context: &mut vm::RuntimeContext<'_>,
    address: u64,
    oldlength: u64,
    newlength: u64,
    flags: u32,
) -> RuntimeResult<vm::Value> {
    let result = runtime.replay().run_binding_with_context(
        MEMORY_PROTECT_REMAP,
        context,
        |context| {
            platform_vm::destack_memory_remap(
                runtime, context, address, oldlength, newlength, flags,
            )
        },
        |context, result| {
            let _ = &context;
            if let Ok(value) = result {
                let result_value = *value;
                let result_replay_address = result_value.address;
                let result_replay_length = result_value.length;
                let result_replay = ProtectedMemoryRange {
                    address: result_replay_address,
                    length: result_replay_length,
                };
                let payload = MemoryProtectRemapReplay {
                    result: Ok(result_replay),
                };
                return Ok(Some(payload));
            }

            if let Err(error) = result {
                let payload = {
                    let result = Err(PlatformError::from(error.as_ref()));
                    MemoryProtectRemapReplay { result }
                };
                return Ok(Some(payload));
            }

            Ok(None)
        },
        |context, payload| {
            let _ = &context;
            // replay result
            match payload.result {
                Ok(value) => {
                    let vm_result_address = value.address;
                    let vm_result_length = value.length;
                    let vm_result = ProtectedMemoryRangeVm {
                        address: vm_result_address,
                        length: vm_result_length,
                    };
                    Ok(vm_result)
                }
                Err(error) => Err(RuntimeError::from(error).boxed()),
            }
        },
    );
    let result = encode_destack_memory_protect_remap_result(context, result)?;
    Ok(result)
}

/// Register VM bindings for memory.
pub fn register_memory_vm_bindings(registry: &mut BindingRegistry, isolate: &mut Isolate) {
    {
        binding!(
            registry,
            isolate,
            MEMORY_ADVISE_ADVISE,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_ADVISE_ADVISE)?;

                    // decode args
                    let (address, length, advice) =
                        decode_destack_memory_advise_advise_args(context, args)?;

                    // execute binding
                    destack_memory_advise_advise_vm_replay(
                        runtime, context, address, length, advice,
                    )
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_ADVISE_DISCARD,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_ADVISE_DISCARD)?;

                    // decode args
                    let (address, length) =
                        decode_destack_memory_advise_discard_args(context, args)?;

                    // execute binding
                    destack_memory_advise_discard_vm_replay(runtime, context, address, length)
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_ADVISE_HUGE_PAGE,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_ADVISE_HUGE_PAGE)?;

                    // decode args
                    let (address, length, enabled) =
                        decode_destack_memory_advise_huge_page_args(context, args)?;

                    // execute binding
                    destack_memory_advise_huge_page_vm_replay(
                        runtime, context, address, length, enabled,
                    )
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(registry, isolate, MEMORY_LOCK_LOCK, move |context, args| {
            with_runtime_call_context(|runtime| {
                // policy
                runtime.check_policy(MEMORY_LOCK_LOCK)?;

                // decode args
                let (address, length) = decode_destack_memory_lock_lock_args(context, args)?;

                // execute binding
                destack_memory_lock_lock_vm_replay(runtime, context, address, length)
            })
            .map_err(Into::into)
        });
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_LOCK_UNLOCK,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_LOCK_UNLOCK)?;

                    // decode args
                    let (address, length) = decode_destack_memory_lock_unlock_args(context, args)?;

                    // execute binding
                    destack_memory_lock_unlock_vm_replay(runtime, context, address, length)
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_MAP_COMMIT,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_MAP_COMMIT)?;

                    // decode args
                    let (address, length, flags) =
                        decode_destack_memory_map_commit_args(context, args)?;

                    // execute binding
                    destack_memory_map_commit_vm_replay(runtime, context, address, length, flags)
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_MAP_DECOMMIT,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_MAP_DECOMMIT)?;

                    // decode args
                    let (address, length) = decode_destack_memory_map_decommit_args(context, args)?;

                    // execute binding
                    destack_memory_map_decommit_vm_replay(runtime, context, address, length)
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_MAP_NUMA_BIND,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_MAP_NUMA_BIND)?;

                    // decode args
                    let (address, length, policy, nodemask) =
                        decode_destack_memory_map_numa_bind_args(context, args)?;

                    // execute binding
                    destack_memory_map_numa_bind_vm_replay(
                        runtime, context, address, length, policy, nodemask,
                    )
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_MAP_RELEASE,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_MAP_RELEASE)?;

                    // decode args
                    let (address, length) = decode_destack_memory_map_release_args(context, args)?;

                    // execute binding
                    destack_memory_map_release_vm_replay(runtime, context, address, length)
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_MAP_RESERVE,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_MAP_RESERVE)?;

                    // decode args
                    let (length, flags) = decode_destack_memory_map_reserve_args(context, args)?;

                    // execute binding
                    destack_memory_map_reserve_vm_replay(runtime, context, length, flags)
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_PROTECT_EXECUTE,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_PROTECT_EXECUTE)?;

                    // decode args
                    let (address, length, enabled) =
                        decode_destack_memory_protect_execute_args(context, args)?;

                    // execute binding
                    destack_memory_protect_execute_vm_replay(
                        runtime, context, address, length, enabled,
                    )
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_PROTECT_FLUSH_INSTRUCTION_CACHE,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_PROTECT_FLUSH_INSTRUCTION_CACHE)?;

                    // decode args
                    let (address, length) =
                        decode_destack_memory_protect_flush_instruction_cache_args(context, args)?;

                    // execute binding
                    destack_memory_protect_flush_instruction_cache_vm_replay(
                        runtime, context, address, length,
                    )
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_PROTECT_PROTECT,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_PROTECT_PROTECT)?;

                    // decode args
                    let (address, length, protection) =
                        decode_destack_memory_protect_protect_args(context, args)?;

                    // execute binding
                    destack_memory_protect_protect_vm_replay(
                        runtime, context, address, length, protection,
                    )
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_PROTECT_REMAP,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_PROTECT_REMAP)?;

                    // decode args
                    let (address, oldlength, newlength, flags) =
                        decode_destack_memory_protect_remap_args(context, args)?;

                    // execute binding
                    destack_memory_protect_remap_vm_replay(
                        runtime, context, address, oldlength, newlength, flags,
                    )
                })
                .map_err(Into::into)
            }
        );
    }
    {
        binding!(
            registry,
            isolate,
            MEMORY_PROTECT_SET_WRITE_XOR_EXECUTE,
            move |context, args| {
                with_runtime_call_context(|runtime| {
                    // policy
                    runtime.check_policy(MEMORY_PROTECT_SET_WRITE_XOR_EXECUTE)?;

                    // decode args
                    let (enabled,) =
                        decode_destack_memory_protect_set_write_xor_execute_args(context, args)?;

                    // execute binding
                    let result = platform_vm::destack_memory_set_write_xor_execute(
                        runtime, context, enabled,
                    );
                    encode_destack_memory_protect_set_write_xor_execute_result(context, result)
                })
                .map_err(Into::into)
            }
        );
    }
}

/// Install VM bindings for memory.
pub fn install_memory_vm_bindings(registry: &mut BindingRegistry, isolate: &mut Isolate) {
    register_memory_vm_bindings(registry, isolate);
}

vm_binding_set!(pub MEMORY_VM_BINDINGS, "memory", install_memory_vm_bindings);
