/* generated by destack_client_generate, do not edit */

import {
    BinaryReader,
    BinaryWriter,
    Json,
    SerdeError,
    jsonArray,
    jsonBool,
    jsonField,
    jsonInteger,
    jsonObject,
    jsonOptional,
    jsonString,
} from "../../../protocol/serde.js";
import type { StringId } from "../../core/string.js";
import type { LocalNodeId } from "../tree/node.js";
import {
    decodeStringId,
    encodeStringId,
    fromJsonStringId,
    toJsonStringId,
} from "../../core/string.js";
import {
    decodeLocalNodeId,
    encodeLocalNodeId,
    fromJsonLocalNodeId,
    toJsonLocalNodeId,
} from "../tree/node.js";

/** Slot index inside a dispatch table. */
export type DispatchSlot = number;

export const DispatchSlot = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: DispatchSlot): void {
        encodeDispatchSlot(writer, value);
    },

    /** Decode one DispatchSlot. */
    decode(reader: BinaryReader): DispatchSlot {
        return decodeDispatchSlot(reader);
    },

    /** Return this value as JSON. */
    toJson(value: DispatchSlot): Json {
        return toJsonDispatchSlot(value);
    },

    /** Return one DispatchSlot from one JSON value. */
    fromJson(value: Json): DispatchSlot {
        return fromJsonDispatchSlot(value);
    },
};

/** Encode one DispatchSlot. */
export function encodeDispatchSlot(writer: BinaryWriter, value: DispatchSlot): void {
    writer.writeUnsigned(value);
}

/** Decode one DispatchSlot. */
export function decodeDispatchSlot(reader: BinaryReader): DispatchSlot {
    return reader.readNumber();
}

/** Return one JSON value for one DispatchSlot. */
export function toJsonDispatchSlot(value: DispatchSlot): Json {
    return value;
}

/** Return one DispatchSlot from one JSON value. */
export function fromJsonDispatchSlot(value: Json): DispatchSlot {
    return jsonInteger(value);
}

/** Canonical dispatch table for one MIR module. */
export type DispatchTable = {
    /** Virtual dispatch tables. */
    readonly virtualTables: ReadonlyArray<VirtualTable>;
    /** Dynamic dispatch tables. */
    readonly dynamicTables: ReadonlyArray<DynamicTable>;
    /** Dynamic dispatch shapes keyed by constraint type id. */
    readonly dynamicShapes: ReadonlyArray<DynamicShape>;
};

export const DispatchTable = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: DispatchTable): void {
        encodeDispatchTable(writer, value);
    },

    /** Decode one DispatchTable. */
    decode(reader: BinaryReader): DispatchTable {
        return decodeDispatchTable(reader);
    },

    /** Return this value as JSON. */
    toJson(value: DispatchTable): Json {
        return toJsonDispatchTable(value);
    },

    /** Return one DispatchTable from one JSON value. */
    fromJson(value: Json): DispatchTable {
        return fromJsonDispatchTable(value);
    },
};

/** Encode one DispatchTable. */
export function encodeDispatchTable(writer: BinaryWriter, value: DispatchTable): void {
    writer.writeUnsigned(value.virtualTables.length);
    for (const item0 of value.virtualTables) {
        encodeVirtualTable(writer, item0);
    }
    writer.writeUnsigned(value.dynamicTables.length);
    for (const item1 of value.dynamicTables) {
        encodeDynamicTable(writer, item1);
    }
    writer.writeUnsigned(value.dynamicShapes.length);
    for (const item2 of value.dynamicShapes) {
        encodeDynamicShape(writer, item2);
    }
}

/** Decode one DispatchTable. */
export function decodeDispatchTable(reader: BinaryReader): DispatchTable {
    const virtualTables = (() => {
        const length0 = reader.readNumber();
        const items0: Array<VirtualTable> = [];
        for (let index = 0; index < length0; index += 1) {
            items0.push(decodeVirtualTable(reader));
        }
        return items0;
    })();
    const dynamicTables = (() => {
        const length1 = reader.readNumber();
        const items1: Array<DynamicTable> = [];
        for (let index = 0; index < length1; index += 1) {
            items1.push(decodeDynamicTable(reader));
        }
        return items1;
    })();
    const dynamicShapes = (() => {
        const length2 = reader.readNumber();
        const items2: Array<DynamicShape> = [];
        for (let index = 0; index < length2; index += 1) {
            items2.push(decodeDynamicShape(reader));
        }
        return items2;
    })();

    return {
        virtualTables,
        dynamicTables,
        dynamicShapes,
    };
}

/** Return one JSON value for one DispatchTable. */
export function toJsonDispatchTable(value: DispatchTable): Json {
    return {
        virtualTables: value.virtualTables.map((item0) => toJsonVirtualTable(item0)),
        dynamicTables: value.dynamicTables.map((item0) => toJsonDynamicTable(item0)),
        dynamicShapes: value.dynamicShapes.map((item0) => toJsonDynamicShape(item0)),
    };
}

/** Return one DispatchTable from one JSON value. */
export function fromJsonDispatchTable(value: Json): DispatchTable {
    const object = jsonObject(value);

    return {
        virtualTables: jsonArray(jsonField(object, "virtualTables")).map((item0) =>
            fromJsonVirtualTable(item0),
        ),
        dynamicTables: jsonArray(jsonField(object, "dynamicTables")).map((item0) =>
            fromJsonDynamicTable(item0),
        ),
        dynamicShapes: jsonArray(jsonField(object, "dynamicShapes")).map((item0) =>
            fromJsonDynamicShape(item0),
        ),
    };
}

/** Entry in a dynamic dispatch table. */
export type DynamicEntry =
    /** Slot containing a field offset. */
    | {
          readonly kind: "field";
          /** The field offset in bytes. */
          readonly offset: number;
      }
    /** Slot containing a concrete function implementation. */
    | {
          readonly kind: "function";
          /** The concrete function implementation. */
          readonly function: LocalNodeId;
      }
    /** Slot without a concrete member, read as undefined. */
    | {
          readonly kind: "absent";
      };

export const DynamicEntry = {
    /** Slot containing a field offset. */
    field(offset: number): DynamicEntry {
        return { kind: "field", offset };
    },

    /** Slot containing a concrete function implementation. */
    function(function_: LocalNodeId): DynamicEntry {
        return { kind: "function", function: function_ };
    },

    /** Slot without a concrete member, read as undefined. */
    absent(): DynamicEntry {
        return { kind: "absent" };
    },

    /** Encode this value. */
    encode(writer: BinaryWriter, value: DynamicEntry): void {
        encodeDynamicEntry(writer, value);
    },

    /** Decode one DynamicEntry. */
    decode(reader: BinaryReader): DynamicEntry {
        return decodeDynamicEntry(reader);
    },

    /** Return this value as JSON. */
    toJson(value: DynamicEntry): Json {
        return toJsonDynamicEntry(value);
    },

    /** Return one DynamicEntry from one JSON value. */
    fromJson(value: Json): DynamicEntry {
        return fromJsonDynamicEntry(value);
    },
};

/** Encode one DynamicEntry. */
export function encodeDynamicEntry(writer: BinaryWriter, value: DynamicEntry): void {
    switch (value.kind) {
        case "field":
            writer.writeUnsigned(0);
            writer.writeUnsigned(value.offset);
            return;
        case "function":
            writer.writeUnsigned(1);
            encodeLocalNodeId(writer, value.function);
            return;
        case "absent":
            writer.writeUnsigned(2);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one DynamicEntry. */
export function decodeDynamicEntry(reader: BinaryReader): DynamicEntry {
    const variant = reader.readNumber();

    switch (variant) {
        case 0: {
            const offset = reader.readNumber();

            return {
                kind: "field",
                offset,
            };
        }
        case 1: {
            const function_ = decodeLocalNodeId(reader);

            return {
                kind: "function",
                function: function_,
            };
        }
        case 2: {
            return { kind: "absent" };
        }
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one DynamicEntry. */
export function toJsonDynamicEntry(value: DynamicEntry): Json {
    switch (value.kind) {
        case "field":
            return {
                kind: "field",
                offset: value.offset,
            };
        case "function":
            return {
                kind: "function",
                function: toJsonLocalNodeId(value.function),
            };
        case "absent":
            return {
                kind: "absent",
            };
    }

    throw new SerdeError("unknown enum variant");
}

/** Return one DynamicEntry from one JSON value. */
export function fromJsonDynamicEntry(value: Json): DynamicEntry {
    const object = jsonObject(value);
    const kind = jsonString(jsonField(object, "kind"));

    switch (kind) {
        case "field":
            return {
                kind,
                offset: jsonInteger(jsonField(object, "offset")),
            };
        case "function":
            return {
                kind,
                function: fromJsonLocalNodeId(jsonField(object, "function")),
            };
        case "absent":
            return {
                kind,
            };
    }

    throw new SerdeError(`unknown enum variant: ${kind}`);
}

/** One name-keyed entry in a dynamic dispatch table. */
export type DynamicNamedEntry = {
    /** The concrete field name. */
    readonly name: StringId;
    /** The entry backing the name. */
    readonly entry: DynamicEntry;
};

export const DynamicNamedEntry = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: DynamicNamedEntry): void {
        encodeDynamicNamedEntry(writer, value);
    },

    /** Decode one DynamicNamedEntry. */
    decode(reader: BinaryReader): DynamicNamedEntry {
        return decodeDynamicNamedEntry(reader);
    },

    /** Return this value as JSON. */
    toJson(value: DynamicNamedEntry): Json {
        return toJsonDynamicNamedEntry(value);
    },

    /** Return one DynamicNamedEntry from one JSON value. */
    fromJson(value: Json): DynamicNamedEntry {
        return fromJsonDynamicNamedEntry(value);
    },
};

/** Encode one DynamicNamedEntry. */
export function encodeDynamicNamedEntry(writer: BinaryWriter, value: DynamicNamedEntry): void {
    encodeStringId(writer, value.name);
    encodeDynamicEntry(writer, value.entry);
}

/** Decode one DynamicNamedEntry. */
export function decodeDynamicNamedEntry(reader: BinaryReader): DynamicNamedEntry {
    const name = decodeStringId(reader);
    const entry = decodeDynamicEntry(reader);

    return {
        name,
        entry,
    };
}

/** Return one JSON value for one DynamicNamedEntry. */
export function toJsonDynamicNamedEntry(value: DynamicNamedEntry): Json {
    return {
        name: toJsonStringId(value.name),
        entry: toJsonDynamicEntry(value.entry),
    };
}

/** Return one DynamicNamedEntry from one JSON value. */
export function fromJsonDynamicNamedEntry(value: Json): DynamicNamedEntry {
    const object = jsonObject(value);

    return {
        name: fromJsonStringId(jsonField(object, "name")),
        entry: fromJsonDynamicEntry(jsonField(object, "entry")),
    };
}

/** Table shape for one dynamic constraint. */
export type DynamicShape = {
    /** The dynamic constraint type owning this shape. */
    readonly constraint: LocalNodeId;
    /** Slots in declaration order. */
    readonly slots: ReadonlyArray<DynamicSlot>;
    /** Whether the constraint answers keyed finds by field name. */
    readonly isKeyed: boolean;
};

export const DynamicShape = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: DynamicShape): void {
        encodeDynamicShape(writer, value);
    },

    /** Decode one DynamicShape. */
    decode(reader: BinaryReader): DynamicShape {
        return decodeDynamicShape(reader);
    },

    /** Return this value as JSON. */
    toJson(value: DynamicShape): Json {
        return toJsonDynamicShape(value);
    },

    /** Return one DynamicShape from one JSON value. */
    fromJson(value: Json): DynamicShape {
        return fromJsonDynamicShape(value);
    },
};

/** Encode one DynamicShape. */
export function encodeDynamicShape(writer: BinaryWriter, value: DynamicShape): void {
    encodeLocalNodeId(writer, value.constraint);
    writer.writeUnsigned(value.slots.length);
    for (const item1 of value.slots) {
        encodeDynamicSlot(writer, item1);
    }
    writer.writeBool(value.isKeyed);
}

/** Decode one DynamicShape. */
export function decodeDynamicShape(reader: BinaryReader): DynamicShape {
    const constraint = decodeLocalNodeId(reader);
    const slots = (() => {
        const length1 = reader.readNumber();
        const items1: Array<DynamicSlot> = [];
        for (let index = 0; index < length1; index += 1) {
            items1.push(decodeDynamicSlot(reader));
        }
        return items1;
    })();
    const isKeyed = reader.readBool();

    return {
        constraint,
        slots,
        isKeyed,
    };
}

/** Return one JSON value for one DynamicShape. */
export function toJsonDynamicShape(value: DynamicShape): Json {
    return {
        constraint: toJsonLocalNodeId(value.constraint),
        slots: value.slots.map((item0) => toJsonDynamicSlot(item0)),
        isKeyed: value.isKeyed,
    };
}

/** Return one DynamicShape from one JSON value. */
export function fromJsonDynamicShape(value: Json): DynamicShape {
    const object = jsonObject(value);

    return {
        constraint: fromJsonLocalNodeId(jsonField(object, "constraint")),
        slots: jsonArray(jsonField(object, "slots")).map((item0) => fromJsonDynamicSlot(item0)),
        isKeyed: jsonBool(jsonField(object, "isKeyed")),
    };
}

/** Slot descriptor for a dynamic shape. */
export type DynamicSlot =
    /** Field slot. */
    | {
          readonly kind: "field";
          /** The canonical dispatch field id. */
          readonly field: LocalNodeId;
          /** The field name. */
          readonly name: StringId;
      }
    /** Function slot. */
    | {
          readonly kind: "function";
          /** The function name, absent for call signatures. */
          readonly name?: StringId;
          /** The function signature. */
          readonly signature: LocalNodeId;
      };

export const DynamicSlot = {
    /** Field slot. */
    field(field: LocalNodeId, name: StringId): DynamicSlot {
        return { kind: "field", field, name };
    },

    /** Function slot. */
    function(name: StringId | undefined, signature: LocalNodeId): DynamicSlot {
        return { kind: "function", name, signature };
    },

    /** Encode this value. */
    encode(writer: BinaryWriter, value: DynamicSlot): void {
        encodeDynamicSlot(writer, value);
    },

    /** Decode one DynamicSlot. */
    decode(reader: BinaryReader): DynamicSlot {
        return decodeDynamicSlot(reader);
    },

    /** Return this value as JSON. */
    toJson(value: DynamicSlot): Json {
        return toJsonDynamicSlot(value);
    },

    /** Return one DynamicSlot from one JSON value. */
    fromJson(value: Json): DynamicSlot {
        return fromJsonDynamicSlot(value);
    },
};

/** Encode one DynamicSlot. */
export function encodeDynamicSlot(writer: BinaryWriter, value: DynamicSlot): void {
    switch (value.kind) {
        case "field":
            writer.writeUnsigned(0);
            encodeLocalNodeId(writer, value.field);
            encodeStringId(writer, value.name);
            return;
        case "function":
            writer.writeUnsigned(1);
            writer.writeOption(value.name, (value0) => {
                encodeStringId(writer, value0);
            });
            encodeLocalNodeId(writer, value.signature);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one DynamicSlot. */
export function decodeDynamicSlot(reader: BinaryReader): DynamicSlot {
    const variant = reader.readNumber();

    switch (variant) {
        case 0: {
            const field = decodeLocalNodeId(reader);
            const name = decodeStringId(reader);

            return {
                kind: "field",
                field,
                name,
            };
        }
        case 1: {
            const name = reader.readOption(() => decodeStringId(reader));
            const signature = decodeLocalNodeId(reader);

            return {
                kind: "function",
                ...(name === undefined ? {} : { name }),
                signature,
            };
        }
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one DynamicSlot. */
export function toJsonDynamicSlot(value: DynamicSlot): Json {
    switch (value.kind) {
        case "field":
            return {
                kind: "field",
                field: toJsonLocalNodeId(value.field),
                name: toJsonStringId(value.name),
            };
        case "function":
            return {
                kind: "function",
                ...(value.name === undefined ? {} : { name: toJsonStringId(value.name) }),
                signature: toJsonLocalNodeId(value.signature),
            };
    }

    throw new SerdeError("unknown enum variant");
}

/** Return one DynamicSlot from one JSON value. */
export function fromJsonDynamicSlot(value: Json): DynamicSlot {
    const object = jsonObject(value);
    const kind = jsonString(jsonField(object, "kind"));

    switch (kind) {
        case "field":
            return {
                kind,
                field: fromJsonLocalNodeId(jsonField(object, "field")),
                name: fromJsonStringId(jsonField(object, "name")),
            };
        case "function":
            return {
                kind,
                name: jsonOptional(object, "name", (value) => fromJsonStringId(value)),
                signature: fromJsonLocalNodeId(jsonField(object, "signature")),
            };
    }

    throw new SerdeError(`unknown enum variant: ${kind}`);
}

/** Table for one concrete implementation of one dynamic constraint. */
export type DynamicTable = {
    /** The concrete type providing the implementation. */
    readonly concrete: LocalNodeId;
    /** The dynamic constraint type being dispatched. */
    readonly constraint: LocalNodeId;
    /** Entries in dynamic shape order. */
    readonly entries: ReadonlyArray<DynamicEntry>;
    /** The concrete field entries sorted by name for keyed finds. */
    readonly names: ReadonlyArray<DynamicNamedEntry>;
};

export const DynamicTable = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: DynamicTable): void {
        encodeDynamicTable(writer, value);
    },

    /** Decode one DynamicTable. */
    decode(reader: BinaryReader): DynamicTable {
        return decodeDynamicTable(reader);
    },

    /** Return this value as JSON. */
    toJson(value: DynamicTable): Json {
        return toJsonDynamicTable(value);
    },

    /** Return one DynamicTable from one JSON value. */
    fromJson(value: Json): DynamicTable {
        return fromJsonDynamicTable(value);
    },
};

/** Encode one DynamicTable. */
export function encodeDynamicTable(writer: BinaryWriter, value: DynamicTable): void {
    encodeLocalNodeId(writer, value.concrete);
    encodeLocalNodeId(writer, value.constraint);
    writer.writeUnsigned(value.entries.length);
    for (const item2 of value.entries) {
        encodeDynamicEntry(writer, item2);
    }
    writer.writeUnsigned(value.names.length);
    for (const item3 of value.names) {
        encodeDynamicNamedEntry(writer, item3);
    }
}

/** Decode one DynamicTable. */
export function decodeDynamicTable(reader: BinaryReader): DynamicTable {
    const concrete = decodeLocalNodeId(reader);
    const constraint = decodeLocalNodeId(reader);
    const entries = (() => {
        const length2 = reader.readNumber();
        const items2: Array<DynamicEntry> = [];
        for (let index = 0; index < length2; index += 1) {
            items2.push(decodeDynamicEntry(reader));
        }
        return items2;
    })();
    const names = (() => {
        const length3 = reader.readNumber();
        const items3: Array<DynamicNamedEntry> = [];
        for (let index = 0; index < length3; index += 1) {
            items3.push(decodeDynamicNamedEntry(reader));
        }
        return items3;
    })();

    return {
        concrete,
        constraint,
        entries,
        names,
    };
}

/** Return one JSON value for one DynamicTable. */
export function toJsonDynamicTable(value: DynamicTable): Json {
    return {
        concrete: toJsonLocalNodeId(value.concrete),
        constraint: toJsonLocalNodeId(value.constraint),
        entries: value.entries.map((item0) => toJsonDynamicEntry(item0)),
        names: value.names.map((item0) => toJsonDynamicNamedEntry(item0)),
    };
}

/** Return one DynamicTable from one JSON value. */
export function fromJsonDynamicTable(value: Json): DynamicTable {
    const object = jsonObject(value);

    return {
        concrete: fromJsonLocalNodeId(jsonField(object, "concrete")),
        constraint: fromJsonLocalNodeId(jsonField(object, "constraint")),
        entries: jsonArray(jsonField(object, "entries")).map((item0) =>
            fromJsonDynamicEntry(item0),
        ),
        names: jsonArray(jsonField(object, "names")).map((item0) =>
            fromJsonDynamicNamedEntry(item0),
        ),
    };
}

/** Virtual method table for one concrete type. */
export type VirtualTable = {
    /** The concrete type owning this table. */
    readonly concrete: LocalNodeId;
    /** Method implementations in virtual slot order. */
    readonly methods: ReadonlyArray<LocalNodeId>;
};

export const VirtualTable = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: VirtualTable): void {
        encodeVirtualTable(writer, value);
    },

    /** Decode one VirtualTable. */
    decode(reader: BinaryReader): VirtualTable {
        return decodeVirtualTable(reader);
    },

    /** Return this value as JSON. */
    toJson(value: VirtualTable): Json {
        return toJsonVirtualTable(value);
    },

    /** Return one VirtualTable from one JSON value. */
    fromJson(value: Json): VirtualTable {
        return fromJsonVirtualTable(value);
    },
};

/** Encode one VirtualTable. */
export function encodeVirtualTable(writer: BinaryWriter, value: VirtualTable): void {
    encodeLocalNodeId(writer, value.concrete);
    writer.writeUnsigned(value.methods.length);
    for (const item1 of value.methods) {
        encodeLocalNodeId(writer, item1);
    }
}

/** Decode one VirtualTable. */
export function decodeVirtualTable(reader: BinaryReader): VirtualTable {
    const concrete = decodeLocalNodeId(reader);
    const methods = (() => {
        const length1 = reader.readNumber();
        const items1: Array<LocalNodeId> = [];
        for (let index = 0; index < length1; index += 1) {
            items1.push(decodeLocalNodeId(reader));
        }
        return items1;
    })();

    return {
        concrete,
        methods,
    };
}

/** Return one JSON value for one VirtualTable. */
export function toJsonVirtualTable(value: VirtualTable): Json {
    return {
        concrete: toJsonLocalNodeId(value.concrete),
        methods: value.methods.map((item0) => toJsonLocalNodeId(item0)),
    };
}

/** Return one VirtualTable from one JSON value. */
export function fromJsonVirtualTable(value: Json): VirtualTable {
    const object = jsonObject(value);

    return {
        concrete: fromJsonLocalNodeId(jsonField(object, "concrete")),
        methods: jsonArray(jsonField(object, "methods")).map((item0) => fromJsonLocalNodeId(item0)),
    };
}
