/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, SerdeError, compareBytes, jsonArray, jsonField, jsonObject, jsonString, nestedBytes } from "../../../protocol/serde.js";
import type { DispatchSlot } from "./dispatch.js";
import type { LocalNodeId } from "../tree/node.js";
import { decodeDispatchSlot, encodeDispatchSlot, fromJsonDispatchSlot, toJsonDispatchSlot } from "./dispatch.js";
import { decodeLocalNodeId, encodeLocalNodeId, fromJsonLocalNodeId, toJsonLocalNodeId } from "../tree/node.js";

/** Drop table for one MIR module. */
export type DropTable = {
    /** Full drop glue keyed by type id. */
    readonly glueByType: ReadonlyMap<LocalNodeId, DropGlue>;
    /** User-authored drop hooks keyed by type id. */
    readonly hooksByType: ReadonlyMap<LocalNodeId, DropHook>;
};

export const DropTable = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: DropTable): void {
        encodeDropTable(writer, value);
    },

    /** Decode one DropTable. */
    decode(reader: BinaryReader): DropTable {
        return decodeDropTable(reader);
    },

    /** Return this value as JSON. */
    toJson(value: DropTable): Json {
        return toJsonDropTable(value);
    },

    /** Return one DropTable from one JSON value. */
    fromJson(value: Json): DropTable {
        return fromJsonDropTable(value);
    },
};

/** Encode one DropTable. */
export function encodeDropTable(writer: BinaryWriter, value: DropTable): void {
    const entries0 = Array.from(value.glueByType.entries()).map(([key0, item0]) => {
        const keyBytes = nestedBytes((writer) => {
            encodeLocalNodeId(writer, key0);
        });
        return { key0, item0, keyBytes };
    });
    entries0.sort((left, right) => compareBytes(left.keyBytes, right.keyBytes));
    writer.writeUnsigned(entries0.length);
    for (const entry0 of entries0) {
        encodeLocalNodeId(writer, entry0.key0);
        encodeDropGlue(writer, entry0.item0);
    }
    const entries1 = Array.from(value.hooksByType.entries()).map(([key1, item1]) => {
        const keyBytes = nestedBytes((writer) => {
            encodeLocalNodeId(writer, key1);
        });
        return { key1, item1, keyBytes };
    });
    entries1.sort((left, right) => compareBytes(left.keyBytes, right.keyBytes));
    writer.writeUnsigned(entries1.length);
    for (const entry1 of entries1) {
        encodeLocalNodeId(writer, entry1.key1);
        encodeDropHook(writer, entry1.item1);
    }
}

/** Decode one DropTable. */
export function decodeDropTable(reader: BinaryReader): DropTable {
    const glueByType = (() => { const length0 = reader.readNumber(); const items0 = new Map<LocalNodeId, DropGlue>(); for (let index = 0; index < length0; index += 1) { items0.set(decodeLocalNodeId(reader), decodeDropGlue(reader)); } return items0; })();
    const hooksByType = (() => { const length1 = reader.readNumber(); const items1 = new Map<LocalNodeId, DropHook>(); for (let index = 0; index < length1; index += 1) { items1.set(decodeLocalNodeId(reader), decodeDropHook(reader)); } return items1; })();

    return {
        glueByType,
        hooksByType,
    };
}

/** Return one JSON value for one DropTable. */
export function toJsonDropTable(value: DropTable): Json {
    return {
        glueByType: Array.from(value.glueByType.entries()).map(([key0, item0]) => [toJsonLocalNodeId(key0), toJsonDropGlue(item0)] as const),
        hooksByType: Array.from(value.hooksByType.entries()).map(([key0, item0]) => [toJsonLocalNodeId(key0), toJsonDropHook(item0)] as const),
    };
}

/** Return one DropTable from one JSON value. */
export function fromJsonDropTable(value: Json): DropTable {
    const object = jsonObject(value);

    return {
        glueByType: new Map(jsonArray(jsonField(object, "glueByType")).map((entry) => { const items = jsonArray(entry); if (items.length !== 2) { throw new SerdeError(`expected JSON map entry length 2: ${items.length}`); } const key0 = items[0]; const item0 = items[1]; return [fromJsonLocalNodeId(key0), fromJsonDropGlue(item0)] as const; })),
        hooksByType: new Map(jsonArray(jsonField(object, "hooksByType")).map((entry) => { const items = jsonArray(entry); if (items.length !== 2) { throw new SerdeError(`expected JSON map entry length 2: ${items.length}`); } const key0 = items[0]; const item0 = items[1]; return [fromJsonLocalNodeId(key0), fromJsonDropHook(item0)] as const; })),
    };
}

/** Full drop glue selected for one MIR type. */
export type DropGlue =
    /** No drop glue is required. */
    | {
          readonly kind: "none";
      }
    /** Call compiler-generated drop glue. */
    | {
          readonly kind: "generated";
          /** The drop function. */
          readonly function: LocalNodeId;
      }
    /** Dispatch through a runtime drop slot. */
    | {
          readonly kind: "dynamic";
          /** The drop dispatch slot. */
          readonly slot: DispatchSlot;
      }
;

export const DropGlue = {
    /** No drop glue is required. */
    none(): DropGlue {
        return { kind: "none" };
    },

    /** Call compiler-generated drop glue. */
    generated(function_: LocalNodeId): DropGlue {
        return { kind: "generated", function: function_ };
    },

    /** Dispatch through a runtime drop slot. */
    dynamic(slot: DispatchSlot): DropGlue {
        return { kind: "dynamic", slot };
    },

    /** Encode this value. */
    encode(writer: BinaryWriter, value: DropGlue): void {
        encodeDropGlue(writer, value);
    },

    /** Decode one DropGlue. */
    decode(reader: BinaryReader): DropGlue {
        return decodeDropGlue(reader);
    },

    /** Return this value as JSON. */
    toJson(value: DropGlue): Json {
        return toJsonDropGlue(value);
    },

    /** Return one DropGlue from one JSON value. */
    fromJson(value: Json): DropGlue {
        return fromJsonDropGlue(value);
    },
};

/** Encode one DropGlue. */
export function encodeDropGlue(writer: BinaryWriter, value: DropGlue): void {
    switch (value.kind) {
        case "none":
            writer.writeUnsigned(0);
            return;
        case "generated":
            writer.writeUnsigned(1);
            encodeLocalNodeId(writer, value.function);
            return;
        case "dynamic":
            writer.writeUnsigned(2);
            encodeDispatchSlot(writer, value.slot);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one DropGlue. */
export function decodeDropGlue(reader: BinaryReader): DropGlue {
    const variant = reader.readNumber();

    switch (variant) {
        case 0: {
            return { kind: "none" };
        }
        case 1: {
            const function_ = decodeLocalNodeId(reader);

            return {
                kind: "generated",
                function: function_,
            };
        }
        case 2: {
            const slot = decodeDispatchSlot(reader);

            return {
                kind: "dynamic",
                slot,
            };
        }
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one DropGlue. */
export function toJsonDropGlue(value: DropGlue): Json {
    switch (value.kind) {
        case "none":
            return {
                kind: "none",
            };
        case "generated":
            return {
                kind: "generated",
                function: toJsonLocalNodeId(value.function),
            };
        case "dynamic":
            return {
                kind: "dynamic",
                slot: toJsonDispatchSlot(value.slot),
            };
    }

    throw new SerdeError("unknown enum variant");
}

/** Return one DropGlue from one JSON value. */
export function fromJsonDropGlue(value: Json): DropGlue {
    const object = jsonObject(value);
    const kind = jsonString(jsonField(object, "kind"));

    switch (kind) {
        case "none":
            return {
                kind,
            };
        case "generated":
            return {
                kind,
                function: fromJsonLocalNodeId(jsonField(object, "function")),
            };
        case "dynamic":
            return {
                kind,
                slot: fromJsonDispatchSlot(jsonField(object, "slot")),
            };
    }

    throw new SerdeError(`unknown enum variant: ${kind}`);
}

/** User-authored drop hook for one MIR type. */
export type DropHook = {
    /** The hook function. */
    readonly function: LocalNodeId;
};

export const DropHook = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: DropHook): void {
        encodeDropHook(writer, value);
    },

    /** Decode one DropHook. */
    decode(reader: BinaryReader): DropHook {
        return decodeDropHook(reader);
    },

    /** Return this value as JSON. */
    toJson(value: DropHook): Json {
        return toJsonDropHook(value);
    },

    /** Return one DropHook from one JSON value. */
    fromJson(value: Json): DropHook {
        return fromJsonDropHook(value);
    },
};

/** Encode one DropHook. */
export function encodeDropHook(writer: BinaryWriter, value: DropHook): void {
    encodeLocalNodeId(writer, value.function);
}

/** Decode one DropHook. */
export function decodeDropHook(reader: BinaryReader): DropHook {
    const function_ = decodeLocalNodeId(reader);

    return {
        function: function_,
    };
}

/** Return one JSON value for one DropHook. */
export function toJsonDropHook(value: DropHook): Json {
    return {
        function: toJsonLocalNodeId(value.function),
    };
}

/** Return one DropHook from one JSON value. */
export function fromJsonDropHook(value: Json): DropHook {
    const object = jsonObject(value);

    return {
        function: fromJsonLocalNodeId(jsonField(object, "function")),
    };
}
