/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, SerdeError, jsonArray, jsonField, jsonObject, jsonString } from "../../../protocol/serde.js";
import type { Point } from "../tree/call.js";
import type { Value } from "../tree/value.js";
import { decodePoint, encodePoint, fromJsonPoint, toJsonPoint } from "../tree/call.js";
import { decodeValue, encodeValue, fromJsonValue, toJsonValue } from "../tree/value.js";

/** One point where the collector may run. */
export type Safepoint = {
    /** The point: a parking call, or a loop header or tail call that elaboration polls at. */
    readonly point: Point;
    /** How the collector gets to run at the point. */
    readonly kind: SafepointKind;
    /** The managed handles whose borrows are live at the point, held live past it. */
    readonly live: ReadonlyArray<Value>;
};

export const Safepoint = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: Safepoint): void {
        encodeSafepoint(writer, value);
    },

    /** Decode one Safepoint. */
    decode(reader: BinaryReader): Safepoint {
        return decodeSafepoint(reader);
    },

    /** Return this value as JSON. */
    toJson(value: Safepoint): Json {
        return toJsonSafepoint(value);
    },

    /** Return one Safepoint from one JSON value. */
    fromJson(value: Json): Safepoint {
        return fromJsonSafepoint(value);
    },
};

/** Encode one Safepoint. */
export function encodeSafepoint(writer: BinaryWriter, value: Safepoint): void {
    encodePoint(writer, value.point);
    encodeSafepointKind(writer, value.kind);
    writer.writeUnsigned(value.live.length);
    for (const item2 of value.live) {
        encodeValue(writer, item2);
    }
}

/** Decode one Safepoint. */
export function decodeSafepoint(reader: BinaryReader): Safepoint {
    const point = decodePoint(reader);
    const kind = decodeSafepointKind(reader);
    const live = (() => { const length2 = reader.readNumber(); const items2: Array<Value> = []; for (let index = 0; index < length2; index += 1) { items2.push(decodeValue(reader)); } return items2; })();

    return {
        point,
        kind,
        live,
    };
}

/** Return one JSON value for one Safepoint. */
export function toJsonSafepoint(value: Safepoint): Json {
    return {
        point: toJsonPoint(value.point),
        kind: toJsonSafepointKind(value.kind),
        live: value.live.map((item0) => toJsonValue(item0)),
    };
}

/** Return one Safepoint from one JSON value. */
export function fromJsonSafepoint(value: Json): Safepoint {
    const object = jsonObject(value);

    return {
        point: fromJsonPoint(jsonField(object, "point")),
        kind: fromJsonSafepointKind(jsonField(object, "kind")),
        live: jsonArray(jsonField(object, "live")).map((item0) => fromJsonValue(item0)),
    };
}

/** How the collector gets to run at one safepoint. */
export type SafepointKind = "park" | "poll";

export const SafepointKind = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: SafepointKind): void {
        encodeSafepointKind(writer, value);
    },

    /** Decode one SafepointKind. */
    decode(reader: BinaryReader): SafepointKind {
        return decodeSafepointKind(reader);
    },

    /** Return this value as JSON. */
    toJson(value: SafepointKind): Json {
        return toJsonSafepointKind(value);
    },

    /** Return one SafepointKind from one JSON value. */
    fromJson(value: Json): SafepointKind {
        return fromJsonSafepointKind(value);
    },
};

/** Encode one SafepointKind. */
export function encodeSafepointKind(writer: BinaryWriter, value: SafepointKind): void {
    switch (value) {
        case "park":
            writer.writeUnsigned(0);
            return;
        case "poll":
            writer.writeUnsigned(1);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one SafepointKind. */
export function decodeSafepointKind(reader: BinaryReader): SafepointKind {
    const variant = reader.readNumber();

    switch (variant) {
        case 0:
            return "park";
        case 1:
            return "poll";
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one SafepointKind. */
export function toJsonSafepointKind(value: SafepointKind): Json {
    return value;
}

/** Return one SafepointKind from one JSON value. */
export function fromJsonSafepointKind(value: Json): SafepointKind {
    const variant = jsonString(value);

    switch (variant) {
        case "park":
            return "park";
        case "poll":
            return "poll";
    }

    throw new SerdeError(`unknown enum variant: ${variant}`);
}

/** The safepoints of verified MIR: the points where the collector may run, each with the handles held live there. */
export type SafepointTable = {
    /** The safepoints sorted by point. */
    readonly points: ReadonlyArray<Safepoint>;
};

export const SafepointTable = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: SafepointTable): void {
        encodeSafepointTable(writer, value);
    },

    /** Decode one SafepointTable. */
    decode(reader: BinaryReader): SafepointTable {
        return decodeSafepointTable(reader);
    },

    /** Return this value as JSON. */
    toJson(value: SafepointTable): Json {
        return toJsonSafepointTable(value);
    },

    /** Return one SafepointTable from one JSON value. */
    fromJson(value: Json): SafepointTable {
        return fromJsonSafepointTable(value);
    },
};

/** Encode one SafepointTable. */
export function encodeSafepointTable(writer: BinaryWriter, value: SafepointTable): void {
    writer.writeUnsigned(value.points.length);
    for (const item0 of value.points) {
        encodeSafepoint(writer, item0);
    }
}

/** Decode one SafepointTable. */
export function decodeSafepointTable(reader: BinaryReader): SafepointTable {
    const points = (() => { const length0 = reader.readNumber(); const items0: Array<Safepoint> = []; for (let index = 0; index < length0; index += 1) { items0.push(decodeSafepoint(reader)); } return items0; })();

    return {
        points,
    };
}

/** Return one JSON value for one SafepointTable. */
export function toJsonSafepointTable(value: SafepointTable): Json {
    return {
        points: value.points.map((item0) => toJsonSafepoint(item0)),
    };
}

/** Return one SafepointTable from one JSON value. */
export function fromJsonSafepointTable(value: Json): SafepointTable {
    const object = jsonObject(value);

    return {
        points: jsonArray(jsonField(object, "points")).map((item0) => fromJsonSafepoint(item0)),
    };
}
