syntax = "proto3";

package symbolx.bench;

import "proto/lang.proto";
import "google/protobuf/descriptor.proto";

enum ServiceKind {
  UNSPECIFIED = 0;
  INTERNAL = 1;
  PUBLIC = 2;
}

extend google.protobuf.ServiceOptions {
  ServiceKind kind = 50000;
}

extend google.protobuf.FieldOptions {
  // Field should never be printed in logs.
  optional bool sensitive = 50000;
}

// Core metadata for all RPC requests.
// This is passed as specially encoded headers with robust dicts,
// but it's nice to have a common definition.
// NOTE: update :RpcMetadataEncoding when changing RpcMetadata
message RpcMetadata {
  // Client
  optional ClientType client_type = 2;
  optional string client_id = 3;
  optional string client_nonce = 4;
  optional string client_access_token = 5;

  // Badges
  message BadgeInfo {
    optional string id = 2;
    optional string key = 3;
    optional string password = 4;
  }
  repeated BadgeInfo badges = 6;
}