syntax = "proto3";

package symbol.bench;

import "google/protobuf/struct.proto";
import "proto/common.proto";
import "proto/language.proto";

message QueryRequest {
  ScopeData scope = 1;
  // The Query to execute.
  QueryData query = 2;
}
message QueryResponse {
  // The result of the Query.
  QueryResultData result = 1;
}

message SubscribeRequest {
  QueryData query = 1;
}
message SubscribeResponse {
  // The result of the Query.
  QueryUpdateData update = 1;
}

message CommitRequest {
  ScopeData scope = 1;
  repeated ChangeData changes = 3;
}
message CommitResponse {
  uint64 epoch = 3;
  repeated ChangeResultData results = 4;
}

message UploadFilesRequest { 
  ScopeData scope = 1;
  repeated FileData files = 2;
}

message UploadFilesResponse {
  message UploadHandle {
    FileData file = 1;
    string post_url = 2;
    google.protobuf.Struct fields = 3;
    string get_url = 4;
  }
  repeated UploadHandle handles = 1; // handles for each valid file upload
}

message DownloadFilesRequest {
  ScopeData scope = 1;
  repeated NodeReferenceData files = 2;
}

message DownloadFilesResponse {
  message DownloadHandle {
    FileData file = 1;
    string get_url = 2;
  }
  repeated DownloadHandle handles = 1; // handles for each valid file download
}

// A Host provides the operating system of a Bench.
service Host {
  option (kind) = PUBLIC; // :ServiceKind
  
  //
  // Graph
  //

  rpc Query(QueryRequest) returns (QueryResponse);
  rpc Subscribe(SubscribeRequest) returns (stream SubscribeResponse);
  rpc Commit(CommitRequest) returns (CommitResponse);

  // 
  // Files? 
  //

  // 'Upload' some files (get URLs to upload them to). Handles may be incomplete.
  rpc UploadFiles(UploadFilesRequest) returns (UploadFilesResponse);
  // 'Download' some files (get URLs to download them from). Handles may be incomplete.
  rpc DownloadFiles(DownloadFilesRequest) returns (DownloadFilesResponse);
}
