syntax = "proto3";

package symbolx.bench;

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/struct.proto";

enum AccessKind {
  ACCESS_KIND_UNSPECIFIED = 0;
  ACCESS_KIND_READ = 1;
  ACCESS_KIND_EDIT = 20;
  ACCESS_KIND_USE = 40;
}

enum AccessMode {
  ACCESS_MODE_UNSPECIFIED = 0;
  ACCESS_MODE_ADAPTIVE = 1;
  ACCESS_MODE_ATOMIC = 2;
}

enum AccessType {
  ACCESS_TYPE_UNSPECIFIED = 0;
  ACCESS_TYPE_GET = 1;
  ACCESS_TYPE_SEARCH = 2;
  ACCESS_TYPE_AGGREGATE = 3;
  ACCESS_TYPE_CREATE = 20;
  ACCESS_TYPE_UPSERT = 21;
  ACCESS_TYPE_UPDATE = 22;
  ACCESS_TYPE_MOVE = 23;
  ACCESS_TYPE_ARCHIVE = 24;
  ACCESS_TYPE_UNARCHIVE = 25;
  ACCESS_TYPE_DELETE = 26;
  ACCESS_TYPE_RESTORE = 27;
  ACCESS_TYPE_ERASE = 28;
  ACCESS_TYPE_START = 40;
  ACCESS_TYPE_PAUSE = 41;
  ACCESS_TYPE_RESUME = 42;
  ACCESS_TYPE_STOP = 43;
  ACCESS_TYPE_KILL = 44;
  ACCESS_TYPE_SEND = 45;
  ACCESS_TYPE_RECEIVE = 46;
}

enum AggregationOp {
  AGGREGATION_OP_UNSPECIFIED = 0;
  AGGREGATION_OP_EXISTS = 400;
  AGGREGATION_OP_COUNT = 401;
  AGGREGATION_OP_SUM = 402;
  AGGREGATION_OP_MIN = 403;
  AGGREGATION_OP_MAX = 404;
  AGGREGATION_OP_AVERAGE = 405;
  AGGREGATION_OP_MEDIAN = 406;
  AGGREGATION_OP_HISTOGRAM = 407;
}

// How to align the contents/subviews of a view along its orientation.
enum Alignment {
  ALIGNMENT_UNSPECIFIED = 0;
  ALIGNMENT_START = 1;
  ALIGNMENT_MIDDLE = 2;
  ALIGNMENT_END = 3;
  ALIGNMENT_SPACE_BETWEEN = 4;
}

// An anchor in 2D space.
enum Anchor {
  ANCHOR_UNSPECIFIED = 0;
  ANCHOR_TOP = 1;
  ANCHOR_TOP_LEFT = 2;
  ANCHOR_TOP_RIGHT = 3;
  ANCHOR_RIGHT = 11;
  ANCHOR_RIGHT_TOP = 12;
  ANCHOR_RIGHT_BOTTOM = 13;
  ANCHOR_BOTTOM = 21;
  ANCHOR_BOTTOM_LEFT = 22;
  ANCHOR_BOTTOM_RIGHT = 23;
  ANCHOR_LEFT = 31;
  ANCHOR_LEFT_TOP = 32;
  ANCHOR_LEFT_BOTTOM = 33;
}

enum BenchType {
  BENCH_TYPE_UNSPECIFIED = 0;
  BENCH_TYPE_BENCH = 1;
  BENCH_TYPE_USER = 2;
  BENCH_TYPE_ORGANIZATION = 3;
  BENCH_TYPE_HANDLE = 4;
  BENCH_TYPE_CLIENT = 5;
  BENCH_TYPE_SERVER = 500;
  BENCH_TYPE_STORE = 501;
  BENCH_TYPE_MACHINE = 502;
  BENCH_TYPE_DRIVE = 503;
  BENCH_TYPE_MEMBERSHIP = 600;
  BENCH_TYPE_INVITE = 601;
  BENCH_TYPE_BRANCH = 1000;
  BENCH_TYPE_PACKAGE = 1001;
  BENCH_TYPE_DEPENDENCY = 1002;
  BENCH_TYPE_SPACE = 1003;
  BENCH_TYPE_BLOCK = 1010;
  BENCH_TYPE_TRIGGER = 1011;
  BENCH_TYPE_FIELD = 1012;
  BENCH_TYPE_QUERY = 1013;
  BENCH_TYPE_VIEW = 1014;
  BENCH_TYPE_STEP = 1015;
  BENCH_TYPE_BADGE = 1016;
  BENCH_TYPE_FILE = 1100;
  BENCH_TYPE_SECRET = 1101;
  BENCH_TYPE_MESSAGE = 1102;
  BENCH_TYPE_RECORD = 1103;
  BENCH_TYPE_NOTIFICATION = 1104;
  BENCH_TYPE_SESSION = 1200;
  BENCH_TYPE_RUN = 1201;
  BENCH_TYPE_SIGNAL = 1202;
  BENCH_TYPE_LOG = 1203;
  BENCH_TYPE_SKIP = 9000;
  BENCH_TYPE_SESSION_CONTEXT = 10001;
  BENCH_TYPE_EDIT_CONTEXT = 10002;
  BENCH_TYPE_EDIT = 10005;
  BENCH_TYPE_CHANGE = 10006;
  BENCH_TYPE_CHANGE_VIGNETTE = 10007;
  BENCH_TYPE_GRAPH_SCOPE = 10050;
  BENCH_TYPE_CLIENT_ORIGIN = 10051;
  BENCH_TYPE_NODE_REFERENCE = 10052;
  BENCH_TYPE_PROPERTY_REFERENCE = 10053;
  BENCH_TYPE_PATH = 10060;
  BENCH_TYPE_PATH_TOKEN = 10061;
  BENCH_TYPE_POLICY = 10100;
  BENCH_TYPE_POLICY_RULE = 10101;
  BENCH_TYPE_SUBJECT = 10102;
  BENCH_TYPE_ACCESS_ZONE = 10104;
  BENCH_TYPE_ACCESS_MATRIX = 10105;
  BENCH_TYPE_ACCESS = 10107;
  BENCH_TYPE_TEXT = 10150;
  BENCH_TYPE_TEXT_LINE = 10151;
  BENCH_TYPE_TEXT_SPAN = 10152;
  BENCH_TYPE_TYPE_INFO = 10200;
  BENCH_TYPE_TYPE_CONSTRAINT = 10201;
  BENCH_TYPE_SCHEDULE = 10202;
  BENCH_TYPE_FILE_REFERENCE = 10204;
  BENCH_TYPE_ICON = 10205;
  BENCH_TYPE_SECRET_REFERENCE = 10206;
  BENCH_TYPE_FILE_INFO = 10207;
  BENCH_TYPE_TRIGGER_INFO = 10208;
  BENCH_TYPE_EXPRESSION = 10300;
  BENCH_TYPE_AGGREGATION = 10301;
  BENCH_TYPE_SELECTION = 10302;
  BENCH_TYPE_QUERY_INFO = 10303;
  BENCH_TYPE_READ_OPTIONS = 10304;
  BENCH_TYPE_VALUE = 10305;
  BENCH_TYPE_COMPUTED_VALUE = 10306;
  BENCH_TYPE_CODE = 10400;
  BENCH_TYPE_CODE_LINE = 10401;
  BENCH_TYPE_PIPE = 10450;
  BENCH_TYPE_RUN_ERROR = 10500;
  BENCH_TYPE_RUN_OPTIONS = 10501;
  BENCH_TYPE_RUN_ATTEMPT = 10502;
  BENCH_TYPE_RUN_TRACE = 10503;
  BENCH_TYPE_RUN_FRAME = 10504;
  BENCH_TYPE_BREAKPOINT = 10520;
  BENCH_TYPE_MODEL_OPTIONS = 10430;
  BENCH_TYPE_LOG_INFO = 10550;
  BENCH_TYPE_COLOR = 11000;
  BENCH_TYPE_FONT = 11001;
  BENCH_TYPE_BOX = 11002;
  BENCH_TYPE_OFFSET = 11003;
  BENCH_TYPE_TRANSFORM = 11004;
  BENCH_TYPE_START_VIEW_STATE = 11200;
  BENCH_TYPE_FEED_VIEW_STATE = 11201;
  BENCH_TYPE_CHART_VIEW_STATE = 11202;
  BENCH_TYPE_HISTORY_VIEW_STATE = 11203;
  BENCH_TYPE_TIMELINE_VIEW_STATE = 11204;
  BENCH_TYPE_USER_WIZARD_VIEW_STATE = 11205;
  BENCH_TYPE_PAGE_VIEW_STATE = 11206;
  BENCH_TYPE_TREE_VIEW_STATE = 11207;
  BENCH_TYPE_ENUM_TYPE = 20001;
  BENCH_TYPE_NODE_TYPE = 20002;
  BENCH_TYPE_STRUCT_TYPE = 20003;
  BENCH_TYPE_OBJECT_TYPE = 20004;
  BENCH_TYPE_BENCH_TYPE = 20005;
  BENCH_TYPE_CHANGE_KIND = 20011;
  BENCH_TYPE_ACCESS_MODE = 20030;
  BENCH_TYPE_ACCESS_KIND = 20031;
  BENCH_TYPE_READ_TYPE = 20032;
  BENCH_TYPE_EDIT_TYPE = 20033;
  BENCH_TYPE_USE_TYPE = 20034;
  BENCH_TYPE_ACCESS_TYPE = 20035;
  BENCH_TYPE_CHANGE_CATEGORY = 20036;
  BENCH_TYPE_POLICY_EFFECT = 20040;
  BENCH_TYPE_CLOUD = 20050;
  BENCH_TYPE_REGION = 20051;
  BENCH_TYPE_REGION_ZONE = 20052;
  BENCH_TYPE_REGION_AREA = 20053;
  BENCH_TYPE_RESOURCE_STATUS = 20054;
  BENCH_TYPE_FILE_RETENTION_MODE = 2060;
  BENCH_TYPE_FILE_KIND = 2061;
  BENCH_TYPE_FILE_TYPE = 2062;
  BENCH_TYPE_FILE_FORMAT = 2063;
  BENCH_TYPE_CLIENT_TYPE = 20070;
  BENCH_TYPE_PRIMITIVE_TYPE = 20080;
  BENCH_TYPE_FIELD_ZONE = 20082;
  BENCH_TYPE_TYPE_KIND = 20083;
  BENCH_TYPE_BLOCK_TYPE = 20384;
  BENCH_TYPE_SCHEDULE_TYPE = 20100;
  BENCH_TYPE_TIME_INTERVAL = 20101;
  BENCH_TYPE_DAY = 20102;
  BENCH_TYPE_MONTH = 20103;
  BENCH_TYPE_TEXT_LINE_TYPE = 20110;
  BENCH_TYPE_ICON_KIND = 20111;
  BENCH_TYPE_EXPRESSION_KIND = 20200;
  BENCH_TYPE_EXPRESSION_OP = 20201;
  BENCH_TYPE_LITERAL_OP = 20202;
  BENCH_TYPE_FUNCTIONAL_OP = 20203;
  BENCH_TYPE_CONDITIONAL_OP = 20204;
  BENCH_TYPE_AGGREGATION_OP = 20205;
  BENCH_TYPE_SORT_MODE = 20206;
  BENCH_TYPE_SORT_OP = 20207;
  BENCH_TYPE_SELECTION_KIND = 20208;
  BENCH_TYPE_PATH_TOKEN_TYPE = 20210;
  BENCH_TYPE_STEP_TYPE = 20500;
  BENCH_TYPE_PIPE_TYPE = 20501;
  BENCH_TYPE_LOG_KIND = 20502;
  BENCH_TYPE_LOG_LEVEL = 20503;
  BENCH_TYPE_RUN_STATUS = 20504;
  BENCH_TYPE_RUN_KIND = 20505;
  BENCH_TYPE_RUN_ERROR_KIND = 20506;
  BENCH_TYPE_RUN_ERROR_TYPE = 20507;
  BENCH_TYPE_SESSION_STATUS = 20508;
  BENCH_TYPE_TRIGGER_TYPE = 20509;
  BENCH_TYPE_NOTIFICATION_KIND = 20510;
  BENCH_TYPE_BREAKPOINT_KIND = 20511;
  BENCH_TYPE_BREAKPOINT_ACTION = 20512;
  BENCH_TYPE_CODE_TYPE = 20513;
  BENCH_TYPE_MODEL_PROVIDER = 20530;
  BENCH_TYPE_MODEL_TYPE = 20531;
  BENCH_TYPE_SPACE_TYPE = 21000;
  BENCH_TYPE_VIEW_TYPE = 21001;
  BENCH_TYPE_VARIANT = 21002;
  BENCH_TYPE_COLOR_TYPE = 21003;
  BENCH_TYPE_COLOR_SHADE = 21004;
  BENCH_TYPE_FONT_TYPE = 21005;
  BENCH_TYPE_FONT_WEIGHT = 21006;
  BENCH_TYPE_FONT_SIZE = 21007;
  BENCH_TYPE_SPACING = 21008;
  BENCH_TYPE_ANCHOR = 21009;
  BENCH_TYPE_ORIENTATION = 21010;
  BENCH_TYPE_ALIGNMENT = 21011;
  BENCH_TYPE_USER_WIZARD_STAGE = 21200;
  BENCH_TYPE_TREE_VIEW_PRESET = 21201;
  BENCH_TYPE_USER_STATUS = 29000;
  BENCH_TYPE_ORGANIZATION_STATUS = 29001;
}

enum BlockType {
  BLOCK_TYPE_UNSPECIFIED = 0;
  BLOCK_TYPE_PAGE = 1;
  BLOCK_TYPE_CLASS = 10;
  BLOCK_TYPE_CHOICE = 11;
  BLOCK_TYPE_SIGNAL = 12;
  BLOCK_TYPE_NOTIFICATION = 13;
  BLOCK_TYPE_TEXT = 30;
  BLOCK_TYPE_CODE = 31;
  BLOCK_TYPE_FLOW = 32;
  BLOCK_TYPE_VARIABLE = 50;
  BLOCK_TYPE_DATABASE = 51;
  BLOCK_TYPE_QUERY = 52;
  BLOCK_TYPE_VIEW = 70;
  BLOCK_TYPE_ROLE = 90;
  BLOCK_TYPE_IDENTITY = 91;
}

enum BreakpointAction {
  BREAKPOINT_ACTION_UNSPECIFIED = 0;
  BREAKPOINT_ACTION_SUSPEND = 1;
}

enum BreakpointKind {
  BREAKPOINT_KIND_UNSPECIFIED = 0;
  BREAKPOINT_KIND_START_RUN = 1;
  BREAKPOINT_KIND_FAIL_RUN = 2;
  BREAKPOINT_KIND_COMPLETE_RUN = 3;
  BREAKPOINT_KIND_FAIL_ATTEMPT = 4;
  BREAKPOINT_KIND_CODE_LINE = 20;
}

// Optional classification for edits.
enum ChangeCategory {
  CHANGE_CATEGORY_UNSPECIFIED = 0;
  CHANGE_CATEGORY_SPACE = 10;
  CHANGE_CATEGORY_SESSION = 20;
}

// The kind of Change.
enum ChangeKind {
  CHANGE_KIND_UNSPECIFIED = 0;
  CHANGE_KIND_CODE = 1;
  CHANGE_KIND_MATERIALIZED = 2;
  CHANGE_KIND_LOGS = 3;
  CHANGE_KIND_LOGS_QUERY = 4;
}

enum ClientType {
  CLIENT_TYPE_UNSPECIFIED = 0;
  CLIENT_TYPE_BENCH_WEB = 1;
  CLIENT_TYPE_BENCH_BROWSER_PLUGIN = 2;
  CLIENT_TYPE_BENCH_DESKTOP = 3;
  CLIENT_TYPE_BENCH_MOBILE = 4;
  CLIENT_TYPE_BENCH_MACHINE = 10;
}

// The cloud provider.
enum Cloud {
  CLOUD_UNSPECIFIED = 0;
  CLOUD_AWS = 100;
  CLOUD_AZURE = 101;
  CLOUD_GCP = 102;
  CLOUD_OCI = 103;
  CLOUD_ALIBABA = 104;
  CLOUD_HETZNER = 200;
  CLOUD_NEON = 300;
  CLOUD_PRIVATE = 900;
}

// The implicit 'type' of some Code.
// We don't set this explicitly in Code because it depends on where the Code is used.
enum CodeType {
  CODE_TYPE_UNSPECIFIED = 0;
  CODE_TYPE_SNIPPET = 1;
  CODE_TYPE_SCRIPT = 2;
  CODE_TYPE_FUNCTION = 3;
}

// Built-in color shades a la Tailwind.
enum ColorShade {
  COLOR_SHADE_UNSPECIFIED = 0;
  COLOR_SHADE_S50 = 50;
  COLOR_SHADE_S100 = 100;
  COLOR_SHADE_S200 = 200;
  COLOR_SHADE_S300 = 300;
  COLOR_SHADE_S400 = 400;
  COLOR_SHADE_S500 = 500;
  COLOR_SHADE_S600 = 600;
  COLOR_SHADE_S700 = 700;
  COLOR_SHADE_S800 = 800;
  COLOR_SHADE_S900 = 900;
  COLOR_SHADE_S950 = 950;
}

// Built-in color types a la SwiftUI or Tailwind.
enum ColorType {
  COLOR_TYPE_UNSPECIFIED = 0;
  COLOR_TYPE_PRIMARY = 1;
  COLOR_TYPE_SECONDARY = 2;
  COLOR_TYPE_ACCENT = 3;
  COLOR_TYPE_CANVAS = 4;
  COLOR_TYPE_SUCCESS = 10;
  COLOR_TYPE_HINT = 11;
  COLOR_TYPE_WARNING = 12;
  COLOR_TYPE_DANGER = 13;
  COLOR_TYPE_GRAY = 30;
  COLOR_TYPE_RED = 31;
  COLOR_TYPE_ORANGE = 32;
  COLOR_TYPE_AMBER = 33;
  COLOR_TYPE_YELLOW = 34;
  COLOR_TYPE_LIME = 35;
  COLOR_TYPE_GREEN = 36;
  COLOR_TYPE_EMERALD = 37;
  COLOR_TYPE_TEAL = 38;
  COLOR_TYPE_CYAN = 39;
  COLOR_TYPE_SKY = 40;
  COLOR_TYPE_BLUE = 41;
  COLOR_TYPE_INDIGO = 42;
  COLOR_TYPE_VIOLET = 43;
  COLOR_TYPE_PURPLE = 44;
  COLOR_TYPE_FUCHSIA = 45;
  COLOR_TYPE_PINK = 46;
  COLOR_TYPE_ROSE = 47;
}

enum ConditionalOp {
  CONDITIONAL_OP_UNSPECIFIED = 0;
  CONDITIONAL_OP_NOT = 301;
  CONDITIONAL_OP_AND = 302;
  CONDITIONAL_OP_OR = 303;
  CONDITIONAL_OP_EQUALS = 310;
  CONDITIONAL_OP_NOT_EQUALS = 311;
  CONDITIONAL_OP_GREATER_THAN = 312;
  CONDITIONAL_OP_GREATER_THAN_OR_EQUALS = 313;
  CONDITIONAL_OP_LESS_THAN = 314;
  CONDITIONAL_OP_LESS_THAN_OR_EQUALS = 315;
  CONDITIONAL_OP_MATCHES_REGEX = 320;
  CONDITIONAL_OP_STARTS_WITH = 321;
  CONDITIONAL_OP_ENDS_WITH = 322;
  CONDITIONAL_OP_CONTAINS = 330;
  CONDITIONAL_OP_NOT_CONTAINS = 331;
  CONDITIONAL_OP_IN = 332;
  CONDITIONAL_OP_NOT_IN = 333;
  CONDITIONAL_OP_EXISTS = 340;
  CONDITIONAL_OP_NOT_EXISTS = 341;
  CONDITIONAL_OP_NEAR = 350;
}

enum Day {
  DAY_UNSPECIFIED = 0;
  DAY_MONDAY = 1;
  DAY_TUESDAY = 2;
  DAY_WEDNESDAY = 3;
  DAY_THURSDAY = 4;
  DAY_FRIDAY = 5;
  DAY_SATURDAY = 6;
  DAY_SUNDAY = 7;
}

// Ways to edit nodes.
enum EditType {
  EDIT_TYPE_UNSPECIFIED = 0;
  EDIT_TYPE_CREATE = 20;
  EDIT_TYPE_UPSERT = 21;
  EDIT_TYPE_UPDATE = 22;
  EDIT_TYPE_MOVE = 23;
  EDIT_TYPE_ARCHIVE = 24;
  EDIT_TYPE_UNARCHIVE = 25;
  EDIT_TYPE_DELETE = 26;
  EDIT_TYPE_RESTORE = 27;
  EDIT_TYPE_ERASE = 28;
}

enum EnumType {
  ENUM_TYPE_UNSPECIFIED = 0;
  ENUM_TYPE_ENUM_TYPE = 20001;
  ENUM_TYPE_NODE_TYPE = 20002;
  ENUM_TYPE_STRUCT_TYPE = 20003;
  ENUM_TYPE_OBJECT_TYPE = 20004;
  ENUM_TYPE_BENCH_TYPE = 20005;
  ENUM_TYPE_CHANGE_KIND = 20011;
  ENUM_TYPE_ACCESS_MODE = 20030;
  ENUM_TYPE_ACCESS_KIND = 20031;
  ENUM_TYPE_READ_TYPE = 20032;
  ENUM_TYPE_EDIT_TYPE = 20033;
  ENUM_TYPE_USE_TYPE = 20034;
  ENUM_TYPE_ACCESS_TYPE = 20035;
  ENUM_TYPE_CHANGE_CATEGORY = 20036;
  ENUM_TYPE_POLICY_EFFECT = 20040;
  ENUM_TYPE_CLOUD = 20050;
  ENUM_TYPE_REGION = 20051;
  ENUM_TYPE_REGION_ZONE = 20052;
  ENUM_TYPE_REGION_AREA = 20053;
  ENUM_TYPE_RESOURCE_STATUS = 20054;
  ENUM_TYPE_FILE_RETENTION_MODE = 2060;
  ENUM_TYPE_FILE_KIND = 2061;
  ENUM_TYPE_FILE_TYPE = 2062;
  ENUM_TYPE_FILE_FORMAT = 2063;
  ENUM_TYPE_CLIENT_TYPE = 20070;
  ENUM_TYPE_PRIMITIVE_TYPE = 20080;
  ENUM_TYPE_FIELD_ZONE = 20082;
  ENUM_TYPE_TYPE_KIND = 20083;
  ENUM_TYPE_BLOCK_TYPE = 20384;
  ENUM_TYPE_SCHEDULE_TYPE = 20100;
  ENUM_TYPE_TIME_INTERVAL = 20101;
  ENUM_TYPE_DAY = 20102;
  ENUM_TYPE_MONTH = 20103;
  ENUM_TYPE_TEXT_LINE_TYPE = 20110;
  ENUM_TYPE_ICON_KIND = 20111;
  ENUM_TYPE_EXPRESSION_KIND = 20200;
  ENUM_TYPE_EXPRESSION_OP = 20201;
  ENUM_TYPE_LITERAL_OP = 20202;
  ENUM_TYPE_FUNCTIONAL_OP = 20203;
  ENUM_TYPE_CONDITIONAL_OP = 20204;
  ENUM_TYPE_AGGREGATION_OP = 20205;
  ENUM_TYPE_SORT_MODE = 20206;
  ENUM_TYPE_SORT_OP = 20207;
  ENUM_TYPE_SELECTION_KIND = 20208;
  ENUM_TYPE_PATH_TOKEN_TYPE = 20210;
  ENUM_TYPE_STEP_TYPE = 20500;
  ENUM_TYPE_PIPE_TYPE = 20501;
  ENUM_TYPE_LOG_KIND = 20502;
  ENUM_TYPE_LOG_LEVEL = 20503;
  ENUM_TYPE_RUN_STATUS = 20504;
  ENUM_TYPE_RUN_KIND = 20505;
  ENUM_TYPE_RUN_ERROR_KIND = 20506;
  ENUM_TYPE_RUN_ERROR_TYPE = 20507;
  ENUM_TYPE_SESSION_STATUS = 20508;
  ENUM_TYPE_TRIGGER_TYPE = 20509;
  ENUM_TYPE_NOTIFICATION_KIND = 20510;
  ENUM_TYPE_BREAKPOINT_KIND = 20511;
  ENUM_TYPE_BREAKPOINT_ACTION = 20512;
  ENUM_TYPE_CODE_TYPE = 20513;
  ENUM_TYPE_MODEL_PROVIDER = 20530;
  ENUM_TYPE_MODEL_TYPE = 20531;
  ENUM_TYPE_SPACE_TYPE = 21000;
  ENUM_TYPE_VIEW_TYPE = 21001;
  ENUM_TYPE_VARIANT = 21002;
  ENUM_TYPE_COLOR_TYPE = 21003;
  ENUM_TYPE_COLOR_SHADE = 21004;
  ENUM_TYPE_FONT_TYPE = 21005;
  ENUM_TYPE_FONT_WEIGHT = 21006;
  ENUM_TYPE_FONT_SIZE = 21007;
  ENUM_TYPE_SPACING = 21008;
  ENUM_TYPE_ANCHOR = 21009;
  ENUM_TYPE_ORIENTATION = 21010;
  ENUM_TYPE_ALIGNMENT = 21011;
  ENUM_TYPE_USER_WIZARD_STAGE = 21200;
  ENUM_TYPE_TREE_VIEW_PRESET = 21201;
  ENUM_TYPE_USER_STATUS = 29000;
  ENUM_TYPE_ORGANIZATION_STATUS = 29001;
}

enum ExpressionKind {
  EXPRESSION_KIND_UNSPECIFIED = 0;
  EXPRESSION_KIND_LITERAL = 1;
  EXPRESSION_KIND_FUNCTIONAL = 2;
  EXPRESSION_KIND_CONDITIONAL = 3;
  EXPRESSION_KIND_SORT = 4;
  EXPRESSION_KIND_AGGREGATION = 5;
}

enum ExpressionOp {
  EXPRESSION_OP_UNSPECIFIED = 0;
  EXPRESSION_OP_VALUE = 100;
  EXPRESSION_OP_NONE = 101;
  EXPRESSION_OP_TRUE = 102;
  EXPRESSION_OP_FALSE = 103;
  EXPRESSION_OP_ADD = 200;
  EXPRESSION_OP_SUBTRACT = 201;
  EXPRESSION_OP_MULTIPLY = 202;
  EXPRESSION_OP_DIVIDE = 203;
  EXPRESSION_OP_MODULO = 204;
  EXPRESSION_OP_POWER = 205;
  EXPRESSION_OP_NOT = 301;
  EXPRESSION_OP_AND = 302;
  EXPRESSION_OP_OR = 303;
  EXPRESSION_OP_EQUALS = 310;
  EXPRESSION_OP_NOT_EQUALS = 311;
  EXPRESSION_OP_GREATER_THAN = 312;
  EXPRESSION_OP_GREATER_THAN_OR_EQUALS = 313;
  EXPRESSION_OP_LESS_THAN = 314;
  EXPRESSION_OP_LESS_THAN_OR_EQUALS = 315;
  EXPRESSION_OP_MATCHES_REGEX = 320;
  EXPRESSION_OP_STARTS_WITH = 321;
  EXPRESSION_OP_ENDS_WITH = 322;
  EXPRESSION_OP_CONTAINS = 330;
  EXPRESSION_OP_NOT_CONTAINS = 331;
  EXPRESSION_OP_IN = 332;
  EXPRESSION_OP_NOT_IN = 333;
  EXPRESSION_OP_EXISTS = 400;
  EXPRESSION_OP_NOT_EXISTS = 341;
  EXPRESSION_OP_NEAR = 350;
  EXPRESSION_OP_COUNT = 401;
  EXPRESSION_OP_SUM = 402;
  EXPRESSION_OP_MIN = 403;
  EXPRESSION_OP_MAX = 404;
  EXPRESSION_OP_AVERAGE = 405;
  EXPRESSION_OP_MEDIAN = 406;
  EXPRESSION_OP_HISTOGRAM = 407;
  EXPRESSION_OP_ASCENDING = 500;
  EXPRESSION_OP_DESCENDING = 501;
}

// The 'zone' of a Field within its Block.
enum FieldZone {
  FIELD_ZONE_UNSPECIFIED = 0;
  FIELD_ZONE_VARIABLE = 1;
  FIELD_ZONE_MEMBER = 2;
  FIELD_ZONE_INPUT = 3;
  FIELD_ZONE_OUTPUT = 4;
  FIELD_ZONE_OPTION = 5;
  FIELD_ZONE_RUNTIME = 6;
}

// The format of a file (roughly an extension).
enum FileFormat {
  FILE_FORMAT_UNSPECIFIED = 0;
  FILE_FORMAT_TXT = 10000;
  FILE_FORMAT_MARKDOWN = 10001;
  FILE_FORMAT_RTF = 10002;
  FILE_FORMAT_INI = 10003;
  FILE_FORMAT_LOG = 10004;
  FILE_FORMAT_PYTHON = 20000;
  FILE_FORMAT_JAVASCRIPT = 20001;
  FILE_FORMAT_TYPESCRIPT = 20002;
  FILE_FORMAT_GO = 20003;
  FILE_FORMAT_C_LANG = 20004;
  FILE_FORMAT_CPP = 20005;
  FILE_FORMAT_OBJECTIVE_C = 20006;
  FILE_FORMAT_SWIFT = 20007;
  FILE_FORMAT_RUBY = 20008;
  FILE_FORMAT_PHP = 20009;
  FILE_FORMAT_CSS = 20011;
  FILE_FORMAT_JAVA = 20012;
  FILE_FORMAT_KOTLIN = 20013;
  FILE_FORMAT_RUST = 20014;
  FILE_FORMAT_SCALA = 20015;
  FILE_FORMAT_SHELL = 20016;
  FILE_FORMAT_SQL = 20017;
  FILE_FORMAT_POWERSHELL = 20018;
  FILE_FORMAT_ASSEMBLY = 20019;
  FILE_FORMAT_LATEX = 20020;
  FILE_FORMAT_JPEG = 30000;
  FILE_FORMAT_PNG = 30001;
  FILE_FORMAT_GIF = 30002;
  FILE_FORMAT_BMP = 30003;
  FILE_FORMAT_TIFF = 30004;
  FILE_FORMAT_WEBP = 30005;
  FILE_FORMAT_SVG = 30006;
  FILE_FORMAT_ICO = 30007;
  FILE_FORMAT_RAW = 30008;
  FILE_FORMAT_HEIC = 30009;
  FILE_FORMAT_HEIF = 30010;
  FILE_FORMAT_MP3 = 40000;
  FILE_FORMAT_WAV = 40001;
  FILE_FORMAT_FLAC = 40002;
  FILE_FORMAT_AAC = 40003;
  FILE_FORMAT_OGG = 40004;
  FILE_FORMAT_M4A = 40005;
  FILE_FORMAT_WMA = 40006;
  FILE_FORMAT_MP4 = 50000;
  FILE_FORMAT_WEBM = 50001;
  FILE_FORMAT_AVI = 50002;
  FILE_FORMAT_MOV = 50003;
  FILE_FORMAT_WMV = 50004;
  FILE_FORMAT_FLV = 50005;
  FILE_FORMAT_MKV = 50006;
  FILE_FORMAT_PDF = 60000;
  FILE_FORMAT_DOCX = 60001;
  FILE_FORMAT_PPTX = 60002;
  FILE_FORMAT_ODT = 60003;
  FILE_FORMAT_XLSX = 60004;
  FILE_FORMAT_ODS = 60005;
  FILE_FORMAT_EPUB = 60006;
  FILE_FORMAT_MOBI = 60007;
  FILE_FORMAT_CHM = 60008;
  FILE_FORMAT_DOC = 60009;
  FILE_FORMAT_XLS = 60100;
  FILE_FORMAT_PPT = 60101;
  FILE_FORMAT_HTML = 60102;
  FILE_FORMAT_JSON = 70000;
  FILE_FORMAT_YAML = 70001;
  FILE_FORMAT_CSV = 70002;
  FILE_FORMAT_XML = 70003;
  FILE_FORMAT_TOML = 70004;
  FILE_FORMAT_SQLITE = 70100;
  FILE_FORMAT_PARQUET = 70101;
  FILE_FORMAT_ZIP = 80000;
  FILE_FORMAT_RAR = 80001;
  FILE_FORMAT_TAR = 80002;
  FILE_FORMAT_SEVENZIP = 80003;
  FILE_FORMAT_CAB = 80004;
  FILE_FORMAT_GZIP = 80005;
  FILE_FORMAT_BZIP2 = 80006;
  FILE_FORMAT_XZ = 80007;
  FILE_FORMAT_EXE = 90000;
  FILE_FORMAT_APP_IMAGE = 90001;
  FILE_FORMAT_APK = 90002;
  FILE_FORMAT_DMG = 90003;
  FILE_FORMAT_JAR = 90004;
  FILE_FORMAT_MSI = 90005;
  FILE_FORMAT_DEB = 90006;
  FILE_FORMAT_RPM = 90007;
}

enum FileKind {
  FILE_KIND_UNSPECIFIED = 0;
  FILE_KIND_DRIVE = 1;
  FILE_KIND_DRIVE_INLINE = 2;
  FILE_KIND_INLINE = 3;
  FILE_KIND_EXTERNAL = 10;
}

enum FileRetentionMode {
  FILE_RETENTION_MODE_UNSPECIFIED = 0;
  FILE_RETENTION_MODE_AUTOMATIC = 1;
  FILE_RETENTION_MODE_MANUAL = 2;
  FILE_RETENTION_MODE_TIMED = 3;
}

enum FileType {
  FILE_TYPE_UNSPECIFIED = 0;
  FILE_TYPE_TEXT = 1;
  FILE_TYPE_CODE = 2;
  FILE_TYPE_IMAGE = 3;
  FILE_TYPE_AUDIO = 4;
  FILE_TYPE_VIDEO = 5;
  FILE_TYPE_DOCUMENT = 6;
  FILE_TYPE_DATA = 7;
  FILE_TYPE_ARCHIVE = 8;
  FILE_TYPE_EXECUTABLE = 9;
  FILE_TYPE_GENERIC = 99;
}

enum FontSize {
  FONT_SIZE_UNSPECIFIED = 0;
  FONT_SIZE_XS = 12;
  FONT_SIZE_SM = 14;
  FONT_SIZE_BASE = 16;
  FONT_SIZE_LG = 18;
  FONT_SIZE_XL = 20;
  FONT_SIZE_XL2 = 24;
  FONT_SIZE_XL3 = 30;
  FONT_SIZE_XL4 = 36;
  FONT_SIZE_XL5 = 48;
  FONT_SIZE_XL6 = 60;
  FONT_SIZE_XL7 = 72;
}

enum FontType {
  FONT_TYPE_UNSPECIFIED = 0;
  FONT_TYPE_SERIF = 1;
  FONT_TYPE_SANS = 2;
  FONT_TYPE_MONO = 3;
}

enum FontWeight {
  FONT_WEIGHT_UNSPECIFIED = 0;
  FONT_WEIGHT_THIN = 100;
  FONT_WEIGHT_EXTRA_LIGHT = 200;
  FONT_WEIGHT_LIGHT = 300;
  FONT_WEIGHT_NORMAL = 400;
  FONT_WEIGHT_MEDIUM = 500;
  FONT_WEIGHT_SEMI_BOLD = 600;
  FONT_WEIGHT_BOLD = 700;
  FONT_WEIGHT_EXTRA_BOLD = 800;
  FONT_WEIGHT_BLACK = 900;
}

enum FunctionalOp {
  FUNCTIONAL_OP_UNSPECIFIED = 0;
  FUNCTIONAL_OP_ADD = 200;
  FUNCTIONAL_OP_SUBTRACT = 201;
  FUNCTIONAL_OP_MULTIPLY = 202;
  FUNCTIONAL_OP_DIVIDE = 203;
  FUNCTIONAL_OP_MODULO = 204;
  FUNCTIONAL_OP_POWER = 205;
}

enum IconKind {
  ICON_KIND_UNSPECIFIED = 0;
  ICON_KIND_EMOJI = 1;
  ICON_KIND_FILE = 2;
  ICON_KIND_FONT_AWESOME = 3;
  ICON_KIND_VS_CODE = 4;
}

enum IdEnum {
  ID_ENUM_UNSPECIFIED = 0;
}

enum LiteralOp {
  LITERAL_OP_UNSPECIFIED = 0;
  LITERAL_OP_VALUE = 100;
  LITERAL_OP_NONE = 101;
  LITERAL_OP_TRUE = 102;
  LITERAL_OP_FALSE = 103;
}

enum LogKind {
  LOG_KIND_UNSPECIFIED = 0;
  LOG_KIND_CHANGE = 1;
  LOG_KIND_EDIT = 2;
}

enum LogLevel {
  LOG_LEVEL_UNSPECIFIED = 0;
  LOG_LEVEL_TRACE = 1;
  LOG_LEVEL_DEBUG = 2;
  LOG_LEVEL_INFO = 3;
  LOG_LEVEL_WARNING = 4;
  LOG_LEVEL_ERROR = 5;
  LOG_LEVEL_CRITICAL = 6;
}

enum ModelProvider {
  MODEL_PROVIDER_UNSPECIFIED = 0;
  MODEL_PROVIDER_OPENAI = 100;
  MODEL_PROVIDER_ANTHROPIC = 200;
  MODEL_PROVIDER_GOOGLE = 300;
  MODEL_PROVIDER_META = 400;
}

enum ModelType {
  MODEL_TYPE_UNSPECIFIED = 0;
  MODEL_TYPE_GPT4_0 = 101;
  MODEL_TYPE_GPT4_O_MINI = 102;
  MODEL_TYPE_CLAUDE_3_5_SONNET = 201;
  MODEL_TYPE_GEMINI_1_5_PRO = 301;
  MODEL_TYPE_LLAMA_3_1_80B = 401;
  MODEL_TYPE_LLAMA_3_1_400B = 402;
}

enum Month {
  MONTH_UNSPECIFIED = 0;
  MONTH_JANUARY = 1;
  MONTH_FEBRUARY = 2;
  MONTH_MARCH = 3;
  MONTH_APRIL = 4;
  MONTH_MAY = 5;
  MONTH_JUNE = 6;
  MONTH_JULY = 7;
  MONTH_AUGUST = 8;
  MONTH_SEPTEMBER = 9;
  MONTH_OCTOBER = 10;
  MONTH_NOVEMBER = 11;
  MONTH_DECEMBER = 12;
}

enum NodeType {
  NODE_TYPE_UNSPECIFIED = 0;
  NODE_TYPE_BENCH = 1;
  NODE_TYPE_USER = 2;
  NODE_TYPE_ORGANIZATION = 3;
  NODE_TYPE_HANDLE = 4;
  NODE_TYPE_CLIENT = 5;
  NODE_TYPE_SERVER = 500;
  NODE_TYPE_STORE = 501;
  NODE_TYPE_MACHINE = 502;
  NODE_TYPE_DRIVE = 503;
  NODE_TYPE_MEMBERSHIP = 600;
  NODE_TYPE_INVITE = 601;
  NODE_TYPE_BRANCH = 1000;
  NODE_TYPE_PACKAGE = 1001;
  NODE_TYPE_DEPENDENCY = 1002;
  NODE_TYPE_SPACE = 1003;
  NODE_TYPE_BLOCK = 1010;
  NODE_TYPE_TRIGGER = 1011;
  NODE_TYPE_FIELD = 1012;
  NODE_TYPE_QUERY = 1013;
  NODE_TYPE_VIEW = 1014;
  NODE_TYPE_STEP = 1015;
  NODE_TYPE_BADGE = 1016;
  NODE_TYPE_FILE = 1100;
  NODE_TYPE_SECRET = 1101;
  NODE_TYPE_MESSAGE = 1102;
  NODE_TYPE_RECORD = 1103;
  NODE_TYPE_NOTIFICATION = 1104;
  NODE_TYPE_SESSION = 1200;
  NODE_TYPE_RUN = 1201;
  NODE_TYPE_SIGNAL = 1202;
  NODE_TYPE_LOG = 1203;
  NODE_TYPE_SKIP = 9000;
}

// The level of interaction required for a notification.
enum NotificationKind {
  NOTIFICATION_KIND_UNSPECIFIED = 0;
  NOTIFICATION_KIND_PASSIVE = 1;
  NOTIFICATION_KIND_ACTIVE = 2;
  NOTIFICATION_KIND_URGENT = 3;
}

enum ObjectType {
  OBJECT_TYPE_UNSPECIFIED = 0;
  OBJECT_TYPE_BENCH = 1;
  OBJECT_TYPE_USER = 2;
  OBJECT_TYPE_ORGANIZATION = 3;
  OBJECT_TYPE_HANDLE = 4;
  OBJECT_TYPE_CLIENT = 5;
  OBJECT_TYPE_SERVER = 500;
  OBJECT_TYPE_STORE = 501;
  OBJECT_TYPE_MACHINE = 502;
  OBJECT_TYPE_DRIVE = 503;
  OBJECT_TYPE_MEMBERSHIP = 600;
  OBJECT_TYPE_INVITE = 601;
  OBJECT_TYPE_BRANCH = 1000;
  OBJECT_TYPE_PACKAGE = 1001;
  OBJECT_TYPE_DEPENDENCY = 1002;
  OBJECT_TYPE_SPACE = 1003;
  OBJECT_TYPE_BLOCK = 1010;
  OBJECT_TYPE_TRIGGER = 1011;
  OBJECT_TYPE_FIELD = 1012;
  OBJECT_TYPE_QUERY = 1013;
  OBJECT_TYPE_VIEW = 1014;
  OBJECT_TYPE_STEP = 1015;
  OBJECT_TYPE_BADGE = 1016;
  OBJECT_TYPE_FILE = 1100;
  OBJECT_TYPE_SECRET = 1101;
  OBJECT_TYPE_MESSAGE = 1102;
  OBJECT_TYPE_RECORD = 1103;
  OBJECT_TYPE_NOTIFICATION = 1104;
  OBJECT_TYPE_SESSION = 1200;
  OBJECT_TYPE_RUN = 1201;
  OBJECT_TYPE_SIGNAL = 1202;
  OBJECT_TYPE_LOG = 1203;
  OBJECT_TYPE_SKIP = 9000;
  OBJECT_TYPE_SESSION_CONTEXT = 10001;
  OBJECT_TYPE_EDIT_CONTEXT = 10002;
  OBJECT_TYPE_EDIT = 10005;
  OBJECT_TYPE_CHANGE = 10006;
  OBJECT_TYPE_CHANGE_VIGNETTE = 10007;
  OBJECT_TYPE_GRAPH_SCOPE = 10050;
  OBJECT_TYPE_CLIENT_ORIGIN = 10051;
  OBJECT_TYPE_NODE_REFERENCE = 10052;
  OBJECT_TYPE_PROPERTY_REFERENCE = 10053;
  OBJECT_TYPE_PATH = 10060;
  OBJECT_TYPE_PATH_TOKEN = 10061;
  OBJECT_TYPE_POLICY = 10100;
  OBJECT_TYPE_POLICY_RULE = 10101;
  OBJECT_TYPE_SUBJECT = 10102;
  OBJECT_TYPE_ACCESS_ZONE = 10104;
  OBJECT_TYPE_ACCESS_MATRIX = 10105;
  OBJECT_TYPE_ACCESS = 10107;
  OBJECT_TYPE_TEXT = 10150;
  OBJECT_TYPE_TEXT_LINE = 10151;
  OBJECT_TYPE_TEXT_SPAN = 10152;
  OBJECT_TYPE_TYPE_INFO = 10200;
  OBJECT_TYPE_TYPE_CONSTRAINT = 10201;
  OBJECT_TYPE_SCHEDULE = 10202;
  OBJECT_TYPE_FILE_REFERENCE = 10204;
  OBJECT_TYPE_ICON = 10205;
  OBJECT_TYPE_SECRET_REFERENCE = 10206;
  OBJECT_TYPE_FILE_INFO = 10207;
  OBJECT_TYPE_TRIGGER_INFO = 10208;
  OBJECT_TYPE_EXPRESSION = 10300;
  OBJECT_TYPE_AGGREGATION = 10301;
  OBJECT_TYPE_SELECTION = 10302;
  OBJECT_TYPE_QUERY_INFO = 10303;
  OBJECT_TYPE_READ_OPTIONS = 10304;
  OBJECT_TYPE_VALUE = 10305;
  OBJECT_TYPE_COMPUTED_VALUE = 10306;
  OBJECT_TYPE_CODE = 10400;
  OBJECT_TYPE_CODE_LINE = 10401;
  OBJECT_TYPE_PIPE = 10450;
  OBJECT_TYPE_RUN_ERROR = 10500;
  OBJECT_TYPE_RUN_OPTIONS = 10501;
  OBJECT_TYPE_RUN_ATTEMPT = 10502;
  OBJECT_TYPE_RUN_TRACE = 10503;
  OBJECT_TYPE_RUN_FRAME = 10504;
  OBJECT_TYPE_BREAKPOINT = 10520;
  OBJECT_TYPE_MODEL_OPTIONS = 10430;
  OBJECT_TYPE_LOG_INFO = 10550;
  OBJECT_TYPE_COLOR = 11000;
  OBJECT_TYPE_FONT = 11001;
  OBJECT_TYPE_BOX = 11002;
  OBJECT_TYPE_OFFSET = 11003;
  OBJECT_TYPE_TRANSFORM = 11004;
  OBJECT_TYPE_START_VIEW_STATE = 11200;
  OBJECT_TYPE_FEED_VIEW_STATE = 11201;
  OBJECT_TYPE_CHART_VIEW_STATE = 11202;
  OBJECT_TYPE_HISTORY_VIEW_STATE = 11203;
  OBJECT_TYPE_TIMELINE_VIEW_STATE = 11204;
  OBJECT_TYPE_USER_WIZARD_VIEW_STATE = 11205;
  OBJECT_TYPE_PAGE_VIEW_STATE = 11206;
  OBJECT_TYPE_TREE_VIEW_STATE = 11207;
}

enum OrganizationStatus {
  ORGANIZATION_STATUS_UNSPECIFIED = 0;
  ORGANIZATION_STATUS_REGISTERED = 4;
  ORGANIZATION_STATUS_ACTIVATED = 10;
}

// Which way to orient the contents/subviews of a view.
enum Orientation {
  ORIENTATION_UNSPECIFIED = 0;
  ORIENTATION_HORIZONTAL = 1;
  ORIENTATION_VERTICAL = 11;
}

enum PathTokenType {
  PATH_TOKEN_TYPE_UNSPECIFIED = 0;
  PATH_TOKEN_TYPE_ROOT = 1;
  PATH_TOKEN_TYPE_CURRENT = 2;
  PATH_TOKEN_TYPE_PARENT = 3;
  PATH_TOKEN_TYPE_BENCH = 4;
  PATH_TOKEN_TYPE_CHILD = 5;
  PATH_TOKEN_TYPE_CONTAINER = 7;
  PATH_TOKEN_TYPE_UNIQUE = 8;
  PATH_TOKEN_TYPE_FIELD = 10;
}

enum PipeType {
  PIPE_TYPE_UNSPECIFIED = 0;
  PIPE_TYPE_THEN = 1;
  PIPE_TYPE_WITH = 2;
}

enum PolicyEffect {
  POLICY_EFFECT_UNSPECIFIED = 0;
  POLICY_EFFECT_ALLOW = 1;
  POLICY_EFFECT_DENY = 2;
}

// Fundamental column / storage types we support (subset of SQL types, used directly in sql/core).
// NOTE: the ids here are used in type identity keys, so any change is breaking.
enum PrimitiveType {
  PRIMITIVE_TYPE_UNSPECIFIED = 0;
  PRIMITIVE_TYPE_BOOLEAN = 1;
  PRIMITIVE_TYPE_INT16 = 4;
  PRIMITIVE_TYPE_INT32 = 6;
  PRIMITIVE_TYPE_INT64 = 8;
  PRIMITIVE_TYPE_DECIMAL = 10;
  PRIMITIVE_TYPE_FLOAT32 = 16;
  PRIMITIVE_TYPE_FLOAT64 = 17;
  PRIMITIVE_TYPE_STRING = 20;
  PRIMITIVE_TYPE_UUID = 21;
  PRIMITIVE_TYPE_JSON = 22;
  PRIMITIVE_TYPE_BYTES = 25;
  PRIMITIVE_TYPE_VECTOR = 26;
  PRIMITIVE_TYPE_DATETIME = 30;
  PRIMITIVE_TYPE_INTERVAL = 31;
}

// Ways to read nodes.
enum ReadType {
  READ_TYPE_UNSPECIFIED = 0;
  READ_TYPE_GET = 1;
  READ_TYPE_SEARCH = 2;
  READ_TYPE_AGGREGATE = 3;
}

// A reference to a Node or Struct - usually both have an identity (except for inlined Structs).
enum ReferenceKind {
  REFERENCE_KIND_UNSPECIFIED = 0;
  REFERENCE_KIND_NODE_ANCESTOR = 1;
  REFERENCE_KIND_NODE_ANCESTOR_OR_SELF = 2;
  REFERENCE_KIND_NODE_PARENT = 3;
  REFERENCE_KIND_NODE_CHILDREN = 4;
  REFERENCE_KIND_NODE_REGULAR = 5;
  REFERENCE_KIND_NODE_TEMPLATE = 6;
  REFERENCE_KIND_STRUCT_PARENT = 10;
  REFERENCE_KIND_STRUCT_CHILD = 11;
  REFERENCE_KIND_PROPERTY = 20;
}

// Actual regions within a Zone in an Area.
enum Region {
  REGION_UNSPECIFIED = 0;
  REGION_ZURICH = 1001;
  REGION_FRANKFURT = 1002;
  REGION_VIRGINIA = 2001;
  REGION_OHIO = 2002;
  REGION_OREGON = 2101;
  REGION_SAO_PAULO = 3001;
  REGION_CAPE_TOWN = 5001;
  REGION_MUMBAI = 6001;
  REGION_SINGAPORE = 6101;
  REGION_TOKYO = 6201;
  REGION_SYDNEY = 7001;
}

// Rough 'contintents' of Regions.
enum RegionArea {
  REGION_AREA_UNSPECIFIED = 0;
  REGION_AREA_EUROPE = 1000;
  REGION_AREA_NORTH_AMERICA = 2000;
  REGION_AREA_SOUTH_AMERICA = 3000;
  REGION_AREA_MIDDLE_EAST = 4000;
  REGION_AREA_AFRICA = 5000;
  REGION_AREA_ASIA = 6000;
  REGION_AREA_AUSTRALIA = 7000;
  REGION_AREA_PRIVATE = 9000;
  REGION_AREA_GLOBAL = 10090;
}

// A larger zone of Regions within an Area.
enum RegionZone {
  REGION_ZONE_UNSPECIFIED = 0;
  REGION_ZONE_EUROPE_CENTRAL = 1000;
  REGION_ZONE_NORTH_AMERICA_EAST = 2000;
  REGION_ZONE_NORTH_AMERICA_WEST = 2100;
  REGION_ZONE_SOUTH_AMERICA_EAST = 3000;
  REGION_ZONE_MIDDLE_EAST_CENTRAL = 4000;
  REGION_ZONE_MIDDLE_EAST_WEST = 4100;
  REGION_ZONE_AFRICA_SOUTH = 5000;
  REGION_ZONE_ASIA_WEST = 6000;
  REGION_ZONE_ASIA_SOUTH = 6100;
  REGION_ZONE_ASIA_EAST = 6200;
  REGION_ZONE_AUSTRALIA_SOUTH = 7000;
}

// Generalized status of a Resource in its lifecycle.
enum ResourceStatus {
  RESOURCE_STATUS_UNSPECIFIED = 0;
  RESOURCE_STATUS_DECLARED = 1;
  RESOURCE_STATUS_PROVISIONING = 5;
  RESOURCE_STATUS_HEALTHY = 10;
  RESOURCE_STATUS_UNHEALTHY = 15;
  RESOURCE_STATUS_SLEEPING = 20;
  RESOURCE_STATUS_DECOMMISSIONED = 30;
}

enum RunErrorKind {
  RUN_ERROR_KIND_UNSPECIFIED = 0;
  RUN_ERROR_KIND_INTERNAL = 1;
  RUN_ERROR_KIND_RUNTIME = 5;
}

enum RunErrorType {
  RUN_ERROR_TYPE_UNSPECIFIED = 0;
  RUN_ERROR_TYPE_RUNTIME_UNAVAILABLE = 1;
  RUN_ERROR_TYPE_RUN_IMPOSSIBLE = 2;
  RUN_ERROR_TYPE_REPLAY = 10;
  RUN_ERROR_TYPE_MODEL_INCAPABLE = 100;
  RUN_ERROR_TYPE_UNKNOWN_NONRETRYABLE = 499;
  RUN_ERROR_TYPE_MODEL_FAILED = 500;
  RUN_ERROR_TYPE_UNKNOWN_RETRYABLE = 999;
}

// The kind of some runnable.
enum RunKind {
  RUN_KIND_UNSPECIFIED = 0;
  RUN_KIND_CODE = 1;
  RUN_KIND_TEXT = 2;
  RUN_KIND_STEP = 3;
  RUN_KIND_FLOW = 4;
}

enum RunStatus {
  RUN_STATUS_UNSPECIFIED = 0;
  RUN_STATUS_SCHEDULED = 1;
  RUN_STATUS_QUEUED = 2;
  RUN_STATUS_RUNNING = 3;
  RUN_STATUS_PAUSED = 4;
  RUN_STATUS_SUSPENDED = 5;
  RUN_STATUS_CANCELLED = 6;
  RUN_STATUS_ABORTED = 7;
  RUN_STATUS_FAILED = 8;
  RUN_STATUS_COMPLETED = 9;
}

enum ScheduleType {
  SCHEDULE_TYPE_UNSPECIFIED = 0;
  SCHEDULE_TYPE_INTERVAL = 1;
  SCHEDULE_TYPE_CRON = 2;
}

enum SelectionKind {
  SELECTION_KIND_UNSPECIFIED = 0;
  SELECTION_KIND_RANGE = 1;
  SELECTION_KIND_LIST = 2;
}

enum SessionStatus {
  SESSION_STATUS_UNSPECIFIED = 0;
  SESSION_STATUS_PENDING = 1;
  SESSION_STATUS_OPEN = 3;
  SESSION_STATUS_CLOSED = 6;
}

enum SortMode {
  SORT_MODE_UNSPECIFIED = 0;
  SORT_MODE_MAX = 1;
  SORT_MODE_MIN = 2;
  SORT_MODE_AVERAGE = 3;
  SORT_MODE_SUM = 4;
  SORT_MODE_MEDIAN = 5;
}

enum SortOp {
  SORT_OP_UNSPECIFIED = 0;
  SORT_OP_ASCENDING = 500;
  SORT_OP_DESCENDING = 501;
}

enum SpaceType {
  SPACE_TYPE_UNSPECIFIED = 0;
  SPACE_TYPE_DESKTOP = 10;
  SPACE_TYPE_MOBILE = 20;
  SPACE_TYPE_EXTENSION = 30;
}

// The spacing scale for positions, padding, margin, etc. We don't enforce this.
enum Spacing {
  SPACING_UNSPECIFIED = 0;
  SPACING_S1 = 1;
  SPACING_S2 = 2;
  SPACING_S3 = 3;
  SPACING_S4 = 4;
  SPACING_S6 = 6;
  SPACING_S8 = 8;
  SPACING_S10 = 10;
  SPACING_S12 = 12;
  SPACING_S14 = 14;
  SPACING_S16 = 16;
  SPACING_S20 = 20;
  SPACING_S24 = 24;
  SPACING_S28 = 28;
  SPACING_S32 = 32;
  SPACING_S36 = 36;
  SPACING_S40 = 40;
  SPACING_S44 = 44;
  SPACING_S48 = 48;
  SPACING_S52 = 52;
  SPACING_S56 = 56;
  SPACING_S60 = 60;
  SPACING_S64 = 64;
  SPACING_S72 = 72;
  SPACING_S80 = 80;
  SPACING_S96 = 96;
  SPACING_S128 = 128;
  SPACING_S160 = 160;
  SPACING_S192 = 192;
  SPACING_S224 = 224;
  SPACING_S256 = 256;
}

enum StepType {
  STEP_TYPE_UNSPECIFIED = 0;
  STEP_TYPE_START = 1;
  STEP_TYPE_COMPLETE = 2;
  STEP_TYPE_FAIL = 3;
  STEP_TYPE_VALUE = 10;
  STEP_TYPE_TRIGGER = 11;
  STEP_TYPE_PASS = 50;
  STEP_TYPE_BLOCK = 51;
  STEP_TYPE_CODE = 52;
  STEP_TYPE_TEXT = 53;
  STEP_TYPE_SEND = 54;
  STEP_TYPE_MATCH = 100;
  STEP_TYPE_FILTER = 101;
  STEP_TYPE_LOOP = 102;
  STEP_TYPE_MERGE = 103;
  STEP_TYPE_FLATTEN = 105;
  STEP_TYPE_ACCUMULATE = 106;
  STEP_TYPE_REDUCE = 107;
  STEP_TYPE_ZIP = 108;
  STEP_TYPE_GROUP = 150;
}

enum StructType {
  STRUCT_TYPE_UNSPECIFIED = 0;
  STRUCT_TYPE_SESSION_CONTEXT = 10001;
  STRUCT_TYPE_EDIT_CONTEXT = 10002;
  STRUCT_TYPE_EDIT = 10005;
  STRUCT_TYPE_CHANGE = 10006;
  STRUCT_TYPE_CHANGE_VIGNETTE = 10007;
  STRUCT_TYPE_GRAPH_SCOPE = 10050;
  STRUCT_TYPE_CLIENT_ORIGIN = 10051;
  STRUCT_TYPE_NODE_REFERENCE = 10052;
  STRUCT_TYPE_PROPERTY_REFERENCE = 10053;
  STRUCT_TYPE_PATH = 10060;
  STRUCT_TYPE_PATH_TOKEN = 10061;
  STRUCT_TYPE_POLICY = 10100;
  STRUCT_TYPE_POLICY_RULE = 10101;
  STRUCT_TYPE_SUBJECT = 10102;
  STRUCT_TYPE_ACCESS_ZONE = 10104;
  STRUCT_TYPE_ACCESS_MATRIX = 10105;
  STRUCT_TYPE_ACCESS = 10107;
  STRUCT_TYPE_TEXT = 10150;
  STRUCT_TYPE_TEXT_LINE = 10151;
  STRUCT_TYPE_TEXT_SPAN = 10152;
  STRUCT_TYPE_TYPE_INFO = 10200;
  STRUCT_TYPE_TYPE_CONSTRAINT = 10201;
  STRUCT_TYPE_SCHEDULE = 10202;
  STRUCT_TYPE_FILE_REFERENCE = 10204;
  STRUCT_TYPE_ICON = 10205;
  STRUCT_TYPE_SECRET_REFERENCE = 10206;
  STRUCT_TYPE_FILE_INFO = 10207;
  STRUCT_TYPE_TRIGGER_INFO = 10208;
  STRUCT_TYPE_EXPRESSION = 10300;
  STRUCT_TYPE_AGGREGATION = 10301;
  STRUCT_TYPE_SELECTION = 10302;
  STRUCT_TYPE_QUERY_INFO = 10303;
  STRUCT_TYPE_READ_OPTIONS = 10304;
  STRUCT_TYPE_VALUE = 10305;
  STRUCT_TYPE_COMPUTED_VALUE = 10306;
  STRUCT_TYPE_CODE = 10400;
  STRUCT_TYPE_CODE_LINE = 10401;
  STRUCT_TYPE_PIPE = 10450;
  STRUCT_TYPE_RUN_ERROR = 10500;
  STRUCT_TYPE_RUN_OPTIONS = 10501;
  STRUCT_TYPE_RUN_ATTEMPT = 10502;
  STRUCT_TYPE_RUN_TRACE = 10503;
  STRUCT_TYPE_RUN_FRAME = 10504;
  STRUCT_TYPE_BREAKPOINT = 10520;
  STRUCT_TYPE_MODEL_OPTIONS = 10430;
  STRUCT_TYPE_LOG_INFO = 10550;
  STRUCT_TYPE_COLOR = 11000;
  STRUCT_TYPE_FONT = 11001;
  STRUCT_TYPE_BOX = 11002;
  STRUCT_TYPE_OFFSET = 11003;
  STRUCT_TYPE_TRANSFORM = 11004;
  STRUCT_TYPE_START_VIEW_STATE = 11200;
  STRUCT_TYPE_FEED_VIEW_STATE = 11201;
  STRUCT_TYPE_CHART_VIEW_STATE = 11202;
  STRUCT_TYPE_HISTORY_VIEW_STATE = 11203;
  STRUCT_TYPE_TIMELINE_VIEW_STATE = 11204;
  STRUCT_TYPE_USER_WIZARD_VIEW_STATE = 11205;
  STRUCT_TYPE_PAGE_VIEW_STATE = 11206;
  STRUCT_TYPE_TREE_VIEW_STATE = 11207;
}

enum TextLineType {
  TEXT_LINE_TYPE_UNSPECIFIED = 0;
  TEXT_LINE_TYPE_PLAIN = 1;
  TEXT_LINE_TYPE_HEADING_SMALL = 10;
  TEXT_LINE_TYPE_HEADING_MEDIUM = 11;
  TEXT_LINE_TYPE_HEADING_LARGE = 12;
  TEXT_LINE_TYPE_CALLOUT = 20;
  TEXT_LINE_TYPE_QUOTE = 21;
  TEXT_LINE_TYPE_LIST_BULLET = 30;
  TEXT_LINE_TYPE_LIST_NUMBERED = 31;
  TEXT_LINE_TYPE_LIST_UNCHECKED = 32;
  TEXT_LINE_TYPE_LIST_CHECKED = 33;
  TEXT_LINE_TYPE_DIVIDER = 40;
}

enum TimeInterval {
  TIME_INTERVAL_UNSPECIFIED = 0;
  TIME_INTERVAL_SECOND = 2;
  TIME_INTERVAL_MINUTE = 3;
  TIME_INTERVAL_HOUR = 4;
  TIME_INTERVAL_DAY = 5;
  TIME_INTERVAL_WEEK = 6;
  TIME_INTERVAL_MONTH = 7;
  TIME_INTERVAL_YEAR = 8;
}

enum TreeViewPreset {
  TREE_VIEW_PRESET_UNSPECIFIED = 0;
  TREE_VIEW_PRESET_EXPLORE = 1;
  TREE_VIEW_PRESET_OUTLINE = 2;
}

// Triggers for blocks (for both actual runs and pre-defined triggers).
enum TriggerType {
  TRIGGER_TYPE_UNSPECIFIED = 0;
  TRIGGER_TYPE_SCHEDULE = 1;
  TRIGGER_TYPE_SIGNAL = 2;
}

// The 'kind' of a Type.
enum TypeKind {
  TYPE_KIND_UNSPECIFIED = 0;
  TYPE_KIND_PRIMITIVE = 1;
  TYPE_KIND_STRUCT = 2;
  TYPE_KIND_NODE = 3;
  TYPE_KIND_ENUM = 4;
  TYPE_KIND_BASED_NODE = 5;
  TYPE_KIND_OBJECT = 6;
  TYPE_KIND_LITERAL = 7;
  TYPE_KIND_ALIAS = 10;
}

// Ways to use nodes.
enum UseType {
  USE_TYPE_UNSPECIFIED = 0;
  USE_TYPE_START = 40;
  USE_TYPE_PAUSE = 41;
  USE_TYPE_RESUME = 42;
  USE_TYPE_STOP = 43;
  USE_TYPE_KILL = 44;
  USE_TYPE_SEND = 45;
  USE_TYPE_RECEIVE = 46;
}

enum UserStatus {
  USER_STATUS_UNSPECIFIED = 0;
  USER_STATUS_INVITED = 1;
  USER_STATUS_RESERVED = 2;
  USER_STATUS_WAITLISTED = 3;
  USER_STATUS_REGISTERED = 4;
  USER_STATUS_ACTIVATED = 10;
}

// The stage of a User view.
enum UserWizardViewStage {
  USER_WIZARD_VIEW_STAGE_UNSPECIFIED = 0;
  USER_WIZARD_VIEW_STAGE_SIGN_UP = 1;
  USER_WIZARD_VIEW_STAGE_LOG_IN = 2;
}

// The style variant of a view.
enum Variant {
  VARIANT_UNSPECIFIED = 0;
  VARIANT_PRIMARY = 1;
  VARIANT_SECONDARY = 2;
  VARIANT_COMPACT = 3;
  VARIANT_STEALTH = 4;
}

enum ViewType {
  VIEW_TYPE_UNSPECIFIED = 0;
  VIEW_TYPE_USER_WIZARD = 1;
  VIEW_TYPE_BENCH_WIZARD = 2;
  VIEW_TYPE_EMPTY = 80;
  VIEW_TYPE_PAGE = 201;
  VIEW_TYPE_BLOCK = 202;
  VIEW_TYPE_FIELD = 203;
  VIEW_TYPE_DATABASE = 204;
  VIEW_TYPE_VIEW = 205;
  VIEW_TYPE_FLOW = 206;
  VIEW_TYPE_STEP = 207;
  VIEW_TYPE_TYPE = 208;
  VIEW_TYPE_VARIABLE = 209;
  VIEW_TYPE_OBJECT = 210;
  VIEW_TYPE_RUN = 211;
  VIEW_TYPE_LOG = 212;
  VIEW_TYPE_TREE = 400;
  VIEW_TYPE_INSPECT = 403;
  VIEW_TYPE_CREATE = 404;
  VIEW_TYPE_CHAT = 405;
  VIEW_TYPE_START = 406;
  VIEW_TYPE_FEED = 407;
  VIEW_TYPE_TIMELINE = 408;
  VIEW_TYPE_HISTORY = 409;
  VIEW_TYPE_WINDOW = 1000;
  VIEW_TYPE_TAB = 1002;
  VIEW_TYPE_SPLIT = 1003;
  VIEW_TYPE_SPLIT_DRAWER = 1004;
  VIEW_TYPE_STACK = 1010;
  VIEW_TYPE_DRAWER = 1011;
  VIEW_TYPE_SCROLL = 1012;
  VIEW_TYPE_GRID = 1013;
  VIEW_TYPE_LIST = 1020;
  VIEW_TYPE_TABLE = 1021;
  VIEW_TYPE_GROUP = 1030;
  VIEW_TYPE_SECTION = 1031;
  VIEW_TYPE_SPACER = 1050;
  VIEW_TYPE_DIVIDER = 1051;
  VIEW_TYPE_SHAPE = 1053;
  VIEW_TYPE_PROGRESS = 1054;
  VIEW_TYPE_AVATAR = 1055;
  VIEW_TYPE_BADGE = 1056;
  VIEW_TYPE_CHART = 1057;
  VIEW_TYPE_BUTTON = 1100;
  VIEW_TYPE_MULTI_BUTTON = 1101;
  VIEW_TYPE_LINK = 1110;
  VIEW_TYPE_VALUE = 1220;
  VIEW_TYPE_NUMBER = 1232;
  VIEW_TYPE_SLIDER = 1233;
  VIEW_TYPE_STRING = 1240;
  VIEW_TYPE_TEXT = 1241;
  VIEW_TYPE_CODE = 1242;
  VIEW_TYPE_JSON = 1243;
  VIEW_TYPE_TOGGLE = 1250;
  VIEW_TYPE_PICKER = 1253;
  VIEW_TYPE_CALENDAR = 1256;
  VIEW_TYPE_MAP = 1258;
  VIEW_TYPE_COLOR = 1260;
  VIEW_TYPE_ICON = 1261;
  VIEW_TYPE_FILE = 1270;
  VIEW_TYPE_IMAGE = 1273;
  VIEW_TYPE_AUDIO = 1274;
  VIEW_TYPE_VIDEO = 1275;
  VIEW_TYPE_DOCUMENT = 1276;
}

// An evaluated access.
message AccessData {
  ObjectType metatype = 1;
  AccessMode mode = 30;
  PolicyEffect decision = 31;
  AccessType verb = 32;
  NodeType node_type = 33;
  repeated PropertyReferenceData allowed_properties_ptr = 34;
}

// The materialized access matrix generated for a specific subject to quickly evaluate access for objects.
message AccessMatrixData {
  ObjectType metatype = 1;
  SubjectData subject = 30;
  repeated SubjectData identities = 32;
  repeated AccessZoneData scoped_zones = 33;
  repeated AccessZoneData base_zones = 34;
}

// The pre-filtered access rules for a given identity.
// Clients use this to indicate access rights, but - obviously - only our copy is binding.
message AccessZoneData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 4;
  string scope_id = 30;
  int32 identity_id = 31;
  repeated PolicyRuleData rules = 32;
}

// The result of an aggregation expression.
message AggregationData {
  ObjectType metatype = 1;
  AggregationOp op = 30;
  optional bool exists = 31;
  optional int32 count = 32;
  optional float scalar = 33;
}

// A box value. Absolute units are in pixels, ideally in Spacing scale.
message BoxData {
  ObjectType metatype = 1;
  optional int32 width = 50;
  optional int32 height = 51;
  optional float width_relative = 52;
  optional float height_relative = 53;
}

// A breakpoint in some context.
message BreakpointData {
  ObjectType metatype = 1;
  BreakpointKind kind = 30;
  BreakpointAction action = 31;
  optional ExpressionData condition = 40;
}

// A change is a sequence of related edits.
// Any edit not associated with a change is implicitly in its own change.
// The 'key' is the id the change will have in the Log.
message ChangeData {
  ObjectType metatype = 1;
  string key = 30;
  ChangeKind kind = 31;
  optional NodeReferenceData scope_ptr = 32;
  optional CodeData code = 33;
  repeated EditData edits = 34;
  repeated NodeReferenceData logs_ptr = 35;
  optional QueryInfoData logs_query = 36;
}

// A short non-binding summary of key properties at the time just before the edit.
// (so if you rename Block 'A' to 'B', the vignette will say 'A').
message ChangeVignetteData {
  ObjectType metatype = 1;
  optional string name = 30;
  optional string title = 31;
  optional IconData icon = 35;
}

// The state of a Chart view.
message ChartViewStateData {
  ObjectType metatype = 1;
}

// Information to identify a client.
message ClientOriginData {
  ObjectType metatype = 1;
  ClientType type = 30;
  optional string id = 31;
  optional string nonce = 32;
}

// Code composed of multiple lines.
message CodeData {
  ObjectType metatype = 1;
  repeated CodeLineData lines = 30;
}

// A line of code.
message CodeLineData {
  ObjectType metatype = 1;
  optional string content = 32;
}

// A color value.
message ColorData {
  ObjectType metatype = 1;
  optional ColorType type = 31;
  optional ColorShade shade = 32;
  optional string hex = 33;
}

// A value computed from an expression or code snippet.
message ComputedValueData {
  ObjectType metatype = 1;
  optional ExpressionData expression = 35;
  optional CodeData code = 36;
}

// An edit to a Node. Currently, edits are always on the property level (no sub-properties or values).
// 
// For updates/moves, the old/new node values are just the edited properties.
// For archive/delete/erase, the old node is the full node.
// (technically we don't *need* the old node if it's not an erase, but it's very convenient)
// Similarly, for create/upsert/unarchive/restore, the new node is the full node.
message EditData {
  ObjectType metatype = 1;
  string id = 2;
  EditType type = 30;
  NodeReferenceData node_ptr = 31;
  optional ChangeVignetteData vignette = 32;
  repeated int32 properties = 40;
  optional SomeNodeData old_node_partial = 41;
  optional SomeNodeData new_node_partial = 42;
  GraphScopeData scope = 60;
  optional string change_key = 61;
  optional ChangeCategory category = 62;
  optional NodeReferenceData subject_ptr = 63;
  optional ClientOriginData origin = 64;
  optional EditContextData context = 65;
  google.protobuf.Timestamp edited_at = 66;
  optional int64 revision = 67;
  optional int64 epoch = 68;
}

// Additional context for a specific edit (per-edit variable subset of Session context).
message EditContextData {
  ObjectType metatype = 1;
  optional NodeReferenceData block_ptr = 70;
  optional NodeReferenceData step_ptr = 71;
  optional NodeReferenceData session_ptr = 72;
  optional NodeReferenceData run_ptr = 73;
  optional NodeReferenceData run_root_ptr = 74;
  optional NodeReferenceData identity_ptr = 75;
}

// An expression like a value, function, comparison or such.
message ExpressionData {
  ObjectType metatype = 1;
  ExpressionOp op = 30;
  optional PropertyReferenceData property_ptr = 31;
  repeated ExpressionData clauses = 35;
  optional google.protobuf.Struct value_packed = 36;
  optional SortMode sort_mode = 38;
  optional float tolerance = 39;
}

// The state of a Feed view.
message FeedViewStateData {
  ObjectType metatype = 1;
  optional NodeType node_type = 30;
  optional ExpressionData filter = 31;
  repeated string filter_pills = 99;
}

// File metadata.
message FileInfoData {
  ObjectType metatype = 1;
  FileKind kind = 40;
  string title = 41;
  optional NodeReferenceData drive_ptr = 42;
  optional string external_url = 43;
  optional bytes inline_content = 44;
  FileType coarse_type = 50;
  optional string mime_type = 51;
  optional FileFormat format = 52;
  int64 size = 53;
  optional string sha256 = 54;
  optional int32 width = 55;
  optional int32 height = 56;
  optional float aspect_ratio = 57;
  optional string codec = 58;
  optional float duration = 60;
  optional int32 bitrate = 61;
  optional int32 channels = 62;
  optional int32 sample_rate = 63;
}

// A reference to a File. Extends NodeReference with file-specific metadata.
message FileReferenceData {
  ObjectType metatype = 1;
  NodeType type = 30;
  optional string id = 31;
  optional string ck = 32;
  optional string bench_id = 33;
  optional string base_ck = 34;
  optional string base_bench_id = 35;
  FileKind kind = 40;
  string title = 41;
  optional NodeReferenceData drive_ptr = 42;
  optional string external_url = 43;
  optional bytes inline_content = 44;
  FileType coarse_type = 50;
  optional string mime_type = 51;
  optional FileFormat format = 52;
  int64 size = 53;
  optional string sha256 = 54;
  optional int32 width = 55;
  optional int32 height = 56;
  optional float aspect_ratio = 57;
  optional string codec = 58;
  optional float duration = 60;
  optional int32 bitrate = 61;
  optional int32 channels = 62;
  optional int32 sample_rate = 63;
}

// A font value.
message FontData {
  ObjectType metatype = 1;
  optional FontType type = 31;
  optional FontWeight weight = 32;
  optional FontSize size = 33;
}

// The scope for an operation on the Bench graph.
message GraphScopeData {
  ObjectType metatype = 1;
  optional string bench_id = 30;
  optional string package_id = 31;
}

// The state of a History view.
message HistoryViewStateData {
  ObjectType metatype = 1;
}

// An icon to be displayed in some view.
message IconData {
  ObjectType metatype = 1;
  IconKind kind = 30;
  optional string emoji = 31;
  optional string fa_name = 33;
  optional string vs_name = 34;
  optional ColorData color = 40;
}

// A simple log for user-generated logs at runtime.
// This is like a mini-Log that we can attach to Runs and also copy into the combined Log.
// 
// Conveniently, we can make this tiny because the containing Run already has all the context.
// 
// NOTE :Incomplete: also capture edit events as mini logs?
// NOTE :Incomplete: copy Run.logs into Logs somewhere
message LogInfoData {
  ObjectType metatype = 1;
  google.protobuf.Timestamp created_at = 11;
  LogLevel level = 31;
  optional TextData text = 61;
  optional string text_plain = 62;
  optional google.protobuf.Struct value_packed = 65;
}

// Options for running an ML model.
message ModelOptionsData {
  ObjectType metatype = 1;
  optional ModelProvider provider = 30;
  optional ModelType model = 31;
}

// A plain reference to a Node.
// We include the Bench and 'ck' where available.
// Base = the node is 'based' on (like Record.parent->Block, Signal.type->Block).
message NodeReferenceData {
  ObjectType metatype = 1;
  NodeType type = 30;
  optional string id = 31;
  optional string ck = 32;
  optional string bench_id = 33;
  optional string base_ck = 34;
  optional string base_bench_id = 35;
}

// A position value. Absolute units are in pixels, ideally in Spacing scale.
message OffsetData {
  ObjectType metatype = 1;
  optional int32 top = 40;
  optional int32 right = 41;
  optional int32 bottom = 42;
  optional int32 left = 43;
  optional float top_relative = 44;
  optional float right_relative = 45;
  optional float bottom_relative = 46;
  optional float left_relative = 47;
}

// The state of a Page view.
message PageViewStateData {
  ObjectType metatype = 1;
}

// A human-readable Bench path to reference nodes.
// Paths names and special operators combined with slashes.
// Fields may also be accessed with '.' separators.
// 
// Relative:
// / -> root of this package
// . -> current node
// .. -> parent of current node
// ../.. -> parent of parent of current node
// 
// Node -> ./Node -> node 'Node' relative to current node
// >Sibling -> sibling 'Sibling' of current node
// ~ -> closest container
// ~Node -> closest container with node 'Node'
// ^Name -> uniquely named node or child in closest container
// .property -> 'property' of current node
// 
// Node2.property -> 'property' of 'Node2' (there must not be anything after .property)
// Node1/Node2/Node3 -> child 'Node3' of child 'Node2' of child 'Node1' of current node
// 
// @bench -> absolute reference to bench 'bench'
// @bench/Node1/Node2/Node3 -> absolute reference to 'Node3' in current package of @bench
message PathData {
  ObjectType metatype = 1;
  repeated PathTokenData tokens = 31;
}

// A semantic part of a Bench path.
message PathTokenData {
  ObjectType metatype = 1;
  PathTokenType type = 31;
  optional string name = 32;
}

// A connection between two Steps in a FlowBlock.
message PipeData {
  ObjectType metatype = 1;
  PipeType type = 30;
  NodeReferenceData source_ptr = 31;
}

// A policy regulating access to nodes within its scope.
// The scope is determined by where its attached, but may be further restricted using 'scopes'.
// 
// The basics of access control:
// 1. Access is DENIED implicitly unless explicitly and fully ALLOWED.
// 2. Policies are either attached
// a. directly to nodes (scoped to the node)
// b. or to a delegate (full scope or less as specified)
// 3. Policies are evaluated in order up the node graph, first match decides*.
// (This means you can read a sub block but not its parent.)
// 4. Every identity/role/... applicable to a subject is evaluated separately and *any* allow wins.
// 
// * Conceptually, we do 'ray trace' up the graph for every node/property/...,
// but actually doing that for every request is prohibitively expensive.
// Instead, we 'rasterize' an 'access matrix' and use 'zones' as a shortcut.
message PolicyData {
  ObjectType metatype = 1;
  string name = 30;
  optional TextData text = 31;
  repeated PolicyRuleData rules = 32;
  repeated NodeReferenceData scopes_ptr = 33;
}

// A rule in a policy: [subject] + [effect] [verb] + [object] [if condition].
// Subject, verb and object are ORed, in-group conditions are ANDed.
// (where None/empty -> wildcard, any value -> filter)
message PolicyRuleData {
  ObjectType metatype = 1;
  string name = 30;
  optional TextData text = 31;
  optional bool subject_is_delegated = 40;
  optional bool subject_is_authenticated = 41;
  optional bool subject_is_staff = 42;
  optional bool subject_is_member = 43;
  optional bool subject_is_owner = 44;
  PolicyEffect effect = 60;
  repeated AccessType verbs = 61;
  repeated AccessKind verb_kinds = 62;
  repeated NodeType object_node_types = 80;
  repeated PropertyReferenceData object_properties_ptr = 81;
  optional bool object_properties_is_system = 82;
  optional bool object_properties_is_sensitive = 83;
  optional bool object_properties_is_kernel = 84;
}

// A reference to a builtin object's Property.
// If type is unset, this refers to a base property in one of the base BuiltinObject types.
message PropertyReferenceData {
  ObjectType metatype = 1;
  optional ObjectType type = 30;
  int32 id = 31;
  optional NodeType references_node = 32;
}

// A stored query.
message QueryInfoData {
  ObjectType metatype = 1;
  ReadType read_type = 40;
  NodeType node_type = 41;
  optional NodeReferenceData base_ptr = 42;
  optional ExpressionData filter = 43;
  repeated ExpressionData sort = 44;
}

// Fine-grained options to a read request.
// This is an addition to primary options (like the filter for a search or aggregation).
message ReadOptionsData {
  ObjectType metatype = 1;
  repeated NodeType ancestor_types = 31;
  repeated NodeType descendant_types = 32;
  repeated PropertyReferenceData include_properties_ptr = 40;
  repeated PropertyReferenceData exclude_properties_ptr = 41;
  repeated PropertyReferenceData select_properties_ptr = 42;
  bool select_all_properties = 43;
  bool include_hidden = 50;
}

// A single attempt at a Run.
message RunAttemptData {
  ObjectType metatype = 1;
  RunStatus status = 30;
  optional float duration = 31;
  optional google.protobuf.Timestamp started_at = 32;
  optional int32 started_epoch = 33;
  optional google.protobuf.Timestamp terminated_at = 35;
  optional int32 terminated_epoch = 36;
  optional RunErrorData error = 37;
}

// An error that occurred in the context of a Run.
message RunErrorData {
  ObjectType metatype = 1;
  RunErrorKind kind = 30;
  RunErrorType type = 31;
  optional string title = 32;
  optional TextData text = 33;
  optional NodeReferenceData node_ptr = 34;
  optional RunTraceData trace = 35;
}

// A single frame in a stacktrace.
message RunFrameData {
  ObjectType metatype = 1;
}

// Options for running something.
// Limits are per top level run context (i.e. the root Run in some Session).
message RunOptionsData {
  ObjectType metatype = 1;
  optional int32 max_runs = 30;
  optional int32 max_concurrency = 31;
  optional int32 max_attempts = 32;
  optional float timeout = 33;
  optional float retry_interval = 40;
  optional float backoff = 41;
  optional float max_retry_interval = 42;
  optional float jitter = 43;
  repeated RunErrorType retry_on = 44;
  repeated BreakpointData breakpoints = 50;
  optional ModelOptionsData model_options = 60;
}

// A stacktrace for a Run.
message RunTraceData {
  ObjectType metatype = 1;
  repeated RunFrameData frames = 30;
}

// The time-based schedule of something.
message ScheduleData {
  ObjectType metatype = 1;
  ScheduleType type = 30;
  optional string timezone = 31;
  int32 every = 40;
  TimeInterval interval = 41;
  optional google.protobuf.Duration offset = 42;
  optional string cron = 50;
}

// A reference to a Secret. Extends NodeReference with secret-specific metadata.
message SecretReferenceData {
  ObjectType metatype = 1;
  NodeType type = 30;
  optional string id = 31;
  optional string ck = 32;
  optional string bench_id = 33;
  optional string base_ck = 34;
  optional string base_bench_id = 35;
  string title = 43;
}

// A selection of nodes/values.
message SelectionData {
  ObjectType metatype = 1;
  SelectionKind kind = 30;
  repeated NodeReferenceData nodes_ptr = 31;
  optional NodeReferenceData from_node_ptr = 32;
  optional NodeReferenceData to_node_ptr = 33;
}

// Context information for runtime nodes created in a session.
message SessionContextData {
  ObjectType metatype = 1;
  optional NodeReferenceData block_ptr = 70;
  optional NodeReferenceData step_ptr = 71;
  optional NodeReferenceData session_ptr = 72;
  optional NodeReferenceData run_ptr = 73;
  optional NodeReferenceData run_root_ptr = 74;
  optional NodeReferenceData client_ptr = 75;
  optional NodeReferenceData machine_ptr = 76;
  optional NodeReferenceData server_ptr = 77;
  optional NodeReferenceData user_ptr = 78;
  optional NodeReferenceData identity_ptr = 79;
}

// The state of a Start view.
message StartViewStateData {
  ObjectType metatype = 1;
  optional google.protobuf.Struct inputs_packed = 30;
  optional NodeReferenceData last_run_ptr = 40;
  optional google.protobuf.Struct last_outputs_packed = 41;
  optional FeedViewStateData feed = 50;
}

// The <whoever/whatever> issuing a request. Unknown/ignored attributes are unset.
// (We unset various combinations of attributes to evaluate the access of acting subjects independently.)
message SubjectData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional bool is_authenticated = 30;
  optional bool is_staff = 31;
  optional bool is_system = 32;
  optional NodeReferenceData client_ptr = 40;
  optional NodeReferenceData user_ptr = 41;
  optional NodeReferenceData server_ptr = 42;
  optional NodeReferenceData identity_ptr = 50;
  repeated NodeReferenceData badges_ptr = 51;
  repeated NodeReferenceData owned_ptr = 52;
  repeated NodeReferenceData memberships_ptr = 53;
  repeated NodeReferenceData roles_ptr = 54;
}

// Rich, markdown-inspired Text with mentions, lists & other extensions.
// Text is structured into lines, which contain spans.
// Formatting can be applied at per Text, line and span.
message TextData {
  ObjectType metatype = 1;
  repeated TextLineData lines = 32;
}

// A single line of Text with formatting, composed of spans.
// A line may contain hard breaks, so it's effectively a paragraph.
message TextLineData {
  ObjectType metatype = 1;
  TextLineType type = 30;
  repeated TextSpanData spans = 33;
  optional ColorType color = 50;
  optional bool is_bold = 60;
  optional bool is_italic = 61;
  optional bool is_strikethrough = 62;
  optional bool is_underline = 63;
  optional bool is_code = 64;
}

// A span of text with optional formatting.
message TextSpanData {
  ObjectType metatype = 1;
  optional string content = 33;
  oneof node_ptr {
    NodeReferenceData node_ptr_node = 340;
    FileReferenceData node_ptr_file = 341;
    SecretReferenceData node_ptr_secret = 342;
  };
  optional ColorType color = 50;
  optional bool is_bold = 60;
  optional bool is_italic = 61;
  optional bool is_strikethrough = 62;
  optional bool is_underline = 63;
  optional bool is_code = 64;
}

// The state of a Timeline view.
message TimelineViewStateData {
  ObjectType metatype = 1;
}

// A transform in 2D space.
message TransformData {
  ObjectType metatype = 1;
  optional int32 translate_x = 30;
  optional int32 translate_y = 31;
  optional float scale_x = 33;
  optional float scale_y = 34;
  optional float skew_x = 36;
  optional float skew_y = 37;
  optional int32 rotate_x = 40;
}

// The state of a Tree view.
message TreeViewStateData {
  ObjectType metatype = 1;
  repeated NodeType node_types = 35;
  optional bool filter_is_page = 36;
  optional bool is_default_expanded = 37;
  optional TreeViewPreset preset = 99;
}

// The basic information describing a trigger.
message TriggerInfoData {
  ObjectType metatype = 1;
  optional int32 processed_epoch = 40;
  optional ScheduleData schedule = 50;
  optional NodeReferenceData signal_ptr = 51;
  optional ExpressionData condition = 52;
}

// A simple constraint on the values of a type. :TypeConstraint
// Basically a more restricted form of a condition Expression.
message TypeConstraintData {
  ObjectType metatype = 1;
  optional float min_value = 40;
  optional float max_value = 41;
  optional float step_value = 42;
  optional int32 min_length = 50;
  optional int32 max_length = 51;
  optional string regex = 60;
  optional string starts_with = 61;
  optional string ends_with = 62;
  optional BlockType block_type = 70;
  optional StepType step_type = 71;
  optional FileType file_type = 72;
  optional FileFormat file_format = 73;
}

// A type from the type system.
message TypeInfoData {
  ObjectType metatype = 1;
  TypeKind kind = 40;
  optional PrimitiveType primitive_type = 41;
  optional BenchType bench_type = 42;
  optional NodeReferenceData base_type_ptr = 43;
  optional FieldZone base_field_zone = 44;
  optional google.protobuf.Struct default_packed = 50;
  optional ExpressionData condition = 54;
  optional TypeConstraintData constraint = 55;
  bool is_list = 60;
  bool is_secret = 61;
  bool is_required = 62;
}

// The state of a User view.
message UserWizardViewStateData {
  ObjectType metatype = 1;
  optional UserWizardViewStage stage = 30;
}

// A generic typed 'freeform' value.
message ValueData {
  ObjectType metatype = 1;
  TypeInfoData type = 31;
  optional string name = 32;
  optional TextData text = 34;
  optional google.protobuf.Struct value_packed = 35;
}

// Attach a badge to a node with an inline definition.
// A badge's policies are delegated to the 'holder' (any client presenting its secrets).
// The delegated policies apply at the parent scope OR given scopes (which must be below parent's).
message BadgeData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 31;
  repeated PolicyData delegated_policies = 32;
  optional google.protobuf.Timestamp expires_at = 33;
  optional string key = 40;
  optional string key_hash = 41;
  optional string password = 42;
  optional string password_hash = 43;
}

// A Bench is an AI-native operating system for a new generation of fully integrated, fluid software.
message BenchData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional NodeReferenceData main_handle_ptr = 31;
  string slug = 32;
  string name = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  optional NodeReferenceData owner_ptr = 36;
  Region region = 37;
  optional string encryption_key = 38;
  repeated PolicyData policies = 39;
  optional NodeReferenceData main_store_ptr = 40;
  optional NodeReferenceData main_server_ptr = 41;
  optional NodeReferenceData main_drive_ptr = 42;
  optional NodeReferenceData main_branch_ptr = 50;
}

// A building block with logic, types, UI, data, auth, AI, ...
message BlockData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  BlockType type = 30;
  string name = 32;
  string order_key = 33;
  repeated NodeReferenceData bases_ptr = 35;
  optional TextData text = 36;
  optional IconData icon = 37;
  optional TypeInfoData value_type = 39;
  optional google.protobuf.Struct value_packed = 40;
  optional CodeData code = 42;
  optional RunOptionsData run_options = 43;
  repeated NodeReferenceData roles_ptr = 46;
  optional NodeReferenceData identity_ptr = 47;
  repeated PolicyData policies = 48;
  repeated PolicyData delegated_policies = 49;
  bool is_builtin = 60;
  bool is_owned = 61;
  bool is_paused = 64;
}

// A branch is a lineage of Bench history.
message BranchData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional string slug = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  repeated PolicyData policies = 36;
  optional NodeReferenceData main_package_ptr = 40;
  optional NodeReferenceData base_ptr = 41;
  bool is_overlay = 60;
  bool is_light = 61;
}

// A client to a Bench.
message ClientData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  ClientType type = 30;
  string name = 32;
  optional string device_type = 40;
  optional string device_name = 41;
  optional string operating_system = 42;
  optional string browser_name = 43;
  optional string browser_version = 44;
  optional string place_id = 45;
  optional string access_token = 50;
  google.protobuf.Timestamp seen_at = 51;
  optional google.protobuf.Timestamp logged_in_at = 52;
  optional NodeReferenceData space_ptr = 60;
  optional NodeReferenceData machine_ptr = 61;
}

// A dependency on another Bench (pointing to a specific Package).
// If scopes are given, only those blocks are included.
message DependencyData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  repeated NodeReferenceData scopes_ptr = 30;
  NodeReferenceData dependency_ptr = 40;
}

// Drive for file storage.
message DriveData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  optional ResourceStatus current_status = 37;
}

// A used-defined attribute of some value
// (Bench defines Properties for Nodes/Structs, Users define Fields for Values inside those).
message FieldData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 30;
  string order_key = 31;
  FieldZone zone = 32;
  optional TextData text = 33;
  optional IconData icon = 34;
  optional google.protobuf.Struct value_packed = 35;
  TypeKind kind = 40;
  optional PrimitiveType primitive_type = 41;
  optional BenchType bench_type = 42;
  optional NodeReferenceData base_type_ptr = 43;
  optional FieldZone base_field_zone = 44;
  optional google.protobuf.Struct default_packed = 50;
  optional ExpressionData condition = 54;
  optional TypeConstraintData constraint = 55;
  bool is_list = 60;
  bool is_secret = 61;
  bool is_required = 62;
}

// A file stored somewhere (like a Drive, orexternally).
// De-duplicated so that there's only one File per unique file content for our own files.
message FileData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional FileRetentionMode retention = 30;
  optional google.protobuf.Timestamp expires_at = 31;
  FileKind kind = 40;
  string title = 41;
  optional NodeReferenceData drive_ptr = 42;
  optional string external_url = 43;
  optional bytes inline_content = 44;
  FileType coarse_type = 50;
  optional string mime_type = 51;
  optional FileFormat format = 52;
  int64 size = 53;
  optional string sha256 = 54;
  optional int32 width = 55;
  optional int32 height = 56;
  optional float aspect_ratio = 57;
  optional string codec = 58;
  optional float duration = 60;
  optional int32 bitrate = 61;
  optional int32 channels = 62;
  optional int32 sample_rate = 63;
}

// A Bench @handle. Can only be created/edited by the system.
message HandleData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string slug = 30;
}

// An invitation to become a member of this Bench.
message InviteData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional NodeReferenceData user_ptr = 30;
  optional string user_email = 31;
  bool is_owner = 32;
  repeated NodeReferenceData roles_ptr = 33;
}

// A Log of something happening in a Bench.
message LogData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  LogKind kind = 30;
  LogLevel level = 31;
  optional NodeReferenceData change_ptr = 32;
  optional AccessType type = 40;
  optional NodeReferenceData node_ptr = 41;
  repeated int32 properties = 42;
  optional google.protobuf.Struct old_node_packed = 43;
  optional google.protobuf.Struct old_node_secret_packed = 44;
  optional google.protobuf.Struct new_node_packed = 45;
  optional google.protobuf.Struct new_node_secret_packed = 46;
  optional int64 new_revision = 47;
  optional ChangeCategory category = 48;
  optional ChangeVignetteData vignette = 49;
  optional NodeReferenceData block_ptr = 70;
  optional NodeReferenceData step_ptr = 71;
  optional NodeReferenceData session_ptr = 72;
  optional NodeReferenceData run_ptr = 73;
  optional NodeReferenceData run_root_ptr = 74;
  optional NodeReferenceData client_ptr = 75;
  optional NodeReferenceData machine_ptr = 76;
  optional NodeReferenceData server_ptr = 77;
  optional NodeReferenceData user_ptr = 78;
  optional NodeReferenceData identity_ptr = 79;
}

// A Machine provides some isolated compute, usually for a Server.
// A Machine may also be manually provisioned with specific image/profiles.
message MachineData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  optional ResourceStatus current_status = 37;
  optional string version = 40;
  optional string current_version = 41;
  optional string external_name = 42;
  optional string external_id = 43;
  optional string connection_uri = 44;
  float cpu = 50;
  optional float current_cpu = 51;
  float ram = 52;
  optional float current_ram = 53;
  optional google.protobuf.Timestamp started_at = 60;
  optional google.protobuf.Timestamp terminated_at = 61;
  optional google.protobuf.Timestamp active_at = 62;
}

// A membership to this Bench (and its owner if it's the main Bench).
message MembershipData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NodeReferenceData user_ptr = 30;
  bool is_owner = 31;
}

// A Message by a User or program (author = created_by).
// If the parent is also a Message, then this is part of a thread. Threads may be nested.
message MessageData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NodeReferenceData origin_ptr = 32;
  optional PathData path = 33;
  optional NodeReferenceData reply_to_ptr = 34;
  optional string title = 40;
  optional TextData text = 41;
  optional google.protobuf.Struct value_packed = 42;
  bool is_pinned = 50;
}

// A Node with properties like a Struct and a global identity in our graph.
// Conceptually, all nodes live together happily in a single giant supergraph.
// In practice, there are multiple stores and we load smaller subgraphs at runtime.
// Nodes resolve references to each through a super graph composed of *currently loaded* NodeGraphs.
message BaseNodeData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
}

// A Notification for a Bench (author = created_by).
message NotificationData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NotificationKind kind = 30;
  NodeReferenceData type_ptr = 32;
  optional google.protobuf.Timestamp expires_at = 33;
  optional google.protobuf.Timestamp read_at = 34;
  optional string title = 40;
  optional TextData text = 41;
  optional google.protobuf.Struct value_packed = 42;
}

// A Bench organization with Users as members.
// Until activation only its creator has access.
message OrganizationData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional NodeReferenceData main_handle_ptr = 31;
  optional string slug = 32;
  string name = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  optional NodeReferenceData main_bench_ptr = 36;
  OrganizationStatus status = 37;
}

// A package is a version of a Bench in a Branch.
message PackageData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional TextData text = 34;
  optional IconData icon = 35;
  repeated PolicyData policies = 36;
  optional NodeReferenceData base_ptr = 40;
  bool is_snapshot = 60;
  bool is_overlay = 61;
  bool is_paused = 65;
}

// A stored query with identity.
message QueryData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 30;
  string order_key = 31;
  ReadType read_type = 40;
  NodeType node_type = 41;
  optional NodeReferenceData base_ptr = 42;
  optional ExpressionData filter = 43;
  repeated ExpressionData sort = 44;
}

// A record in a DatabaseBlock.
// If the block is_materialized, the backing table is a real Postgres table.
message RecordData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional google.protobuf.Struct value_packed = 30;
}

// A 'run' of Blocks (and Steps within them) or 'lambdas' (just Code/Text).
// When 'running' something that's not directly runnable (like a Text Block, Text Step or Text Lambda),
// we implicitly pass it to the corresponding default Text program.
// Once terminated, a Run is effectively immutable.
message RunData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  RunKind kind = 30;
  optional NodeReferenceData root_ptr = 32;
  optional CodeData code = 36;
  optional RunOptionsData options = 38;
  RunStatus status = 40;
  optional RunStatus current_status = 41;
  optional float duration = 42;
  repeated RunAttemptData attempts = 43;
  optional RunErrorData error = 44;
  optional google.protobuf.Timestamp scheduled_at = 45;
  optional int32 scheduled_epoch = 46;
  optional google.protobuf.Timestamp started_at = 47;
  optional int32 started_epoch = 48;
  optional google.protobuf.Timestamp halted_at = 49;
  optional int32 halted_epoch = 50;
  optional NodeReferenceData halted_on_run_ptr = 51;
  optional google.protobuf.Timestamp terminated_at = 53;
  optional int32 terminated_epoch = 54;
  optional google.protobuf.Struct inputs_packed = 60;
  optional google.protobuf.Struct outputs_packed = 61;
  optional google.protobuf.Struct value_packed = 62;
  repeated LogInfoData logs = 65;
  optional NodeReferenceData block_ptr = 70;
  optional NodeReferenceData step_ptr = 71;
  optional NodeReferenceData session_ptr = 72;
  optional NodeReferenceData run_ptr = 73;
  optional NodeReferenceData run_root_ptr = 74;
  optional NodeReferenceData client_ptr = 75;
  optional NodeReferenceData machine_ptr = 76;
  optional NodeReferenceData server_ptr = 77;
  optional NodeReferenceData user_ptr = 78;
  optional NodeReferenceData identity_ptr = 79;
}

// A secret value.
message SecretData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string title = 33;
  TypeInfoData value_type = 40;
  optional google.protobuf.Struct value_packed = 41;
}

// A server provides some compute for a Bench's Runtime.
// Physical compute is materialized (on-demand) as Machines.
message ServerData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  optional ResourceStatus current_status = 37;
  optional string version = 40;
  optional string current_version = 41;
  optional float min_cpu = 50;
  optional float max_cpu = 51;
  optional float min_ram = 52;
  optional float max_ram = 53;
  optional google.protobuf.Timestamp active_at = 60;
  optional google.protobuf.Timestamp bumped_at = 61;
}

// A managed Session for interacting with and running a Bench in a Client.
// If a Run spans multiple Clients, each Client will have its own Session.
// On some Clients a Session may persist across Runs (like in the web client).
// Once closed, a Session (like a Run) is effectively immutable.
message SessionData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  SessionStatus status = 40;
  optional float duration = 41;
  optional google.protobuf.Timestamp opened_at = 42;
  optional google.protobuf.Timestamp closed_at = 43;
  optional NodeReferenceData client_ptr = 61;
  optional NodeReferenceData server_ptr = 62;
  optional NodeReferenceData machine_ptr = 63;
  optional NodeReferenceData user_ptr = 64;
}

// A Signal emitted in this Bench, usually received in Triggers.
message SignalData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NodeReferenceData type_ptr = 32;
  optional google.protobuf.Struct value_packed = 42;
  optional NodeReferenceData block_ptr = 70;
  optional NodeReferenceData step_ptr = 71;
  optional NodeReferenceData session_ptr = 72;
  optional NodeReferenceData run_ptr = 73;
  optional NodeReferenceData run_root_ptr = 74;
  optional NodeReferenceData client_ptr = 75;
  optional NodeReferenceData machine_ptr = 76;
  optional NodeReferenceData server_ptr = 77;
  optional NodeReferenceData user_ptr = 78;
  optional NodeReferenceData identity_ptr = 79;
}

// A reference to another node in some graph that wasn't available for some reason (usually permissions).
message SkipData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NodeReferenceData reference_ptr = 30;
  optional string order_key = 31;
}

// A space for a user to interact with the Bench.
message SpaceData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  SpaceType type = 30;
  string name = 31;
  optional TextData text = 32;
  string order_key = 33;
  repeated PolicyData policies = 34;
  optional Anchor bar_position = 40;
  optional SelectionData focus = 70;
  optional NodeReferenceData inspection_ptr = 75;
  optional NodeReferenceData base_ptr = 76;
}

// An data or control flow node in a FlowBlock.
message StepData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  StepType type = 30;
  string name = 32;
  string order_key = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  optional RunOptionsData run_options = 36;
  repeated PipeData incoming_pipes = 37;
  optional TypeInfoData value_type = 40;
  optional google.protobuf.Struct value_packed = 41;
  optional NodeReferenceData node_ptr = 43;
  optional CodeData code = 44;
  optional ExpressionData condition = 45;
  repeated NodeReferenceData roles_ptr = 46;
  optional NodeReferenceData identity_ptr = 47;
  repeated PolicyData policies = 48;
  optional OffsetData position = 60;
  optional BoxData size = 61;
}

// A trusty Postgres-compatible database.
message StoreData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  optional ResourceStatus current_status = 37;
  optional string version = 40;
  optional string current_version = 41;
  optional string external_name = 50;
  optional string external_id = 51;
  optional string connection_uri = 52;
}

// A trigger to run the node it is attached to (like a Block).
message TriggerData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  TriggerType type = 30;
  string name = 31;
  optional int32 processed_epoch = 40;
  optional ScheduleData schedule = 50;
  optional NodeReferenceData signal_ptr = 51;
  optional ExpressionData condition = 52;
  bool is_paused = 60;
}

// A Bench user.
message UserData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional NodeReferenceData main_handle_ptr = 31;
  optional string slug = 32;
  string name = 33;
  optional TextData text = 34;
  optional string email = 35;
  optional IconData icon = 36;
  optional NodeReferenceData main_bench_ptr = 37;
  UserStatus status = 38;
  optional bytes password_salt = 50;
  optional bytes password_hash = 51;
  optional google.protobuf.Timestamp last_logged_in_at = 70;
  bool is_staff = 90;
}

// A view of a user interface in a Bench.
message ViewData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  ViewType type = 30;
  string name = 31;
  optional string title = 32;
  optional TextData text = 33;
  string order_key = 34;
  optional IconData icon = 35;
  optional TypeInfoData value_type = 40;
  optional google.protobuf.Struct value_packed = 41;
  oneof node_ptr {
    NodeReferenceData node_ptr_node = 420;
    FileReferenceData node_ptr_file = 421;
    SecretReferenceData node_ptr_secret = 422;
  };
  optional Variant variant = 50;
  optional FontData font = 51;
  optional OffsetData position = 60;
  optional BoxData size = 61;
  optional OffsetData margin = 62;
  optional OffsetData padding = 63;
  optional Orientation orientation = 64;
  optional Alignment alignment = 65;
  optional TransformData transform = 66;
  optional SelectionData selection = 70;
  optional SelectionData focus = 71;
  optional SelectionData expansion = 72;
  optional bool is_visible = 80;
  optional bool is_disabled = 81;
  optional bool is_input = 82;
  optional bool is_inline = 83;
  optional bool is_loading = 90;
}

message SomeNodeData {
  oneof node {
    BenchData bench = 1;
    UserData user = 2;
    OrganizationData organization = 3;
    HandleData handle = 4;
    ClientData client = 5;
    ServerData server = 6;
    StoreData store = 7;
    MachineData machine = 8;
    DriveData drive = 9;
    MembershipData membership = 10;
    InviteData invite = 11;
    BranchData branch = 12;
    PackageData package = 13;
    DependencyData dependency = 14;
    SpaceData space = 15;
    BlockData block = 16;
    TriggerData trigger = 17;
    FieldData field = 18;
    QueryData query = 19;
    ViewData view = 20;
    StepData step = 21;
    BadgeData badge = 22;
    FileData file = 23;
    SecretData secret = 24;
    MessageData message = 25;
    RecordData record = 26;
    NotificationData notification = 27;
    SessionData session = 28;
    RunData run = 29;
    SignalData signal = 30;
    LogData log = 31;
    SkipData skip = 32;
  };
}

