syntax = "proto3";

package symbolx.bench;

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/struct.proto";
import "proto/google/type/datetime.proto";
import "proto/google/type/date.proto";
import "proto/google/type/timeofday.proto";

enum EnumType {
  ENUM_TYPE_UNSPECIFIED = 0;
  ENUM_TYPE_ENUM_TYPE = 20001;
  ENUM_TYPE_NODE_TYPE = 20002;
  ENUM_TYPE_STRUCT_TYPE = 20003;
  ENUM_TYPE_OBJECT_TYPE = 20004;
  ENUM_TYPE_ACCESS_MODE = 20501;
  ENUM_TYPE_ACCESS_KIND = 20502;
  ENUM_TYPE_QUERY_TYPE = 20503;
  ENUM_TYPE_EDIT_TYPE = 20504;
  ENUM_TYPE_USE_TYPE = 20505;
  ENUM_TYPE_ACCESS_TYPE = 20506;
  ENUM_TYPE_CHANGE_CATEGORY = 20507;
  ENUM_TYPE_EDIT_OPERATION_TYPE = 20508;
  ENUM_TYPE_POLICY_EFFECT = 20509;
  ENUM_TYPE_BENCH_TYPE = 21001;
  ENUM_TYPE_CLOUD = 21002;
  ENUM_TYPE_REGION = 21003;
  ENUM_TYPE_REGION_ZONE = 21004;
  ENUM_TYPE_REGION_AREA = 21005;
  ENUM_TYPE_RESOURCE_STATUS = 21006;
  ENUM_TYPE_FILE_RETENTION_MODE = 21007;
  ENUM_TYPE_FILE_KIND = 21008;
  ENUM_TYPE_FILE_TYPE = 21009;
  ENUM_TYPE_FILE_FORMAT = 21010;
  ENUM_TYPE_CLIENT_TYPE = 21011;
  ENUM_TYPE_MACHINE_TYPE = 21012;
  ENUM_TYPE_PRIMITIVE_TYPE = 21501;
  ENUM_TYPE_FIELD_ZONE = 21502;
  ENUM_TYPE_TYPE_KIND = 21503;
  ENUM_TYPE_TYPE_FORMAT = 21504;
  ENUM_TYPE_OBJECT_KIND = 21505;
  ENUM_TYPE_BLOCK_TYPE = 21506;
  ENUM_TYPE_AGENCY = 21507;
  ENUM_TYPE_SCHEDULE_TYPE = 22001;
  ENUM_TYPE_TIME_INTERVAL = 22002;
  ENUM_TYPE_DAY = 22003;
  ENUM_TYPE_MONTH = 22004;
  ENUM_TYPE_TEXT_LINE_TYPE = 22005;
  ENUM_TYPE_ICON_KIND = 22006;
  ENUM_TYPE_MESSAGE_TYPE = 22007;
  ENUM_TYPE_MESSAGE_STATUS = 22008;
  ENUM_TYPE_EXPRESSION_KIND = 22501;
  ENUM_TYPE_EXPRESSION_OP = 22502;
  ENUM_TYPE_LITERAL_TYPE = 22503;
  ENUM_TYPE_FUNCTIONAL_TYPE = 22504;
  ENUM_TYPE_CONDITIONAL_TYPE = 22505;
  ENUM_TYPE_AGGREGATION_TYPE = 22506;
  ENUM_TYPE_SORT_MODE = 22507;
  ENUM_TYPE_SORT_TYPE = 22508;
  ENUM_TYPE_PATH_TOKEN_TYPE = 22509;
  ENUM_TYPE_LOG_KIND = 23001;
  ENUM_TYPE_LOG_LEVEL = 23002;
  ENUM_TYPE_RUN_STATUS = 23003;
  ENUM_TYPE_RUN_TYPE = 23004;
  ENUM_TYPE_RUN_ERROR_KIND = 23005;
  ENUM_TYPE_RUN_ERROR_TYPE = 23006;
  ENUM_TYPE_RUN_SPAN_TYPE = 23007;
  ENUM_TYPE_RUN_EVENT_TYPE = 23008;
  ENUM_TYPE_SESSION_STATUS = 23009;
  ENUM_TYPE_TRIGGER_TYPE = 23010;
  ENUM_TYPE_BREAKPOINT_SITE = 23011;
  ENUM_TYPE_BREAKPOINT_ACTION = 23012;
  ENUM_TYPE_BREAKPOINT_TARGET = 23013;
  ENUM_TYPE_INTERRUPT_TYPE = 23014;
  ENUM_TYPE_INTERRUPT_STATUS = 23015;
  ENUM_TYPE_CACHE_MODE = 23016;
  ENUM_TYPE_CODE_TYPE = 23017;
  ENUM_TYPE_MODEL_PROVIDER = 23018;
  ENUM_TYPE_MODEL_TYPE = 23019;
  ENUM_TYPE_STEP_TYPE = 23020;
  ENUM_TYPE_PORT_SIDE = 23021;
  ENUM_TYPE_PIPE_TYPE = 23022;
  ENUM_TYPE_NOTIFICATION_LEVEL = 23023;
  ENUM_TYPE_RUNTIME_MODE = 23024;
  ENUM_TYPE_SPACE_TYPE = 23501;
  ENUM_TYPE_VIEW_TYPE = 23502;
  ENUM_TYPE_VARIANT = 23503;
  ENUM_TYPE_COLOR_TYPE = 23504;
  ENUM_TYPE_COLOR_SHADE = 23505;
  ENUM_TYPE_FONT_TYPE = 23506;
  ENUM_TYPE_FONT_WEIGHT = 23507;
  ENUM_TYPE_FONT_SIZE = 23508;
  ENUM_TYPE_SPACING = 23509;
  ENUM_TYPE_ANCHOR = 23510;
  ENUM_TYPE_ORIENTATION = 23511;
  ENUM_TYPE_ALIGNMENT = 23512;
  ENUM_TYPE_USER_WIZARD_STAGE = 23513;
  ENUM_TYPE_TREE_VIEW_PRESET = 23514;
  ENUM_TYPE_HUB_ASPECT = 23515;
  ENUM_TYPE_HELP_ASPECT = 23516;
  ENUM_TYPE_USER_STATUS = 24001;
  ENUM_TYPE_ORGANIZATION_STATUS = 24002;
}

enum NodeType {
  NODE_TYPE_UNSPECIFIED = 0;
  NODE_TYPE_BENCH = 1;
  NODE_TYPE_USER = 2;
  NODE_TYPE_ORGANIZATION = 3;
  NODE_TYPE_HANDLE = 4;
  NODE_TYPE_CLIENT = 5;
  NODE_TYPE_SERVER = 200;
  NODE_TYPE_STORE = 201;
  NODE_TYPE_DRIVE = 203;
  NODE_TYPE_VAULT = 204;
  NODE_TYPE_CACHE = 205;
  NODE_TYPE_MACHINE = 250;
  NODE_TYPE_BROWSER = 251;
  NODE_TYPE_FILE = 260;
  NODE_TYPE_STREAM = 261;
  NODE_TYPE_SECRET = 262;
  NODE_TYPE_MEMBERSHIP = 600;
  NODE_TYPE_INVITE = 601;
  NODE_TYPE_BRANCH = 1000;
  NODE_TYPE_PACKAGE = 1001;
  NODE_TYPE_DEPENDENCY = 1002;
  NODE_TYPE_SPACE = 1003;
  NODE_TYPE_BLOCK = 1010;
  NODE_TYPE_TRIGGER = 1011;
  NODE_TYPE_FIELD = 1012;
  NODE_TYPE_QUERY = 1013;
  NODE_TYPE_VIEW = 1020;
  NODE_TYPE_STEP = 1030;
  NODE_TYPE_PIPE = 1031;
  NODE_TYPE_BADGE = 1040;
  NODE_TYPE_MESSAGE = 1100;
  NODE_TYPE_RECORD = 1101;
  NODE_TYPE_SESSION = 1900;
  NODE_TYPE_RUN = 1901;
  NODE_TYPE_INTERRUPT = 1902;
  NODE_TYPE_LOG = 1903;
  NODE_TYPE_SKIP = 9000;
}

enum StructType {
  STRUCT_TYPE_UNSPECIFIED = 0;
  STRUCT_TYPE_RUNTIME_CONTEXT = 10001;
  STRUCT_TYPE_EDIT_CONTEXT = 10002;
  STRUCT_TYPE_EDIT = 10003;
  STRUCT_TYPE_EDIT_INFO = 10004;
  STRUCT_TYPE_EDIT_OPERATION = 10005;
  STRUCT_TYPE_CHANGE = 10006;
  STRUCT_TYPE_CHANGE_VIGNETTE = 10007;
  STRUCT_TYPE_GRAPH_SCOPE = 10008;
  STRUCT_TYPE_CLIENT_ORIGIN = 10009;
  STRUCT_TYPE_NODE_REFERENCE = 10010;
  STRUCT_TYPE_PROPERTY_REFERENCE = 10011;
  STRUCT_TYPE_POLICY = 10500;
  STRUCT_TYPE_POLICY_RULE = 10501;
  STRUCT_TYPE_SUBJECT = 10502;
  STRUCT_TYPE_ACCESS_ZONE = 10503;
  STRUCT_TYPE_ACCESS_MATRIX = 10504;
  STRUCT_TYPE_ACCESS = 10505;
  STRUCT_TYPE_MACHINE_IMAGE = 11000;
  STRUCT_TYPE_TYPE_INFO = 11500;
  STRUCT_TYPE_TYPE_CONSTRAINT = 11501;
  STRUCT_TYPE_VARIABLE_OBJECT = 11502;
  STRUCT_TYPE_MEMBER_OBJECT = 11503;
  STRUCT_TYPE_INPUT_OBJECT = 11504;
  STRUCT_TYPE_OUTPUT_OBJECT = 11505;
  STRUCT_TYPE_SCHEDULE = 11506;
  STRUCT_TYPE_FILE_INFO = 11507;
  STRUCT_TYPE_ICON = 11509;
  STRUCT_TYPE_TEXT = 12000;
  STRUCT_TYPE_TEXT_LINE = 12001;
  STRUCT_TYPE_TEXT_SPAN = 12002;
  STRUCT_TYPE_CODE = 12100;
  STRUCT_TYPE_CODE_LINE = 12101;
  STRUCT_TYPE_PATH = 12200;
  STRUCT_TYPE_PATH_TOKEN = 12201;
  STRUCT_TYPE_EXPRESSION = 12202;
  STRUCT_TYPE_AGGREGATION_RESULT = 12203;
  STRUCT_TYPE_SELECTION = 12204;
  STRUCT_TYPE_SELECT_OPTIONS = 12205;
  STRUCT_TYPE_VALUE = 12206;
  STRUCT_TYPE_COMPUTED_VALUE = 12207;
  STRUCT_TYPE_OBJECT_MAPPING = 12208;
  STRUCT_TYPE_FIELD_MAPPING = 12209;
  STRUCT_TYPE_RUN_ERROR = 12700;
  STRUCT_TYPE_RUN_OPTIONS = 12701;
  STRUCT_TYPE_RUN_ATTEMPT = 12702;
  STRUCT_TYPE_RUN_TRACE = 12703;
  STRUCT_TYPE_RUN_FRAME = 12704;
  STRUCT_TYPE_RUN_SPAN = 12705;
  STRUCT_TYPE_RUN_EVENT = 12706;
  STRUCT_TYPE_TEXT_OPTIONS = 12707;
  STRUCT_TYPE_AUDIO_OPTIONS = 12708;
  STRUCT_TYPE_IMAGE_OPTIONS = 12709;
  STRUCT_TYPE_VIDEO_OPTIONS = 12710;
  STRUCT_TYPE_CONTINUE = 12711;
  STRUCT_TYPE_CALL = 12712;
  STRUCT_TYPE_CONTEXT = 12713;
  STRUCT_TYPE_BREAKPOINT = 12714;
  STRUCT_TYPE_LOG_INFO = 12715;
  STRUCT_TYPE_COLOR = 13200;
  STRUCT_TYPE_FONT = 13201;
  STRUCT_TYPE_RECTANGLE = 13202;
  STRUCT_TYPE_OFFSET = 13203;
  STRUCT_TYPE_TRANSFORM = 13204;
  STRUCT_TYPE_VECTOR2 = 13205;
  STRUCT_TYPE_VECTOR3 = 13206;
  STRUCT_TYPE_VECTOR4 = 13207;
  STRUCT_TYPE_LINE = 13208;
  STRUCT_TYPE_RECTANGLE_CONSTRAINT = 13209;
}

enum ObjectType {
  OBJECT_TYPE_UNSPECIFIED = 0;
  OBJECT_TYPE_BENCH = 1;
  OBJECT_TYPE_USER = 2;
  OBJECT_TYPE_ORGANIZATION = 3;
  OBJECT_TYPE_HANDLE = 4;
  OBJECT_TYPE_CLIENT = 5;
  OBJECT_TYPE_SERVER = 200;
  OBJECT_TYPE_STORE = 201;
  OBJECT_TYPE_DRIVE = 203;
  OBJECT_TYPE_VAULT = 204;
  OBJECT_TYPE_CACHE = 205;
  OBJECT_TYPE_MACHINE = 250;
  OBJECT_TYPE_BROWSER = 251;
  OBJECT_TYPE_FILE = 260;
  OBJECT_TYPE_STREAM = 261;
  OBJECT_TYPE_SECRET = 262;
  OBJECT_TYPE_MEMBERSHIP = 600;
  OBJECT_TYPE_INVITE = 601;
  OBJECT_TYPE_BRANCH = 1000;
  OBJECT_TYPE_PACKAGE = 1001;
  OBJECT_TYPE_DEPENDENCY = 1002;
  OBJECT_TYPE_SPACE = 1003;
  OBJECT_TYPE_BLOCK = 1010;
  OBJECT_TYPE_TRIGGER = 1011;
  OBJECT_TYPE_FIELD = 1012;
  OBJECT_TYPE_QUERY = 1013;
  OBJECT_TYPE_VIEW = 1020;
  OBJECT_TYPE_STEP = 1030;
  OBJECT_TYPE_PIPE = 1031;
  OBJECT_TYPE_BADGE = 1040;
  OBJECT_TYPE_MESSAGE = 1100;
  OBJECT_TYPE_RECORD = 1101;
  OBJECT_TYPE_SESSION = 1900;
  OBJECT_TYPE_RUN = 1901;
  OBJECT_TYPE_INTERRUPT = 1902;
  OBJECT_TYPE_LOG = 1903;
  OBJECT_TYPE_SKIP = 9000;
  OBJECT_TYPE_RUNTIME_CONTEXT = 10001;
  OBJECT_TYPE_EDIT_CONTEXT = 10002;
  OBJECT_TYPE_EDIT = 10003;
  OBJECT_TYPE_EDIT_INFO = 10004;
  OBJECT_TYPE_EDIT_OPERATION = 10005;
  OBJECT_TYPE_CHANGE = 10006;
  OBJECT_TYPE_CHANGE_VIGNETTE = 10007;
  OBJECT_TYPE_GRAPH_SCOPE = 10008;
  OBJECT_TYPE_CLIENT_ORIGIN = 10009;
  OBJECT_TYPE_NODE_REFERENCE = 10010;
  OBJECT_TYPE_PROPERTY_REFERENCE = 10011;
  OBJECT_TYPE_POLICY = 10500;
  OBJECT_TYPE_POLICY_RULE = 10501;
  OBJECT_TYPE_SUBJECT = 10502;
  OBJECT_TYPE_ACCESS_ZONE = 10503;
  OBJECT_TYPE_ACCESS_MATRIX = 10504;
  OBJECT_TYPE_ACCESS = 10505;
  OBJECT_TYPE_MACHINE_IMAGE = 11000;
  OBJECT_TYPE_TYPE_INFO = 11500;
  OBJECT_TYPE_TYPE_CONSTRAINT = 11501;
  OBJECT_TYPE_VARIABLE_OBJECT = 11502;
  OBJECT_TYPE_MEMBER_OBJECT = 11503;
  OBJECT_TYPE_INPUT_OBJECT = 11504;
  OBJECT_TYPE_OUTPUT_OBJECT = 11505;
  OBJECT_TYPE_SCHEDULE = 11506;
  OBJECT_TYPE_FILE_INFO = 11507;
  OBJECT_TYPE_ICON = 11509;
  OBJECT_TYPE_TEXT = 12000;
  OBJECT_TYPE_TEXT_LINE = 12001;
  OBJECT_TYPE_TEXT_SPAN = 12002;
  OBJECT_TYPE_CODE = 12100;
  OBJECT_TYPE_CODE_LINE = 12101;
  OBJECT_TYPE_PATH = 12200;
  OBJECT_TYPE_PATH_TOKEN = 12201;
  OBJECT_TYPE_EXPRESSION = 12202;
  OBJECT_TYPE_AGGREGATION_RESULT = 12203;
  OBJECT_TYPE_SELECTION = 12204;
  OBJECT_TYPE_SELECT_OPTIONS = 12205;
  OBJECT_TYPE_VALUE = 12206;
  OBJECT_TYPE_COMPUTED_VALUE = 12207;
  OBJECT_TYPE_OBJECT_MAPPING = 12208;
  OBJECT_TYPE_FIELD_MAPPING = 12209;
  OBJECT_TYPE_RUN_ERROR = 12700;
  OBJECT_TYPE_RUN_OPTIONS = 12701;
  OBJECT_TYPE_RUN_ATTEMPT = 12702;
  OBJECT_TYPE_RUN_TRACE = 12703;
  OBJECT_TYPE_RUN_FRAME = 12704;
  OBJECT_TYPE_RUN_SPAN = 12705;
  OBJECT_TYPE_RUN_EVENT = 12706;
  OBJECT_TYPE_TEXT_OPTIONS = 12707;
  OBJECT_TYPE_AUDIO_OPTIONS = 12708;
  OBJECT_TYPE_IMAGE_OPTIONS = 12709;
  OBJECT_TYPE_VIDEO_OPTIONS = 12710;
  OBJECT_TYPE_CONTINUE = 12711;
  OBJECT_TYPE_CALL = 12712;
  OBJECT_TYPE_CONTEXT = 12713;
  OBJECT_TYPE_BREAKPOINT = 12714;
  OBJECT_TYPE_LOG_INFO = 12715;
  OBJECT_TYPE_COLOR = 13200;
  OBJECT_TYPE_FONT = 13201;
  OBJECT_TYPE_RECTANGLE = 13202;
  OBJECT_TYPE_OFFSET = 13203;
  OBJECT_TYPE_TRANSFORM = 13204;
  OBJECT_TYPE_VECTOR2 = 13205;
  OBJECT_TYPE_VECTOR3 = 13206;
  OBJECT_TYPE_VECTOR4 = 13207;
  OBJECT_TYPE_LINE = 13208;
  OBJECT_TYPE_RECTANGLE_CONSTRAINT = 13209;
}

enum AccessMode {
  ACCESS_MODE_UNSPECIFIED = 0;
  ACCESS_MODE_ADAPTIVE = 1;
  ACCESS_MODE_ATOMIC = 2;
}

enum AccessKind {
  ACCESS_KIND_UNSPECIFIED = 0;
  ACCESS_KIND_READ = 1;
  ACCESS_KIND_EDIT = 20;
  ACCESS_KIND_USE = 40;
}

// Ways to read nodes.
enum QueryType {
  QUERY_TYPE_UNSPECIFIED = 0;
  QUERY_TYPE_GET = 1;
  QUERY_TYPE_SEARCH = 2;
  QUERY_TYPE_AGGREGATE = 3;
}

// Ways to edit nodes.
enum EditType {
  EDIT_TYPE_UNSPECIFIED = 0;
  EDIT_TYPE_CREATE = 20;
  EDIT_TYPE_UPSERT = 21;
  EDIT_TYPE_UPDATE = 22;
  EDIT_TYPE_MOVE = 23;
  EDIT_TYPE_DELETE = 26;
  EDIT_TYPE_RESTORE = 27;
  EDIT_TYPE_ERASE = 28;
}

// Ways to use nodes.
enum UseType {
  USE_TYPE_UNSPECIFIED = 0;
  USE_TYPE_START = 40;
  USE_TYPE_PAUSE = 41;
  USE_TYPE_RESUME = 42;
  USE_TYPE_STOP = 43;
  USE_TYPE_KILL = 44;
  USE_TYPE_SEND = 45;
  USE_TYPE_RECEIVE = 46;
}

enum AccessType {
  ACCESS_TYPE_UNSPECIFIED = 0;
  ACCESS_TYPE_GET = 1;
  ACCESS_TYPE_SEARCH = 2;
  ACCESS_TYPE_AGGREGATE = 3;
  ACCESS_TYPE_CREATE = 20;
  ACCESS_TYPE_UPSERT = 21;
  ACCESS_TYPE_UPDATE = 22;
  ACCESS_TYPE_MOVE = 23;
  ACCESS_TYPE_DELETE = 26;
  ACCESS_TYPE_RESTORE = 27;
  ACCESS_TYPE_ERASE = 28;
  ACCESS_TYPE_START = 40;
  ACCESS_TYPE_PAUSE = 41;
  ACCESS_TYPE_RESUME = 42;
  ACCESS_TYPE_STOP = 43;
  ACCESS_TYPE_KILL = 44;
  ACCESS_TYPE_SEND = 45;
  ACCESS_TYPE_RECEIVE = 46;
}

// Optional classification for edits.
enum ChangeCategory {
  CHANGE_CATEGORY_UNSPECIFIED = 0;
  CHANGE_CATEGORY_SPACE = 10;
  CHANGE_CATEGORY_RUNTIME = 20;
}

// The type of edit operation.
enum EditOperationType {
  EDIT_OPERATION_TYPE_UNSPECIFIED = 0;
  EDIT_OPERATION_TYPE_SET = 1;
  EDIT_OPERATION_TYPE_CLEAR = 2;
}

enum PolicyEffect {
  POLICY_EFFECT_UNSPECIFIED = 0;
  POLICY_EFFECT_ALLOW = 1;
  POLICY_EFFECT_DENY = 2;
}

enum BenchType {
  BENCH_TYPE_UNSPECIFIED = 0;
  BENCH_TYPE_BENCH = 1;
  BENCH_TYPE_USER = 2;
  BENCH_TYPE_ORGANIZATION = 3;
  BENCH_TYPE_HANDLE = 4;
  BENCH_TYPE_CLIENT = 5;
  BENCH_TYPE_SERVER = 200;
  BENCH_TYPE_STORE = 201;
  BENCH_TYPE_DRIVE = 203;
  BENCH_TYPE_VAULT = 204;
  BENCH_TYPE_CACHE = 205;
  BENCH_TYPE_MACHINE = 250;
  BENCH_TYPE_BROWSER = 251;
  BENCH_TYPE_FILE = 260;
  BENCH_TYPE_STREAM = 261;
  BENCH_TYPE_SECRET = 262;
  BENCH_TYPE_MEMBERSHIP = 600;
  BENCH_TYPE_INVITE = 601;
  BENCH_TYPE_BRANCH = 1000;
  BENCH_TYPE_PACKAGE = 1001;
  BENCH_TYPE_DEPENDENCY = 1002;
  BENCH_TYPE_SPACE = 1003;
  BENCH_TYPE_BLOCK = 1010;
  BENCH_TYPE_TRIGGER = 1011;
  BENCH_TYPE_FIELD = 1012;
  BENCH_TYPE_QUERY = 1013;
  BENCH_TYPE_VIEW = 1020;
  BENCH_TYPE_STEP = 1030;
  BENCH_TYPE_PIPE = 1031;
  BENCH_TYPE_BADGE = 1040;
  BENCH_TYPE_MESSAGE = 1100;
  BENCH_TYPE_RECORD = 1101;
  BENCH_TYPE_SESSION = 1900;
  BENCH_TYPE_RUN = 1901;
  BENCH_TYPE_INTERRUPT = 1902;
  BENCH_TYPE_LOG = 1903;
  BENCH_TYPE_SKIP = 9000;
  BENCH_TYPE_RUNTIME_CONTEXT = 10001;
  BENCH_TYPE_EDIT_CONTEXT = 10002;
  BENCH_TYPE_EDIT = 10003;
  BENCH_TYPE_EDIT_INFO = 10004;
  BENCH_TYPE_EDIT_OPERATION = 10005;
  BENCH_TYPE_CHANGE = 10006;
  BENCH_TYPE_CHANGE_VIGNETTE = 10007;
  BENCH_TYPE_GRAPH_SCOPE = 10008;
  BENCH_TYPE_CLIENT_ORIGIN = 10009;
  BENCH_TYPE_NODE_REFERENCE = 10010;
  BENCH_TYPE_PROPERTY_REFERENCE = 10011;
  BENCH_TYPE_POLICY = 10500;
  BENCH_TYPE_POLICY_RULE = 10501;
  BENCH_TYPE_SUBJECT = 10502;
  BENCH_TYPE_ACCESS_ZONE = 10503;
  BENCH_TYPE_ACCESS_MATRIX = 10504;
  BENCH_TYPE_ACCESS = 10505;
  BENCH_TYPE_MACHINE_IMAGE = 11000;
  BENCH_TYPE_TYPE_INFO = 11500;
  BENCH_TYPE_TYPE_CONSTRAINT = 11501;
  BENCH_TYPE_VARIABLE_OBJECT = 11502;
  BENCH_TYPE_MEMBER_OBJECT = 11503;
  BENCH_TYPE_INPUT_OBJECT = 11504;
  BENCH_TYPE_OUTPUT_OBJECT = 11505;
  BENCH_TYPE_SCHEDULE = 11506;
  BENCH_TYPE_FILE_INFO = 11507;
  BENCH_TYPE_ICON = 11509;
  BENCH_TYPE_TEXT = 12000;
  BENCH_TYPE_TEXT_LINE = 12001;
  BENCH_TYPE_TEXT_SPAN = 12002;
  BENCH_TYPE_CODE = 12100;
  BENCH_TYPE_CODE_LINE = 12101;
  BENCH_TYPE_PATH = 12200;
  BENCH_TYPE_PATH_TOKEN = 12201;
  BENCH_TYPE_EXPRESSION = 12202;
  BENCH_TYPE_AGGREGATION_RESULT = 12203;
  BENCH_TYPE_SELECTION = 12204;
  BENCH_TYPE_SELECT_OPTIONS = 12205;
  BENCH_TYPE_VALUE = 12206;
  BENCH_TYPE_COMPUTED_VALUE = 12207;
  BENCH_TYPE_OBJECT_MAPPING = 12208;
  BENCH_TYPE_FIELD_MAPPING = 12209;
  BENCH_TYPE_RUN_ERROR = 12700;
  BENCH_TYPE_RUN_OPTIONS = 12701;
  BENCH_TYPE_RUN_ATTEMPT = 12702;
  BENCH_TYPE_RUN_TRACE = 12703;
  BENCH_TYPE_RUN_FRAME = 12704;
  BENCH_TYPE_RUN_SPAN = 12705;
  BENCH_TYPE_RUN_EVENT = 12706;
  BENCH_TYPE_TEXT_OPTIONS = 12707;
  BENCH_TYPE_AUDIO_OPTIONS = 12708;
  BENCH_TYPE_IMAGE_OPTIONS = 12709;
  BENCH_TYPE_VIDEO_OPTIONS = 12710;
  BENCH_TYPE_CONTINUE = 12711;
  BENCH_TYPE_CALL = 12712;
  BENCH_TYPE_CONTEXT = 12713;
  BENCH_TYPE_BREAKPOINT = 12714;
  BENCH_TYPE_LOG_INFO = 12715;
  BENCH_TYPE_COLOR = 13200;
  BENCH_TYPE_FONT = 13201;
  BENCH_TYPE_RECTANGLE = 13202;
  BENCH_TYPE_OFFSET = 13203;
  BENCH_TYPE_TRANSFORM = 13204;
  BENCH_TYPE_VECTOR2 = 13205;
  BENCH_TYPE_VECTOR3 = 13206;
  BENCH_TYPE_VECTOR4 = 13207;
  BENCH_TYPE_LINE = 13208;
  BENCH_TYPE_RECTANGLE_CONSTRAINT = 13209;
  BENCH_TYPE_ENUM_TYPE = 20001;
  BENCH_TYPE_NODE_TYPE = 20002;
  BENCH_TYPE_STRUCT_TYPE = 20003;
  BENCH_TYPE_OBJECT_TYPE = 20004;
  BENCH_TYPE_ACCESS_MODE = 20501;
  BENCH_TYPE_ACCESS_KIND = 20502;
  BENCH_TYPE_QUERY_TYPE = 20503;
  BENCH_TYPE_EDIT_TYPE = 20504;
  BENCH_TYPE_USE_TYPE = 20505;
  BENCH_TYPE_ACCESS_TYPE = 20506;
  BENCH_TYPE_CHANGE_CATEGORY = 20507;
  BENCH_TYPE_EDIT_OPERATION_TYPE = 20508;
  BENCH_TYPE_POLICY_EFFECT = 20509;
  BENCH_TYPE_BENCH_TYPE = 21001;
  BENCH_TYPE_CLOUD = 21002;
  BENCH_TYPE_REGION = 21003;
  BENCH_TYPE_REGION_ZONE = 21004;
  BENCH_TYPE_REGION_AREA = 21005;
  BENCH_TYPE_RESOURCE_STATUS = 21006;
  BENCH_TYPE_FILE_RETENTION_MODE = 21007;
  BENCH_TYPE_FILE_KIND = 21008;
  BENCH_TYPE_FILE_TYPE = 21009;
  BENCH_TYPE_FILE_FORMAT = 21010;
  BENCH_TYPE_CLIENT_TYPE = 21011;
  BENCH_TYPE_MACHINE_TYPE = 21012;
  BENCH_TYPE_PRIMITIVE_TYPE = 21501;
  BENCH_TYPE_FIELD_ZONE = 21502;
  BENCH_TYPE_TYPE_KIND = 21503;
  BENCH_TYPE_TYPE_FORMAT = 21504;
  BENCH_TYPE_OBJECT_KIND = 21505;
  BENCH_TYPE_BLOCK_TYPE = 21506;
  BENCH_TYPE_AGENCY = 21507;
  BENCH_TYPE_SCHEDULE_TYPE = 22001;
  BENCH_TYPE_TIME_INTERVAL = 22002;
  BENCH_TYPE_DAY = 22003;
  BENCH_TYPE_MONTH = 22004;
  BENCH_TYPE_TEXT_LINE_TYPE = 22005;
  BENCH_TYPE_ICON_KIND = 22006;
  BENCH_TYPE_MESSAGE_TYPE = 22007;
  BENCH_TYPE_MESSAGE_STATUS = 22008;
  BENCH_TYPE_EXPRESSION_KIND = 22501;
  BENCH_TYPE_EXPRESSION_OP = 22502;
  BENCH_TYPE_LITERAL_TYPE = 22503;
  BENCH_TYPE_FUNCTIONAL_TYPE = 22504;
  BENCH_TYPE_CONDITIONAL_TYPE = 22505;
  BENCH_TYPE_AGGREGATION_TYPE = 22506;
  BENCH_TYPE_SORT_MODE = 22507;
  BENCH_TYPE_SORT_TYPE = 22508;
  BENCH_TYPE_PATH_TOKEN_TYPE = 22509;
  BENCH_TYPE_LOG_KIND = 23001;
  BENCH_TYPE_LOG_LEVEL = 23002;
  BENCH_TYPE_RUN_STATUS = 23003;
  BENCH_TYPE_RUN_TYPE = 23004;
  BENCH_TYPE_RUN_ERROR_KIND = 23005;
  BENCH_TYPE_RUN_ERROR_TYPE = 23006;
  BENCH_TYPE_RUN_SPAN_TYPE = 23007;
  BENCH_TYPE_RUN_EVENT_TYPE = 23008;
  BENCH_TYPE_SESSION_STATUS = 23009;
  BENCH_TYPE_TRIGGER_TYPE = 23010;
  BENCH_TYPE_BREAKPOINT_SITE = 23011;
  BENCH_TYPE_BREAKPOINT_ACTION = 23012;
  BENCH_TYPE_BREAKPOINT_TARGET = 23013;
  BENCH_TYPE_INTERRUPT_TYPE = 23014;
  BENCH_TYPE_INTERRUPT_STATUS = 23015;
  BENCH_TYPE_CACHE_MODE = 23016;
  BENCH_TYPE_CODE_TYPE = 23017;
  BENCH_TYPE_MODEL_PROVIDER = 23018;
  BENCH_TYPE_MODEL_TYPE = 23019;
  BENCH_TYPE_STEP_TYPE = 23020;
  BENCH_TYPE_PORT_SIDE = 23021;
  BENCH_TYPE_PIPE_TYPE = 23022;
  BENCH_TYPE_NOTIFICATION_LEVEL = 23023;
  BENCH_TYPE_RUNTIME_MODE = 23024;
  BENCH_TYPE_SPACE_TYPE = 23501;
  BENCH_TYPE_VIEW_TYPE = 23502;
  BENCH_TYPE_VARIANT = 23503;
  BENCH_TYPE_COLOR_TYPE = 23504;
  BENCH_TYPE_COLOR_SHADE = 23505;
  BENCH_TYPE_FONT_TYPE = 23506;
  BENCH_TYPE_FONT_WEIGHT = 23507;
  BENCH_TYPE_FONT_SIZE = 23508;
  BENCH_TYPE_SPACING = 23509;
  BENCH_TYPE_ANCHOR = 23510;
  BENCH_TYPE_ORIENTATION = 23511;
  BENCH_TYPE_ALIGNMENT = 23512;
  BENCH_TYPE_USER_WIZARD_STAGE = 23513;
  BENCH_TYPE_TREE_VIEW_PRESET = 23514;
  BENCH_TYPE_HUB_ASPECT = 23515;
  BENCH_TYPE_HELP_ASPECT = 23516;
  BENCH_TYPE_USER_STATUS = 24001;
  BENCH_TYPE_ORGANIZATION_STATUS = 24002;
}

// The cloud provider.
enum Cloud {
  CLOUD_UNSPECIFIED = 0;
  CLOUD_AWS = 100;
  CLOUD_AZURE = 101;
  CLOUD_GCP = 102;
  CLOUD_OCI = 103;
  CLOUD_ALIBABA = 104;
  CLOUD_HETZNER = 200;
  CLOUD_NEON = 300;
  CLOUD_PRIVATE = 900;
}

// Actual regions within a Zone in an Area.
enum Region {
  REGION_UNSPECIFIED = 0;
  REGION_ZURICH = 1001;
  REGION_FRANKFURT = 1002;
  REGION_VIRGINIA = 2001;
  REGION_OHIO = 2002;
  REGION_OREGON = 2101;
  REGION_SAO_PAULO = 3001;
  REGION_CAPE_TOWN = 5001;
  REGION_MUMBAI = 6001;
  REGION_SINGAPORE = 6101;
  REGION_TOKYO = 6201;
  REGION_SYDNEY = 7001;
}

// A larger zone of Regions within an Area.
enum RegionZone {
  REGION_ZONE_UNSPECIFIED = 0;
  REGION_ZONE_EUROPE_CENTRAL = 1000;
  REGION_ZONE_NORTH_AMERICA_EAST = 2000;
  REGION_ZONE_NORTH_AMERICA_WEST = 2100;
  REGION_ZONE_SOUTH_AMERICA_EAST = 3000;
  REGION_ZONE_MIDDLE_EAST_CENTRAL = 4000;
  REGION_ZONE_MIDDLE_EAST_WEST = 4100;
  REGION_ZONE_AFRICA_SOUTH = 5000;
  REGION_ZONE_ASIA_WEST = 6000;
  REGION_ZONE_ASIA_SOUTH = 6100;
  REGION_ZONE_ASIA_EAST = 6200;
  REGION_ZONE_AUSTRALIA_SOUTH = 7000;
}

// Rough 'contintents' of Regions.
enum RegionArea {
  REGION_AREA_UNSPECIFIED = 0;
  REGION_AREA_EUROPE = 1000;
  REGION_AREA_NORTH_AMERICA = 2000;
  REGION_AREA_SOUTH_AMERICA = 3000;
  REGION_AREA_MIDDLE_EAST = 4000;
  REGION_AREA_AFRICA = 5000;
  REGION_AREA_ASIA = 6000;
  REGION_AREA_AUSTRALIA = 7000;
  REGION_AREA_PRIVATE = 9000;
  REGION_AREA_GLOBAL = 10090;
}

// Generalized status of a Resource in its lifecycle.
enum ResourceStatus {
  RESOURCE_STATUS_UNSPECIFIED = 0;
  RESOURCE_STATUS_DECLARED = 1;
  RESOURCE_STATUS_UP = 10;
  RESOURCE_STATUS_SLEEPING = 11;
  RESOURCE_STATUS_DOWN = 15;
  RESOURCE_STATUS_DEGRADED = 16;
  RESOURCE_STATUS_GONE = 30;
}

enum FileRetentionMode {
  FILE_RETENTION_MODE_UNSPECIFIED = 0;
  FILE_RETENTION_MODE_AUTOMATIC = 1;
  FILE_RETENTION_MODE_MANUAL = 2;
  FILE_RETENTION_MODE_TIMED = 3;
}

enum FileKind {
  FILE_KIND_UNSPECIFIED = 0;
  FILE_KIND_DRIVE = 1;
  FILE_KIND_DRIVE_INLINE = 2;
  FILE_KIND_INLINE = 3;
  FILE_KIND_EXTERNAL = 10;
}

enum FileType {
  FILE_TYPE_UNSPECIFIED = 0;
  FILE_TYPE_TEXT = 1;
  FILE_TYPE_CODE = 2;
  FILE_TYPE_IMAGE = 3;
  FILE_TYPE_AUDIO = 4;
  FILE_TYPE_VIDEO = 5;
  FILE_TYPE_DOCUMENT = 6;
  FILE_TYPE_DATA = 7;
  FILE_TYPE_ARCHIVE = 8;
  FILE_TYPE_EXECUTABLE = 9;
  FILE_TYPE_GENERIC = 99;
}

// The format of a file (roughly an extension).
enum FileFormat {
  FILE_FORMAT_UNSPECIFIED = 0;
  FILE_FORMAT_TXT = 10000;
  FILE_FORMAT_MARKDOWN = 10001;
  FILE_FORMAT_RTF = 10002;
  FILE_FORMAT_INI = 10003;
  FILE_FORMAT_LOG = 10004;
  FILE_FORMAT_PYTHON = 20000;
  FILE_FORMAT_JAVASCRIPT = 20001;
  FILE_FORMAT_TYPESCRIPT = 20002;
  FILE_FORMAT_GO = 20003;
  FILE_FORMAT_C_LANG = 20004;
  FILE_FORMAT_CPP = 20005;
  FILE_FORMAT_OBJECTIVE_C = 20006;
  FILE_FORMAT_SWIFT = 20007;
  FILE_FORMAT_RUBY = 20008;
  FILE_FORMAT_PHP = 20009;
  FILE_FORMAT_CSS = 20011;
  FILE_FORMAT_JAVA = 20012;
  FILE_FORMAT_KOTLIN = 20013;
  FILE_FORMAT_RUST = 20014;
  FILE_FORMAT_SCALA = 20015;
  FILE_FORMAT_SHELL = 20016;
  FILE_FORMAT_SQL = 20017;
  FILE_FORMAT_POWERSHELL = 20018;
  FILE_FORMAT_ASSEMBLY = 20019;
  FILE_FORMAT_LATEX = 20020;
  FILE_FORMAT_JPEG = 30000;
  FILE_FORMAT_PNG = 30001;
  FILE_FORMAT_GIF = 30002;
  FILE_FORMAT_BMP = 30003;
  FILE_FORMAT_TIFF = 30004;
  FILE_FORMAT_WEBP = 30005;
  FILE_FORMAT_SVG = 30006;
  FILE_FORMAT_ICO = 30007;
  FILE_FORMAT_RAW = 30008;
  FILE_FORMAT_HEIC = 30009;
  FILE_FORMAT_HEIF = 30010;
  FILE_FORMAT_MP3 = 40000;
  FILE_FORMAT_WAV = 40001;
  FILE_FORMAT_FLAC = 40002;
  FILE_FORMAT_AAC = 40003;
  FILE_FORMAT_OGG = 40004;
  FILE_FORMAT_M4A = 40005;
  FILE_FORMAT_WMA = 40006;
  FILE_FORMAT_MP4 = 50000;
  FILE_FORMAT_WEBM = 50001;
  FILE_FORMAT_AVI = 50002;
  FILE_FORMAT_MOV = 50003;
  FILE_FORMAT_WMV = 50004;
  FILE_FORMAT_FLV = 50005;
  FILE_FORMAT_MKV = 50006;
  FILE_FORMAT_PDF = 60000;
  FILE_FORMAT_DOCX = 60001;
  FILE_FORMAT_PPTX = 60002;
  FILE_FORMAT_ODT = 60003;
  FILE_FORMAT_XLSX = 60004;
  FILE_FORMAT_ODS = 60005;
  FILE_FORMAT_EPUB = 60006;
  FILE_FORMAT_MOBI = 60007;
  FILE_FORMAT_CHM = 60008;
  FILE_FORMAT_DOC = 60009;
  FILE_FORMAT_XLS = 60100;
  FILE_FORMAT_PPT = 60101;
  FILE_FORMAT_HTML = 60102;
  FILE_FORMAT_JSON = 70000;
  FILE_FORMAT_YAML = 70001;
  FILE_FORMAT_CSV = 70002;
  FILE_FORMAT_XML = 70003;
  FILE_FORMAT_TOML = 70004;
  FILE_FORMAT_SQLITE = 70100;
  FILE_FORMAT_PARQUET = 70101;
  FILE_FORMAT_ZIP = 80000;
  FILE_FORMAT_RAR = 80001;
  FILE_FORMAT_TAR = 80002;
  FILE_FORMAT_SEVENZIP = 80003;
  FILE_FORMAT_CAB = 80004;
  FILE_FORMAT_GZIP = 80005;
  FILE_FORMAT_BZIP2 = 80006;
  FILE_FORMAT_XZ = 80007;
  FILE_FORMAT_EXE = 90000;
  FILE_FORMAT_APP_IMAGE = 90001;
  FILE_FORMAT_APK = 90002;
  FILE_FORMAT_DMG = 90003;
  FILE_FORMAT_JAR = 90004;
  FILE_FORMAT_MSI = 90005;
  FILE_FORMAT_DEB = 90006;
  FILE_FORMAT_RPM = 90007;
}

enum ClientType {
  CLIENT_TYPE_UNSPECIFIED = 0;
  CLIENT_TYPE_BENCH_WEB = 1;
  CLIENT_TYPE_BENCH_BROWSER_PLUGIN = 2;
  CLIENT_TYPE_BENCH_DESKTOP = 3;
  CLIENT_TYPE_BENCH_MOBILE = 4;
  CLIENT_TYPE_BENCH_MACHINE = 10;
}

enum MachineType {
  MACHINE_TYPE_UNSPECIFIED = 0;
  MACHINE_TYPE_RUNTIME = 1;
}

// Fundamental column / storage types we support (subset of SQL types, used directly in sql/core).
// NOTE: the ids here are used in type identity keys, so any change is breaking.
enum PrimitiveType {
  PRIMITIVE_TYPE_UNSPECIFIED = 0;
  PRIMITIVE_TYPE_BOOLEAN = 1;
  PRIMITIVE_TYPE_INT16 = 4;
  PRIMITIVE_TYPE_INT32 = 6;
  PRIMITIVE_TYPE_INT64 = 8;
  PRIMITIVE_TYPE_DECIMAL = 10;
  PRIMITIVE_TYPE_FLOAT32 = 16;
  PRIMITIVE_TYPE_FLOAT64 = 17;
  PRIMITIVE_TYPE_STRING = 20;
  PRIMITIVE_TYPE_UUID = 21;
  PRIMITIVE_TYPE_JSON = 22;
  PRIMITIVE_TYPE_BYTES = 25;
  PRIMITIVE_TYPE_VECTOR = 26;
  PRIMITIVE_TYPE_DATETIME = 30;
  PRIMITIVE_TYPE_DATE = 31;
  PRIMITIVE_TYPE_TIME = 32;
  PRIMITIVE_TYPE_INTERVAL = 33;
}

// The type of a Field within its Block. Overlaps with ObjectKind.
enum FieldType {
  FIELD_TYPE_UNSPECIFIED = 0;
  FIELD_TYPE_VARIABLE = 1;
  FIELD_TYPE_MEMBER = 2;
  FIELD_TYPE_INPUT = 3;
  FIELD_TYPE_OUTPUT = 4;
  FIELD_TYPE_OPTION = 5;
}

// The 'kind' of a Type.
enum TypeKind {
  TYPE_KIND_UNSPECIFIED = 0;
  TYPE_KIND_PRIMITIVE = 1;
  TYPE_KIND_STRUCT = 2;
  TYPE_KIND_NODE = 3;
  TYPE_KIND_ENUM = 4;
  TYPE_KIND_BASED_NODE = 5;
  TYPE_KIND_OBJECT = 6;
  TYPE_KIND_LITERAL = 7;
  TYPE_KIND_UNION = 8;
}

// The fine-grained format of some Type.
enum TypeFormat {
  TYPE_FORMAT_UNSPECIFIED = 0;
  TYPE_FORMAT_URL = 2000;
  TYPE_FORMAT_EMAIL = 2001;
  TYPE_FORMAT_EMOJI = 2002;
  TYPE_FORMAT_PHONE_NUMBER = 2003;
  TYPE_FORMAT_SLUG = 2004;
}

// The type of an Object. Overlaps with FieldType.
enum ObjectKind {
  OBJECT_KIND_UNSPECIFIED = 0;
  OBJECT_KIND_VARIABLE = 1;
  OBJECT_KIND_MEMBER = 2;
  OBJECT_KIND_INPUT = 3;
  OBJECT_KIND_OUTPUT = 4;
  OBJECT_KIND_BUILTIN = 10;
}

enum BlockType {
  BLOCK_TYPE_UNSPECIFIED = 0;
  BLOCK_TYPE_PAGE = 1;
  BLOCK_TYPE_TEXT = 2;
  BLOCK_TYPE_CLASS = 10;
  BLOCK_TYPE_CHOICE = 11;
  BLOCK_TYPE_MESSAGE = 12;
  BLOCK_TYPE_ACTION = 21;
  BLOCK_TYPE_FLOW = 22;
  BLOCK_TYPE_VALUE = 30;
  BLOCK_TYPE_DATABASE = 31;
  BLOCK_TYPE_QUERY = 32;
  BLOCK_TYPE_VIEW = 40;
  BLOCK_TYPE_ROLE = 50;
  BLOCK_TYPE_IDENTITY = 51;
}

enum Agency {
  AGENCY_UNSPECIFIED = 0;
  AGENCY_CODE = 1;
  AGENCY_DELEGATE = 2;
  AGENCY_GENERATE = 3;
}

enum ScheduleType {
  SCHEDULE_TYPE_UNSPECIFIED = 0;
  SCHEDULE_TYPE_INTERVAL = 1;
  SCHEDULE_TYPE_CRON = 2;
}

enum TimeInterval {
  TIME_INTERVAL_UNSPECIFIED = 0;
  TIME_INTERVAL_SECOND = 2;
  TIME_INTERVAL_MINUTE = 3;
  TIME_INTERVAL_HOUR = 4;
  TIME_INTERVAL_DAY = 5;
  TIME_INTERVAL_WEEK = 6;
  TIME_INTERVAL_MONTH = 7;
  TIME_INTERVAL_YEAR = 8;
}

enum Day {
  DAY_UNSPECIFIED = 0;
  DAY_MONDAY = 1;
  DAY_TUESDAY = 2;
  DAY_WEDNESDAY = 3;
  DAY_THURSDAY = 4;
  DAY_FRIDAY = 5;
  DAY_SATURDAY = 6;
  DAY_SUNDAY = 7;
}

enum Month {
  MONTH_UNSPECIFIED = 0;
  MONTH_JANUARY = 1;
  MONTH_FEBRUARY = 2;
  MONTH_MARCH = 3;
  MONTH_APRIL = 4;
  MONTH_MAY = 5;
  MONTH_JUNE = 6;
  MONTH_JULY = 7;
  MONTH_AUGUST = 8;
  MONTH_SEPTEMBER = 9;
  MONTH_OCTOBER = 10;
  MONTH_NOVEMBER = 11;
  MONTH_DECEMBER = 12;
}

enum TextLineType {
  TEXT_LINE_TYPE_UNSPECIFIED = 0;
  TEXT_LINE_TYPE_PLAIN = 1;
  TEXT_LINE_TYPE_HEADING_1 = 10;
  TEXT_LINE_TYPE_HEADING_2 = 11;
  TEXT_LINE_TYPE_HEADING_3 = 12;
  TEXT_LINE_TYPE_HEADING_4 = 13;
  TEXT_LINE_TYPE_CALLOUT = 20;
  TEXT_LINE_TYPE_QUOTE = 21;
  TEXT_LINE_TYPE_LIST_BULLET = 30;
  TEXT_LINE_TYPE_LIST_NUMBERED = 31;
  TEXT_LINE_TYPE_LIST_UNCHECKED = 32;
  TEXT_LINE_TYPE_LIST_CHECKED = 33;
  TEXT_LINE_TYPE_DIVIDER = 40;
}

enum IconKind {
  ICON_KIND_UNSPECIFIED = 0;
  ICON_KIND_EMOJI = 1;
  ICON_KIND_FONT_AWESOME = 3;
  ICON_KIND_VS_CODE = 4;
}

enum MessageType {
  MESSAGE_TYPE_UNSPECIFIED = 0;
  MESSAGE_TYPE_NATIVE = 1;
  MESSAGE_TYPE_EMAIL = 10;
  MESSAGE_TYPE_SMS = 11;
}

enum MessageStatus {
  MESSAGE_STATUS_UNSPECIFIED = 0;
  MESSAGE_STATUS_DRAFT = 1;
  MESSAGE_STATUS_PREPARED = 2;
  MESSAGE_STATUS_SENDING = 3;
  MESSAGE_STATUS_SENT = 4;
  MESSAGE_STATUS_FAILED = 5;
  MESSAGE_STATUS_RECEIVED = 6;
  MESSAGE_STATUS_READ = 7;
  MESSAGE_STATUS_EXPIRED = 8;
}

enum ExpressionKind {
  EXPRESSION_KIND_UNSPECIFIED = 0;
  EXPRESSION_KIND_LITERAL = 1;
  EXPRESSION_KIND_FUNCTIONAL = 2;
  EXPRESSION_KIND_CONDITIONAL = 3;
  EXPRESSION_KIND_SORT = 4;
  EXPRESSION_KIND_AGGREGATION = 5;
}

enum ExpressionType {
  EXPRESSION_TYPE_UNSPECIFIED = 0;
  EXPRESSION_TYPE_VALUE = 100;
  EXPRESSION_TYPE_NONE = 101;
  EXPRESSION_TYPE_TRUE = 102;
  EXPRESSION_TYPE_FALSE = 103;
  EXPRESSION_TYPE_ADD = 200;
  EXPRESSION_TYPE_SUBTRACT = 201;
  EXPRESSION_TYPE_MULTIPLY = 202;
  EXPRESSION_TYPE_DIVIDE = 203;
  EXPRESSION_TYPE_MODULO = 204;
  EXPRESSION_TYPE_POWER = 205;
  EXPRESSION_TYPE_NOT = 301;
  EXPRESSION_TYPE_AND = 302;
  EXPRESSION_TYPE_OR = 303;
  EXPRESSION_TYPE_EQUALS = 310;
  EXPRESSION_TYPE_NOT_EQUALS = 311;
  EXPRESSION_TYPE_GREATER_THAN = 312;
  EXPRESSION_TYPE_GREATER_THAN_OR_EQUALS = 313;
  EXPRESSION_TYPE_LESS_THAN = 314;
  EXPRESSION_TYPE_LESS_THAN_OR_EQUALS = 315;
  EXPRESSION_TYPE_MATCHES_REGEX = 320;
  EXPRESSION_TYPE_STARTS_WITH = 321;
  EXPRESSION_TYPE_ENDS_WITH = 322;
  EXPRESSION_TYPE_CONTAINS = 330;
  EXPRESSION_TYPE_NOT_CONTAINS = 331;
  EXPRESSION_TYPE_IN = 332;
  EXPRESSION_TYPE_NOT_IN = 333;
  EXPRESSION_TYPE_EXISTS = 400;
  EXPRESSION_TYPE_NOT_EXISTS = 341;
  EXPRESSION_TYPE_NEAR = 350;
  EXPRESSION_TYPE_COUNT = 401;
  EXPRESSION_TYPE_SUM = 402;
  EXPRESSION_TYPE_MIN = 403;
  EXPRESSION_TYPE_MAX = 404;
  EXPRESSION_TYPE_AVERAGE = 405;
  EXPRESSION_TYPE_MEDIAN = 406;
  EXPRESSION_TYPE_HISTOGRAM = 407;
  EXPRESSION_TYPE_ASCENDING = 500;
  EXPRESSION_TYPE_DESCENDING = 501;
}

enum LiteralType {
  LITERAL_TYPE_UNSPECIFIED = 0;
  LITERAL_TYPE_VALUE = 100;
  LITERAL_TYPE_NONE = 101;
  LITERAL_TYPE_TRUE = 102;
  LITERAL_TYPE_FALSE = 103;
}

enum FunctionalType {
  FUNCTIONAL_TYPE_UNSPECIFIED = 0;
  FUNCTIONAL_TYPE_ADD = 200;
  FUNCTIONAL_TYPE_SUBTRACT = 201;
  FUNCTIONAL_TYPE_MULTIPLY = 202;
  FUNCTIONAL_TYPE_DIVIDE = 203;
  FUNCTIONAL_TYPE_MODULO = 204;
  FUNCTIONAL_TYPE_POWER = 205;
}

enum ConditionalType {
  CONDITIONAL_TYPE_UNSPECIFIED = 0;
  CONDITIONAL_TYPE_NOT = 301;
  CONDITIONAL_TYPE_AND = 302;
  CONDITIONAL_TYPE_OR = 303;
  CONDITIONAL_TYPE_EQUALS = 310;
  CONDITIONAL_TYPE_NOT_EQUALS = 311;
  CONDITIONAL_TYPE_GREATER_THAN = 312;
  CONDITIONAL_TYPE_GREATER_THAN_OR_EQUALS = 313;
  CONDITIONAL_TYPE_LESS_THAN = 314;
  CONDITIONAL_TYPE_LESS_THAN_OR_EQUALS = 315;
  CONDITIONAL_TYPE_MATCHES_REGEX = 320;
  CONDITIONAL_TYPE_STARTS_WITH = 321;
  CONDITIONAL_TYPE_ENDS_WITH = 322;
  CONDITIONAL_TYPE_CONTAINS = 330;
  CONDITIONAL_TYPE_NOT_CONTAINS = 331;
  CONDITIONAL_TYPE_IN = 332;
  CONDITIONAL_TYPE_NOT_IN = 333;
  CONDITIONAL_TYPE_EXISTS = 340;
  CONDITIONAL_TYPE_NOT_EXISTS = 341;
  CONDITIONAL_TYPE_NEAR = 350;
}

enum AggregationType {
  AGGREGATION_TYPE_UNSPECIFIED = 0;
  AGGREGATION_TYPE_EXISTS = 400;
  AGGREGATION_TYPE_COUNT = 401;
  AGGREGATION_TYPE_SUM = 402;
  AGGREGATION_TYPE_MIN = 403;
  AGGREGATION_TYPE_MAX = 404;
  AGGREGATION_TYPE_AVERAGE = 405;
  AGGREGATION_TYPE_MEDIAN = 406;
  AGGREGATION_TYPE_HISTOGRAM = 407;
}

enum SortMode {
  SORT_MODE_UNSPECIFIED = 0;
  SORT_MODE_MAX = 1;
  SORT_MODE_MIN = 2;
  SORT_MODE_AVERAGE = 3;
  SORT_MODE_SUM = 4;
  SORT_MODE_MEDIAN = 5;
}

enum SortType {
  SORT_TYPE_UNSPECIFIED = 0;
  SORT_TYPE_ASCENDING = 500;
  SORT_TYPE_DESCENDING = 501;
}

enum PathTokenType {
  PATH_TOKEN_TYPE_UNSPECIFIED = 0;
  PATH_TOKEN_TYPE_ROOT = 1;
  PATH_TOKEN_TYPE_CURRENT = 2;
  PATH_TOKEN_TYPE_PARENT = 3;
  PATH_TOKEN_TYPE_BENCH = 4;
  PATH_TOKEN_TYPE_CHILD = 5;
  PATH_TOKEN_TYPE_CONTAINER = 7;
  PATH_TOKEN_TYPE_UNIQUE = 8;
  PATH_TOKEN_TYPE_FIELD = 10;
}

enum LogKind {
  LOG_KIND_UNSPECIFIED = 0;
  LOG_KIND_CHANGE = 1;
  LOG_KIND_EDIT = 2;
}

enum LogLevel {
  LOG_LEVEL_UNSPECIFIED = 0;
  LOG_LEVEL_TRACE = 1;
  LOG_LEVEL_DEBUG = 2;
  LOG_LEVEL_INFO = 3;
  LOG_LEVEL_WARNING = 4;
  LOG_LEVEL_ERROR = 5;
  LOG_LEVEL_CRITICAL = 6;
}

enum RunStatus {
  RUN_STATUS_UNSPECIFIED = 0;
  RUN_STATUS_SCHEDULED = 1;
  RUN_STATUS_QUEUED = 2;
  RUN_STATUS_RUNNING = 3;
  RUN_STATUS_PAUSED = 4;
  RUN_STATUS_YIELDED = 5;
  RUN_STATUS_WAITING = 6;
  RUN_STATUS_CANCELLED = 7;
  RUN_STATUS_ABORTED = 8;
  RUN_STATUS_FAILED = 9;
  RUN_STATUS_COMPLETED = 10;
}

enum RunType {
  RUN_TYPE_UNSPECIFIED = 0;
  RUN_TYPE_CODE = 1;
  RUN_TYPE_ACTION = 2;
  RUN_TYPE_STEP = 10;
  RUN_TYPE_FLOW = 11;
  RUN_TYPE_PIPE = 12;
}

enum RunErrorKind {
  RUN_ERROR_KIND_UNSPECIFIED = 0;
  RUN_ERROR_KIND_INTERNAL = 1;
  RUN_ERROR_KIND_RUNTIME = 5;
}

enum RunErrorType {
  RUN_ERROR_TYPE_UNSPECIFIED = 0;
  RUN_ERROR_TYPE_REPLAY = 1;
  RUN_ERROR_TYPE_ABORTED = 2;
  RUN_ERROR_TYPE_RUNTIME_UNAVAILABLE = 3;
  RUN_ERROR_TYPE_RUN_IMPOSSIBLE = 4;
  RUN_ERROR_TYPE_INVALID_VALUE = 5;
  RUN_ERROR_TYPE_CODE_INVALID = 20;
  RUN_ERROR_TYPE_TEXT_INVALID = 21;
  RUN_ERROR_TYPE_MODEL_INCAPABLE = 100;
  RUN_ERROR_TYPE_NON_RETRYABLE = 499;
  RUN_ERROR_TYPE_MODEL_FAILED = 500;
  RUN_ERROR_TYPE_ACTION_CHANGED = 501;
  RUN_ERROR_TYPE_INVALID_CONTINUATION = 502;
  RUN_ERROR_TYPE_INVALID_CALL = 503;
  RUN_ERROR_TYPE_INTERRUPT_CANCELLED = 504;
  RUN_ERROR_TYPE_RETRYABLE = 999;
}

enum RunSpanType {
  RUN_SPAN_TYPE_UNSPECIFIED = 0;
  RUN_SPAN_TYPE_CUSTOM = 1000;
}

enum RunEventType {
  RUN_EVENT_TYPE_UNSPECIFIED = 0;
  RUN_EVENT_TYPE_PAUSED = 1;
  RUN_EVENT_TYPE_RESUMED = 2;
  RUN_EVENT_TYPE_HALTED = 3;
  RUN_EVENT_TYPE_CUSTOM = 1000;
}

enum SessionStatus {
  SESSION_STATUS_UNSPECIFIED = 0;
  SESSION_STATUS_PENDING = 1;
  SESSION_STATUS_OPEN = 3;
  SESSION_STATUS_CLOSED = 6;
}

// Triggers for blocks (for both actual runs and pre-defined triggers).
enum TriggerType {
  TRIGGER_TYPE_UNSPECIFIED = 0;
  TRIGGER_TYPE_SCHEDULE = 1;
  TRIGGER_TYPE_SIGNAL = 2;
}

enum BreakpointSite {
  BREAKPOINT_SITE_UNSPECIFIED = 0;
  BREAKPOINT_SITE_RUN_BEFORE = 1;
  BREAKPOINT_SITE_RUN_AFTER_FAILED = 2;
  BREAKPOINT_SITE_RUN_AFTER_COMPLETED = 3;
  BREAKPOINT_SITE_RUN_AFTER = 5;
}

enum BreakpointAction {
  BREAKPOINT_ACTION_UNSPECIFIED = 0;
  BREAKPOINT_ACTION_YIELD = 1;
}

enum BreakpointScope {
  BREAKPOINT_SCOPE_UNSPECIFIED = 0;
  BREAKPOINT_SCOPE_SELF = 1;
  BREAKPOINT_SCOPE_CHILD = 2;
  BREAKPOINT_SCOPE_STEP = 20;
  BREAKPOINT_SCOPE_PIPE = 21;
}

enum InterruptType {
  INTERRUPT_TYPE_UNSPECIFIED = 0;
  INTERRUPT_TYPE_PAUSE = 1;
  INTERRUPT_TYPE_YIELD = 2;
  INTERRUPT_TYPE_WAIT = 3;
}

enum InterruptStatus {
  INTERRUPT_STATUS_UNSPECIFIED = 0;
  INTERRUPT_STATUS_OPEN = 1;
  INTERRUPT_STATUS_CANCELLED = 7;
  INTERRUPT_STATUS_COMPLETED = 10;
}

// How to handle caching.
enum CacheMode {
  CACHE_MODE_UNSPECIFIED = 0;
  CACHE_MODE_NEVER = 1;
  CACHE_MODE_ALWAYS = 2;
}

// The implicit 'type' of some Code.
// We don't set this explicitly in Code because it depends on where the Code is used.
enum CodeType {
  CODE_TYPE_UNSPECIFIED = 0;
  CODE_TYPE_SNIPPET = 1;
  CODE_TYPE_SCRIPT = 2;
  CODE_TYPE_FUNCTION = 3;
}

enum ModelProvider {
  MODEL_PROVIDER_UNSPECIFIED = 0;
  MODEL_PROVIDER_OPENAI = 100;
  MODEL_PROVIDER_ANTHROPIC = 200;
  MODEL_PROVIDER_GOOGLE = 300;
  MODEL_PROVIDER_META = 400;
}

enum ModelType {
  MODEL_TYPE_UNSPECIFIED = 0;
  MODEL_TYPE_OPENAI_GPT4_0 = 101;
  MODEL_TYPE_OPENAI_GPT4_O_MINI = 102;
  MODEL_TYPE_OPENAI_O1_PREVIEW = 103;
  MODEL_TYPE_OPENAI_O1_MINI = 104;
  MODEL_TYPE_ANTHROPIC_CLAUDE_3_5_SONNET = 201;
  MODEL_TYPE_GOOGLE_GEMINI_1_5_PRO = 301;
  MODEL_TYPE_META_LLAMA_3_1_80B = 401;
  MODEL_TYPE_META_LLAMA_3_1_400B = 402;
}

enum StepType {
  STEP_TYPE_UNSPECIFIED = 0;
  STEP_TYPE_START = 1;
  STEP_TYPE_COMPLETE = 2;
  STEP_TYPE_FAIL = 3;
  STEP_TYPE_TRIGGER = 4;
  STEP_TYPE_ACTION = 60;
  STEP_TYPE_CREATE = 61;
  STEP_TYPE_YIELD = 62;
  STEP_TYPE_LOOP = 501;
  STEP_TYPE_TEXT = 900;
}

enum PortSide {
  PORT_SIDE_UNSPECIFIED = 0;
  PORT_SIDE_INCOMING = 1;
  PORT_SIDE_OUTGOING = 2;
}

enum PipeType {
  PIPE_TYPE_UNSPECIFIED = 0;
  PIPE_TYPE_PASS = 1;
  PIPE_TYPE_SELECT = 2;
  PIPE_TYPE_OPTION = 3;
  PIPE_TYPE_STREAM = 50;
}

// The level of interaction required for a notification.
enum NotificationLevel {
  NOTIFICATION_LEVEL_UNSPECIFIED = 0;
  NOTIFICATION_LEVEL_PASSIVE = 1;
  NOTIFICATION_LEVEL_ACTIVE = 2;
  NOTIFICATION_LEVEL_URGENT = 3;
}

enum RuntimeMode {
  RUNTIME_MODE_UNSPECIFIED = 0;
  RUNTIME_MODE_PRODUCTION = 1;
  RUNTIME_MODE_DEVELOPMENT = 2;
  RUNTIME_MODE_TEST = 3;
}

enum SpaceType {
  SPACE_TYPE_UNSPECIFIED = 0;
  SPACE_TYPE_DESKTOP = 10;
  SPACE_TYPE_BROWSER = 20;
  SPACE_TYPE_MOBILE = 30;
}

enum ViewType {
  VIEW_TYPE_UNSPECIFIED = 0;
  VIEW_TYPE_USER_WIZARD = 1;
  VIEW_TYPE_BENCH_WIZARD = 2;
  VIEW_TYPE_EMPTY = 100;
  VIEW_TYPE_PAGE = 201;
  VIEW_TYPE_BLOCK = 202;
  VIEW_TYPE_FIELD = 203;
  VIEW_TYPE_DATABASE = 204;
  VIEW_TYPE_VIEW = 205;
  VIEW_TYPE_FLOW = 206;
  VIEW_TYPE_STEP = 207;
  VIEW_TYPE_PIPE = 208;
  VIEW_TYPE_TYPE = 209;
  VIEW_TYPE_OBJECT = 210;
  VIEW_TYPE_TREE = 400;
  VIEW_TYPE_DETAIL = 403;
  VIEW_TYPE_CREATE = 404;
  VIEW_TYPE_CHAT = 405;
  VIEW_TYPE_RUN = 406;
  VIEW_TYPE_FEED = 407;
  VIEW_TYPE_TIMELINE = 408;
  VIEW_TYPE_HUB = 409;
  VIEW_TYPE_HELP = 411;
  VIEW_TYPE_WINDOW = 1000;
  VIEW_TYPE_TAB = 1002;
  VIEW_TYPE_HISTORY = 1003;
  VIEW_TYPE_SPLIT = 1005;
  VIEW_TYPE_SPLIT_DRAWER = 1006;
  VIEW_TYPE_STACK = 1010;
  VIEW_TYPE_DRAWER = 1011;
  VIEW_TYPE_SCROLL = 1012;
  VIEW_TYPE_GRID = 1013;
  VIEW_TYPE_GROUP = 1030;
  VIEW_TYPE_SECTION = 1031;
  VIEW_TYPE_FORM = 1032;
  VIEW_TYPE_SPACER = 1040;
  VIEW_TYPE_DIVIDER = 1041;
  VIEW_TYPE_LIST = 1050;
  VIEW_TYPE_TABLE = 1051;
  VIEW_TYPE_GALLERY = 1052;
  VIEW_TYPE_BOARD = 1053;
  VIEW_TYPE_BREADCRUMB = 1100;
  VIEW_TYPE_PROGRESS = 1101;
  VIEW_TYPE_AVATAR = 1102;
  VIEW_TYPE_BADGE = 1103;
  VIEW_TYPE_SHAPE = 1130;
  VIEW_TYPE_CHART = 1140;
  VIEW_TYPE_BUTTON = 1200;
  VIEW_TYPE_MULTI_BUTTON = 1201;
  VIEW_TYPE_LINK = 1210;
  VIEW_TYPE_VALUE = 1300;
  VIEW_TYPE_NUMBER = 1310;
  VIEW_TYPE_SLIDER = 1311;
  VIEW_TYPE_STRING = 1320;
  VIEW_TYPE_TEXT = 1321;
  VIEW_TYPE_CODE = 1322;
  VIEW_TYPE_JSON = 1323;
  VIEW_TYPE_TOGGLE = 1330;
  VIEW_TYPE_PICKER = 1331;
  VIEW_TYPE_COLOR = 1340;
  VIEW_TYPE_ICON = 1341;
  VIEW_TYPE_FILE = 1350;
  VIEW_TYPE_IMAGE = 1353;
  VIEW_TYPE_AUDIO = 1354;
  VIEW_TYPE_VIDEO = 1355;
  VIEW_TYPE_DOCUMENT = 1356;
  VIEW_TYPE_CONDITIONAL = 1361;
  VIEW_TYPE_SORT = 1362;
  VIEW_TYPE_AGGREGATION = 1363;
}

// The style variant of a view.
enum Variant {
  VARIANT_UNSPECIFIED = 0;
  VARIANT_PRIMARY = 1;
  VARIANT_SECONDARY = 2;
  VARIANT_COMPACT = 3;
  VARIANT_STEALTH = 4;
}

// Built-in color types a la SwiftUI or Tailwind.
enum ColorType {
  COLOR_TYPE_UNSPECIFIED = 0;
  COLOR_TYPE_PRIMARY = 1;
  COLOR_TYPE_SECONDARY = 2;
  COLOR_TYPE_ACCENT = 3;
  COLOR_TYPE_CANVAS = 4;
  COLOR_TYPE_SUCCESS = 10;
  COLOR_TYPE_HINT = 11;
  COLOR_TYPE_WARNING = 12;
  COLOR_TYPE_DANGER = 13;
  COLOR_TYPE_GRAY = 30;
  COLOR_TYPE_RED = 31;
  COLOR_TYPE_ORANGE = 32;
  COLOR_TYPE_AMBER = 33;
  COLOR_TYPE_YELLOW = 34;
  COLOR_TYPE_LIME = 35;
  COLOR_TYPE_GREEN = 36;
  COLOR_TYPE_EMERALD = 37;
  COLOR_TYPE_TEAL = 38;
  COLOR_TYPE_CYAN = 39;
  COLOR_TYPE_SKY = 40;
  COLOR_TYPE_BLUE = 41;
  COLOR_TYPE_INDIGO = 42;
  COLOR_TYPE_VIOLET = 43;
  COLOR_TYPE_PURPLE = 44;
  COLOR_TYPE_FUCHSIA = 45;
  COLOR_TYPE_PINK = 46;
  COLOR_TYPE_ROSE = 47;
}

// Built-in color shades a la Tailwind.
enum ColorShade {
  COLOR_SHADE_UNSPECIFIED = 0;
  COLOR_SHADE_S50 = 50;
  COLOR_SHADE_S100 = 100;
  COLOR_SHADE_S200 = 200;
  COLOR_SHADE_S300 = 300;
  COLOR_SHADE_S400 = 400;
  COLOR_SHADE_S500 = 500;
  COLOR_SHADE_S600 = 600;
  COLOR_SHADE_S700 = 700;
  COLOR_SHADE_S800 = 800;
  COLOR_SHADE_S900 = 900;
  COLOR_SHADE_S950 = 950;
}

enum FontType {
  FONT_TYPE_UNSPECIFIED = 0;
  FONT_TYPE_SERIF = 1;
  FONT_TYPE_SANS = 2;
  FONT_TYPE_MONO = 3;
}

enum FontWeight {
  FONT_WEIGHT_UNSPECIFIED = 0;
  FONT_WEIGHT_THIN = 100;
  FONT_WEIGHT_EXTRA_LIGHT = 200;
  FONT_WEIGHT_LIGHT = 300;
  FONT_WEIGHT_NORMAL = 400;
  FONT_WEIGHT_MEDIUM = 500;
  FONT_WEIGHT_SEMI_BOLD = 600;
  FONT_WEIGHT_BOLD = 700;
  FONT_WEIGHT_EXTRA_BOLD = 800;
  FONT_WEIGHT_BLACK = 900;
}

enum FontSize {
  FONT_SIZE_UNSPECIFIED = 0;
  FONT_SIZE_XS = 12;
  FONT_SIZE_SM = 14;
  FONT_SIZE_BASE = 16;
  FONT_SIZE_LG = 18;
  FONT_SIZE_XL = 20;
  FONT_SIZE_XL2 = 24;
  FONT_SIZE_XL3 = 30;
  FONT_SIZE_XL4 = 36;
  FONT_SIZE_XL5 = 48;
  FONT_SIZE_XL6 = 60;
  FONT_SIZE_XL7 = 72;
}

// The spacing scale for positions, padding, margin, etc. We don't enforce this.
enum Spacing {
  SPACING_UNSPECIFIED = 0;
  SPACING_S1 = 1;
  SPACING_S2 = 2;
  SPACING_S3 = 3;
  SPACING_S4 = 4;
  SPACING_S6 = 6;
  SPACING_S8 = 8;
  SPACING_S10 = 10;
  SPACING_S12 = 12;
  SPACING_S14 = 14;
  SPACING_S16 = 16;
  SPACING_S20 = 20;
  SPACING_S24 = 24;
  SPACING_S28 = 28;
  SPACING_S32 = 32;
  SPACING_S36 = 36;
  SPACING_S40 = 40;
  SPACING_S44 = 44;
  SPACING_S48 = 48;
  SPACING_S52 = 52;
  SPACING_S56 = 56;
  SPACING_S60 = 60;
  SPACING_S64 = 64;
  SPACING_S72 = 72;
  SPACING_S80 = 80;
  SPACING_S96 = 96;
  SPACING_S128 = 128;
  SPACING_S160 = 160;
  SPACING_S192 = 192;
  SPACING_S224 = 224;
  SPACING_S256 = 256;
}

// An anchor in 2D space.
enum Anchor {
  ANCHOR_UNSPECIFIED = 0;
  ANCHOR_TOP = 1;
  ANCHOR_TOP_LEFT = 2;
  ANCHOR_TOP_RIGHT = 3;
  ANCHOR_RIGHT = 11;
  ANCHOR_RIGHT_TOP = 12;
  ANCHOR_RIGHT_BOTTOM = 13;
  ANCHOR_BOTTOM = 21;
  ANCHOR_BOTTOM_LEFT = 22;
  ANCHOR_BOTTOM_RIGHT = 23;
  ANCHOR_LEFT = 31;
  ANCHOR_LEFT_TOP = 32;
  ANCHOR_LEFT_BOTTOM = 33;
}

// Which way to orient the contents/subviews of a view.
enum Orientation {
  ORIENTATION_UNSPECIFIED = 0;
  ORIENTATION_HORIZONTAL = 1;
  ORIENTATION_HORIZONTAL_REVERSED = 2;
  ORIENTATION_VERTICAL = 11;
  ORIENTATION_VERTICAL_REVERSED = 12;
}

// How to align the contents/subviews of a view along its orientation.
enum Alignment {
  ALIGNMENT_UNSPECIFIED = 0;
  ALIGNMENT_START = 1;
  ALIGNMENT_MIDDLE = 2;
  ALIGNMENT_END = 3;
  ALIGNMENT_SPACE_BETWEEN = 4;
}

// The stage of a User view.
enum UserWizardViewStage {
  USER_WIZARD_VIEW_STAGE_UNSPECIFIED = 0;
  USER_WIZARD_VIEW_STAGE_SIGN_UP = 1;
  USER_WIZARD_VIEW_STAGE_LOG_IN = 2;
}

enum TreeViewPreset {
  TREE_VIEW_PRESET_UNSPECIFIED = 0;
  TREE_VIEW_PRESET_EXPLORE = 1;
  TREE_VIEW_PRESET_OUTLINE = 2;
}

enum HubAspect {
  HUB_ASPECT_UNSPECIFIED = 0;
  HUB_ASPECT_BENCH = 1;
  HUB_ASPECT_ACTIVITY = 2;
  HUB_ASPECT_CATALOG = 3;
  HUB_ASPECT_LIBRARY = 4;
}

enum HelpAspect {
  HELP_ASPECT_UNSPECIFIED = 0;
  HELP_ASPECT_DETAIL = 1;
  HELP_ASPECT_RUN = 2;
  HELP_ASPECT_CHAT = 3;
  HELP_ASPECT_VERSION = 4;
}

enum UserStatus {
  USER_STATUS_UNSPECIFIED = 0;
  USER_STATUS_INVITED = 1;
  USER_STATUS_RESERVED = 2;
  USER_STATUS_WAITLISTED = 3;
  USER_STATUS_REGISTERED = 4;
  USER_STATUS_ACTIVATED = 10;
}

enum OrganizationStatus {
  ORGANIZATION_STATUS_UNSPECIFIED = 0;
  ORGANIZATION_STATUS_REGISTERED = 4;
  ORGANIZATION_STATUS_ACTIVATED = 10;
}

message GraphScopeData {
  ObjectType metatype = 1;
  optional string bench_id = 30;
  optional string package_id = 31;
}

message ClientOriginData {
  ObjectType metatype = 1;
  ClientType type = 30;
  optional string id = 31;
  optional string nonce = 32;
}

message NodeReferenceData {
  ObjectType metatype = 1;
  NodeType node_type = 30;
  optional string id = 31;
  optional string ck = 32;
  optional string bench_id = 33;
  optional string base_ck = 34;
  optional string base_bench_id = 35;
}

message PropertyReferenceData {
  ObjectType metatype = 1;
  optional ObjectType type = 30;
  int32 id = 31;
  optional NodeType references_node = 32;
  optional string references_meta = 33;
}

message VariableObjectData {
  ObjectType metatype = 1;
}

message MemberObjectData {
  ObjectType metatype = 1;
}

message InputObjectData {
  ObjectType metatype = 1;
  optional TextData text = 100;
}

message OutputObjectData {
  ObjectType metatype = 1;
  optional TextData text = 100;
  optional CallData call = 110;
  repeated ContinueData continuations = 111;
}

message ValueData {
  ObjectType metatype = 1;
  TypeInfoData type = 31;
  optional string name = 32;
  optional TextData text = 34;
  optional google.protobuf.Value value_packed = 35;
}

message SelectionData {
  ObjectType metatype = 1;
  repeated NodeReferenceData nodes_ptr = 40;
  repeated NodeReferenceData fields_ptr = 41;
}

message ExpressionData {
  ObjectType metatype = 1;
  ExpressionType type = 30;
  optional PropertyReferenceData property_ptr = 31;
  optional NodeReferenceData field_ptr = 32;
  optional NodeReferenceData block_ptr = 33;
  repeated ExpressionData clauses = 40;
  optional google.protobuf.Value value_packed = 46;
  optional SortMode sort_mode = 48;
  optional float tolerance = 49;
}

message AggregationResultData {
  ObjectType metatype = 1;
  AggregationType op = 30;
  optional bool exists = 31;
  optional int32 count = 32;
  optional float scalar = 33;
}

message ComputedValueData {
  ObjectType metatype = 1;
  optional ExpressionData expression = 35;
  optional CodeData code = 36;
}

message TypeConstraintData {
  ObjectType metatype = 1;
  optional float min_value = 40;
  optional float max_value = 41;
  optional float step_value = 42;
  optional int32 min_length = 50;
  optional int32 max_length = 51;
  optional string regex = 60;
  optional string starts_with = 61;
  optional string ends_with = 62;
  optional bool node_is_attached = 70;
  repeated NodeType node_types = 71;
  repeated NodeReferenceData node_scope_ptr = 72;
  optional int32 node_max_depth = 73;
  repeated BlockType block_types = 80;
  repeated StepType step_types = 81;
  repeated FileType file_types = 82;
  repeated FileFormat file_formats = 83;
  repeated ViewType view_types = 84;
}

message TypeInfoData {
  ObjectType metatype = 1;
  TypeKind kind = 40;
  optional PrimitiveType primitive_type = 41;
  optional BenchType bench_type = 42;
  optional NodeReferenceData base_type_ptr = 43;
  optional FieldType base_field_type = 44;
  optional NodeReferenceData oneof_ptr = 45;
  optional google.protobuf.Value default_packed = 50;
  optional TypeFormat format = 53;
  optional ExpressionData condition = 54;
  optional TypeConstraintData constraint = 55;
  bool is_required = 60;
  bool is_list = 61;
  bool is_secret = 62;
}

message TextSpanData {
  ObjectType metatype = 1;
  optional string content = 33;
  optional NodeReferenceData node_ptr = 34;
  optional ColorType color = 50;
  optional bool is_bold = 60;
  optional bool is_italic = 61;
  optional bool is_strikethrough = 62;
  optional bool is_underline = 63;
  optional bool is_code = 64;
}

message TextLineData {
  ObjectType metatype = 1;
  TextLineType type = 30;
  repeated TextSpanData spans = 33;
  optional ColorType color = 50;
  optional bool is_bold = 60;
  optional bool is_italic = 61;
  optional bool is_strikethrough = 62;
  optional bool is_underline = 63;
  optional bool is_code = 64;
}

message TextData {
  ObjectType metatype = 1;
  repeated TextLineData lines = 32;
}

message PolicyData {
  ObjectType metatype = 1;
  string name = 30;
  optional TextData text = 31;
  repeated PolicyRuleData rules = 32;
  repeated NodeReferenceData scopes_ptr = 33;
}

message PolicyRuleData {
  ObjectType metatype = 1;
  string name = 30;
  optional TextData text = 31;
  optional bool subject_is_delegated = 40;
  optional bool subject_is_authenticated = 41;
  optional bool subject_is_staff = 42;
  optional bool subject_is_member = 43;
  optional bool subject_is_owner = 44;
  PolicyEffect effect = 60;
  repeated AccessType verbs = 61;
  repeated AccessKind verb_kinds = 62;
  repeated NodeType object_node_types = 80;
  repeated PropertyReferenceData object_properties_ptr = 81;
  optional bool object_properties_is_system = 82;
  optional bool object_properties_is_sensitive = 83;
  optional bool object_properties_is_kernel = 84;
}

message SubjectData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional bool is_authenticated = 30;
  optional bool is_staff = 31;
  optional bool is_system = 32;
  optional NodeReferenceData client_ptr = 40;
  optional NodeReferenceData user_ptr = 41;
  optional NodeReferenceData server_ptr = 42;
  optional NodeReferenceData identity_ptr = 50;
  repeated NodeReferenceData badges_ptr = 51;
  repeated NodeReferenceData owned_ptr = 52;
  repeated NodeReferenceData memberships_ptr = 53;
  repeated NodeReferenceData roles_ptr = 54;
}

message AccessZoneData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 4;
  string scope_id = 30;
  int32 identity_id = 31;
  repeated PolicyRuleData rules = 32;
}

message AccessMatrixData {
  ObjectType metatype = 1;
  SubjectData subject = 30;
  repeated SubjectData identities = 32;
  repeated AccessZoneData scoped_zones = 33;
  repeated AccessZoneData base_zones = 34;
}

message AccessData {
  ObjectType metatype = 1;
  AccessMode mode = 30;
  PolicyEffect decision = 31;
  AccessType verb = 32;
  NodeType node_type = 33;
  repeated PropertyReferenceData allowed_properties_ptr = 34;
}

message CallData {
  ObjectType metatype = 1;
  NodeReferenceData node_ptr = 30;
  optional google.protobuf.Value inputs_packed = 31;
  optional ObjectMappingData mapping = 50;
  optional CodeData mapping_code = 51;
}

message ContinueData {
  ObjectType metatype = 1;
  NodeReferenceData node_ptr = 30;
  optional google.protobuf.Value inputs_packed = 31;
  optional ObjectMappingData mapping = 50;
  optional CodeData mapping_code = 51;
}

message SelectOptionsData {
  ObjectType metatype = 1;
  bool select_all_properties = 40;
  repeated PropertyReferenceData include_properties_ptr = 41;
  repeated PropertyReferenceData exclude_properties_ptr = 42;
  repeated PropertyReferenceData select_properties_ptr = 43;
  repeated NodeReferenceData select_fields_ptr = 51;
}

message CodeLineData {
  ObjectType metatype = 1;
  optional string content = 32;
}

message CodeData {
  ObjectType metatype = 1;
  repeated CodeLineData lines = 30;
}

message FileInfoData {
  ObjectType metatype = 1;
  FileKind kind = 40;
  string title = 41;
  optional string external_url = 43;
  optional bytes inline_content = 44;
  FileType type = 50;
  optional string mime_type = 51;
  optional FileFormat format = 52;
  int64 size = 53;
  optional string sha256 = 54;
  optional int32 width = 55;
  optional int32 height = 56;
  optional float aspect_ratio = 57;
  optional string codec = 58;
  optional google.protobuf.Duration duration = 60;
  optional int32 bitrate = 61;
  optional int32 channels = 62;
  optional int32 sample_rate = 63;
}

message TextOptionsData {
  ObjectType metatype = 1;
  optional float temperature = 30;
}

message AudioOptionsData {
  ObjectType metatype = 1;
}

message ImageOptionsData {
  ObjectType metatype = 1;
}

message VideoOptionsData {
  ObjectType metatype = 1;
}

message RunOptionsData {
  ObjectType metatype = 1;
  optional int32 max_attempts = 30;
  optional int32 max_concurrency = 31;
  optional int32 max_runs = 32;
  optional google.protobuf.Duration timeout = 35;
  optional google.protobuf.Duration retry_interval = 40;
  optional float backoff = 41;
  optional google.protobuf.Duration max_retry_interval = 42;
  repeated RunErrorType retry_on = 44;
  optional bool suppress_fail = 45;
  optional bool suppress_abort = 46;
  optional bool suppress_pause = 47;
  repeated BreakpointData breakpoints = 60;
  optional CacheMode cache_mode = 70;
  optional google.protobuf.Duration cache_retention = 71;
  optional ModelProvider model_provider = 80;
  optional ModelType model_type = 81;
  optional TextOptionsData text_options = 82;
  optional AudioOptionsData audio_options = 83;
  optional ImageOptionsData image_options = 84;
  optional VideoOptionsData video_options = 85;
}

message RunAttemptData {
  ObjectType metatype = 1;
  optional CodeData code = 30;
  RunStatus status = 40;
  optional google.protobuf.Duration duration = 41;
  optional google.protobuf.Timestamp started_at = 42;
  optional int32 started_epoch = 43;
  optional google.protobuf.Timestamp terminated_at = 45;
  optional int32 terminated_epoch = 46;
  optional google.protobuf.Timestamp interrupted_at = 47;
  optional NodeReferenceData interrupt_ptr = 50;
  optional RunErrorData error = 51;
  optional google.protobuf.Value intermediates_packed = 54;
}

message RunTraceData {
  ObjectType metatype = 1;
  repeated RunFrameData frames = 30;
}

message RunFrameData {
  ObjectType metatype = 1;
}

message RunSpanData {
  ObjectType metatype = 1;
  RunSpanType type = 30;
  string name = 32;
  optional string title = 33;
  optional TextData text = 34;
  optional string text_plain = 35;
  optional google.protobuf.Timestamp started_at = 40;
  optional google.protobuf.Timestamp terminated_at = 41;
  optional google.protobuf.Duration duration = 42;
}

message RunEventData {
  ObjectType metatype = 1;
  RunEventType type = 30;
  string name = 32;
  optional string title = 33;
  optional TextData text = 34;
  optional string text_plain = 35;
  optional google.protobuf.Timestamp created_at = 40;
  optional LogLevel level = 41;
}

message RunErrorData {
  ObjectType metatype = 1;
  RunErrorKind kind = 30;
  RunErrorType type = 31;
  optional string title = 32;
  optional TextData text = 33;
  optional NodeReferenceData node_ptr = 34;
  optional RunTraceData trace = 35;
}

message ContextData {
  ObjectType metatype = 1;
}

message ObjectMappingData {
  ObjectType metatype = 1;
  repeated FieldMappingData field_mappings = 40;
}

message FieldMappingData {
  ObjectType metatype = 1;
  NodeReferenceData source_ptr = 35;
  NodeReferenceData target_ptr = 36;
}

message ScheduleData {
  ObjectType metatype = 1;
  ScheduleType type = 30;
  string timezone = 31;
  int32 every = 40;
  TimeInterval interval = 41;
  optional google.protobuf.Duration offset = 42;
  optional string cron = 50;
}

message BreakpointData {
  ObjectType metatype = 1;
  BreakpointSite site = 30;
  BreakpointScope scope = 31;
  BreakpointAction action = 32;
}

message LogInfoData {
  ObjectType metatype = 1;
  google.protobuf.Timestamp created_at = 11;
  LogLevel level = 31;
  optional TextData text = 61;
  optional string text_plain = 62;
  optional google.protobuf.Value value_packed = 65;
}

message MachineImageData {
  ObjectType metatype = 1;
}

message ColorData {
  ObjectType metatype = 1;
  optional ColorType type = 31;
  optional ColorShade shade = 32;
  optional string hex = 33;
}

message FontData {
  ObjectType metatype = 1;
  optional FontType type = 31;
  optional FontWeight weight = 32;
  optional FontSize size = 33;
}

message TransformData {
  ObjectType metatype = 1;
  optional float translate_x = 30;
  optional float translate_y = 31;
  optional float scale_x = 33;
  optional float scale_y = 34;
  optional float skew_x = 36;
  optional float skew_y = 37;
  optional float rotate_x = 40;
}

message RectangleData {
  ObjectType metatype = 1;
  optional int32 width = 50;
  optional int32 height = 51;
  optional float width_relative = 52;
  optional float height_relative = 53;
}

message OffsetData {
  ObjectType metatype = 1;
  optional int32 top = 40;
  optional int32 right = 41;
  optional int32 bottom = 42;
  optional int32 left = 43;
  optional float top_relative = 44;
  optional float right_relative = 45;
  optional float bottom_relative = 46;
  optional float left_relative = 47;
}

message Vector2Data {
  ObjectType metatype = 1;
  float x = 30;
  float y = 31;
}

message Vector3Data {
  ObjectType metatype = 1;
  float x = 30;
  float y = 31;
  float z = 32;
}

message Vector4Data {
  ObjectType metatype = 1;
  float x = 30;
  float y = 31;
  float z = 32;
  float w = 33;
}

message LineData {
  ObjectType metatype = 1;
  repeated Vector2Data points = 30;
}

message RectangleConstraintData {
  ObjectType metatype = 1;
  optional int32 min_width = 50;
  optional int32 max_width = 51;
  optional int32 min_height = 52;
  optional int32 max_height = 53;
}

message IconData {
  ObjectType metatype = 1;
  IconKind kind = 30;
  optional string emoji = 31;
  optional string fa_name = 33;
  optional string vsc_name = 34;
  optional ColorData color = 40;
}

message PathTokenData {
  ObjectType metatype = 1;
  PathTokenType type = 31;
  optional string name = 32;
}

message PathData {
  ObjectType metatype = 1;
  repeated PathTokenData tokens = 31;
}

message ChangeVignetteData {
  ObjectType metatype = 1;
  optional string name = 30;
  optional string title = 31;
  optional int32 subtype = 32;
  optional IconData icon = 35;
}

message EditOperationData {
  ObjectType metatype = 1;
  EditOperationType type = 30;
  repeated string path = 31;
  optional google.protobuf.Value new_value_packed = 40;
  optional google.protobuf.Value old_value_packed = 41;
}

message EditInfoData {
  ObjectType metatype = 1;
  string id = 2;
  EditType type = 30;
  NodeReferenceData node_ptr = 31;
  optional ChangeVignetteData vignette = 32;
  google.protobuf.Timestamp edited_at = 33;
  optional google.protobuf.Timestamp old_edited_at = 34;
  optional SomeNodeData node_data = 40;
  repeated EditOperationData operations = 41;
}

message EditData {
  ObjectType metatype = 1;
  string id = 2;
  EditType type = 30;
  NodeReferenceData node_ptr = 31;
  optional ChangeVignetteData vignette = 32;
  google.protobuf.Timestamp edited_at = 33;
  optional google.protobuf.Timestamp old_edited_at = 34;
  optional SomeNodeData node_data = 40;
  repeated EditOperationData operations = 41;
  GraphScopeData scope = 60;
  optional string change_key = 61;
  optional ChangeCategory category = 62;
  optional NodeReferenceData subject_ptr = 63;
  optional ClientOriginData origin = 64;
  optional EditContextData context = 65;
  optional int64 epoch = 68;
  optional NodeReferenceData undo_of_ptr = 69;
}

message ChangeData {
  ObjectType metatype = 1;
  string key = 30;
  optional NodeReferenceData scope_ptr = 32;
  optional CodeData code = 33;
  repeated EditData edits = 34;
}

message EditContextData {
  ObjectType metatype = 1;
  optional NodeReferenceData block_ptr = 70;
  optional NodeReferenceData step_ptr = 71;
  optional NodeReferenceData session_ptr = 72;
  optional NodeReferenceData run_ptr = 73;
  optional NodeReferenceData run_root_ptr = 74;
  optional NodeReferenceData identity_ptr = 75;
}

message RuntimeContextData {
  ObjectType metatype = 1;
  optional NodeReferenceData session_ptr = 80;
  optional NodeReferenceData run_ptr = 81;
  optional NodeReferenceData run_root_ptr = 82;
  optional NodeReferenceData client_ptr = 83;
  optional NodeReferenceData machine_ptr = 84;
  optional NodeReferenceData server_ptr = 85;
  optional NodeReferenceData user_ptr = 86;
  optional NodeReferenceData identity_ptr = 87;
}

message BaseNodeData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
}

message SkipData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  NodeReferenceData reference_ptr = 30;
  optional string order_key = 31;
}

message FieldData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  FieldType type = 30;
  string name = 31;
  string order_key = 32;
  optional TextData text = 33;
  optional IconData icon = 34;
  TypeKind kind = 40;
  optional PrimitiveType primitive_type = 41;
  optional BenchType bench_type = 42;
  optional NodeReferenceData base_type_ptr = 43;
  optional FieldType base_field_type = 44;
  optional NodeReferenceData oneof_ptr = 45;
  optional google.protobuf.Value default_packed = 50;
  optional TypeFormat format = 53;
  optional ExpressionData condition = 54;
  optional TypeConstraintData constraint = 55;
  bool is_required = 60;
  bool is_list = 61;
  bool is_secret = 62;
  RuntimeMode mode = 90;
}

message BenchData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  optional NodeReferenceData main_handle_ptr = 31;
  string slug = 32;
  string name = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  optional NodeReferenceData owner_ptr = 36;
  Region region = 37;
  optional string encryption_key = 38;
  repeated PolicyData policies = 39;
  optional NodeReferenceData main_store_ptr = 40;
  optional NodeReferenceData main_server_ptr = 41;
  optional NodeReferenceData main_drive_ptr = 42;
  optional NodeReferenceData main_vault_ptr = 43;
  optional NodeReferenceData main_cache_ptr = 44;
  optional NodeReferenceData main_branch_ptr = 50;
}

message BranchData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  string name = 32;
  optional string slug = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  repeated PolicyData policies = 36;
  optional NodeReferenceData main_package_ptr = 40;
  optional NodeReferenceData base_ptr = 41;
  bool is_overlay = 60;
  bool is_light = 61;
}

message PackageData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  optional TextData text = 34;
  optional IconData icon = 35;
  repeated PolicyData policies = 36;
  optional NodeReferenceData base_ptr = 40;
  bool is_snapshot = 60;
  bool is_overlay = 61;
}

message DependencyData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  repeated NodeReferenceData scopes_ptr = 30;
  NodeReferenceData dependency_ptr = 40;
  RuntimeMode mode = 90;
}

message ServerData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  ResourceStatus current_status = 37;
  string version = 40;
  optional string current_version = 41;
  optional float min_cpu = 50;
  optional float max_cpu = 51;
  optional float min_ram = 52;
  optional float max_ram = 53;
  optional google.protobuf.Timestamp active_at = 60;
  optional google.protobuf.Timestamp bumped_at = 61;
  RuntimeMode mode = 90;
}

message StoreData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  ResourceStatus current_status = 37;
  string version = 40;
  optional string current_version = 41;
  optional string external_name = 50;
  optional string external_id = 51;
  optional string connection_uri = 52;
  RuntimeMode mode = 90;
}

message DriveData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  ResourceStatus current_status = 37;
  RuntimeMode mode = 90;
}

message VaultData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  ResourceStatus current_status = 37;
  RuntimeMode mode = 90;
}

message CacheData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  ResourceStatus current_status = 37;
  RuntimeMode mode = 90;
}

message ClientData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  ClientType type = 30;
  string title = 32;
  optional string device_type = 40;
  optional string device_name = 41;
  optional string operating_system = 42;
  optional string browser_name = 43;
  optional string browser_version = 44;
  optional string place_id = 45;
  optional string access_token = 50;
  optional google.protobuf.Timestamp seen_at = 51;
  optional google.protobuf.Timestamp logged_in_at = 52;
  optional NodeReferenceData space_ptr = 60;
  optional NodeReferenceData machine_ptr = 61;
}

message HandleData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  string slug = 30;
}

message UserData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  optional NodeReferenceData main_handle_ptr = 31;
  optional string slug = 32;
  string name = 33;
  optional TextData text = 34;
  optional string email = 35;
  optional IconData icon = 36;
  optional NodeReferenceData main_bench_ptr = 37;
  UserStatus status = 38;
  optional bytes password_salt = 50;
  optional bytes password_hash = 51;
  optional google.protobuf.Timestamp last_logged_in_at = 70;
  bool is_staff = 90;
}

message OrganizationData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  optional NodeReferenceData main_handle_ptr = 31;
  optional string slug = 32;
  string name = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  optional NodeReferenceData main_bench_ptr = 36;
  OrganizationStatus status = 37;
}

message MembershipData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  NodeReferenceData user_ptr = 30;
  bool is_owner = 31;
}

message InviteData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  optional NodeReferenceData user_ptr = 30;
  optional string user_email = 31;
  bool is_owner = 32;
  repeated NodeReferenceData roles_ptr = 33;
}

message BadgeData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  string name = 31;
  repeated PolicyData delegated_policies = 32;
  optional google.protobuf.Timestamp expires_at = 33;
  optional string key = 40;
  optional string key_hash = 41;
  optional string password = 42;
  optional string password_hash = 43;
  RuntimeMode mode = 90;
}

message QueryData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  QueryType type = 30;
  string name = 31;
  string order_key = 32;
  NodeType node_type = 41;
  optional NodeReferenceData block_ptr = 42;
  repeated NodeReferenceData roots_ptr = 43;
  optional ExpressionData filter = 44;
  repeated ExpressionData sort = 45;
  optional ExpressionData aggregation = 46;
  repeated NodeType ancestor_types = 50;
  repeated NodeType descendant_types = 51;
  optional SelectOptionsData select = 60;
  bool include_deleted = 61;
  optional int32 first = 62;
  optional int32 skip = 63;
  RuntimeMode mode = 90;
}

message BlockData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  BlockType type = 30;
  string name = 32;
  string order_key = 33;
  optional IconData icon = 34;
  optional TextData text = 35;
  optional google.protobuf.Value variables_packed = 40;
  optional RunOptionsData run_options = 41;
  repeated PolicyData policies = 42;
  repeated PolicyData delegated_policies = 43;
  repeated NodeReferenceData roles_ptr = 44;
  optional NodeReferenceData identity_ptr = 45;
  bool is_builtin = 60;
  bool is_owned = 61;
  RuntimeMode mode = 90;
}

// A building block with logic, types, UI, state, auth, AI, ...
message ValueBlockData {
  optional TypeInfoData value_type = 100;
  optional google.protobuf.Value value_packed = 101;
}

// A building block with logic, types, UI, state, auth, AI, ...
message ActionBlockData {
  Agency agency = 100;
  bool is_dynamic = 101;
  optional CodeData code = 111;
  repeated NodeReferenceData tools_ptr = 112;
  optional NodeReferenceData delegate_ptr = 113;
}

// A building block with logic, types, UI, state, auth, AI, ...
message TextBlockData {
}

// A building block with logic, types, UI, state, auth, AI, ...
message FlowBlockData {
}

// A building block with logic, types, UI, state, auth, AI, ...
message DatabaseBlockData {
  optional NodeReferenceData query_ptr = 100;
}

// A building block with logic, types, UI, state, auth, AI, ...
message QueryBlockData {
  optional NodeReferenceData query_ptr = 100;
}

message RecordData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  optional string title = 32;
  optional TextData text = 33;
  optional string order_key = 34;
  NodeReferenceData block_ptr = 36;
  optional google.protobuf.Value value_packed = 40;
  RuntimeMode mode = 90;
}

message FileData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  ResourceStatus current_status = 37;
  FileKind kind = 40;
  string title = 41;
  optional string external_url = 43;
  optional bytes inline_content = 44;
  FileType type = 50;
  optional string mime_type = 51;
  optional FileFormat format = 52;
  int64 size = 53;
  optional string sha256 = 54;
  optional int32 width = 55;
  optional int32 height = 56;
  optional float aspect_ratio = 57;
  optional string codec = 58;
  optional google.protobuf.Duration duration = 60;
  optional int32 bitrate = 61;
  optional int32 channels = 62;
  optional int32 sample_rate = 63;
  FileRetentionMode retention = 70;
  optional google.protobuf.Timestamp expires_at = 71;
  RuntimeMode mode = 90;
}

message RunData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  RunType type = 30;
  optional NodeReferenceData root_ptr = 31;
  optional NodeReferenceData block_ptr = 32;
  optional NodeReferenceData step_ptr = 33;
  optional NodeReferenceData pipe_ptr = 34;
  repeated NodeReferenceData incoming_ptr = 36;
  repeated NodeReferenceData outgoing_ptr = 37;
  optional ContextData context = 38;
  RunOptionsData options = 39;
  RunStatus status = 40;
  optional google.protobuf.Duration duration = 41;
  repeated RunAttemptData attempts = 44;
  optional RunErrorData error = 45;
  optional google.protobuf.Timestamp scheduled_at = 46;
  optional int32 scheduled_epoch = 47;
  optional google.protobuf.Timestamp started_at = 48;
  optional int32 started_epoch = 49;
  optional google.protobuf.Timestamp killed_at = 50;
  optional google.protobuf.Timestamp interrupted_at = 51;
  optional NodeReferenceData interrupt_ptr = 52;
  optional google.protobuf.Timestamp paused_at = 53;
  optional google.protobuf.Timestamp resumed_at = 54;
  optional google.protobuf.Timestamp terminated_at = 55;
  optional int32 terminated_epoch = 56;
  optional google.protobuf.Value variables_packed = 60;
  optional google.protobuf.Value inputs_packed = 61;
  optional google.protobuf.Value intermediates_packed = 62;
  optional google.protobuf.Value outputs_packed = 63;
  repeated LogInfoData logs = 65;
  repeated RunSpanData spans = 66;
  repeated RunEventData events = 67;
  optional NodeReferenceData session_ptr = 80;
  optional NodeReferenceData run_ptr = 81;
  optional NodeReferenceData run_root_ptr = 82;
  optional NodeReferenceData client_ptr = 83;
  optional NodeReferenceData machine_ptr = 84;
  optional NodeReferenceData server_ptr = 85;
  optional NodeReferenceData user_ptr = 86;
  optional NodeReferenceData identity_ptr = 87;
  RuntimeMode mode = 90;
}

message PipeData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  PipeType type = 30;
  string name = 32;
  string order_key = 33;
  optional TextData text = 34;
  NodeReferenceData source_ptr = 35;
  NodeReferenceData target_ptr = 36;
  optional RunOptionsData run_options = 50;
  optional ExpressionData condition = 60;
  optional CodeData condition_code = 61;
  optional TypeConstraintData constraint = 62;
  optional ObjectMappingData mapping = 70;
  optional CodeData mapping_code = 71;
  optional google.protobuf.Duration delay = 80;
  RuntimeMode mode = 90;
  optional ColorData color = 91;
  bool is_hidden = 92;
  bool is_name_hidden = 93;
}

// A connection between two Steps in a Flow (source = outgoing, target = incoming).
// Pipes are stored in the containing Flow or containing Step.
message SelectPipeData {
}

message StepData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  StepType type = 30;
  string name = 32;
  string order_key = 33;
  optional IconData icon = 35;
  optional TextData text = 36;
  optional RunOptionsData run_options = 41;
  repeated NodeReferenceData roles_ptr = 42;
  optional NodeReferenceData identity_ptr = 43;
  optional Vector2Data position = 80;
  optional RectangleData size = 81;
  RuntimeMode mode = 90;
}

// A data or control flow node in a Flow. Steps are connected by Pipes.
message ActionStepData {
  Agency agency = 100;
  bool is_dynamic = 101;
  optional CodeData code = 111;
  repeated NodeReferenceData tools_ptr = 112;
  optional NodeReferenceData delegate_ptr = 113;
}

// A data or control flow node in a Flow. Steps are connected by Pipes.
message CreateStepData {
  NodeType node_type = 100;
  FieldType field_type = 101;
  optional NodeReferenceData block_base_ptr = 102;
}

// A data or control flow node in a Flow. Steps are connected by Pipes.
message LoopStepData {
  optional NodeReferenceData for_field_ptr = 100;
}

// A data or control flow node in a Flow. Steps are connected by Pipes.
message TextStepData {
}

message TriggerData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  TriggerType type = 30;
  string name = 31;
  bool is_paused = 35;
  optional int32 processed_epoch = 36;
  optional ScheduleData schedule = 50;
  optional NodeReferenceData message_ptr = 51;
  optional ExpressionData condition = 52;
  RuntimeMode mode = 90;
}

message InterruptData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  InterruptType type = 30;
  optional NodeReferenceData root_ptr = 31;
  optional NodeReferenceData block_ptr = 32;
  optional NodeReferenceData step_ptr = 33;
  optional NodeReferenceData pipe_ptr = 34;
  optional int32 attempt_no = 37;
  optional BreakpointSite breakpoint_site = 38;
  InterruptStatus status = 40;
  optional google.protobuf.Duration duration = 41;
  optional google.protobuf.Timestamp closed_at = 42;
  optional NodeReferenceData trigger_ptr = 49;
  optional google.protobuf.Value inputs_packed = 51;
  optional google.protobuf.Value outputs_packed = 52;
  optional NodeReferenceData session_ptr = 80;
  optional NodeReferenceData run_ptr = 81;
  optional NodeReferenceData run_root_ptr = 82;
  optional NodeReferenceData client_ptr = 83;
  optional NodeReferenceData machine_ptr = 84;
  optional NodeReferenceData server_ptr = 85;
  optional NodeReferenceData user_ptr = 86;
  optional NodeReferenceData identity_ptr = 87;
  RuntimeMode mode = 90;
}

message LogData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  LogKind kind = 30;
  LogLevel level = 31;
  optional NodeReferenceData change_ptr = 32;
  optional NodeReferenceData undo_of_ptr = 33;
  optional AccessType type = 40;
  optional NodeReferenceData node_ptr = 41;
  optional google.protobuf.Value node_data = 43;
  repeated EditOperationData operations = 44;
  optional ChangeCategory category = 48;
  optional ChangeVignetteData vignette = 49;
  optional NodeReferenceData session_ptr = 80;
  optional NodeReferenceData run_ptr = 81;
  optional NodeReferenceData run_root_ptr = 82;
  optional NodeReferenceData client_ptr = 83;
  optional NodeReferenceData machine_ptr = 84;
  optional NodeReferenceData server_ptr = 85;
  optional NodeReferenceData user_ptr = 86;
  optional NodeReferenceData identity_ptr = 87;
  RuntimeMode mode = 90;
}

message MachineData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  MachineType type = 30;
  string title = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  ResourceStatus current_status = 37;
  string version = 40;
  optional string current_version = 41;
  optional string external_name = 42;
  optional string external_id = 43;
  optional string connection_uri = 44;
  optional NodeReferenceData client_ptr = 45;
  float cpu = 50;
  optional float current_cpu = 51;
  float ram = 52;
  optional float current_ram = 53;
  optional google.protobuf.Timestamp started_at = 60;
  optional google.protobuf.Timestamp killed_at = 61;
  optional google.protobuf.Timestamp terminated_at = 62;
  optional google.protobuf.Timestamp active_at = 63;
  optional google.protobuf.Timestamp restarted_at = 64;
  RuntimeMode mode = 90;
}

message BrowserData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  ResourceStatus current_status = 37;
  RuntimeMode mode = 90;
}

message MessageData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  MessageType type = 30;
  MessageStatus status = 31;
  NodeReferenceData origin_ptr = 35;
  optional NodeReferenceData block_ptr = 36;
  optional NodeReferenceData reply_to_ptr = 37;
  optional string title = 40;
  optional TextData text = 41;
  optional google.protobuf.Value value_packed = 42;
  optional google.protobuf.Timestamp expires_at = 44;
  optional google.protobuf.Timestamp read_at = 45;
  bool is_pinned = 50;
  RuntimeMode mode = 90;
}

message ViewData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  ViewType type = 30;
  string name = 31;
  optional string title = 32;
  string order_key = 34;
  optional IconData icon = 35;
  optional google.protobuf.Value subviews_packed = 39;
  optional TypeInfoData value_type = 40;
  optional NodeReferenceData node_ptr = 42;
  optional Variant variant = 50;
  optional FontData font = 51;
  optional OffsetData position = 60;
  optional RectangleData size = 61;
  optional OffsetData margin = 62;
  optional OffsetData padding = 63;
  optional Orientation orientation = 64;
  optional Alignment alignment = 65;
  optional TransformData transform = 66;
  optional RectangleConstraintData constraint = 67;
  optional SelectionData selection = 70;
  optional SelectionData focus = 71;
  bool is_hidden = 80;
  bool is_disabled = 81;
  bool is_input = 82;
  bool is_inline = 83;
  bool is_loading = 85;
  RuntimeMode mode = 90;
}

// A view of a user interface in a Bench.
message TreeViewData {
  repeated NodeType node_types = 100;
  optional bool filter_is_page = 101;
  optional bool is_default_expanded = 102;
  repeated NodeReferenceData expanded_nodes_ptr = 103;
  repeated NodeReferenceData collapsed_nodes_ptr = 104;
  optional TreeViewPreset preset = 110;
}

// A view of a user interface in a Bench.
message RunViewData {
  optional google.protobuf.Value inputs_packed = 100;
}

// A view of a user interface in a Bench.
message FeedViewData {
  optional NodeType query_node_type = 100;
  optional ExpressionData filter = 101;
  repeated string filter_pills = 102;
}

// A view of a user interface in a Bench.
message HubViewData {
  HubAspect aspect = 100;
}

// A view of a user interface in a Bench.
message HelpViewData {
  HelpAspect aspect = 100;
}

// A view of a user interface in a Bench.
message DetailViewData {
  repeated string expanded_sections = 100;
  repeated string collapsed_sections = 101;
}

// A view of a user interface in a Bench.
message UserWizardViewData {
  optional UserWizardViewStage stage = 100;
}

// A view of a user interface in a Bench.
message IconViewData {
  bool include_color = 100;
}

message SpaceData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  SpaceType type = 30;
  string name = 31;
  optional TextData text = 32;
  string order_key = 33;
  repeated PolicyData policies = 34;
  optional SelectionData focus = 70;
  optional NodeReferenceData inspection_ptr = 75;
  optional NodeReferenceData base_ptr = 76;
  optional NodeReferenceData run_ptr = 77;
  RuntimeMode mode = 90;
}

message SecretData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  string title = 33;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  ResourceStatus current_status = 37;
  TypeInfoData value_type = 40;
  optional google.protobuf.Value value_packed = 41;
  RuntimeMode mode = 90;
}

message SessionData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData package_ptr = 5;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  SessionStatus status = 40;
  optional google.protobuf.Duration duration = 41;
  optional google.protobuf.Timestamp opened_at = 42;
  optional google.protobuf.Timestamp closed_at = 43;
  optional NodeReferenceData session_ptr = 80;
  optional NodeReferenceData run_ptr = 81;
  optional NodeReferenceData run_root_ptr = 82;
  optional NodeReferenceData client_ptr = 83;
  optional NodeReferenceData machine_ptr = 84;
  optional NodeReferenceData server_ptr = 85;
  optional NodeReferenceData user_ptr = 86;
  optional NodeReferenceData identity_ptr = 87;
  RuntimeMode mode = 90;
}

message StreamData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  google.protobuf.Timestamp created_at = 10;
  optional NodeReferenceData created_by_ptr = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  optional NodeReferenceData updated_by_ptr = 14;
  int64 updated_epoch = 15;
  optional google.protobuf.Timestamp deleted_at = 16;
  optional google.protobuf.Value subnode_packed = 29;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  ResourceStatus current_status = 37;
  RuntimeMode mode = 90;
}

enum IdEnum {
  ID_ENUM_UNSPECIFIED = 0;
}

// A reference to a Node or Struct - usually both have an identity (except for inlined Structs).
enum ReferenceKind {
  REFERENCE_KIND_UNSPECIFIED = 0;
  REFERENCE_KIND_NODE_ANCESTOR = 1;
  REFERENCE_KIND_NODE_ANCESTOR_OR_SELF = 2;
  REFERENCE_KIND_NODE_PARENT = 3;
  REFERENCE_KIND_NODE_CHILDREN = 4;
  REFERENCE_KIND_NODE_REGULAR = 5;
  REFERENCE_KIND_NODE_TEMPLATE = 6;
  REFERENCE_KIND_STRUCT_PARENT = 10;
  REFERENCE_KIND_STRUCT_CHILD = 11;
  REFERENCE_KIND_PROPERTY = 20;
}

message SomeNodeData {
  oneof node {
    BenchData bench = 1;
    UserData user = 2;
    OrganizationData organization = 3;
    HandleData handle = 4;
    ClientData client = 5;
    ServerData server = 6;
    StoreData store = 7;
    DriveData drive = 8;
    VaultData vault = 9;
    CacheData cache = 10;
    MachineData machine = 11;
    BrowserData browser = 12;
    FileData file = 13;
    StreamData stream = 14;
    SecretData secret = 15;
    MembershipData membership = 16;
    InviteData invite = 17;
    BranchData branch = 18;
    PackageData package = 19;
    DependencyData dependency = 20;
    SpaceData space = 21;
    BlockData block = 22;
    TriggerData trigger = 23;
    FieldData field = 24;
    QueryData query = 25;
    ViewData view = 26;
    StepData step = 27;
    PipeData pipe = 28;
    BadgeData badge = 29;
    MessageData message = 30;
    RecordData record = 31;
    SessionData session = 32;
    RunData run = 33;
    InterruptData interrupt = 34;
    LogData log = 35;
    SkipData skip = 36;
  };
}

