syntax = "proto3";

package symbolx.bench;

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/struct.proto";

enum AccessKind {
  ACCESS_KIND_UNSPECIFIED = 0;
  ACCESS_KIND_READ = 1;
  ACCESS_KIND_EDIT = 20;
  ACCESS_KIND_USE = 40;
}

enum AccessMode {
  ACCESS_MODE_UNSPECIFIED = 0;
  ACCESS_MODE_ADAPTIVE = 1;
  ACCESS_MODE_ATOMIC = 2;
}

enum AccessType {
  ACCESS_TYPE_UNSPECIFIED = 0;
  ACCESS_TYPE_GET = 1;
  ACCESS_TYPE_SEARCH = 2;
  ACCESS_TYPE_AGGREGATE = 3;
  ACCESS_TYPE_CREATE = 20;
  ACCESS_TYPE_UPSERT = 21;
  ACCESS_TYPE_UPDATE = 22;
  ACCESS_TYPE_MOVE = 23;
  ACCESS_TYPE_ARCHIVE = 24;
  ACCESS_TYPE_UNARCHIVE = 25;
  ACCESS_TYPE_DELETE = 26;
  ACCESS_TYPE_RESTORE = 27;
  ACCESS_TYPE_ERASE = 28;
  ACCESS_TYPE_START = 40;
  ACCESS_TYPE_PAUSE = 41;
  ACCESS_TYPE_RESUME = 42;
  ACCESS_TYPE_STOP = 43;
  ACCESS_TYPE_KILL = 44;
  ACCESS_TYPE_SEND = 45;
  ACCESS_TYPE_RECEIVE = 46;
}

enum AggregationOp {
  AGGREGATION_OP_UNSPECIFIED = 0;
  AGGREGATION_OP_EXISTS = 400;
  AGGREGATION_OP_COUNT = 401;
  AGGREGATION_OP_SUM = 402;
  AGGREGATION_OP_MIN = 403;
  AGGREGATION_OP_MAX = 404;
  AGGREGATION_OP_AVERAGE = 405;
  AGGREGATION_OP_MEDIAN = 406;
  AGGREGATION_OP_HISTOGRAM = 407;
}

// How to align the contents/subviews of a view along its orientation.
enum Alignment {
  ALIGNMENT_UNSPECIFIED = 0;
  ALIGNMENT_START = 1;
  ALIGNMENT_MIDDLE = 2;
  ALIGNMENT_END = 3;
  ALIGNMENT_SPACE_BETWEEN = 4;
}

// An anchor in 2D space.
enum Anchor {
  ANCHOR_UNSPECIFIED = 0;
  ANCHOR_TOP = 1;
  ANCHOR_TOP_LEFT = 2;
  ANCHOR_TOP_RIGHT = 3;
  ANCHOR_RIGHT = 11;
  ANCHOR_RIGHT_TOP = 12;
  ANCHOR_RIGHT_BOTTOM = 13;
  ANCHOR_BOTTOM = 21;
  ANCHOR_BOTTOM_LEFT = 22;
  ANCHOR_BOTTOM_RIGHT = 23;
  ANCHOR_LEFT = 31;
  ANCHOR_LEFT_TOP = 32;
  ANCHOR_LEFT_BOTTOM = 33;
}

enum BenchType {
  BENCH_TYPE_UNSPECIFIED = 0;
  BENCH_TYPE_BENCH = 1;
  BENCH_TYPE_ENVIRONMENT = 2;
  BENCH_TYPE_BRANCH = 3;
  BENCH_TYPE_PACKAGE = 20;
  BENCH_TYPE_DEPENDENCY = 21;
  BENCH_TYPE_UPGRADE = 22;
  BENCH_TYPE_SPACE = 23;
  BENCH_TYPE_LINK = 24;
  BENCH_TYPE_SKIP = 25;
  BENCH_TYPE_ISSUE = 26;
  BENCH_TYPE_BLOCK = 30;
  BENCH_TYPE_TRIGGER = 31;
  BENCH_TYPE_FIELD = 32;
  BENCH_TYPE_QUERY = 33;
  BENCH_TYPE_VIEW = 34;
  BENCH_TYPE_STEP = 35;
  BENCH_TYPE_BADGE = 60;
  BENCH_TYPE_ROLE = 61;
  BENCH_TYPE_IDENTITY = 62;
  BENCH_TYPE_MEMBERSHIP = 63;
  BENCH_TYPE_INVITE = 64;
  BENCH_TYPE_SESSION = 80;
  BENCH_TYPE_RUN = 81;
  BENCH_TYPE_SIGNAL = 82;
  BENCH_TYPE_LOG = 83;
  BENCH_TYPE_NOTIFICATION = 84;
  BENCH_TYPE_MESSAGE = 85;
  BENCH_TYPE_RECORD = 86;
  BENCH_TYPE_SERVER = 160;
  BENCH_TYPE_STORE = 161;
  BENCH_TYPE_MACHINE = 162;
  BENCH_TYPE_DRIVE = 163;
  BENCH_TYPE_BLOB = 164;
  BENCH_TYPE_HANDLE = 220;
  BENCH_TYPE_USER = 221;
  BENCH_TYPE_ORGANIZATION = 222;
  BENCH_TYPE_CLIENT = 223;
  BENCH_TYPE_PATH = 1000;
  BENCH_TYPE_PATH_SEGMENT = 1001;
  BENCH_TYPE_PATH_TOKEN = 1002;
  BENCH_TYPE_NODE_REFERENCE = 1003;
  BENCH_TYPE_PROPERTY_REFERENCE = 1004;
  BENCH_TYPE_VALUE_REFERENCE = 1005;
  BENCH_TYPE_TYPE_INFO = 1010;
  BENCH_TYPE_TYPE_CONSTRAINT = 1011;
  BENCH_TYPE_CONTEXT = 1020;
  BENCH_TYPE_SESSION_CONTEXT = 1021;
  BENCH_TYPE_EDIT_CONTEXT = 1022;
  BENCH_TYPE_SCHEDULE = 1012;
  BENCH_TYPE_PROJECTION = 1013;
  BENCH_TYPE_POLICY = 1030;
  BENCH_TYPE_POLICY_RULE = 1031;
  BENCH_TYPE_SUBJECT = 1032;
  BENCH_TYPE_ACCESS_ZONE = 1034;
  BENCH_TYPE_ACCESS_MATRIX = 1035;
  BENCH_TYPE_ACCESS = 1037;
  BENCH_TYPE_READ_OPTIONS = 1050;
  BENCH_TYPE_EXPRESSION = 1060;
  BENCH_TYPE_AGGREGATION = 1061;
  BENCH_TYPE_SELECTION = 1070;
  BENCH_TYPE_CODE = 1090;
  BENCH_TYPE_CODE_LINE = 1091;
  BENCH_TYPE_STEP_CONNECTION = 1100;
  BENCH_TYPE_RUN_ERROR = 1110;
  BENCH_TYPE_RUN_OPTIONS = 1111;
  BENCH_TYPE_RETRY_ATTEMPT = 1113;
  BENCH_TYPE_TEXT = 1160;
  BENCH_TYPE_TEXT_LINE = 1161;
  BENCH_TYPE_TEXT_SPAN = 1162;
  BENCH_TYPE_COLOR = 1200;
  BENCH_TYPE_FONT = 1201;
  BENCH_TYPE_BOX = 1202;
  BENCH_TYPE_OFFSET = 1203;
  BENCH_TYPE_TRANSFORM = 1204;
  BENCH_TYPE_FILE = 1250;
  BENCH_TYPE_ICON = 1251;
  BENCH_TYPE_ENUM_TYPE = 2001;
  BENCH_TYPE_NODE_TYPE = 2002;
  BENCH_TYPE_STRUCT_TYPE = 2003;
  BENCH_TYPE_OBJECT_TYPE = 2004;
  BENCH_TYPE_BENCH_TYPE = 2005;
  BENCH_TYPE_VISIBILITY = 2010;
  BENCH_TYPE_ACCESS_MODE = 2030;
  BENCH_TYPE_ACCESS_KIND = 2033;
  BENCH_TYPE_READ_TYPE = 2034;
  BENCH_TYPE_EDIT_TYPE = 2035;
  BENCH_TYPE_USE_TYPE = 2036;
  BENCH_TYPE_ACCESS_TYPE = 2037;
  BENCH_TYPE_POLICY_EFFECT = 2040;
  BENCH_TYPE_REGION = 2050;
  BENCH_TYPE_TENANCY = 2051;
  BENCH_TYPE_SERVER_PROFILE = 2055;
  BENCH_TYPE_MACHINE_PROFILE = 2056;
  BENCH_TYPE_RESOURCE_STATUS = 2057;
  BENCH_TYPE_FILE_RETENTION_MODE = 2058;
  BENCH_TYPE_CLIENT_TYPE = 2060;
  BENCH_TYPE_BLOCK_TYPE = 2070;
  BENCH_TYPE_PRIMITIVE_TYPE = 2080;
  BENCH_TYPE_FORMAT_HINT = 2081;
  BENCH_TYPE_FIELD_ZONE = 2082;
  BENCH_TYPE_TYPE_KIND = 2083;
  BENCH_TYPE_TEXT_LINE_TYPE = 2090;
  BENCH_TYPE_SCHEDULE_TYPE = 2100;
  BENCH_TYPE_TIME_INTERVAL = 2101;
  BENCH_TYPE_DAY = 2102;
  BENCH_TYPE_MONTH = 2103;
  BENCH_TYPE_ISSUE_KIND = 2170;
  BENCH_TYPE_ISSUE_TYPE = 2171;
  BENCH_TYPE_STEP_TYPE = 2180;
  BENCH_TYPE_STEP_CONNECTION_TYPE = 2181;
  BENCH_TYPE_SPACE_TYPE = 2200;
  BENCH_TYPE_VIEW_TYPE = 2201;
  BENCH_TYPE_VARIANT = 2202;
  BENCH_TYPE_COLOR_TYPE = 2203;
  BENCH_TYPE_COLOR_SHADE = 2204;
  BENCH_TYPE_FONT_TYPE = 2205;
  BENCH_TYPE_FONT_WEIGHT = 2206;
  BENCH_TYPE_FONT_SIZE = 2207;
  BENCH_TYPE_SPACING = 2208;
  BENCH_TYPE_ANCHOR = 2209;
  BENCH_TYPE_ORIENTATION = 2210;
  BENCH_TYPE_ALIGNMENT = 2211;
  BENCH_TYPE_ICON_KIND = 2212;
  BENCH_TYPE_LOG_KIND = 2250;
  BENCH_TYPE_LOG_LEVEL = 2251;
  BENCH_TYPE_RUN_STATUS = 2260;
  BENCH_TYPE_RUN_KIND = 2261;
  BENCH_TYPE_RUN_ERROR_KIND = 2262;
  BENCH_TYPE_RUN_ERROR_TYPE = 2263;
  BENCH_TYPE_SESSION_STATUS = 2264;
  BENCH_TYPE_TRIGGER_TYPE = 2270;
  BENCH_TYPE_NOTIFICATION_KIND = 2281;
  BENCH_TYPE_EXPRESSION_KIND = 2300;
  BENCH_TYPE_EXPRESSION_OP = 2301;
  BENCH_TYPE_LITERAL_OP = 2302;
  BENCH_TYPE_FUNCTIONAL_OP = 2303;
  BENCH_TYPE_CONDITIONAL_OP = 2304;
  BENCH_TYPE_AGGREGATION_OP = 2305;
  BENCH_TYPE_SORT_MODE = 2306;
  BENCH_TYPE_SORT_OP = 2307;
  BENCH_TYPE_SELECTION_KIND = 2308;
  BENCH_TYPE_PATH_TOKEN_TYPE = 2320;
  BENCH_TYPE_PATH_SEGMENT_TYPE = 2321;
  BENCH_TYPE_USER_STATUS = 2500;
  BENCH_TYPE_ORGANIZATION_STATUS = 2501;
}

enum BlockType {
  BLOCK_TYPE_UNSPECIFIED = 0;
  BLOCK_TYPE_ALIAS = 1;
  BLOCK_TYPE_PAGE = 2;
  BLOCK_TYPE_MODULE = 3;
  BLOCK_TYPE_BLANK = 4;
  BLOCK_TYPE_CLASS = 10;
  BLOCK_TYPE_CHOICE = 11;
  BLOCK_TYPE_SIGNAL = 13;
  BLOCK_TYPE_PROTOCOL = 14;
  BLOCK_TYPE_TEXT = 30;
  BLOCK_TYPE_CODE = 31;
  BLOCK_TYPE_SCRIPT = 32;
  BLOCK_TYPE_FLOW = 33;
  BLOCK_TYPE_VARIABLE = 50;
  BLOCK_TYPE_QUERY = 52;
  BLOCK_TYPE_DATABASE = 53;
  BLOCK_TYPE_SCREEN = 70;
  BLOCK_TYPE_ROLE = 90;
  BLOCK_TYPE_IDENTITY = 91;
}

enum ClientType {
  CLIENT_TYPE_UNSPECIFIED = 0;
  CLIENT_TYPE_BENCH_WEB = 1;
  CLIENT_TYPE_BENCH_BROWSER_PLUGIN = 2;
  CLIENT_TYPE_BENCH_DESKTOP = 3;
  CLIENT_TYPE_BENCH_MOBILE = 4;
  CLIENT_TYPE_BENCH_SERVER = 10;
}

// Built-in color shades a la Tailwind.
enum ColorShade {
  COLOR_SHADE_UNSPECIFIED = 0;
  COLOR_SHADE_S50 = 50;
  COLOR_SHADE_S100 = 100;
  COLOR_SHADE_S200 = 200;
  COLOR_SHADE_S300 = 300;
  COLOR_SHADE_S400 = 400;
  COLOR_SHADE_S500 = 500;
  COLOR_SHADE_S600 = 600;
  COLOR_SHADE_S700 = 700;
  COLOR_SHADE_S800 = 800;
  COLOR_SHADE_S900 = 900;
  COLOR_SHADE_S950 = 950;
}

// Built-in color types a la SwiftUI or Tailwind.
enum ColorType {
  COLOR_TYPE_UNSPECIFIED = 0;
  COLOR_TYPE_PRIMARY = 1;
  COLOR_TYPE_SECONDARY = 2;
  COLOR_TYPE_ACCENT = 3;
  COLOR_TYPE_CANVAS = 4;
  COLOR_TYPE_SUCCESS = 10;
  COLOR_TYPE_HINT = 11;
  COLOR_TYPE_WARNING = 12;
  COLOR_TYPE_DANGER = 13;
  COLOR_TYPE_GRAY = 30;
  COLOR_TYPE_RED = 31;
  COLOR_TYPE_ORANGE = 32;
  COLOR_TYPE_AMBER = 33;
  COLOR_TYPE_YELLOW = 34;
  COLOR_TYPE_LIME = 35;
  COLOR_TYPE_GREEN = 36;
  COLOR_TYPE_EMERALD = 37;
  COLOR_TYPE_TEAL = 38;
  COLOR_TYPE_CYAN = 39;
  COLOR_TYPE_SKY = 40;
  COLOR_TYPE_BLUE = 41;
  COLOR_TYPE_INDIGO = 42;
  COLOR_TYPE_VIOLET = 43;
  COLOR_TYPE_PURPLE = 44;
  COLOR_TYPE_FUCHSIA = 45;
  COLOR_TYPE_PINK = 46;
  COLOR_TYPE_ROSE = 47;
}

enum ConditionalOp {
  CONDITIONAL_OP_UNSPECIFIED = 0;
  CONDITIONAL_OP_NOT = 301;
  CONDITIONAL_OP_AND = 302;
  CONDITIONAL_OP_OR = 303;
  CONDITIONAL_OP_EQUALS = 310;
  CONDITIONAL_OP_NOT_EQUALS = 311;
  CONDITIONAL_OP_GREATER_THAN = 312;
  CONDITIONAL_OP_GREATER_THAN_OR_EQUALS = 313;
  CONDITIONAL_OP_LESS_THAN = 314;
  CONDITIONAL_OP_LESS_THAN_OR_EQUALS = 315;
  CONDITIONAL_OP_MATCHES_REGEX = 320;
  CONDITIONAL_OP_STARTS_WITH = 321;
  CONDITIONAL_OP_ENDS_WITH = 322;
  CONDITIONAL_OP_CONTAINS = 330;
  CONDITIONAL_OP_NOT_CONTAINS = 331;
  CONDITIONAL_OP_IN = 332;
  CONDITIONAL_OP_NOT_IN = 333;
  CONDITIONAL_OP_EXISTS = 340;
  CONDITIONAL_OP_NOT_EXISTS = 341;
  CONDITIONAL_OP_NEAR = 350;
}

enum Day {
  DAY_UNSPECIFIED = 0;
  DAY_MONDAY = 1;
  DAY_TUESDAY = 2;
  DAY_WEDNESDAY = 3;
  DAY_THURSDAY = 4;
  DAY_FRIDAY = 5;
  DAY_SATURDAY = 6;
  DAY_SUNDAY = 7;
}

// Ways to edit nodes.
enum EditType {
  EDIT_TYPE_UNSPECIFIED = 0;
  EDIT_TYPE_CREATE = 20;
  EDIT_TYPE_UPSERT = 21;
  EDIT_TYPE_UPDATE = 22;
  EDIT_TYPE_MOVE = 23;
  EDIT_TYPE_ARCHIVE = 24;
  EDIT_TYPE_UNARCHIVE = 25;
  EDIT_TYPE_DELETE = 26;
  EDIT_TYPE_RESTORE = 27;
  EDIT_TYPE_ERASE = 28;
}

enum EnumType {
  ENUM_TYPE_UNSPECIFIED = 0;
  ENUM_TYPE_ENUM_TYPE = 2001;
  ENUM_TYPE_NODE_TYPE = 2002;
  ENUM_TYPE_STRUCT_TYPE = 2003;
  ENUM_TYPE_OBJECT_TYPE = 2004;
  ENUM_TYPE_BENCH_TYPE = 2005;
  ENUM_TYPE_VISIBILITY = 2010;
  ENUM_TYPE_ACCESS_MODE = 2030;
  ENUM_TYPE_ACCESS_KIND = 2033;
  ENUM_TYPE_READ_TYPE = 2034;
  ENUM_TYPE_EDIT_TYPE = 2035;
  ENUM_TYPE_USE_TYPE = 2036;
  ENUM_TYPE_ACCESS_TYPE = 2037;
  ENUM_TYPE_POLICY_EFFECT = 2040;
  ENUM_TYPE_REGION = 2050;
  ENUM_TYPE_TENANCY = 2051;
  ENUM_TYPE_SERVER_PROFILE = 2055;
  ENUM_TYPE_MACHINE_PROFILE = 2056;
  ENUM_TYPE_RESOURCE_STATUS = 2057;
  ENUM_TYPE_FILE_RETENTION_MODE = 2058;
  ENUM_TYPE_CLIENT_TYPE = 2060;
  ENUM_TYPE_BLOCK_TYPE = 2070;
  ENUM_TYPE_PRIMITIVE_TYPE = 2080;
  ENUM_TYPE_FORMAT_HINT = 2081;
  ENUM_TYPE_FIELD_ZONE = 2082;
  ENUM_TYPE_TYPE_KIND = 2083;
  ENUM_TYPE_TEXT_LINE_TYPE = 2090;
  ENUM_TYPE_SCHEDULE_TYPE = 2100;
  ENUM_TYPE_TIME_INTERVAL = 2101;
  ENUM_TYPE_DAY = 2102;
  ENUM_TYPE_MONTH = 2103;
  ENUM_TYPE_ISSUE_KIND = 2170;
  ENUM_TYPE_ISSUE_TYPE = 2171;
  ENUM_TYPE_STEP_TYPE = 2180;
  ENUM_TYPE_STEP_CONNECTION_TYPE = 2181;
  ENUM_TYPE_SPACE_TYPE = 2200;
  ENUM_TYPE_VIEW_TYPE = 2201;
  ENUM_TYPE_VARIANT = 2202;
  ENUM_TYPE_COLOR_TYPE = 2203;
  ENUM_TYPE_COLOR_SHADE = 2204;
  ENUM_TYPE_FONT_TYPE = 2205;
  ENUM_TYPE_FONT_WEIGHT = 2206;
  ENUM_TYPE_FONT_SIZE = 2207;
  ENUM_TYPE_SPACING = 2208;
  ENUM_TYPE_ANCHOR = 2209;
  ENUM_TYPE_ORIENTATION = 2210;
  ENUM_TYPE_ALIGNMENT = 2211;
  ENUM_TYPE_ICON_KIND = 2212;
  ENUM_TYPE_LOG_KIND = 2250;
  ENUM_TYPE_LOG_LEVEL = 2251;
  ENUM_TYPE_RUN_STATUS = 2260;
  ENUM_TYPE_RUN_KIND = 2261;
  ENUM_TYPE_RUN_ERROR_KIND = 2262;
  ENUM_TYPE_RUN_ERROR_TYPE = 2263;
  ENUM_TYPE_SESSION_STATUS = 2264;
  ENUM_TYPE_TRIGGER_TYPE = 2270;
  ENUM_TYPE_NOTIFICATION_KIND = 2281;
  ENUM_TYPE_EXPRESSION_KIND = 2300;
  ENUM_TYPE_EXPRESSION_OP = 2301;
  ENUM_TYPE_LITERAL_OP = 2302;
  ENUM_TYPE_FUNCTIONAL_OP = 2303;
  ENUM_TYPE_CONDITIONAL_OP = 2304;
  ENUM_TYPE_AGGREGATION_OP = 2305;
  ENUM_TYPE_SORT_MODE = 2306;
  ENUM_TYPE_SORT_OP = 2307;
  ENUM_TYPE_SELECTION_KIND = 2308;
  ENUM_TYPE_PATH_TOKEN_TYPE = 2320;
  ENUM_TYPE_PATH_SEGMENT_TYPE = 2321;
  ENUM_TYPE_USER_STATUS = 2500;
  ENUM_TYPE_ORGANIZATION_STATUS = 2501;
}

enum ExpressionKind {
  EXPRESSION_KIND_UNSPECIFIED = 0;
  EXPRESSION_KIND_LITERAL = 1;
  EXPRESSION_KIND_FUNCTIONAL = 2;
  EXPRESSION_KIND_CONDITIONAL = 3;
  EXPRESSION_KIND_SORT = 4;
  EXPRESSION_KIND_AGGREGATION = 5;
}

enum ExpressionOp {
  EXPRESSION_OP_UNSPECIFIED = 0;
  EXPRESSION_OP_VALUE = 100;
  EXPRESSION_OP_NONE = 101;
  EXPRESSION_OP_TRUE = 102;
  EXPRESSION_OP_FALSE = 103;
  EXPRESSION_OP_ADD = 200;
  EXPRESSION_OP_SUBTRACT = 201;
  EXPRESSION_OP_MULTIPLY = 202;
  EXPRESSION_OP_DIVIDE = 203;
  EXPRESSION_OP_MODULO = 204;
  EXPRESSION_OP_POWER = 205;
  EXPRESSION_OP_NOT = 301;
  EXPRESSION_OP_AND = 302;
  EXPRESSION_OP_OR = 303;
  EXPRESSION_OP_EQUALS = 310;
  EXPRESSION_OP_NOT_EQUALS = 311;
  EXPRESSION_OP_GREATER_THAN = 312;
  EXPRESSION_OP_GREATER_THAN_OR_EQUALS = 313;
  EXPRESSION_OP_LESS_THAN = 314;
  EXPRESSION_OP_LESS_THAN_OR_EQUALS = 315;
  EXPRESSION_OP_MATCHES_REGEX = 320;
  EXPRESSION_OP_STARTS_WITH = 321;
  EXPRESSION_OP_ENDS_WITH = 322;
  EXPRESSION_OP_CONTAINS = 330;
  EXPRESSION_OP_NOT_CONTAINS = 331;
  EXPRESSION_OP_IN = 332;
  EXPRESSION_OP_NOT_IN = 333;
  EXPRESSION_OP_EXISTS = 400;
  EXPRESSION_OP_NOT_EXISTS = 341;
  EXPRESSION_OP_NEAR = 350;
  EXPRESSION_OP_COUNT = 401;
  EXPRESSION_OP_SUM = 402;
  EXPRESSION_OP_MIN = 403;
  EXPRESSION_OP_MAX = 404;
  EXPRESSION_OP_AVERAGE = 405;
  EXPRESSION_OP_MEDIAN = 406;
  EXPRESSION_OP_HISTOGRAM = 407;
  EXPRESSION_OP_ASCENDING = 500;
  EXPRESSION_OP_DESCENDING = 501;
}

// The 'zone' of a Field within its Block.
enum FieldZone {
  FIELD_ZONE_UNSPECIFIED = 0;
  FIELD_ZONE_VARIABLE = 1;
  FIELD_ZONE_MEMBER = 2;
  FIELD_ZONE_INPUT = 3;
  FIELD_ZONE_OUTPUT = 4;
  FIELD_ZONE_OPTION = 5;
}

enum FileRetentionMode {
  FILE_RETENTION_MODE_UNSPECIFIED = 0;
  FILE_RETENTION_MODE_AUTOMATIC = 1;
  FILE_RETENTION_MODE_MANUAL = 2;
  FILE_RETENTION_MODE_TIMED = 3;
}

enum FontSize {
  FONT_SIZE_UNSPECIFIED = 0;
  FONT_SIZE_XS = 12;
  FONT_SIZE_SM = 14;
  FONT_SIZE_BASE = 16;
  FONT_SIZE_LG = 18;
  FONT_SIZE_XL = 20;
  FONT_SIZE_XL2 = 24;
  FONT_SIZE_XL3 = 30;
  FONT_SIZE_XL4 = 36;
  FONT_SIZE_XL5 = 48;
  FONT_SIZE_XL6 = 60;
  FONT_SIZE_XL7 = 72;
}

enum FontType {
  FONT_TYPE_UNSPECIFIED = 0;
  FONT_TYPE_SERIF = 1;
  FONT_TYPE_SANS = 2;
  FONT_TYPE_MONO = 3;
}

enum FontWeight {
  FONT_WEIGHT_UNSPECIFIED = 0;
  FONT_WEIGHT_THIN = 100;
  FONT_WEIGHT_EXTRA_LIGHT = 200;
  FONT_WEIGHT_LIGHT = 300;
  FONT_WEIGHT_NORMAL = 400;
  FONT_WEIGHT_MEDIUM = 500;
  FONT_WEIGHT_SEMI_BOLD = 600;
  FONT_WEIGHT_BOLD = 700;
  FONT_WEIGHT_EXTRA_BOLD = 800;
  FONT_WEIGHT_BLACK = 900;
}

// Extra semantic hint for types.
enum FormatHint {
  FORMAT_HINT_UNSPECIFIED = 0;
  FORMAT_HINT_TITLE = 1;
  FORMAT_HINT_EMAIL = 2;
  FORMAT_HINT_URL = 3;
  FORMAT_HINT_MARKDOWN = 4;
  FORMAT_HINT_CODE = 5;
  FORMAT_HINT_EMOJI = 6;
  FORMAT_HINT_PHONE = 20;
  FORMAT_HINT_RATING = 21;
  FORMAT_HINT_SLIDER = 22;
  FORMAT_HINT_IMAGE = 60;
  FORMAT_HINT_VIDEO = 61;
  FORMAT_HINT_AUDIO = 62;
}

enum FunctionalOp {
  FUNCTIONAL_OP_UNSPECIFIED = 0;
  FUNCTIONAL_OP_ADD = 200;
  FUNCTIONAL_OP_SUBTRACT = 201;
  FUNCTIONAL_OP_MULTIPLY = 202;
  FUNCTIONAL_OP_DIVIDE = 203;
  FUNCTIONAL_OP_MODULO = 204;
  FUNCTIONAL_OP_POWER = 205;
}

enum IconKind {
  ICON_KIND_UNSPECIFIED = 0;
  ICON_KIND_EMOJI = 1;
  ICON_KIND_FILE = 2;
  ICON_KIND_FONT_AWESOME = 3;
}

enum IdEnum {
  ID_ENUM_UNSPECIFIED = 0;
}

// Type of diagnostic in increasing severity.
enum IssueKind {
  ISSUE_KIND_UNSPECIFIED = 0;
  ISSUE_KIND_HINT = 1;
  ISSUE_KIND_INFO = 2;
  ISSUE_KIND_WARNING = 3;
  ISSUE_KIND_ERROR = 4;
}

// Built-in issue types.
enum IssueType {
  ISSUE_TYPE_UNSPECIFIED = 0;
  ISSUE_TYPE_MISSING_REFERENCE = 1;
  ISSUE_TYPE_CIRCULAR_BASE = 2;
  ISSUE_TYPE_MISMATCHED_BASE = 3;
  ISSUE_TYPE_AMBIGUOUS_NAME = 100;
}

enum LiteralOp {
  LITERAL_OP_UNSPECIFIED = 0;
  LITERAL_OP_VALUE = 100;
  LITERAL_OP_NONE = 101;
  LITERAL_OP_TRUE = 102;
  LITERAL_OP_FALSE = 103;
}

enum LogKind {
  LOG_KIND_UNSPECIFIED = 0;
  LOG_KIND_READ = 1;
  LOG_KIND_EDIT = 2;
  LOG_KIND_USE = 3;
  LOG_KIND_CUSTOM = 10;
}

enum LogLevel {
  LOG_LEVEL_UNSPECIFIED = 0;
  LOG_LEVEL_TRACE = 1;
  LOG_LEVEL_DEBUG = 2;
  LOG_LEVEL_INFO = 3;
  LOG_LEVEL_WARNING = 4;
  LOG_LEVEL_ERROR = 5;
  LOG_LEVEL_CRITICAL = 6;
}

enum MachineProfile {
  MACHINE_PROFILE_UNSPECIFIED = 0;
  MACHINE_PROFILE_TINY = 3;
  MACHINE_PROFILE_SMALL = 5;
  MACHINE_PROFILE_MEDIUM = 7;
}

enum Month {
  MONTH_UNSPECIFIED = 0;
  MONTH_JANUARY = 1;
  MONTH_FEBRUARY = 2;
  MONTH_MARCH = 3;
  MONTH_APRIL = 4;
  MONTH_MAY = 5;
  MONTH_JUNE = 6;
  MONTH_JULY = 7;
  MONTH_AUGUST = 8;
  MONTH_SEPTEMBER = 9;
  MONTH_OCTOBER = 10;
  MONTH_NOVEMBER = 11;
  MONTH_DECEMBER = 12;
}

enum NodeType {
  NODE_TYPE_UNSPECIFIED = 0;
  NODE_TYPE_BENCH = 1;
  NODE_TYPE_ENVIRONMENT = 2;
  NODE_TYPE_BRANCH = 3;
  NODE_TYPE_PACKAGE = 20;
  NODE_TYPE_DEPENDENCY = 21;
  NODE_TYPE_UPGRADE = 22;
  NODE_TYPE_SPACE = 23;
  NODE_TYPE_LINK = 24;
  NODE_TYPE_SKIP = 25;
  NODE_TYPE_ISSUE = 26;
  NODE_TYPE_BLOCK = 30;
  NODE_TYPE_TRIGGER = 31;
  NODE_TYPE_FIELD = 32;
  NODE_TYPE_QUERY = 33;
  NODE_TYPE_VIEW = 34;
  NODE_TYPE_STEP = 35;
  NODE_TYPE_BADGE = 60;
  NODE_TYPE_ROLE = 61;
  NODE_TYPE_IDENTITY = 62;
  NODE_TYPE_MEMBERSHIP = 63;
  NODE_TYPE_INVITE = 64;
  NODE_TYPE_SESSION = 80;
  NODE_TYPE_RUN = 81;
  NODE_TYPE_SIGNAL = 82;
  NODE_TYPE_LOG = 83;
  NODE_TYPE_NOTIFICATION = 84;
  NODE_TYPE_MESSAGE = 85;
  NODE_TYPE_RECORD = 86;
  NODE_TYPE_SERVER = 160;
  NODE_TYPE_STORE = 161;
  NODE_TYPE_MACHINE = 162;
  NODE_TYPE_DRIVE = 163;
  NODE_TYPE_BLOB = 164;
  NODE_TYPE_HANDLE = 220;
  NODE_TYPE_USER = 221;
  NODE_TYPE_ORGANIZATION = 222;
  NODE_TYPE_CLIENT = 223;
}

// The level of interaction required for a notification.
enum NotificationKind {
  NOTIFICATION_KIND_UNSPECIFIED = 0;
  NOTIFICATION_KIND_PASSIVE = 1;
  NOTIFICATION_KIND_ACTIVE = 2;
  NOTIFICATION_KIND_URGENT = 3;
}

enum ObjectType {
  OBJECT_TYPE_UNSPECIFIED = 0;
  OBJECT_TYPE_BENCH = 1;
  OBJECT_TYPE_ENVIRONMENT = 2;
  OBJECT_TYPE_BRANCH = 3;
  OBJECT_TYPE_PACKAGE = 20;
  OBJECT_TYPE_DEPENDENCY = 21;
  OBJECT_TYPE_UPGRADE = 22;
  OBJECT_TYPE_SPACE = 23;
  OBJECT_TYPE_LINK = 24;
  OBJECT_TYPE_SKIP = 25;
  OBJECT_TYPE_ISSUE = 26;
  OBJECT_TYPE_BLOCK = 30;
  OBJECT_TYPE_TRIGGER = 31;
  OBJECT_TYPE_FIELD = 32;
  OBJECT_TYPE_QUERY = 33;
  OBJECT_TYPE_VIEW = 34;
  OBJECT_TYPE_STEP = 35;
  OBJECT_TYPE_BADGE = 60;
  OBJECT_TYPE_ROLE = 61;
  OBJECT_TYPE_IDENTITY = 62;
  OBJECT_TYPE_MEMBERSHIP = 63;
  OBJECT_TYPE_INVITE = 64;
  OBJECT_TYPE_SESSION = 80;
  OBJECT_TYPE_RUN = 81;
  OBJECT_TYPE_SIGNAL = 82;
  OBJECT_TYPE_LOG = 83;
  OBJECT_TYPE_NOTIFICATION = 84;
  OBJECT_TYPE_MESSAGE = 85;
  OBJECT_TYPE_RECORD = 86;
  OBJECT_TYPE_SERVER = 160;
  OBJECT_TYPE_STORE = 161;
  OBJECT_TYPE_MACHINE = 162;
  OBJECT_TYPE_DRIVE = 163;
  OBJECT_TYPE_BLOB = 164;
  OBJECT_TYPE_HANDLE = 220;
  OBJECT_TYPE_USER = 221;
  OBJECT_TYPE_ORGANIZATION = 222;
  OBJECT_TYPE_CLIENT = 223;
  OBJECT_TYPE_PATH = 1000;
  OBJECT_TYPE_PATH_SEGMENT = 1001;
  OBJECT_TYPE_PATH_TOKEN = 1002;
  OBJECT_TYPE_NODE_REFERENCE = 1003;
  OBJECT_TYPE_PROPERTY_REFERENCE = 1004;
  OBJECT_TYPE_VALUE_REFERENCE = 1005;
  OBJECT_TYPE_TYPE_INFO = 1010;
  OBJECT_TYPE_TYPE_CONSTRAINT = 1011;
  OBJECT_TYPE_CONTEXT = 1020;
  OBJECT_TYPE_SESSION_CONTEXT = 1021;
  OBJECT_TYPE_EDIT_CONTEXT = 1022;
  OBJECT_TYPE_SCHEDULE = 1012;
  OBJECT_TYPE_PROJECTION = 1013;
  OBJECT_TYPE_POLICY = 1030;
  OBJECT_TYPE_POLICY_RULE = 1031;
  OBJECT_TYPE_SUBJECT = 1032;
  OBJECT_TYPE_ACCESS_ZONE = 1034;
  OBJECT_TYPE_ACCESS_MATRIX = 1035;
  OBJECT_TYPE_ACCESS = 1037;
  OBJECT_TYPE_READ_OPTIONS = 1050;
  OBJECT_TYPE_EXPRESSION = 1060;
  OBJECT_TYPE_AGGREGATION = 1061;
  OBJECT_TYPE_SELECTION = 1070;
  OBJECT_TYPE_CODE = 1090;
  OBJECT_TYPE_CODE_LINE = 1091;
  OBJECT_TYPE_STEP_CONNECTION = 1100;
  OBJECT_TYPE_RUN_ERROR = 1110;
  OBJECT_TYPE_RUN_OPTIONS = 1111;
  OBJECT_TYPE_RETRY_ATTEMPT = 1113;
  OBJECT_TYPE_TEXT = 1160;
  OBJECT_TYPE_TEXT_LINE = 1161;
  OBJECT_TYPE_TEXT_SPAN = 1162;
  OBJECT_TYPE_COLOR = 1200;
  OBJECT_TYPE_FONT = 1201;
  OBJECT_TYPE_BOX = 1202;
  OBJECT_TYPE_OFFSET = 1203;
  OBJECT_TYPE_TRANSFORM = 1204;
  OBJECT_TYPE_FILE = 1250;
  OBJECT_TYPE_ICON = 1251;
}

enum OrganizationStatus {
  ORGANIZATION_STATUS_UNSPECIFIED = 0;
  ORGANIZATION_STATUS_REGISTERED = 4;
  ORGANIZATION_STATUS_ACTIVATED = 10;
}

// Which way to orient the contents/subviews of a view.
enum Orientation {
  ORIENTATION_UNSPECIFIED = 0;
  ORIENTATION_HORIZONTAL = 1;
  ORIENTATION_VERTICAL = 11;
}

enum PathSegmentType {
  PATH_SEGMENT_TYPE_UNSPECIFIED = 0;
  PATH_SEGMENT_TYPE_BENCH = 1;
  PATH_SEGMENT_TYPE_ENVIRONMENT = 2;
  PATH_SEGMENT_TYPE_BRANCH = 3;
  PATH_SEGMENT_TYPE_PACKAGE = 4;
  PATH_SEGMENT_TYPE_BLOCK = 5;
  PATH_SEGMENT_TYPE_SUB_BLOCK = 6;
  PATH_SEGMENT_TYPE_PROPERTY = 7;
  PATH_SEGMENT_TYPE_CURRENT = 10;
  PATH_SEGMENT_TYPE_CURRENT_PARENT = 11;
  PATH_SEGMENT_TYPE_CURRENT_PACKAGE = 12;
  PATH_SEGMENT_TYPE_CURRENT_MODULE = 13;
  PATH_SEGMENT_TYPE_CURRENT_PAGE = 14;
  PATH_SEGMENT_TYPE_CURRENT_SOURCE_MODULE = 15;
  PATH_SEGMENT_TYPE_CURRENT_UNIQUE = 16;
  PATH_SEGMENT_TYPE_FILTER = 20;
}

enum PathTokenType {
  PATH_TOKEN_TYPE_UNSPECIFIED = 0;
  PATH_TOKEN_TYPE_SLASH = 1;
  PATH_TOKEN_TYPE_COLON = 2;
  PATH_TOKEN_TYPE_DOT = 3;
  PATH_TOKEN_TYPE_AT = 4;
  PATH_TOKEN_TYPE_DOLLAR = 5;
  PATH_TOKEN_TYPE_CARET = 6;
  PATH_TOKEN_TYPE_TILDE = 7;
  PATH_TOKEN_TYPE_DOUBLE_DOT = 8;
  PATH_TOKEN_TYPE_NAME = 10;
  PATH_TOKEN_TYPE_EXPRESSION = 11;
}

enum PolicyEffect {
  POLICY_EFFECT_UNSPECIFIED = 0;
  POLICY_EFFECT_ALLOW = 1;
  POLICY_EFFECT_DENY = 2;
}

// Fundamental column / storage types we support (subset of SQL types, used directly in sql/core).
// NOTE: the ids here are used in type identity keys, so any change is breaking.
enum PrimitiveType {
  PRIMITIVE_TYPE_UNSPECIFIED = 0;
  PRIMITIVE_TYPE_BOOLEAN = 1;
  PRIMITIVE_TYPE_INT16 = 5;
  PRIMITIVE_TYPE_INT32 = 6;
  PRIMITIVE_TYPE_INT64 = 7;
  PRIMITIVE_TYPE_DECIMAL = 9;
  PRIMITIVE_TYPE_FLOAT32 = 12;
  PRIMITIVE_TYPE_FLOAT64 = 13;
  PRIMITIVE_TYPE_STRING = 20;
  PRIMITIVE_TYPE_UUID = 21;
  PRIMITIVE_TYPE_JSON = 22;
  PRIMITIVE_TYPE_BYTES = 25;
  PRIMITIVE_TYPE_VECTOR = 26;
  PRIMITIVE_TYPE_DATETIME = 30;
  PRIMITIVE_TYPE_INTERVAL = 31;
}

// Ways to read nodes.
enum ReadType {
  READ_TYPE_UNSPECIFIED = 0;
  READ_TYPE_GET = 1;
  READ_TYPE_SEARCH = 2;
  READ_TYPE_AGGREGATE = 3;
}

// A reference to a Node or Struct - usually both have an identity (except for inlined Structs).
enum ReferenceKind {
  REFERENCE_KIND_UNSPECIFIED = 0;
  REFERENCE_KIND_NODE_ANCESTOR_ROOT = 1;
  REFERENCE_KIND_NODE_ANCESTOR_FIRST = 2;
  REFERENCE_KIND_NODE_PARENT = 3;
  REFERENCE_KIND_NODE_CHILDREN = 4;
  REFERENCE_KIND_NODE_REGULAR = 5;
  REFERENCE_KIND_NODE_TEMPLATE = 6;
  REFERENCE_KIND_STRUCT_PARENT = 10;
  REFERENCE_KIND_STRUCT_CHILD = 11;
  REFERENCE_KIND_PROPERTY = 20;
}

// Where a Resource is located (physically).
// There are
// - 'continental' regions ([>1, <100]: Europe, North America, etc.).
// - 'area' regions ([%20=0]: Europe Central, US East, etc.).
// - 'city' regions (Frankfurt, Ohio, etc.).
enum Region {
  REGION_UNSPECIFIED = 0;
  REGION_GLOBAL = 1;
  REGION_EUROPE = 2;
  REGION_EUROPE_CENTRAL = 100;
  REGION_EUROPE_ZURICH = 101;
  REGION_EUROPE_FRANKFURT = 102;
}

// Generalized status of a Resource in its lifecycle.
enum ResourceStatus {
  RESOURCE_STATUS_UNSPECIFIED = 0;
  RESOURCE_STATUS_DECLARED = 1;
  RESOURCE_STATUS_PROVISIONING = 5;
  RESOURCE_STATUS_HEALTHY = 10;
  RESOURCE_STATUS_UNHEALTHY = 15;
  RESOURCE_STATUS_SLEEPING = 20;
  RESOURCE_STATUS_DECOMMISSIONED = 30;
}

enum RunErrorKind {
  RUN_ERROR_KIND_UNSPECIFIED = 0;
  RUN_ERROR_KIND_INTERNAL = 1;
  RUN_ERROR_KIND_RUNTIME = 5;
}

enum RunErrorType {
  RUN_ERROR_TYPE_UNSPECIFIED = 0;
  RUN_ERROR_TYPE_NO_RUNTIME_AVAILABLE = 1;
}

enum RunKind {
  RUN_KIND_UNSPECIFIED = 0;
  RUN_KIND_BLOCK = 1;
  RUN_KIND_STEP = 2;
  RUN_KIND_LAMBDA = 10;
}

enum RunStatus {
  RUN_STATUS_UNSPECIFIED = 0;
  RUN_STATUS_SCHEDULED = 1;
  RUN_STATUS_QUEUED = 2;
  RUN_STATUS_RUNNING = 3;
  RUN_STATUS_PAUSED = 4;
  RUN_STATUS_SUSPENDED = 5;
  RUN_STATUS_CANCELLED = 6;
  RUN_STATUS_ABORTED = 7;
  RUN_STATUS_FAILED = 8;
  RUN_STATUS_COMPLETED = 9;
}

enum ScheduleType {
  SCHEDULE_TYPE_UNSPECIFIED = 0;
  SCHEDULE_TYPE_INTERVAL = 1;
  SCHEDULE_TYPE_CRON = 2;
}

enum SelectionKind {
  SELECTION_KIND_UNSPECIFIED = 0;
  SELECTION_KIND_RANGE = 1;
  SELECTION_KIND_LIST = 2;
}

enum ServerProfile {
  SERVER_PROFILE_UNSPECIFIED = 0;
  SERVER_PROFILE_TINY = 3;
  SERVER_PROFILE_SMALL = 5;
  SERVER_PROFILE_MEDIUM = 7;
}

enum SessionStatus {
  SESSION_STATUS_UNSPECIFIED = 0;
  SESSION_STATUS_PENDING = 1;
  SESSION_STATUS_OPEN = 3;
  SESSION_STATUS_CLOSED = 6;
}

enum SortMode {
  SORT_MODE_UNSPECIFIED = 0;
  SORT_MODE_MAX = 1;
  SORT_MODE_MIN = 2;
  SORT_MODE_AVERAGE = 3;
  SORT_MODE_SUM = 4;
  SORT_MODE_MEDIAN = 5;
}

enum SortOp {
  SORT_OP_UNSPECIFIED = 0;
  SORT_OP_ASCENDING = 500;
  SORT_OP_DESCENDING = 501;
}

enum SpaceType {
  SPACE_TYPE_UNSPECIFIED = 0;
  SPACE_TYPE_DESKTOP = 10;
  SPACE_TYPE_MOBILE = 20;
  SPACE_TYPE_EXTENSION = 30;
}

// The spacing scale for positions, padding, margin, etc. We don't enforce this.
enum Spacing {
  SPACING_UNSPECIFIED = 0;
  SPACING_S1 = 1;
  SPACING_S2 = 2;
  SPACING_S3 = 3;
  SPACING_S4 = 4;
  SPACING_S6 = 6;
  SPACING_S8 = 8;
  SPACING_S10 = 10;
  SPACING_S12 = 12;
  SPACING_S14 = 14;
  SPACING_S16 = 16;
  SPACING_S20 = 20;
  SPACING_S24 = 24;
  SPACING_S28 = 28;
  SPACING_S32 = 32;
  SPACING_S36 = 36;
  SPACING_S40 = 40;
  SPACING_S44 = 44;
  SPACING_S48 = 48;
  SPACING_S52 = 52;
  SPACING_S56 = 56;
  SPACING_S60 = 60;
  SPACING_S64 = 64;
  SPACING_S72 = 72;
  SPACING_S80 = 80;
  SPACING_S96 = 96;
  SPACING_S128 = 128;
  SPACING_S160 = 160;
  SPACING_S192 = 192;
  SPACING_S224 = 224;
  SPACING_S256 = 256;
}

enum StepConnectionType {
  STEP_CONNECTION_TYPE_UNSPECIFIED = 0;
  STEP_CONNECTION_TYPE_THEN = 1;
}

enum StepType {
  STEP_TYPE_UNSPECIFIED = 0;
  STEP_TYPE_START = 1;
  STEP_TYPE_VALUE = 2;
  STEP_TYPE_TRIGGER = 10;
  STEP_TYPE_RUN = 20;
  STEP_TYPE_RUN_DEFERRED = 21;
  STEP_TYPE_SEND = 22;
  STEP_TYPE_COMPLETE = 23;
  STEP_TYPE_BRANCH = 30;
  STEP_TYPE_FILTER = 31;
  STEP_TYPE_LOOP = 32;
  STEP_TYPE_GROUP = 50;
}

enum StructType {
  STRUCT_TYPE_UNSPECIFIED = 0;
  STRUCT_TYPE_PATH = 1000;
  STRUCT_TYPE_PATH_SEGMENT = 1001;
  STRUCT_TYPE_PATH_TOKEN = 1002;
  STRUCT_TYPE_NODE_REFERENCE = 1003;
  STRUCT_TYPE_PROPERTY_REFERENCE = 1004;
  STRUCT_TYPE_VALUE_REFERENCE = 1005;
  STRUCT_TYPE_TYPE_INFO = 1010;
  STRUCT_TYPE_TYPE_CONSTRAINT = 1011;
  STRUCT_TYPE_CONTEXT = 1020;
  STRUCT_TYPE_SESSION_CONTEXT = 1021;
  STRUCT_TYPE_EDIT_CONTEXT = 1022;
  STRUCT_TYPE_SCHEDULE = 1012;
  STRUCT_TYPE_PROJECTION = 1013;
  STRUCT_TYPE_POLICY = 1030;
  STRUCT_TYPE_POLICY_RULE = 1031;
  STRUCT_TYPE_SUBJECT = 1032;
  STRUCT_TYPE_ACCESS_ZONE = 1034;
  STRUCT_TYPE_ACCESS_MATRIX = 1035;
  STRUCT_TYPE_ACCESS = 1037;
  STRUCT_TYPE_READ_OPTIONS = 1050;
  STRUCT_TYPE_EXPRESSION = 1060;
  STRUCT_TYPE_AGGREGATION = 1061;
  STRUCT_TYPE_SELECTION = 1070;
  STRUCT_TYPE_CODE = 1090;
  STRUCT_TYPE_CODE_LINE = 1091;
  STRUCT_TYPE_STEP_CONNECTION = 1100;
  STRUCT_TYPE_RUN_ERROR = 1110;
  STRUCT_TYPE_RUN_OPTIONS = 1111;
  STRUCT_TYPE_RETRY_ATTEMPT = 1113;
  STRUCT_TYPE_TEXT = 1160;
  STRUCT_TYPE_TEXT_LINE = 1161;
  STRUCT_TYPE_TEXT_SPAN = 1162;
  STRUCT_TYPE_COLOR = 1200;
  STRUCT_TYPE_FONT = 1201;
  STRUCT_TYPE_BOX = 1202;
  STRUCT_TYPE_OFFSET = 1203;
  STRUCT_TYPE_TRANSFORM = 1204;
  STRUCT_TYPE_FILE = 1250;
  STRUCT_TYPE_ICON = 1251;
}

// How a Resource is shared (if at all).
enum Tenancy {
  TENANCY_UNSPECIFIED = 0;
  TENANCY_SHARED = 3;
  TENANCY_DEDICATED = 7;
}

enum TextLineType {
  TEXT_LINE_TYPE_UNSPECIFIED = 0;
  TEXT_LINE_TYPE_PLAIN = 1;
  TEXT_LINE_TYPE_HEADING_SMALL = 10;
  TEXT_LINE_TYPE_HEADING_MEDIUM = 11;
  TEXT_LINE_TYPE_HEADING_LARGE = 12;
  TEXT_LINE_TYPE_CALLOUT = 20;
  TEXT_LINE_TYPE_QUOTE = 21;
  TEXT_LINE_TYPE_LIST_BULLET = 30;
  TEXT_LINE_TYPE_LIST_NUMBERED = 31;
  TEXT_LINE_TYPE_LIST_UNCHECKED = 32;
  TEXT_LINE_TYPE_LIST_CHECKED = 33;
  TEXT_LINE_TYPE_DIVIDER = 40;
}

enum TimeInterval {
  TIME_INTERVAL_UNSPECIFIED = 0;
  TIME_INTERVAL_SECOND = 2;
  TIME_INTERVAL_MINUTE = 3;
  TIME_INTERVAL_HOUR = 4;
  TIME_INTERVAL_DAY = 5;
  TIME_INTERVAL_WEEK = 6;
  TIME_INTERVAL_MONTH = 7;
  TIME_INTERVAL_YEAR = 8;
}

// Triggers for blocks (for both actual runs and pre-defined triggers).
enum TriggerType {
  TRIGGER_TYPE_UNSPECIFIED = 0;
  TRIGGER_TYPE_SCHEDULE = 1;
  TRIGGER_TYPE_SIGNAL = 2;
}

// The 'kind' of a Type.
enum TypeKind {
  TYPE_KIND_UNSPECIFIED = 0;
  TYPE_KIND_PRIMITIVE = 1;
  TYPE_KIND_STRUCT = 2;
  TYPE_KIND_NODE = 3;
  TYPE_KIND_ENUM = 4;
  TYPE_KIND_BASED_NODE = 5;
  TYPE_KIND_OBJECT = 6;
  TYPE_KIND_LITERAL = 7;
  TYPE_KIND_ALIAS = 10;
}

// Ways to use nodes.
enum UseType {
  USE_TYPE_UNSPECIFIED = 0;
  USE_TYPE_START = 40;
  USE_TYPE_PAUSE = 41;
  USE_TYPE_RESUME = 42;
  USE_TYPE_STOP = 43;
  USE_TYPE_KILL = 44;
  USE_TYPE_SEND = 45;
  USE_TYPE_RECEIVE = 46;
}

enum UserStatus {
  USER_STATUS_UNSPECIFIED = 0;
  USER_STATUS_INVITED = 1;
  USER_STATUS_RESERVED = 2;
  USER_STATUS_WAITLISTED = 3;
  USER_STATUS_REGISTERED = 4;
  USER_STATUS_ACTIVATED = 10;
}

// The style variant of a view.
enum Variant {
  VARIANT_UNSPECIFIED = 0;
  VARIANT_PRIMARY = 1;
  VARIANT_SECONDARY = 2;
  VARIANT_COMPACT = 3;
  VARIANT_STEALTH = 4;
}

enum ViewType {
  VIEW_TYPE_UNSPECIFIED = 0;
  VIEW_TYPE_USER_WIZARD = 1;
  VIEW_TYPE_BENCH_WIZARD = 2;
  VIEW_TYPE_EMPTY = 80;
  VIEW_TYPE_PAGE = 101;
  VIEW_TYPE_BLOCK = 102;
  VIEW_TYPE_FIELD = 103;
  VIEW_TYPE_DATABASE = 104;
  VIEW_TYPE_SCREEN = 105;
  VIEW_TYPE_FLOW = 106;
  VIEW_TYPE_STEP = 107;
  VIEW_TYPE_TYPE = 108;
  VIEW_TYPE_VARIABLE = 109;
  VIEW_TYPE_OBJECT = 110;
  VIEW_TYPE_RUN = 111;
  VIEW_TYPE_EXPLORE = 150;
  VIEW_TYPE_OUTLINE = 151;
  VIEW_TYPE_INSPECT = 153;
  VIEW_TYPE_CREATE = 154;
  VIEW_TYPE_CHAT = 155;
  VIEW_TYPE_START = 156;
  VIEW_TYPE_FEED = 157;
  VIEW_TYPE_TIMELINE = 158;
  VIEW_TYPE_HISTORY = 159;
  VIEW_TYPE_WINDOW = 500;
  VIEW_TYPE_TAB = 502;
  VIEW_TYPE_SPLIT = 503;
  VIEW_TYPE_SPLIT_DRAWER = 504;
  VIEW_TYPE_STACK = 510;
  VIEW_TYPE_DRAWER = 511;
  VIEW_TYPE_SCROLL = 512;
  VIEW_TYPE_GRID = 513;
  VIEW_TYPE_LIST = 520;
  VIEW_TYPE_TABLE = 521;
  VIEW_TYPE_GROUP = 530;
  VIEW_TYPE_SECTION = 531;
  VIEW_TYPE_SPACER = 540;
  VIEW_TYPE_DIVIDER = 541;
  VIEW_TYPE_SHAPE = 543;
  VIEW_TYPE_PROGRESS = 544;
  VIEW_TYPE_AVATAR = 545;
  VIEW_TYPE_BADGE = 546;
  VIEW_TYPE_CHART = 547;
  VIEW_TYPE_BUTTON = 600;
  VIEW_TYPE_MULTI_BUTTON = 601;
  VIEW_TYPE_LINK = 610;
  VIEW_TYPE_VALUE = 620;
  VIEW_TYPE_NUMBER = 632;
  VIEW_TYPE_SLIDER = 633;
  VIEW_TYPE_STRING = 640;
  VIEW_TYPE_TEXT = 641;
  VIEW_TYPE_CODE = 642;
  VIEW_TYPE_JSON = 643;
  VIEW_TYPE_TOGGLE = 650;
  VIEW_TYPE_PICKER = 653;
  VIEW_TYPE_CALENDAR = 656;
  VIEW_TYPE_MAP = 658;
  VIEW_TYPE_COLOR = 660;
  VIEW_TYPE_FILE = 670;
  VIEW_TYPE_ICON = 672;
  VIEW_TYPE_IMAGE = 673;
  VIEW_TYPE_VIDEO = 674;
  VIEW_TYPE_AUDIO = 675;
}

enum Visibility {
  VISIBILITY_UNSPECIFIED = 0;
  VISIBILITY_PAGE = 4;
  VISIBILITY_MODULE = 6;
  VISIBILITY_BENCH = 8;
  VISIBILITY_PUBLIC = 10;
}

// An evaluated access on some objects as part of a larger request (by the same subject).
message AccessData {
  ObjectType metatype = 1;
  AccessMode mode = 30;
  PolicyEffect decision = 31;
  AccessType verb = 32;
  NodeType node_type = 33;
  repeated PropertyReferenceData allowed_properties_ptr = 34;
}

// The materialized access matrix generated for a specific subject to quickly evaluate access for objects.
message AccessMatrixData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  SubjectData subject = 30;
  repeated SubjectData identities = 32;
  repeated AccessZoneData scoped_zones = 33;
  repeated AccessZoneData base_zones = 34;
}

// The pre-filtered access rules for a given identity.
// Clients use this to indicate access rights, but - obviously - only our copy is binding.
message AccessZoneData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  string scope_id = 30;
  int32 identity_id = 31;
  repeated PolicyRuleData rules = 32;
}

// The result of an aggregation expression.
message AggregationData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  AggregationOp op = 30;
  optional bool exists = 31;
  optional int32 count = 32;
  optional float scalar = 33;
}

// A box value. Absolute units are in pixels, ideally in Spacing scale.
message BoxData {
  ObjectType metatype = 1;
  optional int32 width = 50;
  optional int32 height = 51;
  optional float width_relative = 52;
  optional float height_relative = 53;
}

// Code composed of multiple lines.
message CodeData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  repeated CodeLineData lines = 30;
}

// A line of code.
message CodeLineData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  string content = 32;
}

// A color value.
message ColorData {
  ObjectType metatype = 1;
  optional ColorType type = 31;
  optional ColorShade shade = 32;
  optional string hex = 33;
}

// The context at some point and time in the Bench tree.
message ContextData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  optional NodeReferenceData bench_ptr = 30;
  optional NodeReferenceData environment_ptr = 31;
  optional NodeReferenceData branch_ptr = 32;
  optional NodeReferenceData package_ptr = 33;
  optional NodeReferenceData module_ptr = 34;
  optional NodeReferenceData page_ptr = 35;
  optional NodeReferenceData block_ptr = 36;
  optional NodeReferenceData step_ptr = 37;
  optional NodeReferenceData client_ptr = 40;
  optional NodeReferenceData server_ptr = 41;
  optional NodeReferenceData user_ptr = 42;
  optional int64 epoch = 50;
  optional NodeReferenceData session_ptr = 51;
  optional NodeReferenceData run_ptr = 52;
  optional NodeReferenceData run_root_ptr = 53;
  optional NodeReferenceData trigger_ptr = 54;
  optional NodeReferenceData signal_ptr = 55;
}

// Additional context for a specific edit (per-edit variable subset of Session context).
message EditContextData {
  ObjectType metatype = 1;
  optional NodeReferenceData block_ptr = 60;
  optional NodeReferenceData step_ptr = 61;
  optional NodeReferenceData session_ptr = 62;
  optional NodeReferenceData run_ptr = 63;
  optional NodeReferenceData run_root_ptr = 64;
}

// An expression like a value, function, comparison or such.
message ExpressionData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  ExpressionOp op = 30;
  optional NodeReferenceData field_ptr = 31;
  optional PropertyReferenceData property_ptr = 32;
  repeated ExpressionData clauses = 35;
  optional google.protobuf.Struct value_packed = 36;
  optional SortMode sort_mode = 38;
  optional float tolerance = 39;
}

// A reference to a file stored somewhere.
message FileData {
  ObjectType metatype = 1;
  optional string type = 31;
  string name = 33;
  optional int32 size = 34;
  optional string sha512 = 35;
  optional NodeReferenceData blob_ptr = 36;
  optional string external_url = 37;
}

// A font value.
message FontData {
  ObjectType metatype = 1;
  optional FontType type = 31;
  optional FontWeight weight = 32;
  optional FontSize size = 33;
}

// An icon to be displayed in some view.
message IconData {
  ObjectType metatype = 1;
  IconKind kind = 30;
  optional string emoji = 31;
  optional FileData file = 32;
  optional string fa_name = 33;
  optional ColorData color = 40;
}

// A reference to a Node.
// We include the Bench and 'ck' where available.
// Base = the node is 'based' on (like Record.parent->Block, Signal.type->Block).
message NodeReferenceData {
  ObjectType metatype = 1;
  NodeType type = 30;
  optional string id = 31;
  optional string ck = 32;
  optional string bench_id = 33;
  optional string base_ck = 34;
  optional string base_bench_id = 35;
}

// A position value. Absolute units are in pixels, ideally in Spacing scale.
message OffsetData {
  ObjectType metatype = 1;
  optional int32 top = 40;
  optional int32 right = 41;
  optional int32 bottom = 42;
  optional int32 left = 43;
  optional float top_relative = 44;
  optional float right_relative = 45;
  optional float bottom_relative = 46;
  optional float left_relative = 47;
}

// A human-readable Bench path to reference source nodes and their fields/properties. Absolute or relative.
// Paths are case-insensitive, support alphanum + spaces and use '/' as the primary node separator.
// Nodes 'below' block-level are prefixed with one ':'. Fields are accessed with '.' separators.
// 
// flotothemoon/Mirror/Notion/Databases/Landscape
// ^ bench      ^ blocks
// flotothemoon/Applications/Birdy/MainScreen:Dashboard/Big Graphs/Graph1.name
// ^ bench      ^ blocks                      ^ sub-block nod            ^ field
// flotothemoon/Sandbox/Sales/Pipeline/Scraping/WebsiteSamples/Replit.document.title
// ^ bench      ^ blocks                                              ^ field  ^ field
// 
// flotothemoon
// ^ bench
// flotothemoon.name
// ^ bench      ^ field
// flotothemoon-tests/Tests/Databases/TestPopulate.code
// ^ bench            ^ blocks                     ^ field
// 
// .
// ^ current
// ..
// ^ parent
// ../../Header Screen:Header/Title.theme.primary.color
// ^ blocks           ^ sub-nodes  ^ field
// ../../../../Graphs
// ^ parents
// 
// symbolx@2024-01-01/Library/Common/Utils/DateUtils
// ^ bench ^ package  ^ blocks
// symbolx@MyNewFeature:2024-01-01/Applications/Chat/MainScreen:ChatInput/Input.text
// ^ bench ^ branch     ^ package  ^ blocks                     ^ sub-nodes     ^ field
// 
// also relative:
// / -> package (=Package)
// $ -> module (=Block|Package)
// ^ -> page (=Block)
// $User -> module-unique node (=Block|View)
// ~ -> source module root (like $ but for templated)
// [<expr like ck=...>] -> dynamic Expression filter
// 
// ''
// ERROR (invalid, empty path)
// '../'
// ERROR (invalid, trailing slash)
// ../../Something/../SomethingElse
// ERROR (invalid, cannot go up and down in the same path)
// 
// The general syntax is:
// [bench-name][@branch-name][:package-name][/[block-name][:sub-node-name]][.field-name]
// For absolute paths, the bench name is required.
message PathData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  repeated PathSegmentData segments = 31;
}

// A semantic part of a Bench path.
message PathSegmentData {
  ObjectType metatype = 1;
  PathSegmentType type = 31;
  optional string name = 32;
  optional NodeReferenceData reference_ptr = 33;
}

// A lexical token in a Bench path.
message PathTokenData {
  ObjectType metatype = 1;
  PathTokenType type = 31;
  optional string content = 32;
}

// A policy regulating access to nodes within its scope.
// The scope is determined by where its attached, but may be further restricted using 'scopes'.
// 
// The basics of access control:
// 1. Access is DENIED implicitly unless explicitly and fully ALLOWED.
// 2. Policies are either attached
// a. directly to nodes (scoped to the node)
// b. or to a delegate (full scope or less as specified)
// 3. Policies are evaluated in order up the node graph, first match decides*.
// (This means you can read a sub block but not its parent.)
// 4. Every identity/role/... applicable to a subject is evaluated separately and *any* allow wins.
// 
// * Conceptually, we do 'ray trace' up the graph for every node/property/...,
// but actually doing that for every request is prohibitively expensive.
// Instead, we 'rasterize' an 'access matrix' and use 'zones' as a shortcut.
message PolicyData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  string name = 30;
  optional TextData text = 31;
  repeated PolicyRuleData rules = 32;
  repeated NodeReferenceData scopes_ptr = 33;
}

// A rule in a policy: [subject] + [effect] [verb] + [object] [if condition].
// Subject, verb and object are ORed, in-group conditions are ANDed.
// (where None/empty -> wildcard, any value -> filter)
message PolicyRuleData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  string name = 30;
  optional TextData text = 31;
  optional bool subject_is_delegated = 40;
  optional bool subject_is_authenticated = 41;
  optional bool subject_is_staff = 42;
  optional bool subject_is_member = 43;
  optional bool subject_is_owner = 44;
  PolicyEffect effect = 60;
  repeated AccessType verbs = 61;
  repeated AccessKind verb_kinds = 62;
  repeated NodeType object_node_types = 80;
  repeated PropertyReferenceData object_properties_ptr = 81;
  optional bool object_properties_is_system = 82;
  optional bool object_properties_is_sensitive = 83;
  optional bool object_properties_is_kernel = 84;
}

// A projection into the graph.
// NOTE :Incomplete :Architecture: figure out projection
// - how do we filter and LoD this?
// - how do we represent unloaded nodes?
// - how do we make projections reproducible and inspectable in the editor?
message ProjectionData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
}

// A reference to a builtin object's Property.
// If type is unset, this refers to a base property in one of the base BuiltinObject types.
message PropertyReferenceData {
  ObjectType metatype = 1;
  optional ObjectType type = 30;
  int32 id = 31;
  optional NodeType references_node = 32;
}

// Fine-grained options to a read request.
// This is an addition to primary options (like the filter for a search or aggregation).
message ReadOptionsData {
  ObjectType metatype = 1;
  repeated NodeType ancestor_types = 31;
  repeated NodeType descendant_types = 32;
  repeated PropertyReferenceData include_properties_ptr = 40;
  repeated PropertyReferenceData exclude_properties_ptr = 41;
  repeated PropertyReferenceData select_properties_ptr = 42;
  bool select_all_properties = 43;
  bool include_hidden = 50;
}

// A single attempt at a Run.
message RetryAttemptData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  RunStatus status = 30;
  optional float duration = 31;
  optional google.protobuf.Timestamp started_at = 32;
  optional int32 started_epoch = 33;
  optional google.protobuf.Timestamp paused_at = 34;
  optional google.protobuf.Timestamp terminated_at = 35;
  optional int32 terminated_epoch = 36;
  optional RunErrorData error = 37;
}

// An error that occurred in the context of a Run.
message RunErrorData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  RunErrorKind kind = 30;
  optional RunErrorType type = 31;
  optional string title = 32;
  optional TextData text = 33;
  optional NodeReferenceData node_ptr = 34;
}

// Options for running something.
message RunOptionsData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  optional int32 max_concurrency = 30;
  optional int32 max_attempts = 31;
  optional float retry_interval = 32;
  optional float backoff = 33;
  optional float max_retry_interval = 34;
  optional float jitter = 35;
  repeated RunErrorType retry_on = 38;
}

// The time-based schedule of something.
message ScheduleData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  ScheduleType type = 30;
  optional string timezone = 31;
  int32 every = 40;
  TimeInterval interval = 41;
  optional google.protobuf.Duration offset = 42;
  optional string cron = 50;
}

// A selection of nodes/values.
message SelectionData {
  ObjectType metatype = 1;
  SelectionKind kind = 30;
  repeated NodeReferenceData nodes_ptr = 31;
  optional NodeReferenceData from_node_ptr = 32;
  optional NodeReferenceData to_node_ptr = 33;
}

// Context information for runtime nodes created in a session.
message SessionContextData {
  ObjectType metatype = 1;
  optional NodeReferenceData block_ptr = 60;
  optional NodeReferenceData step_ptr = 61;
  optional NodeReferenceData session_ptr = 62;
  optional NodeReferenceData run_ptr = 63;
  optional NodeReferenceData run_root_ptr = 64;
  optional NodeReferenceData client_ptr = 65;
  optional NodeReferenceData machine_ptr = 66;
  optional NodeReferenceData server_ptr = 67;
  optional NodeReferenceData user_ptr = 68;
}

// A connection between two Steps in a FlowBlock.
message StepConnectionData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  StepConnectionType type = 30;
  NodeReferenceData source_ptr = 31;
}

// The <whoever/whatever> issuing a request. Unknown/ignored attributes are unset.
// (We unset various combinations of attributes to evaluate the access of acting subjects independently.)
message SubjectData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  optional bool is_authenticated = 30;
  optional bool is_staff = 31;
  optional bool is_system = 32;
  optional NodeReferenceData client_ptr = 40;
  optional NodeReferenceData user_ptr = 41;
  optional NodeReferenceData server_ptr = 42;
  optional NodeReferenceData identity_ptr = 50;
  repeated NodeReferenceData badges_ptr = 51;
  repeated NodeReferenceData owned_ptr = 52;
  repeated NodeReferenceData memberships_ptr = 53;
  repeated NodeReferenceData roles_ptr = 54;
}

// Rich, markdown-inspired Text with mentions, lists & other extensions.
// Text is structured into lines, which contain spans.
// Formatting can be applied at per Text, line and span.
message TextData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  repeated TextLineData lines = 32;
}

// A single line of Text with formatting, composed of spans.
// A line may contain hard breaks, so it's effectively a paragraph.
message TextLineData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  TextLineType type = 30;
  repeated TextSpanData spans = 33;
  optional IconData icon = 34;
  optional ColorType color = 50;
  optional bool is_bold = 60;
  optional bool is_italic = 61;
  optional bool is_strikethrough = 62;
  optional bool is_underline = 63;
  optional bool is_code = 64;
}

// A span of text with optional formatting.
message TextSpanData {
  ObjectType metatype = 1;
  optional string content = 33;
  optional NodeReferenceData node_ptr = 34;
  optional ColorType color = 50;
  optional bool is_bold = 60;
  optional bool is_italic = 61;
  optional bool is_strikethrough = 62;
  optional bool is_underline = 63;
  optional bool is_code = 64;
}

// A transform in 2D space.
message TransformData {
  ObjectType metatype = 1;
  optional int32 translate_x = 30;
  optional int32 translate_y = 31;
  optional float scale_x = 33;
  optional float scale_y = 34;
  optional float skew_x = 36;
  optional float skew_y = 37;
  optional int32 rotate_x = 40;
}

// A simple constraint on the values of a type. :TypeConstraint
// Basically a more restricted form of a condition Expression.
message TypeConstraintData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  optional float min_value = 40;
  optional float max_value = 41;
  optional float step_value = 42;
  optional int32 min_length = 50;
  optional int32 max_length = 51;
  optional string regex = 60;
  optional string starts_with = 61;
  optional string ends_with = 62;
}

// A type from the type system.
message TypeInfoData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  TypeKind kind = 40;
  optional PrimitiveType primitive_type = 41;
  optional BenchType bench_type = 42;
  optional NodeReferenceData base_type_ptr = 43;
  optional FieldZone base_field_zone = 44;
  optional google.protobuf.Struct default_packed = 50;
  optional Visibility visibility = 52;
  optional FormatHint format_hint = 53;
  optional ExpressionData condition = 54;
  optional TypeConstraintData constraint = 55;
  bool is_list = 60;
  bool is_secret = 61;
  bool is_required = 62;
}

// Reference a value at a path of a Node.
message ValueReferenceData {
  ObjectType metatype = 1;
  int32 id = 2;
  optional int32 parent_id = 3;
  optional string parent_key = 4;
  optional string order_key = 9;
  PathData path = 31;
}

// Attach a badge to a node with an inline definition.
// A badge's policies are delegated to the 'holder' (any client presenting its secrets).
// The delegated policies apply at the parent scope OR given scopes (which must be below parent's).
message BadgeData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 31;
  repeated PolicyData delegated_policies = 32;
  optional google.protobuf.Timestamp expires_at = 33;
  optional string key = 40;
  optional string key_hash = 41;
  optional string password = 42;
  optional string password_hash = 43;
}

// A Bench is an AI-native operating system for a new generation of fully integrated, fluid software.
message BenchData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional NodeReferenceData main_handle_ptr = 31;
  string slug = 32;
  string name = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  optional NodeReferenceData owner_ptr = 36;
  Region region = 37;
  optional string encryption_key = 38;
  repeated PolicyData policies = 39;
  optional NodeReferenceData main_environment_ptr = 40;
  optional NodeReferenceData main_branch_ptr = 41;
}

// The actual file content stored as a Blob in a Drive. De-duped to 1 per sha512.
message BlobData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  optional ResourceStatus current_status = 37;
  string sha512 = 40;
  int64 size = 41;
  string mime_type = 42;
  FileRetentionMode retention = 43;
  optional google.protobuf.Timestamp expires_at = 44;
}

// A building block containing logic, types, UI, data, AI, - any Bench program source.
message BlockData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  BlockType type = 30;
  string name = 32;
  string order_key = 33;
  repeated PolicyData policies = 34;
  repeated NodeReferenceData bases_ptr = 35;
  optional TextData text = 36;
  optional IconData icon = 37;
  optional Visibility visibility = 38;
  optional TypeInfoData value_type = 39;
  optional google.protobuf.Struct value_packed = 40;
  optional google.protobuf.Struct secret_value_packed = 41;
  optional CodeData code = 42;
  optional RunOptionsData run_options = 43;
  repeated PolicyData delegated_policies = 49;
  bool is_builtin = 60;
  bool is_page = 61;
  bool is_protocol = 62;
  bool is_template = 63;
  bool is_paused = 64;
  bool is_materialized = 65;
}

// A branch is a lineage of Bench history.
message BranchData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional string slug = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  repeated PolicyData policies = 36;
  optional NodeReferenceData main_package_ptr = 40;
  optional NodeReferenceData base_ptr = 41;
  bool is_overlay = 60;
  bool is_light = 61;
}

// A client to a Bench.
message ClientData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  ClientType type = 30;
  string name = 32;
  optional string device_type = 40;
  optional string device_name = 41;
  optional string operating_system = 42;
  optional string browser_name = 43;
  optional string browser_version = 44;
  optional string place_id = 45;
  optional string access_token = 50;
  google.protobuf.Timestamp seen_at = 51;
  optional google.protobuf.Timestamp logged_in_at = 52;
  optional NodeReferenceData space_ptr = 60;
  optional NodeReferenceData machine_ptr = 61;
}

// A dependency on another Bench (pointing to a specific Package).
// If scopes are given, only those blocks are included.
message DependencyData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  repeated NodeReferenceData scopes_ptr = 30;
  NodeReferenceData dependency_ptr = 40;
  repeated NodeReferenceData dependency_scopes_ptr = 41;
}

// Drive for file storage.
message DriveData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  optional ResourceStatus current_status = 37;
}

// An environment of resources for a Bench's packages.
message EnvironmentData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional TextData text = 34;
  optional IconData icon = 35;
  repeated PolicyData policies = 36;
  NodeReferenceData server_ptr = 40;
  NodeReferenceData store_ptr = 41;
  NodeReferenceData drive_ptr = 42;
}

// A used-defined attribute of some value
// (Bench defines Properties for Nodes/Structs, Users define Fields for Values inside those).
message FieldData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 30;
  string order_key = 31;
  FieldZone zone = 32;
  optional TextData text = 33;
  optional IconData icon = 34;
  optional google.protobuf.Struct value_packed = 35;
  TypeKind kind = 40;
  optional PrimitiveType primitive_type = 41;
  optional BenchType bench_type = 42;
  optional NodeReferenceData base_type_ptr = 43;
  optional FieldZone base_field_zone = 44;
  optional google.protobuf.Struct default_packed = 50;
  optional Visibility visibility = 52;
  optional FormatHint format_hint = 53;
  optional ExpressionData condition = 54;
  optional TypeConstraintData constraint = 55;
  bool is_list = 60;
  bool is_secret = 61;
  bool is_required = 62;
}

// A Bench @handle. Can only be created/edited by the system.
message HandleData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  optional NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string slug = 30;
}

// Attach an identity to a block, member or user (only the user itself can do that).
// Identity policies are delegated to the parent and its descendants.
// The delegated policies apply to all descendant's accesses.
message IdentityData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NodeReferenceData type_ptr = 30;
}

// An invitation to become a member of this Bench.
message InviteData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional NodeReferenceData user_ptr = 30;
  optional string user_email = 31;
  bool is_owner = 32;
  repeated NodeReferenceData roles_ptr = 33;
}

// A diagnostic regarding something in the Bench source.
message IssueData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  IssueKind kind = 30;
  IssueType type = 31;
  optional NodeReferenceData subject_ptr = 33;
  optional PathData path = 34;
  repeated PropertyReferenceData properties_ptr = 35;
  optional string title = 40;
  optional TextData text = 41;
}

// A reference to another node in some graph.
// The referenced subtree is inlined on access.
// The reference may be indirect through a value somewhere (which should point to a node).
message LinkData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional NodeReferenceData reference_ptr = 30;
  optional string order_key = 32;
}

// A Log of something happening in a Bench.
message LogData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  LogKind kind = 30;
  LogLevel level = 31;
  optional AccessType type = 40;
  optional NodeReferenceData node_ptr = 41;
  repeated int32 properties = 42;
  optional google.protobuf.Struct old_node_packed = 43;
  optional google.protobuf.Struct old_node_secret_packed = 44;
  optional google.protobuf.Struct new_node_packed = 45;
  optional google.protobuf.Struct new_node_secret_packed = 46;
  optional int64 new_revision = 47;
  optional string title = 50;
  optional TextData text = 51;
  optional google.protobuf.Struct value_packed = 52;
  optional google.protobuf.Struct secret_value_packed = 53;
  optional NodeReferenceData block_ptr = 60;
  optional NodeReferenceData step_ptr = 61;
  optional NodeReferenceData session_ptr = 62;
  optional NodeReferenceData run_ptr = 63;
  optional NodeReferenceData run_root_ptr = 64;
  optional NodeReferenceData client_ptr = 65;
  optional NodeReferenceData machine_ptr = 66;
  optional NodeReferenceData server_ptr = 67;
  optional NodeReferenceData user_ptr = 68;
}

// A Machine provides some isolated compute for a Server.
message MachineData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  optional ResourceStatus current_status = 37;
  MachineProfile profile = 40;
  optional MachineProfile current_profile = 41;
  optional string version = 42;
  optional string current_version = 43;
  optional string external_name = 50;
  optional string external_id = 51;
  optional string connection_uri = 52;
  optional google.protobuf.Timestamp started_at = 60;
  optional google.protobuf.Timestamp terminated_at = 61;
  optional google.protobuf.Timestamp active_at = 62;
}

// A membership to this Bench (and its owner if it's the main Bench).
message MembershipData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NodeReferenceData user_ptr = 30;
  bool is_owner = 31;
}

// A Message by a User or program (author = created_by).
// If the parent is also a Message, then this is part of a thread. Threads may be nested.
message MessageData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NodeReferenceData origin_ptr = 32;
  optional PathData path = 33;
  optional NodeReferenceData reply_to_ptr = 34;
  optional string title = 40;
  optional TextData text = 41;
  optional google.protobuf.Struct value_packed = 42;
  optional google.protobuf.Struct secret_value_packed = 43;
  bool is_pinned = 50;
}

// A basic Node with properties like a Struct and a global identity in our graph.
// Conceptually, all nodes live together happily in a single big graph family.
// In practice and at runtime, there are multiple smaller NodeGraphs we load via Connections.
// Nodes resolve references to each through a super graph composed of currently loaded NodeGraphs.
message BaseNodeData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
}

// A Notification for a Bench (author = created_by).
message NotificationData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NotificationKind kind = 30;
  NodeReferenceData type_ptr = 32;
  optional google.protobuf.Timestamp expires_at = 33;
  optional google.protobuf.Timestamp read_at = 34;
  optional string title = 40;
  optional TextData text = 41;
  optional google.protobuf.Struct value_packed = 42;
  optional google.protobuf.Struct secret_value_packed = 43;
}

// A Bench organization with Users as members.
// Until activation only its creator has access.
message OrganizationData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional NodeReferenceData main_handle_ptr = 31;
  optional string slug = 32;
  string name = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  optional NodeReferenceData main_bench_ptr = 36;
  OrganizationStatus status = 37;
}

// A package is a version of a Bench in a Branch.
message PackageData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional string slug = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  repeated PolicyData policies = 36;
  NodeReferenceData environment_ptr = 40;
  optional NodeReferenceData base_ptr = 41;
  bool is_snapshot = 60;
  bool is_overlay = 61;
  bool is_paused = 65;
}

// A stored query.
message QueryData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 30;
  string order_key = 31;
  ReadType read_type = 32;
  NodeType node_type = 33;
  optional NodeReferenceData base_ptr = 34;
  optional ExpressionData filter = 35;
  repeated ExpressionData sort = 36;
}

// A record in a DatabaseBlock.
// If the block is_materialized, the backing table is a real Postgres table.
message RecordData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional google.protobuf.Struct value_packed = 30;
  optional google.protobuf.Struct secret_value_packed = 31;
}

// Attach a role to a block or member.
// Role policies are delegated to the parent and its descendants.
// The delegated policies apply to all descendant's accesses.
message RoleData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NodeReferenceData type_ptr = 30;
}

// A 'run' of Blocks (and Steps within them) or 'lambdas' (just Code/Text).
// When 'running' something that's not directly runnable (like a Text Block, Text Step or Text Lambda),
// we implicitly pass it to the corresponding default Text program.
// Once terminated, a Run is effectively immutable.
message RunData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  RunKind kind = 30;
  NodeReferenceData root_ptr = 32;
  optional CodeData code = 36;
  optional TextData text = 37;
  optional RunOptionsData options = 38;
  RunStatus status = 40;
  optional RunStatus current_status = 41;
  optional float duration = 42;
  optional google.protobuf.Timestamp scheduled_at = 43;
  optional int32 scheduled_epoch = 44;
  optional google.protobuf.Timestamp started_at = 45;
  optional int32 started_epoch = 46;
  optional google.protobuf.Timestamp paused_at = 47;
  optional google.protobuf.Timestamp terminated_at = 48;
  optional int32 terminated_epoch = 49;
  optional google.protobuf.Struct inputs_packed = 50;
  optional google.protobuf.Struct inputs_secret_packed = 51;
  optional google.protobuf.Struct outputs_packed = 52;
  optional google.protobuf.Struct outputs_secret_packed = 53;
  optional google.protobuf.Struct value_packed = 54;
  optional google.protobuf.Struct value_secret_packed = 55;
  repeated RetryAttemptData attempts = 56;
  optional RunErrorData error = 57;
  optional NodeReferenceData block_ptr = 60;
  optional NodeReferenceData step_ptr = 61;
  optional NodeReferenceData session_ptr = 62;
  optional NodeReferenceData run_ptr = 63;
  optional NodeReferenceData run_root_ptr = 64;
  optional NodeReferenceData client_ptr = 65;
  optional NodeReferenceData machine_ptr = 66;
  optional NodeReferenceData server_ptr = 67;
  optional NodeReferenceData user_ptr = 68;
}

// A server provides some compute for a Bench's Runtime.
// Physical compute is materialized (on-demand) as Machines.
message ServerData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  optional ResourceStatus current_status = 37;
  ServerProfile profile = 40;
  optional ServerProfile current_profile = 41;
  optional string version = 42;
  optional string current_version = 43;
  optional google.protobuf.Timestamp active_at = 60;
  optional google.protobuf.Timestamp bumped_at = 61;
}

// A managed Session for interacting with and running a Bench in a Client.
// If a Run spans multiple Clients, each Client will have its own Session.
// On some Clients a Session may persist across Runs (like in the web client).
// Once closed, a Session (like a Run) is effectively immutable.
message SessionData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  SessionStatus status = 40;
  optional float duration = 41;
  optional google.protobuf.Timestamp opened_at = 42;
  optional google.protobuf.Timestamp closed_at = 43;
  optional NodeReferenceData client_ptr = 61;
  optional NodeReferenceData server_ptr = 62;
  optional NodeReferenceData machine_ptr = 63;
  optional NodeReferenceData user_ptr = 64;
}

// A Signal emitted in this Bench, usually received in Triggers.
message SignalData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NodeReferenceData type_ptr = 32;
  optional google.protobuf.Struct value_packed = 42;
  optional google.protobuf.Struct secret_value_packed = 43;
  optional NodeReferenceData block_ptr = 60;
  optional NodeReferenceData step_ptr = 61;
  optional NodeReferenceData session_ptr = 62;
  optional NodeReferenceData run_ptr = 63;
  optional NodeReferenceData run_root_ptr = 64;
  optional NodeReferenceData client_ptr = 65;
  optional NodeReferenceData machine_ptr = 66;
  optional NodeReferenceData server_ptr = 67;
  optional NodeReferenceData user_ptr = 68;
}

// A reference to another node in some graph that wasn't available for some reason (usually permissions).
message SkipData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  NodeReferenceData reference_ptr = 30;
  optional string order_key = 31;
}

// A space for a user to interact with the Bench.
message SpaceData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  SpaceType type = 30;
  string name = 31;
  optional TextData text = 32;
  string order_key = 33;
  repeated PolicyData policies = 34;
  optional Anchor bar_position = 40;
  optional SelectionData focus = 70;
  optional NodeReferenceData inspection_ptr = 75;
  optional NodeReferenceData base_ptr = 76;
}

// An data or control flow unit in a FlowBlock.
message StepData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  StepType type = 30;
  string name = 32;
  string order_key = 33;
  optional TextData text = 34;
  optional IconData icon = 35;
  optional RunOptionsData run_options = 36;
  repeated StepConnectionData connections = 37;
  optional TypeInfoData value_type = 40;
  optional google.protobuf.Struct value_packed = 41;
  optional google.protobuf.Struct secret_value_packed = 42;
  optional NodeReferenceData node_ptr = 43;
  optional CodeData code = 44;
  optional ExpressionData condition = 45;
  optional OffsetData position = 50;
  optional ColorData background_color = 51;
  bool is_template = 60;
}

// A trusty Postgres database.
message StoreData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData bench_ptr = 6;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional TextData text = 34;
  Region region = 35;
  ResourceStatus status = 36;
  optional ResourceStatus current_status = 37;
  optional string version = 40;
  optional string current_version = 41;
  optional string external_name = 50;
  optional string external_id = 51;
  optional string connection_uri = 52;
}

// A trigger to run the node it is attached to (like a Block or Step).
message TriggerData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  TriggerType type = 30;
  string name = 31;
  optional int32 processed_epoch = 32;
  optional ScheduleData schedule = 40;
  optional NodeReferenceData signal_ptr = 41;
  optional ExpressionData condition = 42;
  bool is_paused = 50;
}

// An 'upgrade' to a Package, marking changes made to the containing Package.
message UpgradeData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  string name = 32;
  optional string title = 34;
  optional TextData text = 35;
}

// A Bench user.
message UserData {
  ObjectType metatype = 1;
  string id = 2;
  optional NodeReferenceData parent_ptr = 4;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 13;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  optional NodeReferenceData main_handle_ptr = 31;
  optional string slug = 32;
  string name = 33;
  optional TextData text = 34;
  optional string email = 35;
  optional IconData icon = 36;
  optional NodeReferenceData main_bench_ptr = 37;
  UserStatus status = 38;
  optional bytes password_salt = 50;
  optional bytes password_hash = 51;
  optional google.protobuf.Timestamp last_logged_in_at = 70;
  bool is_staff = 90;
}

// A view of a user interface in a Bench.
message ViewData {
  ObjectType metatype = 1;
  string id = 2;
  string ck = 3;
  optional NodeReferenceData parent_ptr = 4;
  NodeReferenceData package_ptr = 5;
  NodeReferenceData bench_ptr = 6;
  optional NodeReferenceData template_ptr = 7;
  optional int64 templated_epoch = 8;
  int64 revision = 10;
  google.protobuf.Timestamp created_at = 11;
  int64 created_epoch = 12;
  google.protobuf.Timestamp updated_at = 13;
  int64 updated_epoch = 14;
  optional google.protobuf.Timestamp deleted_at = 15;
  optional google.protobuf.Timestamp archived_at = 16;
  optional NodeReferenceData created_by_ptr = 21;
  optional NodeReferenceData updated_by_ptr = 22;
  repeated int32 set_properties = 29;
  ViewType type = 30;
  string name = 31;
  optional string title = 32;
  optional TextData text = 33;
  string order_key = 34;
  optional IconData icon = 35;
  optional TypeInfoData value_type = 40;
  optional google.protobuf.Struct value_packed = 41;
  optional NodeReferenceData node_ptr = 42;
  optional Variant variant = 50;
  optional FontData font = 51;
  optional OffsetData position = 60;
  optional BoxData size = 61;
  optional OffsetData margin = 62;
  optional OffsetData padding = 63;
  optional Orientation orientation = 64;
  optional Alignment alignment = 65;
  optional TransformData transform = 66;
  optional SelectionData selection = 70;
  optional SelectionData focus = 71;
  optional SelectionData expansion = 72;
  optional bool is_visible = 80;
  optional bool is_disabled = 81;
  optional bool is_input = 82;
  optional bool is_inline = 83;
  optional bool is_template = 84;
  optional bool is_loading = 90;
}

message SomeNodeData {
  oneof node {
    BenchData bench = 1;
    EnvironmentData environment = 2;
    BranchData branch = 3;
    PackageData package = 4;
    DependencyData dependency = 5;
    UpgradeData upgrade = 6;
    SpaceData space = 7;
    LinkData link = 8;
    SkipData skip = 9;
    IssueData issue = 10;
    BlockData block = 11;
    TriggerData trigger = 12;
    FieldData field = 13;
    QueryData query = 14;
    ViewData view = 15;
    StepData step = 16;
    BadgeData badge = 17;
    RoleData role = 18;
    IdentityData identity = 19;
    MembershipData membership = 20;
    InviteData invite = 21;
    SessionData session = 22;
    RunData run = 23;
    SignalData signal = 24;
    LogData log = 25;
    NotificationData notification = 26;
    MessageData message = 27;
    RecordData record = 28;
    ServerData server = 29;
    StoreData store = 30;
    MachineData machine = 31;
    DriveData drive = 32;
    BlobData blob = 33;
    HandleData handle = 34;
    UserData user = 35;
    OrganizationData organization = 36;
    ClientData client = 37;
  };
}

