syntax = "proto3";

package symbolx.bench;

import "proto/common.proto";
import "proto/lang.proto";

message RunRequest {
	GraphScopeData scope = 1;
	NodeReferenceData computer_ptr = 2;
	NodeReferenceData thread_ptr = 3; // :RunRouting
	repeated NodeReferenceData run_ptrs = 10;
}
message RunResponse {
}
  
// A Runtime for running a Bench somewhere (like on a Computer or a Client).
// The Runtime may run multiple processes/threads to process its Runs in Sessions in parallel.
service Runtime {
	option (kind) = INTERNAL; // :ServiceKind
  
	// Process Runs. Returns immediately after queuing.
	rpc Run(RunRequest) returns (RunResponse);
}
   