syntax = "proto3";

package symbolx.bench;

import "proto/common.proto";
import "proto/lang.proto";

//
// Runtime
//

message RunRequest {
	NodeReferenceData run_ptr = 1;
}
message RunResponse {
}
  
// A Runtime for running a Bench somewhere (like on a Computer or a Client).
// The Runtime may run multiple processes/threads to process its Runs in Sessions in parallel.
service Runtime {
	option (kind) = INTERNAL; // :ServiceKind
  
	// Process a new/existing Run in this runtime. If not blocking, returns immediately on queuing.
	rpc Run(RunRequest) returns (RunResponse);
}
   