syntax = "proto3";

package symbolx.bench;

import "proto/common.proto";
import "proto/lang.proto";

//
// Graph
//

message GetNodesRequest {
  GraphScope scope = 1;
  repeated NodeReferenceData roots = 2;  // must be of same type
  optional ReadOptionsData options = 3;
  optional bool no_cache = 4;
}
message GetNodesResponse {
  // Nodes are in pre-order (parent before children) traversal.
  repeated SomeNodeData nodes = 1;
  uint64 epoch = 2;
  string query_token = 3;
}

message SearchNodesRequest {
  GraphScope scope = 1;
  NodeType node_type = 2;
  repeated NodeReferenceData bases = 3;
  optional ExpressionData filter = 4;
  repeated ExpressionData sort = 5;
  optional int32 first = 6;
  optional int32 skip = 7;
  optional string after = 8;
  optional ReadOptionsData options = 9;
  optional bool count = 10;
  optional bool no_cache = 11;
}
message SearchNodesResponse {
  // Nodes in pre-order (parent before children) traversal.
  repeated SomeNodeData nodes = 1;
  repeated NodeReferenceData roots = 2;
  repeated string cursors = 3;
  optional string start_cursor = 4;
  optional int32 total = 5;
  uint64 epoch = 6;
  string query_token = 7;
}

message AggregateNodesRequest {
  GraphScope scope = 1;
  NodeType node_type = 2;
  repeated NodeReferenceData bases = 3;
  optional ExpressionData filter = 4;
  repeated ExpressionData sort = 5;
  ExpressionData aggregation = 6;
  optional bool no_cache = 7;
}
message AggregateNodesResponse {
  AggregationData aggregation = 1;
  uint64 epoch = 2;
  string query_token = 3;
}

message WatchEditsRequest {
  string query_token = 1;
  optional uint64 since_epoch = 2;
}
message WatchEditsResponse {
  repeated EditData edits = 1;
  repeated EditData cascaded_edits = 2;
  uint64 epoch = 3;
}

message WatchAggregationRequest {
  string query_token = 1;
  optional uint64 since_epoch = 2;
}
message WatchAggregationResponse {
  AggregationData aggregation = 1;
  uint64 epoch = 2;
}

message CommitTransactionRequest {
  GraphScope scope = 1;
  string id = 2;
  repeated EditData edits = 3;
  optional SessionContextData context = 4;
}
message CommitTransactionResponse {
  repeated int64 revisions = 1;
  repeated EditData cascaded_edits = 2; 
  uint64 epoch = 3;
}

message FlushTransactionRequest {
  GraphScope scope = 1;
  string id = 2;
  repeated EditData edits = 3;
}
message FlushTransactionResponse {
  repeated int64 revisions = 1;
  repeated EditData cascaded_edits = 2; 
  uint64 epoch = 3;
}

message CompleteTransactionRequest {
  GraphScope scope = 1;
  string id = 2;
}
message CompleteTransactionResponse {
}

message CommitCompletedTransactionRequest {
  GraphScope scope = 1;
  string transaction_id = 2;
}
message CommitCompletedTransactionResponse {
}

message CancelTransactionRequest {
  GraphScope scope = 1;
  string transaction_id = 2;
}
message CancelTransactionResponse {
}

// Common service definition for global and bench-local :GraphIO
service GraphIO {
  // Get nodes (of the same root type) in this graph. Error if any node is not found/accessible.
  rpc GetNodes(GetNodesRequest) returns (GetNodesResponse);
  // Search nodes in this graph.
  rpc SearchNodes(SearchNodesRequest) returns (SearchNodesResponse);
  // Aggregate nodes in this graph.
  rpc AggregateNodes(AggregateNodesRequest) returns (AggregateNodesResponse);
  // Receive any relevant node edits for a get/search query.
  rpc WatchEdits(WatchEditsRequest) returns (stream WatchEditsResponse);
  // Receive any relevant aggregation updates for an aggregation query.
  rpc WatchAggregation(WatchAggregationRequest) returns (stream WatchAggregationResponse);
  // Commit a new or pending completed transaction to this graph.
  rpc CommitTransaction(CommitTransactionRequest) returns (CommitTransactionResponse);
  // Begins or extends a pending transaction. Edits are additive.
  rpc FlushTransaction(FlushTransactionRequest) returns (FlushTransactionResponse);
  // Prepares a transaction to commit to this graph. Nothing is committed, but no further edits are allowed.
  rpc CompleteTransaction(CompleteTransactionRequest) returns (CompleteTransactionResponse);
  // Rolls back a pending or completed transaction to this graph.
  rpc CancelTransaction(CancelTransactionRequest) returns (CancelTransactionResponse);
}


//
// Supervisor
//

message ClientDataIn {
  optional string id = 2;
  ClientType type = 30;
  string name = 32;
  optional string device_type = 40;
  optional string device_name = 41;
  optional string operating_system = 42;
  optional string browser_name = 43;
  optional string browser_version = 44;
  optional string place_id = 45;
  optional string access_token = 50;
  optional NodeReferenceData space_ptr = 60;
}

message SignupUserRequest {
  optional string id = 1;
  string slug = 2;
  optional string name = 3;
  string email = 4 [(sensitive) = true];
  string password = 5 [(sensitive) = true];
  ClientDataIn client = 6;
}
message SignupUserResponse {
  UserData user = 1;
  ClientData client = 2;
  string access_token = 3 [(sensitive) = true];
}

message ChangeUserPasswordRequest {
  string old_password = 1 [(sensitive) = true];
  string new_password = 2 [(sensitive) = true];
}
message ChangeUserPasswordResponse {
  UserData user = 1;
  uint64 epoch = 2;
}

message LoginUserRequest {
  oneof user {
    string id = 1;
    string slug = 2;
    string email = 3 [(sensitive) = true];
  }
  string password = 4 [(sensitive) = true];
  ClientDataIn client = 5;
}
message LoginUserResponse {
  UserData user = 1;
  ClientData client = 2;
  string access_token = 3 [(sensitive) = true];
}

message LogoutUserRequest {
  // If specified, log out only the specified clients (instead of the current client).
  repeated NodeReferenceData clients = 1;
  // If specified, log out all clients (incl. current).
  optional bool logout_all = 2;
}
message LogoutUserResponse {
}

message CreateOrganizationRequest {
  OrganizationData organization = 1;
}
message CreateOrganizationResponse {
  OrganizationData organization = 1;
  uint64 epoch = 2;
}

message CreateBenchRequest {
  NodeReferenceData owner = 1;
  string slug = 2;
  Region region = 3;
  bool is_main = 4;
}
message CreateBenchResponse {
  BenchData bench = 1;
}

message GetHostRequest {
  oneof bench {
    string id = 1;
    string slug = 2;
  }
}
message GetHostResponse {
  string connection_uri = 1;
  NodeReferenceData bench = 2;
}

// Global control plane: create & manage the global stuff like Benches, Users, etc..
service Supervisor {
  option (kind) = PUBLIC; // :ServiceKind

  //
  // Global IO for non-source nodes outside Benches :GraphIO
  //

  rpc GetNodes(GetNodesRequest) returns (GetNodesResponse);
  rpc SearchNodes(SearchNodesRequest) returns (SearchNodesResponse);
  rpc AggregateNodes(AggregateNodesRequest) returns (AggregateNodesResponse);
  rpc WatchEdits(WatchEditsRequest) returns (stream WatchEditsResponse);
  rpc WatchAggregation(WatchAggregationRequest) returns (stream WatchAggregationResponse);
  rpc CommitTransaction(CommitTransactionRequest) returns (CommitTransactionResponse);
  rpc FlushTransaction(FlushTransactionRequest) returns (FlushTransactionResponse);
  rpc CompleteTransaction(CompleteTransactionRequest) returns (CompleteTransactionResponse);
  rpc CancelTransaction(CancelTransactionRequest) returns (CancelTransactionResponse);

  //
  // User management
  //

  // Create user account.
  rpc SignupUser(SignupUserRequest) returns (SignupUserResponse);
  // Change user password.
  rpc ChangeUserPassword(ChangeUserPasswordRequest) returns (ChangeUserPasswordResponse);
  // Login user account with a new or existing client.
  rpc LoginUser(LoginUserRequest) returns (LoginUserResponse);
  // Logout user account with the current or other owned clients.
  rpc LogoutUser(LogoutUserRequest) returns (LogoutUserResponse);

  //
  // Bench management
  //

  // Create a Bench. If this is the first Bench for the owner, we activate the User/Organization.
  rpc CreateBench(CreateBenchRequest) returns (CreateBenchResponse);
  // Gets Bench host information.
  rpc GetHost(GetHostRequest) returns (GetHostResponse);
}

//
// Host
//

// The Host provides the operating system of a Bench.
service Host {
  option (kind) = PUBLIC; // :ServiceKind
  
  //
  // General IO for nodes in this Bench (only) :GraphIO
  //

  rpc GetNodes(GetNodesRequest) returns (GetNodesResponse);
  rpc SearchNodes(SearchNodesRequest) returns (SearchNodesResponse);
  rpc AggregateNodes(AggregateNodesRequest) returns (AggregateNodesResponse);
  rpc WatchEdits(WatchEditsRequest) returns (stream WatchEditsResponse);
  rpc WatchAggregation(WatchAggregationRequest) returns (stream WatchAggregationResponse);
  rpc CommitTransaction(CommitTransactionRequest) returns (CommitTransactionResponse);
  rpc FlushTransaction(FlushTransactionRequest) returns (FlushTransactionResponse);
  rpc CompleteTransaction(CompleteTransactionRequest) returns (CompleteTransactionResponse);
  rpc CancelTransaction(CancelTransactionRequest) returns (CancelTransactionResponse);

  // ...
}
