syntax = "proto3";

package symbol.bench;

import "google/protobuf/struct.proto";
import "proto/common.proto";
import "proto/lang.proto";

//
// Supervisor
//

message ClientDataIn {
  ClientType type = 30;
  optional string name = 32;
  optional string device_type = 40;
  optional string device_name = 41;
  optional string operating_system = 42;
  optional string browser_name = 43;
  optional string browser_version = 44;
  optional string place_id = 45;
  optional string access_token = 50;
  optional NodeReferenceData space_ptr = 60;
}

message SignupUserRequest {
  string slug = 2;
  optional string name = 3;
  string email = 4 [(sensitive) = true];
  string password = 5 [(sensitive) = true];
  Region region = 6;
  ClientDataIn client = 9;
  optional bool activate = 10;
}
message SignupUserResponse {
  UserData user = 1;
  ClientData client = 2;
  string access_token = 3 [(sensitive) = true];
}

message ChangeUserPasswordRequest {
  string old_password = 1 [(sensitive) = true];
  string new_password = 2 [(sensitive) = true];
}
message ChangeUserPasswordResponse {
  UserData user = 1;
  uint64 epoch = 2;
}

message LoginUserRequest {
  oneof user {
    string id = 1;
    string slug = 2;
    string email = 3 [(sensitive) = true];
  }
  string password = 4 [(sensitive) = true];
  ClientDataIn client = 5;
}
message LoginUserResponse {
  UserData user = 1;
  ClientData client = 2;
  string access_token = 3 [(sensitive) = true];
}

message LogoutUserRequest {
  // If specified, log out only the specified clients (instead of the current client).
  repeated NodeReferenceData clients = 1;
  // If specified, log out all clients (incl. current).
  optional bool logout_all = 2;
}
message LogoutUserResponse {
}

message CreateOrganizationRequest {
  OrganizationData organization = 1;
}
message CreateOrganizationResponse {
  OrganizationData organization = 1;
  uint64 epoch = 2;
}

message ResolveHostsRequest {
  message BenchKey {
    oneof bench {
      string id = 1;
      string slug = 2;
    }
  }
  repeated BenchKey benches = 1;
}
message ResolveHostsResponse {
  message HostInfo {
    string domain = 1;
    int32 grpc_port = 2;
    int32 grpc_web_port = 3;
    bool ssl = 4;
    NodeReferenceData bench = 5;
  }
  repeated HostInfo hosts = 1;
}

// Control plane: create & manage the global stuff like Benches, Users, etc..
service Supervisor {
  option (kind) = PUBLIC; // :ServiceKind

  // Create User.
  rpc SignupUser(SignupUserRequest) returns (SignupUserResponse);
  // Change User.password.
  rpc ChangeUserPassword(ChangeUserPasswordRequest) returns (ChangeUserPasswordResponse);
  // Login User with a new or existing Client.
  rpc LoginUser(LoginUserRequest) returns (LoginUserResponse);
  // Logout User with the current or other owned Clients.
  rpc LogoutUser(LogoutUserRequest) returns (LogoutUserResponse);

  // Gets Bench host information.
  rpc ResolveHosts(ResolveHostsRequest) returns (ResolveHostsResponse);
}

//
// Host
//

message QueryRequest {
  ScopeData scope = 1;
  // The Query to execute.
  QueryData query = 2;
}
message QueryResponse {
  // The result of the Query.
  QueryResultData result = 1;
}

message SubscribeRequest {
  QueryData query = 1;
}
message SubscribeResponse {
  // The result of the Query.
  QueryUpdateData update = 1;
}

message CommitRequest {
  ScopeData scope = 1;
  repeated ChangeData changes = 3;
}
message CommitResponse {
  uint64 epoch = 3;
  repeated ChangeResultData results = 4;
}

message UploadFilesRequest { 
  ScopeData scope = 1;
  repeated FileData files = 2;
}

message UploadFilesResponse {
  message UploadHandle {
    FileData file = 1;
    string post_url = 2;
    google.protobuf.Struct fields = 3;
    string get_url = 4;
  }
  repeated UploadHandle handles = 1; // handles for each valid file upload
}

message DownloadFilesRequest {
  ScopeData scope = 1;
  repeated NodeReferenceData files = 2;
}

message DownloadFilesResponse {
  message DownloadHandle {
    FileData file = 1;
    string get_url = 2;
  }
  repeated DownloadHandle handles = 1; // handles for each valid file download
}

// A Host provides the operating system of a Bench.
service Host {
  option (kind) = PUBLIC; // :ServiceKind
  
  //
  // Graph
  //

  rpc Query(QueryRequest) returns (QueryResponse);
  rpc Subscribe(SubscribeRequest) returns (stream SubscribeResponse);
  rpc Commit(CommitRequest) returns (CommitResponse);

  // 
  // Files? 
  //

  // 'Upload' some files (get URLs to upload them to). Handles may be incomplete.
  rpc UploadFiles(UploadFilesRequest) returns (UploadFilesResponse);
  // 'Download' some files (get URLs to download them from). Handles may be incomplete.
  rpc DownloadFiles(DownloadFilesRequest) returns (DownloadFilesResponse);
}
