[package]
name = "tspp_query"
description = "TS++ Query"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
tspp_artifact = { workspace = true }
tspp_core = { workspace = true }
tspp_dir = { workspace = true }
tspp_source = { workspace = true }
tspp_serde = { workspace = true }
tspp_repository = { path = "../repository", default-features = false }

# general
parking_lot = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
# language
tspp_session = { workspace = true, features = ["native"] }
tspp_workspace = { workspace = true, features = ["native"] }

# general
futures = { workspace = true, features = ["executor"] }
indexmap = { workspace = true }
libtest-mimic = { workspace = true }
pulldown-cmark = { workspace = true }

[[test]]
name = "fixture"
path = "tests/fixture/main.rs"
harness = false

[lints]
workspace = true
