// generated by generate-bindings: do not edit

use crate::diagnostic::RuntimeStatus;
use crate::host::abi::location::{LocationLastKnownResponse, LocationServicesResponse};
use crate::host::apple::abi::ingress::destack_host_ios_notify_location_sample as runtime_notify_location_sample;
use crate::host::apple::abi::location::{
    destack_host_ios_location_last_known as runtime_location_last_known,
    destack_host_ios_location_services_enabled as runtime_location_services_enabled,
    destack_host_ios_location_watch_close as runtime_location_watch_close,
    destack_host_ios_location_watch_open as runtime_location_watch_open,
};
use crate::platform::abi::NativeStringRef;
use crate::platform::os::{LocationSampleValue, LocationWatchOptions};

/// Forward the `services_enabled` location request through the ABI artifact.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn destack_host_ios_location_services_enabled(
    session_handle: u64,
    response: *mut LocationServicesResponse,
) -> u32 {
    unsafe { runtime_location_services_enabled(session_handle, response) }
}

/// Forward the `last_known` location request through the ABI artifact.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn destack_host_ios_location_last_known(
    session_handle: u64,
    response: *mut LocationLastKnownResponse,
) -> u32 {
    unsafe { runtime_location_last_known(session_handle, response) }
}

/// Forward the `watch_open` location request through the ABI artifact.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn destack_host_ios_location_watch_open(
    session_handle: u64,
    watch_id: NativeStringRef,
    options: LocationWatchOptions,
) -> u32 {
    unsafe { runtime_location_watch_open(session_handle, watch_id, options) }
}

/// Forward the `watch_close` location request through the ABI artifact.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn destack_host_ios_location_watch_close(
    session_handle: u64,
    watch_id: NativeStringRef,
) -> u32 {
    unsafe { runtime_location_watch_close(session_handle, watch_id) }
}

/// Forward the `notify_location_sample` ingress through the ABI artifact.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn destack_host_ios_notify_location_sample(
    runtime_id: u64,
    watch_id: NativeStringRef,
    sample: LocationSampleValue,
) -> RuntimeStatus {
    unsafe { runtime_notify_location_sample(runtime_id, watch_id, sample) }
}
