[package]
name = "dyst_javascript_compiler"
description = "Dyst JavaScript Compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"
doctest = false

[dependencies]
dyst_ast = { workspace = true }
dyst_diagnostic = { workspace = true }
dyst_dir = { workspace = true }
dyst_fir = { workspace = true }
dyst_javascript_ast = { workspace = true }
dyst_mir = { workspace = true }
dyst_module = { workspace = true }
dyst_session = { workspace = true }
dyst_source = { workspace = true }

destack_unicode = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
