[project]
name = "destack"
version = "2025.08.01.22"
description = "Destack Language Definition (Internal)"
authors = [{ name = "Symbol Industries", email = "hello@symbol.industries" }]
requires-python = ">=3.13"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["destack"]
exclude = ["venv*", "requirements*", "*.egg-info"]

[tool.uv]
package = true

[tool.pytest_env]
ENVIRONMENT = "test"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_test_loop_scope = "session"
python_files = "test/**/*.py test/*.py"
python_classes = "!TestProfile"
pythonpath = ["."]
log_cli = true
addopts = [
	'-rP',
	"-vv",
	"--import-mode=importlib",
	"--color=yes",
	'--strict-markers',
]
markers = []
filterwarnings = ["ignore::DeprecationWarning", "ignore::UserWarning"]

