[package]
name = "destack-rs"
description = "Rust compatibility crate for Destack"
version = "0.55.3"
edition = "2024"
authors = ["Symbol Industries"]
license = "MIT"
rust-version = "1.89"
readme = "README.md"
repository = "https://github.com/destack-sh/destack"
homepage = "https://github.com/destack-sh/destack"
documentation = "https://docs.rs/destack-rs"
keywords = ["destack", "typescript", "compiler", "runtime"]
categories = ["compilers", "development-tools"]

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
destack = { version = "=0.55.3", path = "../.." }

[workspace]
