/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, jsonBigint, jsonField, jsonObject } from "../../../protocol/serde.js";

/** Stable RPC service identifier. */
export type ServiceId = bigint;

export const ServiceId = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: ServiceId): void {
        encodeServiceId(writer, value);
    },

    /** Decode one ServiceId. */
    decode(reader: BinaryReader): ServiceId {
        return decodeServiceId(reader);
    },

    /** Return this value as JSON. */
    toJson(value: ServiceId): Json {
        return toJsonServiceId(value);
    },

    /** Return one ServiceId from one JSON value. */
    fromJson(value: Json): ServiceId {
        return fromJsonServiceId(value);
    },
};

/** Encode one ServiceId. */
export function encodeServiceId(writer: BinaryWriter, value: ServiceId): void {
    writer.writeUnsigned(value);
}

/** Decode one ServiceId. */
export function decodeServiceId(reader: BinaryReader): ServiceId {
    return reader.readUnsigned();
}

/** Return one JSON value for one ServiceId. */
export function toJsonServiceId(value: ServiceId): Json {
    return value.toString();
}

/** Return one ServiceId from one JSON value. */
export function fromJsonServiceId(value: Json): ServiceId {
    return jsonBigint(value);
}

/** Stable canonical service schema fingerprint. */
export type ServiceFingerprint = bigint;

export const ServiceFingerprint = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: ServiceFingerprint): void {
        encodeServiceFingerprint(writer, value);
    },

    /** Decode one ServiceFingerprint. */
    decode(reader: BinaryReader): ServiceFingerprint {
        return decodeServiceFingerprint(reader);
    },

    /** Return this value as JSON. */
    toJson(value: ServiceFingerprint): Json {
        return toJsonServiceFingerprint(value);
    },

    /** Return one ServiceFingerprint from one JSON value. */
    fromJson(value: Json): ServiceFingerprint {
        return fromJsonServiceFingerprint(value);
    },
};

/** Encode one ServiceFingerprint. */
export function encodeServiceFingerprint(writer: BinaryWriter, value: ServiceFingerprint): void {
    writer.writeUnsigned(value);
}

/** Decode one ServiceFingerprint. */
export function decodeServiceFingerprint(reader: BinaryReader): ServiceFingerprint {
    return reader.readUnsigned();
}

/** Return one JSON value for one ServiceFingerprint. */
export function toJsonServiceFingerprint(value: ServiceFingerprint): Json {
    return value.toString();
}

/** Return one ServiceFingerprint from one JSON value. */
export function fromJsonServiceFingerprint(value: Json): ServiceFingerprint {
    return jsonBigint(value);
}
