[package]
name = "dyst_language_token"
description = "Dyst Language Tokens"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"

[dependencies]
dyst_language_source = { workspace = true }
destack_library_unicode = { workspace = true }

[dev-dependencies]
destack_library_file = { workspace = true }

quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
criterion = { workspace = true }
pprof = { workspace = true }

[[bench]]
name = "dyst_language_token"
harness = false

[lints]
workspace = true
