[package]
name = "dyst_token"
description = "Dyst Tokens"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"
doctest = true

[dependencies]
dyst_source = { workspace = true }
destack_unicode = { workspace = true }

[dev-dependencies]
destack_file = { workspace = true }

quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
criterion = { workspace = true }
pprof = { workspace = true }

[[bench]]
name = "dyst_token"
harness = false

[lints]
workspace = true
