// generated by generate-bindings: stub, do not edit

#![allow(clippy::missing_safety_doc)]
use crate::diagnostic::{RuntimeError, RuntimeResult};
use crate::platform::PlatformError;

use crate::runtime::BindingCallContext;

use crate::platform::resource;
use crate::platform::thread::{ThreadCpuSet, ThreadOptions};

/// Simulation binding for `destack.thread.local.create`.
pub(crate) unsafe fn destack_thread_local_create(
    _binding: &BindingCallContext,
    out: *mut resource::ThreadLocalKey,
) -> RuntimeResult<()> {
    if out.is_null() {
        return Err(RuntimeError::from(PlatformError::null_pointer("out")).boxed());
    }
    let _ = out;

    Err(RuntimeError::from(PlatformError::not_supported("destack.thread.local.create")).boxed())
}

/// Simulation binding for `destack.thread.local.delete`.
pub(crate) unsafe fn destack_thread_local_delete(
    _binding: &BindingCallContext,
    key: resource::ThreadLocalKey,
) -> RuntimeResult<()> {
    let _ = key;

    Err(RuntimeError::from(PlatformError::not_supported("destack.thread.local.delete")).boxed())
}

/// Simulation binding for `destack.thread.local.get`.
pub(crate) unsafe fn destack_thread_local_get(
    _binding: &BindingCallContext,
    out: *mut u64,
    key: resource::ThreadLocalKey,
) -> RuntimeResult<()> {
    if out.is_null() {
        return Err(RuntimeError::from(PlatformError::null_pointer("out")).boxed());
    }
    let _ = (out, key);

    Err(RuntimeError::from(PlatformError::not_supported("destack.thread.local.get")).boxed())
}

/// Simulation binding for `destack.thread.local.set`.
pub(crate) unsafe fn destack_thread_local_set(
    _binding: &BindingCallContext,
    key: resource::ThreadLocalKey,
    argument_value: u64,
) -> RuntimeResult<()> {
    let _ = (key, argument_value);

    Err(RuntimeError::from(PlatformError::not_supported("destack.thread.local.set")).boxed())
}

/// Simulation binding for `destack.thread.sched.getAffinity`.
pub(crate) unsafe fn destack_thread_get_affinity(
    _binding: &BindingCallContext,
    out: *mut ThreadCpuSet,
    handle: resource::ThreadHandle,
) -> RuntimeResult<()> {
    if out.is_null() {
        return Err(RuntimeError::from(PlatformError::null_pointer("out")).boxed());
    }
    let _ = (out, handle);

    Err(RuntimeError::from(PlatformError::not_supported(
        "destack.thread.sched.getAffinity",
    ))
    .boxed())
}

/// Simulation binding for `destack.thread.sched.getPriority`.
pub(crate) unsafe fn destack_thread_get_priority(
    _binding: &BindingCallContext,
    out: *mut i32,
    handle: resource::ThreadHandle,
) -> RuntimeResult<()> {
    if out.is_null() {
        return Err(RuntimeError::from(PlatformError::null_pointer("out")).boxed());
    }
    let _ = (out, handle);

    Err(RuntimeError::from(PlatformError::not_supported(
        "destack.thread.sched.getPriority",
    ))
    .boxed())
}

/// Simulation binding for `destack.thread.sched.setAffinity`.
pub(crate) unsafe fn destack_thread_set_affinity(
    _binding: &BindingCallContext,
    handle: resource::ThreadHandle,
    cpus: ThreadCpuSet,
) -> RuntimeResult<()> {
    let _ = (handle, cpus);

    Err(RuntimeError::from(PlatformError::not_supported(
        "destack.thread.sched.setAffinity",
    ))
    .boxed())
}

/// Simulation binding for `destack.thread.sched.setPriority`.
pub(crate) unsafe fn destack_thread_set_priority(
    _binding: &BindingCallContext,
    handle: resource::ThreadHandle,
    priority: i32,
) -> RuntimeResult<()> {
    let _ = (handle, priority);

    Err(RuntimeError::from(PlatformError::not_supported(
        "destack.thread.sched.setPriority",
    ))
    .boxed())
}

/// Simulation binding for `destack.thread.spawn.detach`.
pub(crate) unsafe fn destack_thread_detach(
    _binding: &BindingCallContext,
    handle: resource::ThreadHandle,
) -> RuntimeResult<()> {
    let _ = handle;

    Err(RuntimeError::from(PlatformError::not_supported("destack.thread.spawn.detach")).boxed())
}

/// Simulation binding for `destack.thread.spawn.join`.
pub(crate) unsafe fn destack_thread_join(
    _binding: &BindingCallContext,
    out: *mut u64,
    handle: resource::ThreadHandle,
) -> RuntimeResult<()> {
    if out.is_null() {
        return Err(RuntimeError::from(PlatformError::null_pointer("out")).boxed());
    }
    let _ = (out, handle);

    Err(RuntimeError::from(PlatformError::not_supported("destack.thread.spawn.join")).boxed())
}

/// Simulation binding for `destack.thread.spawn.start`.
pub(crate) unsafe fn destack_thread_spawn(
    _binding: &BindingCallContext,
    out: *mut resource::ThreadHandle,
    entry: resource::ThreadEntryHandle,
    argument: u64,
    options: ThreadOptions,
) -> RuntimeResult<()> {
    if out.is_null() {
        return Err(RuntimeError::from(PlatformError::null_pointer("out")).boxed());
    }
    let _ = (out, entry, argument, options);

    Err(RuntimeError::from(PlatformError::not_supported("destack.thread.spawn.start")).boxed())
}

/// Simulation binding for `destack.thread.wait.addressWait`.
pub(crate) unsafe fn destack_thread_address_wait(
    _binding: &BindingCallContext,
    address: u64,
    expected: u32,
    timeoutns: u64,
) -> RuntimeResult<()> {
    let _ = (address, expected, timeoutns);

    Err(RuntimeError::from(PlatformError::not_supported(
        "destack.thread.wait.addressWait",
    ))
    .boxed())
}

/// Simulation binding for `destack.thread.wait.addressWakeAll`.
pub(crate) unsafe fn destack_thread_address_wake_all(
    _binding: &BindingCallContext,
    address: u64,
) -> RuntimeResult<()> {
    let _ = address;

    Err(RuntimeError::from(PlatformError::not_supported(
        "destack.thread.wait.addressWakeAll",
    ))
    .boxed())
}

/// Simulation binding for `destack.thread.wait.addressWakeOne`.
pub(crate) unsafe fn destack_thread_address_wake_one(
    _binding: &BindingCallContext,
    address: u64,
) -> RuntimeResult<()> {
    let _ = address;

    Err(RuntimeError::from(PlatformError::not_supported(
        "destack.thread.wait.addressWakeOne",
    ))
    .boxed())
}
