[package]
name = "destack_bridge_language"
description = "Destack language bridge contract"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
readme = "README.md"
repository = "https://github.com/destack-sh/destack"
homepage = "https://github.com/destack-sh/destack"

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
destack_bridge_language_macros.workspace = true
destack_repository.workspace = true
destack_session.workspace = true

[lints]
workspace = true
