use std::collections::{BTreeMap, BTreeSet};

use destack_dir::EnumBackingType;

use super::codegen::ModuleCodegen;
use super::{binding_type_requires_abi, collect_binding_type_domains};
use crate::platform::model::{
    BindingEnumValue, BindingType, ConstantEntry, ConstantValue, ModuleAbiTypes,
};

impl ModuleAbiTypes {
    /// Render ABI type definitions for one runtime module.
    pub(crate) fn render(
        &self,
        module: &str,
        constants: Option<&BTreeMap<String, ConstantEntry>>,
    ) -> String {
        AbiRenderer::new(module, self, constants).render()
    }
}

/// Stateful ABI renderer for one binding module.
struct AbiRenderer<'a> {
    /// The binding module being rendered.
    module: &'a str,
    /// The collected ABI types for this module.
    types: &'a ModuleAbiTypes,
    /// Optional exported constants for this module.
    constants: Option<&'a BTreeMap<String, ConstantEntry>>,
    /// Rust naming and type rendering helpers.
    codegen: ModuleCodegen<'a>,
    /// Accumulated rendered output.
    output: String,
}

impl<'a> AbiRenderer<'a> {
    /// Create one ABI renderer for one binding module.
    fn new(
        module: &'a str,
        types: &'a ModuleAbiTypes,
        constants: Option<&'a BTreeMap<String, ConstantEntry>>,
    ) -> Self {
        Self {
            module,
            types,
            constants,
            codegen: ModuleCodegen::new(module),
            output: String::new(),
        }
    }
}

impl AbiRenderer<'_> {
    /// Render ABI type definitions for this binding module.
    fn render(mut self) -> String {
        let domain = self.module;
        let codegen = self.codegen;
        let structs = &self.types.structs;
        let newtypes = &self.types.newtypes;
        let enums = &self.types.enums;
        let tagged_unions = &self.types.tagged_unions;
        let aggregate_type_registrations =
            collect_named_aggregate_registrations(domain, structs, newtypes, tagged_unions);
        let has_named_types = !newtypes.is_empty()
            || !enums.is_empty()
            || !structs.is_empty()
            || !tagged_unions.is_empty();
        let output = &mut self.output;
        let needs_abi = newtypes.values().any(|binding_type| {
            let BindingType::Newtype { inner, .. } = binding_type else {
                return false;
            };
            binding_type_requires_abi(inner)
        }) || structs
            .values()
            .any(|binding_type| binding_type_requires_abi(binding_type))
            || tagged_unions
                .values()
                .any(|binding_type| binding_type_requires_abi(binding_type));
        let mut type_domains = BTreeSet::new();
        for binding_type in newtypes.values() {
            collect_binding_type_domains(domain, binding_type, &mut type_domains);
        }
        for binding_type in structs.values() {
            collect_binding_type_domains(domain, binding_type, &mut type_domains);
        }
        for binding_type in enums.values() {
            collect_binding_type_domains(domain, binding_type, &mut type_domains);
        }
        for binding_type in tagged_unions.values() {
            collect_binding_type_domains(domain, binding_type, &mut type_domains);
        }

        output.push_str("// generated by generate-bindings: do not edit\n\n");
        output.push_str("#![allow(dead_code)]\n");
        output.push_str("#![allow(unused_imports)]\n");
        output.push_str("#![allow(unreachable_pub)]\n\n");
        output.push_str("#![allow(clippy::bind_instead_of_map)]\n\n");
        output.push_str("#![allow(clippy::enum_variant_names)]\n\n");
        output.push_str("#![allow(clippy::len_zero)]\n\n");
        if needs_abi {
            output.push_str("use crate::platform::abi::{BindingAbi, NativeAbi, VmAbi};\n");
        }
        let needs_vm_value_codec = newtypes.values().any(|binding_type| {
            let BindingType::Newtype { inner, .. } = binding_type else {
                return false;
            };
            !binding_type_requires_abi(inner)
        }) || !enums.is_empty();
        let needs_vm_aggregate_codec = !structs.is_empty()
            || newtypes.values().any(|binding_type| {
                let BindingType::Newtype { inner, .. } = binding_type else {
                    return false;
                };
                binding_type_requires_abi(inner)
            })
            || !tagged_unions.is_empty();
        if needs_vm_value_codec || needs_vm_aggregate_codec {
            output.push_str("use crate::diagnostic::RuntimeError;\n");
            output.push_str("use crate::diagnostic::RuntimeResult;\n");
            output.push_str("use crate::platform::PlatformError as AbiPlatformError;\n");
        }
        if has_named_types {
            output.push_str(
                "use crate::platform::abi::{NativeSlice, NativeStringRef, NativeStringSlice};\n",
            );
            output.push_str(
                "use crate::platform::{NativeArray, NativeAbiCodec, VmAbiCodec, VmCollectionElement};\n",
            );
            output.push_str("use crate::runtime::BindingCallContext;\n");
        }
        if needs_vm_value_codec {
            output.push_str("use crate::platform::VmValueCodec;\n");
        }
        if needs_vm_aggregate_codec {
            output.push_str("use crate::platform::VmAggregateCodec;\n");
            output.push_str("use crate::platform::{VmArray, VmSlice};\n");
        }
        output.push_str("use destack_vm as vm;\n");
        if !newtypes.is_empty()
            || !enums.is_empty()
            || !structs.is_empty()
            || !tagged_unions.is_empty()
        {
            output.push_str("use serde::{Deserialize, Serialize};\n");
        }
        if !type_domains.is_empty() {
            let imports = type_domains
                .iter()
                .map(|domain| domain.as_str())
                .collect::<Vec<_>>()
                .join(", ");
            output.push_str(&format!("use crate::platform::{{{imports}}};\n"));
        }
        let mut alias_domains = BTreeSet::new();
        alias_domains.insert(domain.to_string());
        alias_domains.extend(type_domains.iter().cloned());
        for alias_domain in alias_domains {
            let alias = codegen.platform_domain_alias(alias_domain.as_str());
            output.push_str(&format!(
                "use crate::platform::{alias_domain} as {alias};\n"
            ));
        }
        if needs_abi
            || !newtypes.is_empty()
            || !enums.is_empty()
            || !structs.is_empty()
            || !tagged_unions.is_empty()
        {
            output.push_str("\n");
        }

        for (name, binding_type) in newtypes {
            let BindingType::Newtype { inner, .. } = binding_type else {
                panic!("expected newtype binding for {name}");
            };
            let requires_abi = binding_type_requires_abi(inner);
            let value_name = codegen.value_type_name(name);
            output.push_str(&format!("/// ABI newtype for {name}.\n"));
            if requires_abi {
                output.push_str("#[repr(C)]\n");
                output.push_str("#[derive(Debug, Clone, Copy)]\n");
                output.push_str(&format!("pub struct {name}Abi<A: BindingAbi>(\n"));
                output.push_str(&format!(
                    "    /// Inner value.\n    pub {},\n",
                    codegen.abi_struct_field_type(inner)
                ));
                output.push_str(");\n\n");
                output.push_str(&format!("pub type {name} = {name}Abi<NativeAbi>;\n"));
                output.push_str(&format!("pub type {name}Vm = {name}Abi<VmAbi>;\n\n"));
                let inner_vm_type = codegen.vm_type_for_binding(inner);
                output.push_str(&format!("impl VmAggregateCodec for {name}Abi<VmAbi> {{\n"));
                output.push_str(
                "    fn decode_with_context(context: &vm::ExternalReadContext<'_, '_>, value: vm::Word) -> RuntimeResult<Self> {\n",
            );
                output.push_str(&format!(
                "        Ok(Self(<{inner_vm_type} as VmAggregateCodec>::decode_with_context(context, value)?))\n"
            ));
                output.push_str("    }\n\n");
                output.push_str(
                "    fn encode_with_context(self, context: &mut vm::ExternalWriteContext<'_, '_>) -> RuntimeResult<vm::Word> {\n",
            );
                output.push_str(&format!(
                "        <{inner_vm_type} as VmAggregateCodec>::encode_with_context(self.0, context)\n"
            ));
                output.push_str("    }\n");
                output.push_str("}\n\n");
                output.push_str(&format!(
                    "impl VmCollectionElement for {name}Abi<VmAbi> {{}}\n\n"
                ));

                output.push_str(&format!("/// Value type for {name}.\n"));
                output.push_str("#[repr(transparent)]\n");
                output.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
                output.push_str(&format!("pub struct {value_name}(\n"));
                output.push_str(&format!(
                    "    /// Inner value.\n    pub {},\n",
                    codegen.owned_type_for_binding(inner)
                ));
                output.push_str(");\n\n");

                output.push_str(&format!(
                    "impl NativeAbiCodec for {name}Abi<NativeAbi> {{\n"
                ));
                output.push_str(&format!("    type Value = {value_name};\n\n"));
                output.push_str(
                "    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {\n",
            );
                output.push_str(&format!(
                    "        Ok({value_name}({}))\n",
                    codegen.render_native_into_value(inner, "self.0")
                ));
                output.push_str("    }\n\n");
                output.push_str(
                "    fn from_value(binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {\n",
            );
                output.push_str(&format!(
                    "        Self({})\n",
                    codegen.render_native_from_value(inner, "value.0")
                ));
                output.push_str("    }\n");
                output.push_str("}\n\n");

                output.push_str(&format!("impl VmAbiCodec for {name}Abi<VmAbi> {{\n"));
                output.push_str(&format!("    type Value = {value_name};\n\n"));
                output.push_str(
                "    fn into_value(self, context: &vm::ExternalReadContext<'_, '_>) -> RuntimeResult<<Self as VmAbiCodec>::Value> {\n",
            );
                output.push_str(&format!(
                    "        Ok({value_name}({}))\n",
                    codegen.render_vm_into_value(inner, "self.0")
                ));
                output.push_str("    }\n\n");
                output.push_str(
                "    fn from_value(context: &mut vm::ExternalWriteContext<'_, '_>, value: <Self as VmAbiCodec>::Value) -> RuntimeResult<Self> {\n",
            );
                output.push_str(&format!(
                    "        Ok(Self({}))\n",
                    codegen.render_vm_from_value(inner, "value.0")
                ));
                output.push_str("    }\n");
                output.push_str("}\n\n");

                continue;
            }

            let inner_type = codegen.abi_newtype_inner_type(inner);
            output.push_str("#[repr(transparent)]\n");
            output.push_str(
                "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n",
            );
            output.push_str(&format!("pub struct {name}(\n"));
            output.push_str(&format!("    /// Inner value.\n    pub {inner_type},\n"));
            output.push_str(");\n\n");
            output.push_str(&format!("pub type {name}Vm = {name};\n\n"));

            output.push_str(&format!("impl VmValueCodec for {name} {{\n"));
            output.push_str("    fn decode(value: vm::Word) -> RuntimeResult<Self> {\n");
            output.push_str(&format!(
                "        Ok(Self(<{inner_type} as VmValueCodec>::decode(value)?))\n"
            ));
            output.push_str("    }\n\n");
            output.push_str("    fn encode(self) -> vm::Word {\n");
            output.push_str(&format!(
                "        <{inner_type} as VmValueCodec>::encode(self.0)\n"
            ));
            output.push_str("    }\n");
            output.push_str("}\n\n");
            output.push_str(&format!("impl VmCollectionElement for {name} {{}}\n\n"));

            output.push_str(&format!("/// Value type for {name}.\n"));
            output.push_str(&format!("pub type {value_name} = {name};\n\n"));

            output.push_str(&format!("impl NativeAbiCodec for {name} {{\n"));
            output.push_str(&format!("    type Value = {value_name};\n\n"));
            output.push_str(
            "    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {\n",
        );
            output.push_str("        Ok(self)\n");
            output.push_str("    }\n\n");
            output.push_str(
            "    fn from_value(_binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {\n",
        );
            output.push_str("        value\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");

            output.push_str(&format!("impl VmAbiCodec for {name} {{\n"));
            output.push_str(&format!("    type Value = {value_name};\n\n"));
            output.push_str(
            "    fn into_value(self, _context: &vm::ExternalReadContext<'_, '_>) -> RuntimeResult<<Self as VmAbiCodec>::Value> {\n",
        );
            output.push_str("        Ok(self)\n");
            output.push_str("    }\n\n");
            output.push_str(
            "    fn from_value(_context: &mut vm::ExternalWriteContext<'_, '_>, value: <Self as VmAbiCodec>::Value) -> RuntimeResult<Self> {\n",
        );
            output.push_str("        Ok(value)\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");
        }

        for (name, binding_type) in enums {
            let BindingType::Enum {
                backing, variants, ..
            } = binding_type
            else {
                panic!("expected enum binding for {name}");
            };
            let repr = ModuleCodegen::enum_backing_repr(*backing);
            output.push_str(&format!("/// ABI enum for {name}.\n"));
            output.push_str(&format!("#[repr({repr})]\n"));
            output.push_str(
                "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]\n",
            );
            output.push_str(&format!("pub enum {name} {{\n"));
            for variant in variants {
                if let BindingEnumValue::Int(value) = variant.value {
                    output.push_str(&format!("    /// {0}.\n    {0} = {value},\n", variant.name));
                }
            }
            output.push_str("}\n\n");

            if matches!(backing, EnumBackingType::Int(_)) {
                let backing_type = ModuleCodegen::enum_backing_rust_type(*backing);
                let mut arms = Vec::new();
                for variant in variants {
                    if let BindingEnumValue::Int(value) = variant.value {
                        let literal = format!("{value}{backing_type}");
                        arms.push(format!("{literal} => Self::{}", variant.name));
                    }
                }
                let arms = arms.join(", ");
                output.push_str(&format!("impl VmValueCodec for {name} {{\n"));
                output.push_str("    fn decode(value: vm::Word) -> RuntimeResult<Self> {\n");
                output.push_str(&format!(
                    "        let raw = <{backing_type} as VmValueCodec>::decode(value)?;\n"
                ));
                output.push_str("        let decoded = match raw {\n");
                output.push_str(&format!("            {arms},\n"));
                output.push_str(&format!(
                "            _ => return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(\"value\", \"unknown {name} value\")).boxed()),\n"
            ));
                output.push_str("        };\n");
                output.push_str("        Ok(decoded)\n");
                output.push_str("    }\n\n");
                output.push_str("    fn encode(self) -> vm::Word {\n");
                output.push_str(&format!(
                    "        <{backing_type} as VmValueCodec>::encode(self as {backing_type})\n"
                ));
                output.push_str("    }\n");
                output.push_str("}\n\n");
            }
            output.push_str(&format!("impl VmCollectionElement for {name} {{}}\n\n"));

            output.push_str(&format!("/// Value type for {name}.\n"));
            output.push_str(&format!(
                "pub type {} = {name};\n\n",
                codegen.value_type_name(name)
            ));

            output.push_str(&format!("impl NativeAbiCodec for {name} {{\n"));
            output.push_str(&format!(
                "    type Value = {};\n\n",
                codegen.value_type_name(name)
            ));
            output.push_str(
            "    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {\n",
        );
            output.push_str("        Ok(self)\n");
            output.push_str("    }\n\n");
            output.push_str(
            "    fn from_value(_binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {\n",
        );
            output.push_str("        value\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");

            output.push_str(&format!("impl VmAbiCodec for {name} {{\n"));
            output.push_str(&format!(
                "    type Value = {};\n\n",
                codegen.value_type_name(name)
            ));
            output.push_str(
            "    fn into_value(self, _context: &vm::ExternalReadContext<'_, '_>) -> RuntimeResult<<Self as VmAbiCodec>::Value> {\n",
        );
            output.push_str("        Ok(self)\n");
            output.push_str("    }\n\n");
            output.push_str(
            "    fn from_value(_context: &mut vm::ExternalWriteContext<'_, '_>, value: <Self as VmAbiCodec>::Value) -> RuntimeResult<Self> {\n",
        );
            output.push_str("        Ok(value)\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");
        }

        for (union_name, binding_type) in tagged_unions {
            let BindingType::TaggedUnion { variants, .. } = binding_type else {
                panic!("expected tagged union binding for {union_name}");
            };
            let variant_tags = codegen.tagged_union_variant_tags(union_name, variants);
            let requires_abi = binding_type_requires_abi(binding_type);
            let value_name = codegen.value_type_name(union_name);
            output.push_str(&format!("/// ABI tagged union for {union_name}.\n"));
            if requires_abi {
                output.push_str(&format!("pub enum {union_name}Abi<A: BindingAbi> {{\n"));
            } else {
                output
                    .push_str("#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]\n");
                output.push_str(&format!("pub enum {union_name} {{\n"));
            }
            for variant in variants {
                let variant_type = if requires_abi {
                    codegen.abi_struct_field_type(&variant.binding_type)
                } else {
                    codegen.native_type_for_binding(&variant.binding_type)
                };
                output.push_str(&format!("    /// {} variant.\n", variant.name));
                output.push_str(&format!("    {}({variant_type}),\n", variant.name));
            }
            output.push_str("}\n\n");

            if requires_abi {
                output.push_str(&format!(
                    "pub type {union_name} = {union_name}Abi<NativeAbi>;\n"
                ));
                output.push_str(&format!(
                    "pub type {union_name}Vm = {union_name}Abi<VmAbi>;\n\n"
                ));
                output.push_str(&format!(
                    "impl<A: BindingAbi> std::fmt::Debug for {union_name}Abi<A> {{\n"
                ));
                output.push_str("    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
                output.push_str(&format!(
                    "        formatter.debug_tuple(\"{union_name}Abi\").finish()\n"
                ));
                output.push_str("    }\n");
                output.push_str("}\n\n");
                output.push_str(&format!("impl Copy for {union_name}Abi<NativeAbi> {{}}\n"));
                output.push_str(&format!(
                "impl Clone for {union_name}Abi<NativeAbi> {{\n    fn clone(&self) -> Self {{ *self }}\n}}\n"
            ));
                output.push_str(&format!("impl Copy for {union_name}Abi<VmAbi> {{}}\n"));
                output.push_str(&format!(
                "impl Clone for {union_name}Abi<VmAbi> {{\n    fn clone(&self) -> Self {{ *self }}\n}}\n\n"
            ));
            } else {
                output.push_str(&format!("pub type {union_name}Vm = {union_name};\n\n"));
            }

            let vm_union_type = if requires_abi {
                format!("{union_name}Abi<VmAbi>")
            } else {
                union_name.clone()
            };
            let union_metadata_name =
                codegen.named_type_metadata_name(codegen.module(), union_name);
            output.push_str(&format!("impl VmAggregateCodec for {vm_union_type} {{\n"));
            output.push_str(
            "    fn decode_with_context(context: &vm::ExternalReadContext<'_, '_>, value: vm::Word) -> RuntimeResult<Self> {\n",
        );
            output.push_str(&format!(
            "        let value_ref = context.value_ref(value, \"{}\").map_err(|error| RuntimeError::from(error).boxed())?;\n",
            union_metadata_name
        ));
            output.push_str(
            "        <Self as VmAggregateCodec>::decode_value_ref_with_context(context, &value_ref)\n",
        );
            output.push_str("    }\n\n");
            output.push_str(
            "    fn decode_value_ref_with_context(context: &vm::ExternalReadContext<'_, '_>, value_ref: &vm::VmValueRef<'_, '_>) -> RuntimeResult<Self> {\n",
        );
            output.push_str("        let field_count = value_ref.field_count();\n");
            output.push_str("        if field_count != 2 {\n");
            output.push_str(
            "            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(\"value\", \"expected 2 fields\")).boxed());\n",
        );
            output.push_str("        }\n");
            output.push_str(
            "        let tag = <u32 as VmAggregateCodec>::decode_field_with_context(context, value_ref, 0)?;\n",
        );
            output.push_str("        let decoded = match tag {\n");
            for (variant, tag) in variants.iter().zip(variant_tags.iter().copied()) {
                let variant_type = codegen.vm_type_for_binding(&variant.binding_type);
                output.push_str(&format!(
                "            {tag}u32 => Self::{}(<{variant_type} as VmAggregateCodec>::decode_field_with_context(context, value_ref, 1)?),\n",
                variant.name
            ));
            }
            output.push_str(&format!(
            "            _ => return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(\"value\", \"unknown {union_name} tag\")).boxed()),\n"
        ));
            output.push_str("        };\n");
            output.push_str("        Ok(decoded)\n");
            output.push_str("    }\n\n");
            output.push_str(
            "    fn encode_with_context(self, context: &mut vm::ExternalWriteContext<'_, '_>) -> RuntimeResult<vm::Word> {\n",
        );
            output.push_str("        match self {\n");
            for (variant, tag) in variants.iter().zip(variant_tags.iter().copied()) {
                let variant_type = codegen.vm_type_for_binding(&variant.binding_type);
                output.push_str(&format!(
                    "            Self::{}(value) => {{\n",
                    variant.name
                ));
                output.push_str(&format!(
                "                let tag_value = <u32 as VmAggregateCodec>::encode_with_context({tag}u32, context)?;\n"
            ));
                output.push_str(&format!(
                "                let payload_value = <{variant_type} as VmAggregateCodec>::encode_with_context(value, context)?;\n"
            ));
                output.push_str(&format!(
                    "                let mut value_builder = context.begin_named_aggregate_builder(\"{}\").map_err(Box::<RuntimeError>::from)?;\n",
                    codegen.escape_rust_string(&union_metadata_name)
                ));
                output.push_str("                value_builder.write_field(0, tag_value).map_err(Box::<RuntimeError>::from)?;\n");
                output.push_str("                value_builder.write_field(1, payload_value).map_err(Box::<RuntimeError>::from)?;\n");
                output.push_str(
                    "                value_builder.finish().map_err(Box::<RuntimeError>::from)\n",
                );
                output.push_str("            }\n");
            }
            output.push_str("        }\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");
            output.push_str(&format!(
                "impl VmCollectionElement for {vm_union_type} {{}}\n\n"
            ));

            if requires_abi {
                output.push_str(&format!("/// Value type for {union_name}.\n"));
                output.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
                output.push_str(&format!("pub enum {value_name} {{\n"));
                for variant in variants {
                    let variant_type = codegen.owned_type_for_binding(&variant.binding_type);
                    output.push_str(&format!("    /// {} variant.\n", variant.name));
                    output.push_str(&format!("    {}({variant_type}),\n", variant.name));
                }
                output.push_str("}\n\n");

                output.push_str(&format!(
                    "impl NativeAbiCodec for {union_name}Abi<NativeAbi> {{\n"
                ));
                output.push_str(&format!("    type Value = {value_name};\n\n"));
                output.push_str(
                "    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {\n",
            );
                output.push_str("        let owned = match self {\n");
                for variant in variants {
                    output.push_str(&format!(
                        "            Self::{}(value) => {value_name}::{}({}),\n",
                        variant.name,
                        variant.name,
                        codegen.render_native_into_value(&variant.binding_type, "value")
                    ));
                }
                output.push_str("        };\n");
                output.push_str("        Ok(owned)\n");
                output.push_str("    }\n\n");
                output.push_str(
                "    fn from_value(binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {\n",
            );
                output.push_str("        match value {\n");
                for variant in variants {
                    output.push_str(&format!(
                        "            {value_name}::{}(value) => Self::{}({}),\n",
                        variant.name,
                        variant.name,
                        codegen.render_native_from_value(&variant.binding_type, "value")
                    ));
                }
                output.push_str("        }\n");
                output.push_str("    }\n");
                output.push_str("}\n\n");

                output.push_str(&format!("impl VmAbiCodec for {union_name}Abi<VmAbi> {{\n"));
                output.push_str(&format!("    type Value = {value_name};\n\n"));
                output.push_str(
                "    fn into_value(self, context: &vm::ExternalReadContext<'_, '_>) -> RuntimeResult<<Self as VmAbiCodec>::Value> {\n",
            );
                output.push_str("        let owned = match self {\n");
                for variant in variants {
                    output.push_str(&format!(
                        "            Self::{}(value) => {value_name}::{}({}),\n",
                        variant.name,
                        variant.name,
                        codegen.render_vm_into_value(&variant.binding_type, "value")
                    ));
                }
                output.push_str("        };\n");
                output.push_str("        Ok(owned)\n");
                output.push_str("    }\n\n");
                output.push_str(
                "    fn from_value(context: &mut vm::ExternalWriteContext<'_, '_>, value: <Self as VmAbiCodec>::Value) -> RuntimeResult<Self> {\n",
            );
                output.push_str("        match value {\n");
                for variant in variants {
                    output.push_str(&format!(
                        "            {value_name}::{}(value) => Ok(Self::{}({})),\n",
                        variant.name,
                        variant.name,
                        codegen.render_vm_from_value(&variant.binding_type, "value")
                    ));
                }
                output.push_str("        }\n");
                output.push_str("    }\n");
                output.push_str("}\n\n");
            } else {
                output.push_str(&format!("/// Value type for {union_name}.\n"));
                output.push_str(&format!("pub type {value_name} = {union_name};\n\n"));

                output.push_str(&format!("impl NativeAbiCodec for {union_name} {{\n"));
                output.push_str(&format!("    type Value = {value_name};\n\n"));
                output.push_str(
                "    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {\n",
            );
                output.push_str("        Ok(self)\n");
                output.push_str("    }\n\n");
                output.push_str(
                "    fn from_value(_binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {\n",
            );
                output.push_str("        value\n");
                output.push_str("    }\n");
                output.push_str("}\n\n");

                output.push_str(&format!("impl VmAbiCodec for {union_name} {{\n"));
                output.push_str(&format!("    type Value = {value_name};\n\n"));
                output.push_str(
                "    fn into_value(self, _context: &vm::ExternalReadContext<'_, '_>) -> RuntimeResult<<Self as VmAbiCodec>::Value> {\n",
            );
                output.push_str("        Ok(self)\n");
                output.push_str("    }\n\n");
                output.push_str(
                "    fn from_value(_context: &mut vm::ExternalWriteContext<'_, '_>, value: <Self as VmAbiCodec>::Value) -> RuntimeResult<Self> {\n",
            );
                output.push_str("        Ok(value)\n");
                output.push_str("    }\n");
                output.push_str("}\n\n");
            }
        }

        for (struct_name, binding_type) in structs {
            let BindingType::Struct { fields, .. } = binding_type else {
                panic!("expected struct binding for {struct_name}");
            };
            let requires_abi = binding_type_requires_abi(binding_type);
            let value_name = codegen.value_type_name(struct_name);
            let struct_metadata_name =
                codegen.named_type_metadata_name(codegen.module(), struct_name);
            output.push_str(&format!("/// ABI struct for {struct_name}.\n"));
            output.push_str("#[repr(C)]\n");
            if requires_abi {
                output.push_str(&format!("pub struct {struct_name}Abi<A: BindingAbi> {{\n"));
            } else {
                output
                    .push_str("#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]\n");
                output.push_str(&format!("pub struct {struct_name} {{\n"));
            }
            for field in fields {
                let field_name = codegen.to_snake_case(&field.name);
                let field_type = codegen.abi_struct_field_type(&field.binding_type);
                codegen.write_field_docs(output, field.documentation.as_deref(), &field_name);
                output.push_str(&format!("    pub {field_name}: {field_type},\n"));
            }
            output.push_str("}\n\n");
            if requires_abi {
                output.push_str(&format!(
                    "pub type {struct_name} = {struct_name}Abi<NativeAbi>;\n"
                ));
                output.push_str(&format!(
                    "pub type {struct_name}Vm = {struct_name}Abi<VmAbi>;\n\n"
                ));
                output.push_str(&format!(
                    "impl<A: BindingAbi> std::fmt::Debug for {struct_name}Abi<A> {{\n"
                ));
                output.push_str("    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
                output.push_str(&format!(
                    "        formatter.debug_struct(\"{struct_name}Abi\").finish_non_exhaustive()\n"
                ));
                output.push_str("    }\n");
                output.push_str("}\n\n");
                output.push_str(&format!("impl Copy for {struct_name}Abi<NativeAbi> {{}}\n"));
                output.push_str(&format!(
                "impl Clone for {struct_name}Abi<NativeAbi> {{\n    fn clone(&self) -> Self {{ *self }}\n}}\n"
            ));
                output.push_str(&format!("impl Copy for {struct_name}Abi<VmAbi> {{}}\n"));
                output.push_str(&format!(
                "impl Clone for {struct_name}Abi<VmAbi> {{\n    fn clone(&self) -> Self {{ *self }}\n}}\n\n"
            ));

                output.push_str(&format!(
                    "impl VmAggregateCodec for {struct_name}Abi<VmAbi> {{\n"
                ));
                output.push_str(
                "    fn decode_with_context(context: &vm::ExternalReadContext<'_, '_>, value: vm::Word) -> RuntimeResult<Self> {\n",
            );
                let metadata_name = codegen.named_type_metadata_name(codegen.module(), struct_name);
                output.push_str(&format!(
                "        let value_ref = context.value_ref(value, \"{}\").map_err(|error| RuntimeError::from(error).boxed())?;\n",
                metadata_name
            ));
                output.push_str(
                "        <Self as VmAggregateCodec>::decode_value_ref_with_context(context, &value_ref)\n",
            );
                output.push_str("    }\n\n");
                output.push_str(
                "    fn decode_value_ref_with_context(context: &vm::ExternalReadContext<'_, '_>, value_ref: &vm::VmValueRef<'_, '_>) -> RuntimeResult<Self> {\n",
            );
                output.push_str("        let field_count = value_ref.field_count();\n");
                if fields.is_empty() {
                    output.push_str("        if field_count != 0 {\n");
                } else {
                    output.push_str(&format!("        if field_count != {} {{\n", fields.len()));
                }
                output.push_str(&format!(
                "            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(\"value\", \"expected {} fields\")).boxed());\n",
                fields.len()
            ));
                output.push_str("        }\n");
                for (index, field) in fields.iter().enumerate() {
                    let field_name = codegen.to_snake_case(&field.name);
                    let field_type = codegen.vm_type_for_binding(&field.binding_type);
                    let local_name = format!("field_{field_name}");
                    output.push_str(&format!(
                    "        let {local_name} = <{field_type} as VmAggregateCodec>::decode_field_with_context(context, value_ref, {index})?;\n"
                ));
                }
                output.push_str("        Ok(Self {\n");
                for field in fields {
                    let field_name = codegen.to_snake_case(&field.name);
                    let local_name = format!("field_{field_name}");
                    output.push_str(&format!("            {field_name}: {local_name},\n"));
                }
                output.push_str("        })\n");
                output.push_str("    }\n\n");
                output.push_str(
                "    fn encode_with_context(self, context: &mut vm::ExternalWriteContext<'_, '_>) -> RuntimeResult<vm::Word> {\n",
            );
                output.push_str(&format!(
                    "        let mut value_builder = context.begin_named_aggregate_builder(\"{}\").map_err(Box::<RuntimeError>::from)?;\n",
                    codegen.escape_rust_string(&struct_metadata_name)
                ));
                for (index, field) in fields.iter().enumerate() {
                    let field_name = codegen.to_snake_case(&field.name);
                    let field_type = codegen.vm_type_for_binding(&field.binding_type);
                    output.push_str(&format!(
                    "        let field_value = <{field_type} as VmAggregateCodec>::encode_with_context(self.{field_name}, context)?;\n"
                ));
                    output.push_str(&format!(
                    "        value_builder.write_field({index}, field_value).map_err(Box::<RuntimeError>::from)?;\n"
                ));
                }
                output.push_str(
                    "        value_builder.finish().map_err(Box::<RuntimeError>::from)\n",
                );
                output.push_str("    }\n");
                output.push_str("}\n\n");
                output.push_str(&format!(
                    "impl VmCollectionElement for {struct_name}Abi<VmAbi> {{}}\n\n"
                ));

                output.push_str(&format!("/// Value type for {struct_name}.\n"));
                output.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
                output.push_str(&format!("pub struct {value_name} {{\n"));
                for field in fields {
                    let field_name = codegen.to_snake_case(&field.name);
                    let field_type = codegen.owned_type_for_binding(&field.binding_type);
                    codegen.write_field_docs(output, field.documentation.as_deref(), &field_name);
                    output.push_str(&format!("    pub {field_name}: {field_type},\n"));
                }
                output.push_str("}\n\n");

                output.push_str(&format!(
                    "impl NativeAbiCodec for {struct_name}Abi<NativeAbi> {{\n"
                ));
                output.push_str(&format!("    type Value = {value_name};\n\n"));
                output.push_str(
                "    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {\n",
            );
                output.push_str(&format!("        Ok({value_name} {{\n"));
                for field in fields {
                    let field_name = codegen.to_snake_case(&field.name);
                    output.push_str(&format!(
                        "            {field_name}: {},\n",
                        codegen.render_native_into_value(
                            &field.binding_type,
                            &format!("self.{field_name}")
                        )
                    ));
                }
                output.push_str("        })\n");
                output.push_str("    }\n\n");
                output.push_str(
                "    fn from_value(binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {\n",
            );
                output.push_str("        Self {\n");
                for field in fields {
                    let field_name = codegen.to_snake_case(&field.name);
                    output.push_str(&format!(
                        "            {field_name}: {},\n",
                        codegen.render_native_from_value(
                            &field.binding_type,
                            &format!("value.{field_name}")
                        )
                    ));
                }
                output.push_str("        }\n");
                output.push_str("    }\n");
                output.push_str("}\n\n");

                // FUGU #Performance: avoid eagerly materializing VM heap fields into owned values, see V8 Local handles
                output.push_str(&format!("impl VmAbiCodec for {struct_name}Abi<VmAbi> {{\n"));
                output.push_str(&format!("    type Value = {value_name};\n\n"));
                output.push_str(
                "    fn into_value(self, context: &vm::ExternalReadContext<'_, '_>) -> RuntimeResult<<Self as VmAbiCodec>::Value> {\n",
            );
                output.push_str(&format!("        Ok({value_name} {{\n"));
                for field in fields {
                    let field_name = codegen.to_snake_case(&field.name);
                    output.push_str(&format!(
                        "            {field_name}: {},\n",
                        codegen.render_vm_into_value(
                            &field.binding_type,
                            &format!("self.{field_name}")
                        )
                    ));
                }
                output.push_str("        })\n");
                output.push_str("    }\n\n");
                output.push_str(
                "    fn from_value(context: &mut vm::ExternalWriteContext<'_, '_>, value: <Self as VmAbiCodec>::Value) -> RuntimeResult<Self> {\n",
            );
                output.push_str("        Ok(Self {\n");
                for field in fields {
                    let field_name = codegen.to_snake_case(&field.name);
                    output.push_str(&format!(
                        "            {field_name}: {},\n",
                        codegen.render_vm_from_value(
                            &field.binding_type,
                            &format!("value.{field_name}")
                        )
                    ));
                }
                output.push_str("        })\n");
                output.push_str("    }\n");
                output.push_str("}\n\n");
            } else {
                output.push_str(&format!("pub type {struct_name}Vm = {struct_name};\n\n"));

                output.push_str(&format!("impl VmAggregateCodec for {struct_name} {{\n"));
                output.push_str(
                "    fn decode_with_context(context: &vm::ExternalReadContext<'_, '_>, value: vm::Word) -> RuntimeResult<Self> {\n",
            );
                let metadata_name = codegen.named_type_metadata_name(codegen.module(), struct_name);
                output.push_str(&format!(
                "        let value_ref = context.value_ref(value, \"{}\").map_err(|error| RuntimeError::from(error).boxed())?;\n",
                metadata_name
            ));
                output.push_str(
                "        <Self as VmAggregateCodec>::decode_value_ref_with_context(context, &value_ref)\n",
            );
                output.push_str("    }\n\n");
                output.push_str(
                "    fn decode_value_ref_with_context(context: &vm::ExternalReadContext<'_, '_>, value_ref: &vm::VmValueRef<'_, '_>) -> RuntimeResult<Self> {\n",
            );
                output.push_str("        let field_count = value_ref.field_count();\n");
                if fields.is_empty() {
                    output.push_str("        if field_count != 0 {\n");
                } else {
                    output.push_str(&format!("        if field_count != {} {{\n", fields.len()));
                }
                output.push_str(&format!(
                "            return Err(RuntimeError::from(AbiPlatformError::invalid_argument_value(\"value\", \"expected {} fields\")).boxed());\n",
                fields.len()
            ));
                output.push_str("        }\n");
                for (index, field) in fields.iter().enumerate() {
                    let field_name = codegen.to_snake_case(&field.name);
                    let field_type = codegen.vm_type_for_binding(&field.binding_type);
                    let local_name = format!("field_{field_name}");
                    output.push_str(&format!(
                    "        let {local_name} = <{field_type} as VmAggregateCodec>::decode_field_with_context(context, value_ref, {index})?;\n"
                ));
                }
                output.push_str("        Ok(Self {\n");
                for field in fields {
                    let field_name = codegen.to_snake_case(&field.name);
                    let local_name = format!("field_{field_name}");
                    output.push_str(&format!("            {field_name}: {local_name},\n"));
                }
                output.push_str("        })\n");
                output.push_str("    }\n\n");
                output.push_str(
                "    fn encode_with_context(self, context: &mut vm::ExternalWriteContext<'_, '_>) -> RuntimeResult<vm::Word> {\n",
            );
                output.push_str(&format!(
                    "        let mut value_builder = context.begin_named_aggregate_builder(\"{}\").map_err(Box::<RuntimeError>::from)?;\n",
                    codegen.escape_rust_string(&struct_metadata_name)
                ));
                for (index, field) in fields.iter().enumerate() {
                    let field_name = codegen.to_snake_case(&field.name);
                    let field_type = codegen.vm_type_for_binding(&field.binding_type);
                    output.push_str(&format!(
                    "        let field_value = <{field_type} as VmAggregateCodec>::encode_with_context(self.{field_name}, context)?;\n"
                ));
                    output.push_str(&format!(
                    "        value_builder.write_field({index}, field_value).map_err(Box::<RuntimeError>::from)?;\n"
                ));
                }
                output.push_str(
                    "        value_builder.finish().map_err(Box::<RuntimeError>::from)\n",
                );
                output.push_str("    }\n");
                output.push_str("}\n\n");

                output.push_str(&format!("/// Value type for {struct_name}.\n"));
                output.push_str(&format!("pub type {value_name} = {struct_name};\n\n"));

                output.push_str(&format!("impl NativeAbiCodec for {struct_name} {{\n"));
                output.push_str(&format!("    type Value = {value_name};\n\n"));
                output.push_str(
                "    unsafe fn into_value(self) -> RuntimeResult<<Self as NativeAbiCodec>::Value> {\n",
            );
                output.push_str("        Ok(self)\n");
                output.push_str("    }\n\n");
                output.push_str(
                "    fn from_value(_binding: &BindingCallContext, value: <Self as NativeAbiCodec>::Value) -> Self {\n",
            );
                output.push_str("        value\n");
                output.push_str("    }\n");
                output.push_str("}\n\n");

                output.push_str(&format!("impl VmAbiCodec for {struct_name} {{\n"));
                output.push_str(&format!("    type Value = {value_name};\n\n"));
                output.push_str(
                "    fn into_value(self, _context: &vm::ExternalReadContext<'_, '_>) -> RuntimeResult<<Self as VmAbiCodec>::Value> {\n",
            );
                output.push_str("        Ok(self)\n");
                output.push_str("    }\n\n");
                output.push_str(
                "    fn from_value(_context: &mut vm::ExternalWriteContext<'_, '_>, value: <Self as VmAbiCodec>::Value) -> RuntimeResult<Self> {\n",
            );
                output.push_str("        Ok(value)\n");
                output.push_str("    }\n");
                output.push_str("}\n\n");
                output.push_str(&format!(
                    "impl VmCollectionElement for {struct_name} {{}}\n\n"
                ));
            }
        }

        for (struct_name, binding_type) in structs {
            let BindingType::Struct { fields, .. } = binding_type else {
                continue;
            };
            if !binding_type_requires_abi(binding_type) {
                continue;
            }

            let replay_name = codegen.replay_struct_name(struct_name);
            output.push_str(&format!("/// Replay struct for {struct_name}.\n"));
            output.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
            output.push_str(&format!("pub struct {replay_name} {{\n"));
            for field in fields {
                let field_name = codegen.to_snake_case(&field.name);
                let field_type = codegen.replay_type_for_binding(&field.binding_type);
                codegen.write_field_docs(output, field.documentation.as_deref(), &field_name);
                output.push_str(&format!("    pub {field_name}: {field_type},\n"));
            }
            output.push_str("}\n\n");
        }

        for (union_name, binding_type) in tagged_unions {
            let BindingType::TaggedUnion { variants, .. } = binding_type else {
                continue;
            };
            if !binding_type_requires_abi(binding_type) {
                continue;
            }

            let replay_name = codegen.replay_tagged_union_name(union_name);
            output.push_str(&format!("/// Replay enum for {union_name}.\n"));
            output.push_str("#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]\n");
            output.push_str(&format!("pub enum {replay_name} {{\n"));
            for variant in variants {
                let variant_type = codegen.replay_type_for_binding(&variant.binding_type);
                output.push_str(&format!("    /// {} variant.\n", variant.name));
                output.push_str(&format!("    {}({variant_type}),\n", variant.name));
            }
            output.push_str("}\n\n");
        }

        if let Some(constants) = self.constants
            && !constants.is_empty()
        {
            for constant in constants.values() {
                Self::write_constant(&codegen, constant, output);
            }
        }

        let register_aggregate_types_fn = codegen.register_aggregate_types_fn_name();
        let isolate_name = if aggregate_type_registrations.is_empty() {
            "_isolate"
        } else {
            "isolate"
        };
        output.push_str(&format!(
            "/// Register VM aggregate schemas for {domain}.\n"
        ));
        output.push_str(&format!(
            "pub(crate) fn {register_aggregate_types_fn}({isolate_name}: &mut vm::Isolate) -> vm::Result<()> {{\n"
        ));
        for (metadata_name, field_count) in aggregate_type_registrations {
            output.push_str(&format!(
                "    isolate.register_named_aggregate_type(\"{}\", {})?;\n",
                codegen.escape_rust_string(&metadata_name),
                field_count
            ));
        }
        if !aggregate_type_registrations.is_empty() {
            output.push_str("\n");
        }
        output.push_str("    Ok(())\n");
        output.push_str("}\n");

        self.output
    }

    /// Write one exported constant definition into the ABI output.
    fn write_constant(codegen: &ModuleCodegen<'_>, constant: &ConstantEntry, output: &mut String) {
        if let Some(documentation) = constant.documentation.as_deref() {
            for line in documentation.lines() {
                if line.trim().is_empty() {
                    output.push_str("///\n");
                    continue;
                }

                output.push_str(&format!("/// {}\n", line.trim_end()));
            }
        } else {
            output.push_str(&format!("/// Constant `{}`.\n", constant.name));
        }

        let type_name = codegen.native_type_for_binding(&constant.binding_type);
        let value = Self::render_constant_value(constant);
        output.push_str(&format!(
            "pub const {}: {} = {};\n\n",
            constant.name, type_name, value
        ));
    }

    /// Render one constant payload expression for one exported constant entry.
    fn render_constant_value(constant: &ConstantEntry) -> String {
        match &constant.value {
            ConstantValue::Integer(value) => {
                Self::render_integer_constant_value(&constant.binding_type, *value)
            }
        }
    }

    /// Render one integer constant payload for the requested binding type.
    fn render_integer_constant_value(binding_type: &BindingType, value: i128) -> String {
        match binding_type {
            BindingType::Int(bits) => Self::render_signed_integer_literal(*bits, value),
            BindingType::UInt(bits) => Self::render_unsigned_integer_literal(*bits, value),
            BindingType::Newtype { name, inner, .. } => {
                let inner = Self::render_integer_constant_value(inner, value);
                format!("{name}({inner})")
            }
            _ => panic!("unsupported constant binding type for integer payload: {binding_type:?}"),
        }
    }

    /// Render one signed integer literal with the requested bit width.
    fn render_signed_integer_literal(bits: u8, value: i128) -> String {
        match bits {
            8 => format!(
                "{}i8",
                i8::try_from(value).unwrap_or_else(|_| panic!("i8 overflow: {value}"))
            ),
            16 => {
                format!(
                    "{}i16",
                    i16::try_from(value).unwrap_or_else(|_| panic!("i16 overflow: {value}"))
                )
            }
            32 => {
                format!(
                    "{}i32",
                    i32::try_from(value).unwrap_or_else(|_| panic!("i32 overflow: {value}"))
                )
            }
            64 => {
                format!(
                    "{}i64",
                    i64::try_from(value).unwrap_or_else(|_| panic!("i64 overflow: {value}"))
                )
            }
            _ => panic!("unsupported signed integer width for constant rendering: {bits}"),
        }
    }

    /// Render one unsigned integer literal with the requested bit width.
    fn render_unsigned_integer_literal(bits: u8, value: i128) -> String {
        match bits {
            8 => format!(
                "{}u8",
                u8::try_from(value).unwrap_or_else(|_| panic!("u8 overflow: {value}"))
            ),
            16 => {
                format!(
                    "{}u16",
                    u16::try_from(value).unwrap_or_else(|_| panic!("u16 overflow: {value}"))
                )
            }
            32 => {
                format!(
                    "{}u32",
                    u32::try_from(value).unwrap_or_else(|_| panic!("u32 overflow: {value}"))
                )
            }
            64 => {
                format!(
                    "{}u64",
                    u64::try_from(value).unwrap_or_else(|_| panic!("u64 overflow: {value}"))
                )
            }
            _ => panic!("unsupported unsigned integer width for constant rendering: {bits}"),
        }
    }
}

/// Collect named aggregate registrations for one ABI module.
fn collect_named_aggregate_registrations(
    module: &str,
    structs: &BTreeMap<String, BindingType>,
    newtypes: &BTreeMap<String, BindingType>,
    tagged_unions: &BTreeMap<String, BindingType>,
) -> Vec<(String, usize)> {
    let codegen = ModuleCodegen::new(module);
    let mut registrations = Vec::new();

    // aggregate newtypes
    for (name, binding_type) in newtypes {
        let Some(field_count) = named_aggregate_field_count(binding_type) else {
            continue;
        };
        let metadata_name = codegen.named_type_metadata_name(module, name);
        registrations.push((metadata_name, field_count));
    }

    // aggregate structs
    for (name, binding_type) in structs {
        let Some(field_count) = named_aggregate_field_count(binding_type) else {
            continue;
        };
        let metadata_name = codegen.named_type_metadata_name(module, name);
        registrations.push((metadata_name, field_count));
    }

    // tagged unions
    for (name, binding_type) in tagged_unions {
        let Some(field_count) = named_aggregate_field_count(binding_type) else {
            continue;
        };
        let metadata_name = codegen.named_type_metadata_name(module, name);
        registrations.push((metadata_name, field_count));
    }

    registrations
}

/// Return the semantic field count for one named storage binding type.
fn named_aggregate_field_count(binding_type: &BindingType) -> Option<usize> {
    match binding_type {
        BindingType::Newtype { inner, .. } => binding_type_requires_abi(inner).then_some(1),
        BindingType::Struct { fields, .. } => Some(fields.len()),
        BindingType::TaggedUnion { .. } => Some(2),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use crate::platform::model::{
        BindingTaggedUnionVariant, BindingType, ConstantEntry, ConstantValue,
    };

    use super::AbiRenderer;
    use super::codegen::ModuleCodegen;

    /// Keep tagged union tags stable regardless of declaration order.
    #[test]
    fn test_tagged_union_variant_tags_are_order_independent() {
        let variants = vec![
            BindingTaggedUnionVariant {
                name: "OpenFile".to_string(),
                binding_type: BindingType::Void,
            },
            BindingTaggedUnionVariant {
                name: "OpenUrl".to_string(),
                binding_type: BindingType::Void,
            },
            BindingTaggedUnionVariant {
                name: "ShareText".to_string(),
                binding_type: BindingType::Void,
            },
        ];
        let mut reversed = variants.clone();
        reversed.reverse();
        let codegen = ModuleCodegen::new("os");

        let mut forward_tags = BTreeMap::new();
        for (variant, tag) in variants
            .iter()
            .zip(codegen.tagged_union_variant_tags("IntentEvent", &variants))
        {
            forward_tags.insert(variant.name.clone(), tag);
        }

        let mut reversed_tags = BTreeMap::new();
        for (variant, tag) in reversed
            .iter()
            .zip(codegen.tagged_union_variant_tags("IntentEvent", &reversed))
        {
            reversed_tags.insert(variant.name.clone(), tag);
        }

        assert_eq!(forward_tags, reversed_tags);
    }

    /// Render integer constant payloads for typed and newtype constants.
    #[test]
    fn test_render_constant_value_renders_integer_literals() {
        let primitive = ConstantEntry {
            name: "FOO".to_string(),
            documentation: None,
            binding_type: BindingType::UInt(32),
            value: ConstantValue::Integer(7),
        };
        assert_eq!(AbiRenderer::render_constant_value(&primitive), "7u32");

        let wrapped = ConstantEntry {
            name: "BAR".to_string(),
            documentation: None,
            binding_type: BindingType::Newtype {
                name: "WindowEventKindMask".to_string(),
                domain: "display".to_string(),
                inner: Box::new(BindingType::UInt(64)),
            },
            value: ConstantValue::Integer(16),
        };
        assert_eq!(
            AbiRenderer::render_constant_value(&wrapped),
            "WindowEventKindMask(16u64)"
        );
    }
}
