[package]
name = "destack_std_lsp"
description = "Destack Standard Library Language Server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"

[[bin]]
name = "destack_std_lsp"
path = "rust/main.rs"

[dependencies]
destack_lang_lex = { workspace = true }
destack_lang_parse = { workspace = true }

tokio = { workspace = true, features = [
	"rt-multi-thread",
	"macros",
	"io-util",
	"sync",
	"io-std",
] }
# TODO: vendor tower-lsp
tower-lsp-server = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
