[package]
name = "destack_javascript_machine"
description = "Destack JavaScript Virtual Machine"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_ast = { workspace = true }
destack_dir = { workspace = true }
destack_fir = { workspace = true }
destack_mir = { workspace = true }
destack_source = { workspace = true }
destack_unicode = { workspace = true }

# general
deno_runtime = { version = "0.229.0", optional = true }
v8 = { version = "142.0.0", optional = true }

[dev-dependencies]

[features]
default = []
bun = []
deno = ["dep:deno_runtime"]
jsc = []
node = []
v8 = ["dep:v8"]

[lints]
workspace = true
