[package]
name = "tspp_cli"
description = "TS++ CLI"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
default-run = "tspp"

[features]
default = ["dev"]
dev = ["tiktoken-rs"]
schema = ["schemars"]

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "generate-cli-schema"
path = "src/bin/generate-cli-schema.rs"
required-features = ["schema"]

[dependencies]
# language
tspp_artifact = { workspace = true }
tspp_compiler = { workspace = true, features = ["native"] }
tspp_core = { workspace = true }
tspp_dir = { workspace = true }
tspp_fir = { workspace = true }
tspp_formatter = { workspace = true }
tspp_json = { workspace = true }
tspp_linter = { workspace = true }
tspp_mir = { workspace = true }
tspp_parser = { workspace = true }
tspp_program = { workspace = true }
tspp_query = { workspace = true }
tspp_repository = { workspace = true }
tspp_rpc = { workspace = true }
tspp_runtime = { workspace = true }
tspp_serde = { workspace = true }
tspp_session = { workspace = true, features = ["native"] }
tspp_source = { workspace = true }

# platform
tspp_daemon = { workspace = true }
tspp_lsp = { workspace = true }
tspp_vm = { workspace = true }
tspp_workspace = { workspace = true }

# general
clap = { workspace = true, features = ["derive"] }
clap_complete = { workspace = true }
console = { workspace = true }
futures = { workspace = true, features = ["async-await", "executor"] }
indicatif = { workspace = true }
jiff = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
schemars = { workspace = true, optional = true }

# dev-only
tiktoken-rs = { workspace = true, optional = true }

[lints]
workspace = true
