use destack_source::DiagnosticSeverity;
use destack_workspace::RuleSeverity;

use super::{LintCategory, LintContext};

/// The IR level at which a lint operates.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LintLevel {
    /// Operates on AST (untyped, pre-binding).
    Ast,
    /// Operates on DIR (typed IR with symbols and types).
    Dir,
    /// Operates on MIR (low-level IR).
    Mir,
}

/// The scope at which a lint operates.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LintScope {
    /// Operates on a single module.
    Module,
    /// Operates on the entire program (cross-module analysis).
    Program,
}

/// Static metadata about a lint rule, generated by `define_lints!`.
#[derive(Debug, Clone, Copy)]
pub struct LintMeta {
    /// Rule ID like "no-floating-promise".
    pub id: &'static str,
    /// Code like "LC001".
    pub code: &'static str,
    /// Name like "NoFloatingPromise".
    pub name: &'static str,
    /// Human-readable description.
    pub description: &'static str,
    /// Category.
    pub category: LintCategory,
    /// Default severity when not configured.
    pub default_severity: DiagnosticSeverity,
    /// URL to documentation.
    pub docs_url: Option<&'static str>,
    /// Whether this lint has an auto-fix.
    pub fixable: bool,
    /// IR level this lint operates on.
    pub level: LintLevel,
    /// Scope this lint operates on.
    pub scope: LintScope,
}

impl LintMeta {
    /// Get the full lint identifier (category/id).
    pub fn full_id(&self) -> String {
        format!("{}/{}", self.category.name(), self.id)
    }

    /// Check if this lint is enabled by default (part of recommended set).
    pub fn is_recommended(&self) -> bool {
        self.category.is_recommended()
    }
}

/// Trait for lint rules.
///
/// Lint rules implement this trait to define how they check code.
/// Object-safe to allow dynamic dispatch.
pub trait LintRule: Send + Sync {
    /// Get the static metadata for this lint rule.
    fn meta(&self) -> &'static LintMeta;

    /// Check a module for lint violations.
    fn check_module(&self, ctx: &mut LintContext<'_>) {
        let _ = ctx;
    }

    /// Check the entire program for lint violations (cross-module analysis).
    fn check_program(&self, ctx: &mut LintContext<'_>) {
        let _ = ctx;
    }

    /// Get the effective severity given configuration.
    fn effective_severity(&self, configured: Option<RuleSeverity>) -> RuleSeverity {
        configured.unwrap_or_else(|| match self.meta().default_severity {
            DiagnosticSeverity::Note => RuleSeverity::Off,
            DiagnosticSeverity::Warning => RuleSeverity::Warn,
            DiagnosticSeverity::Error => RuleSeverity::Error,
        })
    }

    /// Check if this lint should run at the given level.
    fn runs_at_level(&self, level: LintLevel) -> bool {
        self.meta().level == level
    }
}

/// A boxed lint rule for dynamic dispatch.
pub type BoxedLintRule = Box<dyn LintRule>;

/// Create a boxed lint rule from a type implementing LintRule.
pub fn boxed<R: LintRule + 'static>(rule: R) -> BoxedLintRule {
    Box::new(rule)
}
