[package]
name = "destack_workspace_service"
description = "Destack Workspace Service"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_compiler = { workspace = true }
destack_resolver = { workspace = true }
destack_source = { workspace = true }
destack_workspace = { workspace = true }

# general
dashmap = { workspace = true }
parking_lot = { workspace = true }

[lints]
workspace = true
