# ruff: noqa

from typing import TYPE_CHECKING, Union

VERSION = "2025.06.28.0"

# import from all generated files
from .health_pb2 import *
from .common_pb2 import *
from .common_grpc import *
from .language_grpc import *
from .universe_grpc import *
from .space_grpc import *
from .health_grpc import *
from .language_pb2 import *
from .universe_pb2 import *
from .space_pb2 import *
from .google.type.date_pb2 import *
from .google.type.timeofday_pb2 import *
from .google.type.datetime_pb2 import *

# extra utility types
AnyNodeProto = Union[
    CustomEntityDefinitionProto,
    CustomEntityProto,
    CustomEnumDefinitionProto,
    EditEventProto,
    CustomEventDefinitionProto,
    CustomEventProto,
    GaugeMetricProto,
    GaugeMeasurementProto,
    CounterMetricProto,
    CounterMeasurementProto,
    HistogramMetricProto,
    HistogramMeasurementProto,
    CustomOptionProto,
    CustomPropertyProto,
    SnapshotProto,
    BranchProto,
    CustomStructDefinitionProto,
    EntitlementRequestedEventProto,
    EntitlementGrantedEventProto,
    EntitlementRevokedEventProto,
    EntitlementExpiredEventProto,
    EntitlementProto,
    InviteSentEventProto,
    InviteRescindedEventProto,
    InviteAcceptedEventProto,
    InviteRejectedEventProto,
    InviteProto,
    MembershipJoinedEventProto,
    MembershipLeftEventProto,
    MembershipProto,
    PermissionProto,
    RoleAssignedEventProto,
    RoleUnassignedEventProto,
    RoleProto,
    SanctionRequestedEventProto,
    SanctionGrantedEventProto,
    SanctionRevokedEventProto,
    SanctionExpiredEventProto,
    SanctionProto,
    CustomViewDefinitionProto,
    CustomViewProto,
    FrameViewProto,
    LabelViewProto,
    SplitViewProto,
    TextViewProto,
    NumberInputViewProto,
    SliderInputViewProto,
    WizardViewProto,
    ThreadViewProto,
    AnnotationShapeProto,
    ArrowShapeProto,
    CanvasProto,
    LineShapeProto,
    PolygonShapeProto,
    FileProto,
    LinkProto,
    EnvironmentProto,
    FolderProto,
    TagProto,
    TaggingProto,
    DatabaseProto,
    MachineProto,
    PointerDownEventProto,
    PointerUpEventProto,
    PointerMoveEventProto,
    PointerEnterEventProto,
    PointerOverEventProto,
    PointerLeaveEventProto,
    LongPressEventProto,
    LeftClickEventProto,
    RightClickEventProto,
    MiddleClickEventProto,
    DoubleClickEventProto,
    WheelEventProto,
    KeyDownEventProto,
    KeyUpEventProto,
    KeyPressEventProto,
    DragStartEventProto,
    DragEndEventProto,
    DragOverEventProto,
    DragEnterEventProto,
    DragLeaveEventProto,
    DropEventProto,
    CopyEventProto,
    CutEventProto,
    PasteEventProto,
    FocusInEventProto,
    FocusOutEventProto,
    ActionProto,
    EventCursorProto,
    ScreenCursorProto,
    ThreadCursorProto,
    RouteProto,
    ScriptProto,
    ServiceProto,
    TimerStartedEventProto,
    TimerStoppedEventProto,
    TimerProto,
    TriggerStartedEventProto,
    TriggerStoppedEventProto,
    TriggerProto,
    InterruptionProto,
    LogProto,
    RunStartedEventProto,
    RunPauseRequestedEventProto,
    RunPausedEventProto,
    RunResumeRequestedEventProto,
    RunResumedEventProto,
    RunStopRequestedEventProto,
    RunFailedEventProto,
    RunCompletedEventProto,
    RunProto,
    SpanProto,
    LayerProto,
    SceneEnteredEventProto,
    SceneExitedEventProto,
    SceneProto,
    VariantProto,
    WindowProto,
    FollowProto,
    MessageProto,
    NotificationSentEventProto,
    NotificationRescindedEventProto,
    NotificationReadEventProto,
    NotificationDismissedEventProto,
    NotificationExpiredEventProto,
    NotificationProto,
    ReactionProto,
    StarProto,
    ThreadProto,
    AgentProto,
    ClientProto,
    FriendshipProto,
    FriendshipInviteSentEventProto,
    FriendshipInviteRescindedEventProto,
    FriendshipInviteAcceptedEventProto,
    FriendshipInviteRejectedEventProto,
    FriendshipInviteProto,
    HandleProto,
    OrganizationProto,
    SpaceProto,
    TeamProto,
    UserProto,
    ColorStyleProto,
    BorderStyleProto,
    TransitionStyleProto,
    EffectStyleProto,
    GradientStyleProto,
    FillStyleProto,
    FontStyleProto,
    PaletteProto,
    ShadowStyleProto,
    StrokeStyleProto,
    ThemeProto,
]
AnyStructProto = Union[
    ScopeProto,
    RelationReferenceProto,
    ObjectReferenceProto,
    PropertyReferenceProto,
    NodeReferenceProto,
    EditProto,
    ChangeProto,
    ChangeResultProto,
    IconProto,
    StringConstraintProto,
    NumberConstraintProto,
    CollectionConstraintProto,
    NodeConstraintProto,
    TypeProto,
    ValueProto,
    FunctionProto,
    ConditionProto,
    AggregationProto,
    ExpressionProto,
    SortProto,
    SelectProto,
    JoinProto,
    QueryProto,
    HistogramProto,
    QueryResultProto,
    QueryResultGroupProto,
    QueryUpdateProto,
    SelectionProto,
    PropertyDefinitionProto,
    TraitDefinitionProto,
    NodeDefinitionProto,
    StructDefinitionProto,
    EnumDefinitionProto,
    OptionDefinitionProto,
    PermissionDefinitionProto,
    ConstantDefinitionProto,
    TextSpanProto,
    TextProto,
    Vector2Proto,
    Vector3Proto,
    Vector4Proto,
    Vector2iProto,
    Vector3iProto,
    Vector4iProto,
    LengthProto,
    PositionProto,
    DimensionProto,
    InsetsProto,
    CornersProto,
    Axis2Proto,
    Axis3Proto,
    GridProto,
    GridSpanProto,
    LineProto,
    PolygonProto,
    DatabaseInfoProto,
    GalaxyInfoProto,
    ScheduleProto,
    OriginProto,
    ColorProto,
    BorderProto,
    TransitionProto,
    EffectProto,
    GradientStopProto,
    GradientProto,
    FillProto,
    FontProto,
    ShadowProto,
    StrokeProto,
    StrokeCapProto,
    StrokePointProto,
    StrokePathProto,
]
AnyObjectProto = AnyNodeProto | AnyStructProto
