# ruff: noqa

from typing import TYPE_CHECKING, Union

VERSION = "2025.06.26.1"

# import from all generated files
from .health_pb2 import *
from .common_pb2 import *
from .common_grpc import *
from .language_grpc import *
from .universe_grpc import *
from .space_grpc import *
from .health_grpc import *
from .language_pb2 import *
from .universe_pb2 import *
from .space_pb2 import *
from .google.type.date_pb2 import *
from .google.type.timeofday_pb2 import *
from .google.type.datetime_pb2 import *

# extra utility types
AnyNodeProto = Union[
    CustomEntityDefinitionProto,
    CustomEntityProto,
    CustomEnumDefinitionProto,
    EditEventProto,
    CustomEventDefinitionProto,
    CustomEventProto,
    GaugeMetricProto,
    GaugeMeasurementProto,
    CounterMetricProto,
    CounterMeasurementProto,
    HistogramMetricProto,
    HistogramMeasurementProto,
    CustomOptionProto,
    CustomPropertyProto,
    SnapshotProto,
    BranchProto,
    CustomStructDefinitionProto,
    EntitlementEventProto,
    EntitlementProto,
    InviteEventProto,
    InviteProto,
    MembershipEventProto,
    MembershipProto,
    PermissionProto,
    RoleEventProto,
    RoleProto,
    SanctionEventProto,
    SanctionProto,
    CustomViewDefinitionProto,
    CustomViewProto,
    FrameViewProto,
    LabelViewProto,
    SplitViewProto,
    TextViewProto,
    NumberInputViewProto,
    SliderInputViewProto,
    WizardViewProto,
    ThreadViewProto,
    AnnotationShapeProto,
    ArrowShapeProto,
    CanvasProto,
    LineShapeProto,
    PlaneShapeProto,
    FileProto,
    LinkProto,
    EnvironmentProto,
    FolderProto,
    TagProto,
    TaggingProto,
    DatabaseProto,
    MachineProto,
    ActionProto,
    EventCursorProto,
    ScreenCursorProto,
    ThreadCursorProto,
    RouteProto,
    ScriptProto,
    ServiceProto,
    TimerEventProto,
    TimerProto,
    TriggerEventProto,
    TriggerProto,
    InterruptionProto,
    LogProto,
    RunEventProto,
    RunProto,
    SpanProto,
    LayerProto,
    SceneEventProto,
    SceneProto,
    VariantProto,
    WindowProto,
    FollowProto,
    MessageProto,
    NotificationEventProto,
    NotificationProto,
    ReactionProto,
    StarProto,
    ThreadProto,
    AgentProto,
    ClientProto,
    FriendshipProto,
    FriendshipInviteEventProto,
    FriendshipInviteProto,
    HandleProto,
    OrganizationProto,
    SpaceProto,
    TeamProto,
    UserProto,
    ColorStyleProto,
    BorderStyleProto,
    TransitionStyleProto,
    EffectStyleProto,
    GradientStyleProto,
    FillStyleProto,
    FontStyleProto,
    PaletteProto,
    ShadowStyleProto,
    ThemeProto,
]
AnyStructProto = Union[
    ScopeProto,
    RelationReferenceProto,
    ObjectReferenceProto,
    PropertyReferenceProto,
    NodeReferenceProto,
    EditProto,
    ChangeProto,
    ChangeResultProto,
    IconProto,
    StringConstraintProto,
    NumberConstraintProto,
    CollectionConstraintProto,
    NodeConstraintProto,
    TypeProto,
    ValueProto,
    FunctionProto,
    ConditionProto,
    AggregationProto,
    ExpressionProto,
    SortProto,
    SelectProto,
    JoinProto,
    QueryProto,
    HistogramProto,
    QueryResultProto,
    QueryResultGroupProto,
    QueryUpdateProto,
    SelectionProto,
    PropertyDefinitionProto,
    TraitDefinitionProto,
    NodeDefinitionProto,
    StructDefinitionProto,
    EnumDefinitionProto,
    OptionDefinitionProto,
    PermissionDefinitionProto,
    ConstantDefinitionProto,
    TextSpanProto,
    TextProto,
    LengthProto,
    PositionProto,
    DimensionProto,
    InsetsProto,
    CornersProto,
    Axis2Proto,
    Axis3Proto,
    Vector2Proto,
    Vector3Proto,
    Vector4Proto,
    Vector2iProto,
    Vector3iProto,
    Vector4iProto,
    GridProto,
    GridSpanProto,
    DatabaseInfoProto,
    GalaxyInfoProto,
    ScheduleProto,
    OriginProto,
    ColorProto,
    BorderProto,
    TransitionProto,
    EffectProto,
    GradientStopProto,
    GradientProto,
    FillProto,
    FontProto,
    ShadowProto,
]
AnyObjectProto = AnyNodeProto | AnyStructProto
