[package]
name = "tspp_fir"
description = "TS++ Formatting IR"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
tspp_source = { workspace = true }
tspp_unicode = { workspace = true }

# general
rustc-hash = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
