[package]
name = "dyst_fir"
description = "Dyst Formatting IR"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"
doctest = true

[dependencies]
dyst_diagnostic = { workspace = true }
dyst_session = { workspace = true }
dyst_source = { workspace = true }
dyst_token = { workspace = true }
destack_unicode = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }

[lints]
workspace = true
