/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, SerdeError, jsonArray, jsonField, jsonObject, jsonString } from "../../../protocol/serde.js";
import type { DiagnosticLabel } from "./label.js";
import type { PatchSet } from "../edit/edit.js";
import { decodeDiagnosticLabel, encodeDiagnosticLabel, fromJsonDiagnosticLabel, toJsonDiagnosticLabel } from "./label.js";
import { decodePatchSet, encodePatchSet, fromJsonPatchSet, toJsonPatchSet } from "../edit/edit.js";

/** Whether a suggestion can be applied automatically. */
export type Applicability = "automatic" | "unsafe" | "dangerous";

export const Applicability = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: Applicability): void {
        encodeApplicability(writer, value);
    },

    /** Decode one Applicability. */
    decode(reader: BinaryReader): Applicability {
        return decodeApplicability(reader);
    },

    /** Return this value as JSON. */
    toJson(value: Applicability): Json {
        return toJsonApplicability(value);
    },

    /** Return one Applicability from one JSON value. */
    fromJson(value: Json): Applicability {
        return fromJsonApplicability(value);
    },
};

/** Encode one Applicability. */
export function encodeApplicability(writer: BinaryWriter, value: Applicability): void {
    switch (value) {
        case "automatic":
            writer.writeUnsigned(0);
            return;
        case "unsafe":
            writer.writeUnsigned(1);
            return;
        case "dangerous":
            writer.writeUnsigned(2);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one Applicability. */
export function decodeApplicability(reader: BinaryReader): Applicability {
    const variant = reader.readNumber();

    switch (variant) {
        case 0:
            return "automatic";
        case 1:
            return "unsafe";
        case 2:
            return "dangerous";
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one Applicability. */
export function toJsonApplicability(value: Applicability): Json {
    return value;
}

/** Return one Applicability from one JSON value. */
export function fromJsonApplicability(value: Json): Applicability {
    const variant = jsonString(value);

    switch (variant) {
        case "automatic":
            return "automatic";
        case "unsafe":
            return "unsafe";
        case "dangerous":
            return "dangerous";
    }

    throw new SerdeError(`unknown enum variant: ${variant}`);
}

/** One suggested source change for a diagnostic. */
export type DiagnosticSuggestion = {
    /** Exact source patches for machine application. */
    readonly patches: PatchSet;
    /** Source labels to show with the suggestion. */
    readonly labels: ReadonlyArray<DiagnosticLabel>;
    /** The message of the suggestion. */
    readonly message: string;
    /** The applicability of the suggestion. */
    readonly applicability: Applicability;
};

export const DiagnosticSuggestion = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: DiagnosticSuggestion): void {
        encodeDiagnosticSuggestion(writer, value);
    },

    /** Decode one DiagnosticSuggestion. */
    decode(reader: BinaryReader): DiagnosticSuggestion {
        return decodeDiagnosticSuggestion(reader);
    },

    /** Return this value as JSON. */
    toJson(value: DiagnosticSuggestion): Json {
        return toJsonDiagnosticSuggestion(value);
    },

    /** Return one DiagnosticSuggestion from one JSON value. */
    fromJson(value: Json): DiagnosticSuggestion {
        return fromJsonDiagnosticSuggestion(value);
    },
};

/** Encode one DiagnosticSuggestion. */
export function encodeDiagnosticSuggestion(writer: BinaryWriter, value: DiagnosticSuggestion): void {
    encodePatchSet(writer, value.patches);
    writer.writeUnsigned(value.labels.length);
    for (const item1 of value.labels) {
        encodeDiagnosticLabel(writer, item1);
    }
    writer.writeString(value.message);
    encodeApplicability(writer, value.applicability);
}

/** Decode one DiagnosticSuggestion. */
export function decodeDiagnosticSuggestion(reader: BinaryReader): DiagnosticSuggestion {
    const patches = decodePatchSet(reader);
    const labels = (() => { const length1 = reader.readNumber(); const items1: Array<DiagnosticLabel> = []; for (let index = 0; index < length1; index += 1) { items1.push(decodeDiagnosticLabel(reader)); } return items1; })();
    const message = reader.readString();
    const applicability = decodeApplicability(reader);

    return {
        patches,
        labels,
        message,
        applicability,
    };
}

/** Return one JSON value for one DiagnosticSuggestion. */
export function toJsonDiagnosticSuggestion(value: DiagnosticSuggestion): Json {
    return {
        patches: toJsonPatchSet(value.patches),
        labels: value.labels.map((item0) => toJsonDiagnosticLabel(item0)),
        message: value.message,
        applicability: toJsonApplicability(value.applicability),
    };
}

/** Return one DiagnosticSuggestion from one JSON value. */
export function fromJsonDiagnosticSuggestion(value: Json): DiagnosticSuggestion {
    const object = jsonObject(value);

    return {
        patches: fromJsonPatchSet(jsonField(object, "patches")),
        labels: jsonArray(jsonField(object, "labels")).map((item0) => fromJsonDiagnosticLabel(item0)),
        message: jsonString(jsonField(object, "message")),
        applicability: fromJsonApplicability(jsonField(object, "applicability")),
    };
}
