[package]
name = "tspp_index"
description = "TS++ Index"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
tspp_artifact = { workspace = true }
tspp_core = { workspace = true }
tspp_dir = { workspace = true }
tspp_serde = { workspace = true }
tspp_source = { workspace = true }
tspp_repository = { path = "../repository", default-features = false }

# general
rustc-hash = { workspace = true }

[lints]
workspace = true
