name: destack
description: Dart client for Destack.
version: 0.55.3
homepage: https://github.com/destack-sh/destack
repository: https://github.com/destack-sh/destack
issue_tracker: https://github.com/destack-sh/destack/issues

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  ffi: ^2.1.3
