[package]
name = "destack_compiler"
description = "Destack Compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_artifact = { workspace = true }
destack_ast = { workspace = true }
destack_builtin = { path = "../builtin", default-features = false }
destack_codegen_js = { workspace = true }
destack_codegen_native = { workspace = true, optional = true }
destack_compiler_macros = { workspace = true }
destack_core = { workspace = true }
destack_css = { workspace = true }
destack_dir = { workspace = true }
destack_engine = { workspace = true }
destack_fir = { workspace = true }
destack_html = { workspace = true }
destack_mir = { workspace = true }
destack_parser = { workspace = true }
destack_query = { workspace = true }
destack_resolver = { workspace = true }
destack_source = { workspace = true }
destack_vm = { workspace = true }
destack_workspace = { path = "../workspace", default-features = false }

# general
dashmap = { workspace = true }
filetime = { workspace = true }
indexmap = { workspace = true }
lightningcss = { workspace = true, features = ["bundler", "into_owned", "serde", "visitor"] }
mime_guess = { workspace = true }
parking_lot = { workspace = true }
postcard = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
smallvec = { workspace = true }
target-lexicon = { workspace = true }
base64 = { workspace = true }
tracing = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
serde_yaml_ng = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
clap = { workspace = true }
criterion = { workspace = true }
destack_formatter = { workspace = true }
destack_linter = { workspace = true }
destack_session = { workspace = true }
pprof = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = ["full"]
parallel = []
native-codegen = ["dep:destack_codegen_native"]
deadlock-detection = ["parking_lot/deadlock_detection"]
optimize = []
builtin-full = ["destack_builtin/full", "destack_workspace/builtin-full"]
builtin-core = ["destack_builtin/core", "destack_workspace/builtin-core"]
full = [
    "parallel",
    "native-codegen",
    "deadlock-detection",
    "optimize",
    "builtin-full",
]
core = ["builtin-core"]
[[bench]]
name = "destack_compile"
harness = false

[lints]
workspace = true
