[package]
name = "dyst_compiler"
description = "Dyst Compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
dyst_ast = { workspace = true }
dyst_dir = { workspace = true }
dyst_fir = { workspace = true }
dyst_mir = { workspace = true }
dyst_parser = { workspace = true }
dyst_source = { workspace = true }
dyst_resolver = { workspace = true }

crossbeam-deque = { workspace = true }
rayon = { workspace = true }
parking_lot = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
