[package]
name = "destack_compiler"
description = "Destack Compiler"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
destack_bytecode = { workspace = true }
# language
destack_artifact = { workspace = true }
destack_artifact_macros = { workspace = true }
destack_core = { workspace = true }
destack_dir = { workspace = true }
destack_program = { workspace = true }
destack_fir = { workspace = true }
destack_formatter = { workspace = true }
destack_heap = { workspace = true }
destack_js = { workspace = true }
destack_mir = { workspace = true }
destack_native = { workspace = true }
destack_parser = { workspace = true }
destack_query = { workspace = true }
destack_source = { workspace = true }
destack_webassembly = { workspace = true }
destack_repository = { path = "../repository", default-features = false }
destack_serde = { workspace = true }

# general
dashmap = { workspace = true }
filetime = { workspace = true }
indexmap = { workspace = true }
mime_guess = { workspace = true }
parking_lot = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"] }
smallvec = { workspace = true }
target-lexicon = { workspace = true }
base64 = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cranelift-codegen = { workspace = true, optional = true }
cranelift-frontend = { workspace = true, optional = true }
cranelift-module = { workspace = true, optional = true }
cranelift-native = { workspace = true, optional = true }
cranelift-object = { workspace = true, optional = true }
gimli = { workspace = true, features = ["write"], optional = true }
serde_yaml_ng = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
clap = { workspace = true }
criterion = { workspace = true }
destack_formatter = { workspace = true }
destack_memory = { workspace = true }
destack_session = { workspace = true, features = ["native"] }
futures = { workspace = true, features = ["executor"] }
pprof = { workspace = true }

[features]
default = ["native"]
native = [
    "dep:cranelift-codegen",
    "dep:cranelift-frontend",
    "dep:cranelift-module",
    "dep:cranelift-native",
    "dep:cranelift-object",
    "dep:gimli",
]
deadlock-detection = ["parking_lot/deadlock_detection"]

[[bench]]
name = "destack_compile"
harness = false

[lints]
workspace = true
