use std::path::Path;

use anyhow::Result;

use crate::generate::core::{
    Field, Item, Payload, PayloadNames, Schema, SchemaModule, Shape, Type, Variant, write_text,
};

use super::generate::target_segments;

const GENERATED_HEADER: &str = "/* generated by destack_bridge_generate, do not edit */";

/// Generate TypeScript backend adapter functions.
pub(in crate::generate::typescript) fn generate(root: &Path, schema: &Schema) -> Result<()> {
    for backend in [Backend::Napi, Backend::Wasm] {
        let content = render_adapter(schema, backend);

        write_text(root, backend.file(), content)?;
    }

    Ok(())
}

/// One TypeScript backend adapter target.
#[derive(Clone, Copy)]
enum Backend {
    /// Node API transport.
    Napi,
    /// WebAssembly transport.
    Wasm,
}

/// One generated text document.
struct Text {
    /// Generated source.
    source: String,
}

impl Backend {
    /// Return this backend generated adapter path.
    fn file(self) -> &'static str {
        match self {
            Self::Napi => "bridge/typescript/src/napi/generated.ts",
            Self::Wasm => "bridge/typescript/src/wasm/generated.ts",
        }
    }

    /// Return this backend import namespace.
    fn namespace(self) -> &'static str {
        match self {
            Self::Napi => "Napi",
            Self::Wasm => "Wasm",
        }
    }

    /// Return this backend function stem.
    fn stem(self) -> &'static str {
        match self {
            Self::Napi => "Napi",
            Self::Wasm => "Wasm",
        }
    }
}

impl Text {
    /// Create one empty text document.
    fn new() -> Self {
        Self {
            source: String::new(),
        }
    }

    /// Write raw generated source.
    fn raw(&mut self, source: impl AsRef<str>) {
        self.source.push_str(source.as_ref());
    }

    /// Write one line.
    fn line(&mut self, line: impl AsRef<str>) {
        self.source.push_str(line.as_ref());
        self.source.push('\n');
    }

    /// Write one blank line.
    fn blank(&mut self) {
        self.source.push('\n');
    }

    /// Write one documentation line.
    fn doc(&mut self, doc: impl AsRef<str>) {
        self.line(format!("/** {} */", doc.as_ref()));
    }

    /// Return the generated source.
    fn finish(self) -> String {
        self.source
    }
}

/// Render one backend adapter module.
fn render_adapter(schema: &Schema, backend: Backend) -> String {
    let mut text = Text::new();
    text.line(GENERATED_HEADER);
    text.blank();

    text.raw(render_imports(schema, backend));
    if matches!(backend, Backend::Wasm) {
        text.blank();
        text.line("type WasmModule = typeof import(\"@destack/language-wasm\");");
    }

    for name in adapter_item_names(schema) {
        let item = schema.item(&name);

        if generates_to_backend(schema, item) {
            text.blank();
            text.raw(render_to_item(schema, backend, item));
        }
        if generates_from_backend(schema, item) {
            text.blank();
            text.raw(render_from_item(schema, backend, item));
        }
    }

    text.finish()
}

/// Render imports for one backend adapter module.
fn render_imports(schema: &Schema, backend: Backend) -> String {
    let mut text = Text::new();
    let namespace = backend.namespace();
    let package = match backend {
        Backend::Napi => "@destack/language-napi",
        Backend::Wasm => "@destack/language-wasm",
    };

    text.line(format!("import type * as {namespace} from \"{package}\";"));
    for module in &schema.modules {
        let names = &module.names;
        let path = backend_import_path(module);

        if names.len() == 1 {
            text.line(format!("import type {{ {} }} from \"{path}\";", names[0]));
        } else {
            text.line("import type {");
            for name in names {
                text.line(format!("    {name},"));
            }
            text.line(format!("}} from \"{path}\";"));
        }
    }

    text.finish()
}

/// Return bridge item names in generated module order.
fn adapter_item_names(schema: &Schema) -> Vec<String> {
    schema
        .modules
        .iter()
        .flat_map(|module| module.names.iter().cloned())
        .collect()
}

/// Return whether this item needs a backend conversion function.
fn generates_to_backend(schema: &Schema, item: &Item) -> bool {
    item.generates_into_bridge()
        || schema
            .items
            .values()
            .any(|other| other.generates_into_bridge() && other.references(&item.name))
}

/// Return whether this item needs a public bridge conversion function.
fn generates_from_backend(schema: &Schema, item: &Item) -> bool {
    item.generates_from_bridge()
        || schema
            .items
            .values()
            .any(|other| other.generates_from_bridge() && other.references(&item.name))
}

/// Render one backend conversion function.
fn render_to_item(schema: &Schema, backend: Backend, item: &Item) -> String {
    match &item.shape {
        Shape::Struct(fields) => render_to_struct(schema, backend, item, fields),
        Shape::Enum(variants) if schema.is_unit_enum(&item.name) => {
            render_to_unit_enum(item, variants, backend)
        }
        Shape::Enum(variants) => render_to_payload_enum(schema, backend, item, variants),
    }
}

/// Render one public bridge conversion function.
fn render_from_item(schema: &Schema, backend: Backend, item: &Item) -> String {
    match &item.shape {
        Shape::Struct(fields) => render_from_struct(schema, backend, item, fields),
        Shape::Enum(variants) if schema.is_unit_enum(&item.name) => {
            render_from_unit_enum(item, variants, backend)
        }
        Shape::Enum(variants) => render_from_payload_enum(schema, backend, item, variants),
    }
}

/// Render one struct backend conversion function.
fn render_to_struct(schema: &Schema, backend: Backend, item: &Item, fields: &[Field]) -> String {
    let mut text = Text::new();
    let name = &item.name;
    let function = to_name(backend, name);
    let argument = wasm_argument(backend);
    let target = backend_type(schema, backend, item);

    text.doc(format!(
        "Convert one {name} into the {} transport shape.",
        backend_label(backend)
    ));
    text.raw(render_function_header(
        &function,
        &[argument, &format!("value: {name}")],
        &target,
    ));

    match backend {
        Backend::Napi => {
            text.line("    return {");
            for field in fields {
                let label = field.label();
                let value = to_value(schema, backend, &format!("value.{label}"), &field.ty);

                text.line(format!("        {label}: {value},"));
            }
            text.line("    };");
        }
        Backend::Wasm => {
            let values = fields
                .iter()
                .map(|field| {
                    let label = field.label();

                    to_value(schema, backend, &format!("value.{label}"), &field.ty)
                })
                .collect::<Vec<_>>();

            text.raw(render_wasm_new(name, values));
        }
    }

    text.line("}");

    text.finish()
}

/// Render one struct public bridge conversion function.
fn render_from_struct(schema: &Schema, backend: Backend, item: &Item, fields: &[Field]) -> String {
    let mut text = Text::new();
    let name = &item.name;
    let function = from_name(backend, name);
    let source = backend_type(schema, backend, item);

    text.doc(format!(
        "Convert one {} {name} into the public bridge shape.",
        backend_label(backend)
    ));
    text.raw(render_function_header(
        &function,
        &[&format!("value: {source}")],
        name,
    ));
    text.line("    return {");
    for field in fields {
        let label = field.label();
        let value = from_value(schema, backend, &format!("value.{label}"), &field.ty);

        text.line(format!("        {label}: {value},"));
    }
    text.line("    };");
    text.line("}");

    text.finish()
}

/// Render one unit enum backend conversion function.
fn render_to_unit_enum(item: &Item, variants: &[Variant], backend: Backend) -> String {
    render_unit_enum(
        item,
        variants,
        backend,
        "Convert",
        to_name(backend, &item.name),
        "string",
    )
}

/// Render one unit enum public bridge conversion function.
fn render_from_unit_enum(item: &Item, variants: &[Variant], backend: Backend) -> String {
    render_unit_enum(
        item,
        variants,
        backend,
        "Convert",
        from_name(backend, &item.name),
        &item.name,
    )
}

/// Render one unit enum adapter function.
fn render_unit_enum(
    item: &Item,
    variants: &[Variant],
    backend: Backend,
    verb: &str,
    function: String,
    output: &str,
) -> String {
    let mut text = Text::new();
    let name = &item.name;
    let is_to_backend = output == "string";
    let input = if is_to_backend { name } else { "string" };
    let labels = variants
        .iter()
        .map(|variant| format!("value === {:?}", variant.label()))
        .collect::<Vec<_>>()
        .join(" || ");

    text.doc(format!(
        "{} one {name} {} the {} transport shape.",
        verb,
        if is_to_backend { "into" } else { "from" },
        backend_label(backend)
    ));
    text.raw(render_function_header(
        &function,
        &[&format!("value: {input}")],
        output,
    ));
    text.line(format!("    if ({labels}) {{"));
    text.line("        return value;");
    text.line("    }");
    text.blank();
    text.line(format!(
        "    throw new Error(`unknown {name}: ${{value}}`);"
    ));
    text.line("}");

    text.finish()
}

/// Render one payload enum backend conversion function.
fn render_to_payload_enum(
    schema: &Schema,
    backend: Backend,
    item: &Item,
    variants: &[Variant],
) -> String {
    let mut text = Text::new();
    let name = &item.name;
    let function = to_name(backend, name);
    let argument = wasm_argument(backend);
    let target = backend_type(schema, backend, item);
    let payload_names = PayloadNames::new(variants);

    text.doc(format!(
        "Convert one {name} into the {} transport shape.",
        backend_label(backend)
    ));
    text.raw(render_function_header(
        &function,
        &[argument, &format!("value: {name}")],
        &target,
    ));
    for variant in variants {
        text.raw(render_to_variant(
            schema,
            backend,
            name,
            variant,
            &payload_names,
        ));
    }
    text.line(format!("    throw new Error(\"unknown {name}\");"));
    text.line("}");

    text.finish()
}

/// Render one payload enum public bridge conversion function.
fn render_from_payload_enum(
    schema: &Schema,
    backend: Backend,
    item: &Item,
    variants: &[Variant],
) -> String {
    let mut text = Text::new();
    let name = &item.name;
    let function = from_name(backend, name);
    let source = backend_type(schema, backend, item);
    let payload_names = PayloadNames::new(variants);

    text.doc(format!(
        "Convert one {} {name} into the public bridge shape.",
        backend_label(backend)
    ));
    text.raw(render_function_header(
        &function,
        &[&format!("value: {source}")],
        name,
    ));

    match backend {
        Backend::Napi | Backend::Wasm => {
            for variant in variants {
                text.raw(render_from_payload_variant(
                    schema,
                    backend,
                    variant,
                    &payload_names,
                ));
            }
            text.line(format!("    throw new Error(\"unknown {name}\");"));
        }
    }

    text.line("}");

    text.finish()
}

/// Render one payload enum backend conversion branch.
fn render_to_variant(
    schema: &Schema,
    backend: Backend,
    owner: &str,
    variant: &Variant,
    payload_names: &PayloadNames,
) -> String {
    let mut text = Text::new();
    let label = variant.label();

    text.line(format!("    if (value.kind === {label:?}) {{"));
    match backend {
        Backend::Napi => {
            text.line("        return {");
            text.line(format!("            kind: {label:?},"));
            text.raw(render_napi_payload_fields(
                schema,
                backend,
                variant,
                payload_names,
                "value",
                12,
            ));
            text.line("        };");
        }
        Backend::Wasm => {
            let values = payload_values(schema, backend, variant, "value");

            text.raw(render_wasm_payload_call(owner, &label, values));
        }
    }
    text.line("    }");
    text.blank();

    text.finish()
}

/// Render one payload enum public bridge conversion branch.
fn render_from_payload_variant(
    schema: &Schema,
    backend: Backend,
    variant: &Variant,
    payload_names: &PayloadNames,
) -> String {
    let mut text = Text::new();
    let label = variant.label();

    text.line(format!("    if (value.kind === {label:?}) {{"));
    text.raw(render_payload_bindings(variant, payload_names, "value"));
    text.line("        return {");
    text.line(format!("            kind: {label:?},"));
    text.raw(render_public_payload_fields(
        schema,
        backend,
        variant,
        payload_names,
        12,
    ));
    text.line("        };");
    text.line("    }");
    text.blank();

    text.finish()
}

/// Render NAPI payload fields.
fn render_napi_payload_fields(
    schema: &Schema,
    backend: Backend,
    variant: &Variant,
    payload_names: &PayloadNames,
    value: &str,
    indent: usize,
) -> String {
    let mut text = Text::new();
    let indent = " ".repeat(indent);

    match &variant.payload {
        Payload::Unit => {}
        Payload::Tuple(ty) => {
            let label = variant.payload_field_name();
            let field = format!("{value}.{label}");
            let field = to_value(schema, backend, &field, ty);

            text.line(format!("{indent}{label}: {field},"));
        }
        Payload::Struct(fields) => {
            for field in fields {
                let public_label = field.label();
                let label = payload_names.field_label(variant, field);
                let value = to_value(
                    schema,
                    backend,
                    &format!("{value}.{public_label}"),
                    &field.ty,
                );

                text.line(format!("{indent}{label}: {value},"));
            }
        }
    }

    text.finish()
}

/// Render public payload fields.
fn render_public_payload_fields(
    schema: &Schema,
    backend: Backend,
    variant: &Variant,
    payload_names: &PayloadNames,
    indent: usize,
) -> String {
    let mut text = Text::new();
    let indent = " ".repeat(indent);

    match &variant.payload {
        Payload::Unit => {}
        Payload::Tuple(ty) => {
            let label = variant.payload_field_name();
            let value = from_value(schema, backend, &payload_binding_name(&label), ty);

            text.line(format!("{indent}{label}: {value},"));
        }
        Payload::Struct(fields) => {
            for field in fields {
                let label = field.label();
                let transport = payload_names.field_label(variant, field);
                let value = from_value(
                    schema,
                    backend,
                    &payload_binding_name(&transport),
                    &field.ty,
                );

                text.line(format!("{indent}{label}: {value},"));
            }
        }
    }

    text.finish()
}

/// Render required payload bindings.
fn render_payload_bindings(variant: &Variant, payload_names: &PayloadNames, value: &str) -> String {
    let mut text = Text::new();

    match &variant.payload {
        Payload::Unit => {}
        Payload::Tuple(_) => {
            let label = variant.payload_field_name();

            text.raw(render_required_binding(value, &label));
        }
        Payload::Struct(fields) => {
            for field in fields {
                let label = payload_names.field_label(variant, field);

                text.raw(render_required_binding(value, &label));
            }
        }
    }

    text.finish()
}

/// Render one required payload field binding.
fn render_required_binding(value: &str, label: &str) -> String {
    let mut text = Text::new();
    let binding = payload_binding_name(label);

    text.line(format!("        const {binding} = {value}.{label};"));
    text.line(format!("        if ({binding} == null) {{"));
    text.line(format!(
        "            throw new Error(\"{label} payload is missing\");"
    ));
    text.line("        }");
    text.blank();

    text.finish()
}

/// Return one payload local binding name.
fn payload_binding_name(label: &str) -> String {
    format!("payload_{label}")
}

/// Return payload values for one backend call.
fn payload_values(
    schema: &Schema,
    backend: Backend,
    variant: &Variant,
    value: &str,
) -> Vec<String> {
    match &variant.payload {
        Payload::Unit => Vec::new(),
        Payload::Tuple(ty) => {
            let label = variant.payload_field_name();
            let value = to_value(schema, backend, &format!("{value}.{label}"), ty);

            vec![value]
        }
        Payload::Struct(fields) => fields
            .iter()
            .map(|field| {
                let label = field.label();

                to_value(schema, backend, &format!("{value}.{label}"), &field.ty)
            })
            .collect(),
    }
}

/// Render one TypeScript function header.
fn render_function_header(function: &str, arguments: &[&str], output: &str) -> String {
    let arguments = arguments
        .iter()
        .filter(|argument| !argument.is_empty())
        .copied()
        .collect::<Vec<_>>();

    if arguments.len() == 1 && arguments[0].len() + function.len() + output.len() < 80 {
        return format!(
            "export function {function}({}): {output} {{\n",
            arguments[0]
        );
    }

    let mut text = Text::new();
    text.line(format!("export function {function}("));
    for argument in arguments {
        text.line(format!("    {argument},"));
    }
    text.line(format!("): {output} {{"));

    text.finish()
}

/// Render one WASM constructor call.
fn render_wasm_new(name: &str, values: Vec<String>) -> String {
    let inline = format!("    return new wasm.{name}({});\n", values.join(", "));
    if inline.len() <= 100 {
        return inline;
    }

    let mut text = Text::new();
    text.line(format!("    return new wasm.{name}("));
    for value in values {
        text.line(format!("        {value},"));
    }
    text.line("    );");

    text.finish()
}

/// Render one WASM payload constructor call.
fn render_wasm_payload_call(owner: &str, label: &str, values: Vec<String>) -> String {
    let inline = format!(
        "        return wasm.{owner}.{label}({});\n",
        values.join(", ")
    );
    if inline.len() <= 100 {
        return inline;
    }

    let mut text = Text::new();
    text.line(format!("        return wasm.{owner}.{label}("));
    for value in values {
        text.line(format!("            {value},"));
    }
    text.line("        );");

    text.finish()
}

/// Render one backend value expression.
fn to_value(schema: &Schema, backend: Backend, value: &str, ty: &Type) -> String {
    match ty {
        Type::Vec(ty) if matches!(ty.as_ref(), Type::U8) => match backend {
            Backend::Napi => format!("Array.from({value})"),
            Backend::Wasm => format!("Uint8Array.from({value})"),
        },
        Type::Vec(ty) => {
            let item = to_value(schema, backend, "item", ty);

            format!("{value}.map((item) => {item})")
        }
        Type::Option(ty) => {
            let item = to_value(schema, backend, value, ty);

            format!("{value} == null ? undefined : {item}")
        }
        Type::Named(name) if schema.items.contains_key(name) => {
            let function = to_name(backend, name);
            match backend {
                Backend::Napi => format!("{function}({value})"),
                Backend::Wasm => format!("{function}(wasm, {value})"),
            }
        }
        _ => value.to_string(),
    }
}

/// Render one public bridge value expression.
fn from_value(schema: &Schema, backend: Backend, value: &str, ty: &Type) -> String {
    match ty {
        Type::Vec(ty) if matches!(ty.as_ref(), Type::U8) => format!("Uint8Array.from({value})"),
        Type::Vec(ty) => {
            let item = from_value(schema, backend, "item", ty);

            format!("{value}.map((item) => {item})")
        }
        Type::Option(ty) => {
            let item = from_value(schema, backend, value, ty);

            format!("{value} == null ? undefined : {item}")
        }
        Type::Named(name) if schema.items.contains_key(name) => {
            let function = from_name(backend, name);

            format!("{function}({value})")
        }
        _ => value.to_string(),
    }
}

/// Return one backend type expression.
fn backend_type(schema: &Schema, backend: Backend, item: &Item) -> String {
    if schema.is_unit_enum(&item.name) {
        return "string".to_string();
    }

    format!("{}.{name}", backend.namespace(), name = item.name)
}

/// Return one backend conversion function name.
fn to_name(backend: Backend, name: &str) -> String {
    format!("to{}{name}", backend.stem())
}

/// Return one public bridge conversion function name.
fn from_name(backend: Backend, name: &str) -> String {
    format!("from{}{name}", backend.stem())
}

/// Return one backend label.
fn backend_label(backend: Backend) -> &'static str {
    match backend {
        Backend::Napi => "NAPI",
        Backend::Wasm => "WASM",
    }
}

/// Return the WASM module argument prefix.
fn wasm_argument(backend: Backend) -> &'static str {
    match backend {
        Backend::Napi => "",
        Backend::Wasm => "wasm: WasmModule",
    }
}

/// Return the import path from a backend adapter module to one DTO module.
fn backend_import_path(module: &SchemaModule) -> String {
    let path = target_segments(&module.path).join("/");

    format!("../{path}.js")
}
