[package]
name = "tspp_native"
description = "TS++ native code format and ABI"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
tspp_core = { workspace = true }
tspp_mir = { workspace = true }
tspp_serde = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true
