set shell := ["bash", "-cu"]
set windows-shell := ["C:/Program Files/Git/bin/bash.exe", "-cu"]
set dotenv-load := true
set dotenv-filename := "../.env.local"

_default:
    @just --list --unsorted

# build
build:
    just site/build
    just stack/check

# format
format:
    just site/format
    just stack/format

# check formatting
format-check:
    just site/format-check

# lint
lint:
    just site/lint

# test
test:
    just site/test

# check
check:
    just check-quick

# check quick
check-quick:
    just format-check
    just lint
    just test
    just stack/check

# check full
check-full:
    just check-quick

# diff
diff +deployment:
    just stack/diff {{deployment}}

# deploy
deploy:
    just site/build
    just site/deploy

# clean
clean:
    just site/clean
