set shell := ["bash", "-cu"]
set windows-shell := ["C:/Program Files/Git/bin/bash.exe", "-cu"]
set dotenv-load := true
set dotenv-filename := "../.env.local"

_default:
    @just --list --unsorted

# typecheck
typecheck:
    just site/typecheck
    just stack/typecheck
    just release/typecheck

# lint
lint:
    just site/lint
    just stack/lint
    just release/lint

# check formatting
format-check:
    just site/format-check
    just stack/format-check
    just release/format-check

# typecheck, lint and check formatting
check: typecheck lint format-check

# test
test:
    just site/test
    just stack/test
    just release/test

# format
format:
    just site/format
    just stack/format
    just release/format

# build the site and the release
build:
    just site/build
    just release/build

# plan a stack deployment
diff +deployment:
    just stack/diff {{deployment}}

# deploy the site
deploy:
    just site/build
    just site/deploy

# clean the site's outputs
clean:
    just site/clean
