set shell := ["bash", "-cu"]

# check
check:
    bun run check

# test
test:
    bun run test

# generate the token constants and text styles from tokens.json
generate:
    bun run generate

# format
format:
    bun run destack-check format src tests package.json destack.json
