# ruff: noqa

from typing import TYPE_CHECKING, Union

VERSION = "2025.04.23.1"

# import from all generated files
from .runtime_pb2 import *
from .health_pb2 import *
from .common_pb2 import *
from .common_grpc import *
from .lang_grpc import *
from .runtime_grpc import *
from .system_grpc import *
from .health_grpc import *
from .lang_pb2 import *
from .system_pb2 import *
from .computer_pb2 import *
from .computer_grpc import *
from .google.type.date_pb2 import *
from .google.type.timeofday_pb2 import *
from .google.type.datetime_pb2 import *

# extra utility types
AnyNodeData = Union[
    BenchData,
    HandleData,
    UserData,
    OrganizationData,
    ClientData,
    ScalerData,
    StoreData,
    ComputerData,
    FileData,
    StreamData,
    LinkData,
    PackageData,
    DependencyData,
    PageData,
    BlockData,
    ChoiceData,
    ClassData,
    FieldData,
    OptionData,
    TagData,
    FlowData,
    KitData,
    ActionData,
    TransitionData,
    TriggerData,
    DatabaseData,
    ChannelData,
    ThreadData,
    MessageData,
    NotificationData,
    TeamData,
    MembershipData,
    InviteData,
    RoleData,
    AgentData,
    SessionData,
    RunData,
    SpanData,
    InterruptionData,
    LogData,
    PlanData,
    TaskData,
    ClaimData,
    CursorData,
    ViewData,
    SpaceData,
    RecordData,
    SkipData,
    EmptyData,
]
AnyStructData = Union[
    ContextData,
    EditContextData,
    EditData,
    EditOperationData,
    ChangeData,
    ChangeVignetteData,
    GraphScopeData,
    ClientOriginData,
    NodeReferenceData,
    PropertyReferenceData,
    PolicyData,
    PolicyRuleData,
    PolicySubjectData,
    AccessZoneData,
    AccessMatrixData,
    AccessData,
    TypeData,
    TypeConstraintData,
    FileInfoData,
    IconData,
    ScheduleData,
    TextData,
    TextLineData,
    TextSpanData,
    CodeData,
    ExpressionData,
    AggregationResultData,
    SelectionData,
    SelectOptionsData,
    ErrorData,
    RunTraceData,
    RunFrameData,
    LinkPreviewData,
    ColorData,
    FontData,
    RectangleData,
    OffsetData,
    TransformData,
    Vector2Data,
    Vector3Data,
    Vector4Data,
    LineData,
    RectangleConstraintData,
]
AnyObjectData = AnyNodeData | AnyStructData
BenchNodeData = Union[
    BenchData,
    HandleData,
    ScalerData,
    StoreData,
    ComputerData,
    FileData,
    StreamData,
    LinkData,
    PackageData,
    DependencyData,
    PageData,
    BlockData,
    ChoiceData,
    ClassData,
    FieldData,
    OptionData,
    TagData,
    FlowData,
    KitData,
    ActionData,
    TransitionData,
    TriggerData,
    DatabaseData,
    ChannelData,
    ThreadData,
    MessageData,
    NotificationData,
    TeamData,
    MembershipData,
    InviteData,
    RoleData,
    AgentData,
    SessionData,
    RunData,
    SpanData,
    InterruptionData,
    LogData,
    PlanData,
    TaskData,
    ClaimData,
    CursorData,
    ViewData,
    SpaceData,
    RecordData,
]
ResourceNodeData = Union[ScalerData, StoreData, ComputerData, FileData, StreamData, LinkData]
SourceNodeData = Union[
    PackageData,
    DependencyData,
    PageData,
    BlockData,
    ChoiceData,
    ClassData,
    FieldData,
    OptionData,
    TagData,
    FlowData,
    KitData,
    ActionData,
    TransitionData,
    TriggerData,
    DatabaseData,
]
PageNodeData = Union[
    ScalerData,
    StoreData,
    ComputerData,
    FileData,
    StreamData,
    LinkData,
    PageData,
    ChoiceData,
    ClassData,
    TagData,
    FlowData,
    KitData,
    DatabaseData,
    ChannelData,
    ThreadData,
    TeamData,
    RoleData,
    AgentData,
    PlanData,
    TaskData,
    ViewData,
]
SubjectNodeData = Union[UserData, OrganizationData, ComputerData, AgentData]
JoinableNodeData = Union[PackageData, ChannelData, ThreadData, TeamData]
ClaimableNodeData = Union[
    ScalerData,
    StoreData,
    ComputerData,
    FileData,
    StreamData,
    LinkData,
    PageData,
    FlowData,
    KitData,
    ActionData,
    DatabaseData,
    AgentData,
    PlanData,
    TaskData,
    ViewData,
    RecordData,
]
OwnableNodeData = Union[
    BenchData,
    ScalerData,
    StoreData,
    ComputerData,
    FileData,
    StreamData,
    LinkData,
    PackageData,
    PageData,
    FlowData,
    KitData,
    DatabaseData,
    ThreadData,
    MessageData,
    AgentData,
    PlanData,
    TaskData,
    ClaimData,
    CursorData,
    ViewData,
    SpaceData,
    RecordData,
]
