# ruff: noqa

from typing import TYPE_CHECKING, Union

VERSION = "2025.05.15.1"

# import from all generated files
from .runtime_pb2 import *
from .health_pb2 import *
from .common_pb2 import *
from .common_grpc import *
from .lang_grpc import *
from .runtime_grpc import *
from .system_grpc import *
from .health_grpc import *
from .lang_pb2 import *
from .system_pb2 import *
from .computer_pb2 import *
from .computer_grpc import *
from .google.type.date_pb2 import *
from .google.type.timeofday_pb2 import *
from .google.type.datetime_pb2 import *

# extra utility types
AnyNodeData = Union[
    BenchData,
    HandleData,
    UserData,
    OrganizationData,
    ClientData,
    PackageData,
    DependencyData,
    PageData,
    BlockData,
    DatabaseData,
    ComputerData,
    ScalerData,
    ChoiceData,
    ClassData,
    FieldData,
    OptionData,
    TableData,
    RecordData,
    FileData,
    LinkData,
    ChannelData,
    ThreadData,
    MessageData,
    NotificationData,
    TaskData,
    ClaimData,
    CursorData,
    ServiceData,
    ActionData,
    FlowData,
    FlowEdgeData,
    AgentData,
    SessionData,
    RunData,
    SpanData,
    InterruptionData,
    MembershipData,
    InviteData,
    TeamData,
    RoleData,
    SpaceData,
    WizardViewData,
    FrameViewData,
    LabelViewData,
    SplitViewData,
    InputViewData,
    SliderViewData,
    ThreadViewData,
    ThemeData,
    ColorStyleData,
    TextStyleData,
    BorderStyleData,
    ShadowStyleData,
    GradientStyleData,
    TransitionStyleData,
    EffectStyleData,
    EmptyData,
]
AnyStructData = Union[
    ContextData,
    EditContextData,
    EditData,
    EditOperationData,
    ChangeData,
    ChangeVignetteData,
    GraphScopeData,
    ClientOriginData,
    NodeReferenceData,
    PropertyReferenceData,
    TypeData,
    TypeConstraintData,
    FileInfoData,
    ScheduleData,
    TextData,
    TextLineData,
    TextSpanData,
    CodeData,
    IconData,
    ExpressionData,
    AggregationResultData,
    SelectionData,
    SelectOptionsData,
    ErrorData,
    RunTraceData,
    RunFrameData,
    PolicyData,
    PolicyRuleData,
    PolicySubjectData,
    AccessZoneData,
    AccessMatrixData,
    AccessData,
    ColorData,
    ShadowData,
    BorderData,
    Vector2Data,
    Vector3Data,
    Vector4Data,
    GradientStopData,
    GradientData,
    FillData,
    LengthData,
    PositionData,
    TransitionData,
    EffectData,
]
AnyObjectData = AnyNodeData | AnyStructData
BenchNodeData = Union[
    BenchData,
    HandleData,
    PackageData,
    DependencyData,
    PageData,
    BlockData,
    DatabaseData,
    ComputerData,
    ScalerData,
    ChoiceData,
    ClassData,
    FieldData,
    OptionData,
    TableData,
    RecordData,
    FileData,
    LinkData,
    ChannelData,
    ThreadData,
    MessageData,
    NotificationData,
    TaskData,
    ClaimData,
    CursorData,
    ServiceData,
    ActionData,
    FlowData,
    FlowEdgeData,
    AgentData,
    SessionData,
    RunData,
    SpanData,
    InterruptionData,
    MembershipData,
    InviteData,
    TeamData,
    RoleData,
    SpaceData,
    WizardViewData,
    FrameViewData,
    LabelViewData,
    SplitViewData,
    InputViewData,
    SliderViewData,
    ThreadViewData,
    ThemeData,
    ColorStyleData,
    TextStyleData,
    BorderStyleData,
    ShadowStyleData,
    GradientStyleData,
    TransitionStyleData,
    EffectStyleData,
]
ResourceNodeData = Union[DatabaseData, ComputerData, ScalerData, FileData, LinkData]
PageNodeData = Union[
    PageData,
    DatabaseData,
    ComputerData,
    ScalerData,
    ChoiceData,
    ClassData,
    TableData,
    FileData,
    LinkData,
    ChannelData,
    ThreadData,
    TaskData,
    ServiceData,
    FlowData,
    AgentData,
    TeamData,
    RoleData,
    WizardViewData,
    FrameViewData,
    LabelViewData,
    SplitViewData,
    InputViewData,
    SliderViewData,
    ThreadViewData,
    ThemeData,
    ColorStyleData,
    TextStyleData,
    BorderStyleData,
    ShadowStyleData,
    GradientStyleData,
    TransitionStyleData,
    EffectStyleData,
]
SubjectNodeData = Union[UserData, OrganizationData, ComputerData, AgentData]
JoinableNodeData = Union[PackageData, ChannelData, ThreadData, TeamData]
ClaimableNodeData = Union[
    PageData,
    DatabaseData,
    ComputerData,
    ScalerData,
    TableData,
    RecordData,
    FileData,
    LinkData,
    TaskData,
    ServiceData,
    ActionData,
    FlowData,
    AgentData,
]
OwnableNodeData = Union[
    BenchData,
    PackageData,
    PageData,
    DatabaseData,
    ComputerData,
    ScalerData,
    TableData,
    RecordData,
    FileData,
    LinkData,
    ThreadData,
    MessageData,
    TaskData,
    ClaimData,
    CursorData,
    ServiceData,
    FlowData,
    AgentData,
    SpaceData,
]
ViewNodeData = Union[
    WizardViewData,
    FrameViewData,
    LabelViewData,
    SplitViewData,
    InputViewData,
    SliderViewData,
    ThreadViewData,
]
StyleNodeData = Union[
    ColorStyleData,
    TextStyleData,
    BorderStyleData,
    ShadowStyleData,
    GradientStyleData,
    TransitionStyleData,
    EffectStyleData,
]
