[package]
name = "destack_lang_libgen_rust"
description = "Destack Rust Library Code Generator"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"

[dependencies]
destack_lang_lex = { workspace = true }
destack_lang_parse = { workspace = true }
destack_lang_prelude = { workspace = true }

[dev-dependencies]
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }

[lints]
workspace = true
