[package]
name = "destack_heap"
description = "Destack Heap"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_core = { workspace = true }
destack_mir = { workspace = true }
libc = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive", "rc"] }

[lints]
workspace = true
