[package]
name = "tspp_memory"
description = "TS++ Memory"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
tspp_serde = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[target.'cfg(unix)'.dependencies]
tspp_signal = { workspace = true }
libc = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_Security", "Win32_System_Diagnostics_Debug", "Win32_System_Kernel", "Win32_System_Memory", "Win32_System_SystemInformation", "Win32_System_Threading"] }

[lints]
workspace = true
