[package]
name = "tspp_repository"
description = "TS++ Repository"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "generate-schema"
path = "src/bin/schema.rs"
required-features = ["schema"]

[features]
default = []
schema = ["schemars", "tspp_artifact/schema", "tspp_source/schema"]

[dependencies]
# language
tspp_artifact = { workspace = true }
tspp_core = { workspace = true }
tspp_dir = { workspace = true }
tspp_program = { workspace = true }
tspp_heap = { workspace = true }
tspp_mir = { workspace = true }
tspp_serde = { workspace = true }
tspp_source = { workspace = true }

# general
blake3 = { workspace = true }
dashmap = { workspace = true }
filetime = { workspace = true }
im = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }
parking_lot = { workspace = true }
regex = { workspace = true }
rustc-hash = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true, features = ["preserve_order"] }
smallvec = { workspace = true }

[target.'cfg(all(not(target_os = "wasi"), not(target_arch = "wasm32")))'.dependencies]
memmap2 = { workspace = true }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
js-sys = "0.3.81"
wasm-bindgen = { workspace = true }

[build-dependencies]
tspp_core = { workspace = true }
tspp_source = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }

[lints]
workspace = true
