/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, jsonArray, jsonField, jsonObject } from "../../../protocol/serde.js";
import type { TypeItem } from "./type_item.js";
import { decodeTypeItem, encodeTypeItem, fromJsonTypeItem, toJsonTypeItem } from "./type_item.js";

/** A supertypes request. */
export type SupertypesRequest = {
    /** The type item to expand. */
    readonly item: TypeItem;
};

export const SupertypesRequest = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: SupertypesRequest): void {
        encodeSupertypesRequest(writer, value);
    },

    /** Decode one SupertypesRequest. */
    decode(reader: BinaryReader): SupertypesRequest {
        return decodeSupertypesRequest(reader);
    },

    /** Return this value as JSON. */
    toJson(value: SupertypesRequest): Json {
        return toJsonSupertypesRequest(value);
    },

    /** Return one SupertypesRequest from one JSON value. */
    fromJson(value: Json): SupertypesRequest {
        return fromJsonSupertypesRequest(value);
    },
};

/** Encode one SupertypesRequest. */
export function encodeSupertypesRequest(writer: BinaryWriter, value: SupertypesRequest): void {
    encodeTypeItem(writer, value.item);
}

/** Decode one SupertypesRequest. */
export function decodeSupertypesRequest(reader: BinaryReader): SupertypesRequest {
    const item = decodeTypeItem(reader);

    return {
        item,
    };
}

/** Return one JSON value for one SupertypesRequest. */
export function toJsonSupertypesRequest(value: SupertypesRequest): Json {
    return {
        item: toJsonTypeItem(value.item),
    };
}

/** Return one SupertypesRequest from one JSON value. */
export function fromJsonSupertypesRequest(value: Json): SupertypesRequest {
    const object = jsonObject(value);

    return {
        item: fromJsonTypeItem(jsonField(object, "item")),
    };
}

/** A supertypes response. */
export type SupertypesResponse = {
    /** Type hierarchy items. */
    readonly items: ReadonlyArray<TypeItem>;
};

export const SupertypesResponse = {
    /** Encode this value. */
    encode(writer: BinaryWriter, value: SupertypesResponse): void {
        encodeSupertypesResponse(writer, value);
    },

    /** Decode one SupertypesResponse. */
    decode(reader: BinaryReader): SupertypesResponse {
        return decodeSupertypesResponse(reader);
    },

    /** Return this value as JSON. */
    toJson(value: SupertypesResponse): Json {
        return toJsonSupertypesResponse(value);
    },

    /** Return one SupertypesResponse from one JSON value. */
    fromJson(value: Json): SupertypesResponse {
        return fromJsonSupertypesResponse(value);
    },
};

/** Encode one SupertypesResponse. */
export function encodeSupertypesResponse(writer: BinaryWriter, value: SupertypesResponse): void {
    writer.writeUnsigned(value.items.length);
    for (const item0 of value.items) {
        encodeTypeItem(writer, item0);
    }
}

/** Decode one SupertypesResponse. */
export function decodeSupertypesResponse(reader: BinaryReader): SupertypesResponse {
    const items = (() => { const length0 = reader.readNumber(); const items0: Array<TypeItem> = []; for (let index = 0; index < length0; index += 1) { items0.push(decodeTypeItem(reader)); } return items0; })();

    return {
        items,
    };
}

/** Return one JSON value for one SupertypesResponse. */
export function toJsonSupertypesResponse(value: SupertypesResponse): Json {
    return {
        items: value.items.map((item0) => toJsonTypeItem(item0)),
    };
}

/** Return one SupertypesResponse from one JSON value. */
export function fromJsonSupertypesResponse(value: Json): SupertypesResponse {
    const object = jsonObject(value);

    return {
        items: jsonArray(jsonField(object, "items")).map((item0) => fromJsonTypeItem(item0)),
    };
}
