/* generated by destack_client_generate, do not edit */

import { BinaryReader, BinaryWriter, Json, SerdeError, jsonArray, jsonBigint, jsonBool, jsonField, jsonNumber, jsonObject, jsonOptional, jsonString } from "../../../protocol/serde.js";
import type { StringId } from "../../core/string.js";
import type { Name } from "./name.js";
import type { LocalNodeId } from "./node.js";
import type { FloatType } from "../type/primitive.js";
import type { IntegerType } from "../type/primitive.js";
import type { ScalarAlias } from "../type/primitive.js";
import { decodeStringId, encodeStringId, fromJsonStringId, toJsonStringId } from "../../core/string.js";
import { decodeName, encodeName, fromJsonName, toJsonName } from "./name.js";
import { decodeLocalNodeId, encodeLocalNodeId, fromJsonLocalNodeId, toJsonLocalNodeId } from "./node.js";
import { decodeFloatType, encodeFloatType, fromJsonFloatType, toJsonFloatType } from "../type/primitive.js";
import { decodeIntegerType, encodeIntegerType, fromJsonIntegerType, toJsonIntegerType } from "../type/primitive.js";
import { decodeScalarAlias, encodeScalarAlias, fromJsonScalarAlias, toJsonScalarAlias } from "../type/primitive.js";

/** A ScalarLiteral is literal scalar value. */
export type ScalarLiteral =
    /** Null value. */
    | {
          readonly kind: "null";
      }
    /** Undefined value. */
    | {
          readonly kind: "undefined";
      }
    /** Boolean value. */
    | {
          readonly kind: "boolean";
          readonly boolean: boolean;
      }
    /** Integer value. */
    | {
          readonly kind: "integer";
          readonly integer: bigint;
      }
    /** Bigint value. */
    | {
          readonly kind: "bigint";
          readonly bigint: bigint;
      }
    /** Float value. */
    | {
          readonly kind: "float";
          readonly float: number;
      }
    /** Character value. */
    | {
          readonly kind: "character";
          readonly character: string;
      }
    /** String value. */
    | {
          readonly kind: "string";
          readonly string: StringId;
      }
    /** Regex string value. */
    | {
          readonly kind: "regexString";
          readonly content: StringId;
          readonly flags?: StringId;
      }
;

export const ScalarLiteral = {
    /** Null value. */
    "null"(): ScalarLiteral {
        return { kind: "null" };
    },

    /** Undefined value. */
    "undefined"(): ScalarLiteral {
        return { kind: "undefined" };
    },

    /** Boolean value. */
    "boolean"(boolean_: boolean): ScalarLiteral {
        return { kind: "boolean", boolean: boolean_ };
    },

    /** Integer value. */
    integer(integer: bigint): ScalarLiteral {
        return { kind: "integer", integer };
    },

    /** Bigint value. */
    "bigint"(bigint_: bigint): ScalarLiteral {
        return { kind: "bigint", bigint: bigint_ };
    },

    /** Float value. */
    float(float: number): ScalarLiteral {
        return { kind: "float", float };
    },

    /** Character value. */
    character(character: string): ScalarLiteral {
        return { kind: "character", character };
    },

    /** String value. */
    "string"(string_: StringId): ScalarLiteral {
        return { kind: "string", string: string_ };
    },

    /** Regex string value. */
    regexString(content: StringId, flags: StringId | undefined): ScalarLiteral {
        return { kind: "regexString", content, flags };
    },

    /** Encode this value. */
    encode(writer: BinaryWriter, value: ScalarLiteral): void {
        encodeScalarLiteral(writer, value);
    },

    /** Decode one ScalarLiteral. */
    decode(reader: BinaryReader): ScalarLiteral {
        return decodeScalarLiteral(reader);
    },

    /** Return this value as JSON. */
    toJson(value: ScalarLiteral): Json {
        return toJsonScalarLiteral(value);
    },

    /** Return one ScalarLiteral from one JSON value. */
    fromJson(value: Json): ScalarLiteral {
        return fromJsonScalarLiteral(value);
    },
};

/** Encode one ScalarLiteral. */
export function encodeScalarLiteral(writer: BinaryWriter, value: ScalarLiteral): void {
    switch (value.kind) {
        case "null":
            writer.writeUnsigned(0);
            return;
        case "undefined":
            writer.writeUnsigned(1);
            return;
        case "boolean":
            writer.writeUnsigned(2);
            writer.writeBool(value.boolean);
            return;
        case "integer":
            writer.writeUnsigned(3);
            writer.writeSigned(value.integer);
            return;
        case "bigint":
            writer.writeUnsigned(4);
            writer.writeSigned(value.bigint);
            return;
        case "float":
            writer.writeUnsigned(5);
            writer.writeF64(value.float);
            return;
        case "character":
            writer.writeUnsigned(6);
            writer.writeChar(value.character);
            return;
        case "string":
            writer.writeUnsigned(7);
            encodeStringId(writer, value.string);
            return;
        case "regexString":
            writer.writeUnsigned(8);
            encodeStringId(writer, value.content);
            writer.writeOption(value.flags, (value1) => {
                encodeStringId(writer, value1);
            });
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one ScalarLiteral. */
export function decodeScalarLiteral(reader: BinaryReader): ScalarLiteral {
    const variant = reader.readNumber();

    switch (variant) {
        case 0: {
            return { kind: "null" };
        }
        case 1: {
            return { kind: "undefined" };
        }
        case 2: {
            const boolean_ = reader.readBool();

            return { kind: "boolean", boolean: boolean_ };
        }
        case 3: {
            const integer = reader.readSigned();

            return { kind: "integer", integer };
        }
        case 4: {
            const bigint_ = reader.readSigned();

            return { kind: "bigint", bigint: bigint_ };
        }
        case 5: {
            const float = reader.readF64();

            return { kind: "float", float };
        }
        case 6: {
            const character = reader.readChar();

            return { kind: "character", character };
        }
        case 7: {
            const string_ = decodeStringId(reader);

            return { kind: "string", string: string_ };
        }
        case 8: {
            const content = decodeStringId(reader);
            const flags = reader.readOption(() => decodeStringId(reader));

            return {
                kind: "regexString",
                content,
                ...(flags === undefined ? {} : { flags }),
            };
        }
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one ScalarLiteral. */
export function toJsonScalarLiteral(value: ScalarLiteral): Json {
    switch (value.kind) {
        case "null":
            return {
                kind: "null",
            };
        case "undefined":
            return {
                kind: "undefined",
            };
        case "boolean":
            return {
                kind: "boolean",
                boolean: value.boolean,
            };
        case "integer":
            return {
                kind: "integer",
                integer: value.integer.toString(),
            };
        case "bigint":
            return {
                kind: "bigint",
                bigint: value.bigint.toString(),
            };
        case "float":
            return {
                kind: "float",
                float: value.float,
            };
        case "character":
            return {
                kind: "character",
                character: value.character,
            };
        case "string":
            return {
                kind: "string",
                string: toJsonStringId(value.string),
            };
        case "regexString":
            return {
                kind: "regexString",
                content: toJsonStringId(value.content),
                ...(value.flags === undefined ? {} : { flags: toJsonStringId(value.flags) }),
            };
    }

    throw new SerdeError("unknown enum variant");
}

/** Return one ScalarLiteral from one JSON value. */
export function fromJsonScalarLiteral(value: Json): ScalarLiteral {
    const object = jsonObject(value);
    const kind = jsonString(jsonField(object, "kind"));

    switch (kind) {
        case "null":
            return {
                kind,
            };
        case "undefined":
            return {
                kind,
            };
        case "boolean":
            return {
                kind,
                boolean: jsonBool(jsonField(object, "boolean")),
            };
        case "integer":
            return {
                kind,
                integer: jsonBigint(jsonField(object, "integer")),
            };
        case "bigint":
            return {
                kind,
                bigint: jsonBigint(jsonField(object, "bigint")),
            };
        case "float":
            return {
                kind,
                float: jsonNumber(jsonField(object, "float")),
            };
        case "character":
            return {
                kind,
                character: jsonString(jsonField(object, "character")),
            };
        case "string":
            return {
                kind,
                string: fromJsonStringId(jsonField(object, "string")),
            };
        case "regexString":
            return {
                kind,
                content: fromJsonStringId(jsonField(object, "content")),
                flags: jsonOptional(object, "flags", (value) => fromJsonStringId(value)),
            };
    }

    throw new SerdeError(`unknown enum variant: ${kind}`);
}

/** A TemplateLiteral is literal template value. */
export type TemplateLiteral =
    /** Template string value. */
    | {
          readonly kind: "string";
          readonly string: StringId;
      }
    /** Interpolated template literal value. */
    | {
          readonly kind: "interpolatedString";
          readonly strings: ReadonlyArray<StringId>;
          readonly arguments: ReadonlyArray<LocalNodeId>;
      }
;

export const TemplateLiteral = {
    /** Template string value. */
    "string"(string_: StringId): TemplateLiteral {
        return { kind: "string", string: string_ };
    },

    /** Interpolated template literal value. */
    interpolatedString(strings: ReadonlyArray<StringId>, arguments_: ReadonlyArray<LocalNodeId>): TemplateLiteral {
        return { kind: "interpolatedString", strings, arguments: arguments_ };
    },

    /** Encode this value. */
    encode(writer: BinaryWriter, value: TemplateLiteral): void {
        encodeTemplateLiteral(writer, value);
    },

    /** Decode one TemplateLiteral. */
    decode(reader: BinaryReader): TemplateLiteral {
        return decodeTemplateLiteral(reader);
    },

    /** Return this value as JSON. */
    toJson(value: TemplateLiteral): Json {
        return toJsonTemplateLiteral(value);
    },

    /** Return one TemplateLiteral from one JSON value. */
    fromJson(value: Json): TemplateLiteral {
        return fromJsonTemplateLiteral(value);
    },
};

/** Encode one TemplateLiteral. */
export function encodeTemplateLiteral(writer: BinaryWriter, value: TemplateLiteral): void {
    switch (value.kind) {
        case "string":
            writer.writeUnsigned(0);
            encodeStringId(writer, value.string);
            return;
        case "interpolatedString":
            writer.writeUnsigned(1);
            writer.writeUnsigned(value.strings.length);
            for (const item0 of value.strings) {
                encodeStringId(writer, item0);
            }
            writer.writeUnsigned(value.arguments.length);
            for (const item1 of value.arguments) {
                encodeLocalNodeId(writer, item1);
            }
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one TemplateLiteral. */
export function decodeTemplateLiteral(reader: BinaryReader): TemplateLiteral {
    const variant = reader.readNumber();

    switch (variant) {
        case 0: {
            const string_ = decodeStringId(reader);

            return {
                kind: "string",
                string: string_,
            };
        }
        case 1: {
            const strings = (() => { const length0 = reader.readNumber(); const items0: Array<StringId> = []; for (let index = 0; index < length0; index += 1) { items0.push(decodeStringId(reader)); } return items0; })();
            const arguments_ = (() => { const length1 = reader.readNumber(); const items1: Array<LocalNodeId> = []; for (let index = 0; index < length1; index += 1) { items1.push(decodeLocalNodeId(reader)); } return items1; })();

            return {
                kind: "interpolatedString",
                strings,
                arguments: arguments_,
            };
        }
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one TemplateLiteral. */
export function toJsonTemplateLiteral(value: TemplateLiteral): Json {
    switch (value.kind) {
        case "string":
            return {
                kind: "string",
                string: toJsonStringId(value.string),
            };
        case "interpolatedString":
            return {
                kind: "interpolatedString",
                strings: value.strings.map((item0) => toJsonStringId(item0)),
                arguments: value.arguments.map((item0) => toJsonLocalNodeId(item0)),
            };
    }

    throw new SerdeError("unknown enum variant");
}

/** Return one TemplateLiteral from one JSON value. */
export function fromJsonTemplateLiteral(value: Json): TemplateLiteral {
    const object = jsonObject(value);
    const kind = jsonString(jsonField(object, "kind"));

    switch (kind) {
        case "string":
            return {
                kind,
                string: fromJsonStringId(jsonField(object, "string")),
            };
        case "interpolatedString":
            return {
                kind,
                strings: jsonArray(jsonField(object, "strings")).map((item0) => fromJsonStringId(item0)),
                arguments: jsonArray(jsonField(object, "arguments")).map((item0) => fromJsonLocalNodeId(item0)),
            };
    }

    throw new SerdeError(`unknown enum variant: ${kind}`);
}

/** A tree tag attribute. */
export type TreeAttribute =
    /** Named attribute with an optional value. */
    | {
          readonly kind: "named";
          readonly name: Name;
          readonly value?: TreeAttributeValue;
      }
    /** Spread attribute. */
    | {
          readonly kind: "spread";
          readonly value: LocalNodeId;
      }
    /** Malformed attribute slot. */
    | {
          readonly kind: "error";
      }
;

export const TreeAttribute = {
    /** Named attribute with an optional value. */
    named(name: Name, value: TreeAttributeValue | undefined): TreeAttribute {
        return { kind: "named", name, value };
    },

    /** Spread attribute. */
    spread(value: LocalNodeId): TreeAttribute {
        return { kind: "spread", value };
    },

    /** Malformed attribute slot. */
    error(): TreeAttribute {
        return { kind: "error" };
    },

    /** Encode this value. */
    encode(writer: BinaryWriter, value: TreeAttribute): void {
        encodeTreeAttribute(writer, value);
    },

    /** Decode one TreeAttribute. */
    decode(reader: BinaryReader): TreeAttribute {
        return decodeTreeAttribute(reader);
    },

    /** Return this value as JSON. */
    toJson(value: TreeAttribute): Json {
        return toJsonTreeAttribute(value);
    },

    /** Return one TreeAttribute from one JSON value. */
    fromJson(value: Json): TreeAttribute {
        return fromJsonTreeAttribute(value);
    },
};

/** Encode one TreeAttribute. */
export function encodeTreeAttribute(writer: BinaryWriter, value: TreeAttribute): void {
    switch (value.kind) {
        case "named":
            writer.writeUnsigned(0);
            encodeName(writer, value.name);
            writer.writeOption(value.value, (value1) => {
                encodeTreeAttributeValue(writer, value1);
            });
            return;
        case "spread":
            writer.writeUnsigned(1);
            encodeLocalNodeId(writer, value.value);
            return;
        case "error":
            writer.writeUnsigned(2);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one TreeAttribute. */
export function decodeTreeAttribute(reader: BinaryReader): TreeAttribute {
    const variant = reader.readNumber();

    switch (variant) {
        case 0: {
            const name = decodeName(reader);
            const value = reader.readOption(() => decodeTreeAttributeValue(reader));

            return {
                kind: "named",
                name,
                ...(value === undefined ? {} : { value }),
            };
        }
        case 1: {
            const value = decodeLocalNodeId(reader);

            return {
                kind: "spread",
                value,
            };
        }
        case 2: {
            return { kind: "error" };
        }
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one TreeAttribute. */
export function toJsonTreeAttribute(value: TreeAttribute): Json {
    switch (value.kind) {
        case "named":
            return {
                kind: "named",
                name: toJsonName(value.name),
                ...(value.value === undefined ? {} : { value: toJsonTreeAttributeValue(value.value) }),
            };
        case "spread":
            return {
                kind: "spread",
                value: toJsonLocalNodeId(value.value),
            };
        case "error":
            return {
                kind: "error",
            };
    }

    throw new SerdeError("unknown enum variant");
}

/** Return one TreeAttribute from one JSON value. */
export function fromJsonTreeAttribute(value: Json): TreeAttribute {
    const object = jsonObject(value);
    const kind = jsonString(jsonField(object, "kind"));

    switch (kind) {
        case "named":
            return {
                kind,
                name: fromJsonName(jsonField(object, "name")),
                value: jsonOptional(object, "value", (value) => fromJsonTreeAttributeValue(value)),
            };
        case "spread":
            return {
                kind,
                value: fromJsonLocalNodeId(jsonField(object, "value")),
            };
        case "error":
            return {
                kind,
            };
    }

    throw new SerdeError(`unknown enum variant: ${kind}`);
}

/** The value form of a tree tag attribute. */
export type TreeAttributeValue =
    /** Quoted string attribute value. */
    | {
          readonly kind: "string";
          readonly string: StringId;
      }
    /** Expression container attribute value. */
    | {
          readonly kind: "expression";
          readonly expression: LocalNodeId;
      }
;

export const TreeAttributeValue = {
    /** Quoted string attribute value. */
    "string"(string_: StringId): TreeAttributeValue {
        return { kind: "string", string: string_ };
    },

    /** Expression container attribute value. */
    expression(expression: LocalNodeId): TreeAttributeValue {
        return { kind: "expression", expression };
    },

    /** Encode this value. */
    encode(writer: BinaryWriter, value: TreeAttributeValue): void {
        encodeTreeAttributeValue(writer, value);
    },

    /** Decode one TreeAttributeValue. */
    decode(reader: BinaryReader): TreeAttributeValue {
        return decodeTreeAttributeValue(reader);
    },

    /** Return this value as JSON. */
    toJson(value: TreeAttributeValue): Json {
        return toJsonTreeAttributeValue(value);
    },

    /** Return one TreeAttributeValue from one JSON value. */
    fromJson(value: Json): TreeAttributeValue {
        return fromJsonTreeAttributeValue(value);
    },
};

/** Encode one TreeAttributeValue. */
export function encodeTreeAttributeValue(writer: BinaryWriter, value: TreeAttributeValue): void {
    switch (value.kind) {
        case "string":
            writer.writeUnsigned(0);
            encodeStringId(writer, value.string);
            return;
        case "expression":
            writer.writeUnsigned(1);
            encodeLocalNodeId(writer, value.expression);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one TreeAttributeValue. */
export function decodeTreeAttributeValue(reader: BinaryReader): TreeAttributeValue {
    const variant = reader.readNumber();

    switch (variant) {
        case 0: {
            const string_ = decodeStringId(reader);

            return { kind: "string", string: string_ };
        }
        case 1: {
            const expression = decodeLocalNodeId(reader);

            return { kind: "expression", expression };
        }
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one TreeAttributeValue. */
export function toJsonTreeAttributeValue(value: TreeAttributeValue): Json {
    switch (value.kind) {
        case "string":
            return {
                kind: "string",
                string: toJsonStringId(value.string),
            };
        case "expression":
            return {
                kind: "expression",
                expression: toJsonLocalNodeId(value.expression),
            };
    }

    throw new SerdeError("unknown enum variant");
}

/** Return one TreeAttributeValue from one JSON value. */
export function fromJsonTreeAttributeValue(value: Json): TreeAttributeValue {
    const object = jsonObject(value);
    const kind = jsonString(jsonField(object, "kind"));

    switch (kind) {
        case "string":
            return {
                kind,
                string: fromJsonStringId(jsonField(object, "string")),
            };
        case "expression":
            return {
                kind,
                expression: fromJsonLocalNodeId(jsonField(object, "expression")),
            };
    }

    throw new SerdeError(`unknown enum variant: ${kind}`);
}

/** A tree child. */
export type TreeChild =
    /** Raw tree text. */
    | {
          readonly kind: "text";
          readonly value: StringId;
      }
    /** Expression container child. */
    | {
          readonly kind: "expression";
          readonly value: LocalNodeId;
      }
    /** Spread expression container child. */
    | {
          readonly kind: "spread";
          readonly value: LocalNodeId;
      }
    /** Nested tree expression child. */
    | {
          readonly kind: "tree";
          readonly value: LocalNodeId;
      }
    /** Empty expression container child. */
    | {
          readonly kind: "empty";
      }
    /** Malformed child slot. */
    | {
          readonly kind: "error";
      }
;

export const TreeChild = {
    /** Raw tree text. */
    text(value: StringId): TreeChild {
        return { kind: "text", value };
    },

    /** Expression container child. */
    expression(value: LocalNodeId): TreeChild {
        return { kind: "expression", value };
    },

    /** Spread expression container child. */
    spread(value: LocalNodeId): TreeChild {
        return { kind: "spread", value };
    },

    /** Nested tree expression child. */
    tree(value: LocalNodeId): TreeChild {
        return { kind: "tree", value };
    },

    /** Empty expression container child. */
    empty(): TreeChild {
        return { kind: "empty" };
    },

    /** Malformed child slot. */
    error(): TreeChild {
        return { kind: "error" };
    },

    /** Encode this value. */
    encode(writer: BinaryWriter, value: TreeChild): void {
        encodeTreeChild(writer, value);
    },

    /** Decode one TreeChild. */
    decode(reader: BinaryReader): TreeChild {
        return decodeTreeChild(reader);
    },

    /** Return this value as JSON. */
    toJson(value: TreeChild): Json {
        return toJsonTreeChild(value);
    },

    /** Return one TreeChild from one JSON value. */
    fromJson(value: Json): TreeChild {
        return fromJsonTreeChild(value);
    },
};

/** Encode one TreeChild. */
export function encodeTreeChild(writer: BinaryWriter, value: TreeChild): void {
    switch (value.kind) {
        case "text":
            writer.writeUnsigned(0);
            encodeStringId(writer, value.value);
            return;
        case "expression":
            writer.writeUnsigned(1);
            encodeLocalNodeId(writer, value.value);
            return;
        case "spread":
            writer.writeUnsigned(2);
            encodeLocalNodeId(writer, value.value);
            return;
        case "tree":
            writer.writeUnsigned(3);
            encodeLocalNodeId(writer, value.value);
            return;
        case "empty":
            writer.writeUnsigned(4);
            return;
        case "error":
            writer.writeUnsigned(5);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one TreeChild. */
export function decodeTreeChild(reader: BinaryReader): TreeChild {
    const variant = reader.readNumber();

    switch (variant) {
        case 0: {
            const value = decodeStringId(reader);

            return {
                kind: "text",
                value,
            };
        }
        case 1: {
            const value = decodeLocalNodeId(reader);

            return {
                kind: "expression",
                value,
            };
        }
        case 2: {
            const value = decodeLocalNodeId(reader);

            return {
                kind: "spread",
                value,
            };
        }
        case 3: {
            const value = decodeLocalNodeId(reader);

            return {
                kind: "tree",
                value,
            };
        }
        case 4: {
            return { kind: "empty" };
        }
        case 5: {
            return { kind: "error" };
        }
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one TreeChild. */
export function toJsonTreeChild(value: TreeChild): Json {
    switch (value.kind) {
        case "text":
            return {
                kind: "text",
                value: toJsonStringId(value.value),
            };
        case "expression":
            return {
                kind: "expression",
                value: toJsonLocalNodeId(value.value),
            };
        case "spread":
            return {
                kind: "spread",
                value: toJsonLocalNodeId(value.value),
            };
        case "tree":
            return {
                kind: "tree",
                value: toJsonLocalNodeId(value.value),
            };
        case "empty":
            return {
                kind: "empty",
            };
        case "error":
            return {
                kind: "error",
            };
    }

    throw new SerdeError("unknown enum variant");
}

/** Return one TreeChild from one JSON value. */
export function fromJsonTreeChild(value: Json): TreeChild {
    const object = jsonObject(value);
    const kind = jsonString(jsonField(object, "kind"));

    switch (kind) {
        case "text":
            return {
                kind,
                value: fromJsonStringId(jsonField(object, "value")),
            };
        case "expression":
            return {
                kind,
                value: fromJsonLocalNodeId(jsonField(object, "value")),
            };
        case "spread":
            return {
                kind,
                value: fromJsonLocalNodeId(jsonField(object, "value")),
            };
        case "tree":
            return {
                kind,
                value: fromJsonLocalNodeId(jsonField(object, "value")),
            };
        case "empty":
            return {
                kind,
            };
        case "error":
            return {
                kind,
            };
    }

    throw new SerdeError(`unknown enum variant: ${kind}`);
}

/** A TypeLiteral is literal type. */
export type TypeLiteral =
    /** Never type `never`. */
    | {
          readonly kind: "never";
      }
    /** Uninitialized type and value. */
    | {
          readonly kind: "undefined";
      }
    /** Unknown type. */
    | {
          readonly kind: "unknown";
      }
    /** Void type. */
    | {
          readonly kind: "void";
      }
    /** Null type and value. */
    | {
          readonly kind: "null";
      }
    /** Boolean type. */
    | {
          readonly kind: "boolean";
      }
    /** Character type. */
    | {
          readonly kind: "character";
      }
    /** String type (unsized). */
    | {
          readonly kind: "string";
      }
    /** Bigint type (unsized). */
    | {
          readonly kind: "bigint";
      }
    /** `number`, the `float64` source alias. */
    | {
          readonly kind: "number";
      }
    /** A widthless source alias for a sized scalar, like `int` for `int64`. */
    | {
          readonly kind: "alias";
          readonly alias: ScalarAlias;
      }
    /** Width-spelled integer type, like `int32` or `usize`. */
    | {
          readonly kind: "integer";
          readonly integer: IntegerType;
      }
    /** Width-spelled floating-point type, like `float32`. */
    | {
          readonly kind: "float";
          readonly float: FloatType;
      }
;

export const TypeLiteral = {
    /** Never type `never`. */
    "never"(): TypeLiteral {
        return { kind: "never" };
    },

    /** Uninitialized type and value. */
    "undefined"(): TypeLiteral {
        return { kind: "undefined" };
    },

    /** Unknown type. */
    "unknown"(): TypeLiteral {
        return { kind: "unknown" };
    },

    /** Void type. */
    "void"(): TypeLiteral {
        return { kind: "void" };
    },

    /** Null type and value. */
    "null"(): TypeLiteral {
        return { kind: "null" };
    },

    /** Boolean type. */
    "boolean"(): TypeLiteral {
        return { kind: "boolean" };
    },

    /** Character type. */
    character(): TypeLiteral {
        return { kind: "character" };
    },

    /** String type (unsized). */
    "string"(): TypeLiteral {
        return { kind: "string" };
    },

    /** Bigint type (unsized). */
    "bigint"(): TypeLiteral {
        return { kind: "bigint" };
    },

    /** `number`, the `float64` source alias. */
    "number"(): TypeLiteral {
        return { kind: "number" };
    },

    /** A widthless source alias for a sized scalar, like `int` for `int64`. */
    alias(alias: ScalarAlias): TypeLiteral {
        return { kind: "alias", alias };
    },

    /** Width-spelled integer type, like `int32` or `usize`. */
    integer(integer: IntegerType): TypeLiteral {
        return { kind: "integer", integer };
    },

    /** Width-spelled floating-point type, like `float32`. */
    float(float: FloatType): TypeLiteral {
        return { kind: "float", float };
    },

    /** Encode this value. */
    encode(writer: BinaryWriter, value: TypeLiteral): void {
        encodeTypeLiteral(writer, value);
    },

    /** Decode one TypeLiteral. */
    decode(reader: BinaryReader): TypeLiteral {
        return decodeTypeLiteral(reader);
    },

    /** Return this value as JSON. */
    toJson(value: TypeLiteral): Json {
        return toJsonTypeLiteral(value);
    },

    /** Return one TypeLiteral from one JSON value. */
    fromJson(value: Json): TypeLiteral {
        return fromJsonTypeLiteral(value);
    },
};

/** Encode one TypeLiteral. */
export function encodeTypeLiteral(writer: BinaryWriter, value: TypeLiteral): void {
    switch (value.kind) {
        case "never":
            writer.writeUnsigned(0);
            return;
        case "undefined":
            writer.writeUnsigned(1);
            return;
        case "unknown":
            writer.writeUnsigned(2);
            return;
        case "void":
            writer.writeUnsigned(3);
            return;
        case "null":
            writer.writeUnsigned(4);
            return;
        case "boolean":
            writer.writeUnsigned(5);
            return;
        case "character":
            writer.writeUnsigned(6);
            return;
        case "string":
            writer.writeUnsigned(7);
            return;
        case "bigint":
            writer.writeUnsigned(8);
            return;
        case "number":
            writer.writeUnsigned(9);
            return;
        case "alias":
            writer.writeUnsigned(10);
            encodeScalarAlias(writer, value.alias);
            return;
        case "integer":
            writer.writeUnsigned(11);
            encodeIntegerType(writer, value.integer);
            return;
        case "float":
            writer.writeUnsigned(12);
            encodeFloatType(writer, value.float);
            return;
    }

    throw new SerdeError("unknown enum variant");
}

/** Decode one TypeLiteral. */
export function decodeTypeLiteral(reader: BinaryReader): TypeLiteral {
    const variant = reader.readNumber();

    switch (variant) {
        case 0: {
            return { kind: "never" };
        }
        case 1: {
            return { kind: "undefined" };
        }
        case 2: {
            return { kind: "unknown" };
        }
        case 3: {
            return { kind: "void" };
        }
        case 4: {
            return { kind: "null" };
        }
        case 5: {
            return { kind: "boolean" };
        }
        case 6: {
            return { kind: "character" };
        }
        case 7: {
            return { kind: "string" };
        }
        case 8: {
            return { kind: "bigint" };
        }
        case 9: {
            return { kind: "number" };
        }
        case 10: {
            const alias = decodeScalarAlias(reader);

            return { kind: "alias", alias };
        }
        case 11: {
            const integer = decodeIntegerType(reader);

            return { kind: "integer", integer };
        }
        case 12: {
            const float = decodeFloatType(reader);

            return { kind: "float", float };
        }
    }

    throw new SerdeError(`unknown enum variant index: ${variant}`);
}

/** Return one JSON value for one TypeLiteral. */
export function toJsonTypeLiteral(value: TypeLiteral): Json {
    switch (value.kind) {
        case "never":
            return {
                kind: "never",
            };
        case "undefined":
            return {
                kind: "undefined",
            };
        case "unknown":
            return {
                kind: "unknown",
            };
        case "void":
            return {
                kind: "void",
            };
        case "null":
            return {
                kind: "null",
            };
        case "boolean":
            return {
                kind: "boolean",
            };
        case "character":
            return {
                kind: "character",
            };
        case "string":
            return {
                kind: "string",
            };
        case "bigint":
            return {
                kind: "bigint",
            };
        case "number":
            return {
                kind: "number",
            };
        case "alias":
            return {
                kind: "alias",
                alias: toJsonScalarAlias(value.alias),
            };
        case "integer":
            return {
                kind: "integer",
                integer: toJsonIntegerType(value.integer),
            };
        case "float":
            return {
                kind: "float",
                float: toJsonFloatType(value.float),
            };
    }

    throw new SerdeError("unknown enum variant");
}

/** Return one TypeLiteral from one JSON value. */
export function fromJsonTypeLiteral(value: Json): TypeLiteral {
    const object = jsonObject(value);
    const kind = jsonString(jsonField(object, "kind"));

    switch (kind) {
        case "never":
            return {
                kind,
            };
        case "undefined":
            return {
                kind,
            };
        case "unknown":
            return {
                kind,
            };
        case "void":
            return {
                kind,
            };
        case "null":
            return {
                kind,
            };
        case "boolean":
            return {
                kind,
            };
        case "character":
            return {
                kind,
            };
        case "string":
            return {
                kind,
            };
        case "bigint":
            return {
                kind,
            };
        case "number":
            return {
                kind,
            };
        case "alias":
            return {
                kind,
                alias: fromJsonScalarAlias(jsonField(object, "alias")),
            };
        case "integer":
            return {
                kind,
                integer: fromJsonIntegerType(jsonField(object, "integer")),
            };
        case "float":
            return {
                kind,
                float: fromJsonFloatType(jsonField(object, "float")),
            };
    }

    throw new SerdeError(`unknown enum variant: ${kind}`);
}
