[package]
name = "dyst_language_ast"
description = "Dyst Language AST"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"
doctest = false

[dependencies]
dyst_language_source = { workspace = true }
dyst_language_token = { workspace = true }
dyst_language_arena = { workspace = true }
dyst_language_diagnostic = { workspace = true }
dyst_language_session = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
pprof = { workspace = true }

[lints]
workspace = true
