[package]
name = "destack_language_ast"
description = "Destack Language AST"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "rust/lib.rs"
doctest = false

[dependencies]
destack_language_token = { workspace = true }
destack_language_arena = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
pprof = { workspace = true }

[lints]
workspace = true
