[package]
name = "tspp_core"
description = "TS++ Core Primitives"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
blake3 = { workspace = true }
tspp_serde = { workspace = true }
parking_lot = { workspace = true }
indexmap = { workspace = true }
rustc-hash = { workspace = true }
smallvec = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
stacker = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
