[package]
name = "destack_workspace"
description = "Destack Workspace"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[[bin]]
name = "generate-schema"
path = "src/bin/schema.rs"
required-features = ["schema"]

[features]
default = []
schema = ["schemars", "destack_artifact/schema", "destack_source/schema"]

[dependencies]
# language
destack_artifact = { workspace = true }
destack_core = { workspace = true }
destack_dir = { workspace = true }
destack_heap = { workspace = true }
destack_mir = { workspace = true }
destack_source = { workspace = true }

# general
dashmap = { workspace = true }
filetime = { workspace = true }
im = "15.1.0"
indexmap = { workspace = true, features = ["serde"] }
parking_lot = { workspace = true }
regex = { workspace = true }
rustc-hash = { workspace = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive", "rc"] }
serde_json = { workspace = true, features = ["preserve_order"] }
tracing = { workspace = true }
postcard = { workspace = true }

[target.'cfg(all(not(target_os = "wasi"), not(target_arch = "wasm32")))'.dependencies]
fs2 = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }

[build-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["preserve_order"] }

[lints]
workspace = true
