[package]
name = "destack_workspace"
description = "Destack Workspace"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
destack_ast = { workspace = true }
destack_compiler = { workspace = true }
destack_dir = { workspace = true }
destack_fir = { workspace = true }
destack_javascript_transpiler = { workspace = true }
destack_mir = { workspace = true }
destack_parser = { workspace = true }
destack_source = { workspace = true }
destack_unicode = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
