[package]
name = "destack_workspace"
description = "Destack Workspace"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_artifact = { workspace = true }
destack_compiler = { workspace = true, default-features = false }
destack_core = { workspace = true }
destack_dir = { workspace = true }
destack_fir = { workspace = true }
destack_formatter = { workspace = true }
destack_heap = { workspace = true }
destack_json = { workspace = true }
destack_mir = { workspace = true }
destack_parser = { workspace = true }
destack_pattern = { workspace = true }
destack_program = { workspace = true }
destack_query = { workspace = true }
destack_session = { workspace = true, default-features = false }
destack_serde = { workspace = true }
destack_source = { workspace = true }
destack_vm = { workspace = true }
destack_repository = { path = "../repository", default-features = false }
destack_rpc = { workspace = true }

# general
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true, features = ["async-await", "executor"] }
parking_lot = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
smallvec = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
fs2 = { workspace = true }
destack_runtime = { workspace = true }

[features]
default = ["native"]
native = ["destack_compiler/native", "destack_session/native"]
deadlock-detection = ["destack_compiler/deadlock-detection"]

[lints]
workspace = true
