[package]
name = "destack_codegen_cranelift"
description = "Destack Codegen for Cranelift"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
doctest = false

[dependencies]
# language
destack_ast = { workspace = true }
destack_codegen_lib = { workspace = true }
destack_dir = { workspace = true }
destack_fir = { workspace = true }
destack_mir = { workspace = true }
destack_source = { workspace = true }
destack_workspace = { workspace = true }

# cranelift
cranelift-codegen = { workspace = true }
cranelift-frontend = { workspace = true }
cranelift-module = { workspace = true }
cranelift-native = { workspace = true }
cranelift-object = { workspace = true }
target-lexicon = { workspace = true }

# general
dashmap = { workspace = true }
parking_lot = { workspace = true }
rayon = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
