// generated by generate-bindings: do not edit

#include "../types.h"
#include "../jni.h"
#include "runtime.generated.h"

#include <deque>
#include <string>
#include <vector>

namespace {

std::deque<std::string> runtime_string_storage;

NativeStringRef string_ref_from_java(
    JNIEnv *env,
    jstring value,
    std::deque<std::string> *storage
) {
    if (value == nullptr) {
        return NativeStringRef {
            .data = nullptr,
            .len = 0,
        };
    }

    const char *chars = env->GetStringUTFChars(value, nullptr);
    if (chars == nullptr) {
        return NativeStringRef {
            .data = nullptr,
            .len = 0,
        };
    }

    jsize length = env->GetStringUTFLength(value);
    storage->emplace_back(chars, chars + length);
    env->ReleaseStringUTFChars(value, chars);

    const std::string &owned = storage->back();

    return NativeStringRef {
        .data = reinterpret_cast<const uint8_t *>(owned.data()),
        .len = static_cast<uint32_t>(owned.size()),
    };
}

LocationSample decode_LocationSample(JNIEnv *env, jobject value, std::deque<std::string> *string_storage);

jmethodID resolve_instance_method(
    JNIEnv *env,
    jobject value,
    const char *name,
    const char *signature
) {
    jclass value_class = env->GetObjectClass(value);
    if (value_class == nullptr) {
        return nullptr;
    }

    jmethodID method = env->GetMethodID(value_class, name, signature);
    env->DeleteLocalRef(value_class);

    return method;
}

jobject call_object_getter(
    JNIEnv *env,
    jobject value,
    const char *name,
    const char *signature
) {
    jmethodID method = resolve_instance_method(env, value, name, signature);
    if (method == nullptr) {
        return nullptr;
    }

    return env->CallObjectMethod(value, method);
}

jint call_int_getter(JNIEnv *env, jobject value, const char *name) {
    jmethodID method = resolve_instance_method(env, value, name, "()I");
    return method == nullptr ? 0 : env->CallIntMethod(value, method);
}

jlong call_long_getter(JNIEnv *env, jobject value, const char *name) {
    jmethodID method = resolve_instance_method(env, value, name, "()J");
    return method == nullptr ? 0 : env->CallLongMethod(value, method);
}

jdouble call_double_getter(JNIEnv *env, jobject value, const char *name) {
    jmethodID method = resolve_instance_method(env, value, name, "()D");
    return method == nullptr ? 0.0 : env->CallDoubleMethod(value, method);
}

jboolean call_boolean_getter(JNIEnv *env, jobject value, const char *name) {
    jmethodID method = resolve_instance_method(env, value, name, "()Z");
    return method == nullptr ? JNI_FALSE : env->CallBooleanMethod(value, method);
}

uint64_t decode_boxed_u64(JNIEnv *env, jobject value) {
    jmethodID method = resolve_instance_method(env, value, "longValue", "()J");
    return method == nullptr ? 0 : static_cast<uint64_t>(env->CallLongMethod(value, method));
}

jint call_list_size(JNIEnv *env, jobject value) {
    jmethodID method = resolve_instance_method(env, value, "size", "()I");
    return method == nullptr ? 0 : env->CallIntMethod(value, method);
}

jobject call_list_get(JNIEnv *env, jobject value, jint index) {
    jmethodID method = resolve_instance_method(env, value, "get", "(I)Ljava/lang/Object;");
    return method == nullptr ? nullptr : env->CallObjectMethod(value, method, index);
}

LocationSample decode_LocationSample(JNIEnv *env, jobject value, std::deque<std::string> *string_storage) {
    LocationSample decoded = {};

    decoded.latitude_degrees = static_cast<double>(call_double_getter(env, value, "getLatitudeDegrees"));

    decoded.longitude_degrees = static_cast<double>(call_double_getter(env, value, "getLongitudeDegrees"));

    decoded.altitude_meters = static_cast<double>(call_double_getter(env, value, "getAltitudeMeters"));

    decoded.horizontal_accuracy_meters = static_cast<double>(call_double_getter(env, value, "getHorizontalAccuracyMeters"));

    decoded.vertical_accuracy_meters = static_cast<double>(call_double_getter(env, value, "getVerticalAccuracyMeters"));

    decoded.speed_meters_per_second = static_cast<double>(call_double_getter(env, value, "getSpeedMetersPerSecond"));

    decoded.heading_degrees = static_cast<double>(call_double_getter(env, value, "getHeadingDegrees"));

    decoded.timestamp_unix_ns = static_cast<uint64_t>(call_long_getter(env, value, "getTimestampUnixNs"));


    return decoded;
}


}

/// Deliver one  deliver one location sample into one runtime session into the runtime ingress path.
static jlongArray nativeNotifyLocationSample(
    JNIEnv *env,
    jobject /* abi */,
    jlong sessionHandle,
    jstring watchId,
    jobject sample
) {
    runtime_string_storage.clear();

    NativeStringRef decoded_watch_id = string_ref_from_java(env, static_cast<jstring>(watchId), &runtime_string_storage);
    LocationSample decoded_sample = decode_LocationSample(env, sample, &runtime_string_storage);

    RuntimeStatus status = send_location_sample(
        static_cast<uint64_t>(sessionHandle),
        decoded_watch_id,
        decoded_sample
    );

    return runtime_status_array(env, status);
}

/// Register the location runtime ingress JNI methods.
bool register_location_runtime_natives(JNIEnv *env) {
    JNINativeMethod methods[] = {
        {
            const_cast<char *>("nativeNotifyLocationSample"),
            const_cast<char *>("(JLjava/lang/String;Ldev/destack/runtime/android/module/location/RuntimeLocationSample;)[J"),
            reinterpret_cast<void *>(nativeNotifyLocationSample),
        },
    };

    return register_native_methods(
        env,
        "dev/destack/runtime/android/bridge/ProcessRuntimeIngress",
        methods,
        static_cast<jint>(sizeof(methods) / sizeof(methods[0]))
    );
}
