name: Language Runtime Check (Windows)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  language-runtime-windows-check:
    name: Language Runtime Check (Windows)
    runs-on: windows-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Install Rust and just
        uses: ./.github/actions/setup-rust-just
        with:
          rust_components: clippy

      - name: Install Language Runtime Build Dependencies
        shell: powershell
        run: |
          choco install strawberryperl nasm -y --no-progress
          Add-Content -Path $env:GITHUB_PATH -Value 'C:\Strawberry\perl\bin'
          Add-Content -Path $env:GITHUB_PATH -Value 'C:\Program Files\NASM'

      - name: Check Language Runtime Build Dependencies
        shell: powershell
        run: |
          perl -v
          nasm -v

      - name: Check Language Runtime (Windows)
        run: just language/check-runtime-windows-msvc

      - name: Show sccache Stats
        if: always()
        shell: bash
        run: sccache --show-stats || true
