name: Runtime WASIp1

on:
  workflow_call:

permissions:
  contents: read

jobs:
  runtime-wasip1:
    name: Runtime WASIp1
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Setup Rust and just
        uses: ./.github/actions/setup-rust-just
        with:
          rust_targets: wasm32-wasip1

      - name: Check runtime on wasm32-wasip1
        run: just language/check-runtime-wasip1
