name: Runtime Windows

on:
  workflow_call:

permissions:
  contents: read

jobs:
  runtime-windows:
    name: Runtime Windows
    runs-on: windows-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Setup Rust and just
        uses: ./.github/actions/setup-rust-just
        with:
          rust_components: clippy

      - name: Check runtime on Windows
        run: just language/check-runtime-windows-msvc
