name: Runtime Check (macOS)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  runtime-macos-check:
    name: Runtime Check (macOS)
    runs-on: macos-14
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Install Rust and just
        uses: ./.github/actions/setup-rust-just
        with:
          rust_components: clippy

      - name: Check Runtime (macOS)
        run: just language/check-runtime-macos
