# generated client target, do not edit

from __future__ import annotations

from dataclasses import dataclass

from destack.protocol.serde import BinaryReader, BinaryWriter, Json

@dataclass(frozen=True, slots=True)
class ModuleLinted:
    """The realized module lint surface for one module profile."""
    def encode(self, writer: BinaryWriter) -> None: ...
    @classmethod
    def decode(cls, reader: BinaryReader) -> ModuleLinted: ...
    def to_json(self) -> Json: ...
    @classmethod
    def from_json(cls, value: Json) -> ModuleLinted: ...

def encode_module_linted(writer: BinaryWriter, value: ModuleLinted) -> None: ...
def decode_module_linted(reader: BinaryReader) -> ModuleLinted: ...
def to_json_module_linted(value: ModuleLinted) -> Json: ...
def from_json_module_linted(value: Json) -> ModuleLinted: ...

@dataclass(frozen=True, slots=True)
class PackageLinted:
    """The realized package lint surface for one package."""
    def encode(self, writer: BinaryWriter) -> None: ...
    @classmethod
    def decode(cls, reader: BinaryReader) -> PackageLinted: ...
    def to_json(self) -> Json: ...
    @classmethod
    def from_json(cls, value: Json) -> PackageLinted: ...

def encode_package_linted(writer: BinaryWriter, value: PackageLinted) -> None: ...
def decode_package_linted(reader: BinaryReader) -> PackageLinted: ...
def to_json_package_linted(value: PackageLinted) -> Json: ...
def from_json_package_linted(value: Json) -> PackageLinted: ...

@dataclass(frozen=True, slots=True)
class WorkspaceLinted:
    """The realized workspace lint surface."""
    def encode(self, writer: BinaryWriter) -> None: ...
    @classmethod
    def decode(cls, reader: BinaryReader) -> WorkspaceLinted: ...
    def to_json(self) -> Json: ...
    @classmethod
    def from_json(cls, value: Json) -> WorkspaceLinted: ...

def encode_workspace_linted(writer: BinaryWriter, value: WorkspaceLinted) -> None: ...
def decode_workspace_linted(reader: BinaryReader) -> WorkspaceLinted: ...
def to_json_workspace_linted(value: WorkspaceLinted) -> Json: ...
def from_json_workspace_linted(value: Json) -> WorkspaceLinted: ...

__all__ = [
    "ModuleLinted",
    "encode_module_linted",
    "decode_module_linted",
    "to_json_module_linted",
    "from_json_module_linted",
    "PackageLinted",
    "encode_package_linted",
    "decode_package_linted",
    "to_json_package_linted",
    "from_json_package_linted",
    "WorkspaceLinted",
    "encode_workspace_linted",
    "decode_workspace_linted",
    "to_json_workspace_linted",
    "from_json_workspace_linted",
]
