# generated client target, do not edit

from __future__ import annotations

from ..._generated.mir.analyses.link_graph import (
    CallComponentGraph,
    LinkEdge,
    LinkEdgeKind,
    LinkGraph,
    LinkNode,
    LinkNodeFunction,
    LinkNodeGlobal,
    decode_call_component_graph,
    decode_link_edge,
    decode_link_edge_kind,
    decode_link_graph,
    decode_link_node,
    encode_call_component_graph,
    encode_link_edge,
    encode_link_edge_kind,
    encode_link_graph,
    encode_link_node,
    from_json_call_component_graph,
    from_json_link_edge,
    from_json_link_edge_kind,
    from_json_link_graph,
    from_json_link_node,
    to_json_call_component_graph,
    to_json_link_edge,
    to_json_link_edge_kind,
    to_json_link_graph,
    to_json_link_node,
)

__all__ = [
    "CallComponentGraph",
    "encode_call_component_graph",
    "decode_call_component_graph",
    "to_json_call_component_graph",
    "from_json_call_component_graph",
    "LinkGraph",
    "encode_link_graph",
    "decode_link_graph",
    "to_json_link_graph",
    "from_json_link_graph",
    "LinkNode",
    "encode_link_node",
    "decode_link_node",
    "to_json_link_node",
    "from_json_link_node",
    "LinkNodeFunction",
    "LinkNodeGlobal",
    "LinkEdge",
    "encode_link_edge",
    "decode_link_edge",
    "to_json_link_edge",
    "from_json_link_edge",
    "LinkEdgeKind",
    "encode_link_edge_kind",
    "decode_link_edge_kind",
    "to_json_link_edge_kind",
    "from_json_link_edge_kind",
]
