from __future__ import annotations

from collections.abc import Sequence

from .._generated.dir.symbol.scope import LocalScope, LocalScopeId, Scope
from .._generated.dir.symbol.symbol import LocalSymbolId, Symbol
from .._generated.dir.table.binding import BindingSegment
from .._generated.dir.tree.node import GlobalNodeIdAny
from .._generated.source.file.model.module import ModuleId

class BindingTable:
    """Cumulative lexical scopes and symbols for one DIR module."""

    module_id: ModuleId
    segments: tuple[BindingSegment, ...]

    def __init__(self, segments: Sequence[BindingSegment]) -> None: ...
    @classmethod
    def from_segments(cls, *segments: BindingSegment) -> BindingTable: ...
    def symbol_count(self) -> int: ...
    def scope_count(self) -> int: ...
    def symbol(self, symbol_id: LocalSymbolId) -> Symbol: ...
    def symbol_maybe(self, symbol_id: LocalSymbolId) -> Symbol | None: ...
    def scope(self, scope_id: LocalScopeId) -> Scope: ...
    def scope_maybe(self, scope_id: LocalScopeId) -> Scope | None: ...
    def declaration_symbol(
        self, declaration: GlobalNodeIdAny
    ) -> LocalSymbolId | None: ...
    def implicit_receiver_symbol(
        self, owner: GlobalNodeIdAny
    ) -> LocalSymbolId | None: ...
    def scope_for_node(self, node: GlobalNodeIdAny) -> LocalScope | None: ...
    def scope_for_owner(self, owner: LocalSymbolId) -> LocalScope | None: ...

__all__: list[str]
