syntax = "proto3";

package symbol.bench;

import "bench-proto/language.proto";

// Persistent per client/place.
// NOTE: PersistentInfo is not cleared across user logouts.
message PersistentInfo {
  string placeId = 1;
}

// Web-local information about the active User.
message UserInfo {
  string id = 1;
  string slug = 2;
  string email = 3;
  string name = 4;
  IconData icon = 5;
}

// Web-local information about the active Client.
message ClientInfo {
  string id = 1;
  string access_token = 2;
}

// Web-local information about an active Badge.
message BadgeInfo {
  string id = 1;
  NodeReferenceData package_ptr = 2;
  string key = 3;
  optional string password = 4;
}

message LocalGraph {
  SomeNodeData root = 1;
  repeated SomeNodeData nodes = 2;
}

// Web-local developer settings.
message DeveloperSettings {
  bool is_developer_mode = 1;
}

// All the locally stored data.
// All fields must be messages (may be repeated). :LocalStorageEncoding
message LocalStorage {
  //
  // Auth
  //

  // Stuff persisted forever (ideally, per browser).
  optional PersistentInfo persistent_info = 1;
  // Current logged in user.
  optional UserInfo user_info = 3;
  // Current logged in client.
  optional ClientInfo client_info = 4;
  // All configured badges.
  repeated BadgeInfo badges = 5;

  //
  // Space/Bench
  //

  // The current Space. May be local if not in a current Bench.
  optional NodeReferenceData space_ptr = 10;
  // The current Bench.
  optional NodeReferenceData bench_ptr = 11;
  // The Bench->Package mapping for known Benches.
  repeated NodeReferenceData package_ptrs = 12;
  // The Bench->Space mapping for known Benches.
  repeated NodeReferenceData space_ptrs = 13;
  // Any local graphs.
  repeated LocalGraph local_graphs = 15;

  //
  // Debug
  //

  optional DeveloperSettings developer_settings = 20;
}