use super::abi::android_named_type;
use super::cpp::{
    android_cpp_callback_field_name, render_cpp_parameter_declaration, render_cpp_type,
};
use super::docs::push_cpp_doc_comment;
use super::kotlin::{render_kotlin_runtime_abi, render_kotlin_runtime_bridge};
use crate::host::model::{HostArtifact, HostCatalog, HostPlatform};
use crate::platform::model::WorkspaceLayout;
use destack_runtime::host::abi::describe::{
    HostAbiEnumRepresentation, HostAbiField, HostAbiModule, HostAbiNamedType,
    HostAbiNamedTypeDefinition, HostAbiType,
};

/// Render the generated Android bridge binding files.
pub(crate) fn render_binding_files(
    layout: &WorkspaceLayout,
    generated_catalog: &HostCatalog,
) -> Vec<HostArtifact> {
    let generated_modules: Vec<_> = generated_catalog
        .modules_for_platform(HostPlatform::Android)
        .into_iter()
        .map(|module| module.abi().clone())
        .collect();
    vec![
        HostArtifact {
            path: layout
                .language_root
                .join("runtime/android/kotlin/src/main/kotlin/dev/destack/runtime/android/bridge/RuntimeAbi.generated.kt"),
            contents: render_kotlin_runtime_abi(
                generated_catalog.runtime_ingresses(HostPlatform::Android),
            ),
        },
        HostArtifact {
            path: layout
                .language_root
                .join("runtime/android/kotlin/src/main/kotlin/dev/destack/runtime/android/bridge/RuntimeBridge.generated.kt"),
            contents: render_kotlin_runtime_bridge(&generated_modules),
        },
        HostArtifact {
            path: layout
                .language_root
                .join("runtime/android/kotlin/src/main/cpp/bridge/loader.h"),
            contents: render_loader_header(generated_catalog),
        },
        HostArtifact {
            path: layout
                .language_root
                .join("runtime/android/kotlin/src/main/cpp/bridge/loader.cpp"),
            contents: render_loader_source(generated_catalog),
        },
        HostArtifact {
            path: layout
                .language_root
                .join("runtime/android/kotlin/src/main/cpp/bridge/types.generated.h"),
            contents: render_types_generated_header(generated_catalog, &generated_modules),
        },
        HostArtifact {
            path: layout
                .language_root
                .join("runtime/android/kotlin/src/main/cpp/bridge/registry.generated.h"),
            contents: render_registry_generated_header(generated_catalog, &generated_modules),
        },
    ]
}

/// Render one generated Android types header.
fn render_types_generated_header(
    generated_catalog: &HostCatalog,
    generated_modules: &[HostAbiModule],
) -> String {
    let mut output = String::new();
    output.push_str("// generated by generate-bindings: do not edit\n\n");
    output.push_str("#ifndef DESTACK_RUNTIME_ANDROID_BRIDGE_TYPES_GENERATED_H\n");
    output.push_str("#define DESTACK_RUNTIME_ANDROID_BRIDGE_TYPES_GENERATED_H\n\n");

    render_android_abi_types(&mut output, generated_modules);
    output.push('\n');
    render_android_generated_types(&mut output, generated_catalog, generated_modules);
    output.push_str("\n#endif\n");
    output
}

/// Render the generated Android ABI types.
fn render_android_abi_types(output: &mut String, generated_modules: &[HostAbiModule]) {
    for module in generated_modules {
        for named_type in &module.types {
            render_android_named_type_forward_declaration(output, named_type);
        }
    }

    if !generated_modules.is_empty() {
        output.push('\n');
    }

    for generated_type in collect_android_generated_slice_types(generated_modules) {
        render_android_generated_slice_type(output, &generated_type);
        output.push('\n');
    }

    for module in generated_modules {
        for named_type in &module.types {
            render_android_named_type(output, named_type);
            output.push('\n');
        }
    }
}

/// Render the generated Android bridge files for one module.
fn render_loader_header(generated_catalog: &HostCatalog) -> String {
    let mut output = String::new();
    output.push_str("// generated by generate-bindings: do not edit\n\n");
    output.push_str("#ifndef DESTACK_RUNTIME_ANDROID_BRIDGE_LOADER_H\n");
    output.push_str("#define DESTACK_RUNTIME_ANDROID_BRIDGE_LOADER_H\n\n");
    output.push_str("#include \"types.h\"\n\n");
    output.push_str("/// The resolved runtime bridge bindings for this process.\n");
    output.push_str("struct RuntimeBindings {\n");
    output.push_str("    /// The runtime function that registers one mobile bridge callback table for one session.\n");
    output
        .push_str("    RegisterRuntimeBridgeBindingsFunction register_runtime_bridge_bindings;\n");
    output.push_str("    /// The runtime function that unregisters one mobile bridge callback table for one session.\n");
    output.push_str(
        "    UnregisterRuntimeBridgeBindingsFunction unregister_runtime_bridge_bindings;\n",
    );

    for spec in generated_catalog.runtime_bindings() {
        output.push_str(&format!("    /// {}\n", spec.documentation));
        output.push_str(&format!("    {} {};\n", spec.type_name, spec.field_name));
    }

    output.push_str("};\n\n");
    output.push_str("/// Resolve the runtime bridge bindings from the current process.\n");
    output.push_str("uint32_t resolve_runtime_bindings(RuntimeBindings *out_bindings);\n\n");
    output.push_str("#endif\n");
    output
}

/// Render one generated Android loader source.
fn render_loader_source(generated_catalog: &HostCatalog) -> String {
    let mut output = String::new();
    output.push_str("// generated by generate-bindings: do not edit\n\n");
    output.push_str("#include \"types.h\"\n");
    output.push_str("#include \"loader.h\"\n\n");
    output.push_str("#include <dlfcn.h>\n");
    output.push_str("#include <stdlib.h>\n\n");
    output.push_str("extern \"C\" {\n");
    output.push_str("uint32_t destack_host_android_register_runtime_bridge_bindings(\n");
    output.push_str("    uint64_t session_handle,\n");
    output.push_str("    AndroidRuntimeBridgeBindings callbacks\n");
    output.push_str(") __attribute__((weak));\n");
    output.push_str("void destack_host_android_unregister_runtime_bridge_bindings(\n");
    output.push_str("    uint64_t session_handle\n");
    output.push_str(") __attribute__((weak));\n");

    for spec in generated_catalog.runtime_bindings() {
        output.push('\n');
        output.push_str(&format!(
            "{} destack_host_android_{}(\n",
            spec.result_type.android_name(),
            spec.field_name
        ));

        if spec.parameters.is_empty() {
            output.push_str("    void\n");
        } else {
            for (index, parameter) in spec.parameters.iter().enumerate() {
                let trailing = if index + 1 == spec.parameters.len() {
                    ""
                } else {
                    ","
                };
                let declaration = render_cpp_parameter_declaration(
                    parameter.ty.android_name(),
                    parameter.name,
                );
                output.push_str(&format!("    {declaration}{trailing}\n"));
            }
        }

        output.push_str(") __attribute__((weak));\n");
    }

    output.push_str("}\n\n");
    output.push_str("namespace {\n\n");
    output.push_str("void *symbol_handle = nullptr;\n");
    output.push_str("RuntimeBindings runtime_bindings = {\n");
    output.push_str("    .register_runtime_bridge_bindings = nullptr,\n");
    output.push_str("    .unregister_runtime_bridge_bindings = nullptr,\n");

    for spec in generated_catalog.runtime_bindings() {
        output.push_str(&format!("    .{} = nullptr,\n", spec.field_name));
    }

    output.push_str("};\n\n");
    output.push_str("template <typename SymbolFunction>\n");
    output.push_str(
        "void resolve_symbol_once(SymbolFunction *slot, void *handle, const char *name) {\n",
    );
    output.push_str("    if (*slot != nullptr) {\n");
    output.push_str("        return;\n");
    output.push_str("    }\n\n");
    output.push_str("    *slot = reinterpret_cast<SymbolFunction>(dlsym(handle, name));\n");
    output.push_str("}\n\n");
    output.push_str("/// Resolve one directly linked runtime binding table.\n");
    output.push_str("bool resolve_linked_runtime_bindings(RuntimeBindings *out_bindings) {\n");
    output.push_str("    RuntimeBindings bindings = {\n");
    output.push_str(
        "        .register_runtime_bridge_bindings = destack_host_android_register_runtime_bridge_bindings,\n",
    );
    output.push_str(
        "        .unregister_runtime_bridge_bindings = destack_host_android_unregister_runtime_bridge_bindings,\n",
    );

    for spec in generated_catalog.runtime_bindings() {
        output.push_str(&format!(
            "        .{} = destack_host_android_{},\n",
            spec.field_name, spec.field_name
        ));
    }

    output.push_str("    };\n\n");
    output.push_str("    if (\n");
    output.push_str("        bindings.register_runtime_bridge_bindings == nullptr ||\n");
    output.push_str("        bindings.unregister_runtime_bridge_bindings == nullptr");

    for spec in generated_catalog.runtime_bindings() {
        output.push_str(&format!(
            " ||\n        bindings.{} == nullptr",
            spec.field_name
        ));
    }

    output.push_str("\n    ) {\n");
    output.push_str("        return false;\n");
    output.push_str("    }\n\n");
    output.push_str("    *out_bindings = bindings;\n\n");
    output.push_str("    return true;\n");
    output.push_str("}\n\n");
    output.push_str("/// Resolve the runtime symbol handle for this process.\n");
    output.push_str("void *resolve_symbol_handle() {\n");
    output.push_str("    if (symbol_handle != nullptr) {\n");
    output.push_str("        return symbol_handle;\n");
    output.push_str("    }\n\n");
    output.push_str(
        "    const char *library_path = getenv(\"DESTACK_RUNTIME_HOST_BRIDGE_LIBRARY\");\n",
    );
    output.push_str("    if (library_path != nullptr && library_path[0] != '\\0') {\n");
    output.push_str("        symbol_handle = dlopen(library_path, RTLD_NOW | RTLD_GLOBAL);\n");
    output.push_str("        if (symbol_handle != nullptr) {\n");
    output.push_str("            return symbol_handle;\n");
    output.push_str("        }\n");
    output.push_str("    }\n\n");
    output.push_str("    return nullptr;\n");
    output.push_str("}\n\n");
    output.push_str("}\n\n");
    output.push_str("/// Resolve the runtime bridge bindings from the current process.\n");
    output.push_str("uint32_t resolve_runtime_bindings(RuntimeBindings *out_bindings) {\n");
    output.push_str("    if (resolve_linked_runtime_bindings(out_bindings)) {\n");
    output.push_str("        return HOST_STATUS_OK;\n");
    output.push_str("    }\n\n");
    output.push_str("    void *handle = resolve_symbol_handle();\n");
    output.push_str("    if (handle == nullptr) {\n");
    output.push_str("        return HOST_STATUS_NOT_FOUND;\n");
    output.push_str("    }\n\n");
    output.push_str("    resolve_symbol_once(&runtime_bindings.register_runtime_bridge_bindings, handle, \"destack_host_android_register_runtime_bridge_bindings\");\n");
    output.push_str("    resolve_symbol_once(&runtime_bindings.unregister_runtime_bridge_bindings, handle, \"destack_host_android_unregister_runtime_bridge_bindings\");\n");

    for spec in generated_catalog.runtime_bindings() {
        output.push_str(&format!(
            "    resolve_symbol_once(&runtime_bindings.{}, handle, \"destack_host_android_{}\");\n",
            spec.field_name, spec.field_name
        ));
    }

    output.push_str("\n    if (\n");
    output.push_str("        runtime_bindings.register_runtime_bridge_bindings == nullptr ||\n");
    output.push_str("        runtime_bindings.unregister_runtime_bridge_bindings == nullptr");

    for spec in generated_catalog.runtime_bindings() {
        output.push_str(&format!(
            " ||\n        runtime_bindings.{} == nullptr",
            spec.field_name
        ));
    }

    output.push_str("\n    ) {\n");
    output.push_str("        return HOST_STATUS_NOT_FOUND;\n");
    output.push_str("    }\n\n");
    output.push_str("    *out_bindings = runtime_bindings;\n\n");
    output.push_str("    return 0;\n");
    output.push_str("}\n");
    output
}

/// Render the generated Android callback types.
fn render_android_generated_types(
    output: &mut String,
    generated_catalog: &HostCatalog,
    generated_modules: &[HostAbiModule],
) {
    for module in generated_modules {
        render_android_generated_callback_struct(output, module);
        output.push('\n');
    }

    push_cpp_doc_comment(
        output,
        "The mobile runtime-bridge callbacks registered for one runtime session",
        0,
    );
    output.push_str("struct AndroidRuntimeBridgeBindings {\n");

    for lane in generated_catalog.bridge_lanes(HostPlatform::Android) {
        push_cpp_doc_comment(output, &format!("The {} callbacks", lane.field_name), 4);
        output.push_str(&format!(
            "    {} {};\n",
            lane.callback_type, lane.field_name
        ));
    }

    output.push_str("};\n\n");
    push_cpp_doc_comment(
        output,
        "The runtime function that registers one mobile bridge callback table for one session",
        0,
    );
    output.push_str("using RegisterRuntimeBridgeBindingsFunction =\n");
    output.push_str(
        "    uint32_t (*)(uint64_t session_handle, AndroidRuntimeBridgeBindings callbacks);\n",
    );
    push_cpp_doc_comment(
        output,
        "The runtime function that unregisters one mobile bridge callback table for one session",
        0,
    );
    output.push_str("using UnregisterRuntimeBridgeBindingsFunction =\n");
    output.push_str("    void (*)(uint64_t session_handle);\n");

    for spec in generated_catalog.runtime_bindings() {
        output.push('\n');
        push_cpp_doc_comment(output, spec.documentation, 0);
        output.push_str(&format!("using {} =\n", spec.type_name));
        output.push_str(&format!("    {} (*)(", spec.result_type.android_name()));

        if spec.parameters.is_empty() {
            output.push_str("void");
        } else {
            output.push('\n');

            for (index, parameter) in spec.parameters.iter().enumerate() {
                let trailing = if index + 1 == spec.parameters.len() {
                    ""
                } else {
                    ","
                };
                let declaration =
                    render_cpp_parameter_declaration(parameter.ty.android_name(), parameter.name);
                output.push_str(&format!("        {declaration}{trailing}\n"));
            }

            output.push_str("    ");
        }

        output.push_str(");\n");
    }
}

/// Render one generated Android registry header.
fn render_registry_generated_header(
    generated_catalog: &HostCatalog,
    generated_modules: &[HostAbiModule],
) -> String {
    let mut output = String::new();
    output.push_str("// generated by generate-bindings: do not edit\n\n");
    output.push_str("#ifndef DESTACK_RUNTIME_ANDROID_BRIDGE_REGISTRY_GENERATED_H\n");
    output.push_str("#define DESTACK_RUNTIME_ANDROID_BRIDGE_REGISTRY_GENERATED_H\n\n");
    output.push_str("#include \"types.h\"\n");

    for module in generated_modules {
        output.push_str(&format!(
            "#include \"{}/callbacks.generated.h\"\n",
            module.name
        ));
        output.push_str(&format!(
            "#include \"{}/runtime.generated.h\"\n",
            module.name
        ));
    }

    output.push('\n');
    output.push_str("/// Resolve the generated bridge methods from one runtime bridge instance.\n");
    output
        .push_str("inline bool resolve_generated_bridge_methods(JNIEnv *env, jobject bridge) {\n");

    if generated_modules.is_empty() {
        output.push_str("    return true;\n");
    } else {
        output.push_str("    return\n");

        for (index, module) in generated_modules.iter().enumerate() {
            let trailing = if index + 1 == generated_modules.len() {
                ";"
            } else {
                " &&"
            };
            output.push_str(&format!(
                "        resolve_{}_methods(env, bridge){}\n",
                module.name, trailing
            ));
        }
    }

    output.push_str("}\n\n");
    output.push_str("/// Register the generated runtime ingress JNI methods.\n");
    output.push_str("inline bool register_generated_runtime_bridge_natives(JNIEnv *env) {\n");

    let native_modules: Vec<_> = generated_modules
        .iter()
        .filter(|module| module.name == "intent" || !module.ingress.is_empty())
        .collect();

    if native_modules.is_empty() {
        output.push_str("    return true;\n");
    } else {
        output.push_str("    return\n");

        for (index, module) in native_modules.iter().enumerate() {
            let trailing = if index + 1 == native_modules.len() {
                ";"
            } else {
                " &&"
            };
            output.push_str(&format!(
                "        register_{}_runtime_natives(env){}\n",
                module.name, trailing
            ));
        }
    }

    output.push_str("}\n\n");
    output.push_str(
        "/// Build one runtime bridge callback table with the generated host ABI modules.\n",
    );
    output.push_str(
        "inline AndroidRuntimeBridgeBindings make_generated_runtime_bridge_bindings() {\n",
    );
    output.push_str("    return AndroidRuntimeBridgeBindings {\n");

    for lane in generated_catalog.bridge_lanes(HostPlatform::Android) {
        let module = generated_catalog
            .module(lane.field_name)
            .unwrap_or_else(|| panic!("missing Android runtime bridge module {}", lane.field_name));
        let value = android_generated_runtime_slot_factory(module.abi());
        output.push_str(&format!("        .{} = {},\n", lane.field_name, value));
    }

    output.push_str("    };\n");
    output.push_str("}\n\n");
    output.push_str("#endif\n");
    output
}

/// Render one generated Android callback struct for one module.
fn render_android_generated_callback_struct(output: &mut String, module: &HostAbiModule) {
    push_cpp_doc_comment(
        output,
        &format!(
            "The {} callbacks registered for one runtime session",
            render_android_callback_struct_subject(module)
        ),
        0,
    );
    output.push_str(&format!(
        "struct {} {{\n",
        android_generated_runtime_slot_type(module)
    ));

    for request in &module.requests {
        let field_name = android_cpp_callback_field_name(request);
        push_cpp_doc_comment(
            output,
            &format!("The {} callback", request.name.replace('_', "-")),
            4,
        );
        output.push_str("    uint32_t (*");
        output.push_str(&field_name);
        output.push_str(")(");

        for (index, parameter) in request.parameters.iter().enumerate() {
            if index != 0 {
                output.push_str(", ");
            }

            output.push_str(&render_cpp_parameter_declaration(
                &render_cpp_type(&parameter.ty),
                parameter.name,
            ));
        }

        output.push_str(");\n");
    }

    output.push_str("};\n");
}

/// Return the Android callback-struct subject phrase for one module.
fn render_android_callback_struct_subject(module: &HostAbiModule) -> String {
    module.name.replace('_', "-")
}

/// One generated Android slice type.
pub(super) struct AndroidGeneratedSliceType {
    /// The canonical slice type name.
    pub(super) name: String,
    /// The slice element type name.
    pub(super) element_name: String,
}

/// Render one generated Android named type.
fn render_android_named_type(output: &mut String, named_type: &HostAbiNamedType) {
    push_cpp_doc_comment(output, named_type.documentation, 0);

    match &named_type.definition {
        HostAbiNamedTypeDefinition::Struct { fields } => {
            output.push_str(&format!("struct {} {{\n", named_type.name));

            for field in fields {
                render_android_named_field(output, field);
            }

            output.push_str("};\n");
        }
        HostAbiNamedTypeDefinition::Enum { repr, variants } => {
            output.push_str(&format!(
                "enum class {} : {} {{\n",
                named_type.name,
                render_android_enum_repr(*repr)
            ));

            for variant in variants {
                push_cpp_doc_comment(output, variant.documentation, 4);
                output.push_str(&format!(
                    "    {} = {},\n",
                    variant.name, variant.discriminant
                ));
            }

            output.push_str("};\n");
        }
    }
}

/// Render one generated Android named-type forward declaration.
fn render_android_named_type_forward_declaration(
    output: &mut String,
    named_type: &HostAbiNamedType,
) {
    match &named_type.definition {
        HostAbiNamedTypeDefinition::Struct { .. } => {
            output.push_str(&format!("struct {};\n", named_type.name));
        }
        HostAbiNamedTypeDefinition::Enum { repr, .. } => {
            output.push_str(&format!(
                "enum class {} : {};\n",
                named_type.name,
                render_android_enum_repr(*repr)
            ));
        }
    }
}

/// Render one generated Android named field.
fn render_android_named_field(output: &mut String, field: &HostAbiField) {
    push_cpp_doc_comment(output, field.documentation, 4);
    output.push_str(&format!(
        "    {} {};\n",
        render_cpp_type(&field.ty),
        field.name
    ));
}

/// Render one generated Android slice type.
fn render_android_generated_slice_type(
    output: &mut String,
    generated_type: &AndroidGeneratedSliceType,
) {
    push_cpp_doc_comment(
        output,
        &format!(
            "One {} slice passed through the Android bridge",
            generated_type.element_name
        ),
        0,
    );
    output.push_str(&format!("struct {} {{\n", generated_type.name));
    output.push_str(&format!(
        "    const {} *data;\n",
        generated_type.element_name
    ));
    output.push_str("    uint32_t len;\n");
    output.push_str("};\n");
}

/// Collect the generated Android slice types required by this module slice.
fn collect_android_generated_slice_types(
    generated_modules: &[HostAbiModule],
) -> Vec<AndroidGeneratedSliceType> {
    let mut generated_types = Vec::new();

    for module in generated_modules {
        let mut visited_named_types = Vec::new();

        for function in module.requests.iter().chain(&module.ingress) {
            collect_android_generated_slice_types_from_type(
                module,
                &function.result,
                &mut generated_types,
                &mut visited_named_types,
            );

            for parameter in &function.parameters {
                collect_android_generated_slice_types_from_type(
                    module,
                    &parameter.ty,
                    &mut generated_types,
                    &mut visited_named_types,
                );
            }
        }
    }

    generated_types
}

/// Collect the generated Android slice types reachable from one ABI type.
pub(super) fn collect_android_generated_slice_types_from_type(
    module: &HostAbiModule,
    ty: &HostAbiType,
    generated_types: &mut Vec<AndroidGeneratedSliceType>,
    visited_named_types: &mut Vec<String>,
) {
    match ty {
        HostAbiType::Named(name) => {
            if visited_named_types.iter().any(|existing| existing == name) {
                return;
            }

            visited_named_types.push((*name).to_string());

            if let HostAbiNamedTypeDefinition::Struct { fields } =
                &android_named_type(module, name).definition
            {
                for field in fields {
                    collect_android_generated_slice_types_from_type(
                        module,
                        &field.ty,
                        generated_types,
                        visited_named_types,
                    );
                }
            }
        }
        HostAbiType::NativeArray(inner)
        | HostAbiType::NativeSlice(inner)
        | HostAbiType::OutputPointer(inner) => {
            if let HostAbiType::NativeSlice(element) = ty {
                if let HostAbiType::Named(name) = element.as_ref() {
                    push_android_generated_slice_type(
                        generated_types,
                        AndroidGeneratedSliceType {
                            name: format!("{name}Slice"),
                            element_name: (*name).to_string(),
                        },
                    );
                }
            }

            collect_android_generated_slice_types_from_type(
                module,
                inner,
                generated_types,
                visited_named_types,
            );
        }
        _ => {}
    }
}

/// Push one generated Android slice type once.
fn push_android_generated_slice_type(
    generated_types: &mut Vec<AndroidGeneratedSliceType>,
    generated_type: AndroidGeneratedSliceType,
) {
    if generated_types
        .iter()
        .any(|existing| existing.name == generated_type.name)
    {
        return;
    }

    generated_types.push(generated_type);
}

/// Render one Android enum representation.
fn render_android_enum_repr(repr: HostAbiEnumRepresentation) -> &'static str {
    match repr {
        HostAbiEnumRepresentation::I32 => "int32_t",
        HostAbiEnumRepresentation::U32 => "uint32_t",
    }
}

/// Return the generated callback factory for one Android runtime slot.
fn android_generated_runtime_slot_factory(module: &HostAbiModule) -> String {
    format!("make_{}_callbacks()", module.name)
}

/// Return the callbacks type name for one generated Android runtime slot.
fn android_generated_runtime_slot_type(module: &HostAbiModule) -> String {
    format!(
        "AndroidHost{}Callbacks",
        android_runtime_slot_segment(module.name)
    )
}

/// Return the type segment for one Android runtime slot.
fn android_runtime_slot_segment(name: &str) -> String {
    let mut output = String::new();

    for segment in name.split('_') {
        let mut chars = segment.chars();
        if let Some(first) = chars.next() {
            output.extend(first.to_uppercase());
            output.extend(chars);
        }
    }

    output
}
