use std::collections::BTreeSet;

use super::abi::{
    android_module_uses_type, android_named_struct_fields, android_named_type_is_enum,
};
use super::codec::collect_android_cpp_decode_named_types_from_type;
use super::docs::push_kotlin_doc_comment;
use super::name::{android_package_segment, android_pascal_case, single_ingress};
use crate::host::model::{HostIngress, HostModule, HostRequest};
use destack_runtime::host::abi::describe::{HostAbiFunction, HostAbiModule, HostAbiType};

pub(super) fn render_kotlin_runtime_bridge(modules: &[&HostModule]) -> String {
    let mut output = String::new();
    let mut imports = BTreeSet::new();

    imports.insert("dev.destack.runtime.android.bridge.validateRuntimeIngressStatus".to_string());
    imports.insert("dev.destack.runtime.android.core.HostSessionHandle".to_string());
    imports.insert("dev.destack.runtime.android.core.RuntimeHost".to_string());
    imports.insert("dev.destack.runtime.android.core.hostStatusInvalidArgument".to_string());
    imports.insert("dev.destack.runtime.android.core.hostStatusNotFound".to_string());

    for module in modules {
        for request in module.requests() {
            for parameter in request.input_parameters() {
                collect_android_kotlin_type_imports(&mut imports, module.abi(), &parameter.ty);
            }

            if let Some(output_parameter) = request.output_parameter() {
                let HostAbiType::OutputPointer(inner) = &output_parameter.ty else {
                    panic!("expected Android output pointer for {}", request.name());
                };

                collect_android_kotlin_type_imports(&mut imports, module.abi(), inner);
            } else {
                collect_android_kotlin_type_imports(
                    &mut imports,
                    module.abi(),
                    &request.abi().result,
                );
            }
        }

        if let Some(ingress) = module.single_ingress() {
            for parameter in ingress.parameters() {
                collect_android_kotlin_type_imports(&mut imports, module.abi(), &parameter.ty);
            }
        }
    }

    output.push_str("// generated by generate-bindings: do not edit\n\n");
    output.push_str("package dev.destack.runtime.android.bridge\n\n");
    for import in imports {
        output.push_str(&format!("import {import}\n"));
    }
    output.push('\n');

    for module in modules {
        for request in module.requests() {
            if request.output_parameter().is_some() {
                render_android_runtime_bridge_response_type(&mut output, module, request);
                output.push('\n');
            }
        }
    }

    push_kotlin_doc_comment(
        &mut output,
        "One generated Android runtime-bridge base carrying the shared host lane glue.",
        0,
    );
    output.push_str("public abstract class GeneratedRuntimeBridge(\n");
    output.push_str("    protected val sessionHandle: HostSessionHandle,\n");
    output.push_str("    protected val runtimeApi: RuntimeIngress,\n");
    output.push_str(") {\n");
    push_kotlin_doc_comment(
        &mut output,
        "Resolve the attached runtime host for one background-thread bridge callback.",
        4,
    );
    output.push_str("    protected abstract fun <T> withRuntimeHost(\n");
    output.push_str("        onMissing: () -> T,\n");
    output.push_str("        body: (RuntimeHost) -> T,\n");
    output.push_str("    ): T\n\n");
    push_kotlin_doc_comment(
        &mut output,
        "Resolve the attached runtime host for one main-thread bridge callback.",
        4,
    );
    output.push_str("    protected abstract fun <T> withRuntimeHostOnMainThread(\n");
    output.push_str("        onMissing: () -> T,\n");
    output.push_str("        body: (RuntimeHost) -> T,\n");
    output.push_str("    ): T");

    let mut is_first_method = true;
    for module in modules {
        if let Some(ingress) = module.single_ingress() {
            output.push_str("\n\n");
            render_kotlin_runtime_bridge_ingress_method(&mut output, module, ingress);
            is_first_method = false;
        }

        for request in module.requests() {
            output.push_str("\n\n");
            render_kotlin_runtime_bridge_request_method(&mut output, module, request);

            output.push_str("\n\n");
            render_kotlin_runtime_bridge_internal_request_method(&mut output, module, request);
            is_first_method = false;
        }
    }

    if is_first_method {
        output.push('\n');
    }

    output.push_str("\n}\n");
    output
}

pub(super) fn render_kotlin_runtime_abi(ingress_modules: &[&HostModule]) -> String {
    let mut output = String::new();
    let mut imports = BTreeSet::new();

    for module in ingress_modules {
        let ingress = single_ingress(module.abi());

        for parameter in &ingress.parameters {
            collect_android_kotlin_type_imports(&mut imports, module.abi(), &parameter.ty);
        }

        collect_android_kotlin_type_imports(&mut imports, module.abi(), &ingress.result);
    }

    output.push_str("// generated by generate-bindings: do not edit\n\n");
    output.push_str("package dev.destack.runtime.android.bridge\n\n");
    output.push_str("import dev.destack.runtime.android.core.HostSessionHandle\n");
    for import in imports {
        if import != "dev.destack.runtime.android.core.HostSessionHandle" {
            output.push_str(&format!("import {import}\n"));
        }
    }

    output.push('\n');
    push_kotlin_doc_comment(
        &mut output,
        "The generated low-level runtime ABI surface for one Android host bridge.",
        0,
    );
    output.push_str("public interface RuntimeAbi {\n");

    for module in ingress_modules {
        render_kotlin_runtime_abi_interface_method(&mut output, module);
        output.push('\n');
    }

    push_kotlin_doc_comment(
        &mut output,
        "Attach one bridge instance to one runtime session.",
        4,
    );
    output.push_str("    public fun attachBridge(\n");
    output.push_str("        sessionHandle: HostSessionHandle,\n");
    output.push_str("        bridge: RuntimeBridge,\n");
    output.push_str("    ): Int\n\n");

    push_kotlin_doc_comment(
        &mut output,
        "Detach one bridge instance from one runtime session.",
        4,
    );
    output.push_str("    public fun detachBridge(\n");
    output.push_str("        sessionHandle: HostSessionHandle,\n");
    output.push_str("    )\n");
    output.push_str("}\n\n");

    push_kotlin_doc_comment(
        &mut output,
        "The generated process runtime ABI resolved through the Android JNI bridge.",
        0,
    );
    output.push_str("public object ProcessRuntimeAbi : RuntimeAbi {\n");
    output.push_str("    init {\n");
    output.push_str("        RuntimeHostLibraryLoader.ensureLoaded()\n");
    output.push_str("    }\n\n");

    for module in ingress_modules {
        render_kotlin_runtime_abi_impl_method(&mut output, module);
        output.push('\n');
    }

    push_kotlin_doc_comment(
        &mut output,
        "Attach one runtime bridge to one native runtime session.",
        4,
    );
    output.push_str("    override fun attachBridge(\n");
    output.push_str("        sessionHandle: HostSessionHandle,\n");
    output.push_str("        bridge: RuntimeBridge,\n");
    output.push_str("    ): Int {\n");
    output.push_str("        return nativeAttachBridge(\n");
    output.push_str("            sessionHandle.rawValue,\n");
    output.push_str("            bridge,\n");
    output.push_str("        )\n");
    output.push_str("    }\n\n");

    push_kotlin_doc_comment(
        &mut output,
        "Detach one runtime bridge from one native runtime session.",
        4,
    );
    output.push_str("    override fun detachBridge(\n");
    output.push_str("        sessionHandle: HostSessionHandle,\n");
    output.push_str("    ) {\n");
    output.push_str("        nativeDetachBridge(sessionHandle.rawValue)\n");
    output.push_str("    }\n\n");

    output.push_str("    private external fun nativeAttachBridge(\n");
    output.push_str("        sessionHandle: Long,\n");
    output.push_str("        bridge: RuntimeBridge,\n");
    output.push_str("    ): Int\n\n");
    output.push_str("    private external fun nativeDetachBridge(\n");
    output.push_str("        sessionHandle: Long,\n");
    output.push_str("    )\n");
    output.push_str("}\n");

    output
}

pub(super) fn render_kotlin_abi(module: &HostAbiModule) -> String {
    if module.ingress.is_empty() {
        return String::new();
    }

    let mut output = String::new();

    output.push_str("// generated by generate-bindings: do not edit\n\n");
    output.push_str("package dev.destack.runtime.android.bridge\n\n");
    for import in android_kotlin_imports(module) {
        output.push_str(&format!("import {import}\n"));
    }
    output.push('\n');
    render_kotlin_encoding_helpers(&mut output, module);

    output
}

fn render_kotlin_runtime_abi_interface_method(output: &mut String, module: &HostModule) {
    let module = module.abi();
    let ingress = single_ingress(module);

    render_kotlin_ingress_signature(output, module, ingress, 4, true);
}

fn render_kotlin_runtime_abi_impl_method(output: &mut String, module: &HostModule) {
    let module = module.abi();
    let ingress = single_ingress(module);
    let native_name = android_kotlin_native_name(ingress);

    render_kotlin_ingress_signature(output, module, ingress, 4, false);
    output.push_str(" {\n");
    output.push_str(&format!("        val values = {native_name}(\n"));
    render_kotlin_native_call_arguments(output, ingress, 12);
    output.push_str("        )\n\n");
    output.push_str("        return RuntimeAbiStatus(\n");
    output.push_str("            code = values[0].toInt(),\n");
    output.push_str("            errorId = values[1],\n");
    output.push_str("        )\n");
    output.push_str("    }\n\n");

    output.push_str("    private external fun ");
    output.push_str(&native_name);
    output.push_str("(\n");
    render_kotlin_native_signature(output, module, ingress);
    output.push_str("    ): LongArray\n");
}

/// Render one generated Android runtime-bridge response wrapper.
fn render_android_runtime_bridge_response_type(
    output: &mut String,
    module: &HostModule,
    request: &HostRequest,
) {
    let response_name = android_runtime_bridge_response_type_name(module.abi(), request.abi());

    push_kotlin_doc_comment(
        output,
        &format!(
            "One generated bridge response wrapper for the {} request.",
            request.name().replace('_', "-")
        ),
        0,
    );
    output.push_str(&format!("internal data class {response_name}(\n"));
    output.push_str("    val status: Int,\n");

    for output_parameter in request.output_parameters() {
        let HostAbiType::OutputPointer(inner) = &output_parameter.ty else {
            panic!("expected Android output pointer for {}", request.name());
        };
        let field_type = render_android_kotlin_bridge_type(module.abi(), inner);

        output.push_str(&format!(
            "    val {}: {}? = null,\n",
            android_kotlin_parameter_name(output_parameter.name),
            field_type
        ));
    }

    output.push_str(")\n");
}

/// Render one generated Android runtime ingress forwarder.
fn render_kotlin_runtime_bridge_ingress_method(
    output: &mut String,
    module: &HostModule,
    ingress: &HostIngress,
) {
    let method_name = android_kotlin_method_name(ingress.name());

    push_kotlin_doc_comment(output, ingress.documentation(), 4);
    output.push_str(&format!("    fun {method_name}(\n"));

    let payload_parameters = ingress
        .parameters()
        .iter()
        .filter(|parameter| !matches!(parameter.ty, HostAbiType::HostSessionHandle))
        .collect::<Vec<_>>();

    for (index, parameter) in payload_parameters.iter().enumerate() {
        let trailing = if index + 1 == payload_parameters.len() {
            ""
        } else {
            ","
        };
        let parameter_name = android_kotlin_parameter_name(parameter.name);
        let parameter_type = render_android_kotlin_bridge_type(module.abi(), &parameter.ty);

        output.push_str(&format!(
            "        {parameter_name}: {parameter_type}{trailing}\n"
        ));
    }

    output.push_str("    ) {\n");
    output.push_str(&format!("        val status = runtimeApi.{method_name}(\n"));
    output.push_str("            sessionHandle = sessionHandle,\n");
    for parameter in &payload_parameters {
        let parameter_name = android_kotlin_parameter_name(parameter.name);
        output.push_str(&format!(
            "            {parameter_name} = {parameter_name},\n"
        ));
    }
    output.push_str("        )\n");
    output.push_str("        validateRuntimeIngressStatus(\n");
    output.push_str("            status,\n");
    output.push_str(&format!(
        "            operation = \"{}\",\n",
        ingress
            .documentation()
            .trim_end_matches('.')
            .to_ascii_lowercase()
    ));
    output.push_str("        )\n");
    output.push_str("    }\n");
}

/// Render one generated Android runtime-host request forwarder.
fn render_kotlin_runtime_bridge_request_method(
    output: &mut String,
    module: &HostModule,
    request: &HostRequest,
) {
    let method_name = android_runtime_bridge_method_name(module.abi(), request.abi());
    let module_name = android_kotlin_parameter_name(module.name());
    let target_name = android_kotlin_method_name(request.name());
    let return_type = render_android_kotlin_request_runtime_return_type(module.abi(), request);

    push_kotlin_doc_comment(output, request.documentation(), 4);
    output.push_str(&format!("    fun {method_name}(\n"));
    output.push_str("        runtimeHost: RuntimeHost");

    let input_parameters = request.input_parameters();
    if input_parameters.is_empty() {
        output.push('\n');
        output.push_str(&format!("    ): {return_type} {{\n"));
    } else {
        output.push_str(",\n");
        for (index, parameter) in input_parameters.iter().enumerate() {
            let trailing = if index + 1 == input_parameters.len() {
                ""
            } else {
                ","
            };
            let parameter_name = android_kotlin_parameter_name(parameter.name);
            let parameter_type = render_android_kotlin_bridge_type(module.abi(), &parameter.ty);
            output.push_str(&format!(
                "        {parameter_name}: {parameter_type}{trailing}\n"
            ));
        }
        output.push_str(&format!("    ): {return_type} {{\n"));
    }

    output.push_str(&format!(
        "        return runtimeHost.{module_name}.{target_name}("
    ));
    for (index, parameter) in input_parameters.iter().enumerate() {
        if index > 0 {
            output.push_str(", ");
        }
        output.push_str(&android_kotlin_parameter_name(parameter.name));
    }
    output.push_str(")\n");
    output.push_str("    }\n");
}

/// Render one generated Android internal bridge request wrapper.
fn render_kotlin_runtime_bridge_internal_request_method(
    output: &mut String,
    module: &HostModule,
    request: &HostRequest,
) {
    let method_name = android_runtime_bridge_method_name(module.abi(), request.abi());
    let return_type = render_android_kotlin_request_bridge_return_type(module.abi(), request);
    let wrapper_name = if request.abi().android_main_thread {
        "withRuntimeHostOnMainThread"
    } else {
        "withRuntimeHost"
    };
    let missing_value = render_android_kotlin_missing_host_value(module.abi(), request);
    let invalid_value = render_android_kotlin_invalid_argument_value(module.abi(), request)
        .unwrap_or_else(|| "hostStatusInvalidArgument".to_string());
    let decoded_arguments = render_android_kotlin_decoded_request_arguments(
        module.abi(),
        request,
        wrapper_name,
        &invalid_value,
    );
    let call_arguments = render_android_kotlin_request_call_arguments(request);

    push_kotlin_doc_comment(output, request.documentation(), 4);
    output.push_str(&format!("    @JvmName(\"{method_name}\")\n"));
    output.push_str(&format!("    internal fun {method_name}(\n"));

    let leaves = collect_android_kotlin_request_decode_leaves(module.abi(), request);
    for (index, leaf) in leaves.iter().enumerate() {
        let trailing = if index + 1 == leaves.len() { "" } else { "," };
        output.push_str(&format!(
            "        {}: {}{}\n",
            android_kotlin_decode_leaf_name(&leaf.path),
            render_android_kotlin_decode_leaf_type(module.abi(), &leaf.ty),
            trailing
        ));
    }

    output.push_str(&format!("    ): {return_type} {{\n"));
    output.push_str(&format!("        return {wrapper_name}(\n"));
    output.push_str(&format!("            onMissing = {{ {missing_value} }},\n"));
    output.push_str("        ) { runtimeHost ->\n");

    for line in decoded_arguments {
        output.push_str("            ");
        output.push_str(&line);
        output.push('\n');
    }

    if request.output_parameter().is_some() {
        let response_name = android_runtime_bridge_response_type_name(module.abi(), request.abi());
        let status_expression =
            render_android_kotlin_request_response_status(module.abi(), request);
        let output_name = render_android_kotlin_request_output_name(request);

        output.push_str(&format!(
            "            val bridgeResult = this.{method_name}(runtimeHost"
        ));
        for argument in &call_arguments {
            output.push_str(", ");
            output.push_str(argument);
        }
        output.push_str(")\n");
        output.push_str(&format!(
            "            return@{wrapper_name} {response_name}(\n"
        ));
        output.push_str(&format!("                status = {status_expression},\n"));
        output.push_str(&format!("                {output_name} = bridgeResult,\n"));
        output.push_str("            )\n");
    } else {
        output.push_str(&format!(
            "            return@{wrapper_name} this.{method_name}(runtimeHost"
        ));
        for argument in &call_arguments {
            output.push_str(", ");
            output.push_str(argument);
        }
        output.push_str(")\n");
    }

    output.push_str("        }\n");
    output.push_str("    }\n");
}

/// Return the public runtime-host return type for one request.
fn render_android_kotlin_request_runtime_return_type(
    module: &HostAbiModule,
    request: &HostRequest,
) -> String {
    if let Some(output_parameter) = request.output_parameter() {
        let HostAbiType::OutputPointer(inner) = &output_parameter.ty else {
            panic!("expected Android output pointer for {}", request.name());
        };

        return render_android_kotlin_bridge_type(module, inner);
    }

    render_android_kotlin_native_type(&request.abi().result)
}

/// Return the internal bridge return type for one request.
fn render_android_kotlin_request_bridge_return_type(
    module: &HostAbiModule,
    request: &HostRequest,
) -> String {
    if request.output_parameter().is_some() {
        return android_runtime_bridge_response_type_name(module, request.abi());
    }

    render_android_kotlin_native_type(&request.abi().result)
}

/// Return the generated Android bridge response type name for one request.
pub(super) fn android_runtime_bridge_response_type_name(
    module: &HostAbiModule,
    request: &HostAbiFunction,
) -> String {
    format!(
        "RuntimeHost{}{}Response",
        android_pascal_case(module.name),
        android_pascal_case(request.name)
    )
}

/// Return the missing-host fallback expression for one request.
fn render_android_kotlin_missing_host_value(
    module: &HostAbiModule,
    request: &HostRequest,
) -> String {
    if request.output_parameter().is_some() {
        let response_name = android_runtime_bridge_response_type_name(module, request.abi());
        return format!("{response_name}(status = hostStatusNotFound)");
    }

    match &request.abi().result {
        HostAbiType::Bool => "false".to_string(),
        HostAbiType::HostStatus => "hostStatusNotFound".to_string(),
        other => panic!(
            "unsupported Android runtime bridge missing-host value for {:?} on {}",
            other,
            request.name()
        ),
    }
}

/// Return the invalid-argument fallback expression for one request when needed.
fn render_android_kotlin_invalid_argument_value(
    module: &HostAbiModule,
    request: &HostRequest,
) -> Option<String> {
    if request.output_parameter().is_some() {
        let response_name = android_runtime_bridge_response_type_name(module, request.abi());
        return Some(format!(
            "{response_name}(status = hostStatusInvalidArgument)"
        ));
    }

    if request
        .input_parameters()
        .iter()
        .any(|parameter| android_kotlin_type_decode_can_fail(module, &parameter.ty))
    {
        return Some("hostStatusInvalidArgument".to_string());
    }

    None
}

/// Return the wrapped response status expression for one request result.
fn render_android_kotlin_request_response_status(
    module: &HostAbiModule,
    request: &HostRequest,
) -> String {
    let Some(_output_parameter) = request.output_parameter() else {
        return "hostStatusOk".to_string();
    };

    let _ = module;
    "bridgeResult.status".to_string()
}

/// Return the wrapped output field name for one request.
fn render_android_kotlin_request_output_name(request: &HostRequest) -> String {
    let Some(output_parameter) = request.output_parameter() else {
        panic!("missing Android output parameter for {}", request.name());
    };

    android_kotlin_parameter_name(output_parameter.name)
}

/// Return the decoded call arguments for one request.
fn render_android_kotlin_request_call_arguments(request: &HostRequest) -> Vec<String> {
    let single_named_input = request.input_parameters().len() == 1
        && request
            .input_parameters()
            .first()
            .is_some_and(|parameter| matches!(parameter.ty, HostAbiType::Named(_)));

    request
        .input_parameters()
        .iter()
        .map(|parameter| {
            if single_named_input {
                "decodedRequest".to_string()
            } else {
                format!("decoded{}", android_pascal_case(parameter.name))
            }
        })
        .collect()
}

/// Collect the flattened Kotlin request leaves for one request.
fn collect_android_kotlin_request_decode_leaves(
    module: &HostAbiModule,
    request: &HostRequest,
) -> Vec<AndroidKotlinDecodeLeaf> {
    let mut leaves = Vec::new();

    for parameter in request.input_parameters() {
        let mut path = vec![parameter.name.to_string()];
        collect_android_kotlin_decode_leaves(module, &parameter.ty, &mut path, &mut leaves);
    }

    leaves
}

/// Render the decoded request locals for one request wrapper.
fn render_android_kotlin_decoded_request_arguments(
    module: &HostAbiModule,
    request: &HostRequest,
    wrapper_name: &str,
    invalid_value: &str,
) -> Vec<String> {
    let mut lines = Vec::new();
    let single_named_input = request.input_parameters().len() == 1
        && request
            .input_parameters()
            .first()
            .is_some_and(|parameter| matches!(parameter.ty, HostAbiType::Named(_)));

    for parameter in request.input_parameters() {
        let variable_name = if single_named_input {
            "decodedRequest".to_string()
        } else {
            format!("decoded{}", android_pascal_case(parameter.name))
        };
        let decoded_expression = render_android_kotlin_decode_value(
            module,
            &parameter.ty,
            &[parameter.name.to_string()],
            12,
        );

        if android_kotlin_type_decode_can_fail(module, &parameter.ty) {
            lines.push(format!(
                "val {variable_name} = {decoded_expression} ?: return@{wrapper_name} {invalid_value}"
            ));
        } else {
            lines.push(format!("val {variable_name} = {decoded_expression}"));
        }
    }

    lines
}

fn render_kotlin_encoding_helpers(output: &mut String, module: &HostAbiModule) {
    let decode_names = collect_android_kotlin_request_decode_named_types(module);

    for name in &decode_names {
        if android_named_type_is_enum(module, name) {
            render_android_kotlin_enum_decode_helper(output, module, name);
            output.push('\n');
        }
    }

    for name in &decode_names {
        if !android_named_type_is_enum(module, name) {
            render_android_kotlin_named_decode_helper(output, module, name);
            output.push('\n');
        }
    }
}

/// Collect the named ABI types reachable from request input payloads.
fn collect_android_kotlin_request_decode_named_types(module: &HostAbiModule) -> Vec<String> {
    let mut names = Vec::new();

    for request in &module.requests {
        for parameter in &request.parameters {
            if matches!(
                parameter.ty,
                HostAbiType::HostSessionHandle | HostAbiType::OutputPointer(_)
            ) {
                continue;
            }

            collect_android_cpp_decode_named_types_from_type(module, &parameter.ty, &mut names);
        }
    }

    names
}

/// Return whether one Kotlin decode expression can fail.
fn android_kotlin_type_decode_can_fail(module: &HostAbiModule, ty: &HostAbiType) -> bool {
    match ty {
        HostAbiType::Named(name) if android_named_type_is_enum(module, name) => true,
        HostAbiType::Named(name) => android_named_struct_fields(module, name)
            .iter()
            .any(|field| android_kotlin_type_decode_can_fail(module, &field.ty)),
        HostAbiType::Optional(inner) => android_kotlin_type_decode_can_fail(module, inner),
        HostAbiType::NativeArray(inner)
        | HostAbiType::NativeSlice(inner)
        | HostAbiType::OutputPointer(inner) => android_kotlin_type_decode_can_fail(module, inner),
        _ => false,
    }
}

/// Return whether one Kotlin named decode helper can fail.
fn android_kotlin_named_type_decode_can_fail(module: &HostAbiModule, name: &str) -> bool {
    android_named_struct_fields(module, name)
        .iter()
        .any(|field| android_kotlin_type_decode_can_fail(module, &field.ty))
}

/// Return the decode helper parameter type for one Kotlin leaf.
fn render_android_kotlin_decode_leaf_type(module: &HostAbiModule, ty: &HostAbiType) -> String {
    match ty {
        HostAbiType::U8
        | HostAbiType::U16
        | HostAbiType::I8
        | HostAbiType::I16
        | HostAbiType::U32
        | HostAbiType::I32 => "Int".to_string(),
        HostAbiType::U64 | HostAbiType::HostRequestId => "Long".to_string(),
        HostAbiType::Bool => "Boolean".to_string(),
        HostAbiType::F64 => "Double".to_string(),
        HostAbiType::StringRef => "String".to_string(),
        HostAbiType::StringSlice => "Array<String>".to_string(),
        HostAbiType::Named(name) if android_named_type_is_enum(module, name) => "Int".to_string(),
        HostAbiType::Named(name) => android_kotlin_runtime_named_type(module, name),
        HostAbiType::NativeSlice(inner) => match inner.as_ref() {
            HostAbiType::Named(name) => {
                format!("Array<{}>", android_kotlin_runtime_named_type(module, name))
            }
            HostAbiType::U8
            | HostAbiType::U16
            | HostAbiType::I8
            | HostAbiType::I16
            | HostAbiType::U32
            | HostAbiType::I32 => "IntArray".to_string(),
            other => panic!("unsupported Kotlin decode slice leaf type for {:?}", other),
        },
        HostAbiType::Optional(inner) => {
            format!("{}?", render_android_kotlin_decode_leaf_type(module, inner))
        }
        other => panic!("unsupported Kotlin decode leaf type for {:?}", other),
    }
}

/// Return one Kotlin decode helper parameter name for one field path.
fn android_kotlin_decode_leaf_name(path: &[String]) -> String {
    let mut segments = path.iter();
    let Some(first) = segments.next() else {
        return String::new();
    };

    let mut name = android_kotlin_parameter_name(first);
    for segment in segments {
        name.push_str(&android_pascal_case(segment));
    }

    name
}

/// One flattened Kotlin request-decode leaf.
#[derive(Clone, Debug)]
struct AndroidKotlinDecodeLeaf {
    /// The nested ABI field path for this leaf.
    path: Vec<String>,
    /// The leaf ABI type.
    ty: HostAbiType,
}

/// Collect the flattened Kotlin request-decode leaves for one ABI type.
fn collect_android_kotlin_decode_leaves(
    module: &HostAbiModule,
    ty: &HostAbiType,
    path: &mut Vec<String>,
    leaves: &mut Vec<AndroidKotlinDecodeLeaf>,
) {
    match ty {
        HostAbiType::Named(name) if !android_named_type_is_enum(module, name) => {
            for field in android_named_struct_fields(module, name) {
                path.push(field.name.to_string());
                collect_android_kotlin_decode_leaves(module, &field.ty, path, leaves);
                path.pop();
            }
        }
        HostAbiType::OutputPointer(_) => {}
        _ => leaves.push(AndroidKotlinDecodeLeaf {
            path: path.clone(),
            ty: ty.clone(),
        }),
    }
}

/// Return the flattened Kotlin decode leaves for one named ABI type.
fn android_kotlin_decode_leaves_for_named_type(
    module: &HostAbiModule,
    name: &str,
) -> Vec<AndroidKotlinDecodeLeaf> {
    let mut leaves = Vec::new();

    for field in android_named_struct_fields(module, name) {
        let mut path = vec![field.name.to_string()];
        collect_android_kotlin_decode_leaves(module, &field.ty, &mut path, &mut leaves);
    }

    leaves
}

/// Return one Kotlin runtime type name for one authored ABI type.
fn android_kotlin_runtime_named_type(module: &HostAbiModule, name: &str) -> String {
    android_kotlin_module_type_name(module, name)
}

/// Collect the Kotlin imports for one ABI type tree.
fn collect_android_kotlin_type_imports(
    imports: &mut BTreeSet<String>,
    module: &HostAbiModule,
    ty: &HostAbiType,
) {
    match ty {
        HostAbiType::HostRequestId => {
            imports.insert("dev.destack.runtime.android.core.HostRequestId".to_string());
        }
        HostAbiType::Named(name) => {
            let type_name = android_kotlin_module_type_name(module, name);

            imports.insert(format!(
                "dev.destack.runtime.android.module.{}.{type_name}",
                module.name,
            ));
        }
        HostAbiType::Optional(inner) => {
            collect_android_kotlin_type_imports(imports, module, inner);
        }
        HostAbiType::NativeArray(inner)
        | HostAbiType::NativeSlice(inner)
        | HostAbiType::OutputPointer(inner) => {
            collect_android_kotlin_type_imports(imports, module, inner);
        }
        _ => {}
    }
}

/// Return one generated Kotlin bridge type.
fn render_android_kotlin_bridge_type(module: &HostAbiModule, ty: &HostAbiType) -> String {
    match ty {
        HostAbiType::Named(name) => android_kotlin_module_type_name(module, name),
        _ => render_android_kotlin_native_type(ty),
    }
}

/// Return one Android module type name for one ABI named type.
fn android_kotlin_module_type_name(module: &HostAbiModule, name: &str) -> String {
    let _ = module;
    format!("Runtime{name}")
}

/// Render one generic Kotlin enum decode helper.
fn render_android_kotlin_enum_decode_helper(
    output: &mut String,
    module: &HostAbiModule,
    name: &str,
) {
    let runtime_name = android_kotlin_runtime_named_type(module, name);

    push_kotlin_doc_comment(
        output,
        &format!("Build one Kotlin {name} from one bridge raw value."),
        0,
    );
    output.push_str(&format!("internal fun decodeBridge{name}(\n"));
    output.push_str("    value: Int,\n");
    output.push_str(&format!("): {runtime_name}? {{\n"));
    output.push_str(&format!(
        "    return {runtime_name}.entries.firstOrNull {{ entry ->\n"
    ));
    output.push_str("        entry.rawValue.toInt() == value\n");
    output.push_str("    }\n");
    output.push_str("}\n");
}

/// Render one generic Kotlin named decode helper.
fn render_android_kotlin_named_decode_helper(
    output: &mut String,
    module: &HostAbiModule,
    name: &str,
) {
    let runtime_name = android_kotlin_runtime_named_type(module, name);
    let leaves = android_kotlin_decode_leaves_for_named_type(module, name);
    let can_fail = android_kotlin_named_type_decode_can_fail(module, name);
    let return_type = if can_fail {
        format!("{runtime_name}?")
    } else {
        runtime_name.clone()
    };

    push_kotlin_doc_comment(
        output,
        &format!("Build one Kotlin {name} from one bridge payload."),
        0,
    );
    output.push_str(&format!("internal fun decodeBridge{name}(\n"));
    for (index, leaf) in leaves.iter().enumerate() {
        let trailing = if index + 1 == leaves.len() { "" } else { "," };
        output.push_str(&format!(
            "    {}: {}{}\n",
            android_kotlin_decode_leaf_name(&leaf.path),
            render_android_kotlin_decode_leaf_type(module, &leaf.ty),
            trailing
        ));
    }
    output.push_str(&format!("): {return_type} {{\n"));
    output.push_str(&format!("    return {runtime_name}(\n"));
    render_android_kotlin_struct_field_decodes(output, module, name, 8);
    output.push_str("    )\n");
    output.push_str("}\n");
}

/// Render the struct-field decode expressions for one Kotlin named helper.
fn render_android_kotlin_struct_field_decodes(
    output: &mut String,
    module: &HostAbiModule,
    name: &str,
    indent: usize,
) {
    let prefix = " ".repeat(indent);
    let fields = android_named_struct_fields(module, name);
    let mut index = 0;

    while index < fields.len() {
        let field = &fields[index];

        output.push_str(&format!(
            "{prefix}{} = {},\n",
            android_kotlin_parameter_name(field.name),
            render_android_kotlin_decode_value(
                module,
                &field.ty,
                &[field.name.to_string()],
                indent
            )
        ));
        index += 1;
    }
}

/// Return one Kotlin decoded expression for one ABI type and field path.
fn render_android_kotlin_decode_value(
    module: &HostAbiModule,
    ty: &HostAbiType,
    path: &[String],
    indent: usize,
) -> String {
    match ty {
        HostAbiType::U8
        | HostAbiType::U16
        | HostAbiType::I8
        | HostAbiType::I16
        | HostAbiType::U32
        | HostAbiType::I32
        | HostAbiType::U64
        | HostAbiType::Bool
        | HostAbiType::F64
        | HostAbiType::StringRef => android_kotlin_decode_leaf_name(path),
        HostAbiType::StringSlice => format!("{}.asList()", android_kotlin_decode_leaf_name(path)),
        HostAbiType::HostRequestId => {
            format!(
                "HostRequestId(rawValue = {})",
                android_kotlin_decode_leaf_name(path)
            )
        }
        HostAbiType::Named(name) if android_named_type_is_enum(module, name) => format!(
            "decodeBridge{name}({}) ?: return null",
            android_kotlin_decode_leaf_name(path)
        ),
        HostAbiType::Named(name) => {
            let nested_path = path.to_vec();
            let call = render_android_kotlin_named_decode_call(module, name, &nested_path, indent);
            if android_kotlin_type_decode_can_fail(module, ty) {
                format!("{call} ?: return null")
            } else {
                call
            }
        }
        HostAbiType::NativeSlice(_) => {
            format!("{}.asList()", android_kotlin_decode_leaf_name(path))
        }
        HostAbiType::Optional(inner) => {
            let source = android_kotlin_decode_leaf_name(path);
            match inner.as_ref() {
                HostAbiType::U16
                | HostAbiType::U32
                | HostAbiType::I32
                | HostAbiType::U64
                | HostAbiType::Bool
                | HostAbiType::F64
                | HostAbiType::StringRef => source,
                HostAbiType::StringSlice => format!("{source}?.asList()"),
                HostAbiType::NativeSlice(_) => format!("{source}?.asList()"),
                HostAbiType::HostRequestId => {
                    format!("{source}?.let {{ HostRequestId(rawValue = it) }}")
                }
                HostAbiType::Named(name) if android_named_type_is_enum(module, name) => {
                    format!("{source}?.let {{ decodeBridge{name}(it) ?: return null }}")
                }
                HostAbiType::Named(_) => source,
                other => panic!("unsupported Kotlin optional decode value for {:?}", other),
            }
        }
        other => panic!("unsupported Kotlin decode value for {:?}", other),
    }
}

/// Return one Kotlin nested named decode call for one field path.
fn render_android_kotlin_named_decode_call(
    module: &HostAbiModule,
    name: &str,
    path: &[String],
    indent: usize,
) -> String {
    let leaves = android_kotlin_decode_leaves_for_named_type(module, name);
    let base_prefix = " ".repeat(indent);
    let nested_prefix = " ".repeat(indent + 4);
    let mut output = String::new();

    output.push_str(&format!("decodeBridge{name}(\n"));
    for (index, leaf) in leaves.iter().enumerate() {
        let trailing = if index + 1 == leaves.len() { "" } else { "," };
        let mut leaf_path = path.to_vec();
        leaf_path.extend(leaf.path.iter().cloned());
        output.push_str(&format!(
            "{nested_prefix}{}{}",
            android_kotlin_decode_leaf_name(&leaf_path),
            trailing
        ));
        output.push('\n');
    }
    output.push_str(&format!("{base_prefix})"));
    output
}

/// Render one Kotlin ingress function signature.
fn render_kotlin_ingress_signature(
    output: &mut String,
    module: &HostAbiModule,
    ingress: &HostAbiFunction,
    indent: usize,
    is_interface: bool,
) {
    let prefix = " ".repeat(indent);

    push_kotlin_doc_comment(output, ingress.documentation, indent);
    output.push_str(&prefix);
    if is_interface {
        output.push_str("public ");
    } else {
        output.push_str("override ");
    }
    output.push_str("fun ");
    output.push_str(&android_kotlin_method_name(ingress.name));
    output.push_str("(\n");

    for (index, parameter) in ingress.parameters.iter().enumerate() {
        let trailing = if index + 1 == ingress.parameters.len() {
            ""
        } else {
            ","
        };
        let parameter_type = if matches!(parameter.ty, HostAbiType::HostSessionHandle) {
            "HostSessionHandle".to_string()
        } else {
            render_android_kotlin_bridge_type(module, &parameter.ty)
        };
        output.push_str(&format!(
            "{prefix}    {}: {}{}\n",
            android_kotlin_parameter_name(parameter.name),
            parameter_type,
            trailing
        ));
    }

    output.push_str(&format!("{prefix}): RuntimeAbiStatus"));
}

/// Render the Kotlin native call arguments for one ingress wrapper.
fn render_kotlin_native_call_arguments(
    output: &mut String,
    ingress: &HostAbiFunction,
    indent: usize,
) {
    let prefix = " ".repeat(indent);

    for parameter in &ingress.parameters {
        let argument = if matches!(parameter.ty, HostAbiType::HostSessionHandle) {
            "sessionHandle.rawValue".to_string()
        } else if matches!(parameter.ty, HostAbiType::HostRequestId) {
            format!("{}.rawValue", android_kotlin_parameter_name(parameter.name))
        } else {
            android_kotlin_parameter_name(parameter.name)
        };

        output.push_str(&format!(
            "{prefix}{} = {},\n",
            android_kotlin_parameter_name(parameter.name),
            argument
        ));
    }
}

/// Render one Kotlin native method signature.
fn render_kotlin_native_signature(
    output: &mut String,
    module: &HostAbiModule,
    ingress: &HostAbiFunction,
) {
    for parameter in &ingress.parameters {
        let parameter_type = if matches!(
            parameter.ty,
            HostAbiType::HostSessionHandle | HostAbiType::HostRequestId
        ) {
            "Long".to_string()
        } else {
            render_android_kotlin_bridge_type(module, &parameter.ty)
        };

        output.push_str(&format!(
            "        {}: {},\n",
            android_kotlin_parameter_name(parameter.name),
            parameter_type
        ));
    }
}

/// Return the Kotlin interface name for one module.
#[allow(dead_code)]
fn android_kotlin_interface_name(module: &HostAbiModule) -> String {
    format!("{}Abi", android_package_segment(module))
}

/// Return the Kotlin process object name for one module.
#[allow(dead_code)]
pub(super) fn android_kotlin_process_name(module: &HostAbiModule) -> String {
    format!("Process{}Abi", android_package_segment(module))
}

/// Return the JVM binary name for the aggregate Kotlin runtime ABI.
pub(super) fn android_kotlin_runtime_abi_binary_name() -> &'static str {
    "dev/destack/runtime/android/bridge/ProcessRuntimeAbi"
}

/// Return the Kotlin imports for one module.
fn android_kotlin_imports(module: &HostAbiModule) -> Vec<String> {
    let mut imports = Vec::new();

    if android_module_uses_type(module, &HostAbiType::HostRequestId) {
        imports.push("dev.destack.runtime.android.core.HostRequestId".to_string());
    }

    for named_type in &module.types {
        let type_name = android_kotlin_module_type_name(module, named_type.name);
        imports.push(format!(
            "dev.destack.runtime.android.module.{}.{}",
            module.name, type_name
        ));
    }

    imports
}

/// Return the Kotlin JNI method name for one ingress function.
pub(super) fn android_kotlin_native_name(ingress: &HostAbiFunction) -> String {
    format!(
        "native{}",
        android_pascal_case(&android_kotlin_method_name(ingress.name))
    )
}

/// Return the Kotlin method name for one ingress function.
pub(super) fn android_kotlin_method_name(name: &str) -> String {
    android_kotlin_parameter_name(name)
}

/// Return the RuntimeBridge method name for one generated Android request.
pub(super) fn android_runtime_bridge_method_name(
    module: &HostAbiModule,
    request: &HostAbiFunction,
) -> String {
    format!(
        "{}{}",
        android_kotlin_parameter_name(module.name),
        android_pascal_case(request.name)
    )
}

/// Render one Android Kotlin projected native type.
fn render_android_kotlin_native_type(ty: &HostAbiType) -> String {
    match ty {
        HostAbiType::U8 | HostAbiType::U16 | HostAbiType::I8 | HostAbiType::I16 => {
            "Int".to_string()
        }
        HostAbiType::U32 => "UInt".to_string(),
        HostAbiType::I32 => "Int".to_string(),
        HostAbiType::U64 => "Long".to_string(),
        HostAbiType::HostRequestId => "HostRequestId".to_string(),
        HostAbiType::Bool => "Boolean".to_string(),
        HostAbiType::F64 => "Double".to_string(),
        HostAbiType::StringRef => "String".to_string(),
        HostAbiType::OsPath => "String".to_string(),
        HostAbiType::StringSlice => "List<String>".to_string(),
        HostAbiType::HostSessionHandle => "HostSessionHandle".to_string(),
        HostAbiType::HostStatus => "Int".to_string(),
        HostAbiType::RuntimeStatus => "RuntimeAbiStatus".to_string(),
        HostAbiType::NativeArray(_) => {
            panic!("unsupported Android Kotlin array projection")
        }
        HostAbiType::NativeSlice(element) => {
            format!("List<{}>", render_android_kotlin_native_type(element))
        }
        HostAbiType::OutputPointer(_) => {
            panic!("unsupported Android Kotlin output-pointer projection")
        }
        HostAbiType::Optional(inner) => {
            format!("{}?", render_android_kotlin_native_type(inner))
        }
        HostAbiType::Named(name) => format!("Runtime{name}"),
    }
}

/// Return one Kotlin parameter label for one snake-case parameter.
pub(super) fn android_kotlin_parameter_name(name: &str) -> String {
    let mut segments = name.split('_');
    let Some(first) = segments.next() else {
        return String::new();
    };

    let mut label = first.to_string();
    for segment in segments {
        if segment == "id" {
            label.push_str("Id");
            continue;
        }
        if segment == "url" {
            label.push_str("Url");
            continue;
        }

        let mut characters = segment.chars();
        let Some(first_character) = characters.next() else {
            continue;
        };

        label.push(first_character.to_ascii_uppercase());
        label.extend(characters);
    }

    label
}
